### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by lopuhin** [catboost/catboost#1]
Currently Catboost does not seem to support sparse matrixes, while XGBoost does support them. Are there any plans to add sparse matrix support to Catboost?

**Comment by annaveronika** [comment]
We don't have support for sparse matrices yet. We don't have a concrete plan for adding it, but this is a great feature request, we probably add it later.

**Comment by bratao** [comment]
Version 0.14 contains this on the changelog:
"Impressive speedups for sparse datsets. Will depend on the dataset, but will be at least 2--3 times for sparse data."

Should we consider that catboost already support sparse matrixes?

**Comment by annaveronika** [comment]
There were two major speedups in latest releases, we plan for one more for CPU. Plus we have not yet supported sparse matrix as input data type. So no, it's not supported yet, but we are working on that.
You can try using catboost for sparse data now - if you have something like one-hot encoding, it should work fast enough. But you need to use dense matrix as input data.

**Comment by devforfu** [comment]
When I try to create a `cb.Pool` object using sparse data, I am getting the error:
```
trn_pool = cb.Pool(x_trn, y_trn)
# CatboostError: Invalid data type=<class 'scipy.sparse.csr.csr_matrix'>
```
Does it mean that sparse matrices are not supported yet?

**Comment by annaveronika** [comment]
> When I try to create a `cb.Pool` object using sparse data, I am getting the error:
> 
> ```
> trn_pool = cb.Pool(x_trn, y_trn)
> # CatboostError: Invalid data type=<class 'scipy.sparse.csr.csr_matrix'>
> ```
> 
> Does it mean that sparse matrices are not supported yet?

Yes

**Comment by kizill** [comment]
We are on a stage of internal code review(working on code for sparse column scoring) so it's a matter of weeks.

**Comment by annaveronika** [comment]
We are very happy to announce that this is finally implemented in catboost 0.17!

**Comment by belonesox** [comment]
>We are very happy to announce that this is finally implemented in catboost 0.17!

How this (sparse martix support) should work?  I just  («catboost==0.17.2»)  tried to make a Pool from csr_matrix, got
«_catboost.CatBoostError: only np.ndarray type is supported for cat_feature_data»

**Comment by andrey-khropov** [comment]
> > We are very happy to announce that this is finally implemented in catboost 0.17!
> 
> How this (sparse martix support) should work? I just («catboost==0.17.2») tried to make a Pool from csr_matrix, got
> «_catboost.CatBoostError: only np.ndarray type is supported for cat_feature_data»

Sparse matrices are currently not supported as arguments to FeaturesData. 
Supported ways to pass sparse data to Pool constructor or to fit/predict etc. functions is to pass as X argument any of [scipy sparse matrix classes](https://docs.scipy.org/doc/scipy/reference/sparse.html) (except for dia_matrix which does not make sense as a features matrix) or pandas.DataFrame with sparse columns (the latter case is needed if you have heterogeneous data types for different columns).

We'll update the documentation soon, right now you can look at examples in the tests:

https://github.com/catboost/catboost/blob/aa4d3ac41f62d1540db857ab0134519ec67aa118/catboost/python-package/ut/medium/test.py#L5562

https://github.com/catboost/catboost/blob/aa4d3ac41f62d1540db857ab0134519ec67aa118/catboost/python-package/ut/medium/test.py#L5676

**Comment by belonesox** [comment]
So right now,  categorial and numerical features should be in same sparse matrix of type 'f4'?
(Yes, I tried to create Pool with dense and sparse matrices for numerical and categorial features...)

**Comment by andrey-khropov** [comment]
> So right now, categorial and numerical features should be in same sparse matrix of type 'f4'?

Not necessarily 'f4', any type supported by scipy sparse matrices will work, but 'f4' will be optimal performance-wise, for categorical features it is necessary that these floating point values actually represent integers (i.e. have fractional part equal to 0), it is checked.

Alternatively, you can use pandas.DataFrame with sparse columns.

**Comment by temakahap** [comment]
Thanks to the sparse-matrix support!

Can you pls update documentation -  bacause in these documentation sparse-matrix support is not mentioned(https://catboost.ai/docs/concepts/python-reference_catboostclassifier_fit.html). And also it would be wonderful if there were instruction how to use categorical features in sparse's types.

Thank you!

**Comment by annaveronika** [comment]
Sure, the documentation update will be out this week.

**Comment by andrey-khropov** [comment]
Documentation has been updated with information about sparse data support.

**Comment by temakahap** [comment]
Hello!

I am trying to fit catboost classifier with sparse matrix'es and gpu type.
And i have this error:
CatBoostError: util/generic/maybe.h:15: TMaybe is empty

Code:
model.fit(train_bootstraped, predict_bootsraped, self.cat_features,
                          eval_set = (self.X_validation, self.y_validation))empty

Shapes and sums:
 print (train_bootstraped.shape, predict_bootsraped.shape, predict_bootsraped.sum()                     
            self.X_validation.shape, self.y_validation.shape)
(7467, 214) (7467,) 2489 (25143, 214) (25143,)

Stackoverflow can't have this error(
Can you pls give an advice how ti avoid this erros?

**Comment by annaveronika** [comment]
Sparse data is only supported for CPU right now. Sorry that the error is not clear, we'll fix it.

**Comment by annaveronika** [comment]
Sorry, previous comment is not fully correct. We support sparse data types on GPU (sparse features on GPU are treated like regular features, we'll add full sparse data support for GPU at some point later), I'm not sure why you have this exception, we'll look on this.

**Comment by annaveronika** [comment]
Here's an issue for that https://github.com/catboost/catboost/issues/1175
