### ISSUE TITLE
Installation issue in R cloud Linux machine

### ISSUE THREAD

**Issue by thanish** [catboost/catboost#100]
I have a linux virtual machine in my Azure cloud subscription with R-studio installed in it. I have been trying to install catboost for almost 6 hours and did not succeed. Below is the error I'm getting

> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/tmp/RtmpqBZGrr/devtools65f27efd800/catboost-catboost-8bcfbad/catboost/R-package'  \
  --library='/home/thanish/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘catboost’ ...
** libs
** arch - 
/tmp/RtmpqBZGrr/devtools65f27efd800/catboost-catboost-8bcfbad/catboost/R-package/src//../../../ya make -r
/bin/bash: /tmp/RtmpqBZGrr/devtools65f27efd800/catboost-catboost-8bcfbad/catboost/R-package/src//../../../ya: Permission denied
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 126
ERROR: compilation failed for package ‘catboost’
* removing ‘/home/thanish/R/x86_64-pc-linux-gnu-library/3.4/catboost’
Installation failed: Command failed (1)

I was getting permission errors so I logged into my machine as root as below 
sudo -s
then gave my password 

Once I was logged as the root I gave the read write and every single permission to the bin folder, bash file and also the tmp folder and all the subsequent folders in the tmp("tmp/RtmpqBZGrr/devtools65f27efd800/catboost-catboost-8bcfbad/catboost") and I ran the command again but still getting the same error. Can somebody help me.

**Comment by exprmntr** [comment]
Hello @thanish 

This "Permission denied" error most likely means lost executable flag of "ya" file. 

Can you run command `chmod +x /tmp/RtmpqBZGrr/devtools65f27efd800/catboost-catboost-8bcfbad/catboost/R-package/src//../../../ya` and try again?

**Comment by thanish** [comment]
Hi @exprmntr , I'm not able to see that folder in tmp. below is the screenshot of my tmp.Please help me out with this.

![image](https://user-images.githubusercontent.com/4056145/30176212-3dabab42-941f-11e7-954c-5679baa6b238.png)

**Comment by exprmntr** [comment]
Hi @thanish 

We have pushed a possible fix in the latest version, please try again
