### ISSUE TITLE
package compatible with java 12

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#1000]
is there a packaged jar that I can download that is compatible with java 12? Version 0.2.5 on mavencentral does not have this fix applied

**Comment by oldirtybasti** [comment]
is there any update on this issue?

**Comment by annaveronika** [comment]
We have not started working on that. We'll update the issue, when we have news.

**Comment by andrey-khropov** [comment]
Maven version 0.2.6 released today contains this fix.
