### ISSUE TITLE
Automatically defined Learning Rate for binary classification

### ISSUE THREAD

**Issue by Kim2212** [catboost/catboost#1001]
Problem: Learning Rate estimation formula
catboost version: 0.15.1
Operating System: 
CPU:
GPU:

Hi, can you please explain [this](https://github.com/catboost/catboost/blob/cea160f14a25657b0e0123b0fe93cb5e4df18deb/catboost/libs/train_lib/options_helper.cpp#L139) learning rate estimation formula? Are these `a, b, c, d` variables random?

**Comment by annaveronika** [comment]
These numbers are trained on a large collection of binary classification datasets.
We will probably write a post about that at some point.

**Comment by Kim2212** [comment]
Ok, thanks
