### ISSUE TITLE
DART implementation for Catboost

### ISSUE THREAD

**Issue by tataudat** [catboost/catboost#1006]
Problem:

DART booster, [Dropouts meet Multiple Additive Regression Trees](https://arxiv.org/abs/1505.01866), is quite useful, and with properly tuning can "generally" lead to better models (I'm actually quite skeptical about this claim).

This is a nice feature to have (already implemented in [xgboost](https://xgboost.readthedocs.io/en/latest/tutorials/dart.html) and [lightgbm](https://lightgbm.readthedocs.io/en/latest/Parameters.html) library), and the fact that catboost doesn't recently support it may drawback potential users from adopting catboost (example: me).

Is there any plan to implement/integrate DART for catboost in the future?

**Comment by annaveronika** [comment]
Do you have examples where it improves quality?

**Comment by annaveronika** [comment]
We don't plan to implement DART, because we don't see the profit from it. So closing the issue as won't fix. Please, if you have examples where this technique works for you and cannot be outperformed by changing other params, give us this example.
