### ISSUE TITLE
Unable to install catboost for python3.4 on fedora 23

### ISSUE THREAD

**Issue by iamprakashom** [catboost/catboost#101]
I am trying to install catboost for python 3.4 on fedora23. I tried by building from source, but first `make` step stuck with this message

![image](https://user-images.githubusercontent.com/4259587/30252231-e4128d20-968b-11e7-9a1f-bf2f69995f3a.png)

I am not able to use catboost with python3.4, as I am getting `TypeError: expected bytes, str found` error.

**Update**: I also tried building wheel package as mentioned [here](https://github.com/catboost/catboost/issues/10#issuecomment-316120871), but ended with same error message
![image](https://user-images.githubusercontent.com/4259587/30252287-46890ef6-968d-11e7-9f9b-becaf601bfb7.png)

**Comment by exprmntr** [comment]
Hello @iamprakashom 

Please show output of `ya -v make -v` + all other your options

**Comment by iamprakashom** [comment]
I am getting 
>bash: ya: command not found

error on terminal.

**Comment by exprmntr** [comment]
It should be `../../../ya` in your case (if you run this command from `python-package` folder)

**Comment by iamprakashom** [comment]
output of `ya -v make -v`
![image](https://user-images.githubusercontent.com/4259587/30289508-fa8ab0b4-9749-11e7-8f4a-3e1dd2174e9e.png)

**Comment by exprmntr** [comment]
Hi @iamprakashom 

We have pushed a possible fix in the latest version, please try again
