### ISSUE TITLE
Add Monotonic Constraints

### ISSUE THREAD

**Issue by ykropivn** [catboost/catboost#1011]
Due to business considerations often there is a need to put decreasing/increasing monotonicity constraints for the model. XGBoost has that feature and for some models this is an only reason we use XGBoost over Catboost for these cases. It would be very nice to have that feature in CatBoost.
Here is the reference how it works in XGBoost - https://xgboost.readthedocs.io/en/latest/tutorials/monotonic.html

**Comment by andrey-khropov** [comment]
This has already been implemented: https://github.com/catboost/catboost/issues/199. See monotone_constaints training parameter in the documentation.
