### ISSUE TITLE
Unable to set min_data_in_leaf for CatBoostRegressor

### ISSUE THREAD

**Issue by mavillan** [catboost/catboost#1012]
**Problem:** When I try to set the `min_data_in_leaf` parameter for the CatBoostRegressor like this:
```python
model_params = {'iterations': 300, 'learning_rate': 0.3,  'min_data_in_leaf': 10}
model = CatBoostRegressor(**model_params)
model.fit(train_data, verbose=False)
```
I get the following error: 
```
CatBoostError: catboost/libs/options/json_helper.h:223: Error: change of option min_data_in_leaf is unimplemented for task type CPU and was not default in previous run
```

Is this an expected response? If so, can you clarify why is this decision?. 

**catboost version:** 0.17.1
**Operating System:** OSX Mojave 10.14.6 
**CPU:** Intel Core I5

**Comment by annaveronika** [comment]
min_data_in_leaf is a parameter for training not symmetric trees. To use it you need to set tree growing strategy to other than Symmetric. Other growing policies are supported only on GPU now, we'll implement them on CPU at some point. But in most cases default growing strategy works best, so you can try to use it.

**Comment by annaveronika** [comment]
I hope this answers your quesiton! Let us know if you have other problems.
