### ISSUE TITLE
sum_models incorrectly works with multiclass models

### ISSUE THREAD

**Issue by LSinev** [catboost/catboost#1013]
catboost version: 0.17.3
Operating System: Windows
CPU

1. делаю несколько мультиклассовых моделей с одними настройками на разных фолдах
2. делаю sum_models по примеру, без излишеств
3. делаю .predict с `prediction_type='Probability'`
4. Получаю что-то двухклассовое, вместо ожидаемых, например, четырех (`prediction_type='Class'` дает предсказания 4 классов при этом).

Ожидания:
* если суммировали CatBoostClassifier, то и на выходе — CatBoostClassifier
* все одинаковые параметры должны быть выведены в функции репорта параметров суммированной модели (вряд ли от весов суммирования меняется метрика модели, предсказываемые классы, loss function и т. п.)
* `.classes_` параметр должен быть корректен, ведь, согласно документации, по нему можно понять последовательность классов в результирующем порядке предсказанных вероятностей.

Реальность:
[catboost_test_multiclass.zip](https://github.com/catboost/catboost/files/3659829/catboost_test_multiclass.zip)

**Comment by annaveronika** [comment]
Current status and plans:
1. We are working on fixing the number of classes when doing summation of MultiClass models
2. We are also working on writing correct classes_ for binary and multi classification problems
3.
This request:
все одинаковые параметры должны быть выведены в функции репорта параметров суммированной модели (вряд ли от весов суммирования меняется метрика модели, предсказываемые классы, loss function и т. п.)
we will not do.

**Comment by LSinev** [comment]
Thank you

**Comment by annaveronika** [comment]
The fix for number of classes is on github now and will be on pypi in the next catboost version.
