### ISSUE TITLE
No corresponding "cat_features_hashes" in exported json and cpp files

### ISSUE THREAD

**Issue by IreneZhou** [catboost/catboost#1015]
I'm trying to parse the exported json file, but compare to the python format model file,  the cat_features_hashes data is not provided, also the corresponding CatFeatureHash map is empty in the cpp file. I'm wondering if it can be computed alone independent of a model?

**Comment by annaveronika** [comment]
Sorry, I don't understand the problem. Does your C++ model not provide correct predictions? If so, could you provide a minimal reproducing example of this behavoir?

**Comment by kizill** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 
Please reopen if you still encounter this issue with the latest stable version.
Thank you!
