### ISSUE TITLE
feature request: Timestamp column list in Pool settings

### ISSUE THREAD

**Issue by LSinev** [catboost/catboost#1016]
Would be great to have new option in Pool. Just like cat_features list of numbers or column names.

**Comment by andrey-khropov** [comment]
> Would be great to have new option in Pool. Just like cat_features list of numbers or column names.

Why columns (plural)? Logically there could be only one Timestamp column.

**Comment by LSinev** [comment]
Well, if there is only one sorting column...

**Comment by andrey-khropov** [comment]
> Well, if there is only one sorting column...

I don't understand what you mean.

**Comment by LSinev** [comment]
Раз в реализации/задумке/концепции разработки сортировка доступна через указание только одной колонки, то множественного числа не требуется. Фичреквест состоит в указании этой колонки в параметрах Pool.

**Comment by LSinev** [comment]
Если у нас масса временных колонок [Дни, Часы, минуты, секунды], но указали [Дни, Часы, минуты], то в рамках секунд внутри минуты permutations допустимы. Но я же не знаю нюансов. Разработчикам виднее - одна колонка, значит одна.

**Comment by annaveronika** [comment]
This issue is a great opportunity for external contribution! Adding help wanted and good first issue labels.

**Comment by vroomzel** [comment]
Can this be fully implemented in the Python package or would this require modifying something on the C++ side?

**Comment by andrey-khropov** [comment]
Added this functionality since release 1.0.0.

**Comment by antipisa** [comment]
> Added this functionality since release 1.0.0.

Can you provide an example how to specify this?

**Comment by andrey-khropov** [comment]
> > Added this functionality since release 1.0.0.
> 
> @andrey-khropov Can you provide an example how to specify this?

Pretty straightforward, just provide `timestamp` in the `Pool` object constructor or call `set_timestamp` method of an existing `Pool` object. You can see examples in tests: https://github.com/catboost/catboost/blob/d9fa7efe41ee62a2e1a7742a74e4c2e08b28136a/catboost/python-package/ut/medium/test.py#L9878-L9914.

The documentation will be updated soon.
