### ISSUE TITLE
User Defined Metric Function ERROR

### ISSUE THREAD

**Issue by UCAS-BigBird** [catboost/catboost#1019]
Problem:
My own defined metric function can't work!
I have carefully go through the tutorial that You give me. Such a fantastic work!
But ,I have some questions about USER DEFINED METRIC FUNCTION

the first question is :

1 why handle the error_sum in this way?

            #error_sum += -w * (target[i] * approx[i] - np.log(1 + np.exp(approx[i])))
   
I check my book and find this formula is not like the standard logloss 

2 the second question is 

My own eval metric is 
Q   is a number between [2,4]

-1/N *  np.sum（Yi * log(Pi) x Q +(1-Yi)*log(1-Pi)）

the metric is familiar with the standard loss metric 'Logloss' ,but it put more attention to the right
sample.

So I follow my heart ,and make some changes to the tutorial part ,as is depicted in picture 1.

I got some error which shows np.nan   and I use the numpy to deal with this problem.
![1](https://user-images.githubusercontent.com/42146560/65895344-e6be0080-e3dd-11e9-8ddb-5c5e37264206.png)

But the error warns me I can't change the data type.

So how can I deal with it?

Much thanks

Operating System:windows10
CPU:r5 1400 AMD

**Comment by LyzhinIvan** [comment]
Hi, @UCAS-BigBird !
approx[i] != p[i], actually p[i] = sigmoid(approx[i]) = 1 / (1 + exp(-approx[i]))
Taking this into account, the expression from your first question can be deduced from standard log-loss.
And the correct expression for your second question looks like this: Q * target[i] * log(sigmoid(approx[i])) + (1 - target[i]) * (1 - log(sigmoid(approx[i]))).
If we do the same transformations as in the example, we get: Q * target[i] * approx[i] - log(1 + exp(approx[i])) * (1 + (Q - 1) * target[i])

**Comment by annaveronika** [comment]
Hope it has helped! Let us know if you have more questions!
