### ISSUE TITLE
catboost-0.1.1.exe crush on Windows 7 64-bit

### ISSUE THREAD

**Issue by MichaelMonashev** [catboost/catboost#102]
C:\Temp\catboost>catboost-0.1.1.exe

Usage: C:\Temp\catboost\catboost-0.1.1.exe MODE [MODE_OPTIONS]

Modes:
  fit     train model
  calc    calc model predictions
  fstr    calc model fstr

To get help for specific mode type 'C:\Temp\catboost\catboost-0.1.1.exe MODE -?'
To print program version type 'C:\Temp\catboost\catboost-0.1.1.exe --version'

C:\Temp\catboost>catboost-0.1.1.exe --version
Svn info:
    no svn info

Other info:
    Build by: exprmntr
    Top src dir: C:\Users\exprmntr\cb2\catboost\catboost
    Top build dir: C:\Users\exprmntr\.ya\build\build_root\7a6c70306561773265726730676d636f
    Hostname: EXPRMNTR547E
    Host information:

Microsoft Windows [Version 10.0.14393]

C:\Temp\catboost>catboost-0.1.1.exe fit -?
выдалось сообщение, что работа программы прекращена со следующими подробностями:
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	catboost-0.1.1.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	596cef30
  Имя модуля с ошибкой:	catboost-0.1.1.exe
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	596cef30
  Код исключения:	c0000096
  Смещение исключения:	00000000001030c3
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	fcf8
  Дополнительные сведения 2:	fcf854e3051f01f827a19b9207a0dc87
  Дополнительные сведения 3:	e3f8
  Дополнительные сведения 4:	e3f8cb78b9672c81527b2752893f3bd4

Ознакомьтесь с заявлением о конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
  D:\Windows\system32\ru-RU\erofflps.txt

Попытка запустить с параметром fit -f 1.txt также приводит к падению.

**Comment by annaveronika** [comment]
This is a very old version. Please try building from source. We'll update the binaries soon.

**Comment by MichaelMonashev** [comment]
Ok. I will wait for new binaries.

**Comment by annaveronika** [comment]
Our most recent release contains new binaries:
https://github.com/catboost/catboost/releases/tag/v0.2

**Comment by MichaelMonashev** [comment]
Спасибо!
