### ISSUE TITLE
Multiclass classifier error during model training

### ISSUE THREAD

**Issue by SeanBenner** [catboost/catboost#1022]
Problem: When trying to use CatBoostClassifier, I get this error message:
`_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/libs/lapack/linear_system.cpp:31: System of linear equations is not positive definite`

I am running the example code from https://catboost.ai/docs/concepts/python-usages-examples.html 

```
from catboost import Pool, CatBoostClassifier

train_data = [["summer", 1924, 44],
              ["summer", 1932, 37],
              ["winter", 1980, 37],
              ["summer", 2012, 204]]

eval_data = [["winter", 1996, 197],
             ["winter", 1968, 37],
             ["summer", 2002, 77],
             ["summer", 1948, 59]]

cat_features = [0]

train_label = ["France", "USA", "USA", "UK"]
eval_label = ["USA", "France", "USA", "UK"]


train_dataset = Pool(data=train_data,
                     label=train_label,
                     cat_features=cat_features)

eval_dataset = Pool(data=eval_data,
                    label=eval_label,
                    cat_features=cat_features)

# Initialize CatBoostClassifier
model = CatBoostClassifier(iterations=10,
                           learning_rate=1,
                           depth=2,
                           loss_function='MultiClass')
# Fit model
model.fit(train_dataset)
```

This issue only occurs with CPU (GPU works fine) and the issue doesn't occur if there is a NaN in the training labels, e.g.:

```
import numpy as np
train_label = ["France", "USA", np.nan, "UK"]
```

catboost version:  0.17.4
Operating System:  Windows 10
CPU:  Intel Xeon Silver 4114 CPU @ 2.20GHz
GPU: NVIDIA GeForce RTX 2080 Ti

**Comment by annaveronika** [comment]
For now, please downgrade to the previous version before multiclass speedup.
And could you please share the data with us?

**Comment by annaveronika** [comment]
The fix is now in code and will be on pypi in the next minor release.

**Comment by annaveronika** [comment]
the new version catboost 0.17.5 is on pypi now

**Comment by apokrif333** [comment]
Still not working. My dataset have only float64 columns. 
My catboost version is '0.17.5'.

I get error - 'catboost/private/libs/lapack/linear_system.cpp:31: System of linear equations is not positive definite'.

My code:
`from catboost import Pool, CatBoostClassifier, cv

cat_params = { 
    'iterations': 500,
    'random_state': 42,
    'loss_function': 'MultiClass',
    'eval_metric': 'TotalF1',
    'early_stopping_rounds': 30,
    'thread_count': -1
}
cat_model = CatBoostClassifier(**cat_params)

param_test ={
    'learning_rate': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5],
    'l2_leaf_reg': [0, 1e-3, 1e-2, 1e-1, 1, 2, 5, 7, 10, 50, 100],
    'depth': [2, 3, 4, 5, 6, 7],
    'border_count':[5, 10, 20, 32, 50],
}
randomized_search_result = cat_model.randomized_search(
    param_test,
    X=train,
    y=y_train,
    n_iter=500,
    cv=3,
    plot=True,
    refit=True,
    verbose=0
)`

**Comment by annaveronika** [comment]
Could you please create a new issue for that and provide a minimal reproducing example? It's hard to debug without an example.

**Comment by annaveronika** [comment]
And could you also describe in the issue, which system you are using, Windows or not.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Dear @apokrif333,
While we fix this issue, you may workaround it by changing zero in l2_leaf_reg to some small positive number, e,g, 1e-20.
The root cause is that, for small datasets, Hessian may be degenerate quite often.
E.P.

**Comment by chrico-bu-uab** [comment]
I get this error, even with l2_leaf_reg set to one. When I set the matrix W to the identity or set the off-diagonal elements to small enough values, it works fine.

There's probably something wrong with my math, but I am still surprised it errors out with regularization.

```
def get_W():
    W = np.array([[1. , 0. , 0. , 0. , 0. ],
                  [0. , 1. , 0.1, 0. , 0.1],
                  [0. , 0.1, 1. , 0.1, 0.1],
                  [0. , 0. , 0.1, 1. , 0.1],
                  [0. , 0.1, 0.1, 0.1, 1. ]])
    return W


def calc_grad_hess(approx, target, weight, W):
    target = int(target)

    exp_approx = np.exp(approx - np.max(approx))
    sum_exp_approx = np.sum(exp_approx)
    proba = exp_approx / sum_exp_approx

    grad = np.zeros_like(approx)
    hess = np.zeros((5, 5), dtype=float)

    for i in range(5):
        grad[i] = W[target, i] - proba[i]
        for j in range(5):
            hess[i, j] = proba[i] * (proba[j] - W[i, j])

    denom = -math.log(W[target].mean())
    grad = weight * grad / denom
    hess = weight * hess / denom

    return grad, hess


class ModifiedOrdinalLogLossObjective(object):
    def __init__(self):
        self.W = get_W()
        self.factor = np.mean(-1 / np.log(np.mean(self.W, axis=1)))

    def calc_ders_multi(self, approx, target, weight):
        grad, hess = calc_grad_hess(np.array(approx), target, weight / self.factor, self.W)
        return grad.tolist(), hess.tolist()

...

ordcat = CatBoostClassifier(random_state=SEED, verbose=True, cat_features=cat_features,
                            loss_function=ModifiedOrdinalLogLossObjective(),
                            eval_metric=ModifiedOrdinalLogLossMetric(),
                            classes_count=5,
                            auto_class_weights="Balanced",
                            depth=5,
                            l2_leaf_reg=1.0)
```
