### ISSUE TITLE
Memory error when pickling catboost model

### ISSUE THREAD

**Issue by pseudotensor** [catboost/catboost#1023]
when I do:

```
pickle.dumps(model, protocol=4)
```
catboost is in:
```
Current thread 0x00007f42dd052740 (most recent call first):
  File "lib/python3.6/site-packages/catboost/core.py", line 1261 in _serialize_model
  File "lib/python3.6/site-packages/catboost/core.py", line 1
```

and uses about 50GB of memory to try to save a simple model that should be very small (model fits into GPU using less than 1GB).  I run out of memory on a 64GB system with an error:

```
MemoryError
```

while it's in that catboost code.

Why is catboost using so much memory?

I want to make a pickled or serialized version of the model in memory, but I can also try save_model and read it back in as a binary object, just a hassle.

**Comment by pseudotensor** [comment]
Tried save_model, still issues.

GPU usage is only 6GB during fit:

```
Fri Oct  4 22:41:41 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    On   | 00000000:01:00.0  On |                  N/A |
| 72%   70C    P0   164W / 215W |   7318MiB /  7949MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2188      G   /usr/lib/xorg/Xorg                            55MiB |
|    0      2408      G   /usr/bin/gnome-shell                         150MiB |
|    0      3806      G   /usr/lib/xorg/Xorg                           558MiB |
|    0      3938      G   /usr/bin/gnome-shell                         412MiB |
|    0      7451      G   ...charm-community-2019.1.1/jre64/bin/java     8MiB |
|    0      8457      G   /usr/lib/firefox/firefox                       6MiB |
|    0     23917      G   ...uest-channel-token=12421119560007767455   292MiB |
|    0     28421      C   ...odel_1o3_fold_1o6-running(subprot=True)  5821MiB |
+-----------------------------------------------------------------------------+

```

GPU usage is high, and file saved after fit is 15GB:

```
-rw-------   1 jon jon  15G Oct  4 22:36 catboost_588508.bin
```
but when I read this as binary object and still try to pickle that binary object, I get OOM even though I had 50GB free once pickling started.

**Comment by david-waterworth** [comment]
If you pickle the training data how big is that? I assume when you pickle a trained model it holds a reference to the training data and most likely the residuals etc as well as the tree esemble.

**Comment by pseudotensor** [comment]
Hi, the data set is 600K x 600 columns and is pretty small.  I don't think the model includes the data, but you are saying it does.  Is there a way to avoid keeping the data with the model?

Also, note that the disk size you see there as 15GB is using save_model, which turns into about 3X overhead in memory when pickling due to the extra copies serialization needs.

But I still have no idea why 15GB is needed.

**Comment by david-waterworth** [comment]
yeah that seems a lot - 600K x 600 x 8 (bytes per double precision) is around 3GB so even if a reference to the data is held it seems rather large.

**Comment by pseudotensor** [comment]
I'm able to run on a machine with much more memory, except at the very end I have 12 of these models and I try to pickle them all together and end up with the same MemoryError.

**Comment by pseudotensor** [comment]
I have the original model + data that leads to the problem, how might I share?  The data is only 1GB - 1.4GB pickled file that includes the model + eval_set.

**Comment by pseudotensor** [comment]
Data: https://h2o-release.s3.amazonaws.com/h2o4gpu/catboostfe20d8.pickle
```
import pickle
file = "catboostfe20d8.pickle"
(model, kargs) = pickle.load(open(file, 'rb'))
model.set_params(min_child_samples=None, one_hot_max_size=4)
model.fit(**kargs)
file_new2 = "new2" + file
model.save_model(file_new2)
file_new = "new" + file
pickle.dump(model, open(file_new, 'wb'))
```

The script starts with a data set that is 1.1GB.  During fitting a reasonable amount of GPU memory is used.  However, once the model saving (catboost native) or pickle saving gets going, it uses 150GB (!) (i have 256GB system memory) to write ultimately what are 40GB files (both catboost native and pickle dump):
```
-rw-------     1 jon jon 40626863072 Oct 11 13:09 new2catboostfe20d8.pickle
-rw-------     1 jon jon 40627702597 Oct 11 13:17 newcatboostfe20d8.pickle
```

Both the memory usage (150GB peak) and final model size are crazy large.

I can also share the 40GB files, but they should be able to be generated.

**Comment by pseudotensor** [comment]
Overall, I guess I want to know what can be done.  Obviously I can choose a larger learning rate and smaller number of trees, but is there something else about this case that causes it to use 40GB of disk and 150GB of memory for a 1GB data set that behaved perfectly fine during training in terms of memory size etc.?

**Comment by kizill** [comment]
Hello!
I guess you have lot's of categorical features in your dataset (possibly with high cardinality).
When we are training models, we generate CTR tables for categorical features on-the-fly as they are needed, so it's totally normal, that GPU memory usage shows practically no correlation with resulting model size - we calculate all selected CTR tables __after__ training savinge them in the model object.
To reduce model size, in 0.24 we have finally implemented model size regularization - now we are penalyzing model splits that are using large CTR tables. `model_size_reg` is now turned on by default both on CPU and GPU and set to 0.5. You can play with this parameter, raising it to achieve smaller model size.
Also, you could reduce model size by limiting CTR complexity, setting `max_ctr_complexity` parameter - by default we are trying to greedily make combinations with up to 4 categorical features.
You can read about this params in the new [blog post on towardsdatascience](https://towardsdatascience.com/categorical-features-parameters-in-catboost-4ebd1326bee5) and in [tutorial covering categorical feature parameters](https://github.com/catboost/catboost/blob/master/catboost/tutorials/categorical_features/categorical_features_parameters.ipynb)

Closing this issue, feel free to reopen it if there is something left unclear 😄
Thank you!
