### ISSUE TITLE
missing recordCount in PMML from catboost

### ISSUE THREAD

**Issue by radescu** [catboost/catboost#1026]
Problem: 
The current PMML does not display the recordCount which could be used for estimating the Average and weighted average predicted probabilities when parsing the PMML model.
It would be useful to have this available.

**Comment by andrey-khropov** [comment]
This issue has been resolved by commit https://github.com/catboost/catboost/commit/acfb2997ccb7fe9a89f7a1a80f50fc097d4b5234 and will be included in the next release.
