### ISSUE TITLE
regression sample_weight question 

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#1031]
I'm slightly confused as to how the sample_weight parameter impacts a regression model. The documentation simple says "The weight of each object in the input data in the form of a one-dimensional array-like data." - what does this actually mean? Are you multiplying the i'th element of loss function by sample_weight[i] or dividing? Or are you adjusting the y[i]?

The reason I ask is the Gauss Markov theorem (Aiken 1935) states that the GLM model is minimised by weighting by 1/sigma^2 (the variance of the residuals) but I've found I get a better regression from catboost by setting sample_weight to an estimate of sigma^2 rather than 1/sigma^2

I'm trying to understand if this is the same theorm and catboost is taking the reciprocal or something different.

**Comment by annaveronika** [comment]
Sample weights are used as multipliers in summands of the loss function. They are indicated as w_i here: https://catboost.ai/docs/concepts/loss-functions-regression.html
