### ISSUE TITLE
Java SIGSEGV при большом батче

### ISSUE THREAD

**Issue by belya** [catboost/catboost#1032]
В java пакете catboost при использовании достаточно большого батча (300 документов, 15 признаков) после нескольких сотен итераций программа падает с SIGSEGV. Причиной оказался [код освобождения памяти](https://github.com/catboost/catboost/blob/b4a9d41d222d324f1009a7ea42430746ec2e4208/catboost/jvm-packages/catboost4j-prediction/src/native/ai_catboost_CatBoostJNIImpl.cpp#L597)
```cpp
...
    Y_SCOPE_EXIT(jenv, &catFeatureMatrixRowObjects, &catFeatureMatrixRows) {
        const auto size = catFeatureMatrixRows.size();
        for (size_t i = 0; i < size; ++i) {
            jenv->ReleaseIntArrayElements(
                catFeatureMatrixRowObjects[i],
                const_cast<jint*>(reinterpret_cast<const jint*>(catFeatureMatrixRows[i].data())),
                0);
        }
    };
...
```

Вот фрагмент дампа ошибки
```
Current thread (0x00007f815404b800):  JavaThread "main" [_thread_in_vm, id=22979, stack(0x00007f815e1e5000,0x00007f815e2e5000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Stack: [0x00007f815e1e5000,0x00007f815e2e5000],  sp=0x00007f815e2e1c60,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x68f21e]
C  [libcatboost4j-prediction3962745811698046472.so+0x35665e]  Java_ai_catboost_CatBoostJNIImpl_catBoostModelPredict__J_3_3F_3_3I_3D+0x65e

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  ai.catboost.CatBoostJNIImpl.catBoostModelPredict(J[[F[[I[D)Ljava/lang/String;+0
```

Если закомментировать этот участок, то SIGSEGV не возникает, но память, соответственно, не очищается. Хотелось бы как-то исправить эту ошибку, не вызывая мемори лик. 

Возможно ли узнать ваше мнение, почему такой баг при ReleaseIntArrayElements вообще может происходить? Заранее спасибо!

**Comment by andrey-khropov** [comment]
Commit https://github.com/catboost/catboost/commit/1ecf2e586cb0b66822d329dd23247f1227357e95 should fix this issue. 
New version with this fix will be published on Maven in two days.

**Comment by andrey-khropov** [comment]
Maven version 0.2.6 released today contains this fix.
