### ISSUE TITLE
boost_from_average not available from python api?

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#1033]
Using catboost 17.5 I'm unable to use the new `boost_from_average` param. Looking through core.py it doesn't appear to be defined for either `__init__` or `fit`. I can see where it's used in the CPP code, has it not been exposed via the python api yet?

Edit: the following works

```
estimator = catboost.CatBoostRegressor(
    boosting_type='Plain',
    objective='RMSE',
    eval_metric='RMSE',
    task_type='GPU',
    metric_period=100,
    l2_leaf_reg=95,
    learning_rate=0.03,
    max_depth=9,
    n_estimators=2600,
    #boost_from_average=True
    )
estimator.set_params(boost_from_average=True)
estimator.fit(X,y,sample_weight=None)
```

It looks like `boost_from_average` has been omitted from `__init__`?

Edit2: and because of this using `cross_validate` from `sklearn` fails, i.e.

```
groups=None
splitter=KFold(n_splits=5)
scorer={'score':make_scorer(mean_squared_error, greater_is_better=True)}

scores = cross_validate(
    estimator, 
    X,
    y, 
    groups=groups, 
    cv=splitter, 
    scoring=scorer, 
    return_train_score=True,
    n_jobs=1,
    error_score='raise'
    )
scores
```

Reason is sklearn attempts to construct a new CatBoostRegressor() instance passing to __init__ the params from the `estimator` instance passed in to `cross_validate`. Hence since `set_params` accepts `boost_from_average` as **kwargs but __init__ doesn't cross_validate fails.

**Comment by annaveronika** [comment]
You can use CatBoost cv method for now, we'll add parameter to Regressor and Classifier in the next release.

**Comment by annaveronika** [comment]
This is fixed now in code and will be out in the next release! Thank you very much for reporting this!
