### ISSUE TITLE
CatBoost 0.17.3 Python GPU training slower on smaller datasets

### ISSUE THREAD

**Issue by heipei** [catboost/catboost#1034]
catboost version: 0.17.3
Operating System: Arch Linux
CPU: Core i5 6400
GPU: RTX 2070

I'm not sure if this is a bug or to be expected, but catboost takes **longer** to train on smaller datasets on the GPU than it does on bigger datasets. I'm running training with between 20k and 100k training samples, and the big batches always take ~ a minute whereas the small batches take 3 minutes and more. Not sure how to debug or what to make of that.

My data has ~ 90 features with around 10 categorical features. I'm using the CatBoostClassifier with 2000 iterations and tree depth of 8.

**Comment by annaveronika** [comment]
This is expected behavior. Datasets with <= 50k samples use Ordered boosting by default, and datasets with more samples use Plain boosting by default. This is because of quality reasons - for small datasets Ordered gives better quality. At the same time Ordered boosting is more time consuming.

**Comment by annaveronika** [comment]
I hope this helps! Let us know if you still have questions.

**Comment by heipei** [comment]
Thanks Anna Veronika, that makes sense and now I feel stupid for not realising that. Just wanted to say I absolutely love working with catboost, keep up the good work!
