### ISSUE TITLE
Catboost error when running model.fit

### ISSUE THREAD

**Issue by Chuan1997** [catboost/catboost#1035]
Problem: problem occured when running model.fit()
catboost version: 0.17.2
Operating System:Windows 7

The code is presented as follow:
train_data = pd.read_csv('……/data/train.csv')
target_data = pd.read_csv('……/data/train_target.csv')
test_data = pd.read_csv('……/data/test.csv')
categorical_features_indices=np.where(X.dtypes != np.float)[0]
X=train_data
y=target_data

X_train, X_validation, y_train, y_validation=train_test_split(X,y,train_size=0.75,random_state=2019)
X_test=test_data
best_params={'iterations':500,'learning_rate':0.1,'eval_metric':'AUC','random_seed':42,'logging_level':'Silent','use_best_model':True}
train_pool=Pool(X_train,y_train,cat_features=categorical_features_indices)
valid_pool=Pool(X_validation,y_validation,cat_features=categorical_features_indices)
best_model=CatBoostClassifier(**best_params)
best_model.fit(train_pool,eval_set=valid_pool,plot=True)

Then an error occured:
CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/libs/target/target_converter.cpp:64: Unknown class name: "2708"

**Comment by annaveronika** [comment]
Looks like the eval set has a sample with class name 2708 which is not present in train dataset.

**Comment by annaveronika** [comment]
I hope it helps, let us know if you still have questions!
