### ISSUE TITLE
Question about max_pairs options in Ranking Mode

### ISSUE THREAD

**Issue by bduclaux** [catboost/catboost#1039]
Hello,

Could you describe the pair generation strategy when max_pairs is used ?
Let's assume we have inside a group the following labels:
3 (10 records)
2 (100 records
1 (1000 records)

Will Catboost start by generating pairs between labels 3 and 2, then 3 vs 1, then 2 vs 1 ? How ?
Is there random sampling instead ? In this example, this might lead to a very poor pair set.

Thanks for your help,
Best

**Comment by annaveronika** [comment]
We'll generate a random subset of all possible pairs that can be generated from this data.
Here is the code for pairs generation: https://github.com/catboost/catboost/blob/master/catboost/private/libs/pairs/util.cpp

**Comment by bduclaux** [comment]
Thanks. Very clear.
In my case,  I have a lot of distinct ranking labels, and many records, so huge number of pairs, so I might get better metrics if I pass specific pairs to the algorithm. 
Catboost will spend its time learning the important differences, instead of random pairs for which the ranking accuracy is not correct. Is my understanding correct ?

**Comment by annaveronika** [comment]
CatBoost will maximize the probability of classifying all pairs correctly. Each pair in this case will be equally important. If some pairs are more important than others, you can use pair weights.

**Comment by annaveronika** [comment]
I hope it helps! Let us know if you have more questions!

**Comment by github-shamada** [comment]
@annaveronika 

Hello, thank you for providing the great tool.
BTW, when using max_pairs, the following error occurs.
"Cannot generate pairs consistently - different metrics have different numberof max pairs"

Could you please let me know if there is anything I can do for that.
The version of catboost is 1.2.7.

Problem reproducibility code excerpt:
~~~python
    oModel = CatBoostRanker(
        iterations=100,
        learning_rate=0.1,
        depth=10,
        l2_leaf_reg=3,
        loss_function="PairLogit:max_pairs=50",
        eval_metric="PairAccuracy:max_pairs=50",
        random_seed=123,
        task_type="CPU" if bNoGPU else "GPU",
        verbose=5 if g_bLogPrime else 0,
        early_stopping_rounds=nMaxPatience if nMaxPatience > 0 else None,
    )
    oModel.fit(oPool, eval_set=oPool)

Traceback (most recent call last):
  File "/u/work0/shamada/bondstar/bondstarml/bondstarml.py", line 603, in <module>
    bondstarml(
  File "/u/work0/shamada/bondstar/bondstarml/bondstarml.py", line 495, in bondstarml
    oModel.fit(oPool, eval_set=oPool)  # tuning
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamada/miniconda3/envs/py311a/lib/python3.11/site-packages/catboost/core.py", line 6283, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, pairs, graph,
  File "/home/shamada/miniconda3/envs/py311a/lib/python3.11/site-packages/catboost/core.py", line 2410, in _fit
    self._train(
  File "/home/shamada/miniconda3/envs/py311a/lib/python3.11/site-packages/catboost/core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5017, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5066, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/private/libs/target/data_providers.cpp:451: Cannot generate pairs consistently - different metrics have different numberof max pairs
~~~
