### ISSUE TITLE
Still Having Issues Installing Catboost in R

### ISSUE THREAD

**Issue by BenjaminLott** [catboost/catboost#104]
Hello!

So I'm still having some issues installing Catboost in R.  I've tried following the advice of others but I'm still not making any progress. _I appreciate everyone's work towards making this library_, I've heard great things about it and I'm hopeful that I can use it in the future.

**What I'm working with:**
- Windows 7
- R 3.4.1
- Up to date R Studio
- Python 2.7, 3.5, 3.6 all 64 bit and all added to PATH
- VC++ 2015.3 v140 toolset for desktop (x86,x64)
- VC++ 2017 v141 toolset (x86,x64)
- Visual Studio 2015 & 2017 (x64)

Prior to this step, I downloaded the whole library from github manually (https://github.com/catboost/catboost) and I extracted the zip file into a folder in my computer's location 'C:\Program Files\R\R-3.4.1\library'

**Console: Code & Output (Error Read)**
![image](https://user-images.githubusercontent.com/19614725/30483799-367ddeda-99f6-11e7-9d14-ae608831158f.png)
![image](https://user-images.githubusercontent.com/19614725/30483824-52f439a6-99f6-11e7-9a25-aa5e13e146a7.png)

I think that the issue comes with
```
* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Program Files/R/R-3.4.1/library/catboost-master/catboost-master/catboost/R-package/src/../../../ya.bat make -r -o ../../..
make: /cygdrive/c/Program: Command not found
make: *** [all] Error 127
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Program Files/R/R-3.4.1/library/catboost'
Error: Command failed (1)
```

Any ideas how to move forward?

Thank you in advance for your help and guidance! :)

**Comment by exprmntr** [comment]
Hi @BenjaminLott 

Try to use another directory for installation, without spaces in path (like "Program Files" here)

**Comment by BenjaminLott** [comment]
Hi exprmntr,

Thank you for your help!

> Try to use another directory for installation, without spaces in path (like "Program Files" here)

I attempted what you said and put it in my Documents folder, however, now I am receiving a different error message.
![image](https://user-images.githubusercontent.com/19614725/30545255-15a152f6-9c57-11e7-8c2d-31d8b95816d4.png)

I know from another post in that it means my computer isn't reading VS 2015 C++ compiler, which is rather confusing to me because I have VS C++ Build Tools, Visual Studio 2015 and Visual Studio 2017
![image](https://user-images.githubusercontent.com/19614725/30545903-0bc6c75a-9c59-11e7-8b1f-7dec15f70d2f.png)

 and I added the location to my path environment. Any ideas on how to move forward?

**Comment by BenjaminLott** [comment]
Anyone else having similar problems?

**Comment by sab** [comment]
DEVTOOLS-3924 (internal issue id)

**Comment by annaveronika** [comment]
We could not solve your problem. As some people have problems with R package installation, we decided to publish compiled versions of the package. The progress will be reported in issue https://github.com/catboost/catboost/issues/63.
For now I could only suggest to try again or to use python or command line utility...
