### ISSUE TITLE
get_object_importance top_size bug

### ISSUE THREAD

**Issue by ibuda** [catboost/catboost#1045]
Problem: get_object_importance returns fewer objects then top_size parameter
catboost version: 0.18
Operating System: Ubuntu 19.10
CPU: Intel® Core™ i5-7400 CPU @ 3.00GHz × 4 

The problem is that when you input the parameter top_size into the `get_object_importance()` method, the size of indices and scores is much less than the `top_size` parameter, even though more objects are available.

#### How to reproduce
In  [object_importance_tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/model_analysis/object_importance_tutorial.ipynb) notebook, cell with `get_object_importance`, try to add `top_size` parameter. For example:
```
indices, scores = cb.get_object_importance(
    validation_pool_sampled,
    train_pool_noisy,
    top_size = 100,
    importance_values_sign='Positive' 
)
```
this will give you a list of size 61, i.e. `len(indices) = 61`. When using `top_size=50` you get a list of size 19.

As I understand from the [documentation](https://catboost.ai/docs/concepts/python-reference_catboost_get_object_importance.html), the size of the above lists should be top_size.

**Comment by annaveronika** [comment]
Thank you very much for the issue and for the fix! It will be out on pypi in the next minor release 0.18.1.
