### ISSUE TITLE
Catboost in write-protected directory

### ISSUE THREAD

**Issue by waniz** [catboost/catboost#1051]
Problem:
catboost version: 0.18
Operating System: Linux Mint 19
CPU: i7-6700

Catboost writes temporary files with no respect to the parameter allow_writing_files.

Description:
Catboost installed in Anaconda (only root can write, all can read)
Module (let say it`s name is DS) imports Catboost and installed in Anaconda too.

I import class `Train` from module DS.
Module DS imports Catboost and runs the training process.
Catboost returns an error with no respect to the parameter `allow_writing_files` .

`ERROR - (Permission denied) util/system/file.cpp:620: can't open "cat_feature_index.24c6c761-84a7cf23-22da8e2e-db1b9a95.tmp" with mode CreateAlways|WrOnly|Seq (0x00000034)`

If I set up the parameter `train_dir` - Catboost creates this folder and returns the same error as described.

Solution: no error after `sudo chmod -R 775` to Anaconda directory (but this is a workaround)

Structure:
.../anaconda/../site-packages: (read all, write root only)
       - catboost 0.18
       - ds

python pseudocode:
`
from ds import Train

train = Train()  ->  here Catboost is imported and run
`

**Comment by annaveronika** [comment]
Thanks a lot for the report! We'll look into this.

**Comment by annaveronika** [comment]
This is fixed now in code and will be out in the next release this week. Thank you very much for the report!
