### ISSUE TITLE
An error being caused while importing catboost, probably because of SELinux

### ISSUE THREAD

**Issue by ritiztambi** [catboost/catboost#1052]
**Problem:** File "/app/python/dev/sensei_model.py", line 14, in <module>
           from catboost import CatBoostClassifier
          File "/catboost/catboost/python-package/catboost/__init__.py", line 1, in <module>
           from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models, _have_equal_features  # noqa
         File "/catboost/catboost/python-package/catboost/core.py", line 62, in <module>
            _catboost = get_catboost_bin_module()
          File "/catboost/catboost/python-package/catboost/core.py", line 58, in get_catboost_bin_module
          from . import _catboost
        ImportError: /catboost/catboost/python-package/catboost/_catboost.so: cannot restore segment prot after reloc: Permission denied

**catboost version:**
**Operating System:** Linux Ubuntu 16.04
**CPU:** 
**# GPU:** No

**Comment by kizill** [comment]
We don't have any keys on how to reproduce this issue in year 2021, so closing it 😞 
But if someone have problems like this - please reopen and help us to reproduce and thus to fix 🐱
