### ISSUE TITLE
Error from system

### ISSUE THREAD

**Issue by trancuuquoc** [catboost/catboost#1054]
Problem: Cannot install catboost 0.18, even when I download and install from my local directory using GIT.
Error: Failed to install 'unknown package' from URL:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\TRANCU~1\AppData\Local\Temp\RtmpaIJdmg\file2307e193738.tgz" -C "C:/Users/TRANCU~1/AppData/Local/Temp/RtmpaIJdmg/remotes2301e7e4b94"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\TRANCU~1\AppData\Local\Temp\RtmpaIJdmg\file2307e193738.tgz"' had status 1

Info from system: The package is not for windows 64 bit.
??!?!?!

catboost version: 0.18
Operating System: Windows 10 Pro x64
CPU: Intel Core i7 -7700HQ
# GPU: Nvidia Quadro 1200

**Comment by annaveronika** [comment]
Can you try installation with this instructions:
https://catboost.ai/docs/installation/r-installation-binary-installation.html

**Comment by dbakshee** [comment]
> The package is not for windows 64 bit.

This indicates a conflict with 32-bit tools. [This](https://github.com/catboost/catboost/issues/538#issuecomment-442061952) discussion may be helpful to resolve it
