### ISSUE TITLE
CatBoost 0.18.1 still lists enum34 as a dependency on pypi

### ISSUE THREAD

**Issue by tomzx** [catboost/catboost#1056]
I've recently opened https://github.com/catboost/catboost/pull/1047 in order to fix an issue where `enum34` would be installed even if you had python >= 3.5. After v0.18.1 was released, I tried to install it but was surprised to find that it still installed `enum34` (this is using [poetry](https://poetry.eustace.io/).

Upon trying to find the cause of the problem, I discovered that pypi still lists `enum34` under its `requires_dist` section (see https://pypi.org/pypi/catboost/0.18.1/json). Normally I would have expected it to show something like `"enum34; python_version < \"3.4\""` (e.g., https://pypi.org/pypi/typing-extensions/3.7.4.1/json), but it currently shows as `enum34`. I am not sure if this is a build process error on catboost's side or it is an issue on pypi's side.

I've also tried installing catboost using `pip catboost==0.18.1` and it appears to install properly without `enum34`.

I'm asking here first (I will then ask poetry if it is inconclusive) as it is slightly odd that pypi is not listing the right `requires_dist` value. I do not know how you currently release your packages to PyPI. Is the code available in the repository? I'd like to help fix this issue if it is on catboost's side.

Thanks!

**Comment by dbakshee** [comment]
Hi @tomzx, thank you very much for your comprehensive explanation of the problem. I checked that the metadata of the 0.18.1 wheel files is correct. That is, enum34 is required by cp27 wheels and is not required by cp3* wheels. However, the json file that poetry likely relies upon, does list the enum34 as an unconditional requirement for the package. This may be a result of incorrect submission sequence from our side or improper logic of pypi when creating the json. We will fix the metadata with environment markers and hope it fix the json too.
