### ISSUE TITLE
Failed to install 'catboost' from GitHub

### ISSUE THREAD

**Issue by trancuuquoc** [catboost/catboost#1057]
Problem: Failed to install 'catboost' from GitHub
catboost version: 0.18.1
Operating System: Windows 10 Pro x64
CPU: Core i7-7700HQ
# GPU: Nvidia Quadro 1200
I have this problem of installation:

> library('devtools')
Loading required package: usethis

> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
catboost-catboost-e11d4ab/catboost/benchmarks/model_evaluation_speed/LightGBM_model.txt: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'catboost' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\TRANCU~1\AppData\Local\Temp\RtmpQhcZLD\fileffc3418251f.tar.gz" -C "C:/Users/TRANCU~1/AppData/Local/Temp/RtmpQhcZLD/remotesffc2d601721"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\TRANCU~1\AppData\Local\Temp\RtmpQhcZLD\fileffc3418251f.tar.gz"' had status 1
>

**Comment by andrey-khropov** [comment]
This has been fixed a long time ago.
