### ISSUE TITLE
CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/private/libs/target/target_converter.cpp:64: Unknown class name: "24.0"

### ISSUE THREAD

**Issue by tomdur21** [catboost/catboost#1058]
Problem:  CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/private/libs/target/target_converter.cpp:64: Unknown class name: "24.0"
catboost version: 0.17.5
Operating System: Windows 10 Pro
CPU: i7 2.8Ghz
# GPU: None

**Comment by annaveronika** [comment]
Maybe your validation dataset has a class "24.0" that has not been present in train dataset?

**Comment by annaveronika** [comment]
I hope, the previous comment explains the problem. If you still have a problem, please write in comments, we'll reopen the issue.
