### ISSUE TITLE
Cannot install Catboost in Zbook Studio Workstation

### ISSUE THREAD

**Issue by trancuuquoc** [catboost/catboost#1059]
Problem: Cannot install Catboost in Zbook Studio Workstation G4
catboost version: Any
Operating System: Windows 10 Pro
CPU: 7600HQ
# GPU: Quadro 1200
Hello,
I try to install catboost for R in my laptop for n times, even with new installation of my windows by reset my system and reinstall R immediately after windows installation, but in vain.
I have a Zbook G4 mobile studio workstation with Nvidia Quadro 1200 card.
Thank you very much for your support to solve this problem.
Have a nice day

**Comment by dbakshee** [comment]
Hi @trancuuquoc , could you give a little bit more details? What commands do you run for install? What errors do you observe?

**Comment by kizill** [comment]
Closing as inactive duplicate of #1054 and #1057.
