### ISSUE TITLE
Implement relevant algorithms from NGBoost

### ISSUE THREAD

**Issue by rgeronimi** [catboost/catboost#1062]
Problem: This is not a problem. This is an enhancement tracking ticket.

Objectives:

(1) Inventory the new algorithm alternatives used by NGBoost
https://stanfordmlgroup.github.io/projects/ngboost/
https://github.com/stanfordmlgroup/ngboost

(2) Implement the ones that are relevant for CatBoost

**Comment by StatMixedML** [comment]
Maybe that is of interest to you: I am currently working on an extension of CatBoost to probabilistic forecasting

https://github.com/StatMixedML/CatBoostLSS

It creates probabilistic forecasts from which prediction intervals and quantiles of interest can be derived. So it is very similar to ngboost, however, with all the power of CatBoost. It is still developmental and I will share the code soon.

**Comment by annaveronika** [comment]
Thanks a lot for the issue and for the suggestion! This is an important feature, that is frequently asked by our users. We'll add one of the methods, I will leave a single issue for that, https://github.com/catboost/catboost/issues/1148, closing this one as a duplicate. Please follow the progress there!
