### ISSUE TITLE
loss_function usage does not permit several loss_functions

### ISSUE THREAD

**Issue by antipisa** [catboost/catboost#1071]
Can you please give an example of how to use the loss_function (specified in https://catboost.ai/docs/concepts/loss-functions-regression.html) parameter together with its options? For instance, R2, FairLoss and Quantile do not work:

```
from catboost import CatBoostRegressor, Pool

params = {"boosting_type":"Ordered", 
"num_boost_round":100,
"loss_function":"FairLoss:weights=True",
"eval_metric":"FairLoss"}

model = CatBoostRegressor(**params)
model.fit(Pool(X,label=y))

CatBoostError: Invalid loss_function:"FairLoss:weights=True": for regressor use RMSE, MAE, Quantile, LogLinQuantile, Poisson, MAPE, Lq or custom objective object
```

I am using version 0.17.5.

**Comment by annaveronika** [comment]
There are several problems.
1. R2 and FairLoss cannot be used as loss_function, you only can use RMSE, MAE, Quantile, LogLinQuantile, Poisson, MAPE, Lq or custom objective for the regressor.
2. loss_function parameter does not support use_weights parameter, this parameter is always true for the optimized loss.

**Comment by annaveronika** [comment]
https://catboost.ai/docs/concepts/loss-functions-regression.html

Here you can find, which losses are allowed for optimization, it's the second column. Only those ones can be used in loss_function parameter.

**Comment by annaveronika** [comment]
I hope, it answers your question! Let us know if you have other questions.
