### ISSUE TITLE
catboost/private/libs/target/target_converter.cpp:48: Missing values like "nan" are not supported for target

### ISSUE THREAD

**Issue by jacobfrey36** [catboost/catboost#1073]
Problem:catboost/private/libs/target/target_converter.cpp:48: Missing values like "nan" are not supported for target

![9549D1F37F68D561E1D0B6B2E3D75FE6](https://user-images.githubusercontent.com/51236349/68834976-ff664980-06f1-11ea-9c85-6c11ca3262d8.jpg)
![CBE85D53109D51CA44307CDD49478312](https://user-images.githubusercontent.com/51236349/68834984-02f9d080-06f2-11ea-9d59-814dd2c1af8e.jpg)
my data doesn't have missing values,where I make mistake.
catboost version:
Operating System:mac
CPU:i9
# GPU:

**Comment by annaveronika** [comment]
This is not an error, this is expected behavoir. Since this is a supervised learning library, we are not supporting nan values in target.

**Comment by LyzhinIvan** [comment]
Hello, @jacobfrey36 ! I think you missed iloc in label extracting for valid_data.

**Comment by annaveronika** [comment]
Ok, closing the issue, let us know if you'll have more problems.
