### ISSUE TITLE
Monotonic constraints for Categorical Features

### ISSUE THREAD

**Issue by arose13** [catboost/catboost#1074]
There doesn't appear to be a way to enforce monotonicity (in my case, positive effects only) for categorical features. Is this true or is there a workaround I am unaware of?

**Comment by annaveronika** [comment]
Monotonicity by its definition works for numeric features only. Monotonicity means: if the value of the feature increases, then the value of prediction must not decrease. There is no increasing of feature value for categorical features.

**Comment by arose13** [comment]
I understand that. I suppose I figured internally the categorical features were represented as 0 if false and 1 is true. This 0 -> 1 I was hoping would always be a positive number in the change of the prediction value.

**Comment by annaveronika** [comment]
> I suppose I figured internally the categorical features were represented as 0 if false and 1 is true.

Categorical features don't have to be binary, and if the feature is binary, you can use it in binary format and have monotonic constraints on it.

For not binary features catboost calculates a set of numerical features based on a categorical feature and a set of numerical features based on categorical feature combinations.

**Comment by annaveronika** [comment]
I hope it answers your question. Let us know if you have more questions! Closing the issue.
