### ISSUE TITLE
standalone_evaluator

### ISSUE THREAD

**Issue by dmitrySorokin** [catboost/catboost#1075]
Problem: can not build https://github.com/catboost/catboost/tree/master/catboost/libs/standalone_evaluator example
catboost version: master
Operating System: macos

It seems that you renamed TObliviousTrees to TModelTrees and moved guid.fbs to helpers/

**Comment by dmitrySorokin** [comment]
I can propose a merge request

**Comment by kizill** [comment]
> I can propose a merge request
It would be nice, thanks!

**Comment by dmitrySorokin** [comment]
https://github.com/catboost/catboost/pull/1083

**Comment by annaveronika** [comment]
This is merged now, closing the issue. Thanks a lot @dmitrySorokin for your conrtibution!
