### ISSUE TITLE
Does catboost support data of libsvm format?

### ISSUE THREAD

**Issue by janelu9** [catboost/catboost#1077]

**Comment by annaveronika** [comment]
Yes, it is supported, we'll add it to the docs soon.

**Comment by janelu9** [comment]
how to use it?
train_data = Pool('libsvm')?

**Comment by janelu9** [comment]
> Yes, it is supported, we'll add it to the docs soon.

but,how to import the libsvm noiw?

**Comment by andrey-khropov** [comment]
> > Yes, it is supported, we'll add it to the docs soon.
> 
> but,how to import the libsvm now?

Which API do you use? Python, R, CLI?

1) All APIs can load data from dataset files in libsvm format, CatBoost uses special 'scheme' syntax for this - you need to prefix path to file with 'libsvm://'.

Like this (example for python API):

```py

import catboost as cb

pool = cb.Pool('libsvm:///home/user/datasets/my_dataset/file_in_libsvm_format')

```

2) If you you use python API you can also load dataset in libsvm format as scipy.sparse.csr_matrix for features plus labels using scikit-learn's [load_svmlight_file](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html) and then pass this data to catboost.Pool's constructor like this:

```py
from sklearn.datasets import load_svmlight_file
import catboost as cb

X, y = load_svmlight_file('/home/user/datasets/my_dataset/file_in_libsvm_format')
pool = cb.Pool(X, y)
```

If you do not perform additional transformations on feature data besides catboost.Pool creation then loading directly from file using the first method should be faster.

**Comment by janelu9** [comment]
> > > Yes, it is supported, we'll add it to the docs soon.
> > 
> > 
> > but,how to import the libsvm now?
> 
> Which API do you use? Python, R, CLI?
> 
> 1. All APIs can load data from dataset files in libsvm format, CatBoost uses special 'scheme' syntax for this - you need to prefix path to the file with 'libsvm://'.
> 
> Like this (example for python API):
> 
> ```python
> import catboost as cb
> 
> pool = cb.Pool('libsvm:///home/user/datasets/my_dataset/file_in_libsvm_format')
> ```
> 
> 1. If you use python API you can also load dataset in libsvm format as scipy.sparse.csr_matrix for features plus labels using scikit-learn's [load_svmlight_file](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html) and then pass this data to catboost.Pool's constructor like this:
> 
> ```python
> from sklearn.datasets import load_svmlight_file
> import catboost as cb
> 
> X, y = load_svmlight_file('/home/user/datasets/my_dataset/file_in_libsvm_format')
> pool = cb.Pool(X, y)
> ```
> 
> If you do not perform additional transformations on feature data besides catboost.Pool creation then loading directly from file using the first method should be faster.


what the format of libsvm it supports?

my data's first line is :
0 0:242 1:213 2:48 3:29 4:4 5:1817 6:798 7:5 8:760 9:810 10:512 11:859 12:4 13:204 14:371 15:28 16:299 17:4 18:1470 19:1346 20:113 21:32 22:67 23:70 24:1524 25:1470 26:12049 27:4 28:70 29:7 30:86 31:113 32:5 33:67 34:70 35:1524 36:1470 37:12049 38:4 39:75 40:358 41:478 42:231 43:4 44:478 45:231 46:168 47:89 48:28 49:10 50:48 51:22 52:16 53:1306 54:226 55:4 56:131 57:7 58:218 59:11 60:627 61:7 62:643 63:817 64:15 65:47 66:356 67:65 68:259 69:19 70:259 71:122 72:100 73:478 74:231 75:168 76:89 77:28 78:165 79:10 80:16 81:38 82:8 83:5 84:79 85:11 86:10 87:408 88:75 89:512 90:767 91:111 92:15 93:22 94:49 95:1349 96:159 97:165 98:16 99:32 100:11 101:560 102:242 103:1042 104:242 105:213 106:15 107:12043 108:17963 109:17963 110:17963 111:17963 112:5 113:355 114:53 115:88 116:5 117:53 118:230 119:10 120:277 121:420 122:961 123:1983 124:1260 125:12043

but
CatBoostError: Error in libsvm data. Line 1: Column 1 (value = "0:242"): catboost/libs/data/libsvm_loader.cpp:174: Feature index must be a positive integer

**Comment by janelu9** [comment]
I know ,it starts from 1

**Comment by janelu9** [comment]
but how can I make the model train all the features as cat_features?

**Comment by andrey-khropov** [comment]
> how can I make the model train all the features as cat_features when I use Pool?

libsvm format does not support specifying feature type originally (all features are considered numeric), but CatBoost allows to specify this information using [column description file](https://catboost.ai/docs/concepts/input-data_column-descfile.html) as with usual CatBoost dataset dsv format. 

You have to specify 'column 0' as 'Label' and the subsequent column ids will correspond to feature ids in libsvm format (both indices will start from 1).
Specifying feature names (called ``feature IDs`` in column desciption format documentation) is also supported.

For categorical features values in libsvm file can be integers and strings (without spaces to avoid breaking libsvm format)

For example if you have dataset in libsvm format with numeric features 1, 3, 4 and categorical features 2, 5, like that:

```
0 1:0.12 2:Small 5:1
1 2:Large 3:0.11
1 4:1.1 5:2
```

you should create column description file (let's assume it is called ``cd``) with the following contents (replace ``<tab>`` with actual tab):

```
0 <tab> Label
1 <tab> Num
2 <tab> Categ
3 <tab> Num
4 <tab> Num
5 <tab> Categ
```

and load it in python like that:

```py
import catboost as cb

pool = cb.Pool('libsvm:///home/user/datasets/my_dataset/file_in_libsvm_format', column_description='/home/user/datasets/my_dataset/cd')
```

**Comment by janelu9** [comment]
catboost is a excellent boosting model when the  categorical features are large

**Comment by anuragreddygv323** [comment]
For classification it is fine, but for ranking tasks on CPU, it says 

"I get this error 'one_hot_max_size is 1 for ranking training on CPU is N/A"

**Comment by andrey-khropov** [comment]
Documentation has been updated with information about sparse data support.
