### ISSUE TITLE
Very bad OOTB performance on Boston Housing data set

### ISSUE THREAD

**Issue by Garve** [catboost/catboost#1078]
Problem: Hi! The OOTB performance on the sklearn Bostong dataset is very very bad.

```
import pandas as pd
from catboost import Pool, CatBoostRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

boston = load_boston()
X = boston.data
y = boston.target

X = pd.DataFrame(X, columns=boston.feature_names)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/10, random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=1/9)

c = CatBoostRegressor(early_stopping_rounds=50)
c.fit(
    Pool(X_train, y_train),
    eval_set=Pool(X_val, y_val),
)

c.score(X_test, y_test)
#result: around r² is around 0.03, while for RF it is around 0.93 OOTB.
```

Shoudn't the catboost score be also higher than 0.9?

catboost version: 0.18.1
Operating System: Windows 10, 64bit

**Comment by Garve** [comment]
I found out, that the performance increases to normal levels when not using pandas dataframes. If you do X = X.values first and remove the dataframe structure, everything wors as expected.

So I think catboost does something different, depending on whether the input is a dataframe or a normal numpy array.

**Comment by andrey-khropov** [comment]
This had been a bug in CatBoost. This is the same issue as https://github.com/catboost/catboost/issues/1079. It is fixed by commit https://github.com/catboost/catboost/commit/ecf0e3eb6715245d6d5c00bb9769e2cfb1a300a1. The next CatBoost release on this week will include this fix.
