### ISSUE TITLE
Data corruption when using Pool on sklearn.datasets

### ISSUE THREAD

**Issue by kaz184** [catboost/catboost#1079]
Problem: class `Pool` can't copy the data properly that comes from `sklearn.datasets`.
catboost version : 0.18.1
numpy version : 1.17.4
pandas version : 0.25.1
sklearn version : 0.21.3
OS: Windows 7 (but reproducible on Kaggle)

This is the code to reproduce the Problem above.
```python
import numpy as np
import pandas as pd
import sklearn, catboost
import sklearn.datasets

X, _ = sklearn.datasets.load_iris(return_X_y=True)
x = pd.DataFrame(X[0:2,0:2])
print(x.values)
#[[5.1 3.5]
# [4.9 3. ]]

pool_pd = catboost.Pool(x)
print(pool_pd.get_features()) # data corruption occurred
#[[5.1 3.5]
# [3.5 1.4]]

pool_np = catboost.Pool(x.values)
print(pool_np.get_features())
#[[5.1 3.5]
# [4.9 3. ]]

# build up the same matrix one-by-one.
x = pd.DataFrame([[5.1, 3.5], [4.9, 3.0]], dtype='float64')
print(x.values)
#[[5.1 3.5]
# [4.9 3. ]]

pool_pd = catboost.Pool(x)
print(pool_pd.get_features()) # it's OK now.
#[[5.1 3.5]
# [4.9 3. ]]
```

It's really weird that it's okay to copy the data built by hand but not loaded from `sklearn.datasets`. This causes incorrect prediction on such data and makes `fit` incapable.

**Comment by annaveronika** [comment]
Thanks for pointing it out! It is fixed now in code and will be out on pypi in a new release 0.19.2 today.
