### ISSUE TITLE
Unable to predict with loaded CatBoostClassifier

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [catboost/catboost#108]
This code
```
from catboost import CatBoostClassifier
cat = CatBoostClassifier(iterations=5, loss_function='MultiClass')
cat.fit(X_train, y_train)
cat.save_model('./model.cat')

fresh_cat = CatBoostClassifier()
fresh_cat.load_model('./model.cat')
fresh_cat.predict_proba(X_test)

```
 raises next error:

> ---------------------------------------------------------------------------

> CatboostError                             Traceback (most recent call last)
> <ipython-input-40-f8bc15627a21> in <module>()
> ----> 1 fresh_cat.predict_proba(X_test)
> 
> /usr/local/lib/python3.5/dist-packages/catboost/core.py in predict_proba(self, data, weight, ntree_limit, verbose)
>    1084         prediction : numpy.array
>    1085         """
> -> 1086         return self._predict(data, weight, 'Probability', ntree_limit, verbose)
>    1087 
>    1088     def staged_predict(self, data, weight=None, prediction_type='Class', verbose=None):
> 
> /usr/local/lib/python3.5/dist-packages/catboost/core.py in _predict(self, data, weight, prediction_type, ntree_limit, verbose)
>     491         loss_function = self.get_param('loss_function')
>     492         if loss_function is not None and (loss_function == 'MultiClass' or loss_function == 'MultiClassOneVsAll'):
> --> 493             return np.transpose(self._base_predict_multi(data, prediction_type, ntree_limit, verbose))
>     494         predictions = np.array(self._base_predict(data, prediction_type, ntree_limit, verbose))
>     495         if prediction_type == 'Probability':
> 
> _catboost.pyx in _catboost._CatBoostBase._base_predict_multi (/home/donskov/.ya/build/build_root/6cqq/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:15435)()
> 
> _catboost.pyx in _catboost._CatBoost._base_predict_multi (/home/donskov/.ya/build/build_root/6cqq/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:11496)()
> 
> _catboost.pyx in _catboost._CatBoost._base_predict_multi (/home/donskov/.ya/build/build_root/6cqq/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:11344)()
> 
> CatboostError: catboost/libs/model/model_calcer.h:52: Condition violated: `results.size() == docCount * ModelClassCount'

**Comment by vitekmel** [comment]
Thanks! It was again our mistake, we will fix it in new version.

**Comment by vitekmel** [comment]
Should be fixed now, could you please recheck?

**Comment by vBLFTePebWNi6c** [comment]
@vitekmel works fine. Thanks!
