### ISSUE TITLE
documentation on get_evals_result

### ISSUE THREAD

**Issue by natskr** [catboost/catboost#1080]
Problem: 
When I plot precision/recall with weights=true/false for a highly imbalanced dataset they differ between e.g. 0.1 and 0.9. I was wondering if you could supply some more information on how to interpret the results.

Thank you!

**Comment by annaveronika** [comment]
If weights are present, then they are used for optimization. In metric calculation usage of weights is optional and is regulated by use_weights parameter.
https://catboost.ai/docs/concepts/loss-functions-classification.html - here you can read for every metric, including Precision and Recall, how it is calculated. Here https://catboost.ai/docs/concepts/loss-functions.html you can read how weights are used for use_weights=True for calculation of P, TP, TN and so on.
If use_weight=False, all weights are considered being equal to 1.

**Comment by annaveronika** [comment]
So this is completely normal that weighted metric is different from not weighted one.
I hope it answers your question! Let us know if you have more questions.
Closing the issue.
