### ISSUE TITLE
480KB dataset + depth 16 => Out of memory

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1081]
Catboost version: current
Operating System: Ubuntu 18.04
CPU: 16 cores AMD Tread ripper
Memory: 112GB
#GPU: 3 x GeForce RTX2070 8GB

Classification type: Binary.
Train dataset (480kb): 744 rows and 90 columns - only float values (like 0.52633333).
Val dataset (120KB): 186 row and 90 columns.

Everything works fine if I reduce the depth to 14 - but at a Depth of 16 it runs out of memory - is there an option to prevent this?

I have already tried with: boosting_type="Plain" (Plain works only up to Depth 12, Ordered up to Depth : 14).  Also, by setting "gpu_ram_part=0.8" or max_ctr_complexity=1 doesn't change/help anything.

The weird part is: That it requires less memory than each GPU contains (8 GB)? And which are free according to the Debug log?

`Requested 5696 MB; Free 3958.169335 MB"`

```
Free memory on device #0 7212.578125MB
Free memory on device #1 7458.865624MB
Free memory on device #2 5944.803124MB
```
My code:
```
import pandas as pd
from catboost import CatBoostClassifier, Pool

# Initialize data
train_data = pd.read_csv('./train_x.csv')
label_data = pd.read_csv('./labels_train_x.csv')
val_data = pd.read_csv('./val.csv')
val_labels = pd.read_csv('./labels_val.csv')

# Initialize CatBoostClassifier
model = CatBoostClassifier(iterations=10000, task_type="GPU", devices='0-2', eval_metric='Accuracy', boosting_type="Ordered", depth=16)

#max_ctr_complexity=1, boosting_type="Ordered"
#od_type="Iter", early_stopping_rounds=100, #Logloss #custom_metric=['Accuracy'],
#learning_rate=0.03, #gpu_ram_part=0.8, loss_function='RMSE'
						   
eval_dataset = Pool(val_data, val_labels)

# Fit model
tester = model.fit(train_data, y=label_data, eval_set=eval_dataset, logging_level='Debug')#, cat_features=cat_features)
    
# Get predicted classes
preds_class = model.predict(val_data)
# Get predicted probabilities for each class
preds_proba = model.predict_proba(val_data)

# Get predicted RawFormulaVal
preds_raw = model.predict(val_data, prediction_type='RawFormulaVal')
```

Error:

```
Float Feature #7 is empty
Target border set to 0.5
Learning rate set to 0.02823
No catFeatures for ctrs found and don't look ahead is disabled. Fallback to one permutation
Requested devices:
  0. GeForce RTX 2070 (compute capability 7.5)
  1. GeForce RTX 2070 (compute capability 7.5)
  2. GeForce RTX 2070 (compute capability 7.5)
Free memory on device #0 7212.578125MB
Free memory on device #1 7458.865624MB
Free memory on device #2 5944.803124MB
Compressed index was written in 0.057267 seconds
Compressed DataSet `Learn permutation independent features` with 89 features
Grid policy OneByteFeatures. Memory usage for 89 features and 247 docs at dev 0: 0.02167129517 MB
Grid policy OneByteFeatures. Memory usage for 89 features and 247 docs at dev 1: 0.02167129517 MB
Grid policy OneByteFeatures. Memory usage for 89 features and 249 docs at dev 2: 0.02184677124 MB
Compressed DataSet `Test dataset` with 89 features
Grid policy OneByteFeatures. Memory usage for 89 features and 61 docs at dev 0: 0.005352020264 MB
Grid policy OneByteFeatures. Memory usage for 89 features and 61 docs at dev 1: 0.005352020264 MB
Grid policy OneByteFeatures. Memory usage for 89 features and 63 docs at dev 2: 0.005527496338 MB
Application terminated with error: ??+0 (0x7F476AB133E1)
??+0 (0x7F476AB11685)
??+0 (0x7F476AB10425)
??+0 (0x7F476AB10E08)
??+0 (0x7F47698D84F3)
??+0 (0x7F47698D83A7)
??+0 (0x7F47C97D96DB)
clone+63 (0x7F47C9B1288F)

(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:302: Error: Out of memory. Requested 5696 MB; Free 3958.169335 MB
uncaught exception:
    address -> 0x106c4f800
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:302: Error: Out of memory. Requested 5696 MB; Free 3958.169335 MB"
    type -> NCudaLib::TOutOfMemoryError
Application terminated with error: ??+0 (0x7F476AB133E1)
??+0 (0x7F476AB11685)
??+0 (0x7F476AB10425)
??+0 (0x7F476AB10E08)
??+0 (0x7F47698D84F3)
??+0 (0x7F47698D83A7)
??+0 (0x7F47C97D96DB)
clone+63 (0x7F47C9B1288F)

(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:302: Error: Out of memory. Requested 5696 MB; Free 5353.949219 MB
Application terminated with error: ??+0 (0x7F476AB133E1)
??+0 (0x7F476AB11685)
??+0 (0x7F476AB10425)
??+0 (0x7F476AB10E08)
??+0 (0x7F47698D84F3)
??+0 (0x7F47698D83A7)
??+0 (0x7F47C97D96DB)
clone+63 (0x7F47C9B1288F)

(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:302: Error: Out of memory. Requested 5696 MB; Free 5600.236718 MB
uncaught exception:
    address -> 0x106c39000
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:302: Error: Out of memory. Requested 5696 MB; Free 5353.949219 MB"
    type -> NCudaLib::TOutOfMemoryError
Aborted (core dumped)
```

**Comment by Garfield2013** [comment]
SOLVED!

max_bin=32

was added to the CatBoostClassifier :-)

**Comment by Garfield2013** [comment]
It is difficult from the DOCS to know what actual effect on the model accuracy etc. this "max_bin" has.

If I set it to 1 it will only run for 10 min and it will result in a lower accuracy vs. if I set it to 32 it will take 12 hours - but also result in a higher accuracy. So I guess this param is not only about how it split data - but it actually effect the model's performance a lot...? Can somebody elaborate a bit for me how this truly works and what the purpose is?

**Comment by annaveronika** [comment]
The default tree growing strategy in catboost is symmetric trees. If you set depth to 16, then every tree will have 2^16 leaves, which is probably not what you want. It is recommended to use depth up to 10 or 12.

**Comment by Garfield2013** [comment]
Since CATBOOST support Depth of 16 - why is 10 or 12 recommended? Should 16
not be able to find/generate the same or
hopefully even better settings/models?

**Comment by annaveronika** [comment]
You can use 16, but with depth 16 you cannot build a large ensemble, because it will not fit into memory. 16 doesn't generate the same or better model, because it assigns 2^16 leaves to every tree, which is usually too much for gradient boosting.

**Comment by Garfield2013** [comment]
Can you recommend some exact settings to help us out with the best settings
in regards to CATBOOST:

*System:* Ubuntu 18.04, 3 x GeForce RTX2070 8GB, 112GB memory, 16 cores AMD
3.5GHz
*Classification type:* Binary
*Dataset columns:* Our datasets have 100 columns (all float values).
* Dataset rows:* 500-10.000

*Current setup:*

model = CatBoostClassifier(iterations=1000, task_type="GPU", devices='0-2',
eval_metric='Accuracy', boosting_type="Ordered", depth=16,max_bin=46)
eval_dataset = Pool(val_data, val_labels)
model.fit(train_data, y=label_data, eval_set=eval_dataset, verbose=1)
preds_class = model.predict(val_data)
preds_proba = model.predict_proba(val_data)
preds_raw = model.predict(val_data, prediction_type='RawFormulaVal')

*1. Would you make any changes to the code above?*

*2. Would you recommend any use/changes to the following parameters below?*

- bagging_temperature
- bootstrap-type="Bernoulli" / Bayesian (default)
- loss_function
- learning_rate
- any other?

*3. Please let me know any other suggestions!*

I watch 2 videos with you on youtube yesterday - they were really helpful
:-)
Thank you so much Anna Veronika - you help is highly appreciated! :-)

*PS. We currently get the following results:*

Depth of 12 and 1.000 iterations: 76.76%
Depth of 16 and 1.000 iterations: 77.29%

**Comment by annaveronika** [comment]
https://catboost.ai/docs/concepts/parameter-tuning.html - here are the tips for parameter tuning, I would suggest to try all that you see there.

**Comment by Garfield2013** [comment]
Okay - thank you so much :)
