### ISSUE TITLE
how to get feature_importance for each row?

### ISSUE THREAD

**Issue by dongxiaotian** [catboost/catboost#1085]
Problem:I'm new to catboost. In xgboost and lgb I can use predict(pred_contrib=True) to get feature importance for each row, while in catboost I didn't find method like this. I konw one can use shap value to get importance of (n_rows*n_columns), but can I use the value contributes method in catboost?   
thanks.

**Comment by annaveronika** [comment]
Here is a whole block about different methods of feature analysis, including two types of feature importances:
https://catboost.ai/docs/concepts/model-analysis.html

https://catboost.ai/docs/concepts/python-reference_catboost_get_feature_importance.html
here is the method in Python.

**Comment by annaveronika** [comment]
Hope it helps! Closing the issue. Let us know if you have more questions.
