### ISSUE TITLE
early_stopping_rounds not recognized [R] ver 0.19.1

### ISSUE THREAD

**Issue by slavakx** [catboost/catboost#1086]
catboost version: 0.19.1
Operating System: Windows/Unix
CPU

Although the issue was earlier closed I get the following error when I use early_stopping_rounds parameter in R

catboost/catboost/libs/options/plain_options_helper.cpp:216: Error: unknown option early_stopping_rounds with value 50

**Comment by annaveronika** [comment]
Thanks for the issue, we'll look into this.

**Comment by grag90** [comment]
This problem was fixed in master, will be included in next release
