### ISSUE TITLE
CatBoostClassifier and target_border property

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1088]
According to the CATBoost DOCS: [https://catboost.ai/docs/concepts/python-reference_parameters-list.html](https://catboost.ai/docs/concepts/python-reference_parameters-list.html)

I try to set the property "target_border" to 0.6, 0.7, 0.8... which should effect my results/validation accuracy/confusion matrix A LOT... but nothing changes - what do I miss (do I need to apply other properties as well for it to take effect)?

**Comment by annaveronika** [comment]
This parameter does the following: it binarizes the target (not the predictions) based on the border value.
If your target values are equal to 0 and 1, or to -1 and 1, then the borders that you are using will not take any effect on the training.

**Comment by Garfield2013** [comment]
Okay - then I misunderstood the DOCS... I thought it would change the way the model looked at each data-row when training / the limit which is in use when it learns between each iteration... to learn and distinguish what is actually a 0 and 1...

Another simple question: Please take a look a this [Okay - then I misunderstood the DOCS... I thought it would change the way the model looks at each data-row when training / the limit which is in use when it learns between each iteration... to learn what is actually a 0 and 1...

Another simple question: Please take a look at this chart I draw to show CATBoost's relation between FPR-FNR... It is clear to me that the FPR's error goes in an downwards trend along with the threshold increases... But it is not clear to me that the FNR goes in the opposite direction ...it increases along with the threshold) How is this possible... I guess I don't know how to interpret the chart correct...?

**Comment by annaveronika** [comment]
Here are the docs for PRR and FNR curves:
https://catboost.ai/docs/concepts/python-reference_utils_get_fnr_curve.html

Here https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb
In [34]: shows and example of FPR-FNR curves.

Hope it helps!

**Comment by Garfield2013** [comment]
Thank you so much Anna ! I will look into it! :-)

Also, I have now been working with CATBOOST for some weeks now and so far I have experience with all the thing below:

**My questions is: Does CATBoost contain something else really important I currently miss to look into (I have been reading a lot in the DOCS)? I highly appreciate your support Anna! :-)**

1. Training models (eval_metric='Accuracy')
2. Make prediction ()
3. Load and save (use_best_model, best_estimator_.get_params()) models
4. GridSeach of model params (Depth, iterations, max_bin, l2_leaf_reg, bagging_temperature, random_strenght, fold_len_multiplier, loss_function)
5. Feature importance
6. Object importance
7. FPR-FNR ratio / curve
8. Other: Bootstrap_type, eval_metric, od_type+early_stopping_rounds, gpu_ram_part and plotting

**Comment by annaveronika** [comment]
There's a lot of staff there, I would recommend to go through all our tutorials on github:
https://github.com/catboost/tutorials

**Comment by annaveronika** [comment]
Thanks for your questions, I think, we've solved the initial problem, so I'm closing the issue. I suggest to join our telegram chats and our channel in ods community in slack for catboost discussions!
Closing the issue, thanks for participation!

**Comment by Garfield2013** [comment]
Okay - But what TOP 3 things you would recommend me to look into - for the
biggest gains? :-)

man. 25. nov. 2019 kl. 14.02 skrev annaveronika <notifications@github.com>:

**Comment by annaveronika** [comment]
https://catboost.ai/docs/concepts/tutorials.html - I would suggest to go from top to the bottom of this page.

**Comment by Garfield2013** [comment]
Is it possible to pay and get assistance from you / CATBOOST team - if it
is: please contact me on mb@tradebutler.io

man. 25. nov. 2019 kl. 14.06 skrev annaveronika <notifications@github.com>:

**Comment by annaveronika** [comment]
Thanks for your interest, it's not possible.
