### ISSUE TITLE
Reading several quantized files to a Pool

### ISSUE THREAD

**Issue by aftersought** [catboost/catboost#1089]
We are evaluating catboost to train a model on a dataset that does not fit into RAM in it's raw `float32` form. However, due to the way catboost works, there is no actual need to load float values into RAM: the model is trained on a heavily discretized dataset (lets say we are happy with 256 bits / bins per feature). Currently, we can load a chunk of the dataset in RAM, create a Pool and save quantized file to disk. However, we cannot the ask the Pool constructor to read several of these files to create a single dataset. Is there a way to do it? Or perhaps you will suggest another workaround.

Theoretically we could concatenate several quantized files on disk using OS tools, and feed the resulting file to a Pool. However it appears there is a header to your .bin files, which complicates the matter.

Note that this assumes that all data chunks are quantized using the same bins. As far as we can see, this can be achieved using custom quantization borders, but if you had a tool that would "sync" the subsequent files to the auto-generated borders from the first file, this might come handy too.

It is incredibly wasteful to spend 4x (or 8x) real RAM requirement during data loading stage, when the fitting procedure does not require that memory. We are currently using LightGBM, which has exactly the same data loading pattern, with the same problem. We have ended up writing a custom reader for their Dataset class that reads data from disk efficiently, something we really don't like to do again for catboost.

**Comment by annaveronika** [comment]
Thanks for the issue!
The correct way of doing what you want is to first calculate quantization borders on a subsample of the dataset, then use this borders to quantize parts of the dataset, then merge those parts. This will be done in https://github.com/catboost/catboost/issues/1116.
So please follow that issue, we'll post news there. We currently have some external contributors who are willing to participate, so hopefully at some point this will be done.

I'm closing this issue as a duplicate.

**Comment by jinyyy666** [comment]
Hi @annaveronika  and @andrey-khropov  how is the "merging those parts" done for catboost? Say I want to merge different trunks of the catboost Pool data into one, how will I do that?
