### ISSUE TITLE
How to show catboost visualization in Google Colab

### ISSUE THREAD

**Issue by bhishanpdl** [catboost/catboost#1092]
Platform: Google Colab (Nov 23, 2019)
catboost version: 0.19.1

Problem: Can not visualize fitting plot.

```python
import sys
ENV_COLAB = 'google.colab' in sys.modules

if ENV_COLAB:

    !pip install catboost
    !pip install ipywidgets
    !jupyter nbextension enable --py widgetsnbextension

    print('Environment: Google Colab')

from catboost import CatBoostClassifier, Pool

train_data = [[1, 3], [0, 4], [1, 7], [0, 3]]
train_labels = [1, 0, 1, 1]

model = CatBoostClassifier(learning_rate=0.03)

model.fit(train_data,
          train_labels,
          verbose=False,
          plot=True)
```
Google colab just prints <catboost.core.CatBoostClassifier at 0x7fc7a846d898> instead of showing the plot as shown in [official webpage](https://catboost.ai/docs/features/visualization_jupyter-notebook.html) of catboost.

**Comment by annaveronika** [comment]
That's a duplicate for https://github.com/catboost/catboost/issues/985
