### ISSUE TITLE
get_object_importance and pools

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1093]
It is not clear in DOC - what the difference pools/dataset are [https://catboost.ai/docs/concepts/python-reference_catboostclassifier_get_object_importance.html](https://catboost.ai/docs/concepts/python-reference_catboostclassifier_get_object_importance.html)

If my model has been trained on dataset_1 with 10.000 rows and validated on dataset_2 with 2.000 rows - what would be correct to set pool and train_pool to in the code below?
(It is the train_pool which determine the size of the returned collection which contains the strength values)

get_object_importance(pool,
                      train_pool, # The data for calculating object importances
                      top_size=-1, # The dataset used for training.
                      type='Average',
                      update_method='SinglePoint',
                      importance_values_sign='All',
                      thread_count=-1,
                      verbose=False)

**Comment by annaveronika** [comment]
Sorry, I don't understand the question. Please look through the object importance tutorial, it should help.

**Comment by Garfield2013** [comment]
I’m asking: what is the different between pool and train_pool params?

tir. 26. nov. 2019 kl. 17.06 skrev annaveronika <notifications@github.com>:

**Comment by annaveronika** [comment]
pool is the set of objects for which you are trying to find influential objects from train dataset.
train_pool is train dataset

**Comment by Garfield2013** [comment]
It is still not clear to me - but may be if you can answer the following questions:

1. What does it mean to set the pool and train_pool to the same?
2. What does it mean to set pool to a dataset of 100 rows and train_pool to a subset of these rows - like 10 rows?
3. What does it mean to set pool to a subset dataset of 10 rows and train_pool to a dataset of 100 rows?

**Comment by annaveronika** [comment]
train pool must be the one, used for training with all samples that were used there, pool might be any pool

**Comment by annaveronika** [comment]
For the details of the algorithm you can read the paper https://arxiv.org/abs/1802.06640

**Comment by Garfield2013** [comment]
**I simple want to do the following:**

1. Train on a dataset of 1.000 rows
2. Get the object importance of each single row
3. Sort all 1.000 object importance scores
4. Remove the 10% of the rows with the lowest scores (which had the most bad influence on the training and thereby the final model)
5. Re-train the model with the rest / the TOP 90% of the rows (with the highest score) and check if model performance has increased.

**Should I then set pool and train_pool to the same dataset of 1.000 rows?**

**Comment by annaveronika** [comment]
We have a tutorial which shows an example of how to improve a model by removing some rows with lowest scores, which is precisely what you're trying to do.
Object importance functionality can also be used in other ways, you need to experiment and explore.
I'm grateful for your interest, for discussions on how to use different things from the library I suggest using our telegram chats and our #tool_catboost channel in ods slack community.

**Comment by Garfield2013** [comment]
Okay - I will look into those sources as well! But it is so nice you have
all the knowlegde I need - when I get stucked :-) And I REALLY appreciate
all you help and time Anna! Thank you so much again :-)

tir. 26. nov. 2019 kl. 23.21 skrev annaveronika <notifications@github.com>:
