### ISSUE TITLE
Custom validation function

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1094]
Would it be possible to use a custom function which CATBOOST uses to validate its performance between each iteration (instead of the normal eval_metric='Accuracy' , logloss ect.)?

The function would contain 100% custom logic and not be related to the ordinary values like Accuracy, logloss etc. But it would still return a float value which the model then should optimize from.

**Comment by annaveronika** [comment]
Yes, you need to use custom metric for that. Here's a usage example:
https://catboost.ai/docs/concepts/python-usages-examples.html#custom-loss-function-eval-metric

**Comment by Garfield2013** [comment]
I got the CustomMetric class example to work when I make it return a simple counter variable as score :-)

But I actually like to access the current version of the model inside the get_final_error method.
This way I will make a .predict and return a score for each iteration -> check the line with the comment "# This line fails".

Would that be achievable? 

```
class CustomMetric(object):

    def __init__(self):
        self.counter = 0
        self.current_model = None
        self.current_score = None

    def get_final_error(self, error, weight):
        self.counter+=1
        self.current_model = copy.deepcopy(model)
        self.current_score = self.current_model.predict(val_data) # This line fails
        return self.counter

    def is_max_optimal(self):
        return True

    def evaluate(self, approxes, target, weight):
        # approxes - list of list-like objects (one object per approx dimension)
        # target - list-like object
        # weight - list-like object, can be None
        return 0.0, 0.0
```
Error:

```
<IPython.core.display.HTML object>
MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))
Traceback (most recent call last):
  File "_catboost.pyx", line 1338, in _catboost._MetricGetFinalError
  File "/home/tb/Desktop/catboost/test_single.py", line 26, in get_final_error
    self.current_score = self.current_model.predict(val_data) # This line fails
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 3837, in predict
    return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, 'predict')
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 1846, in _predict
    data, data_is_single_object = self._process_predict_input_data(data, parent_method_name)
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 1825, in _process_predict_input_data
    "Use fit() to train model. Then use this method.").format(parent_method_name))
_catboost.CatBoostError: There is no trained model to use predict(). Use fit() to train model. Then use this method.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_catboost.pyx", line 1328, in _catboost._MetricGetDescription
SystemError: <built-in method encode of str object at 0x7f751d9cb630> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_catboost.pyx", line 1328, in _catboost._MetricGetDescription
SystemError: <built-in method encode of str object at 0x7f751d9cb630> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_catboost.pyx", line 1437, in _catboost._DoubleArrayWrapper.create
SystemError: <class '_catboost._DoubleArrayWrapper'> returned a result with an error set
Exception ignored in: '_catboost._MetricEval'
Traceback (most recent call last):
  File "_catboost.pyx", line 1437, in _catboost._DoubleArrayWrapper.create
SystemError: <class '_catboost._DoubleArrayWrapper'> returned a result with an error set
Traceback (most recent call last):
  File "/home/tb/Desktop/catboost/test_single.py", line 49, in <module>
    result = model.fit(train_data, y=label_data, eval_set=eval_dataset, verbose=1, plot=True)
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 3788, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 1684, in _fit
    train_params["init_model"]
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 1222, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 3710, in _catboost._CatBoost._train
  File "_catboost.pyx", line 3756, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/metrics/metric.cpp:3310: Custom metric evaluate() returned incorrect value. Expected tuple of size 2, got tuple of size 0.
```

**Comment by Garfield2013** [comment]
Another (alternative) thought: If the above scenario is not possible (to access the current model (state) and make a .predit on it while training for each iteration). Would it then be possible to save the model after each iteration (then I will be able to load all models afterwards and then make the prediction)?

**Comment by annaveronika** [comment]
It is not possible to access the model from this class, and we don't plan for this functionality.
For your case you need to use staged_predict functionality which does exactly what you are asking for.

**Comment by Garfield2013** [comment]
haha ... what are the odds! I continue my googling... and 30 secs ago I found: [https://catboost.ai/docs/concepts/python-reference_catboost_staged_predict.html](https://catboost.ai/docs/concepts/python-reference_catboost_staged_predict.html)

Perfect! Thank you so Anna!

**Comment by annaveronika** [comment]
I'm happy we've solved the problem! Closing the issue then.

**Comment by Garfield2013** [comment]
I can execute the code - but nothing really useful to find in the returned object/data ("staged_result" in my the code below)?

How do I access the: RawFormulaVal — One-dimensional numpy.ndarray of raw formula values (one for each object). as mentioned in the DOCS?

Please check this screenshot for better understanding (what I'm looking at): [https://www.screencast.com/t/1v1Vz9OLaSlo](https://www.screencast.com/t/1v1Vz9OLaSlo)

```
eval_dataset = Pool(val_data, val_labels)

model = CatBoostClassifier(task_type="GPU", devices='0-2', eval_metric='Accuracy', boosting_type="Ordered", use_best_model=True, # 'Accuracy'
iterations=100, depth=4, max_bin=46, l2_leaf_reg=20, bagging_temperature=0, random_strength=None)
result = model.fit(train_data, y=label_data, eval_set=eval_dataset, verbose=1, plot=True)

staged_result = model.staged_predict(eval_dataset,
               prediction_type='Class',
               ntree_start=0, 
               ntree_end=100,
               eval_period=1,
               thread_count=-1, 
               verbose=None)
```

**Comment by annaveronika** [comment]
to access raw formula values, you need to use prediction_type='RawFormulaVal'

**Comment by Garfield2013** [comment]
no matter what I set prediction_type to ...class or RawFormulaVal... the output looks the same to me? I simply can't find anything useful in the object?

Please show me an example how to get the prediction values out of "staged_result" :-)

**Comment by annaveronika** [comment]
Did you look on the python examples in the docs?

**Comment by Garfield2013** [comment]
yes of course [https://catboost.ai/docs/concepts/python-reference_catboost_staged_predict.html](https://catboost.ai/docs/concepts/python-reference_catboost_staged_predict.html) - but it doesn't help me - but please check my screenshot... what do I do wrong?

**Comment by annaveronika** [comment]
https://catboost.ai/docs/concepts/python-usages-examples.html

Also please look on the tutorials, some of them have staged_predict examples. I think the main python tutorial contains it also.

**Comment by Garfield2013** [comment]
Solved! I missed the list() ! Now everything/the returned object makes sense! :-)
Btw. what does the "RawFormulaVal" value indicate (I understand "Class" and "Probability")

staged_result = list(model.staged_predict(eval_dataset,
               prediction_type='Class',
               ntree_start=0, 
               ntree_end=0,
               eval_period=1,
               thread_count=-1, 
               verbose=None))

OR

# Fit model
model.fit(train_dataset)

# Get staged_predictions
# First method: use predict() with `ntree_end` in loop
staged_predictions_brute_force = []

for i in range(1, model.tree_count_ + 1):
    staged_predictions_brute_force.append(model.predict(eval_data, 
                                                        ntree_end=i))

# Second method: It is equivalent to the previous, but faster
staged_predictions = list(model.staged_predict(eval_data))
