### ISSUE TITLE
Catboost one hot encoding in pairwiselogit

### ISSUE THREAD

**Issue by anuragreddygv323** [catboost/catboost#1098]
In the documentation it is mentioned that one_hot_max_size is 1 for ranking training on CPU is N/A

In my data, I have close to 20 categorical features with atleast 200 levels in each categorical variable. What to do so that I can incorporate them in my model training?

@annaveronika

**Comment by annaveronika** [comment]
If you mark your features as categorical, they will still be used in your pairwise model.

Since pairwise modes don't require label values, no statistics that are based on label values can be calculated if labels are not present. For this reason one-hot-encoding for categorical features is used.

**Comment by anuragreddygv323** [comment]
I get this error 'one_hot_max_size is 1 for ranking training on CPU is N/A'

**Comment by anuragreddygv323** [comment]
Since pairwise modes don't require label values . - **what do u mean...?** 

the first value is the label/relevance score in the libsvm format

**Comment by annaveronika** [comment]
To train a pairwise model you need to provide pairs of objects, where for each pair it is stated, which object is the winner, and which one is the looser. It doesn't require label values.

**Comment by annaveronika** [comment]
I hope this has helped! Please let us know if you have more questions.
