### ISSUE TITLE
Installation Fails with non-zero exist Version 0.20

### ISSUE THREAD

**Issue by Avichi** [catboost/catboost#1099]
Problem: Installation Catboost v.20
catboost version: v0.20
Operating System: Windows 10 x64
CPU: 8 core
GPU: 1
R-Studio:Version 1.2.5019
R Version:R version 3.5.3 (2019-03-11) -- "Great Truth"

Installation Fails with non-zero exist
Installation Script:
_**install.packages('devtools')
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', args = c("--no-multiarch"))**_

Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘C:/Users/User/AppData/Local/Temp/RtmpopWH2q/file144855804d9d/catboost_0.20.tar.gz’ had non-zero exit status

**Comment by dbakshee** [comment]
Hi @Avichi 
Looks like `args = ...` option for install_url() does not work as documented, and one should use `INSTALL_opts` instead. Could you please try this command? :
```
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch"))
```

**Comment by Avichi** [comment]
Ok , will try recommended oprion, and report back.

**Comment by Avichi** [comment]
@Dimitry, Thanks, and Happy Thanks Giving! it worked, documentation may need update on website.

-----------------------------------
PRIVACY AND CONFIDENTIALITY NOTICE:

This communication constitutes an electronic communication within the meaning of the Electronic Communications Act, 18 USC 2510 and any files transmitted with it may contain PRIVILEGED and CONFIDENTIAL information and may be read or used only by the intended recipient named above, snooping (MITM) while an email is in "real-time" transmission between sender and receiver is a federal crime under the Electronic Communications Protection Act (ECPA), Section 18 U.S.C.A 2517 (4)-Section 18 U.S.C.A 27 Chapter 121 (2701-2712) and Stored Communications Act (SCA, 18 U.S.C. § 2701 and Section 18 U.S.C. § 3121 - U.S. Code - Unannotated Title 18. Crimes and Criminal Procedure § 3121. General prohibition on pen register and trap and trace device use. ) The contents may contain Technical Data that is controlled by the ITAR, 22CFR parts 120 to 130, or EAR, 15CFR parts 730 to 772, and therefore should not be disclosed to a non-U.S. person, or entity, in the U.S. or abroad. If you are not the intended recipient of the email or any of its attachments, please be advised that you have received this email in error and that any use, archiving,physical paper storing,cloud devices storage ,dissemination, distribution, forwarding, printing, reverse engineering, editing and/or copying of this email or any attached files is strictly prohibited. If you have received this email in error or have deliberately(Intentionally) stored this message you will be liable under 18 U.S. Code § 2520, please immediately purge, delete, erase it and all attachments and notify the sender by reply email or contact the sender at the number listed above if one is provided. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.All Privacy Protection & Confidentiality apply to all email authors and recipients all American Citizens as per FISA Section 702 and Fourth Amendment of US Constitution. All META Data of this email source file are protected by above applicable laws and cannot be used against the author/receipts in the Court of Law.This email is sent using Microsoft Outlook and Google Mail SMTP/IMAP/POP3 protocols and AndroidOS

________________________________

**Comment by dbakshee** [comment]
Good, thank you!
