### ISSUE TITLE
Java library with Maven support

### ISSUE THREAD

**Issue by virl** [catboost/catboost#11]
Due to inferiority of Python to proper languages/ecosystems like Java/Kotlin, please add support for CatBoost as java module published in Maven Central / JCenter repository.

XGBoost have such implementation called XGBoost4J already: https://github.com/dmlc/xgboost/tree/master/jvm-packages

Java ecosystem even have very popular Keras-like framework DeepLearning4J: http://deeplearning4j.org

P.S. Please embed all platform-specific native libraries into single JAR, so Java developer wouldn't have to recompile your project during deployment or change pom.xml to support different CPU/GPU in development and production environments.

**Comment by ferrr** [comment]
As you can see, we choose to open source CatBoost with our build system (called _ya make_). One of the key features of _ya make_, which is heavily used inside Yandex, is a great interoperability between programming languages. Java is a first-class citizen at Yandex and, of course, _ya make_ allows to write Java bindings for a native code. 

We don't use much Java at Yandex for machine learning, so don't have enough knowledge and motivation for such a task. It would be awesome if someone implements Java support. We understand a possible struggle with undocumented (at the moment) build system.

We will consider implementing scaffolding for Java support.

Maven export is not a problem.

And to be precise, by now we can't embed multiple libraries in a jar.

**Comment by GlebYarnykh** [comment]
They key point is to make similar to XGBoost/Keras pipeline. Train and preprocess in python, then port model to Java and make live predictions. Also probably sm1 would certainly ask for C++ import for the same reason. Otherwise catboost can't be used in production latency-sensitive systems

**Comment by virl** [comment]
@GlebYarnykh +1. Also native Java support is required for model execution (and, preferrably, training too) on Android.

**Comment by rzykov** [comment]
deeplearning4j uses https://github.com/bytedeco/javacpp to interact with their C++ part

**Comment by yazevnul** [comment]
Hi, we implemented native Java support for model inference

https://github.com/catboost/catboost/tree/master/catboost/jvm-packages/catboost4j-inference

During this week we'll make some minor improvements around dynamic library loading and will publish java module to Maven Central with Darwin, Windows and Mac support for x86-64 systems.

**Comment by annaveronika** [comment]
@hlbkin Let's do the benchmarks in https://github.com/catboost/catboost/issues/465
We are happy if we get any help there.
