### ISSUE TITLE
v0.20 fails with read-only numpy arrays

### ISSUE THREAD

**Issue by maartenbreddels** [catboost/catboost#1101]
Dear Catboost authors,

cc @JovanVeljanoski

Problem: v0.20 does not accept read-only numpy arrays
catboost version: v0.20
Operating System: OSX (on CI, but probably more)

This night, with the v0.20 release, our CI or [vaex](https://github.com/vaexio/vaex) failed:
https://github.com/vaexio/vaex/runs/325458310
The relevant part is:
```
packages/vaex-core/vaex/ml/__init__.py:165: in catboost_model
    booster.fit(dataframe, target)
packages/vaex-core/vaex/ml/catboost.py:105: in fit
    dtrain = catboost.Pool(data=data, label=target_data, **self.pool_params)
/usr/local/miniconda/envs/vaex/lib/python3.7/site-packages/catboost/core.py:373: in __init__
    self._init(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
/usr/local/miniconda/envs/vaex/lib/python3.7/site-packages/catboost/core.py:954: in _init
    self._init_pool(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
_catboost.pyx:3343: in _catboost._PoolBase._init_pool
    ???
_catboost.pyx:3265: in _catboost._PoolBase._init_features_order_layout_pool
    ???
_catboost.pyx:3133: in _catboost._PoolBase._set_label_features_order
    ???
_catboost.pyx:218: in _catboost.make_non_owning_type_cast_array_holder
    ???
stringsource:658: in View.MemoryView.memoryview_cwrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: buffer source array is read-only

stringsource:349: ValueError
```

It seems the issue was introduced in 38eb086a9e574509340f789ef3d9cd32289e3d4b, where  https://github.com/catboost/catboost/blame/d6748095fcb6e441d4da7de19146bbb5c217c99c/catboost/python-package/catboost/_catboost.pyx#L218 should include a const (see [cython docs](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#read-only-views)

Tip: for testing, you can set a numpy array read-only using:
```python
ar.flags['WRITEABLE'] = False
```

Our numpy arrays are read-only because the memory map the data read-only.

Regards,

Maarten Breddels - vaex.io

**Comment by annaveronika** [comment]
Thanks for the report, we'll look into this!

**Comment by andrey-khropov** [comment]
This issue is fixed by commit https://github.com/catboost/catboost/commit/8b42b5b914a2793ada19c631e318203a82b01535, the release with this commit is expected at the end of this week.
