### ISSUE TITLE
Grid search Errors when class_weights are specified in the grid

### ISSUE THREAD

**Issue by elena-sharova** [catboost/catboost#1109]
Problem: grid search does not allow for multiple options for class_weights
catboost version:0.20
Operating System:Windows
CPU: Intel(R) Xeon(R) CPU E3-1225 v5
![image](https://user-images.githubusercontent.com/16509515/70786167-ed74d680-1d83-11ea-8f51-da827990d98c.png)

**Comment by annaveronika** [comment]
Thanks for the issue, we'll implement support for this parameter at some point. For now we are welcoming contributions, because it's a good issue for someone not familiar with the code.

**Comment by NippunSharma** [comment]
I would like to take up this issue (this will be my first issue).

**Comment by annaveronika** [comment]
This has been implemented and is out in version 0.23. Sorry for not closing it in time.

**Comment by elena-sharova** [comment]
Thank you for sorting this out.
