### ISSUE TITLE
Using pandas.Series / numpy.array  in get_feature_importance

### ISSUE THREAD

**Issue by vJenny** [catboost/catboost#111]
The following code works:  
```python 
from catboost import Pool 
pool = Pool(train_df, label, cat_features_ids)
clf = CatBoostClassifier(learning_rate=0.1, iterations=10, random_seed=0)
clf.fit(train_df, label, cat_features=cat_features_ids)
imp = clf.get_feature_importance(pool, fstr_type='Interaction')
```
`train_df` is DataFrame, `label` is Series , `cat_features_ids` is list. Then I tried the following:  
```python
imp = clf.get_feature_importance(train_df, y=label, cat_features=cat_features_ids, fstr_type='Interaction')
```
and 
```python
imp = clf.get_feature_importance(train_df, y=np.array(label), cat_features=cat_features_ids, fstr_type='Interaction')
```
Both of them aren't work. I've got an error: *"CatboostError: Length of label=1 and length of data=114321 is different."*.

This is the modified example from  [here](https://github.com/catboost/catboost/blob/master/catboost/tutorials/kaggle_paribas.ipynb).
Python 3.5.2
CatBoost 0.2.2

**Comment by nikitxskv** [comment]
@vJenny Hello!
Thank you for report!
We fixed this bug in the last version.
