### ISSUE TITLE
validation score not available from get_best_score() when fitting using grid_search()

### ISSUE THREAD

**Issue by laopisai** [catboost/catboost#1114]
Problem: validation score not available from get_best_score() when fitting using grid_search()
catboost version: 0.18.1
Operating System: Ubuntu 19.10
CPU: Intel Core i7-8565U
GPU: GeForce MX130

**Comment by annaveronika** [comment]
Thanks for the issue, we'll look into this!

**Comment by annaveronika** [comment]
this is now fixed in code and will be out in the next release this week
