### ISSUE TITLE
Different AUC score on same data...

### ISSUE THREAD

**Issue by P7668** [catboost/catboost#1115]
This problem occurs while training on GPU.
Is there any way to handle this problem?

**Note:- Random_seed parameter is fixed.**

**Comment by annaveronika** [comment]
Could you please provide a minimal reproducing example of your problem?

**Comment by P7668** [comment]
I trained this model 3 times on same training data_set . 

```
from catboost import CatBoostClassifier
model = CatBoostClassifier(
                            iterations = 3000,
                            learning_rate = 0.07,
                            custom_loss=['AUC'],
                            loss_function = "Logloss",
                            eval_metric="AUC",
                            task_type='GPU',
                            thread_count = -1,
                            verbose = 50,
                            random_seed = 0,
                            metric_period = 50,
                            cat_features=cat_cols
                            )

model.fit(train,target, plot = True)

from sklearn.metrics import roc_auc_score
print(roc_auc_score(target, model.predict_proba(train)[:,1]))
```

In 1st run auc score was **0.9928374822111967**.
In 2nd run :- **0.9929301046208088**
In 3rd run :- **0.9927**

I have to perform Backward Elimination method for feature selection but these varying score on same data cause problem.

**Comment by annaveronika** [comment]
GPU training is not deterministic.

**Comment by sharma-ji** [comment]
I am having same issues while training on my CPU.
