### ISSUE TITLE
custom_loss_and_metric_tutorial

### ISSUE THREAD

**Issue by tktenkate** [catboost/catboost#1119]
Problem: multiclass tutorial produces error
catboost version: 0.20
Operating System: ubuntu
# CPU: i7
GPU:
Following the custom_loss_and_metric tutorial in the multiclass section gives an error. 
When fitting the user defined loss_function in model 2:
model2 = CatBoostClassifier(iterations=10, loss_function=MultiClassObjective(), eval_metric=AccuracyMetric(),
                           learning_rate=0.03, bootstrap_type='Bayesian',
                           leaf_estimation_iterations=1, leaf_estimation_method='Newton', classes_count=5)
model2.fit(X_train, y_train, eval_set=(X_test, y_test))

throws an error:
CatBoostError: catboost/libs/options/catboost_options.cpp:461: classes_count parameter takes effect only with MultiClass/MultiClassOneVsAll loss functions

Obviously I need to set the classes_count in the multiclass situation. Is there a way to circumvent this and still have a multiclass objective loss function?

**Comment by LyzhinIvan** [comment]
Hello, @tktenkate ! Just update catboost - it works well since 0.20.1.

**Comment by andrey-khropov** [comment]
> Hello, @tktenkate ! Just update catboost - it works well since 0.20.1.

Actually this issue is resolved in 0.20.2, not in 0.20.1
