### ISSUE TITLE
Python fault when CatBoostClassifier fit a simple model

### ISSUE THREAD

**Issue by hwait** [catboost/catboost#1120]
Dear Sirs! I have a
Problem:
The following script fails on my PC:

`import numpy as np`
`from catboost import CatBoostClassifier`
`train_data = np.array([[1,4,5,6,4],[4,5,6,7,4],[30,40,50,60,30],[1,4,5,6,4],[4,5,6,7,4]])`
`train_labels = np.array([1,0,0,1,0])`
`model = CatBoostClassifier(learning_rate=1, depth=6, loss_function='Logloss')`
`fit_model = model.fit(train_data, train_labels)`

The run with PYTHONFAULTHANDLER=1 shows:

> Windows fatal exception: code 0xc000001d
>Thread 0x00001580 (most recent call first):
>  File "C:\Users\Nikk\Anaconda3\envs\cbenv\lib\site-packages\catboostWindows fatal exception: code 0xc000001d
>\core.py", line 1225 in _train
> File "C:\Users\Nikk\Anaconda3\envs\cbenv\lib\site-packages\catboost\core.py", line 1690 in _fit
> File "C:\Users\Nikk\Anaconda3\envs\cbenv\lib\site-packages\catboost\core.py", line 3793 in fit
> File "<stdin>", line 1 in <module>

**My environment:**
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
**Catboost version:** 0.20.1
**Operating System:** Microsoft Windows 10 Home 10.0.18362 Build 18362
**CPU:** Intel(R) Core(TM)2 Quad  CPU Q9300 @ 2.50GHz, 
**GPU:** Not used

Thank you for your assistance!
Nikolay Kashavkin

**Comment by annaveronika** [comment]
Thank you for the issue, we'll look into that.
