### ISSUE TITLE
Is it possible to extract the estimator type from a model binary without loading it?

### ISSUE THREAD

**Issue by harupy** [catboost/catboost#1121]
Is it possible to get the estimator type from a model binary without loading it like below?

```python
model = catboost.CatBoostClassifier(...)
model.fit(...)
model.save_model('model.cb')
estimator_type = some_func('model.cb')
```

**Comment by annaveronika** [comment]
It is not possible and we don't plan for that, because the same model can be trained using CatBoost, CatBoostClassifier or command line utility or R. You might want to convert any of these models to CatBoostClassifier. We probably should allow the conversion and provide examples of that.

**Comment by annaveronika** [comment]
Will this solve your problem?

**Comment by annaveronika** [comment]
Hope it has helped!
