### ISSUE TITLE
When we drop classes from our target, CatBoost automatically remaps our remaining classes

### ISSUE THREAD

**Issue by patentedata** [catboost/catboost#1123]
Initial target classes:
2.0    
1.0  
7.0  
9.0 

Selected target classes:
2.0    
1.0

Issue - (1.0, 2.0) is automatically being remapped to (0.0, 1.0) when being trained (while still searching for possible 2.0 predictions, leading to three possible classes?) 

![Screen Shot 2019-12-23 at 4 10 19 PM](https://user-images.githubusercontent.com/59184471/71386363-2ee65c80-25a2-11ea-8952-ecc3841b84b1.png)

This is how the predictions are arranged with all 4 classes vs. 2 classes:

![Screen Shot 2019-12-23 at 9 09 58 PM](https://user-images.githubusercontent.com/59184471/71394951-b3e46c80-25c8-11ea-839a-8d1fcfe6ab76.png)

Fix - remap classes from (1.0, 2.0) to (0.0, 1.0) before training the model.

![Screen Shot 2019-12-23 at 9 23 29 PM](https://user-images.githubusercontent.com/59184471/71395375-8b5d7200-25ca-11ea-9f96-606e9faeb6fb.png)

**Comment by annaveronika** [comment]
Sorry, I don't understand what's the problem. Could you please provide an example with catboost code that works not the way you expect? Also could you please provide the code in code format, so that we could paste it to check the behavoir?

**Comment by patentedata** [comment]
[Notebook](https://github.com/patentedata/Troubleshooting/blob/master/catboost_confusion_matrix_error.ipynb)

[2015.csv](https://www.kaggle.com/cdc/behavioral-risk-factor-surveillance-system)
