### ISSUE TITLE
Sum of shap values does not equal to the prediction

### ISSUE THREAD

**Issue by laopisai** [catboost/catboost#1125]
Problem: Sum of shap values does not equal to the prediction
catboost version: 0.18.1
Operating System: Ubuntu 19.10
CPU: i7-8565U

It only happens sometimes but we find that the of shap values does not equal to the prediction.
Please let us know how we can provide further information

**Comment by annaveronika** [comment]
Maybe you are missing baseline value. Could you please provide a minimal reproducing example, so that we know what you're talking about?

**Comment by annaveronika** [comment]
Also please update to the latest version.

**Comment by laopisai** [comment]
Just update to v0.20.1, seems like it is the same

We use it during inference to provide insight to the prediction.

```
input = np.array(['cat1_value','cat2_value','num1_value','num2_value'])
prediction = model.predict(sample_input)   # model is a CatBoostRegressor
print(prediction)

pool = Pool(
    data = pd.DataFrame(np.array([sample_input]), columns=column_names),
    label = np.array([prediction]),
    cat_features = cat_input_features
)
shap_values = model.get_feature_importance(pool, 'ShapValues')
print(np.sum(shap_values))

```
`prediction` and `np.sum(shap_values)` are not equal sometimes.

We used this method in other project and did not observe similar issue

**Comment by annaveronika** [comment]
We need a full reproducible example to debug the problem. From your code I can guess that you might be using CatBoostClassifier, which converts predictions to 0 and 1 instead of raw formula values. Please try to reproduce the problem and post the full code + data here, otherwise it's hard to debug.

**Comment by laopisai** [comment]
We are very sure that we are using the regressor not the classifier.
Funny thing is that certain input combination will give issue and certain conbination is fine

The data belongs to our client and is confidential.
Is there a way to continue this discussion without disclosing the training data?

**Comment by annaveronika** [comment]
We need to have a reproducer to debug the issue... Maybe you could reproduce it with some other data?

**Comment by laopisai** [comment]
Okay, will come back after the holiday

**Comment by annaveronika** [comment]
Thanks! Also so that we could look on that without examples for now, could you provide the details of the training: what is the grow_policy value, are there any categorical features, if so, what is the max_ctr_complexity? What is the number of trees in the ensample?

**Comment by laopisai** [comment]
Good news and more discovery!

When I was trying to look for "grow_policy" from "get_all_params()" it was not there.
Then I take a look at [grow_policy](https://catboost.ai/docs/search/?query=grow+policy) from the docs, it can only be configured with GPU training.

So we did that and the issue is fixed.

Is it because that CPU training does not use SymmetricTreeso we can't do reliable analysis on the model and the prediction?

**Comment by annaveronika** [comment]
Both, CPU and GPU training use SymmetricTree policy by default. And shap values calculation does not depend on how the model has been trained, because the format of the model is the same. So I don't think the reason for you not seeing the problem anymore is the switch to GPU.

**Comment by laopisai** [comment]
You are right, seems like changing the hyper parameter around will sometime make the issue manifest.
We will need time to prepare a reproducer.

Meanwhile, some of the parameters you asked for before the GPU thingy:
- grow_policy:  SymmetricTree (default as you've explained)
- are there categorical features: yes, multiple
- max_ctr_complexity: 4
- tree_count_: 666

**Comment by laopisai** [comment]
Is there an email that we can send later just in case our management decided that we cannot attachment data on Github?

**Comment by laopisai** [comment]
Attached is a fabricated data representing a subset of our training data and also a minimum working training script.

[reproducer.zip](https://github.com/catboost/catboost/files/4004022/reproducer.zip)

**Comment by annaveronika** [comment]
Thank you very much!

**Comment by laopisai** [comment]
Is there any progress? So let us know if there's anything we can help

**Comment by annaveronika** [comment]
Working on that now.

**Comment by annaveronika** [comment]
The problem was when boost_from_average was set - we didn't account for that in shap values calculation. Good news is that it is a constant addition to bias, so it doesn't influence the actual importance values. The fix is now in code and will be out in the next release soon. Thank you very much for pointing out this bug!

**Comment by laopisai** [comment]
Thanks you too. Do we need to retrain when the new release arrive?

**Comment by ek-ak** [comment]
> Thanks to you too. Do we need to retrain when the new release arrive?

Yes, you need to retrain your model to obtain correct shap values.

**Comment by pseudotensor** [comment]
Still have problems with this even for super trivial random dataset, kind of thing passes normally for lightgbm and xgboost.

```
import numpy as np
import pickle
from catboost import CatBoostClassifier, CatBoostRegressor, EFstrType, Pool

model = CatBoostRegressor()

model.load_model("model.cat")
X, y, cat_features = pickle.load(open("catshapproblem.pkl", "rb"))

data = Pool(X, label=y, cat_features=cat_features)
preds_shap = model.get_feature_importance(
    data=data,
    type=EFstrType.ShapValues
)
preds_raw = model.predict(
        data=X,
        prediction_type="RawFormulaVal",
        ntree_start=0,
    )

max_abs_error = np.max(np.fabs(preds_raw - np.sum(preds_shap, axis=1)))
assert np.isclose(preds_raw, np.sum(preds_shap, axis=1)).all(), "catboost shapley does not sum up correctly: %g" % max_abs_error
```

gives

```
Traceback (most recent call last):
  File "catshapproblem.py", line 22, in <module>
    assert np.isclose(preds_raw, np.sum(preds_shap, axis=1)).all(), "catboost shapley does not sum up correctly: %g" % max_abs_error
AssertionError: catboost shapley does not sum up correctly: 0.0285939
```

[catshapproblem.zip](https://github.com/catboost/catboost/files/5773760/catshapproblem.zip)

**Comment by gcoter** [comment]
Hi @pseudotensor, I also have a similar issue I think (with CatBoostClassifier in my case). I opened an issue on the shap project: https://github.com/slundberg/shap/issues/2364

Did you find a solution?

**Comment by pseudotensor** [comment]
No, the problem remains despite this issue being closed.

**Comment by gcoter** [comment]
Ok, should we open a new issue then?

**Comment by pseudotensor** [comment]
Ya, probably.  I gave a repro case.  They may not like opening a pickle, but one can open it, save it as csv, and then re-post.  I'm unable to at moment.

**Comment by ek-ak** [comment]
Hello! Could you provide a full reproducer? There is no model in zip and  no labels in pickle  in given reproducer.

**Comment by pseudotensor** [comment]
[catshapproblem2.zip](https://github.com/catboost/catboost/files/7949738/catshapproblem2.zip)

```
python catshapproblem.py
```

```
Traceback (most recent call last):
  File "catshapproblem.py", line 22, in <module>
    assert np.isclose(preds_raw, np.sum(preds_shap, axis=1)).all(), "catboost shapley does not sum up correctly: %g" % max_abs_error
AssertionError: catboost shapley does not sum up correctly: 0.165568
```

**Comment by gcoter** [comment]
Hi there, any news on this issue?
