### ISSUE TITLE
Error: max query size supported on GPU is 1023, got 2008

### ISSUE THREAD

**Issue by bbaychev123** [catboost/catboost#1128]
Problem: Getting an error while trying to train a ranking catboost on GPU with loss_function = "YetiRank"
catboost version: 0.20.1
Operating System: Linux Mint 19.3 Cinnamon v4.4.5 64-bit
CPU: Intel i7-8750H @ 2.2GHz x 6
# GPU: 1 (GeForce RTX 2070)
RAM: 32GB

I'm trying the following:
params = {'loss_function':'YetiRank',
         'learning_rate': .05,
         'depth': 8,
         "task_type":"GPU",
         "n_estimators":500,
          "one_hot_max_size":15,
         }

catboost = CatBoost(params)
catboost.fit(train_pool,plot=True)

and I'm getting this error: 
CatBoostError: catboost/cuda/targets/querywise_targets_impl.h:295: Error: max query size supported on GPU is 1023, got 2008

This exact operation works fine with a smaller amount of data, but I need to train on the large train dataset. What should I do?

**Comment by annaveronika** [comment]
You should make groups of size no greater than 1023. You can still use as big of a dataset as you want, but group sizes are restricted.

**Comment by bbaychev123** [comment]
Thanks Anna Veronika

**Comment by TraderZen1617** [comment]
I am facing exact same problem but I do not know how to solve it -  How does one manage the group size? 

# Define CatBoostRanker parameters (tuned for robust performance).
    params = {
        "iterations": 1000,  # Maximum number of boosting iterations
        "learning_rate": 0.1,  # Step size for each iteration
        "depth": 6,  # Tree depth
        "loss_function": "YetiRank",  # Ranking objective for CatBoost
        "eval_metric": "NDCG",  # Evaluation metric (NDCG is commonly used for ranking)
        "random_seed": 42,  # For reproducibility
        "od_type": "Iter",  # Overfitting detector type
        "od_wait": 50,  # Number of iterations to wait before early stopping
        "verbose": 100,  # Print training info every 100 iterations
        "task_type": "GPU",  # Enable GPU training
        "devices": "0",  # Use the first GPU (adjust if needed)
        "gpu_ram_part": 0.95,  # Percentage of GPU RAM to use
    }

    model = CatBoostRanker(**params)

**Comment by andrey-khropov** [comment]
> How does one manage the group size?

All the samples in your dataset are marked with some group id (the samples are ranked within subsets with the same group id), just check that there are group ids that mark subsets with more than 1024 members. Maybe try to remove less valuable samples from such groups to keep size under the limit or drop them altogether if there are not many of them so they won't affect the result of the training too much.
