### ISSUE TITLE
Efficient implementation of third party losses. 

### ISSUE THREAD

**Issue by r-zenine** [catboost/catboost#1129]
Hi Everyone, 

I am trying to come up with an efficient implementation of focal loss for `catboost`. 

As of today, since I have to use the index based `python` api, both naive `Cython` or `C++` implementations considerably increase my training time. We are talking about approximately `10x` slowdown as compared to the standard `catboost` losses.
 
I would like to have access to the underlying `_arr` in `_FloatArrayWrapper` to be able to come up with an efficient `C++` or `Cython` (preferably `C++`) focal loss implementation for `catboost`. 

Is it possible to update this declaration to allow external `c++` code to access the `raw` pointer? 

https://github.com/catboost/catboost/blob/756892ed5622c4219a2942a93945af18a21733cf/catboost/python-package/catboost/_catboost.pyx#L1476

If you deem the change interesting. We could discuss the design and once we come up with a good design. I can work on the PR and update the documentation. ( I have some time for this). 

Thanks Everyone

**Comment by LyzhinIvan** [comment]
Hi, @r-zenine !

This tutorial should be useful for you: https://github.com/catboost/tutorials/blob/master/custom_loss/custom_metric_tutorial.md

**Comment by r-zenine** [comment]
@LyzhinIvan Thanks. It seems use-full. 
Maybe we can reference it in the official documentation ? It might help others. 
What do you think ?

**Comment by r-zenine** [comment]
Hi @LyzhinIvan , 
I already looked at this tutorial. My issue is that the interface for `approx` prevents me for implementing a vectorized version of the loss I want. 

My issue is that swapping the `logloss` for my custom loss multiplies my training time by 4. I would loved to have an api that would allow for vectorized implementation of custom losses.

**Comment by kizill** [comment]
@r-zenine We are currently refactoring this place in code, replacing our floatwrapper with non-owning numpy array. So it'll be ready in 2 weeks. Sorry for such a long wait.

**Comment by kizill** [comment]
Since 0.26 we are using non-owning numpy.ndarray and numba.JIT for custom metrics speedup.
