### ISSUE TITLE
ShapValues and expected value possible inconsistency

### ISSUE THREAD

**Issue by ibuda** [catboost/catboost#1139]
In the code below, when using `get_feature_importance` to get ShapValues and the expected value, I am getting a strangely different "behavior" from what is described in this tutorial [notebook](https://github.com/catboost/catboost/blob/master/catboost/tutorials/model_analysis/shap_values_tutorial.ipynb).

The mentioned above code:
```
import catboost
from catboost import CatBoostClassifier, Pool
from catboost.datasets import titanic
from sklearn.model_selection import train_test_split
import numpy as np

train_df, test_df = catboost.datasets.titanic()
train_df.fillna(-999, inplace=True)
test_df.fillna(-999, inplace=True)
X = train_df.drop('Survived', axis=1)
y = train_df.Survived

cat_ix = np.where(X.dtypes != np.float)[0]
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=42)
X_test = test_df
params = {
    'iterations': 500,
    'learning_rate': 0.1,
    'eval_metric': 'Accuracy',
    'random_seed': 42,
    'logging_level': 'Silent',
}
train_pool = Pool(X_train, y_train, cat_features=cat_ix)
validate_pool = Pool(X_val, y_val, cat_features=cat_ix)
model = CatBoostClassifier(**params)
model.fit(train_pool, eval_set=validate_pool)

print(model.predict(train_pool, prediction_type='RawFormulaVal').mean().round(4))
# prints 0.7318

shap_values = model.get_feature_importance(train_pool, type="ShapValues")
expected_value = shap_values[:,-1][0]
print(expected_value.round(4))
# prints -0.5393
```
In the code above we obtain different values given by `model.predict` and by `shap_values[0,-1]`, whereas if you follow the [shap_values_tutorial.ipynb](https://github.com/catboost/catboost/blob/master/catboost/tutorials/model_analysis/shap_values_tutorial.ipynb) you would obtain same value:
```
shap_values = model.get_feature_importance(Pool(X, y), type='ShapValues')
expected_value = shap_values[0,-1]
print(expected_value.round(4), model.predict(X).mean().round(4))
# prints 22.5318 22.5318
```

After some exploration, I have found the workaround which gives the expected value for the first code (with titanic dataset):
```
shap_values.sum(axis=1).mean().round(4) # -0.7318
```
If possible, could you please explain this inconsistency and what causes it.

Thank you for a great tool that you provided the community with!

---
catboost version: 0.20.2
Operating System: Ubuntu 19.04
CPU: Intel® Core™ i5-7400 CPU

**Comment by annaveronika** [comment]
Thanks for the issue, we'll look into this!

**Comment by ek-ak** [comment]
Hi! Thank you very much for reporting the bug. This issue duplicates  #1125.  The problem was when boost_from_average was set - we didn't account for that in shap values calculation. The fix is now in code and will be out in the next release soon. The problem affected only shap values calculation, you need to retrain model to obtain correct shap values.
