### ISSUE TITLE
Custom metric, calculated each 'verbose' iterations

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#1140]
Problem:
I train catboost models on a headless server and want to plot losses and metrics, using Sacred (https://sacred.readthedocs.io/en/stable/). The loss is RMSE, the metric is 90th percentile of absolute error.
I tried to use the tutorial https://github.com/catboost/catboost/blob/master/catboost/tutorials/custom_loss/custom_loss_and_metric_tutorial.ipynb, I didn't get what I wanted.
1) I successfully reproduced the example with `eval_metric`, but in this case metric is calculated every iteration. In case of 90th percentile it becomes an unacceptably long process.
2) if the code `eval_metric=SacredMetricsSender()` is replaced with `custom_metric=SacredMetricsSender()`, I get `_catboost.CatBoostError: Invalid `custom_metric type=<class 'main.SacredMetricsSender'> : must be string or list of strings.`.`
3) Code `custom_metric='SacredMetricsSender()'` gives error `_catboost.CatBoostError: tools/enum_parser/enum_serialization_runtime/enum_runtime.cpp:32: Key 'SacredMetricsSender' not found in enum ELossFunction. Valid options are: 'Logloss', 'CrossEntropy', 'CtrFactor', 'RMSE', 'Lq', 'MAE', 'Quantile', 'Expectile', 'LogLinQuantile', 'MAPE', 'Poisson', 'MSLE', 'MedianAbsoluteError', 'SMAPE', 'Huber', 'MultiClass', 'MultiClassOneVsAll', 'PairLogit', 'PairLogitPairwise', 'YetiRank', 'YetiRankPairwise', 'QueryRMSE', 'QuerySoftMax', 'QueryCrossEntropy', 'StochasticFilter', 'PythonUserDefinedPerObject', 'UserPerObjMetric', 'UserQuerywiseMetric', 'R2', 'NumErrors', 'FairLoss', 'AUC', 'Accuracy', 'BalancedAccuracy', 'BalancedErrorRate', 'BrierScore', 'Precision', 'Recall', 'F1', 'TotalF1', 'MCC', 'ZeroOneLoss', 'HammingLoss', 'HingeLoss', 'Kappa', 'WKappa', 'LogLikelihoodOfPrediction', 'NormalizedGini', 'PairAccuracy', 'AverageGain', 'QueryAverage', 'PFound', 'PrecisionAt', 'RecallAt', 'MAP', 'NDCG', 'DCG', 'FilteredDCG', 'MultiRMSE'.`

Is it possible to use custom metrics with calculation once in verbose iterations, and if so, how?
catboost version: 0.20.2
Operating System: Linux

**Comment by annaveronika** [comment]
Yes, you need metric_period parameter
