### ISSUE TITLE
Different results when testing with c api

### ISSUE THREAD

**Issue by habiballahkhosravi** [catboost/catboost#1142]
Problem: Testing binary classification using python and c tester programs. The results are different. Is it normal?
catboost version: v0.9.1.1
Operating System: Ubuntu 16.04
CPU: Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz
# GPU:

**Comment by kizill** [comment]
No, raw prediction results should be the same no matter what interface are you using: python or c api. The only difference is that c api gives you raw formula predictions, without sigmoid function while python calcs sigmoid of raw value. Is that your case?

**Comment by habiballahkhosravi** [comment]
Thank you very much. Actually I'm new to machine learning and using catboost. Maybe the problem is how I interpret the results. Using "predict_proba" function in python, it returns a tuple for each line of the test data. The higher value presents the winner index. Using "CalcModelPredictionSingle" function in c, it returns a single double value which can be negative or positive. If positive, class 1 is the winner and if negative, class 0 is the winner. Am I wrong?

**Comment by kizill** [comment]
Yes, c api returns value beforr sigmoid, so if you want to split 0 and 1 class by 0.5 probability border  you can use simple check `raw_value>0`. If you wan specific class border, calculate `Sigmoid(raw_value) > border`
