### ISSUE TITLE
Sum models, how does it work?

### ISSUE THREAD

**Issue by oristides** [catboost/catboost#1143]
Hello,

Does anybody knows how really works Dum Models and the 3 different strategies? 

At documentation there is no especific  information and no sources of how it works. 

Thanks.

**Comment by annaveronika** [comment]
All it does, is it makes a sum of the trees of all models. One model is by definition a sum of trees.
If you are summing two models, and every of them contains 1000 trees, then the sum of these two models is a model with 2000 trees - the ones from the first model and the ones from the second model.

There are no strageties for it, it just combines all the trees from all the models that you are summing.

**Comment by annaveronika** [comment]
Oh, I see what you are asking, the ctr_merge_policy parameter. This is the way to combine hash tables with new numerical features, that are calculated from categorical features.

We'll add more details about that, but I suggest just using the default value.

**Comment by cyprienc** [comment]
Hi - would it please be possible to add more details to the ctr_merge_policy parameter ?
