### ISSUE TITLE
Load model from blob or file instance

### ISSUE THREAD

**Issue by victorbartel** [catboost/catboost#1149]
Problem: Today we can load the model by passing its path to the `load_model` method
Catboost version: 0.20.2
Operating System: Ubuntu 19.10
CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Language: Python 3.7

Hi,

Nowadays it's not very practical to load models from paths only. Especially when you work with cloud-based infrastructure where you can have your model stored in S3/GS/What-else buckets. Maybe something like `load_blob_model` could improve the situation or maybe make `load_model` capable of working with file instances (instead of paths). What do think about such features?

Many thanks.

**Comment by annaveronika** [comment]
We plan to add that. Thank you very much for the suggestion!

**Comment by kizill** [comment]
We have private method in python API for deserializing model from byte-strings, i think we can make it public. And speaking about python file-like objects - currently i don't know how to wrap them effectively to C++ input stream in Cython wrapper, guess it could be puzzling.

**Comment by victorbartel** [comment]
Hi Anna-Veronika,
Hi Stanislav,

Thanks for your reactivity guys :)

> currently i don't know how to wrap them effectively to C++ input stream

Sorry, I didn't think about this, you are right. As you say, I actually spotted prived deserialization method, that would be great to have it, kind of public.

**Comment by kizill** [comment]
Released in 0.24, thanks for waiting for so long :)
