### ISSUE TITLE
Show warning about excessive number of GPU devices for training

### ISSUE THREAD

**Issue by klimentij** [catboost/catboost#1150]
Problem: Training slows down proportionally to the number of GPUs I use. E.g. on device 0 the first 100 iterations take 15 sec, with devices 0:1 about 30 seconds an with devices 0-7 about 120 seconds. When I switch to 'CPU', it's roughly 100x slower. So the fastest way was using a single GPU. Is it a bug?

Dataset: 768 dense features (BERT embeddings vectors), 100k samples

catboost version: 0.20.2
Operating System: Debian GNU/Linux 9
CPU: 96 vCPU
GPU: 8 x V100

**Comment by kizill** [comment]
Hello! It's somehow expected, that unless single GPU is : you have relatively small dataset, in quantized format it will fit in 77MB of GPU Ram. When working with such a small data CUDA kernel startup delays and cross-device synchronization time prevails. To achieve maximum speed we suggest using as little gpu count as possible for trainig.

**Comment by klimentij** [comment]
Thank you!

**Comment by kizill** [comment]
I hope, we should at last warn user about possible performance loss or even autoselect gpu count, so i'll reopen and rename this issue .

**Comment by klimentij** [comment]
That would be awesome, thank you!  👍

**Comment by kizill** [comment]
In reality everything is much more complicated, so for now we decided to suggest users to experiment with gpu count manually to achieve best performance.
