### ISSUE TITLE
Raises "TypeError: No matching signature found" when creating Pool() object

### ISSUE THREAD

**Issue by lotest** [catboost/catboost#1151]
Problem:
catboost version:   v0.20.2
Operating System:  WSL  ubuntu18.04
CPU:  i7 8750H

The issue as title says.

Code : train_pool = Pool(train_X, train_Y, cat_features=cat_columns_names)
train_X and train_Y are pandas DataFrame.
cat_columns_names is an array of categorical column names.

**Comment by annaveronika** [comment]
Could you please provide a reproducible example, so that we can we can debug the issue?

**Comment by lotest** [comment]
> Could you please provide a reproducible example, so that we can we can debug the issue?

Thanks for your reply!

I thought I found the reason.

train_Y is of type 'object'  for my data has some lines with empty value. So causes the exception. It is different with v0.18 which means I should check the data more strictly before use is?

**Comment by annaveronika** [comment]
Ok, that's great news! I'm not sure why it worked in v0.18, but yes, you should check the types of the input data. Closing the issue then.
