### ISSUE TITLE
Problem with compiling the packages 

### ISSUE THREAD

**Issue by badzhafarov** [catboost/catboost#1154]
Problem: compiling the packages for python
catboost version: 0.20
Operating System: Ubuntu 18.04.2
CPU: i3-7100 CPU
Python 3.7.5

Hi,
I tried to compile the packages via the command line 
../../ya make -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config

but got the error

In file included from ../anaconda3/include/python3.7m/Python.h:8:
../anaconda3/include/python3.7m/pyconfig.h:1387:9: error: 'SIZEOF_SIZE_T' macro redefined [-Werror,-Wmacro-redefined]
#define SIZEOF_SIZE_T 8
        ^
../catboost/util/system/platform.h:231:9: note: previous definition is here
#define SIZEOF_SIZE_T SIZEOF_PTR
        ^
1 error generated.
Failed

**Comment by annaveronika** [comment]
Thank you for the issue, we're working on the fix now.

**Comment by andrey-khropov** [comment]
We've been unable to reproduce the error you've encountered (build was successful) but commit https://github.com/catboost/catboost/commit/663fe254dca03a6c94dce7880bcd2027b3cae080 should help. Please check whether this commit solves this issue for you.

**Comment by badzhafarov** [comment]
Thanks, I downloaded the project again and couldn't reproduce my problem.
