### ISSUE TITLE
Feature request: per-feature penalties

### ISSUE THREAD

**Issue by TrentonBush** [catboost/catboost#1155]
In some applications it would be helpful to be able to penalize the use of specific features. Some features may have higher costs to obtain or are less interpretable, which can be an important consideration when the model needs to be explained to non-technical audiences.

Another application is in time series, where a continuous time feature is useful to model changes over time, but vulnerable to overfitting because everything in a time series could be explained with enough splits on time.

For example, if feature1 has additional cost I may want to apply a penalty to it's split gains, which would result in that feature playing a reduced role in the model (lower feature importance) or possibly not get used at all.

A possible implementation for this (used by lightGBM) is to accept a vector of per-feature penalty multipliers on the split gain, applied after any L1/L2 regularization. So `gain[i] = max(0, feature_penalty_factor[i]) * gain[i]` A vector of [1,1,1] would mean no feature-specific penalization.

**Comment by annaveronika** [comment]
Thank you very much for the suggestion, we will add this functionality at some point. For now I'm adding help wanted tag, if someone is interested in contributing, we would be very happy to review the change!

**Comment by annaveronika** [comment]
This is implemented in catboost 0.23
