### ISSUE TITLE
How to store everything that is printed in the terminal when I run .fit()?

### ISSUE THREAD

**Issue by ms8909** [catboost/catboost#1157]
Problem: Unable to store what is printed in the terminal.
catboost version:
Operating System:
CPU:
# GPU:

**Comment by annaveronika** [comment]
I'm not sure it's a problem of catboost, so I would suggest to move this question to stackoverflow for example.
I recommend to write stdout to file or to look on existing files in training folder (there are files where error values are written).

**Comment by ms8909** [comment]
I am trying to train multiple models at once using redis and celery. Is there are a way to save errors and other training details in multiple files: one for each model?

**Comment by annaveronika** [comment]
You can create a different training directory for every training using train_dir parameter, then errors will be written into files in this directories.

**Comment by annaveronika** [comment]
Closing the issue, since there is no problem or feature request for catboost. Please use our chats in slack ODS and Telegram, or stackoverflow with tag catboost for discussions and tips.
