### ISSUE TITLE
Probabilistic Forecasting - CatBoostLSS

### ISSUE THREAD

**Issue by StatMixedML** [catboost/catboost#1158]
**Thank you very much for the issue and for your paper! We will implement one of the solutions in the library, because it is one of the most frequently requested features.**

_Originally posted by @annaveronika in https://github.com/catboost/catboost/issues/1148#issuecomment-576699277_

@annaveronika: Great to hear that [CatBoostLSS ](https://github.com/StatMixedML/CatBoostLSS)is getting support from the CatBoost team! Let`s get in in contact to collaborate on this!

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/issues/1148 - this is the main issue for learning prediction intervals, please don't create duplicates, I've already closed one. We'll post all the news there.
