### ISSUE TITLE
Understanding the example given in Docs, for converting categorical features to numerical features

### ISSUE THREAD

**Issue by rteja1113** [catboost/catboost#116]
Hi all, I'd be glad if someone explained how you arrived at the values of f_integer  in the example(https://tech.yandex.com/catboost/doc/dg/concepts/algorithm-main-stages_cat-to-numberic-docpage/#algorithm-main-stages_cat-to-numberic) for converting categorical features to numerical features.
I understood how you arrived at ctr but having hard time understanding f_integer
as it states, that f_integer = borderCount*(ctr-left)/(right-left), 

where borderCount = 16 for the example(number of splits for categorical feature, shouldn't this be 8? since only 3 categories are there)
and even if we assume 16 and proceed, for the first row, f_integer = (16)*(0.05-0)/(1-0) = 0.8
but for first  row it is given as 2
![screenshot from 2017-09-27 11-23-12](https://user-images.githubusercontent.com/12951831/30925248-13708ff4-a366-11e7-936a-5d749178a40d.png)

My 2nd question is how  f_integer(or)ctr is calculated for unseen classes in test-time ?

Thank You

**Comment by annaveronika** [comment]
This table was written using border_count 50, so not it's not completely correct.
Plus now we don't always convert ctr-s to integers - we currently use different binarizations. So we should change this documentation. We'll do it soon, thanks for noting.
MATRIXNET-973

**Comment by rteja1113** [comment]
Thank you @annaveronika

**Comment by annaveronika** [comment]
fixed the documentation
