### ISSUE TITLE
Unable to install catboost on Python 3.8.0

### ISSUE THREAD

**Issue by tochukwuokafor** [catboost/catboost#1163]
Problem: I'm unable to install catboost using `pip install catboost` on my Python 3.8.0
catboost version:
Operating System: Microsoft Windows 10 Home 64-bit
CPU: 16 GB RAM
# GPU: Intel (R) UHD Graphics 620

![image](https://user-images.githubusercontent.com/30937231/73288193-88a4fc80-41c8-11ea-9dcb-45a27a4bb5ed.png)

**Comment by tochukwuokafor** [comment]
I upgraded to Python 3.8.1 64-bit

**Comment by mikerinderknecht** [comment]
did you manage to install catboost with python 3.8.1?

**Comment by kizill** [comment]
@mikerinderknecht we release only x86_64 catboost version on PyPI, so i guess original problem was with Python 3.8.x x86 installed.
