### ISSUE TITLE
feature importance SHAP values fail with langevin=True

### ISSUE THREAD

**Issue by LSinev** [catboost/catboost#1164]
Problem: `CatBoostError: catboost/libs/fstr/shap_values.cpp:810: Cannot calc shap values, model contains non zero approx for zero-weight leaf`
python: 3.6
catboost version: 0.21
Operating System: Linux (Kaggle)
CPU: Yes

https://www.kaggle.com/lsinev/hr-analytics-with-logreg-catboost-sglb-and-xverse - last output step

**Comment by annaveronika** [comment]
Thanks for the issue! We're looking into this.
