### ISSUE TITLE
Instalation and PyUnicodeUCS4_FromStringAndSize error

### ISSUE THREAD

**Issue by acarvalh** [catboost/catboost#117]
Dear developers

I just installed catboost, but so far I am not being able to call it.
I am aware of the compatibility problems with pip 9.0.0, so I downgraded it, using  

pip install catboost --user
I get
Successfully installed catboost-0.2.2 numpy-1.11.1 six-1.11.0

I am getting the following error when doing:

import numpy
from catboost import CatBoostRegressor

ImportError: /XXX/lib/python2.7/site-packages/catboost/_catboost.so: undefined symbol: PyUnicodeUCS4_FromStringAndSize

thank you for advice
Xanda

**Comment by Pierromagien** [comment]
So how did you solve this problem ? I'm having the same issue when importing catboost

**Comment by newhotter** [comment]
Do you know how to get rid of this error? I face the same error when importing catboost.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python2.7/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models  # noqa
  File "/home/xxx/.local/lib/python2.7/site-packages/catboost/core.py", line 58, in <module>
    _catboost = get_catboost_bin_module()
  File "/home/xxx/.local/lib/python2.7/site-packages/catboost/core.py", line 54, in get_catboost_bin_module
    import _catboost
ImportError: /home/xxx/.local/lib/python2.7/site-packages/catboost/_catboost.so: undefined symbol: PyUnicodeUCS4_FromStringAndSize

**Comment by kizill** [comment]
Are you building from source?

**Comment by newhotter** [comment]
> Are you building from source?

yes, i build from source and the building process has no problem. 
BTW, I build and import catboost using python 2.7 with UCS2 unicode

**Comment by lihaipen** [comment]
hh

**Comment by kizill** [comment]
I suggest you missed build option `-DUSE_ARCADIA_PYTHON=no` See more information about build catboost pythin package from source on this page: https://catboost.ai/docs/installation/python-installation-method-build-from-source-linux-macos.html
