### ISSUE TITLE
Multiregression custom metric?

### ISSUE THREAD

**Issue by lambdaofgod** [catboost/catboost#1173]
How to define multiregression eval metric?

When I define my custom metric like usual metric, I get

> CatBoostError: catboost/private/libs/target/data_providers.cpp:516: Currently only multi-regression objectives work with multidimensional target

**Comment by annaveronika** [comment]
Currently custom metrics are not supported for multi regression. We'll add it at some point.
Please use staged_predict for now.

**Comment by annaveronika** [comment]
This is implemented in catboost 0.23

**Comment by sukhejai** [comment]
CatBoostError: catboost/private/libs/target/data_providers.cpp:516: Currently only multi-regression objectives work with multidimensional target

As per the above comment the by @annaveronika commented on 29 Apr its working in catboost 0.23

Seems again in latest version = 0.24.1 its not working. Can you please help me in this?

**Comment by makarbaderko** [comment]
Also don't work
`cbreg = CatBoostRegressor()
cbreg.fit(X1_train, y1_train)`

`-
CatBoostError                             Traceback (most recent call last)
<ipython-input-117-bfa963fff7eb> in <module>()
      1 cbreg = CatBoostRegressor()
----> 2 cbreg.fit(X1_train, y1_train)

2 frames
/usr/local/lib/python3.6/dist-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1256 
   1257     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1258         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1259         self._set_trained_model_attributes()
   1260 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/private/libs/target/data_providers.cpp:517: Currently only multi-regression objectives work with multidimensional target`

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
You may use this test as an example https://github.com/catboost/catboost/blob/c5ccc653f288f02b53cf2c7f8605fbcfa87e7cd4/catboost/python-package/ut/medium/test.py#L2351

**Comment by elaynousse** [comment]
How about custom multi-regression objectives?
