### ISSUE TITLE
Exception when training with sparse data on GPU

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#1175]
@temakahap 

Hello!

I am trying to fit catboost classifier with sparse matrix'es and gpu type.
And i have this error:
CatBoostError: util/generic/maybe.h:15: TMaybe is empty

Code:
model.fit(train_bootstraped, predict_bootsraped, self.cat_features,
eval_set = (self.X_validation, self.y_validation))empty

Shapes and sums:
print (train_bootstraped.shape, predict_bootsraped.shape, predict_bootsraped.sum()
self.X_validation.shape, self.y_validation.shape)
(7467, 214) (7467,) 2489 (25143, 214) (25143,)

Stackoverflow can't have this error(
Can you pls give an advice how ti avoid this erros?

Model params:
{'iterations': 1500,
'learning_rate': 0.01,
'depth': 6,
'custom_loss':'AUC',
'early_stopping_rounds': 100,
'use_best_model': True,
'task_type': 'GPU'}

**Comment by andrey-khropov** [comment]
This issue is not actually GPU specific (only sparse data-specific).
It has been fixed in the master branch and the fix will be included in the next release.
