### ISSUE TITLE
CatBoost predict differently -> if float values are rounded to less than 9 decimals when training

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1177]
**Type:** Binary classification. 
**Data:** Tabular data, only float values, normalized between 0 and 1.

**Issue (#1):** CATBOOST predicts differently -> if float values are rounded to less than 9 decimals when training.

**Issue (#2):** To make things EVEN more weird - this test’s result changes when I run it on another but 100% identical laptop? At the second laptop - it stops giving different results after 7 decimals (vs. after 8 decimals on the first laptop)?

The example code simple trains and tests. First without rounding at all and second time it rounds to the number of decimals which has been entered when executed. It then outputs in the terminal which indices are different of the two runs when prediction is done.

As you can see in the pictures there is a different when rounding to 6 and 8 decimals - but not with 9 or above.

[Download code example here](https://web.tresorit.com/l#GdP5lniXUuGMD9Vl42xoxg)

The issue exists on both Windows and  Ubuntu and no matter if CATBOOST uses CPU or GPU:

**Catboost version:** 0.21
**Operating System:** Windows 10 / Ubunbu 18.04
**CPU:** Intel i9 6 cores / AMD Threadripper 16 cores
**#GPU:** 1 / 3

<img width="843" alt="catboost_floating_issue" src="https://user-images.githubusercontent.com/3837165/74600643-ec2a9780-50ad-11ea-836d-3a35bb4f14e3.png">

**Comment by kizill** [comment]
Internally, we work with features in float32 interpretation that gives us ~8 decimal digits precision.  In your case you have some columns, where rounding to 8 digits makes some values identical that slightly changes feature values distribution and affects quantization grid. On a dataset with only 1780 objects even small change in data distribution in features grid could affect training, especially when using Ordered boosting.
