### ISSUE TITLE
Python has stopped working when plot_tree

### ISSUE THREAD

**Issue by cmougan** [catboost/catboost#1178]
Problem: Python has stopped working // Kernels appears to have died when plotting tree
catboost version: 0.21
Operating System: Windows 7

![image](https://user-images.githubusercontent.com/43068386/74719709-db585e00-5234-11ea-9d75-36d2cae41784.png)

![image](https://user-images.githubusercontent.com/43068386/74719733-e3180280-5234-11ea-89a7-1133fcd9b551.png)

cb.get_all_params()

{'approx_on_full_history': False,
 'bayesian_matrix_reg': 0.10000000149011612,
 'best_model_min_trees': 1,
 'boost_from_average': False,
 'boosting_type': 'Plain',
 'bootstrap_type': 'MVS',
 'border_count': 254,
 'class_names': [0, 1],
 'classes_count': 0,
 'depth': 6,
 'eval_metric': 'Logloss',
 'feature_border_type': 'GreedyLogSum',
 'fold_len_multiplier': 2,
 'fold_permutation_block': 0,
 'has_time': False,
 'iterations': 1000,
 'l2_leaf_reg': 3,
 'leaf_estimation_backtracking': 'AnyImprovement',
 'leaf_estimation_iterations': 10,
 'leaf_estimation_method': 'Newton',
 'learning_rate': 0.06418699771165848,
 'loss_function': 'Logloss',
 'model_shrink_mode': 'Constant',
 'model_shrink_rate': 0,
 'model_size_reg': 0.5,
 'nan_mode': 'Min',
 'permutation_count': 4,
 'random_seed': 0,
 'random_strength': 1,
 'rsm': 1,
 'sampling_frequency': 'PerTree',
 'score_function': 'Cosine',
 'sparse_features_conflict_fraction': 0,
 'subsample': 0.800000011920929,
 'task_type': 'CPU',
 'use_best_model': False}
[tenfifteen.zip](https://github.com/catboost/catboost/files/4226053/tenfifteen.zip)

​

**Comment by annaveronika** [comment]
Could you provide the file with the model?

**Comment by cmougan** [comment]
@annaveronika  I uploaded the file in the zip.

**Comment by cmougan** [comment]
> Could you provide the file with the model?
@annaveronika I uploaded the file in the zip.

**Comment by LyzhinIvan** [comment]
Hello, @cmougan!
The fix for this issue will be in the next release. Right now you can pass pool as second parameter to plot_tree and it will work.

**Comment by cmougan** [comment]
> Hello, @cmougan!
> The fix for this issue will be in the next release. Right now you can pass pool as second parameter to plot_tree and it will work.

You mean like this @LyzhinIvan ?
cb.plot_tree(tree_idx=0,pool=None)
I get the same error

**Comment by LyzhinIvan** [comment]
No, put your learn pool as second parameter. It is always required if your model has one-hot features to build correct split description, but for models without one-hot features (like yours) it will be optional since the next release.

**Comment by annaveronika** [comment]
The fix is on github.
