### ISSUE TITLE
Get features bug

### ISSUE THREAD

**Issue by totaki** [catboost/catboost#118]
I have train_x(DataFrame) and train_y(Series). When i try get_feature_importance on my estimator, i get error 
```
CatboostError: Length of label=1 and length of data=891 is different.
```
I going to code and find

```python
if not isinstance(y, Sequence):
     y = [y]
```
All time if this True when get labels len = 1. I think this bad idea

Ok. I try make same from Pool object and get same problem but from cpp code
```python
pool = Pool(train_x, train_y)
init_estimator.get_feature_importance(pool)
```
```
CatboostError: catboost/libs/algo/calc_fstr.cpp:187: train and test datasets should have the same feature count
```

**Comment by nikitxskv** [comment]
@totaki Hello!
Thank you for report!
This bug should be fixed in the last version.

**Comment by ferasterkawi** [comment]
Hello #^_^#

Same problem:
_catboost.CatBoostError: Length of label=1 and length of data=268760 is different.

Is this issue fixed???

Thanks

**Comment by annaveronika** [comment]
Yes, the issue above should be fixed.
