### ISSUE TITLE
Decision boundary specification in binary classification metrics.

### ISSUE THREAD

**Issue by nikitxskv** [catboost/catboost#1181]
You need to add a parameter to all binary classification metrics (Accuracy, Precision, Recall, ...), which would set the decision boundary when calculating the metric. Now this border is always equal to 0.5 and it is not convenient:
https://github.com/catboost/catboost/blob/master/catboost/libs/metrics/caching_metric.cpp#L360

**Comment by annaveronika** [comment]
This is implemented in catboost 0.23

**Comment by joeljohnmathew** [comment]
@annaveronika  how about for multi classification, how to set decision boundary?

**Comment by annaveronika** [comment]
In multiclass classification there is no need for decision boundary: the class with maximum probability is selected

**Comment by joeljohnmathew** [comment]
@annaveronika thanks for your response.
