### ISSUE TITLE
Cant run auto plot

### ISSUE THREAD

**Issue by N1ke72** [catboost/catboost#1186]
Problem: Hey! I have a problem. The problem is: despite i`ve activated "plot=True" and installed widgets (turn on it also), graps don`t plotting while solution running.
I used example from your website with the following code:
"w = catboost.MetricVisualizer('/crossentropy/')
w.start()"

and as the output i have just some world:
"MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))" without grap.
What should I do?

So I use anaconda with Python 3.7+ and Jupiter Notebook launched from anaconda.

**Comment by annaveronika** [comment]
I don't think there is a problem in catboost, you probably have not installed or not activated the widgets. Maybe you installed ipywidgets to some other python.
Try again, when you install everything correctly, it should work.

**Comment by annaveronika** [comment]
I don't see how we can help here, so closing the issue.
