### ISSUE TITLE
Model metadata - classes_count incorrectly set

### ISSUE THREAD

**Issue by bduclaux** [catboost/catboost#1193]
Problem: classes_count=0 when training a multiclass model
catboost version: 0.21 - cmdline
Operating System: Linux
CPU: 1

The multiclass_params.classes_count value is always set to zero when training a multiclass model.
How to reproduce :
- Train a dummy classifier with several classes.
- Run  catboost metadata dump -m model.bin

Here is a sample output with 7 classes:
`multiclass_params	{"classes_count":0,"class_names":["class1","class2","class3","class4","class5","class6","class7"],"class_to_label":[0,1,2,3,4,5,6]}
`

**Comment by annaveronika** [comment]
This is correct behavoir: this is the value of the training parameter classes_count, it is not the same as number of classes in your training dataset.

classes_count parameter might be set by the user if for example training dataset contains classes 0,1,3 and user wants the predictions to return a value for class 2.
If classes_count was not set by the user, then in metadata it is stored with default value 0.

**Comment by bduclaux** [comment]
Thanks ! Very clear.
