### ISSUE TITLE
Error on the usage examples about CV

### ISSUE THREAD

**Issue by vba34520** [catboost/catboost#1194]
Problem: The cross-validation example on catboost.ai has a error.
catboost version: 0.21
Operating System: Windows 7
CPU: Core i5-6500

[The cross-validation example on catboost.ai](https://catboost.ai/docs/concepts/python-usages-examples.html#cross-validation) is:
```python
from catboost import Pool, cv

cv_data = [["France", 1924, 44],
           ["USA", 1932, 37],
           ["Switzerland", 1928, 25],
           ["Norway", 1952, 30],
           ["Japan", 1972, 35],
           ["Mexico", 1968, 112]]

labels = [1, 1, 0, 0, 0, 1]

cat_features = [0]

cv_dataset = Pool(data=cv_data,
                  label=labels,
                  cat_features=cat_features)

params = {"iterations": 100,
          "depth": 2,
          "loss_function": "Logloss",
          "verbose": False}

scores = cv(cv_dataset,
            params,
            fold_count=2, 
            plot="True")
```

It cause:
```
CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/private/libs/algo/tensor_search_helpers.cpp:443: Too few sampling units (subsample=0.8, bootstrap_type=MVS): please increase sampling rate or disable sampling
```
Looking forward for your help!

**Comment by shgoren** [comment]
I am also encountering the same error in my own code
would love to get an explanation to what is causing it

I'm getting this error during parameter tuning using functions that I wrote
the weird thing is for the first ~100-200 runs everything is fine and then I start getting this error for almost every run of train.

Thanks

**Comment by annaveronika** [comment]
Thanks for the report, we'll look into this!

**Comment by annaveronika** [comment]
The fix is in code and will be out in the next release. For now you could build from source to overcome the problem. Thanks again for reporting it!

**Comment by parisaazimaee** [comment]
hi @annaveronika ! i am getting this error:
_catboost.CatBoostError: catboost/private/libs/algo/tensor_search_helpers.cpp:502: Too few sampling units (subsample=0.9, bootstrap_type=MVS): please increase sampling rate or disable sampling
i am training a Catboost Regressor model and i am not sure why i am getting this

**Comment by nniaki01** [comment]
For anyone who lands here, I noticed that the reason I was getting this error for **CatBoostRegressor** was because of having a mathematically undefined (`inf`) value in my training set targets.
