### ISSUE TITLE
RangeIndex VS Int64Index for classification prediction

### ISSUE THREAD

**Issue by DavidDufourRausell** [catboost/catboost#1199]
Problem: I trained a CatBoostClassifier model in Amazon Sage Maker. The training data had RangeIndex as index, while the prediction dataframe had Int64Index as index. The predictions were totally different than when transforming the index to RangeIndex with `df.reset_index(drop=True)`. Anyone knows why is this happening? Is it normal or is it a real issue? Thanks.

catboost version: 0.22
Operating System: Linux 4.14.165-102.185.amzn1.x86_64

**Comment by LyzhinIvan** [comment]
Hi, @DavidDufourRausell! Sorry for very long response. I can't reproduce such behavior - I get the same prediction with Int64Index and RangeIndex. If you can reproduce it, please, provide a reproducible script and reopen the issue.
