### ISSUE TITLE
C API Feature request for Multiclass models

### ISSUE THREAD

**Issue by bduclaux** [catboost/catboost#1201]
Hello,

We are using a multiclass model with many classes (>1000) with the C/C++ API.
When doing inference for a specific record, the engine returns a float vector with nb_classes dimensions, which consumes memory (4*nb_records bytes).
In our application, we actually have to needs:
- do a prediction for a specific class ID (from 0 to nb_classes-1) known at runtime
- get the prediction for the most probable class, and return its ID (from 0 to nb_classes-1)

As we are doing inference in batch, it would be great to have two new API methods along these lines:
```
- predict_most_probable_class ( const vector<float*> &float_features, int float_dim, const vector<int*> &hashed_cat_features, int hash_cat_dim) 
=> returns a vector of pairs<class_id, float> representing the most probable class for each record and its prediction (RawFormula)

- predict_specific_class (unsigned int class_id, (same as above...)) 
=> returns a vector of float representing the prediction for the specific class_id

```

Hope this makes sense. I believe there is everything "under the hood" to implement these API extensions. Happy to contribute!

**Comment by andrey-khropov** [comment]
Released in 0.26.
