### ISSUE TITLE
CatboostError after getting SHAP values for new samples

### ISSUE THREAD

**Issue by mrkoloev** [catboost/catboost#1202]
Problem: 
Hello.
My model has been trained with Catboost. Is it possible to get shap values for new samples?

Here is my code:
```
import catboost
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
import pandas as pd
import numpy as np
import shap
from shap import TreeExplainer

df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df = df.drop(columns='PassengerId', axis = 1)
df = df.rename(columns={'Survived':'y'})

#object vars
cat_vars = df.select_dtypes(include=['object']).columns
#filling empty
df[cat_vars] = df[cat_vars].fillna('')

#split train-test
X = df[[i for i in df.columns if 'y' != i]]
y = df['y']
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42, test_size = 0.33)

#cat vars
cat_vars_index = [list(i) for i in np.where(X_train.dtypes == 'object')][0]

model = CatBoostClassifier(
                               iterations = 20
                               , learning_rate = 0.1
                               )
model.fit(X_train,y_train, eval_set=(X_test,y_test), cat_features=cat_vars_index, plot=False,verbose=False)

X_sample = [X_test.iloc[111,:]]

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_sample)
```

But then i got this Error.
`CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=1]="Lovell, Mr. John Hall ("Henry")": Cannot convert 'b'Lovell, Mr. John Hall ("Henry")'' to float`

What am I doing wrong?

catboost version: 0.21
shap version: 0.34.0
Operating System: Windows 10 x64
CPU: Intel Core i7 8550U
GPU: Intel UHD 620

**Comment by annaveronika** [comment]
Have you tried the shap tutorials for catboost in our repo and in shap repo?

**Comment by gladomat** [comment]
You can find it here:
https://github.com/catboost/tutorials/blob/master/model_analysis/shap_values_tutorial.ipynb

Here's the solution:
```
shap_values = model.get_feature_importance(Pool(X, y, cat_features=cat_features), type='ShapValues')
```

**Comment by mrkoloev** [comment]
> Have you tried the shap tutorials for catboost in our repo and in shap repo?

@annaveronika  I haven't found any info how to explain model's result for new X samples with categorical features.
But I have seen some issues about it.  https://github.com/slundberg/shap/issues/662
Is this even possible?
Anyway I want to thank you for such powerful library.

**Comment by mrkoloev** [comment]
> You can find it here:
> https://github.com/catboost/tutorials/blob/master/model_analysis/shap_values_tutorial.ipynb
> 
> Here's the solution:
> 
> ```
> shap_values = model.get_feature_importance(Pool(X, y, cat_features=cat_features), type='ShapValues')
> ```

@gladomat I think this code doesn't work with new samples. I want to explain model's result for new X samples with cat features. But thanks for help.

**Comment by annaveronika** [comment]
> > You can find it here:
> > https://github.com/catboost/tutorials/blob/master/model_analysis/shap_values_tutorial.ipynb
> > Here's the solution:
> > ```
> > shap_values = model.get_feature_importance(Pool(X, y, cat_features=cat_features), type='ShapValues')
> > ```
> 
> @gladomat I think this code doesn't work with new samples. I want to explain model's result for new X samples with cat features. But thanks for help.

It does work with new samples.
