### ISSUE TITLE
thread_count error while generating Tree using pool

### ISSUE THREAD

**Issue by karun8880** [catboost/catboost#1203]
Problem: Getting an error: name 'thread_count' is not defined
catboost version: 0.22
Operating System: macOS Cateline 10.15.3
CPU: 1.8 GHz Dual-Core Intel Core i5
# GPU:
![Screenshot 2020-03-05 at 1 17 28 PM](https://user-images.githubusercontent.com/8527839/75985966-1a4d0b80-5ee5-11ea-9abb-f9715d55a426.png)

**Comment by alvaro-rodrigues** [comment]
Same error here

You can reproduce the error in this notebook:
https://github.com/catboost/tutorials/blob/master/model_analysis/visualize_decision_trees_tutorial.ipynb

https://github.com/catboost/catboost/blob/ba90237192579272e4716dd3794af48adb34c86b/catboost/python-package/catboost/core.py#L2974

**Comment by karun8880** [comment]
I tried fixing it by replacing thread_count by 10.
pool, _ = self._process_predict_input_data(pool, "plot_tree", 10) if pool is not None else (None, None)

it worked.

**Comment by karun8880** [comment]
> I tried fixing it by replacing thread_count by 10.
> pool, _ = self._process_predict_input_data(pool, "plot_tree", 10) if pool is not None else (None, None)
> 
> it worked.

Just a temporary solution though.

**Comment by annaveronika** [comment]
Looking into this.

**Comment by aponte411** [comment]
Hi, any updates on this?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
This should be fixed 4 month ago.
https://github.com/catboost/catboost/blob/37533b8943060f673dd768891669e0a80fa51111/catboost/python-package/catboost/core.py#L3336

Are you still getting this error?

**Comment by techrow-platform** [comment]
Yes, I am but maybe I need to update my version of catboost. Thanks for the update!

**Comment by aponte411** [comment]
Yes, I'm still seeing this but maybe I need to update my version of catboost. Thanks for the update!
