### ISSUE TITLE
model.plot_tree(index) error in showing tree for few indices

### ISSUE THREAD

**Issue by karun8880** [catboost/catboost#1206]
Problem:model.plot_tree(index) error in showing tree for few indices
catboost version:0.22
Operating System:macOS Catelina
CPU:Intel core i5
# GPU:
model.plot_tree(index) error in showing tree for few indices
Build a model for the mushroom dataset with tree_count_ as 782. When I tried to print the trees, I get an 
![Screenshot 2020-03-06 at 10 47 32 AM](https://user-images.githubusercontent.com/8527839/76077270-4f666600-5f98-11ea-96f9-9cfae7c67959.png)
error.

**Comment by annaveronika** [comment]
You need to pass training dataset to the plot_tree function. We'll improve the error message so that it's more clear.

**Comment by karun8880** [comment]
As per my understanding, plot_tree function takes an index of various trees built iteratively during a call to fit function. The model has already been trained, with a number of trees around 700. When I iteratively look into these trees 1 by 1 from index 0 to 700, it gives this message. In the above, the tree at index 4 is giving an error. Can you fix this?

**Comment by annaveronika** [comment]
This error tells you that you need to pass training dataset to plot_tree function to be able to plot the trees.
Training dataset is needed because it contains names of categories. The model doesn't contain them, it only contains their hashes.

**Comment by karun8880** [comment]
Thanks @annaveronika . It gets resolved. The error was earlier coming because of the call to pool for thread_count. I had temporarily fixed it.

**Comment by annaveronika** [comment]
We have fixed the error msg. The new version with a better error msg will be on pypi soon. For now you can build from source.
