### ISSUE TITLE
Some functions not defined in R

### ISSUE THREAD

**Issue by PetoLau** [catboost/catboost#121]
Hello,
I installed catboost on my two different Ubuntu servers in R.
Both versions have this problem:
```
pool1 <- catboost.from_data_frame(data = data.frame(rnorm(1000), target = runif(1000)))
Error: could not find function "catboost.from_data_frame"
```
I can find R documentation by ?catboost.from_data_frame, but R don't see the function and all similar "catboost.from" like functions and I can't use it.
Any suggestions? Thx

**Comment by nikitxskv** [comment]
@PetoLau Hello!
We have updated the R-package interface.
To load pool from the data.frame use [this](https://tech.yandex.com/catboost/doc/dg/concepts/r-reference_catboost-load-docpage/) function

**Comment by anatolix** [comment]
Probably you should remove catboost.from_data_frame from R package documentation. It is still there.

**Comment by nikitxskv** [comment]
@anatolix Thank you for report!
We'll fix it in the next version.
