### ISSUE TITLE
DeprecationWarning for collections.abc

### ISSUE THREAD

**Issue by Trollgeir** [catboost/catboost#1212]
Problem:
catboost version: 0.22
Operating System: Windows
Python: 3.7.4

I'm getting a deprecation warning when trying to wrap my catboost artifact in an MLFlow class and load it with cloudpickle.

Deprecation warning:
`lib\imp.py:342: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

Doing a stack-trace on the warning I get:
`lib\site-packages\catboost\core.py", line 53, in get_catboost_bin_module
    loaded_catboost = imp.load_dynamic('_catboost', so_path)`

I'm fairly certain this line is causing the issue, which should be moved further down in the conditional import on line 16:
https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L10

This seems to have been missed in this commit: https://github.com/catboost/catboost/commit/1356ac70716956c17f41b5c377f22517e3479d9b

**Comment by kizill** [comment]
Thank you for finding and fixing that bug! We will release a package with that fix on PyPI soon.
