### ISSUE TITLE
PairLogitPairwise not working on GPU

### ISSUE THREAD

**Issue by jcrichard** [catboost/catboost#1217]
Problem: PairLogitPairwise not working on GPU while it is working on CPU
catboost version: all
Operating System: linux
CPU:
# GPU:

Here there is no target as I just want to rank. Reproducible example:

```
from catboost import CatBoost
from catboost import Pool
train_pool = Pool(
    data=[[1,1,2],[1,1,3]], pairs=[[0,1]]
)

param = {'loss_function':'PairLogitPairwise',
         'learning_rate': .01,
         'iterations': 1000,
         'depth': 7,
         "task_type":"GPU", #switch to CPU and it works
         }
model = CatBoost(param)
model.fit(train_pool ,
    verbose=100,
    plot=False);
```

**Comment by annaveronika** [comment]
Thanks for the report, we'll look into this. Most probably the problem is that the data is so small, with regular dataset it will work. But we'll fix this, thanks!

**Comment by jcrichard** [comment]
I have the problem on a very large dataset as well.  I just made a short example for you.

Thanks

**Comment by annaveronika** [comment]
Thank you very much for the simple example, we'll look into this.

**Comment by kizill** [comment]
Fixed this issue, fix will appear in next minor release.
