### ISSUE TITLE
error msg for invalid classification objective

### ISSUE THREAD

**Issue by sumansahoo16** [catboost/catboost#1218]
Problem:
When i set my eval_metric to 'TotalF1:average=Macro',it says:
CatBoostError: catboost/libs/metrics/metric.cpp:3813: TotalF1 metric shouldn't have average parameter. Valid parameters are hints, use_weights.
I want to use Macro F1 as eval_metric.
Can anyone help?

catboost version:0.22
Operating System:Windows
CPU:: CPU

**Comment by annaveronika** [comment]
This parameter has been added a few days ago and is not yet in the released version. You need to build code from source or wait for our next release to use it.

**Comment by annaveronika** [comment]
Closing the issue, please let us know if you have more questions.
