### ISSUE TITLE
Catboost Regressor Text Feature 

### ISSUE THREAD

**Issue by gregarious9612** [catboost/catboost#1221]
Problem/Question: I was just wondering if there is a reason as to why in CatboostRegressor fit() there's no `text_features` option, when in the catboostClassifier there is. Not sure if its just because it's still in development or if there are other reasons as to why it's not an option.  

catboost version: 0.22
Operating System: Ubuntu 
GPU: p100

**Comment by annaveronika** [comment]
We only support text features in classification modes now. We will add support for regression at some point, but it will most probably not be soon.

**Comment by j-hartshorn** [comment]
I'm curious about why this is? Is there any particular complications in the regression context, or is it a case of finding the resource/time to implement?

**Comment by maximrohit** [comment]
Any estimate for the functionality to come out?

**Comment by bduclaux** [comment]
Hello,

I was wondering if there's an estimate release date for text features in regression ?

Thanks !

**Comment by fingoldo** [comment]
Bump, please. Any reason that prevents adding this?

**Comment by kizill** [comment]
This will be available in 1.1 version (next release).
