### ISSUE TITLE
Alphanumeric DocId in GPU-version is not supported.

### ISSUE THREAD

**Issue by vJenny** [catboost/catboost#123]
As specified in documentation [here](https://tech.yandex.com/catboost/doc/dg/concepts/input-data_column-descfile-docpage/), I can use alphanumeric DocId in my columns description file. But I've got such error: 
```
Available devices:
  0. GeForce GTX 1080 (compute capability 6.1)
Loading data...
uncaught exception:
    address -> 0x107aacf88
    what() -> "catboost/cuda/data/load_data.h:130: Only ui32 docIds are supported"
    type -> TCatboostException
uncaught exception:
    address -> 0x107aadac8
    what() -> "catboost/cuda/data/load_data.h:130: Only ui32 docIds are supported"
    type -> TCatboostException
Aborted (core dumped)
```

CatBoost 0.2.2

**Comment by annaveronika** [comment]
Our GPU implementation does not jet support the full functionality, but we are working on that. We'll fix the issue soon.

**Comment by Noxoomo** [comment]
will be fixed with next code sync;
For training you don't need docID column so you could replace it with Auxiliary column type in cd-file.

**Comment by annaveronika** [comment]
this is fixed in the last version
