### ISSUE TITLE
Error in calc_feature_statistics

### ISSUE THREAD

**Issue by karun8880** [catboost/catboost#1236]
Problem:CatBoostError: catboost/private/libs/quantized_pool_analysis/quantized_pool_analysis.cpp:386: Internal CatBoost Error (contact developers for assistance): Binarized statistics supported only for one-hot encoded features. Use one_hot_max_size when training to manage that.

catboost version:0.22
Operating System: macOS catelina
CPU: Intel i5
# GPU:
![Screenshot 2020-03-29 at 4 14 16 PM](https://user-images.githubusercontent.com/8527839/77852781-5ddf2080-71d8-11ea-9ed9-08c9c4fa21cf.png)

**Comment by khrisanfov** [comment]
Hello! I think it is because of categorical features.

https://catboost.ai/docs/concepts/python-reference_catboost_calc_feature_statistics.html

"Only models with one-hot encoded categorical features are supported. Set the one_hot_max_size parameter to a large value to ensure that one-hot encoding is applied to all categorical features in the model."

**Comment by karun8880** [comment]
Hi @khrisanfov 
I read the article, where it was written that the catboost uses a quantized pool/borders to convert categorical features into numeric. I  tried making a tree and found that it actually created a tree using the quantized values. I was just curious to know how those values are arrived at? 
In the attached screenshot, you can see that the same feature has been converted into the border as well as numeric and used at different levels. How and Why?
![Screenshot 2020-03-31 at 9 24 59 AM](https://user-images.githubusercontent.com/8527839/78004077-89295300-7331-11ea-957f-e290c4bb6820.png)

**Comment by khurramsiddiqui** [comment]
@karun8880 sorry for hijacking this post , can you please share some elementary level document or tutorial to understand conversion of categorical features into numeric one?

**Comment by karun8880** [comment]
@Khurram The following article describes the ways to convert categorical features into numeric one.

https://towardsdatascience.com/smarter-ways-to-encode-categorical-data-for-machine-learning-part-1-of-3-6dca2f71b159 <https://towardsdatascience.com/smarter-ways-to-encode-categorical-data-for-machine-learning-part-1-of-3-6dca2f71b159>



Dr. Karun Verma
Ph.D., ME(CSE), B.Tech(CSE)
Assistant Professor,
Computer Science and Engineering Department, 
Thapar Institute of Engineering and Technology, Patiala 
(Deemed to be University)
ACM Professional Member
Coordinator, Contemporisation, TIET
Vice President, Entrepreneurship Development Cell, TIET
Office Address: L-541, New Learning Block
Mobile: +919888002791

**Comment by khurramsiddiqui** [comment]
@karun8880 thanks for sharing , actually i want to know how can we control categorical encoding using catboost simple_ctr

**Comment by annaveronika** [comment]
Answering to the initial issue: as the error msg says, calc_feature_statistics method supports only one-hot encoding. You need to increase one-hot-max-size and train the model with this parameter to use calc_feature_statistics method.

As for the question, how to control categorical encoding using simple_ctr parameter, currently you need to look in the documentation, but we plan to publish a python tutorial for that at some point.
Here is the issue to follow:
https://github.com/catboost/catboost/issues/1263

**Comment by karun8880** [comment]
@annaveronika Can you please answer this one?
> In the attached screenshot, you can see that the same feature has been converted into the border as well as numeric and used at different levels. How and Why?

**Comment by annaveronika** [comment]
Here's the issue for that:
https://github.com/catboost/catboost/issues/1130

We'll write docs for that at some point, sorry for inconvenience.
