### ISSUE TITLE
SatL2

### ISSUE THREAD

**Issue by will-hill** [catboost/catboost#1242]
Problem: **Unknown score function SatL2**
catboost version: 0.22
Operating System: Ubuntu 19.10

This documentation
https://catboost.ai/docs/concepts/python-reference_parameters-list.html
mentions score_function **SatL2**
but when attempting to use it, the following CatBoostError is thrown:
catboost/private/libs/options/enum_helpers.cpp:602: Unknown score function SatL2

I peeked at this file:
https://github.com/catboost/catboost/blob/v0.22/catboost/private/libs/options/enum_helpers.cpp
And only see:
NewtonL2, NewtonCosine, Cosine, SolarL2, LOOL2, L2

**Comment by annaveronika** [comment]
Sorry, we'll update the docs. It was an experimental score, we'll remove it from docs.

**Comment by will-hill** [comment]
Thanks!

**Comment by will-hill** [comment]
@annaveronika, is the documentation part of a Github repository?  I wouldn't mind helping make a contribution, starting with documentation, but it doesn't look like the docs are part of any repo.

**Comment by annaveronika** [comment]
Unfortunately it's not a part of the repo :(
