### ISSUE TITLE
 Cannot calc shap values, model contains non zero approx for zero-weight leaf ! => Shap on top of CatBoostRegressor AND Feature importance with  catboost,type=catboost.EFstrType.ShapValues

### ISSUE THREAD

**Issue by borisRa** [catboost/catboost#1243]
Error when trying to get Shap values with internal feature importance and with Shap package as well .

catboost version: 0.22
Operating System: Ubuntu 18.04.2 LTS
CPU: Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz

Parameters : 

{'bagging_temperature': 0.9604678570183911,
 'colsample_bylevel': 0.6994285707697221,
 'l2_leaf_reg': 76.0122956324621,
'learning_rate': 0.45324288669013235,
'max_depth': 8.296986311677536,
 'n_estimators': 1056.4151255646034,
 'one_hot_max_size': 15.797230458141419}

Commands :
1)     CB_model.get_feature_importance(train_pool_catboost,type=catboost.EFstrType.ShapValues)
2)     explainer = shap.TreeExplainer(CB_model)  ;	shap_values = explainer.shap_values(train_pool)

Error  => Problem: CatBoostError: catboost/libs/fstr/shap_values.cpp:810: Cannot calc shap values, model contains non zero approx for zero-weight leaf

**Comment by borisRa** [comment]
Any update ?

**Comment by ek-ak** [comment]
Hello! Sorry for the long time response. Could you provide your model parameters?

**Comment by borisRa** [comment]
The parameters was above :)

Parameters :

{'bagging_temperature': 0.9604678570183911,
'colsample_bylevel': 0.6994285707697221,
'l2_leaf_reg': 76.0122956324621,
'learning_rate': 0.45324288669013235,
'max_depth': 8.296986311677536,
'n_estimators': 1056.4151255646034,
'one_hot_max_size': 15.797230458141419}

**Comment by ek-ak** [comment]
We need the result of command [ get_params()]( https://catboost.ai/docs/concepts/python-reference_catboost_get_params.html ) 
Also it is strange, that integer parameters  like 'n_estimators', 'max_depth' and 'one_hot_max_size' are float.

**Comment by borisRa** [comment]
{'nan_mode': 'Min',
 'eval_metric': 'MAE',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'iterations': 1056,
 'sampling_frequency': 'PerTree',
 'fold_permutation_block': 0,
 'leaf_estimation_method': 'Exact',
 'od_pval': 0,
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'boosting_type': 'Plain',
 'model_shrink_mode': 'Constant',
 'feature_border_type': 'GreedyLogSum',
 'ctr_leaf_count_limit': 18446744073709551615,
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 15,
 'l2_leaf_reg': 76.01229858398438,
 'random_strength': 1,
 'od_type': 'Iter',
 'rsm': 0.6994285583496094,
 'boost_from_average': True,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=1:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'subsample': 0.800000011920929,
 'use_best_model': True,
 'od_wait': 20,
 'random_seed': 2017,
 'depth': 8,
 'ctr_target_border_count': 1,
 'has_time': False,
 'store_all_simple_ctr': False,
 'border_count': 254,
 'classes_count': 0,
 'sparse_features_conflict_fraction': 0,
 'leaf_estimation_backtracking': 'AnyImprovement',
 'best_model_min_trees': 1,
 'model_shrink_rate': 0,
 'min_data_in_leaf': 1,
 'loss_function': 'MAE',
 'learning_rate': 0.4532428979873657,
 'score_function': 'Cosine',
 'task_type': 'CPU',
 'leaf_estimation_iterations': 1,
 'bootstrap_type': 'MVS',
 'max_leaves': 256,
 'permutation_count': 4}

**Comment by borisRa** [comment]
I am using categorical feature too.

**Comment by ek-ak** [comment]
There was a bug in shap values  calculation for models with ranking objectives, Quantile or MAE loss_functions. The fix is in code now and will be out in the next minor release. For now you could build from source to overcome the problem. Thanks for reporting it!

**Comment by annaveronika** [comment]
You can build from source now or wait for the next minor release.
