### ISSUE TITLE
How does catboost handle missing categorical values during categorical encoding and predicting?

### ISSUE THREAD

**Issue by skeller88** [catboost/catboost#1245]
I see from the [documentation](https://catboost.ai/docs/concepts/algorithm-missing-values-processing.html#categorical-features) that 

> CatBoost does not process categorical features in any specific way.

This contradicts with what the [Catboost paper](https://arxiv.org/pdf/1706.09516.pdf) says:

> For categorical variables, missing values are replaced with a special value, i.e., we treat
> missing values as a special category;

Which is correct, and if the paper is correct, what is this special value? 

Similarly, how does CatBoost handle missing categorical values during the [categorical encoding step](https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html)? Does it ignore target values of any observation with the missing categorical value?

**Comment by vroomzel** [comment]
Also, would be interesting to know what happens if during inference a model encounters a categorical feature value that it hasn't seen during training.

**Comment by annaveronika** [comment]
Every categorical feature is treated as a string. Nan categorical features are treated as string "Nan". This is done both, during training and prediction time.

**Comment by annaveronika** [comment]
Hope it helps!

**Comment by flow2k** [comment]
@annaveronika Would appreciate your help with a followup. For a categorical string feature, will empty string (`''`) be treated as the same category as NaN? Or is `''` considered to be a separate category than NaN?

**Comment by jesperbruunhansen** [comment]
Hi @annaveronika has behaviour changed since this question was asked?

I'm seeing Catboost being able to make prediction on categorical value it has never seen before in training (Regressions in my case). Is this the intended behavior and is there anyway I can ensure the model will except on unseend values (other than me self maintaining a list of the trained values, and check before prediction)?

**Comment by abhigenie92** [comment]
@annaveronika  Curious how do you deal with unseen categorical feature values at inference time?

**Comment by seetimee** [comment]
@annaveronika same question as above
