### ISSUE TITLE
cat_features not working?

### ISSUE THREAD

**Issue by mayer79** [catboost/catboost#1246]
Problem: I was using your excellent gradient booster and could not spot any difference when training with or without `cat_features`. I could reproduce the issue with the toy example below. The categorical feature has 20 levels. The training RMSE as well as the predictions are identical between the two models.

- CatBoost version: 0.22 (R package)
- OS: Windows
- CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 3601 MHz, 4 cores
- GPU: Nvidia GTX 1080

```
library(catboost)
n <- 1000
set.seed(1)
X <- data.frame(catvar = sample(1:20, n, TRUE), matrix(rnorm(10 * n), ncol = 10))
y <- rnorm(n, rowSums(X[, 2:5] - abs(X[, 1] - 5)))

pool_num <- catboost.load_pool(X, y)
pool_cat <- catboost.load_pool(X, y, cat_features = 0)

params <- list(iterations = 100, random_seed = 10)
fit_num <- catboost.train(pool_num, params = params)
fit_cat <- catboost.train(pool_cat, params = params)

catboost.predict(fit_num, pool_num)[1] # -0.2630007
catboost.predict(fit_cat, pool_cat)[1] # -0.2630007
```

When activating `task_type = "GPU", I get again twice the same prediction, namely -0.2304115 for the first observation.

**Comment by annaveronika** [comment]
For low cardinality categorical features in RMSE mode one-hot encoding is used.
If the feature is binary, then one-hot encoding works exactly the same as numeric feature.
Probably that is what you are seeing.

Other option, why you can see the same predictions, is that categorical feature is not selected into any tree.

To verify this, you can look on feature importances (for not used ones it will be 0). Also you can output selected trees, if you use python. Other option is to try logging_level='Info' which will output selected splits for every tree.

Thus, having the same result when marking the feature categorical or numeric, is ok and there are several reasons to observe this behavior.

Hope it helps, let us know if you have more questions.

**Comment by mayer79** [comment]
Thank you Anna-Veronika for your well-taken points. I was stumbling over this behaviour here https://www.kaggle.com/mayer79/m5-forecast-tidy-r-catboost with high cardinality variables with positive importance, so I am not 100% convinced yet :-).

**Comment by annaveronika** [comment]
If you think that categorical features parameter is ignored, you should do the things I listed above:
- look on feature importances and check that the features have been used
- look on the tree splits and check which splits have been selected

One more option is to pass categorical features as strings instead of numbers.

**Comment by annaveronika** [comment]
Could you check the splits or pass the strings?

**Comment by mayer79** [comment]
Testing with the small example above, here is the result:
- using character column gives error in `load.pool`
- using factor column *works and gives different result than numeric*

```
library(catboost)
n <- 1000
set.seed(1)
X <- data.frame(catvar = sample(LETTERS[1:20], n, TRUE), matrix(rnorm(10 * n), ncol = 10))
y <- rnorm(n, rowSums(X[, 2:5] - abs(X[, 1] - 5)))

# CHARACTER COLUMN DOES NOT WORK
# Error in catboost.from_data_frame(data, label, pairs, weight, group_id,  :
# Unsupported column type: character
pool_char <- catboost.load_pool(X, y, cat_features = 0)

# FACTOR COLUMN WORKS AND GIVES DIFFERENT RESULT
X$catvar <- factor(X$catvar)
pool_factor <- catboost.load_pool(X, y, cat_features = 0)

params <- list(iterations = 100, random_seed = 10)
fit_factor <- catboost.train(pool_factor, params = params)

catboost.predict(fit_factor, pool_factor)[1] # -1.357761

```

This is quite cool - the help of `catboost.load_pool` even mentions that `categorical_columns` should be factors. Maybe add a user warning/error if this is not the case?

**Comment by Steviey** [comment]
Is this the correct way to load categorical features in R in catBoost?
And if so, how can we mix numerical and categorical data this way?
And what is the meaning of 'cat_features = 0' in this context?
`pool_factor <- catboost.load_pool(X, y, cat_features = 0)`

Thank you very much.

**Comment by mayer79** [comment]
`cat_features` is the (0-based) position vector of categorical features. In my example, it is a single number because there is just one categorical variable. Just don't forget to represent them as factors!

**Comment by Steviey** [comment]
OK, I will feed param cat_feature wit a zero-based numerical vector and set categories in x as.factor()...have to test it out...
