### ISSUE TITLE
Report a type inconsistent bug?

### ISSUE THREAD

**Issue by chengxuanying** [catboost/catboost#1248]
Hi developers!

I think there is a type inconsistent bug here.
https://github.com/catboost/catboost/blob/3cde523d326e08b32caf1b8b138c2c5303dc52e5/catboost/app/bind_options.cpp#L1207

RequiredArgument is int. 
But the arg here (.Handler1T<TString>([plainJsonPtr](const TString& param) {) \
is a TString.

Maybe a type inconsistent bug?

Best,
Chengxuan

**Comment by SergeySilaev** [comment]
Hi Chengxuan!

In this case, this is not an error.
This is a very strange solution. The parameter value has the meaning of an integer, but is passed as a string everywhere in the code.

Here is a chain of calls:

https://github.com/catboost/catboost/blob/8c8888f4798f74f6ee0d10a333c4a353b02c4b24/catboost/app/bind_options.cpp#L1230

https://github.com/catboost/catboost/blob/8c8888f4798f74f6ee0d10a333c4a353b02c4b24/catboost/private/libs/options/plain_options_helper.cpp#L461-462

https://github.com/catboost/catboost/blob/8c8888f4798f74f6ee0d10a333c4a353b02c4b24/catboost/private/libs/options/system_options.cpp#L16

https://github.com/catboost/catboost/blob/8c8888f4798f74f6ee0d10a333c4a353b02c4b24/catboost/private/libs/options/system_options.h#L27

**Comment by chengsyuan** [comment]
Thanks for your very clear response. :)
By the way, I think this strange solution may make the exported APIs have unexpected errors.

**Comment by SergeySilaev** [comment]
Oops, I was wrong
This option of passing the parameter allows you to set a value with a suffix. For example: 100mb

https://github.com/catboost/catboost/blob/2d22c65a0bad99526a4f9786c27b75ee1eed60d1/catboost/cuda/train_lib/train.cpp#L63

https://github.com/catboost/catboost/blob/2d22c65a0bad99526a4f9786c27b75ee1eed60d1/catboost/private/libs/options/system_options.cpp#L81

It might be a good idea to change the parameter description and add a value check

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Fixed this bug.
