### ISSUE TITLE
CatBoostRegressor Invalid param: auto_stop_pval

### ISSUE THREAD

**Issue by theiling** [catboost/catboost#126]
The new update breaks the early stopping: When using CatBoostRegressor and the parameter auto_stop_pval, this paramter is not known anymore. Message is Invalid param: auto_stop_pval

Has this parameter changed or a new name?

Running catboost 0.2.2 from today ( 6-Oct-2017) on Linux, Ubuntu 14.04, Python 3.5

**Comment by annaveronika** [comment]
the name has changed to od_pval

**Comment by unnir** [comment]
what about to change it in the docs?

https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_catboostclassifier-docpage/

**Comment by annaveronika** [comment]
MATRIXNET-1003

**Comment by annaveronika** [comment]
We missed it, thank you for pointing out! will be fixed in the next update.

**Comment by annaveronika** [comment]
fixed now!
