### ISSUE TITLE
[R] Cannot retrieve the original training pool from a model

### ISSUE THREAD

**Issue by Athospd** [catboost/catboost#1260]
Problem: I need to access the training pool that was used to train a given model. How can I recover the training pool from a catboost.Model R object? Or a saved model?

Thank you

catboost version: 0.22
Operating System: linux ubuntu 18.04 LTS

**Comment by annaveronika** [comment]
The training pool is not saved into the model, it is not possible to recover the pool.
To save the model you need to call save_model function (https://catboost.ai/docs/concepts/r-reference_catboost-save_model.html)
Hope it helps. Closing the issue, since there is nothing to do on catboost site.
