### ISSUE TITLE
Poisson Regression doesn't give me a good performance than RMSE / Tweedie regression doesn´t work in R

### ISSUE THREAD

**Issue by OmarVivas** [catboost/catboost#1261]
Problem: Poisson Regression doesn't give me a good performance than RMSE
catboost version: 0.22
Operating System: Windows 10
CPU: Yes

I'm in a Kaggle competition (https://www.kaggle.com/c/m5-forecasting-accuracy) and here recommend use Poisson regression but in my case don´t give better result than RMSE.

Question:
- Poisson works well in R?
- When Tweedie is active to R?
- MultiRMSE works better than RMSE?

Thanks you

**Comment by annaveronika** [comment]
All modes work the same in R and in Python.
Tweedie is only supported starting from 0.23, so in 0.22 it was not supported.
It is not guaranteed that Poisson regression will work better than RMSE on a problem where it looks more suitable, so you need to experiment.
MultiRMSE is a different mode, you should use it if you have several label columns. If there is a single column then it's just RMSE.

Hope it helps!

**Comment by Mollard** [comment]
@annaveronika @OmarVivas I think there is another problem. I tried to use poisson regression with catboost in the same competition M5 (with R). I use RMSE as eval metric. Even in the learning folds, RMSE increase by iteration.  For LGBM it works in this competition, for catboost not. 

RMSE is for LGBM about 2 for both, poisson and RMSE objective.
RMSE is for CatBoost about 2 for RMSE and about 5 or 6 for poisson.

That is not just a bad result. I think there is either a requirement we do not meet or there is something wrong with the catboost internal optimization of the poisson objective.
