### ISSUE TITLE
Controlling Categorical Columns

### ISSUE THREAD

**Issue by khurramsiddiqui** [catboost/catboost#1262]
Hi ,

How catboost categorical variable are encoded ? I believe it is encoded by using target variable statistics e.g. count, mean etc. I use a list of categorical variable during fitting model as follows, does catboost use these categorical variable using target encoding in a hidden layer? 

```
cat_features = np.where(X_train.dtypes == np.object)[0] 
X, y = X_train[all_features], X_train['hasSale']
    
catboost_pool = Pool(X, y,cat_features=cat_features)
clf = cb.CatBoostClassifier(loss_function='Logloss'
                            ,task_type="CPU"
                            ,learning_rate= 0.01
                            ,iterations= 5000 
                            ,od_type="Iter"
                            ,early_stopping_rounds=500
                            ,l2_leaf_reg= 4
                            ,class_weights=[0.5153238758029979, 16.814410480349345]
                            ,random_seed=2019)

for train_index,test_index in folds.split(X,y):
    X_trn,X_tst,y_trn,y_tst=X.iloc[train_index],X.iloc[test_index],y.iloc[train_index],y.iloc[test_index]
    clf.fit(X_trn,y_trn,eval_set=(X_tst,y_tst),use_best_model=True,verbose=500,cat_features=cat_features)
    oof[test_index] = clf.predict(X_tst[all_features])
    
    validate_pool = cb.Pool(X_tst,y_tst,cat_features=cat_features)
    eval_metrics = clf.eval_metrics(validate_pool, ['Logloss'])

```

**Comment by annaveronika** [comment]
Here is the description of how categorical features are handeled:
http://learningsys.org/nips17/assets/papers/paper_11.pdf

You can also read description in docs here:
https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html

Hope it helps!

**Comment by khurramsiddiqui** [comment]
thanks @annaveronika , i have gone through your given second link but there is no example my confusion is when i give cat_features list in fitting model then catboost use categorical feature as target encoding if yes then what statistics it used by default and how can i change default statistics to some other statistics e.g. if default is count then how can i change it to mean? if catboost does not use cat_features as given during fitting model then how can i define it during fitting?

```
all_features = [x for x in X_train.columns if x not in list(uselessColumns) and x not in ('hasSale')]
cat_features = np.where(X_train[all_features].dtypes == np.object)[0] 

X, y = X_train[all_features], X_train['hasSale']
    
folds =StratifiedKFold(n_splits=5,shuffle=True,random_state=2019)
oof = np.zeros(len(X))
# Nfolds =5
# folds = KFold(n_splits=Nfolds, shuffle=True, random_state=2019)
results =[]

catboost_pool = Pool(X, y,cat_features=cat_features)
# For Bachelor
clf = cb.CatBoostClassifier(loss_function='Logloss'
                            ,task_type="CPU"
                            ,learning_rate= 0.01
                            ,iterations= 5000 
                            ,od_type="Iter"
                            ,early_stopping_rounds=500
                            ,l2_leaf_reg= 4
                            ,class_weights=[0.5241379310344828, 10.857142857142858]
                            ,random_seed=2019)

for train_index,test_index in folds.split(X,y):
    X_trn,X_tst,y_trn,y_tst=X.iloc[train_index],X.iloc[test_index],y.iloc[train_index],y.iloc[test_index]
    clf.fit(X_trn,y_trn,eval_set=(X_tst,y_tst),use_best_model=True,verbose=500,cat_features=cat_features)
    oof[test_index] = clf.predict(X_tst[all_features])
    
    validate_pool = cb.Pool(X_tst,y_tst,cat_features=cat_features)
    eval_metrics = clf.eval_metrics(validate_pool, ['Logloss'])
    results.append(min(np.array(list(eval_metrics['Logloss']))))
```

**Comment by annaveronika** [comment]
CatBoost is not using target encoding, it is using similar techniques, which are explained in two links that I've listed above. It is not possible to change the default statistics to something else. One thing you can change - you can switch between one-hot encoding or target-based statistics using one_hot_max_size parameter.

**Comment by khurramsiddiqui** [comment]
@annaveronika what these guys are talking about [https://datascience.stackexchange.com/questions/27003/catboost-categorical-features-handling-options-ctr-settings](url)
