### ISSUE TITLE
DeprecationWarning: imp module

### ISSUE THREAD

**Issue by Trollgeir** [catboost/catboost#1269]
Problem: The imp module is deprecated
catboost version: 0.23
python version: 3.7
Operating System: Windows/Linux

Issue in code: https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/core.py#L5

`/usr/local/lib/python3.7/site-packages/catboost/core.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`

This could be fixed by switching to importlib.

**Comment by kizill** [comment]
Fixed in master, will appear in next release.
