### ISSUE TITLE
Catboost Titanic tutorial doesn't work?

### ISSUE THREAD

**Issue by mf908** [catboost/catboost#127]
When I run the Catboost Titanic tutorial I get to this block

print( 'Best validation accuracy score: {:.2f}±{:.2f} on step {}'.format(
    np.max(cv_data['Accuracy_test_avg']),
    cv_data['Accuracy_test_stddev'][np.argmax(cv_data['Accuracy_test_avg'])],
    np.argmax(cv_data['Accuracy_test_avg'])
))

and it gives me an error:

ValueError                                Traceback (most recent call last)
<ipython-input-14-8f7df85fc0c5> in <module>()
      1 print( 'Best validation accuracy score: {:.2f}±{:.2f} on step {}'.format(
----> 2     np.max(cv_data['Accuracy_test_avg']),
      3     cv_data['Accuracy_test_stddev'][np.argmax(cv_data['Accuracy_test_avg'])],
      4     np.argmax(cv_data['Accuracy_test_avg'])
      5 ))

/anaconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims)
   2250 
   2251     return _methods._amax(a, axis=axis,
-> 2252                           out=out, **kwargs)
   2253 
   2254 

/anaconda/lib/python3.6/site-packages/numpy/core/_methods.py in _amax(a, axis, out, keepdims)
     24 # small reductions
     25 def _amax(a, axis=None, out=None, keepdims=False):
---> 26     return umr_maximum(a, axis, None, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation maximum which has no identity

I'm using Python 3.6.1 and when I import catboost I get

/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module '_catboost' does not match runtime version 3.6
  return f(*args, **kwds)

**Comment by nikitxskv** [comment]
@mf908 Hello!
What are your version of os, python and catboost?

**Comment by yyll008** [comment]
os, python and catboos 
I have the same problem

**Comment by mf908** [comment]
Problem was fixed when I updated to the latest version of catboost
