### ISSUE TITLE
CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:236: Feature LotConfig_CulDSac from pool must be LotConfig_Corner.

### ISSUE THREAD

**Issue by kinghendrix10** [catboost/catboost#1270]
I have this error when running catboost regressor with the following parameters:
```
asdf_model = CatBoostRegressor(depth=6, learning_rate=0.05, n_estimators=750, subsample=0.85, verbose=400)
asdf_model.fit(train_data, y_train)
```
fitting was successful but prediction, not so much

`pred = asdf_model.predict(test_data)`

I got the following error
CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:236: Feature LotConfig_CulDSac from pool must be LotConfig_Corner.

**Comment by annaveronika** [comment]
Could you please provide a minimal reproducing example? This needs to have part of the data.
From the text of the error I can assume that when you are doing predictions, the names of the features are different from the ones in train dataset.

**Comment by kinghendrix10** [comment]
I just found out the problem. The were a null value in the test data. My guess is that was what triggered the error. Thanks

**Comment by annaveronika** [comment]
The error msg seems to be not clear. Could you still try to provide us with an example, so that we could improve it?

**Comment by annaveronika** [comment]
We've improved the error msg, in the new version it will be more clear. Thanks for the issue!
