### ISSUE TITLE
Question regarding feature importance

### ISSUE THREAD

**Issue by spot92** [catboost/catboost#1276]
This is a question, and I don't believe it is a bug. What causes some feature importances to be zero? Does it mean that I do not have enough iterations? Or is there some other hyperparameter determining the number of features to use in the model if not the whole set?

**Comment by annaveronika** [comment]
If feature importance is 0, this means that feature has not been used by the model. Maybe the model has not enough trees, maybe the feature is not useful.

**Comment by annaveronika** [comment]
It is recommended to post issues that contain problems or feature requests on github and use stackoverflow with tag "catboost" for open questions and discussions.
