### ISSUE TITLE
Flatbuffers model verification failed while loading model

### ISSUE THREAD

**Issue by PZherdev** [catboost/catboost#1279]
Problem: CatBoostError: catboost/libs/model/model.cpp:655: Flatbuffers model verification failed
catboost version: 0.23
Operating System: Mac OS Mojave
CPU: Intel Core I7

Trying to learning on libsvm file in this way

```
training_set = cb.Pool('libsvm:////Users/pavelzerdev/Downloads/test_m1.libsvm')

params = {'eval_metric':
    'F1',
   'depth': 2,
  'iterations':
    3,
  'logging_level':
    'Silent',
  'loss_function':
    'Logloss',
  'l2_leaf_reg':
    3,
  'random_strength':
    1,
  'bagging_temperature':
    2,
  'learning_rate':
    0.3 }

model = cb.CatBoost(params = params)
model.fit(training_set)

model.save_model('503.cbm')

clf = cb.CatBoost().load_model('503.cbm')
```
And getting this error while loading model n : 
`CatBoostError: catboost/libs/model/model.cpp:655: Flatbuffers model verification failed`

Used LibSVM in attach

[test_m1.txt](https://github.com/catboost/catboost/files/4591923/test_m1.txt)

**Comment by kizill** [comment]
Fix is in master, will appear in next minor release
