### ISSUE TITLE
ya script security

### ISSUE THREAD

**Issue by montekki** [catboost/catboost#128]
Ya script downloads some blobs via plain http and then checks their MD5 hash here https://github.com/catboost/catboost/blob/master/ya#L7 

However, MD5 sums are no longer a good pattern of security verification, for example see https://www.alchemistowl.org/pocorgtfo/pocorgtfo14.pdf (a large pdf file that has it's own MD5 printed on the cover. This document also contains some nifty examples of MD5 collisions).

I would suggest: 

 1. moving to https
 2. checking with some stronger hash function.

**Comment by exprmntr** [comment]
Hello

We have switched links to https

**Comment by annaveronika** [comment]
@montekki Thanks for the suggestions! We've fixed 1. We will probably fix 2 together with https://github.com/catboost/catboost/issues/131

**Comment by aldanor** [comment]
> Hello
> We have switched links to https

... which made it impossible to install from behind a corporate proxies in case SSL verification fails :/

**Comment by annaveronika** [comment]
We fixed #1, we decided to not fix #2, because it's very low priority.
