### ISSUE TITLE
Add Cox Proportional Hazards Loss

### ISSUE THREAD

**Issue by jordan-melendez** [catboost/catboost#1286]
This is more of a feature request than an issue. It looks like XGBoost [now has](https://github.com/dmlc/xgboost/pull/3043) the ability to train on survival analysis data (`objective=survival:cox`), and I was wondering if it would be possible to implement natively in CatBoost.

I pulled out some of the codes from the XGBoost PR and turned it into a custom CatBoost loss/metric written in python (and sped up with Numba's `jit`, and made more numerically stable). I can share it if it would be helpful. The problem is it involves always checking if `targets` is sorted and then running `argsort` if it's not. I'm wondering if maybe if it were coded natively, then maybe the information about permutations/sorting would already exist and could be used here? Also, it is *much* slower (>10x on my data set) than training using a standard RMSE objective. This might be unavoidable, but maybe not!

I am not familiar with CatBoost's architecture or C++ otherwise I'd try a PR out myself. Thanks!

**Comment by rgeronimi** [comment]
Hi that's interesting has we have been dancing around this in XGBoost (native implementation) which lacks many CatBoost features. Could you share your CatBoost python implementation? Thx!

**Comment by kmedved** [comment]
Any chance of an update here @jordan-melendez? This would be a great feature to add to Catboost.

**Comment by jordan-melendez** [comment]
Hi all, sorry it took a while to get back on this. I extracted the essentials of the code into its own repo, which you can check out [here](https://github.com/jordan-melendez/cox-ph-glm-objective). It's really bare bones right now, and I plan on adding some notes, better documentation/comments, and adding tests in the future. But at least it's out there for anyone who wants to see it!

I agree this would be a great add to CatBoost.

**Comment by kmedved** [comment]
Thank you so much for sharing. Eager to see if the Catboost devs can add.
