### ISSUE TITLE
grid_search not available 

### ISSUE THREAD

**Issue by Idanzinner** [catboost/catboost#1288]
Problem: AttributeError: 'CatBoost' object has no attribute 'grid_search'
catboost version: 
Operating System: ubuntu
CPU: i7
# GPU: Nvidia GeForce GTX 1080 Ti

following this code :

model = CatBoost()

grid = {'learning_rate': [0.03, 0.1,0.3],
        'depth': [4, 6, 10],
        'l2_leaf_reg': [1, 3, 5, 7, 9,11,13,15],
        'iterations' : [1,10,100,1000,3000],
        'bagging_temperature': [0,0.25,0.5,0.75,1,1.5,2,3,4]}

grid_search_result = model.grid_search(grid, 
                                        cv_dataset, 
                                        cv=idx,
                                        partition_random_seed=0,
                                        calc_cv_statistics=True,
                                        search_by_train_test_split=True,
                                        refit=True,
                                        shuffle=True,
                                        stratified=None,
                                        verbose=True)

I get the error:
AttributeError: 'CatBoost' object has no attribute 'grid_search'

plz help

**Comment by annaveronika** [comment]
please check that you have the latest version of the library
