### ISSUE TITLE
Precesion not improving

### ISSUE THREAD

**Issue by khurramsiddiqui** [catboost/catboost#1289]
Problem: I have a dataset consisting of two classes 1 and 0. Dataset is imbalance and 1 is in minority class , so i am using catboost weight mechanism to adjust class balance during training. Every-time with each feature engineering or hyper parameter tuning randomly, my precision score always more or less constant and recall sky rocketed by 0.98. What i am missing or where should i invest my time please give any thought why precision is not improving and why recall improving abnormally

catboost version: 0.22
Operating System: Windows 10
# CPU:

```
cw = list(class_weight.compute_class_weight('balanced',
                                             np.unique(X_train['hasSale']),
                                             X_train['hasSale']))

X, y = X_train[all_features], X_train['hasSale']
    
folds =StratifiedKFold(n_splits=5,shuffle=True,random_state=2019)
oof = np.zeros(len(X))

results =[]

catboost_pool = Pool(X, y,cat_features=cat_features)


clf = cb.CatBoostClassifier(loss_function='Logloss'
                            ,task_type="CPU"
                            ,learning_rate= 0.01
                            ,iterations= 5000 
                            ,od_type="Iter"
                            ,early_stopping_rounds=500
                            ,l2_leaf_reg= 32
                            ,one_hot_max_size =6
                            ,class_weights=cw #[16.5153238758029979, 4.814410480349345]
                            ,random_seed=19)
```
The following distribution of target variables in percent within train and test dataset

```
hasSale (Train)
0    0.950708
1    0.049292
Name: hasSale, dtype: float64
hasSale (Test)
0    0.95662
1    0.04338
Name: hasSale, dtype: float64
```
![image](https://user-images.githubusercontent.com/7759726/81932244-d1c17500-962e-11ea-951c-cf3c68ce597e.png)

**Comment by kizill** [comment]
Closing as inactive, feel free to reopen.
