### ISSUE TITLE
feature importance with text features

### ISSUE THREAD

**Issue by tohich51** [catboost/catboost#1293]
Problem: I want you to add possibility to evaluate feature_importance on models with text features
catboost version: 0.23.1

**Comment by sagol** [comment]
`Error: catboost/libs/fstr/calc_fstr.cpp:662: CalcFstr is not implemented for models with text features`

**Comment by ddofer** [comment]
+1: It's confusing that text features aren't shown when analyzing model importance

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
This is work in progress.
Will be available in one of the upcoming releases.

**Comment by hanan-vian** [comment]
+1 if internally you use bag of the word than feature importance is trivial

**Comment by kizill** [comment]
We fixed this in master in e4a5f68d697213d00bda78950cae91bb7632602a ! Will appear in next release :)
