### ISSUE TITLE
Different learning rate for CPU and GPU

### ISSUE THREAD

**Issue by goupdown** [catboost/catboost#1294]
Problem:

catboost-0.23.exe fit --cd cd --task-type CPU -f train.csv --train-dir catboost.train.dir --delimiter , --verbose 10 -i 1000 --loss-function Logloss --model-file m.bin

Learning rate set to 0.391196

Just change CPU -> GPU

catboost-0.23.exe fit --cd cd --task-type GPU -f train.csv --train-dir catboost.train.dir --delimiter , --verbose 10 -i 1000 --loss-function Logloss --model-file m.bin

Learning rate set to 0.021102

Expected: learning rate is the same for CPU and GPU, learning rate is about 0.02
Actual: learning rate is different for CPU and GPU, for CPU learning rate is 0.39

train.csv: 5mln instancies with weights, binary classification (labels are 0 and 1), 25 features, no cat features.

Download reproducing example here: https://yadi.sk/d/tPoPwq9JO0nomw

catboost version: catboost-0.23.exe
Operating System: Windows Server 2012 R2 Standard Build 9600
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
GPU: NVIDIA GeForce GTX 1050 Ti

**Comment by goupdown** [comment]
Removed weights from train.csv. Nothing changed.

**Comment by kizill** [comment]
We've reproduced that strange behaviour and will prepare fix for it alongside with supporting MVS bootstrap on GPU. I'll appear in 0.24 release, so stay tuned.
