### ISSUE TITLE
Large difference between my train and eval RMSE

### ISSUE THREAD

**Issue by maxBombrun** [catboost/catboost#1296]
Problem: Large gap between my train and eval RMSE
catboost version: 
Operating System: Windows 10
CPU: Intel Core i9, 64GB

I am creating a linear regression model and I wanted to check the training with an eval_set to avoid overfitting, however, I am getting a large difference in error between my training and eval set. 
Any clues why is that?

Thanks
```

# generate 2 class dataset
X_set= cat_df[cat_df.columns.difference([depVar])]
y_labels= cat_df[depVar].astype(int)

# split into train/test sets
trainX, testX, trainy, testy = train_test_split(X_set, y_labels, test_size=0.3, random_state=0)

## We get the index of the categorical variables
columnCatIndex= [trainX.columns.get_loc(c) for c in trainX.columns if c in catVarList+catVarBinList]`

allPool= Pool(X_set, label=y_labels, cat_features=columnCatIndex, has_header=True)
## We create training and testing pool
trainPool= Pool(trainX, label=trainy, cat_features=columnCatIndex, has_header=True)
testPool = Pool(testX, cat_features=columnCatIndex, has_header=True)

params_bidcount = {
          'depth':4,
          'iterations':1000,
          'learning_rate':0.2, 
          'l2_leaf_reg':3,
          'one_hot_max_size': 4
         }
## We create the classifier with the parameters defined previously
catModel= cb.CatBoostRegressor(**params_bidcount)

# train the model
catModel.fit(trainPool, eval_set= Pool(testX, label=testy, cat_features=columnCatIndex, has_header=True), early_stopping_rounds=100, plot=True)
```

![trainVSevval](https://user-images.githubusercontent.com/26302444/82343374-0d738a80-99f3-11ea-8827-c5d9d261017b.png)

**Comment by khurramsiddiqui** [comment]
check distribution of your data between train and test , if there is difference between their distribution then potentially it could be between your train and eval set. 

Further there could be other reason as well , your features strength are weak with target variable , do some feature engineering or extraction plot out your feature and see how it is describing relation with target variable

**Comment by annaveronika** [comment]
Large gaps between train and test metrics are normal, usually the reason is that train and test data are distributed differently.
