### ISSUE TITLE
hyperopt  parameters tuning problem

### ISSUE THREAD

**Issue by sky1122** [catboost/catboost#1301]
Problem: hyperopt can only try tuning parameters once after that it through error

tunning code
https://github.com/Shivanandroy/Utilities/blob/c253d3293715dfd328a8beacb2611524b37e2844/CatBoost_with_HyperOpt.py

`bestTest = 0.697757127                                 

bestIteration = 1057                                   

Shrink model to first 1058 iterations.                 
nb_trees=1058                                          
  0%|          | 0/500 [03:56<?, ?trial/s, best loss=?]
job exception: Invalid cat_features[0] = 430 value: index must be < 31.

  0%|          | 0/500 [03:56<?, ?trial/s, best loss=?]
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-587-84d1c664b7ae> in <module>
     84                      algo=HYPEROPT_ALGO,
     85                      max_evals=N_HYPEROPT_PROBES,
---> 86                      trials=trials)
     87 
     88 print('-'*50)

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, timeout, loss_threshold, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    480             catch_eval_exceptions=catch_eval_exceptions,
    481             return_argmin=return_argmin,
--> 482             show_progressbar=show_progressbar,
    483         )
    484 

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/base.py in fmin(self, fn, space, algo, max_evals, timeout, loss_threshold, max_queue_len, rstate, verbose, pass_expr_memo_ctrl, catch_eval_exceptions, return_argmin, show_progressbar)
    684             catch_eval_exceptions=catch_eval_exceptions,
    685             return_argmin=return_argmin,
--> 686             show_progressbar=show_progressbar,
    687         )
    688 

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, timeout, loss_threshold, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    507 
    508     # next line is where the fmin is actually executed
--> 509     rval.exhaust()
    510 
    511     if return_argmin:

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in exhaust(self)
    328     def exhaust(self):
    329         n_done = len(self.trials)
--> 330         self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    331         self.trials.refresh()
    332         return self

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in run(self, N, block_until_done)
    284                 else:
    285                     # -- loop over trials and do the jobs directly
--> 286                     self.serial_evaluate()
    287 
    288                 self.trials.refresh()

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in serial_evaluate(self, N)
    163                 ctrl = base.Ctrl(self.trials, current_trial=trial)
    164                 try:
--> 165                     result = self.domain.evaluate(spec, ctrl)
    166                 except Exception as e:
    167                     logger.error("job exception: %s" % str(e))

/opt/anaconda3/lib/python3.7/site-packages/hyperopt/base.py in evaluate(self, config, ctrl, attach_attachments)
    892                 print_node_on_error=self.rec_eval_print_node_on_error,
    893             )
--> 894             rval = self.fn(pyll_rval)
    895 
    896         if isinstance(rval, (float, int, np.number)):

<ipython-input-587-84d1c664b7ae> in objective(space)
     55     print('nb_trees={}'.format(nb_trees))
     56 
---> 57     y_pred = model.predict_proba(X_test)
     58 
     59     #test_loss = sklearn.metrics.log_loss(y_test, y_pred, labels=list(range(10)))

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in predict_proba(self, data, ntree_start, ntree_end, thread_count, verbose)
   4027                 with probability for every class for each object.
   4028         """
-> 4029         return self._predict(data, 'Probability', ntree_start, ntree_end, thread_count, verbose, 'predict_proba')
   4030 
   4031 

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in _predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose, parent_method_name)
   1892         if verbose is None:
   1893             verbose = False
-> 1894         data, data_is_single_object = self._process_predict_input_data(data, parent_method_name, thread_count)
   1895         self._validate_prediction_type(prediction_type)
   1896 

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in _process_predict_input_data(self, data, parent_method_name, thread_count, label)
   1878                 cat_features=self._get_cat_feature_indices() if not isinstance(data, FeaturesData) else None,
   1879                 text_features=self._get_text_feature_indices() if not isinstance(data, FeaturesData) else None,
-> 1880                 thread_count=thread_count
   1881             )
   1882         return data, is_single_object

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in __init__(self, data, label, cat_features, text_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    382                     )
    383 
--> 384                 self._init(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    385         super(Pool, self).__init__()
    386 

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in _init(self, data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    946             cat_features = _get_features_indices(cat_features, feature_names)
    947             self._check_string_feature_type(cat_features, 'cat_features')
--> 948             self._check_string_feature_value(cat_features, features_count, 'cat_features')
    949         if text_features is not None:
    950             text_features = _get_features_indices(text_features, feature_names)

/opt/anaconda3/lib/python3.7/site-packages/catboost/core.py in _check_string_feature_value(self, features, features_count, features_name)
    424                 raise CatBoostError("Invalid {}[{}] = {} value type={}: must be int().".format(features_name, indx, feature, type(feature)))
    425             if feature >= features_count:
--> 426                 raise CatBoostError("Invalid {}[{}] = {} value: index must be < {}.".format(features_name, indx, feature, features_count))
    427 
    428     def _check_pairs_type(self, pairs):

CatBoostError: Invalid cat_features[0] = 430 value: index must be < 31`

catboost version:
Operating System:
CPU:
# GPU:

**Comment by sky1122** [comment]
still do not know why. but other codes in tutorial are work.

**Comment by ek-ak** [comment]
Hi! Sorry for very long response. There is now reproduce example in this issue. if you can reproduce it, please, post the minimal reproducing example and reopen the issue.
