### ISSUE TITLE
Feature Request: Time Limit Param / Callback Functionality

### ISSUE THREAD

**Issue by Innixma** [catboost/catboost#1304]
Say I want CatBoost to train until it reaches a maximum score through early stopping or after a certain time has passed.

With LightGBM, I can do:

```
import lightgbm as lgb
model = lgb.train(..., callbacks=MyCustomCallbackFunction)
```

With this callback, my callback function is called after every training iteration and I can customize how I want to stop training, such as by monitoring memory usage, a custom early stopping method, or time elapsed.

However, I have not found similar functionality with CatBoost.

This is particularly important in AutoGluon as we give the option to specify a time limit to the user, but CatBoost can sometimes exceed that time limit significantly.

Are there plans in future to add callback functionality or a time limit parameter to CatBoost?

**Comment by andrey-khropov** [comment]
Released in 0.26.
