### ISSUE TITLE
compile error in centos 7 with clang10

### ISSUE THREAD

**Issue by summernone** [catboost/catboost#1307]
Problem: 
 When compile shared library,error accured below:
catboost-0.23.2/library/cpp/json/writer/json.h:166:17: error: calling 'WriteString' with incomplete return type 'NJsonWriter::TValueContext'
            Buf.WriteString(s, hem);
            ~~~~^~~~~~~~~~~~~~~~~~~
atboost-0.23.2/library/cpp/json/writer/json.h:46:23: note: 'WriteString' declared here
        TValueContext WriteString(const TStringBuf& s, EHtmlEscapeMode hem);
                      ^
catboost-0.23.2/library/cpp/json/writer/json.h:32:11: note: forward declaration of 'NJsonWriter::TValueContext'

catboost version:0.23.2
Operating System: centos
CPU:
# GPU:

**Comment by kizill** [comment]
Hello!
We need some context - how are you building model_interface: via ya make or via makefile?
And if it is possible, can you somehow share docker recipe or docker image to help us reproduce your problem?

**Comment by kizill** [comment]
Closing issue as no response received. Feel free to reopen this issue if more info will be available!
