### ISSUE TITLE
using grid_search using gpu in python

### ISSUE THREAD

**Issue by BeomyoungKim** [catboost/catboost#1309]
Problem: can not use grid search using gpu in python
catboost version: 0.23.2
Operating System: Linux 18.04
CPU: intel xeon silver 4114 2.2ghz 10c/20t
GPU: titan rtf

```
model = CatBoostRegressor(learning_rate=0.05, loss_function = "MAE", eval_metric = 'MAE', random_seed = 777, task_type="GPU",devices='0:1')

grid = {'depth': [2, 3, 4, 6, 10],
        'l2_leaf_reg': [1, 3, 7, 9, 11],
        'subsample' :[0.2, 0.3, 0.6, 0.8],
        'rsm' : [0.3, 0.3, 0.6, 0.8],
        'border_count' :[127, 254, 511, 1023]}

grid_search_result = model.grid_search(grid, 
                                       X=cat_pool, 
                                       cv = 2),
                                       plot=True)
```

I got error 
"library/cpp/json/writer/json_value.cpp:499: Not a map"
Only fit is possible for gpu learning in python Catboost?

**Comment by AdetomiwaO** [comment]
Having the same issue as well, between yesterday and today running into this error. I see a fix for R, anything for python users? Thank yo

**Comment by IamSVP94** [comment]
Interesting theme for me too

**Comment by ovyan** [comment]
Still get the same error too.

**Comment by ovyan** [comment]
Okay, I think I found what causes it. I tried to fit (not grid search) a model like this, and it showed me an error: **Error: rsm on GPU is supported for pairwise modes only**. So removing **'rsm'** from grid search solves the above issue!
