### ISSUE TITLE
No borders for cat features

### ISSUE THREAD

**Issue by semenpetrov** [catboost/catboost#1311]
### CPU: AMD® Ryzen threadripper 1920x 12-core processor × 24 

import numpy as np
np.set_printoptions(precision=4)
from catboost import *
import random

X =[[str(random.randint(0,20)),random.randint(0,20)] for i in range(1000)]
Y = np.random.randint(0,2,1000)
model = CatBoostClassifier(
                  cat_features=[0],verbose=False )
model.fit(X,Y)
print(model.get_borders())
##### {1: [0.5, 1.5,2.5, 3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5, 11.5,12.5,13.5, 14.5,15.5,16.5, [17.5,18.5,19.5]}

X =[[random.randint(0,20),str(random.randint(0,20))] for i in range(1000)]
Y = np.random.randint(0,2,1000)
model = CatBoostClassifier(
                  cat_features=[1],verbose=False )
model.fit(X,Y)
print(model.get_borders())
##### {0: [0.5, 1.5,2.5, 3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5, 11.5,12.5,13.5, 14.5,15.5,16.5, 17.5,18.5,19.5]}

X =[[str(random.randint(0,20)),str(random.randint(0,20))] for i in range(1000)]
Y = np.random.randint(0,2,1000)
model = CatBoostClassifier(
                  cat_features=[0,1],verbose=False )
model.fit(X,Y)
print(model.get_borders())
##### {}

X =[[random.randint(0,20),random.randint(0,20)] for i in range(1000)]
Y = np.random.randint(0,2,1000)
model = CatBoostClassifier(
                  cat_features=[0,1],verbose=False )
model.fit(X,Y)
print(model.get_borders())

**Comment by LyzhinIvan** [comment]
It is expected behavior. Since we calculate some counters for categorical features or one-hot encode them, borders are meaningless. Also some numerical features can have empty set of borders if they were not used in model.
