### ISSUE TITLE
CV not utilizes all processor resources

### ISSUE THREAD

**Issue by Installka** [catboost/catboost#1315]
Problem: 
When I'm using cv(), processor utilization is about 10-30% (processor load is evenly distributed across all cores). When I'm using plain fit(), processor utilization is near 90-100%. In Russian catboost official Telegram chat (@catboost_ru) administrator told me that  this is not normal (cv should use all processor recourses). So, what could be the problem? To reproduce this problem you can use next code:
```python
from catboost import CatBoostClassifier, Pool, cv
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
```
```python
data = pd.read_csv('catboost_test.csv')
```
```python
X = data.drop(columns=['target'])
y = data['target']
X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.75, random_state=42)
```
```python
model = CatBoostClassifier(
    random_seed=42,
    iterations=2000,
    custom_loss=['AUC', 'Accuracy', 'Precision', 'Recall', 'F1']
)

model.fit(
    X_train, y_train,
    eval_set=(X_validation, y_validation),
    verbose=False,
    plot=True
)
```
```python
cv_params = model.get_params()
    
cv_params.update({
    'loss_function': 'Logloss'
})
    
cv_results = cv(
    Pool(X, y),
    cv_params,
    plot=True,
    verbose=False
) 
```
Data - [catboost_test.zip](https://github.com/catboost/catboost/files/4711788/catboost_test.zip)

catboost version: 0.23.2
Operating System: 
1) Windows 7 Pro x64 (latest updates)
2) Windows 10 Pro x64 (version 2004, build 19041.264, latest updates)

CPU: 
1) Intel Core i5-3550
2) Intel Core i7-3770K

**Comment by Installka** [comment]
I also now founded that MacBook Pro 13 (2016) with macOS 10.15.5 and Intel Core i5-6360U cv proceeds 5 times faster than on 3770K. So, maybe problem is with Windows?

**Comment by Installka** [comment]
Today I've tested this problem on virtual machine with Debian 4.9.168-1+deb9u5 and 4 cores of Intel Xeon X5675. And the problem appeared on this setup.

**Comment by kzamkov** [comment]
@dmsivkov

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Related to the CPU part of #1256

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!
