### ISSUE TITLE
Predictions on Linux machine, based on pre-trained model 

### ISSUE THREAD

**Issue by yurygubman** [catboost/catboost#1318]
Problem: Error message when I'm trying to apply predict on Linux machine 
catboost version: catboost==0.23.2
Operating System: Linux / Windows
CPU:

I trained my model on laptop - windows, catboost version  is 0.23.2. After this I saved my model to pkl file, exactly as I do with XGBoost, RF etc.:

Code:
CB = CatBoostClassifier(random_seed=42, max_depth=7, verbose=False)
CB.fit(X=x_train, y= y_train, cat_features = categorical_features)
pkl_filename = path + "catboost_model.pkl"
with open(pkl_filename, 'wb') as file:
     pickle.dump(CB, file)

I uploaded pkl file to cloud, and tried to predict on valid new data, keeping same order of columns and other rules from tutorial:
Code:
catboost_predictor = pickle.load(open(data_folder / 'catboost_amount_disagree.pkl', 'rb'))
pred_prob = catboost_predictor.predict_proba(new_data)[:, 1]

I get an error: 
  File "/usr/local/lib/python3.7/dist-packages/catboost/core.py", line 4051, in predict_proba
    return self._predict(data, 'Probability', ntree_start, ntree_end, thread_count, verbose, 'predict_proba')
  File "/usr/local/lib/python3.7/dist-packages/catboost/core.py", line 1878, in _predict
    predictions = self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "/usr/local/lib/python3.7/dist-packages/catboost/core.py", line 1275, in _base_predict
    return self._object._base_predict(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "_catboost.pyx", line 4405, in _catboost._CatBoost._base_predict
  File "_catboost.pyx", line 4410, in _catboost._CatBoost._base_predict
_catboost.CatBoostError: catboost/private/libs/options/json_helper.h:112: Error: wrong json type

"error": "[500]: (9) Internal server error: catboost/private/libs/options/json_helper.h:112: Error: wrong json type"}
 
I tried to get and print parameters (if they were properly saved) 
catboost_predictor.get_all_params()

and got an error:

(9) Internal server error: catboost/private/libs/options/plain_options_helper.cpp:735: penalties: key per_object_feature_penalties wasn't added to plain options."}

Linux version is exactly the same (catboost==0.23.2). I ran exactly the same stuff on my local computer on Windows, and all is OK, including prediction and predicted values.
I also saved model with your save_model option, but got the same error.

Can you help me?

Thanks,

Yury

**Comment by kizill** [comment]
Hello! To make things clear - what version of CatBoost do you have on your Linux server?

**Comment by yurygubman** [comment]
On my laptop (windows)catboost==0.23.2
Linux pod: catboost==0.23.2
Exactly the same version.

Yury

**Comment by kizill** [comment]
Sorry for delay - we fixed this bug in master in be91e9acac97820ddb6e61aabfed60e5fbaffa6f, there was partially backward compatibility problem. We are planning to release CatBoost with this fix in a near future.

**Comment by kizill** [comment]
Fix released in 0.24 yesterday
