### ISSUE TITLE
Big training model size with training continuation

### ISSUE THREAD

**Issue by HughhguH** [catboost/catboost#1319]
I am using catboost 0.20.2 with Python 3.7 on Windows10 and I want to apply a CatBoostRegressor on a large dataset.

1. If I train all data in once:

```
cb_model = CatBoostRegressor(iterations=1000,
                                         learning_rate=0.1,
                                         depth=12,
                                         eval_metric='RMSE',
                                         random_seed = 23,
                                         bagging_temperature = 0.2,
                                         od_type='Iter',
                                         metric_period = 100,
                                         od_wait=500
                                         )
cat_full = cb_model.fit(train,train_label,
                     eval_set=(test,test_label),
                     use_best_model=True,
                     verbose=True)

model=cat_full.save_model('model_1.model')	
```			

	 
In this case the size of model is 16 MB and I can use it easily to predict new data.

2. If I split the same data into 100 parts and use init_model parameter to train step by step:

```
batch_size = 50
start = 50
xgb_partial = None
for i in range(100):
    cat_partial = cb_model.fit(
                            train[i*start:i*start+batch_size],train_label[i*start:i*start+batch_size],
			    eval_set=(test[i*start:i*start+batch_size],test_label[i*start:i*start+batch_size]),
                            use_best_model=True,
                            init_model=cat_partial)	
			
    model=cat_partial.save_model('model_1.model')	

```

In this case, the saving model size at each iteration increase step after step and at the end the size is 1,526,214 MB in my case. 

Is it normal or something is not set properly? Is it a manageable way to update the same model with new data without having a huge size of the model at the end of the training period?

**Comment by kizill** [comment]
Hello!
First of all, CatBoost currently don't support model leaf values update on new data. `init_model` is just a way to provide model that will be used as baseline prediction before training and after training will be summed with newly trained model, so it's more about [training continuation](https://catboost.ai/docs/concepts/python-usages-examples.html?lang=en#training-continuation).
And i guess you are talking about full model size around 1.5GB, not 1.5TB. In that case it's totally normal, that your model size is so close to 16mb * 100. CatBoost builds full symmetric trees by default, so each tree has 2**12 leafs so each tree leaf values has size of (2^12 * 4) == 16KB. Each time you train new 1000 trees on top of previous model, so everything is as expected.
If i've missed something or that information is not enough - feel free to reopen and ask again:)
Thank you!

**Comment by fingoldo** [comment]
> time you train new 1000 trees on top of previous model, so everything is as expected.
> If i've missed something or that information is not enough - feel free to reopen and ask again:)
> Thank you!

Hi Stanislav, so, training continuation with init_model is not suitable for the case when there are multiple chunks of the same dataset, and Batch training with

```python
batch2 = Pool(train_data2, label=train_labels2)
batch2.set_baseline(model1.predict(batch1))
model2.fit(X=batch2)

# build resulting model

model = sum_models([model1, model2])
```
etc
should be used?
