### ISSUE TITLE
Exporting sum_models as python code

### ISSUE THREAD

**Issue by ghanshyamyadav** [catboost/catboost#1329]
Problem: I have multiple models trained on different chunks of a data set.  I am using sum_models to form a single model. However, I am not able to export the combined model as python code, because I need to set the required ```Pool``` argument: 

```save_model(self, fname, format="python", pool```

I was wondering if I would be able to merge the original pools as well, or any other way to export the combined models as python code?

catboost version: latest
Operating System: Linux
# GPU: Yes

**Comment by kizill** [comment]
Hello!
It only depends on fact whether you have categorical features or no: we have to get original (not hashed) categorical features value to build dictionary `{string: old_cityhash_func_value(string)}` (differing cityhash implementations in different libraries or even version of libraries block us from using them). So, if you have categorical features - yes, just concat your datasets and pass them to save_model, else if you only have float features - just pass any dataset as it won't be really needed. 
If my answer isn't enough - feel free to reopen issue.
Thank you!
