### ISSUE TITLE
Multi-threaded prediction

### ISSUE THREAD

**Issue by ctlaltdefeat** [catboost/catboost#133]
(this should probably be seen as a feature request rather than an issue)
Competing boosted tree libraries (xgboost, lightgbm) support predicting using multiple threads. 
As far as I am aware, in catboost this is not currently possible, and is a feature I would like to see.

**Comment by annaveronika** [comment]
It is possible - you can use -T flag to cmdline or thread_count for python.

**Comment by ctlaltdefeat** [comment]
I am setting thread_count to a number higher than one.
Training indeed uses thread_count number of threads.
However, prediction seems to use one thread regardless.

**Comment by annaveronika** [comment]
We'll take a look, thank you

**Comment by annaveronika** [comment]
Could you provide the code you are running?

**Comment by ctlaltdefeat** [comment]
```
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
import numpy as np

c_params = {
    'thread_count': 4,
    'depth': 4,
    'iterations': 100,
    'learning_rate': 0.1,
}

train = 

ind_t, ind_v = train_test_split(train.index, test_size=0.2, random_state=6)
cbm = CatBoostRegressor(**c_params, random_seed=13)
cbm.fit(
    X=train.iloc[ind_t].drop(['y'], axis=1),
    y=train.iloc[ind_t]['y'],
    eval_set=(train.iloc[ind_v].drop(['y'], axis=1),
              train.iloc[ind_v]['y'])
)
print(cbm.predict(train.iloc[ind_v].drop(['y'], axis=1)))
```
Using the Linux command "htop" shows 4 active

**Comment by ctlaltdefeat** [comment]
In general, I am using python, creating a CatBoostRegressor object with thread_count > 1, and using the Linux command "top" to see that there is only one active core when predicting. It's a bit difficult to provide code because I would need to find an example dataset on which predicting takes a long time, but the issue occurs for me in all cases.

**Comment by annaveronika** [comment]
Most probably the bottle neck of applying the model in your case is the convertion of data from matrix to our internal format. To make it faster you could use our Pool class, then no conversion will be done and applier will speed up when increasing thread count.
