### ISSUE TITLE
CatBoostError: (The handle is invalid.)

### ISSUE THREAD

**Issue by nickcorona** [catboost/catboost#1330]
Problem:
```
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-22-6457cbd19b00> in <module>
      6     Pool(X, y, cat_features=cat_features),
      7     cv_params,
----> 8     plot=True,
      9 )

~\miniconda3\lib\site-packages\catboost\core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, folds, type)
   4964     with log_fixup(), plot_wrapper(plot, [_get_train_dir(params)]):
   4965         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
-> 4966                    as_pandas, folds, type)
   4967 
   4968 

_catboost.pyx in _catboost._cv()

_catboost.pyx in _catboost._cv()

CatBoostError: (The handle is invalid.) c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/util/folder/tempdir.cpp:19: Can't create temporary directory
```
catboost version: 0.23
Operating System: Windows 10
CPU: i5 3570k
Code from python tutorial that creates this bug:
```
cv_params = model.get_params()
cv_params.update({
    'loss_function': 'Logloss'
})
cv_data = cv(
    Pool(X, y, cat_features=cat_features),
    cv_params,
    plot=True,
    as_pandas=False
)
```

**Comment by kizill** [comment]
Hello! Please make sure that your tmp directory is writeable by current user. We use [GetTempPath](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw) WinAPI function to select temp files location, so also please check TMP, TEMP or USERPROFILE environment variables and if they are set, also check their access rights for your user.

**Comment by kizill** [comment]
Hi! Is this issue still relevant?

**Comment by nickcorona** [comment]
Hi. I'm not sure. I'll check tonight.

**Comment by nickcorona** [comment]
> Hello! Please make sure that your tmp directory is writeable by current user. We use [GetTempPath](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw) WinAPI function to select temp files location, so also please check TMP, TEMP or USERPROFILE environment variables and if they are set, also check their access rights for your user.

Hey, so it works after making `C:\Windows\Temp` writeable. Thank you.
