### ISSUE TITLE
Incorrect error message for `dictionaryId` and `tokenizerId`

### ISSUE THREAD

**Issue by feeeper** [catboost/catboost#1331]
Problem:
Invalid (may be) message about `dictionaryId` or `tokenizerId` for text features preprocessing.

``` python
from catboost.datasets import rotten_tomatoes
from catboost import CatBoostClassifier

train_df, test_df = rotten_tomatoes()
train_df['synopsis'] = train_df['synopsis'].astype(str)
test_df['synopsis'] = test_df['synopsis'].astype(str)

clf = CatBoostClassifier(
    random_seed=42, 
    text_features=['synopsis'], 
    task_type='GPU',
    tokenizers = [{
        'tokenizerId': 'Space',
        'delimiter': ' ',
        'separator_type': 'ByDelimiter',
    }],
    dictionaries = [{
        'dictionaryId': 'Unigram',
        'max_dictionary_size': '50000',
        'gram_count': '1',
        'tokenizerId': 'Space'
    }],
    feature_calcers = [
        'BoW:top_tokens_count=1000',
        'NaiveBayes',
    ]
)

# fit raises exception:
# CatBoostError: catboost/private/libs/options/text_processing_options.cpp:34: 
# DictionaryOptions: no tokenizerId was specified
clf.fit(train_df[['synopsis']], train_df['rating_10'])  
```

I looked at [text_processing_options.cpp](https://github.com/catboost/catboost/blob/3381ddd01e30efdf14f79287a7b703b2d609a030/catboost/private/libs/options/text_processing_options.cpp) and find out that may be `dictionaryId` and `tokenizerId` have to be `dictionary_id` and `tokenizer_id`.

I replaced `tokenizerId` and `dictionaryId` to `tokenizer_id` and `dictionary_id` and fit worked just fine.

Working example on google colab [here](https://colab.research.google.com/drive/1rTwN70L0AcWJnjtwRjeMeykpC1GcQTxM?usp=sharing)

catboost version: 0.23.2
Operating System: Windows 10 / Google Colab
CPU: Core i7 (7th gen)
GPU: geforce gtx 1070 m

**Comment by kizill** [comment]
Hello, and thank you for noticing and fixing, it's proper fix!
We are waiting for a pull request in our repo :)
