### ISSUE TITLE
load_model from S3 location

### ISSUE THREAD

**Issue by mohitgoyal201617** [catboost/catboost#1333]
Problem: How load model works if file is present in S3/HDFS location.
catboost version:0.23.2
Operating System: EC2 centos

Right now load_model in python API takes only fileName. So how can we load it from directly from HDFS/S3, there should be some handle to load model from bytestream.

**Comment by kizill** [comment]
Hello!
I guess this should be done alongside with issue #1149 Closing as partial duplicate, please follow that issue. Thanks!
