### ISSUE TITLE
Catboost Target Encoding

### ISSUE THREAD

**Issue by khurramsiddiqui** [catboost/catboost#1336]
Problem: How can i apply target_enc on test data? I am trying to save it in some form of .npy file and read the same file for applying target_enc on new dataset , but not sure this is correct way? I read one of discussion here [https://github.com/catboost/catboost/issues/578](url) but not sure how can i do for classfication?
catboost version: 0.22
Operating System: Ubuntu 20.0.4
# CPU:

```
    import category_encoders as ce
    cat_features=['gender']

    CBE_encoder = ce.CatBoostEncoder()
    target_enc  = CBE_encoder.fit_transform(X_train[cat_features], X_train['isSale'])
    X_train     = X_train.join(target_enc.add_suffix('_cb'))
    np.save(''.join((model_data_dir,'target_enc.npy')), target_enc)
```

**Comment by kizill** [comment]
Hello!
`CatBoostEncoder` is not a part of CatBoost library. It's a work of @janmotl from https://github.com/scikit-learn-contrib/category_encoders repository, so i guess you could create issue in that repo.
