### ISSUE TITLE
How to transfer C++ format model return value to probability?

### ISSUE THREAD

**Issue by freejiebao** [catboost/catboost#1341]
Hi,

I am a new user of Catboost and I was wondering if it is possible to transfer return value of ApplyCatboostModel[1] in C++ model into a probability.  
And I work on a binary classification project, so there  will be two probabilities, one for class 0, another for class 1. How can I get probability for class 1?

Thanks

[1]https://catboost.ai/docs/concepts/c-plus-plus-api_applycatboostmodel.html

**Comment by kizill** [comment]
Hi!
You should apply sigmoid function to model prediction, like in this example:
```cpp
const double rawResult = ApplyCatboostModel({1.0f, 2.0f}, {"a", "b"});
double result = 1 / (1 + exp(-rawResult));
```
