### ISSUE TITLE
Catboosts crashes on GPU OOM

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#1347]
I have 2 GPU's on my workstation. Both report 11,175 MiB total memory.GPU:0 generally has less memory available than the GPU:1 since it's running GNOME, i.e.

<pre>| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:05:00.0  On |                  N/A |
| 42%   58C    P2    62W / 250W |   2229MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:09:00.0 Off |                  N/A |
|  0%   49C    P8    14W / 250W |     12MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+</pre>

I occasionally see the error below - it implies CatBoost tried to allocate 11032 MB from GPU 0, when only GPU 1 has this amount of memory available.

```
(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 11032 MB; Free 8260.007324 MB
uncaught exception:
    address -> 0x106e92400
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 11032 MB; Free 8260.007324 MB"
    type -> NCudaLib::TOutOfMemoryError
```

Also occasionally my python process just exits with no error, and when I set devices='1' I'm seeing:

```
(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 19495 MB; Free 10149.67744 MB
uncaught exception:
    address -> 0x106e92400
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 19495 MB; Free 10149.67744 MB"
    type -> NCudaLib::TOutOfMemoryError
```

Which is more than the total device memory. I'm running optuna in a loop, so perhaps CatBoost isn't freeing memory after each trial. Is there a way to force catboost to dispose?

**Comment by david-waterworth** [comment]
I do realize this cause is some of the hyperparameter trails results in a model which doesn't fit on my GPU - in particular I had max_depth=16. The problem is the intermittent crashing of the python interpreter with no exception message. Is there any way you can trap this exception inside the C++ code and avoid crashing python.exe?

**Comment by kizill** [comment]
Hello!
Aborting execution is incorrect in that case, we'll fix it soon.

**Comment by kizill** [comment]
Fixed in master. We've replaced practically all aborts with exceptions so when memory issues occur exception with meaningful message will be thrown.
