### ISSUE TITLE
grow_policy documentation

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#1348]
I'm looking for a deeper description of grow_policy than https://catboost.ai/docs/concepts/r-reference_catboost-train.html

Do you have a technical paper on this somewhere?

First, what does "non-terminal leaf" mean? I would assume it implies that there's some condition that determines if a leaf can be split further - i.e. the number of leaf samples = min_data_in_leaf meaning it cannot be split any further?

Second, if I understand correctly, `Depthwise` iterates over every leaf at the current depth and splits it. For `Lossguide` though does it back up? i.e. does it iterate over every leaf at every iteration trying all possible splits and then choosing the best one over all the candidate leaves and splits. Or does it always move down the tree only ever considering 2 child nodes?

**Comment by LyzhinIvan** [comment]
Hi, @david-waterworth ! We'll make section in our documentation with more deeper explanation of how different grow policies work. Here I will try to explain it briefly but clearly. 
1) SymmetricTree. The only parameter that matter is __depth__. CatBoost builds __depth__ levels of tree and at each level it  selects a condition (aka split) that gives best score for all leaves - all leaves at current level of tree are splitted by this condition.
2) Depthwise. __min_data_in_leaf__ matters now. CatBoost also builds __depth__ levels sequentially, but selects a condition that gives best score for __each leaf separately__.  So, leaves at level are splitted by different conditions. If number of training objects that fall to a leaf is less than __min_data_in_leaf__ than this leaf is not splitted.
3) Lossguide. __max_leaves__ matters now. CatBoost does not build __depth__ levels sequentially. Everytime CatBoost selects best condition for each leaf, but then splits only one of them - which condition has the best score. If number of training objects that fall to a leaf is less than __min_data_in_leaf__ than this leaf is marked as terminal and not considered later. Leaves at __depth__ level also marked as terminal and not considered later. CatBoost continues to select and split leaves until __max_leaves__ in tree reached or no more leaves that can be splitted.
 
I hope I answered your questions.

**Comment by david-waterworth** [comment]
@LyzhinIvan thanks! Just one final clarification in case 3 (Lossguide).

"Leaves at depth level also marked as terminal" - so does that mean at each **depth** you only split on one leaf - i.e. the tree is highly imbalanced?

**Comment by LyzhinIvan** [comment]
> "Leaves at depth level also marked as terminal" - so does that mean at each **depth** you only split on one leaf - i.e. the tree is highly imbalanced?
No, there I meant leaves at maximum allowed depth, that is specified by __depth__ parameter. If leaf is located at some higher level of tree, it can be splitted even if another leaf at this level was splitted already.
