### ISSUE TITLE
Catboost categorical features treatment 

### ISSUE THREAD

**Issue by michael135** [catboost/catboost#1349]
How by **default** categorical features are treated? 
(When only indexes of categorical columns are specified)

Somehow I didn't succeed to find any reference to this in the documentation.

**Comment by LyzhinIvan** [comment]
Hi, @michael135 ! You can read the explanation in our documentation [here](https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html) or watch one of our presentations at some conference, for example, [this one](https://www.youtube.com/watch?time_continue=468&v=oGRIGdsz7bM).

**Comment by michael135** [comment]
Thank you @LyzhinIvan!

In the documentation it was **not clear for me**  which from

- Borders
- Buckets
- BinarizedTargetMeanValue
- Counter

Is used by default (or maybe I've missed it somehow).

**Comment by LyzhinIvan** [comment]
Yeah, it is not very clear from documentation which counters are used by default and not all counters are described there. Actually, the choice of default counters depends on other parameters, especially on __task_type__ and __loss_function__. For most loss functions we use *Borders* + *Counter* on CPU and *Borders* + *FeatureFreq* on GPU by default. Some counters are calculated with several default priors (3 different priors for *Borders*, *Buckets* and *BinarizedTargetMeanValue*). Also you can specify which counters should be used by __simple_ctr__, __combinations_ctr__ and __per_feature_ctr__ parameters.
