### ISSUE TITLE
Error in installing R package

### ISSUE THREAD

**Issue by PetoLau** [catboost/catboost#135]
During installation of R package on Windows I got this error:

`* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/Peter/AppData/Local/Temp/RtmpC4lmBF/devtools18885a98f3e/catboost-catboost-6ce0e03/catboost/R-package/src/../../../ya.bat make -r -o ../../..
2017-10-14T14:00:51.316000 [MainThread] Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
2017-10-14T14:00:51.322000 [MainThread] Info: will fetch 'YMake' from sandbox
Config was not generated due to errors in C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py", line 1964, in <module>
    main()
  File "C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py", line 1957, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py", line 426, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py", line 534, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "C:\Users\Peter\AppData\Local\Temp\RtmpC4lmBF\devtools18885a98f3e\catboost-catboost-6ce0e03\build\ymake_conf.py", line 816, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe

Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/c1eaff0af934fd9bb8ff08d949af6b0f [..] OK
Downloading http://storage.mds.yandex.net/get-devtools-opensource/233854/371177355 [..............] OK
make: *** [all] Error 1
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/Peter/Documents/R/win-library/3.4/catboost'
Error: Command failed (1)`

Any ideas? Thx

**Comment by jonimatix** [comment]
I am experiencing same issue. Even after i installed RBuildTools, it asked again to reinstall.
Then says:  Could not find build tools necessary to build catboost

**Comment by exprmntr** [comment]
Hello

You need Visual Studio and Visual C++ 2015 Build Tools to build R-package on Windows, see #30 for details

**Comment by pverspeelt** [comment]
I'm having the same issue. 

- Windows 10
- R 3.4.2
- Visual Studio 2017 Community Edition with Windows Platform development and Desktop Development with C++ and VC++ 2015.3 v140 toolset for desktop (x86,x64) and VC++ 2017 v141 toolset (x86,x64) from the individual components tab
- C++ 2015 Build tools
- Anaconda Python 3.6

Both installing via github as installing via a local copy give the same error as above. 
"ConfigureError: Could not determine custom compiler version: cl.exe"

**Comment by sab** [comment]
DEVTOOLS-3924 (internal issue id)

**Comment by annaveronika** [comment]
We could not solve your problem.
As some people have problems with R package installation, we decided to publish compiled versions of the package. The progress will be reported in https://github.com/catboost/catboost/issues/63. For now I could only suggest to try again or to use python or command line utility.

**Comment by ved93** [comment]
Any update on compiled R package version? we are eagerly waiting.....:(

**Comment by NSchnack** [comment]
Quick Fix: use git clone or download as zip and then build the package manually. (@ved93)
```
library(devtools)
setwd("PATH_TO_FOLDER/catboost-master/catboost/R-package")
build()
install()
```

Make sure you have xcode & installed command line tools `xcode-select --install`

**Comment by annaveronika** [comment]
@ved93 We are already working on that, we'll update the issue #63 when it's done.
