### ISSUE TITLE
Issue with building catboost models in parallel foreach loop in R

### ISSUE THREAD

**Issue by AdrianAntico** [catboost/catboost#1352]
Problem: I'm trying to build multiple catboost models in R in parallel using a foreach parallel loop
catboost version: current
Operating System: Window
CPU: 18 cores
# GPU: none

I have a script set up to build a handful of catboost models on different data sets in parallel. When I run individually, they build without error. However, when I run them inside a parallel for loop, I get the following error:

```
# Set up for parallel execution----
  library(doParallel)
  packages <- c("data.table","lubridate","RemixAutoML","parallel")
  cores <- min(16L, parallel::detectCores())
  cl <- parallel::makePSOCKcluster(cores)
  doParallel::registerDoParallel(cl)
  
  # Loop through builds----
  foreach::foreach(
    i = unique(Segments),
    .packages = packages) %dopar% {
        # modeling building in here
    }
"(Access is denied.) c:/program files (x86)/goagent/pipelines/buildmaster/catboost.git/util/system/file.cpp:799: can't open "catboost_info\\catboost_training.json" with mode CreateAlways (0x00000004)"
```
I'm able to score all the models in parallel but not sure why I'm running into errors when trying to build the models in parallel. Any help is greatly appreciated :)

**Comment by LyzhinIvan** [comment]
Hi, @AdrianAntico ! You can specify unique train directory for each thread by __train_dir__ option. It should solve your problem.

**Comment by LyzhinIvan** [comment]
Or you can deny writing file by setting option __allow_writing_files=False__.

**Comment by AdrianAntico** [comment]
@LyzhinIvan  Thanks so much! That did the trick :) You guys are awesome
