### ISSUE TITLE
Catboost crashes (Segmentation Fault) with MultiClassOneVsAll, Lossguide parameters

### ISSUE THREAD

**Issue by barsa4ever** [catboost/catboost#1353]
Problem: Catboost crashes (Segmentation Fault) with MultiClassOneVsAll, Lossguide parameters
catboost version: 0.23.2 / 0.23
Operating System: Red Hat 7.5 / MacOS 10.15.5
CPU: Intel Xeon Gold 6130 CPU / 2.7 GHz Quad-Core Intel Core i7
I was able to reproduce it in two completely different environments
Code to reproduce:
```python
import pandas as pd
from catboost import CatBoostClassifier
from catboost import Pool

train_pool = Pool(pd.DataFrame([[1,1], [2,2], [3,3], [4,4], [5,5]]), pd.Series([0,1,2,3,4]))
params = {
    'iterations': 1,
    'grow_policy': 'Lossguide',
    'loss_function': 'MultiClassOneVsAll'
}
m = CatBoostClassifier(**params)
m.fit(train_pool)
```

**Comment by kizill** [comment]
Fixed in cdb4eef0e48c93045d882b3c6116c8896a580b72
