### ISSUE TITLE
Are there plans for random forest/combining classifiers?

### ISSUE THREAD

**Issue by edkazcarlson** [catboost/catboost#1359]
Are there any plans for a random forests of classifiers similar to scikit's [Voting Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html#sklearn.ensemble.VotingClassifier?)?

**Comment by kizill** [comment]
No, currently we don't have plans for implementing random forest models.
Speaking about voting classifier - CatBoostClassifier supports `sklearn` calling conventions, you could just use it as base predictor in scikit Voting Classifier.
```(python)
from catboost import CatBoostClassifier
from sklearn.ensemble import VotingClassifier
cb_classifier = CatBoostClassifier()
vclf = VotingClassifier(estimators=[('catboost', cb_classifier)], voting='hard')
```
If my answer is not full - feel free to reopen this issue :)
