### ISSUE TITLE
Can not solve the "TypeError: Singleton array cannot be considered a valid collection." issue for CatBoostRegressor

### ISSUE THREAD

**Issue by kilincali35** [catboost/catboost#1360]
Hi, I am going to implement a feature selection step into my algorithm via CatBoost. But I am constantly getting this error while I am trying to use Pool object for data. I removed almost all of my features and rows for debugging. There is only 1 integer numerical variable and 1 object categorical variable. 

If I don't use Pool, but use data directly, this time I am getting the error below. It is getting frustrating for me.
"CatBoostError: 'data' is numpy array of floating point numerical type, it means no categorical features, but 'cat_features' parameter specifies nonzero number of categorical features"

Below I am writing both version codes and error messages. I would be extremely pleased if you can suggest me a way out of this trouble, which is making me crazy. If you have answers for both circumstances, It is more than welcome of course in sake of self-development.

Thank you very much....

Here is my data summary (Service Type is categorical variable, lanecnt is numerical variable. And Time waiting is dependent):

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 2 columns):
SERVICE_TYPE    99 non-null object
LANECNT         99 non-null int32

.......TIME_WAITING
11      7.153834
75      7.277939

....SERVICE_TYPE.......LANECNT
11       Normal       10
75       Normal       11
..          ...      ...
50      Express        6
23       Normal       30

**1st version with Pooled data:**

```
cat_colz= ['SERVICE_TYPE']
num_colz = ['LANECNT']

if feature_selection == 1:
    models = dict()
    paramscat = {
            'est__depth': np.linspace(4,10,4,endpoint=True),
            'est__iterations':[250,100,500,1000],
            'est__learning_rate':[0.001,0.01,0.1,0.3],
            'est__bagging_temperature': [0,5,10,25,50],
            'est__border_count':[5,10,20,50,100]
            }
    models['catb'] = [CatBoostRegressor(cat_features = cat_colz, verbose = 0), paramscat]
    
    for key, value in models.items():
                
        start_time = timeit.default_timer()
        scorer = ['neg_mean_squared_error', 'neg_mean_absolute_error', 'r2']
        if key == 'catb':
            preprocessor = ColumnTransformer(transformers = [('num', MinMaxScaler(feature_range = (0,1)), num_colz)])
            all_pipe = Pipeline(steps = [('prep', preprocessor), ('est', value[0])])
            search_space = value[1]
            _#I both used with and without .values() versions; nothing changes_
            pooled = Pool(data = FeaturesData(
                                                 num_feature_data = np.array(df_x[num_colz].values(), dtype = np.float32), 
                                                 cat_feature_data = np.array(df_x[cat_colz].values(), dtype= 'object'), 
                                                 num_feature_names = num_colz, 
                                                 cat_feature_names = cat_colz),
                                     label =  df_y.values.ravel().tolist())
            
            grid_search = GridSearchCV(all_pipe, search_space, cv=5, verbose=1, refit = 'neg_mean_squared_error', scoring = scorer, 
                                                          return_train_score = True, n_jobs = -1)
           _#both used with and without est__cat_features, nothing changes_
            grid_search.fit(pooled, est__cat_features = cat_colz)
```

**1st version error code**

  File "..., line 432, in <module>
    grid_search.fit(pooled, est__cat_features = cat_colz)
  File "....\model_selection\_search.py", line 650, in fit
    X, y, groups = indexable(X, y, groups)
  File "....\sklearn\utils\validation.py", line 248, in indexable
    check_consistent_length(*result)
  File "....\sklearn\utils\validation.py", line 208, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File ".....\sklearn\utils\validation.py", line 208, in <listcomp>
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File ".....\sklearn\utils\validation.py", line 152, in _num_samples
    " a valid collection." % x)

TypeError: Singleton array array(<catboost.core.Pool object at 0x0000021F6F1D8AC8>, dtype=object) cannot be considered a valid collection.

**2nd version without Pooled data:**

```
for key, value in models.items():
                
        start_time = timeit.default_timer()
        scorer = ['neg_mean_squared_error', 'neg_mean_absolute_error', 'r2']
        if key == 'catb':
            preprocessor = ColumnTransformer(transformers = [('num', MinMaxScaler(feature_range = (0,1)), num_colz)])
            all_pipe = Pipeline(steps = [('prep', preprocessor), ('est', value[0])])
            search_space = value[1]
            grid_search = GridSearchCV(all_pipe, search_space, cv=5, verbose=1, refit = 'neg_mean_squared_error', scoring = scorer, return_train_score = True, n_jobs = -1)
            _#tried it both with and without est__cat_features, nothing changes_
            grid_search.fit(X = df_x, y = df_y.values.ravel(), est__cat_features = cat_colz)
```

**2nd version error code**

  File "...line 433, in <module>
    grid_search.fit(X = df_x, y = df_y.values.ravel(), est__cat_features = cat_colz)
  File "...\sklearn\model_selection\_search.py", line 739, in fit
    self.best_estimator_.fit(X, y, **fit_params)
  File "...\sklearn\pipeline.py", line 354, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "...\catboost\core.py", line 4662, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "...\catboost\core.py", line 1731, in _fit
    save_snapshot, snapshot_file, snapshot_interval, init_model
  File "...\catboost\core.py", line 1619, in _prepare_train_params
    group_weight, subgroup_id, pairs_weight, baseline, column_description)
  File "...\catboost\core.py", line 957, in _build_train_pool
    group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
  File "...\catboost\core.py", line 408, in __init__
    "'data' is numpy array of floating point numerical type, it means no categorical features,"

CatBoostError: 'data' is numpy array of floating point numerical type, it means no categorical features, but 'cat_features' parameter specifies nonzero number of categorical features

**Comment by kizill** [comment]
Hello!
We need simple runnable code snippet that would help us to reproduce your case. Thanks!

**Comment by kilincali35** [comment]
Thank you very much for the quick response. 

In the attachments you can find a reproducible data and 2 versions of codes; as I stated inside the issue. 

[Desktop.zip](https://github.com/catboost/catboost/files/4929950/Desktop.zip)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
The problem is that sklearn.model_selection.GridSearchCV cannot use catboost.Pool as data source.

Could you please try grid search from CatBoost.

Here is an example https://catboost.ai/docs/concepts/python-reference_catboost_grid_search.html

**Comment by kilincali35** [comment]
> The problem is that sklearn.model_selection.GridSearchCV cannot use catboost.Pool as data source.
> 
> Could you please try grid search from CatBoost.
> 
> Here is an example https://catboost.ai/docs/concepts/python-reference_catboost_grid_search.html

Hi, thanks for your advice. For the 1st version of problem, it seems valid. I can try it, but as you know I should sacrifice some of GridSearchCV features in order to do that, but i will try it. 

On the other hand, 2nd version of the problem is not about Catboost.Pool I think. How can I apply GridSearchCV without a Pool data source? What may be the problem in that version?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Inside grid_search, preprocessor gets applied to categorical features somehow, and replaces category labels with floats.
If preprocessor is removed from the pipeline, grid_search succeeds.

**Comment by kilincali35** [comment]
> Inside grid_search, preprocessor gets applied to categorical features somehow, and replaces category labels with floats.
> If preprocessor is removed from the pipeline, grid_search succeeds.

Hi Espetrov, yes it is valid. Somehow it doesn't recognize the "num_colz" part inside MinMaxScaler and applies the preprocessing to both of the columns. I can't figure it out, why.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Should you have further questions, please feel free to reopen this issue.
