### ISSUE TITLE
CatBoostRegressor/CatBoostClassifier doesn't have attribute n_features_in_ required by sklearn.

### ISSUE THREAD

**Issue by ogabrielluiz** [catboost/catboost#1363]
Problem: As of version 0.23.1 scikit-learn implements an attribute called `n_features_in_` which is required to create pipelines (E.g StackingRegressor). At the moment it is not possible to use Catboost within it because of that.
catboost version: 0.23.2
Operating System: Ubuntu 20.04
CPU: Ryzen 7 1800x
GPU: GTX 1070

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for reporting this issue!
We will fix it in one of the next releases.

**Comment by kizill** [comment]
Released in 0.24.1
