### ISSUE TITLE
How can I decode the raw that is returned in the R

### ISSUE THREAD

**Issue by RMHogervorst** [catboost/catboost#1366]
Problem: When I train a model using the R interface to catboost (`catboost.train`) I receive a training object with 
```
str(fit_object)
```

```
handle
raw
feature_importance
tree_count
```
**What is the raw object and how can I access the details in it?** I tried
`rawToChar(fit_object$raw)` but that gives me
```
Error in rawToChar(fit_object$raw) : 
  embedded nul in string
```
While it does show me some details: 
```
"detailed_profile":false,"boosting_options":{"model_shrink_mode":"Constant","approx_on_full_history":false,"fold_len_multiplier":2,"fold_permutation_block":0,"boosting_type":"Plain","iterations":100,"model_shrink_rate":0,"od_config":{"wait_iterations":20,"type":"None","stop_pvalue":0},"boost_from_average":true,"permutation_count":4,"learning_rate":0.22459499537944794},"metrics":{"objective_metric":{"type":"RMSE","params":[]},"eval_metric":{"type":"RMSE","params":[]},"custom_metrics":[]},"metadata":{},"cat_feature_params":{"store_all_simple_ctr":false,"ctr_leaf_count_limit":18446744073709551615,
```
It is not complete and not really decodeable. 

catboost version: 0.23.2
Operating System: MACOS 10.15.5 Mojave

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Only feature_importance and tree_count are documented attributes https://catboost.ai/docs/concepts/r-reference.html .

To explore the resulting model, you may save it in one of the supported formats.

Should you have more questions, please feel free to reopen this issue.

https://github.com/catboost/catboost/blob/ce66b762812f167d54f7b1fa700f04da2d9dc7a1/catboost/R-package/R/catboost.R#L1585
