### ISSUE TITLE
Java API Thread Safety

### ISSUE THREAD

**Issue by rayelnigma** [catboost/catboost#1369]
I couldn't find any official documentation on the Java API in regards to multi-threading and thread safety.

I found a reference to the C API about it being thread safe.  Is the Java API, also, thread safe?

I have a project where we are handling REST service calls within JBOSS, then calling CatBoost within each thread.  If we create a model using `model = CatBoostModel.loadModel()` once at the container level, can we then use the `prediction = model.predict()` within each thread simultaneously?

**Comment by nikitxskv** [comment]
@rayelnigma Hi!

Yes, Java API is thread-safe, so you can make predictions from each thread simultaneously.

**Comment by rayelnigma** [comment]
thank you for the quick response!
