### ISSUE TITLE
stdlib.h not found when installing R package on mac

### ISSUE THREAD

**Issue by Dan8262** [catboost/catboost#137]
Hello,

I try to install the R package on my mac (Mac OS 10.11.6) and I get the following error message:

> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/catboost/R-package'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘catboost’ ...
** libs
** arch - 
chmod +rx /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/catboost/R-package/src//../../../ya
/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/catboost/R-package/src//../../../ya make -r
Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/c1eaff0af934fd9bb8ff08d949af6b0f [..] OK
Downloading http://storage.mds.yandex.net/get-devtools-opensource/479623/371176961 [................] OK
2017-10-16T11:08:49.219188 [MainThread] Info: will fetch 'YMake' from sandbox
------- [CC] {FAILED} $(S)/contrib/libs/double-conversion/diy-fp.cc
command /Users/myName/.ya/tools/v3/300008394/bin/clang++ -mmacosx-version-min=10.9 -c -o /Users/myName/.ya/build/build_root/lopr/00005f/contrib/libs/double-conversion/diy-fp.cc.pic.o /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/double-conversion/diy-fp.cc -I/Users/myName/.ya/build/build_root/lopr/00005f -I/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03 -I/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/cxxsupp/libcxxrt -I/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/cxxsupp/libcxx-next/include -Woverloaded-virtual -Wno-invalid-offsetof -Wno-attributes -Wno-undefined-var-template -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -nostdinc++ -DFAKEID=r3181195 -DARCADIA_ROOT=/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03 -DARCADIA_BUILD_ROOT=/Users/myName/.ya/build/build_root/lopr/00005f -Werror -Wno-error=deprecated-declarations -std=c++14 -nostdinc++ failed with exit code 1
In file included from /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/double-conversion/diy-fp.cc:29:
In file included from /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/double-conversion/diy-fp.h:31:
In file included from /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/double-conversion/utils.h:31:
/private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/cxxsupp/libcxx-next/include/stdlib.h:101:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^
1 error generated.
Failed
make: *** [all] Error 1
ERROR: compilation failed for package ‘catboost’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/catboost’
Installation failed: Command failed (1)

Configuration:
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle

**Comment by Dan8262** [comment]
[Update]
ls -als /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/cxxsupp/libcxx-next/include/stdlib.h
16 -rw-r--r--  1 myName  staff  4563 12 oct 23:36 /private/var/folders/9d/3mfw7fp08xjg41006s7j2qsh0000gn/T/Rtmpi325jR/devtools167d35cf9eca4/catboost-catboost-6ce0e03/contrib/libs/cxxsupp/libcxx-next/include/stdlib.h

**Comment by exprmntr** [comment]
Hello @Dan8262 

It seems like you need to install development tools: try run `xcode-select --install` in terminal

**Comment by Dan8262** [comment]
Hello @exprmntr
I'm already working with XCode, so I think all required development tools are installed.
I performed a find -name "stdlib.h" and I found lot of then them in XCode directories (See below)
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchSimulator.sdk/usr/include/stdlib.h

I also have lot of stdlib.h files associated with other tools on my computer; I tested including /Users/danielcausse/.ya/tools/v3/300008394/lib/clang/3.9.1/include/ in my $PATH variable but it generates a similar error with the #include_next <inttypes.h> directive.

I suppose I have to include a directory that includes all *.h files in my $PATH variable (or another environment variable ?) but I don't know which one is the right one.

**Comment by sab** [comment]
DEVTOOLS-3923 (internal issue ID)

**Comment by annaveronika** [comment]
We could not solve your problem. As some people have problems with R package installation, we decided to publish compiled versions of the package. The progress will be reported in issue https://github.com/catboost/catboost/issues/63. For now I could only suggest to try again or to use python or command line utility.

**Comment by Nosferican** [comment]
Same issue for `zoo` with R 3.4.2 and Mac OS 10.13.1.

**Comment by lwaldron** [comment]
Thank you - I stumbled across this issue while looking for a solution to a similar problem with other packages, and `xcode-select --install` worked for me too. XCode 9.2 (9C40b),

```
> sessionInfo()
R Under development (unstable) (2017-11-01 r73646)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1
```

**Comment by yicongli** [comment]
The root reason is missing the /usr/include folder, installing command-line tools sometimes will not automatically add it. The [Link](https://forums.developer.apple.com/thread/104296) shows the correct way:
Install the package at 
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14. pkg

**Comment by kmcdermo** [comment]
Stumbled across this issue after updated to macOS 10.14, trying to compile source code with ROOT 6.14.02 via ACLiC, and saw the <stdlib.h> was not being found! I had reinstalled command-line tools and updated gcc as well. @yicongli's comment solved the issue, thanks!

**Comment by lunny** [comment]
@yicongli 's comment solved my issue, thanks!

**Comment by annaveronika** [comment]
I do very much encourage you to use precompiled binaries, because this way it will just work - https://tech.yandex.com/catboost/doc/dg/installation/r-installation-binary-installation-docpage/#r-installation-binary-installation

**Comment by leezx** [comment]
head missing.
Install the package at
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14. pkg
works perfectly.

**Comment by sjamayee** [comment]
Same issue with headers missing.
This solved the problem for me:

open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by leedrake5** [comment]
> Same issue with headers missing.
> This solved the problem for me:
> 
> open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

This solution no longer works with MacOSX 10.15 (Catalina)

**Comment by ben519** [comment]
Argh, I'm in the same boat as @leedrake5; after upgrading to MacOSX 10.15 (Catalina) this fix (which I've used many times in the past) no longer works :(

**Comment by cyx96** [comment]
> Argh, I'm in the same boat as @leedrake5; after upgrading to MacOSX 10.15 (Catalina) this fix (which I've used many times in the past) no longer works :(

I know it's a stupid solution, but copying everything inside /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include to /usr/local/include solved for me.

**Comment by blomadam** [comment]
I found this method to be out of date.  I recently solved the same issue with advice from the thread at https://stackoverflow.com/questions/48866862/cannot-install-stringi-since-xcode-command-line-tools-update/49268991#49268991

i.e. 

> Run in Terminal: `mv ~/.R/Makevars ~/.R/old_Makevars` (note that the file has been renamed rather than deleted in case it may need to be restored)

**Comment by ipstone** [comment]
@blomadam 's method doesn't work for me. 
also, @leedrake5's method `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` is no longer working for my macOS 10.14.6

@ben519 approach is working! couldn't believe the hack (good)!
`cp -a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/* /usr/local/include/`

**Comment by danielruss** [comment]
I know this is an old/closed issue.  But I came across this while trying to install another R package.  Instead of copying the files, you can add the directory to the CPATH.  

This worked for me: 
Sys.setenv("CPATH"="/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include")

Then I could compile the package with stdlib.
