### ISSUE TITLE
Be able to log training steps output elsewhere than stdout, with ease

### ISSUE THREAD

**Issue by victorbartel** [catboost/catboost#1372]
Problem: Have more flexible verbosity control on the model fit.
catboost version: 0.23
Operating System: Linux

Greetings,

In order to train our models we are using custom GCP AI Jobs. I would like to have more control on how and where catboost logs its intermediary steps information. Today if you set up the verbosity for `fit` method your logs will end up in the stdout, which is not practical at all in case of GCP. I would like to be able to redirect verbosity messages to a specific logger. Something like:

```python
logger = logzero.logger
model.fit(verbosity=1000, log_to=logger.debug)
```

Many thanks.

**Comment by DianaArapova** [comment]
Hello!
Could you please tell me if you are going to pass callback to log_to? And is this correct that logs will end up in this callback?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
You may now specify custom logger via cout_log and cerr_log parameter in fit and other methods in classes CatBoost and Pool.
These parameters should be either streams, or functions taking log entry as parameter.
Here is an example https://github.com/catboost/catboost/blob/e2e19d8aa06a7a7b3fc7788b5ec221715d831d6b/catboost/python-package/ut/medium/test.py#L4382
