### ISSUE TITLE
CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:79: At position 1 should be feature with name month_map_2 (found month_map_2.0).

### ISSUE THREAD

**Issue by SiddhiGolatkar** [catboost/catboost#1373]
Problem:
catboost version:
Operating System:
CPU:
# GPU:

**Comment by kizill** [comment]
Hello!
We need more context to understand what's wrong. The message you provided only means that you have mixed column order during training and during model evaluation. Please, write here codesnippet that will help us reproduce the problem.

**Comment by mrushad** [comment]
@SiddhiGolatkar

I might be a bit late, but @SiddhiGolatkar do you remember what had caused this error?

I'm getting a similar error when using a model for getting predictions. Some random numbers appear to append into column names.

Please do let me know if you remember how to solve this issue.
