### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by Dhananjay201** [catboost/catboost#1375]
What kind of encoding does catboost use?

**Comment by kizill** [comment]
Hello!
You can read about categorical features encoding and it's parameters in our [official documentation](https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html) or read this great [blogpost](https://towardsdatascience.com/categorical-features-parameters-in-catboost-4ebd1326bee5) with [tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/categorical_features/categorical_features_parameters.ipynb)
For example, in a case when feature cardinality is high, you could try playing with `max_ctr_complexity` parameter, setting it to 2 or 1.
If you could send us reproducing sample when catboost fails to work with categorical data - feel free to reopen this issue :)
Thank you!
