### ISSUE TITLE
GPU not reproducible results

### ISSUE THREAD

**Issue by kaptim** [catboost/catboost#1377]
catboost version: catboost-0.24
System: Google Colab, trained on GPU

Problem: I use catboost to eliminate variables in my data which lead to overfitting (regression problem). I simply train a model, remove some variables and train it again. However, Colab limited my GPU usage so I switched to a second account. There, the results are completely different with the same script used. I have checked the data and the splitting multiple times but it should all be correct. However, the results differ a lot.

My results on my first account:
-	Train: 'MSE': 121.66848086143253, 'R2': 0.7069243065046951
-	Test: 'MSE': 215.1099633178003, 'R2': 0.4876897013112429

My results on the second account:
-       Train: 'MSE': 194.66718338213363, 'R2': 0.5310846378079388}
-       Test: 'MSE': 250.54165999242255, 'R2': 0.40330484611228745

These are the parameters of the model:
params = {'iterations':10000,
        'learning_rate':0.01,
        'depth':4,
        'loss_function':'RMSE',
        #"loss_function": "Logloss",
        'eval_metric':'RMSE',
        #"eval_metric": "Logloss",
        'random_seed':55,
        'metric_period':50,
        'verbose':True,
        'use_best_model':True,
        'task_type':'GPU',
        "one_hot_max_size":30 
        #"train_dir" = "model"
        }

I did not change any of them when I ran the script again. I assumed that when there is a set random_seed, the results should be the same.

About my data: numeric (floats) and categorical data;  some of the categoricals include a lot of categories (e.g., 5600 unique values for 7300 observations), which is why I set "one_hot_max_size" to 30 since my supervisor told me this would speed up training.

**Comment by kizill** [comment]
Could you share your dataset or it's private data?

**Comment by kaptim** [comment]
Yeah, sure
https://drive.google.com/file/d/1zW_muBJXXBk2aWBAdwqYQA5k3fFXZ9Gx/view?usp=sharing
.h5 file, keys: X_train, X_test, y_train, y_test (I hope this works)
The set is not exactly the same as in my question because I had already removed some variables when I posted it. However, the issue is the same
So, I tried it on my local GPU as well and performance still differs (both trained on GPU). Both converge but they do not converge to the same error. Is there some other source of randomness? Or is there some issue with Colab why the performance is different to "normal" GPUs?

**Comment by kaptim** [comment]
My results for the data I shared:
local GPU:
MSE_train: 157.2635750951919, R2_train: 0.6211826513633709, MSE_test: 371.09902756709715, R2_test: 0.11618294790404682
Colab:
MSE_train: 135.74652849605266, R2_train: 0.6730130293656698, MSE_test: 358.1407729078268, R2_test: 0.14704459286266724

(parameters: random_seed = 0, no one_hot_max_size)

**Comment by kaptim** [comment]
Saw in the FAQs that training on GPU is non-deterministic which is why none of my results are reproducible.
Will use CPU from now on.
Thanks a lot and sorry for the inconvenience caused.
