### ISSUE TITLE
catboost doesn't support python 3.6 yet?

### ISSUE THREAD

**Issue by danielyang1009** [catboost/catboost#138]
```
RuntimeWarning: compiletime version 3.5 of module '_catboost' does not match runtime version 3.6
```

Got this error, I have conda python 3.6 install

**Comment by daskol** [comment]
@danielyang1009 There is wheel for python 3.6 on [PyPI](https://pypi.python.org/pypi/catboost/0.2.5). The issue is in your conda environment.

**Comment by annaveronika** [comment]
Most probably the problem is in the way you installed catboost. Maybe you installed it with 3.5 system python, then you run it with anaconda python which is 3.6.
