### ISSUE TITLE
RMSEWithUncertainty Train/Validation Scores Interpretation?

### ISSUE THREAD

**Issue by kmedved** [catboost/catboost#1388]
Hello - thanks for the amazing work on implementing `RMSEWithUncertainty`. This is really the killer feature for GBDT libraries, so I've been excitedly testing it out. I'm having some trouble understanding the `RMSEWithUncertainty` training/validation scores. I had expected them to match the scores for RMSE training, but they don't seem to, and are on a completely different scale entirely.

I'm working with version 0.24 on Windows, but the issue is platform agnostic - I've set up a Colab reproducible example here: https://colab.research.google.com/drive/1SduznbvtB3LF3MLpmcBeLnXnKN1DE5oB?usp=sharing

As you can see, with the CA housing dataset problem, the `RMSEWithUncertainty` Train/Validation scores are  `-0.11963895928507302` and `0.06206563547371406` respectively, although when I run a `.predict()` call and score the model using `mean_squared_error`, I get a score of `0.5170863957395283`.

As a comparison, I've also run the same with just `RMSE` loss, and I get scores of `0.3792210165669188`/`0.4554955778995176`, which are replicated via `.predict()/mean_squared_error`.

So two questions really:

1) How do I interpret the `RMSEWithUncertainty` scores from a `.best_score_` call? I've been using these for hyperparameter searching, but they don't match what I get with `RMSE` or using a `.predict()/mean_square_error` call.

2) Even using the `.predict()/mean_square_error` scoring with `RMSEWithUncertainty`, I get a materially worse scores than with `RMSE` scoring. (0.51 RMSE vs. .45 RMSE). This is using stock parameters and no tuning, but is this to be expected? 

Separately, I'm having issues with Catboost 0.24 generating significantly worse scores with the same hyperparameters than 0.23 was generating, but I am still working on a reproducible example, and will open a separate issue for that when ready.

Thanks!

**Comment by ek-ak** [comment]
Hello! Thank you for this questions!  Tutorial RMSEWithUncertainty is in progress now.
1.  RMSEWithUncertainty  scores really differs from RMSE scores and looks very unusual, so you can add custom_metric = 'RMSE' to see RMSE  scores in .best_score_ call
2. RMSE defaults are tuned from the box, so without tuning RMSEWithUncertainty model will lose by quality =( Also it seems that RMSEWithUncertainty models works better without early_stopping_rounds option.
And we are waiting for your example in another issue )

**Comment by kmedved** [comment]
Adding to this...I saw the release of [version 0.24.1](https://github.com/catboost/catboost/releases/tag/v0.24.1), which adds a lot more super-interesting looking functionality with RMSEWithUncertainty. Any additional documentation or explanation for how to use the the `posterior_sampling`, `diffusion_temperature`, `virtual_ensembles_predict`, `VirtEnsembles`, etc... functionality would be appreciated.

Exciting stuff here.
