### ISSUE TITLE
val on plot_tree leaves

### ISSUE THREAD

**Issue by nauman-chaudhary** [catboost/catboost#1389]
When I plot a tree using plot_tree, there are weird `val` in the leaves.
What do these values represent in case of [binary](https://imgur.com/pB80Dtr) and [multiclass](https://imgur.com/rrXL0Hc) classification?

Is there a way to know the class on leaves?

**Comment by ek-ak** [comment]
Hello! Thank you for your question.
There are several prediction types for binClass - Class, Probability and RawFormulaVal. RawFormulaVal is a number resulting from applying the model (=sum by all tree [leaf value for document in each tree]). Class is obtained from RawFormulaVal by the rule [Class1 =  RawFormulaVal > 0]. Values showed in a plot_tree are leaf values (not probabilities), they are summed to RawFormulaVal, so you can also think about them in terms [Class1 = RawFormulaVal > 0]. Zero value in a leaf usually means that no train objects passed to this leaf.
For MultiClass leaf contains ClassCount values (with zero sum). Class of a leaf can be obtained as  argMax of this array of values in the leaf.

**Comment by OmriKaduri** [comment]
Hi @ek-ak, if I understand what you're saying, the leaf value should always be positive? 
I'm afraid that's not the case (as I've seen leaf values which are negative), so It would be nice if you can explain (maybe add a reference to the relevant code?) how the leaf values are actually computed.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Just citing ek-ak:
> Values showed in a plot_tree are leaf values (not probabilities)
So, plot_tree always shows RawFormulaVal as leaf values.
This RawFormulaVal can be negative.
Given a tree, leaf values are computed to optimize the loss value.

**Comment by RichardScottOZ** [comment]
Definitely useful to put this in the plot_tree explanation docs.

**Comment by xiongshou** [comment]
What does the leaf node Val represent in the tree?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Val is the value predicted by the tree.
You may refer to https://catboost.ai/docs/concepts/python-reference_catboost_plot_tree.html .

**Comment by yiyaoliu** [comment]
Hi there, I understand that in classification, val is the ratio and we can convert it to probability using the sigmoid function. 
But wanna confirms what val stands for in regression. Using the regression from this (https://github.com/catboost/tutorials/blob/master/model_analysis/visualize_decision_trees_tutorial.ipynb) as an example (#34): I thought the val from the first tree should be the y_predicted, but the scale of val in the plot looks like error residuals (y - y_predicted). Can you help confirm if the val is actually residuals instead of predicted value from the first tree?

**Comment by Thuener** [comment]
![image](https://user-images.githubusercontent.com/770605/137751021-0a495fd5-da6b-42f9-8902-88d879e2f16d.png)

Why the plot uses RawFormulaVal? Why not use the same values as the model.predict()?

In my opinion, this makes it much more difficult to interpret the plot results.
