### ISSUE TITLE
GPU support in python lib

### ISSUE THREAD

**Issue by DutchakVitaliy** [catboost/catboost#139]
I was try to use Catboost for my dataset and compare it to xgboost:
Xgboost 5-fold cv - 2 minutes with lr=0.01 (build with CUDA support)
Catboost 5-fold cv about 1 hour with lr=0.25

How I can enable GPU acceleration for python Catboost?

**Comment by annaveronika** [comment]
We will add GPU training support to our python library very soon, but it's not jet ready.

**Comment by annaveronika** [comment]
This is fixed now
