### ISSUE TITLE
Why tag v0.16.5 numpy version requirement diff from the python dist metadata requirement?

### ISSUE THREAD

**Issue by inevity** [catboost/catboost#1390]
Problem:  the python setup.py need just numpy > 1.11 but the dist meta need numpy 1.16   Look like weird
catboost version: 0.16.5 
Operating System: Any
CPU: Any
GPU: Any

**Comment by kizill** [comment]
We've fixed this bug around 28 Oct 2019, so it's fixed since CatBoost v0.18.1 release. Thank you! Closing, as everything is OK in recent versions.
