### ISSUE TITLE
catboost/private/libs/target/target_converter.cpp:32: Missing values like "None" are not supported for target

### ISSUE THREAD

**Issue by Mangol31** [catboost/catboost#1391]
Problem: catboost/private/libs/target/target_converter.cpp:32: Missing values like "None" are not supported for target

![image](https://user-images.githubusercontent.com/20582963/90397469-54842100-e0b1-11ea-8908-afce2a62998f.png)

Unfortunately, I don't have any more ideas how to beat this bug.
1) I don't have any data gaps.
2) I have consistently excluded all the signs in order to understand which one contains "broken" data.
Nothing helped :(
Please help me fix the error.

catboost version: 0.23.2
Operating System: Windows 10 Pro 
CPU: i7-4710MQ

**Comment by ek-ak** [comment]
Hello! Thanks you for your question. Check label in your dataset - you have None value there (target and label are synonyms).

**Comment by Mangol31** [comment]
> Hello! Thanks you for your question. Check label in your dataset - you have None value there (target and label are synonyms).

I'm sorry, but I'm not sure what you mean.

**Comment by Mangol31** [comment]
Thank you very much. Problem solved.
