### ISSUE TITLE
Accuracy goes down

### ISSUE THREAD

**Issue by SakariHack** [catboost/catboost#1393]
Problem:
I have database with some values, like this:
![screen_3](https://user-images.githubusercontent.com/48053963/90536916-5c14fa00-e185-11ea-90c2-14dd39bfaf6d.png)

When i`m trying to fit model, Accuracy first it goes up a little, then it constantly falls. What could be the problem? Bad dataset?

![screen_2](https://user-images.githubusercontent.com/48053963/90536915-5b7c6380-e185-11ea-8a87-8695d152c373.png)
![screen_1](https://user-images.githubusercontent.com/48053963/90536914-5ae3cd00-e185-11ea-9855-d8dce341f04e.png)
catboost version: 0.24

**Comment by SakariHack** [comment]
Size of database ~3000

**Comment by kizill** [comment]
I guess you should try setting super-low learning rate and try playing with l2 regularization. Duplicating all the samples will show no result as shifts all the derivatives sums proportionally and thus changes nothing. I guess it's not a CatBoost problem so closing this issue for now:)
