### ISSUE TITLE
TypeError: No matching signature found

### ISSUE THREAD

**Issue by Mangol31** [catboost/catboost#1398]
Problem: TypeError: No matching signature found
![image](https://user-images.githubusercontent.com/20582963/91037997-720e3900-e623-11ea-8132-520e8f785ffa.png)

And again an incomprehensible mistake for me :( I found that it is caused by one of the categorical features. When I run label encoding for it, the error goes away. But why? I want to pass the categorical feature to the model.

![image](https://user-images.githubusercontent.com/20582963/91038359-12645d80-e624-11ea-82c6-ca5f00ef4729.png)
![image](https://user-images.githubusercontent.com/20582963/91038469-3cb61b00-e624-11ea-94b9-78d7460be411.png)

catboost version: 0.23.2
Operating System: Windows 10 Pro
CPU:i7-4710MQ
# GPU:

**Comment by LyzhinIvan** [comment]
Hi, @Mangol31! 
Write, please, what parameters you specified for model constructor and fit function?

**Comment by Mangol31** [comment]
> Hi, @Mangol31!
> Write, please, what parameters you specified for model constructor and fit function?
Hi, @LyzhinIvan !
```
model = CatBoostRegressor(iterations = ITERATIONS,
                          learning_rate = LR,
                          one_hot_max_size = 2,
                          random_seed = RANDOM_SEED,
                          eval_metric='MAPE',
                          custom_metric=['R2', 'MAE'],
                          od_type = 'Iter',
                          od_wait = 30,
                          rsm = 0.1
                         )
model.fit(X_train, y_train,
         cat_features=cat_features_ids,
         eval_set=(X_test, y_test),
         verbose_eval=100,
         use_best_model=True,
         plot=False
         )
```

**Comment by LyzhinIvan** [comment]
What type of y_train and its values?

**Comment by Mangol31** [comment]
@LyzhinIvan ,
sample of values
![image](https://user-images.githubusercontent.com/20582963/91050566-43e72400-e638-11ea-9eb5-4c17b00cf411.png)
and type
![image](https://user-images.githubusercontent.com/20582963/91050669-6b3df100-e638-11ea-9344-72172e5eb814.png)

**Comment by LyzhinIvan** [comment]
Could you, please, provide full reproducible script with error (maybe,  on small number of rows from your dataset)? I can't reproduce the error. 
And to clarify, are you sure you are using 0.23.2? From the call stack, it seems that this is version 0.24.

**Comment by Mangol31** [comment]
@LyzhinIvan thank you very much for your help! After all, the problem was with y-train. I re-parsed the dataset and saw an error in feature that is used to generate y_train. Now everything works perfectly.
