### ISSUE TITLE
R package need Visual Studio compiler only?

### ISSUE THREAD

**Issue by jurbanhost** [catboost/catboost#14]
сonfig was not generated due to errors in C:\xxx\Temp\RtmpymqlxK\devtools3e9853651dec\catboost-catboost-87e5a37\build\ymake_conf.py
ERROR:root:Could not detect cxx compiler, error is [Error 2]

**Comment by alex-danilin** [comment]
Having the same issue. Is there any solution like setting other compilers?

**Comment by ferrr** [comment]
https://github.com/catboost/catboost/issues/30
