### ISSUE TITLE
Predict class labels from RawFormulaVal score return by apply_catboost_model 

### ISSUE THREAD

**Issue by Piyushbalwani** [catboost/catboost#1400]
Problem: Predict class labels from RawFormulaVal score
catboost version: 0.24
Operating System: Windows
CPU: core i7

I have trained `CatBoostClassifier `and saved model (`save_model`) in python. The python file generated has method `apply_catboost_model` and method is returning `RawFormulaVal` score, but I am interesting in knowing exact class labels for the samples. Is there any way to convert this score to class labels? 
How CatBoost API is predicting labels through method [`predict `](https://catboost.ai/docs/concepts/python-reference_catboostclassifier_predict.html) for `prediction_type=Class` ?

Best Regards
Piyush

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
We apply sigmoid to the raw formula value, and then round the result to the nearest.
Here is the link to the documentation.
https://doc.yandex-team.ru/ml/catboost/doc/concepts/output-data_model-value-output.html#output-data_model-value-output__classification

**Comment by Piyushbalwani** [comment]
Thanks @Evgueni-Petrov-aka-espetrov. 

Above link didn't works for me, but this link is [https://catboost.ai/docs/concepts/output-data_model-value-output.html#output-data_model-value-output__classification](https://catboost.ai/docs/concepts/output-data_model-value-output.html#output-data_model-value-output__classification) working fine.

I got required information in this link:
- **RawFormulaVal** —A number resulting from applying the model.
- **Probability** — A number indicating the probability that the object belongs to the class (a sigmoid of the result of applying the model).
- **Class** — The predicted class (output with the value “1” if the probability is higher than 0.5, otherwise “0”).

Regards,
Piyush
