### ISSUE TITLE
Training on GPU - Bayesian bootstrap type doesn't support taken fraction option

### ISSUE THREAD

**Issue by MatteoFelici** [catboost/catboost#1410]
I'm trying to train a model on Google Cloud Platform with GPU using a container based on `nvidia/cuda`. I use this code

```
catboost_model = CatBoostClassifier(
    use_best_model=True,
    random_seed=1123,
    auto_class_weights='Balanced',
    task_type='GPU',
    eval_metric='Logloss'
)

...

catboost_model.fit(train, y, **fit_params)
```

I get this error:

```_catboost.CatBoostError: catboost/private/libs/options/catboost_options.cpp:736: Error: default bootstrap type (bayesian) doesn't support taken fraction option```

Instead, without using GPU, so:

- remove `task_type` parameter
- use a container based on `python:slim`

everything works fine.

I sincerely don't have any idea about what the "taken fraction option" could be...

catboost version: catboost-0.24.1
Operating System: nvidia/cuda:latest docker image

**Comment by Vetrivel-PS** [comment]
I have also faced a similar issue with the following error :

**CatBoostError: catboost/private/libs/options/catboost_options.cpp:736: Error: default bootstrap type (bayesian) doesn't support taken fraction option**

Im using CatBoostClassifier with GPU. Kindly help.

**Comment by DivyanshAgrawal22** [comment]
I too faced this error, recently. But this could be resolved using `bootstrap_type='Poisson'`. The default is a Gaussian type and it only works on CPU. For GPU try setting it to Poisson. Worked well for me.

Let me know if you need more details.

Cheers!!

**Comment by kizill** [comment]
Sorry for such a long answer. The error message means that you've possibly set `subsample=XXX` parameter somewhere (or that you trigger some bug 😄)
By now, Bayesian bootstrap is fully supported both on CPU and GPU and it's default bootstrap for GPU. Provided code snippet works just fine on my data.
So, please, can you reopen this issue if problem still occurs on your data and send us a code snippet for problem reproduction?

**Comment by naiborhujosua** [comment]
I deleted the subsample parameter and it worked
