### ISSUE TITLE
Export trees to text format

### ISSUE THREAD

**Issue by SwarVaidya** [catboost/catboost#1412]
Hi, I wanted to take a full visualization of trees by exporting them to a text format, much like what [sklearn.tree.export_text](https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_text.html) does. I do not find a way to perform this. Also, I do not find a method to call a tree/estimator to pass it to sklearn, so that it could export to text (if this type of operation is supported by sklearn). Let me know if there is a solution to this.

**Comment by nikitxskv** [comment]
@SwarVaidya, Hi !
What about our internal tree visualization method?
https://catboost.ai/docs/concepts/python-reference_catboost_plot_tree.html

Also, you can dump your model to json file using `save_model` method (specify `format` parameter with `json` value):
https://catboost.ai/docs/concepts/python-reference_catboost_save_model.html
