### ISSUE TITLE
Traverse through nodes of the tree

### ISSUE THREAD

**Issue by sinchanagowda98** [catboost/catboost#1413]
Hello,

I wish to traverse through the nodes of each tree in order to extract information present in the nodes. Is there a way to do this? 

I thought of converting the tree to a graph format which would make it easier to traverse. So, is there a way to export the trees into a DOT format similar to the sklearn.tree.export_graphviz() function for decision trees?

Thank you.

**Comment by nikitxskv** [comment]
@sinchanagowda98 Hi!

You can dump your model to json file using save_model method (specify format parameter with json value) and extract trees information from it:
https://catboost.ai/docs/concepts/python-reference_catboost_save_model.html

**Comment by sinchanagowda98** [comment]
@nikitxskv Thank you!
