### ISSUE TITLE
Custom verbose steps

### ISSUE THREAD

**Issue by vasyarv** [catboost/catboost#142]
At the moment I can see that for python package it is possible only to set `verbose` as `True` or `False`, though it would be useful to set it as `int` value to print every i-th step.

**Comment by souravsingh** [comment]
I am interested in working on this.

**Comment by annaveronika** [comment]
That's great! You can start with catboost/app/cmd_line.cpp and add a new parameter there.
Then you should add the parameter to python package and R package. To do that you can grep by some parameter name and see how it is added.

**Comment by annaveronika** [comment]
We've implemented metric_period parameter. The code is on github now, you could build from source. It'll be updated on pypi in version 0.5.2
