### ISSUE TITLE
GPU/Jupypter Notebook compatibility issue

### ISSUE THREAD

**Issue by kdlin** [catboost/catboost#1421]
Problem:GPU still runs after I interrupt the Kernel in Jupyter
catboost version:0.24.1
Operating System:Linux
CPU: 24 cores
# GPU: 2

On Jupyer notebook, Catboost GPU still runs after I interrupt the kernel. It would be better if Catboost can support the interrupt signal and stop GPU operation. Otherwise, one has to shutdown the notebook and lose all data.

**Comment by LyzhinIvan** [comment]
Hi, @kdlin!

CatBoost supports interrupt signal in Jupiter Notebook. CatBoost checks whether it was interrupted after each iteration.
