### ISSUE TITLE
Create catboost.pool feature like cat_features but in order to "hide" features from model

### ISSUE THREAD

**Issue by ChepkovG** [catboost/catboost#1426]
Problem: while discovering dataset (finding optimal set up of features) it would be useful ti have an opportunity not to drop variables but to put them in some auxil_features so model would ignore them.
catboost version: 0.24
Operating System: windows

**Comment by ljluestc** [comment]
```
import catboost as cb
import pandas as pd

data = pd.read_csv('your_dataset.csv')

data['__aux_feature1'] = data['feature1']
data['__aux_feature2'] = data['feature2']

data.drop(['feature1', 'feature2'], axis=1, inplace=True)

pool = cb.Pool(data=data, label='target', cat_features=['categorical_feature'])

model = cb.CatBoostClassifier(iterations=100, loss_function='Logloss')
model.fit(pool)

```

**Comment by andrey-khropov** [comment]
CatBoost has [`ignored_features` parameter](https://catboost.ai/en/docs/references/training-parameters/#ignored_features).

You can also see examples in the test, for example [for Python API](https://github.com/catboost/catboost/blob/1df1f72804a5f62689b0e333bcab51f744316ba9/catboost/python-package/ut/medium/test.py#L3185-L3198)
