### ISSUE TITLE
shap_interaction_values 

### ISSUE THREAD

**Issue by mdjabc** [catboost/catboost#1427]
WHen I use shap_interaction_values for catboost, some problem:

1.'TreeEnsemble' object has no attribute 'values'.
2.the calculated interaction_values are Nan or 0.

**Comment by mdjabc** [comment]
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(test_x)
shap_interaction_values = shap.TreeExplainer(model).shap_interaction_values(test_x.iloc[:50,:])

**Comment by mdjabc** [comment]
But it can work
prediction_diff = model.get_feature_importance(type='ShapInteractionValues', data=eval_dataset, prettified=True)

**Comment by LyzhinIvan** [comment]
This issue is addressed in the Shap repository https://github.com/slundberg/shap/issues/480.
