### ISSUE TITLE
Saving Pool with only categorical features

### ISSUE THREAD

**Issue by olyaromanyuk** [catboost/catboost#1428]
Problem: 

I have a big dataset (50K rows, 50K columns), all features are categorical. The creation of the pool object takes about 75 minutes, so it makes sense to save the pool object and reuse them for multiple runs.

When I try
`train_pool.save("/home/olharomaniuk/DeepTrait/0248_catboost_tunning/train_data.pool")
`
I get 
```
~/.local/lib/python3.7/site-packages/catboost/core.py in save(self, fname)
    732         """
    733         if not self.is_quantized():
--> 734             raise CatBoostError('Pool is not quantized')
    735 
    736         if not isinstance(fname, STRING_TYPES):

CatBoostError: Pool is not quantized
```

And when I try 
```
train_pool.quantize()
train_pool.save("/home/olharomaniuk/DeepTrait/0248_catboost_tunning/train_data.pool")

```
I get 
```
~/.local/lib/python3.7/site-packages/catboost/core.py in save(self, fname)
    737             raise CatBoostError("Invalid fname type={}: must be str().".format(type(fname)))
    738 
--> 739         self._save(fname)
    740 
    741     def quantize(self, ignored_features=None, per_float_feature_quantization=None, border_count=None,

_catboost.pyx in _catboost._PoolBase._save()

_catboost.pyx in _catboost._PoolBase._save()

CatBoostError: catboost/private/libs/quantized_pool/serialization.cpp:977: Saving quantization results is supported only for numerical features
```
Is there a way to save such pool? Is there a way to initialize pool object faster?

catboost version: 0.23, 0.24.1
Operating System: ubuntu 18.04 LTS
CPU: CPU
GPU: GPU

**Comment by olyaromanyuk** [comment]
I figured out that using X_train.astype("object") makes pool creation 10 times faster, so saving is not that critical in my use case.

**Comment by andrey-khropov** [comment]
Saving quantized pools is supported since https://github.com/catboost/catboost/commit/22b4a0346d0817e5b9698fa29d9eec9a32523ae5 and will be included in the next release.
