### ISSUE TITLE
Example from Quickstart for R package fails at line 2

### ISSUE THREAD

**Issue by OldMortality** [catboost/catboost#1430]
Problem:  Example from Quickstart for R package fails at line 2

library(catboost)
features <- data.frame(feature1 = c(1, 2, 3), feature2 = c('A', 'B', 'C'))
labels <- c(0, 0, 1)
train_pool <- catboost.load_pool(data = features, label = labels)

Error in catboost.from_data_frame(data, label, pairs, weight, group_id,  : 
  Unsupported column type: character

I think it needs to be:

features <- data.frame(feature1 = c(1, 2, 3))
catfeatures <- data.frame(feature2 = c('A', 'B', 'C'))
labels <- c(0, 0, 1)
train_pool <- catboost.load_pool(data = features, cat_features = catfeatures , label = labels)

**Comment by VlasovKirill** [comment]
I apologize for not clarifying earlier. You should use function `factor()` for categorical features  like that:
`features <- data.frame(feature1 = c(1, 2, 3), feature2 = factor(c('A', 'B', 'C')))`

We have updated [quick start](https://catboost.ai/docs/concepts/r-quickstart.html) page
