### ISSUE TITLE
2020-09-25T08:03:35.421699287Z _catboost.CatBoostError: catboost/private/libs/options/catboost_options.cpp:575: Error: rsm on GPU is supported for pairwise modes only

### ISSUE THREAD

**Issue by Jie-Yuan** [catboost/catboost#1433]
2020-09-25T08:03:35.421699287Z _catboost.CatBoostError: catboost/private/libs/options/catboost_options.cpp:575: Error: rsm on GPU is supported for pairwise modes only

**Comment by kizill** [comment]
Hello!
Currently we don't support RSM on GPU for non-pairwise losses, because we don't see need for it - rsm won't provide significant speedup, but it's implementation will require lot's of work, so for now - just don't set RSM while training on GPU.
Thanks!

**Comment by guptadikshant** [comment]
> Hello! Currently we don't support RSM on GPU for non-pairwise losses, because we don't see need for it - rsm won't provide significant speedup, but it's implementation will require lot's of work, so for now - just don't set RSM while training on GPU. Thanks!

How to disable it for training on gpu?

**Comment by sanskaromar** [comment]
For anyone getting this error and wondering about `rsm`, It is an alias for `colsample_bylevel` as mentioned [here](https://catboost.ai/en/docs/references/training-parameters/common).
