### ISSUE TITLE
Windows10 Can't see plot from CatBoostClassifier

### ISSUE THREAD

**Issue by Zibski** [catboost/catboost#144]
I can't force CatBoostClassifier to show a graph by setting plot=True. To test if I'm doing anything wrong, I took titanic example from your GitHub and is is not showing the graph as well.
I pulled newest Jupyter, newest Catboost and few others with no result. It is not showing a graph and no error or warning message. Other than this the Classifier works fine.

I've seen similar issue on Mac posted here, but I wanted to highlight that the problem is also on Windows platform.

**Comment by annaveronika** [comment]
Are you following the installation instruction? https://tech.yandex.com/catboost/doc/dg/concepts/python-installation-docpage/
Have you enabled notebook extension for widgets?

**Comment by Zibski** [comment]
Yes, I have installed Catboost and ipywidgets by pip. The first time I've tried plot I didn't have ipywidgets, after that I realized that it was missing - not sure if this makes any difference... I have turned on widget extensions. 
I've just uninstalled and installed once more catboost and ipywidgets, enabled ipywitgets, still no improvement.

![obraz](https://user-images.githubusercontent.com/32173141/31961540-488fbd72-b8fb-11e7-9eb2-e5297471adc8.png)


![obraz](https://user-images.githubusercontent.com/32173141/31961497-32fbeac6-b8fb-11e7-9663-ffecef81924d.png)

**Comment by yyll008** [comment]
I use Mac miniconda3, have the same problem!

**Comment by nikitxskv** [comment]
@Zibski, @yyll008 Hello!
Most likely the graph are not rendered because of the new version of ipywidgets. Try to install ipywidgets==6.0.0
We will fix this error in the following updates.

**Comment by Zibski** [comment]
@nikitxskv You just opened doors for new World to me. Thank you!

**Comment by yyll008** [comment]
@nikitxskv Thanks,fix this!
and add below:
import catboost
w = catboost.CatboostIpythonWidget('../input/')
w.update_widget()

**Comment by annaveronika** [comment]
fixed
