### ISSUE TITLE
Fail to install on jetson xavier NX

### ISSUE THREAD

**Issue by tupq** [catboost/catboost#1449]
Problem: 
    ERROR: [Errno 8] Exec format error when i run the ya install command as in the guideline:
        "../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON=3.6 -DCUDA_ROOT=/usr/local/cuda"
    The configuration in default_nvcc_flags.make.inc is edited: 
      -gencode arch=compute_72,code=compute_72
catboost version: latest
Operating System: Linux ubuntu 18.04
CPU: aarch64
GPU: nvidia

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
We do not support ARM right now but this work is in progress.

**Comment by tupq** [comment]
Thank you, Iam looking forward to this update.

**Comment by LyzhinIvan** [comment]
The main issue about ARM support is #1526. I close this issue as duplicate.
