### ISSUE TITLE
Best way to implement model export to C-like function

### ISSUE THREAD

**Issue by wingrime** [catboost/catboost#145]
I Want to implement model exporting to C-like function for stand-alone usage  
How properly write own exporters using existing code base?

As primary example I see CoreML exporter, but currently it has no command line export tool (just python interface). Looking in code I see that primary definition of model lies in TCoreModel structure.
```
struct TCoreModel {
    yvector<bool> HasNans;
    yvector<yvector<float>> Borders;
    yvector<TTensorStructure3> TreeStruct;
    yvector<yvector<yvector<double>>> LeafValues; // [numTree][dim][bucketId]
    yvector<int> CatFeatures;
    yvector<TString> FeatureIds;
    int FeatureCount = 0;
    int ApproxDimension = 1; 
}
```

It's not clear how to deal with it. Looks likes real split values are in LeafValues (for performance matters), and split information in TreeStruct vector.

How to properly address it ?

TTensorStructure3 vector (looks like vector size equals numTree ?) has internal vector of TModelSplit , split has kind EModelSplit (it does not clear for me, do split type mater for model export ?)

**Comment by kizill** [comment]
Hello! We already provide standalone(so-library) "C" api with c++ wrapper in catboost/libs/model and simple c++ example code in https://github.com/catboost/catboost/tree/master/catboost/libs/model_interface/cmake_example

And I'm planning to release our header-only version of model evaluator for the case, when there is only float features by the end of this week.

**Comment by wingrime** [comment]
Thanks! I can be a nice solution, my primary interest - code generator for c# code, c library is also nice, but dealing with native code can be painful to maintain, best solution for me - tool that generates code  from simple blocks (header + function with many if's)

**Comment by kizill** [comment]
I understand that data marshalling isn't good, but if we are talking about model evaluator that has full functionality, f.e. categorical features - it's better to use c-api just to have reproducible model evaluation result

**Comment by annaveronika** [comment]
We have save model as code functionality now.

**Comment by wingrime** [comment]
no cat features? only floats ?
