### ISSUE TITLE
X is uninitiated

### ISSUE THREAD

**Issue by Reshma2k** [catboost/catboost#1450]
I am facing problem with the model.fit(test_data).
I keep getting an error: 
"CatBoostError: Label in X has not been initialized."
Can somebody please help me out? Appreciate your help in advance.

from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
%%time
from sklearn.model_selection import StratifiedKFold
#X_test = pd.read_excel("/Users/reshmapathan/Desktop/Info Salons/Predictive Analysis/2 FastAI/tmp/Test.xlsx")
n_fold = 4 # amount of data folds
folds = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=SEED)

params = {'loss_function':'Logloss',
          'eval_metric':'AUC',
          'verbose': 200,
          'random_seed': SEED,
          'nan_mode' : 'Forbidden'
         }

X_test = test_df.drop(columns='attended')
test_data = Pool(data=X_test,
                 cat_features=cat_features)

scores = []
prediction = np.zeros(test_data.shape[0])
print(prediction)

for fold_n, (train_index, valid_index) in enumerate(folds.split(X, y)):
    
    X_train, X_valid = X.iloc[train_index], X.iloc[valid_index] #train and validation data splits
    y_train, y_valid = y.iloc[train_index], y.iloc[valid_index]
    #y_train, y_valid = y[train_index], y[valid_index]
    
    train_data = Pool(data=X_train, 
                      label=y_train, 
                      cat_features=cat_features)
    valid_data = Pool(data=X_valid, 
                      label=y_valid,
                      cat_features=cat_features)
    model = CatBoostClassifier(**params)
    model.fit(train_data,
              eval_set=valid_data, 
              use_best_model=True
             )
    
    score = model.get_best_score()['validation_0']['AUC']
    scores.append(score)

    y_pred = model.predict_proba(test_data)[:, 1]
    prediction += y_pred

prediction /= n_fold
print('CV mean: {:.4f}, CV std: {:.4f}'.format(np.mean(scores), np.std(scores)))

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Highly likely, this error is triggered by passing to fit test_data instead of train_data.

**Comment by Reshma2k** [comment]
> Highly likely, this error is triggered by passing to fit test_data instead of train_data.

Thanks @Evgueni-Petrov-aka-espetrov 
Sorry about the typo. You are right. It was supposed to be a train data. 
I have rectified the code.
