### ISSUE TITLE
Calling  CatBoostClassifier.get_feature_importance() with the documented parameters order throws an exception and stops

### ISSUE THREAD

**Issue by fantauzzi** [catboost/catboost#1451]
Problem:
Calling CatBoostClassifier.get_feature_importance() relying on the documented parameters order throws an exception. Workaround is to name the parameters and not rely on their order.
To reproduce it:
- Downoad and run the tutorial tutorials/events/2019_pydata_london/pydata_london_2019.ipynb
- In the first cell of section "Loss function change", execution stops with 

> TypeError: Argument 'reference_data' has incorrect type (expected _catboost._PoolBase, got str)

- workaround: name all parameters (use parameter keywords) in the call to get_feature_importance(), e.g.
```
np.array(model.get_feature_importance(
    data=train_pool, 
    type='LossFunctionChange', 
    prettified=True
))

```
catboost version: 0.24.1
Operating System: Ubuntu 20.04.1 LTS
CPU: Intel® Core™ i7-2700K CPU @ 3.50GHz × 8
GPU: GTX 1080

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks! We will add reference_data to the description of get_feature-importance soon.
