### ISSUE TITLE
calc_feature_statistics dictionary does not contain the bin sizes

### ISSUE THREAD

**Issue by paullovachy** [catboost/catboost#1452]
Problem: The dictionary returned by the calc_feature_statistics function does not contain the range of values displayed in plotly. Is there anywhere else to retrieve the range of values? I am transforming the calc_feature_statistics dictionary to a dataframe and exporting for visualization elsewhere. 

<img width="996" alt="Screen Shot 2020-10-12 at 6 17 24 PM" src="https://user-images.githubusercontent.com/28489897/95795037-651ed500-0cb7-11eb-87ea-696161b86354.png">

<img width="872" alt="Screen Shot 2020-10-12 at 6 17 45 PM" src="https://user-images.githubusercontent.com/28489897/95795056-6fd96a00-0cb7-11eb-871c-0f0601a17553.png">

For example, I would like to retrieve the information that the highlighted bin is between .88 and .91.

catboost version: 0.24.2
Operating System: macOS

Thank you!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
'Bin sizes' are returned via objects_per_bin.

**Comment by paullovachy** [comment]
I'm sorry - didn't explain properly. I see that the bin sizes are returned. I am looking for the range of values in each bin. For example, you can see that the range of values in highlighted bin in the graph above are between  0.8802 and 0.9117. 

Where can I retrieve that information?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
The borders between bins are returned via borders.
Bins are semi-open intervals (borders[i-1], borders[i]] for i >= 1 plus [borders[0], borders[1]].

**Comment by paullovachy** [comment]
Ah yes I see - thank you!
