### ISSUE TITLE
C API - Add a method to support hashed categorical features and text features

### ISSUE THREAD

**Issue by bduclaux** [catboost/catboost#1456]
Currently, the C/C++ API only supports inference either with :
- Num and Hashed Cat Features (passed a float and int32 arrays), 
- or with Num, Categ and Text Features (passed as float and strings array)

It would be great to have another method to support Num, Hashed Cat Features and Text Features.
The signature of such method should be like in model.h :

```
void Calc(
        TConstArrayRef<TConstArrayRef<float>> floatFeatures,
        TConstArrayRef<TConstArrayRef<int>> catFeatures,
        TConstArrayRef<TVector<TStringBuf>> textFeatures,
        size_t treeStart,
        size_t treeEnd,
        TArrayRef<double> results,
        const TFeatureLayout* featureInfo = nullptr
    ) const;

```

And the corresponding C/C++ API (not sure about the name, but you get the idea) :

```
CATBOOST_API bool CalcModelPredictionHashText(ModelCalcerHandle* modelHandle, size_t docCount,
	const float** floatFeatures, size_t floatFeaturesSize,
	const int** catFeatures, size_t catFeaturesSize,
	const char*** textFeatures, size_t textFeaturesSize,
	double* result, size_t resultSize) 
```

Thanks a lot for the fantastic work you guys are doing !

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!

**Comment by bduclaux** [comment]
Great ! Many thanks !
