### ISSUE TITLE
Catboost classifier for imbalance target variable and impact of randomness

### ISSUE THREAD

**Issue by ishan42d** [catboost/catboost#1459]
Problem: Catboost classifier for imbalance target variable and impact of randomness
I am presently dealing with a dataset whose target variable is highly imbalanced [0,1] = [95%, 5%]. The only major reason that I want to use Catboost here is to process a large number of categorical features that are really important. My questions are as follows:

How can I deal with this huge imbalance with catboost classifier. I am using the below code as of now. What changes can I make so that the overall model is efficient enough to give good results?

`best_params = {'depth': 5,
        'iterations': 1000,
        'learning_rate': 0.01,
        'random_strength': 0.8,
        'random_seed':1,
        'cat_features':categorical_features_indices,
        'eval_metric':'AUC',
        'verbose':200}
        model = CatBoostClassifier(**best_params)

        model.fit(
                 X_train, y_train,
                 eval_set=(X_test, y_test),
                 use_best_model=False,
                 plot=True
                 )`

2. Is there an impact of adding a randomness to the data before doing a test and train split and then processing the split with Catboost classifier? If I remove it then the algo runs fine but if I add the randomness, it gives the following error. Just to given an idea here, all the features are encoded except the ones which are categorical as categorical features should be evaluated by catboost itself by categorical_feature_indices
catboost version: 0.24.2

`CatBoostError: Bad value for 
num_feature[non_default_doc_idx=0,feature_idx=3]="Eng/Tech": Cannot convert 'b'Eng/Tech'' to float`

Why could this be a probable issue? 

Operating System: MacOs
CPU:
# GPU:

**Comment by nikitxskv** [comment]
Hi @ishan42d !
1. You can try to add parameter `auto_class_weights='Balanced'`. It generates weight for each class so to rise the importance of the non-dominant class.
2. I think that you have column indices mismatch. Try to add new randomness column as the last one.
