### ISSUE TITLE
Understanding Conversion of Categorical values to Numerical 

### ISSUE THREAD

**Issue by SMS786** [catboost/catboost#146]
Reading the section for classification on this page : [https://tech.yandex.com/catboost/doc/dg/concepts/algorithm-main-stages_cat-to-numberic-docpage/#algorithm-main-stages_cat-to-numberic](url)

It seems CatBoost uses a modified version of average response ratio for encoding Categoricals.
My question is : What happens while doing predictions ? 
Do you calculate a single value for each unique value of a categorical feature from the training set and use that in the testing set?

Or is it something else?

I tried but couldn't find this info anywhere in the documentation.
Any external reference is also fine.
Thanks.

**Comment by annaveronika** [comment]
When doing prediction we suppose that the test document is the next document after the last document in train.

**Comment by lmassaron** [comment]
Is there any way to extract from a fitted model, for each level of each categorical feature, the value used at test time?

**Comment by annaveronika** [comment]
It's really tricky currently, there is no good way and the tricky way is not documented. We plan to improve documentation for everything that is related to categorical features. There is an issue for that, follow that one, and write there what is important for you to have in docs.
