### ISSUE TITLE
Wrong message "Uncertainty Prediction asked for model fitted without Posterior Sampling option"

### ISSUE THREAD

**Issue by bduclaux** [catboost/catboost#1462]
Problem: Message should not be displayed
catboost version: 0.24.2
Operating System: Linux

A model is trained with the following command line:

```
catboost-linux-0.24.2 fit  --loss-function RMSEWithUncertainty  --posterior-sampling true
```
Then inference is done with the following command line:

```
catboost-linux-0.24.2 calc --prediction-type VirtEnsembles
```
Catboost then displays this output:

```
Uncertainty Prediction asked for model fitted without Posterior Sampling option
Object info sizes: 5000 4
Object info sizes: 5000 4
Object info sizes: 5000 4
...
```

The message `Uncertainty Prediction asked for model fitted without Posterior Sampling option` seems incorrect, as the model is trained with the  `--posterior-sampling` option.

Also, would be great to have some explanations about the various Prediction Types and Output Columns in the CLI catboost calc. The recent additions (VirtEnsembles, TotalUncertainty, ...) seem very interesting, but some practical recommendations would be useful for CLI users !

**Comment by nikitxskv** [comment]
Hi @bduclaux !
Thank you for report!
We fixed it.
