### ISSUE TITLE
auto_class_weights doc unclear

### ISSUE THREAD

**Issue by BurnChrome** [catboost/catboost#1463]
Hi guys,

Thanks for creating catboost, it's very useful!

I'm having some trouble understanding how the 'Balanced' option for the parameter auto_class_weights calculates weights for each class. The doc at https://catboost.ai/docs/concepts/python-reference_parameters-list.html
doesn't elaborate much about the formula used. I find the explanation at the release notes of version 0.23.2 to be more in-depth:
https://github.com/catboost/catboost/releases/tag/v0.23.2

Maybe consider adding it to the docs?
It still remains unclear to me what is the origin of the w_i weights in the formula?
Should they be defined by another parameter? 

Thanks

**Comment by nikitxskv** [comment]
Hi @BurnChrome !
Thank you so much for your report!
We'll improve this parameter description.

**Comment by BurnChrome** [comment]
@nikitxskv  
Thanks for the quick reply 👍 

I quite curious about the w_i weights, could you please give a short explanation of their origin and how are they calculated?
Thanks!

**Comment by nikitxskv** [comment]
Sure, `w_i` - initial weight of i-th object in your dataset. All object weights equal the one by default. You can specify object weights using `weight` parameter in `catboost.Pool` constructor: https://catboost.ai/docs/concepts/python-reference_pool.html
