### ISSUE TITLE
Catboost raise an exception when all the features are equal and allow_const_label=True.

### ISSUE THREAD

**Issue by iagupov** [catboost/catboost#1464]
Problem: Catboost raise an exception when all the features are equal and allow_const_label=True.

I'm trying to run the following code
```
from catboost import CatBoostRegressor
model = CatBoostRegressor(allow_const_label=True)
model.fit([[1,1,1],[1,1,1],[1,1,1]], [1,1,1])
```

and it gives the error (even if I use the allow_const_label flag):
`CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/data/quantization.cpp:2434: All features are either constant or ignored.`

catboost version: 0.24.2
Operating System: Windows 10
CPU: yes.
GPU: no.

Thank you in advance.

**Comment by nikitxskv** [comment]
Hi @iagupov !
`allow_const_label` flag alow pass constant label only, not constant features.
Training a gradient boosting model with all the constant features doesn't make sense.
Why do you need this feature?

**Comment by iagupov** [comment]
I agree that this example has no sense, but in case if I will do predictions for a large number of sensors (time series forecasting) and for every sensor I will create it's own catboost model, it can turn out that some sensors would have the same constant value during the all history period (broken sensor which still generates data). For this purpose, in order to still be able to use catboost model I tried to create this artifitial example. 
But if it's not a good practice to do like this, then I will work with sensor's data quality .
Thank you for your reply.
