### ISSUE TITLE
Running time evaluation

### ISSUE THREAD

**Issue by KleinXin** [catboost/catboost#1465]
Problem: We have a test dataset with 1.7 Billion lines with #dim=9. In order to evaluate the running time of each records, we did two tests. Model is loaded by pickle.
               1. We use pandas.read_csv to read all data, then use predict_proba to do the prediction of all data. The running time 
                   of this function is about 8.56s. In average, 5e-6s for each records.
               2. Each record is used as input to predict_proba. However, the running time of each record is about 0.8s. 
               We use python time package to evaluate the running time.
               I want to know what predict_proba does, but I could not find the source code of predict_proba of catboost. Anyone 
               knows what's wrong?
              thx
     
catboost version: 0.23.2
Operating System: Ubuntu16.04
CPU:
# GPU:

**Comment by kizill** [comment]
Hello! When you are applying model to single line, do you still use pandas dataframe to extract that row? If so, there could be a lack of special optimizations inside Cython code for such objects. You can try two thinga here - measure time of converting each pandas row to numpy array. If it would be fast, you can try predict_proba on that array.
Another possible problem, is that your machine could possible have lots of cores and there is excessive thread creation overhead. You can try fix thos by manually setting `thread_count=1`

**Comment by KleinXin** [comment]
> Hello! When you are applying model to single line, do you still use pandas dataframe to extract that row? If so, there could be a lack of special optimizations inside Cython code for such objects. You can try two things here - measure time of converting each pandas row to numpy array. If it would be fast, you can try predict_proba on that array.
> Another possible problem, is that your machine could possible have lots of cores and there is excessive thread creation overhead. You can try fix this by manually setting `thread_count=1`

thx! I am using pickle re-implemented by AutoGluon. It loads sub-models after loading the ensembled model. That's why it is so time-consuming.
