### ISSUE TITLE
Is it possible to install CatBoost on an ARM server?

### ISSUE THREAD

**Issue by zhenlingcn** [catboost/catboost#1472]
The CPU of my server is based on ARM architecture when I was trying to install CatBoost. The following error occurs:
```bash
ERROR: Could not find a version that satisfies the requirement catboost>=0.23.2 (from pycaret) (from versions: none)
ERROR: No matching distribution found for catboost>=0.23.2 (from pycaret)
```
This not only hinders me from using CatBoost but also impedes me from using other auto-ml frameworks. Therefore, is it possible to support ARM architecture in the near future?

**Comment by andrey-khropov** [comment]
We do not support ARM right now but this work is in progress. 

Are you interested in training CatBoost models on ARM-based computers or only in inference with models trained elsewhere?

**Comment by zhenlingcn** [comment]
In my case, training on my ARM-based computer is critical because I have a high-performance computing server based on ARM chips.

**Comment by kizill** [comment]
Hello! If we are speaking about cross-compilation for aarch64 - we are planning to finish it in a matter of a month (i hope, with CUDA support).

**Comment by naifmeh** [comment]
@kizill : Are there any update on the matter ? 
Thanks in advance for your answer.

**Comment by af258963** [comment]
@zhenlingcn  

> Hello! If we are speaking about cross-compilation for aarch64 - we are planning to finish it in a matter of a month (i hope, with CUDA support).

Is the ARM architecture supported now?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Not yet. Still in progress.

**Comment by sadr1an1** [comment]
But it is any way possible to run it only for evaluation not for training?

**Comment by kizill** [comment]
Now everything works just as planned, sorry for that crazy delay 🙀
To compile without CUDA support with cross-compilation toolkit.
Build app:
```
./ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app
```
Build model_interface (C API for inference):
```
./ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app
```
To compile with SBSA CUDA with cross-compile toolkit please install `cuda-cross-sbsa` package and add `-DCUDA_ROOT=/path/to/installed/cuda` (on ubuntu it's `/usr/local/cuda-11.3`):
```
./ya make -r -DHAVE_CUDA=yes --target-platform default-linux-aarch64 catboost/libs/model_interface/ -DCUDA_ROOT=/usr/local/cuda-11.3/
```
So now i'm closing as DONE 🥳

**Comment by kizill** [comment]
Forgotten to say - we will test and then deploy cross-compiled libraries on PYPI in next major release.

**Comment by felipehertzer** [comment]
Hello, I need to run this package on an aarch64 (raspberrypi) system, however pip installation is not yet available, I tried compiling with windows, mac and linux (ubuntu). But it doesn't work, on ubuntu I get the error below, I'm attaching the log too. Is it possible that you posted the aarch64 python wheel until the pip version is released?

[build-log.txt](https://github.com/catboost/catboost/files/6716259/build-log.txt)


```
ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kizill** [comment]
We'll look again on this, thank you!

**Comment by mcseemk** [comment]
Hello, I have the same issue trying to cross-compile for aarch64 on my x86-64 Ubuntu box. The log is attached - to me it looks identical to the previously posted log though.
[log.txt](https://github.com/catboost/catboost/files/6719360/log.txt)

**Comment by zhenlingcn** [comment]
@kizill Hello, it seems that the cross-compiled library is still not available on PYPI. Is there any recent news in this regard?

**Comment by arestifo** [comment]
Hey, if anyone is still interested I wrote up some instructions to get Python `catboost` wheels working on `linux/arm64`: https://github.com/catboost/catboost/issues/2091
