### ISSUE TITLE
Errors in R Package Installation

### ISSUE THREAD

**Issue by skw1990** [catboost/catboost#148]
Hi, 

I have followed through every single steps yet I am unable to install catboost in R. I have all the steps as per link: https://github.com/catboost/catboost/issues/30

_My error output in R is shown as below. Kindly assist:_
`Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/wui_u/AppData/Local/Temp/Rtmp4KcUbs/devtools2b9842037c51/catboost-catboost-2c11c86/catboost/R-package"  \
  --library="C:/Users/wui_u/OneDrive/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/wui_u/AppData/Local/Temp/Rtmp4KcUbs/devtools2b9842037c51/catboost-catboost-2c11c86/catboost/R-package/src/../../../ya.bat make -r -o ../../..
**2017-10-29T23:04:26.481000 [MainThread] Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).**
Config was not generated due to errors in C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py", line 2055, in <module>
    main()
  File "C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py", line 2048, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py", line 437, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py", line 547, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "C:\Users\wui_u\AppData\Local\Temp\Rtmp4KcUbs\devtools2b9842037c51\catboost-catboost-2c11c86\build\ymake_conf.py", line 804, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe

make: *** [all] Error 1
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/wui_u/OneDrive/Documents/R/win-library/3.4/catboost'
Installation failed: Command failed (1)`

**Comment by sab** [comment]
DEVTOOLS-3924 (internal issue id)

**Comment by skw1990** [comment]
Sorry @sab, what does that mean ya?

**Comment by skw1990** [comment]
Halo, any help or response would be much appreciated. Thanks.

**Comment by sab** [comment]
@skw1990 it's just an id of this issue in our internal issue tracker. I hope we'll solve it soon.

**Comment by skw1990** [comment]
Hi, any luck thus far? Can't wait to test it =)

**Comment by annaveronika** [comment]
We could not solve your problem.
As some people have problems with R package installation, we decided to publish compiled versions of the package. The progress will be reported in https://github.com/catboost/catboost/issues/63. For now I could only suggest to try again or to use python or command line utility.
