### ISSUE TITLE
Error while trying to create a Pool for ranking

### ISSUE THREAD

**Issue by Bhaskarkvvsr** [catboost/catboost#1481]
Problem: I am trying to build a ranking model using Catboost library. I am getting the below error while creating a Pool on my training set.

CatBoostError: catboost/private/libs/data_types/query.cpp:25: Error: queryIds should be grouped

catboost version: '0.24.2'
Operating System: Ubuntu
CPU: AMD Rome

**Comment by LyzhinIvan** [comment]
Hi, @Bhaskarkvvsr ! The error is self-descriptive - objects from the same group should be placed successively, for example see documentation of `group_id` parameter https://catboost.ai/docs/concepts/python-reference_pool.html.

**Comment by biarne-a** [comment]
This error message is absolutely NOT self-descriptive.
Your message is 1000 times better => "objects from the same group should be placed successively"

**Comment by super1ha1** [comment]
Yes, you should sort the dataframe by group_id before using it to create the pool

**Comment by GreyRaphael** [comment]
> Yes, you should sort the dataframe by group_id before using it to create the pool

I works for me
