### ISSUE TITLE
CatBoostRegressor produces unstable results when training with RMSE

### ISSUE THREAD

**Issue by zollen** [catboost/catboost#1483]
I have been experimenting with the new CatBoostRegressor, but the regression results are never fixed/constant. Each run has a slightly different results. Setting the random_state or random_seed don't work. Any idea?

Is it even possible to stabilize the regression results, or is this by designed?

catboost **0.24.2**

**Comment by kizill** [comment]
Do you use gpu for training?

**Comment by zollen** [comment]
No. I don't use gpu. Please close this ticket. I think it figured out the minor randomness. I dynamically determine all of the categorical column names and each run the order of the column names are different. That was what caused the issue.
