### ISSUE TITLE
Does cpu version use 4 permutations ?

### ISSUE THREAD

**Issue by yiyiyi4321** [catboost/catboost#1488]
Problem:  Does cpu version use 4 permutations ?
catboost version: lastest
Operating System: win10
CPU: cpu version
# GPU:

**Comment by LyzhinIvan** [comment]
Hi, @yiyiyi4321! Yes, if you have categorical features or use ordered boosting. 3 permutations are used for tree splits selection, 4th permutation is used for leaf values calculation.
