### ISSUE TITLE
How exactly catboost predictions are obtained?

### ISSUE THREAD

**Issue by maksymiuks** [catboost/catboost#1490]
Hi

In the beginning, I'd like to appreciate your work covering that package. I consider it a great tool. That's why I'm working on a dedicated R interface for tree ensemble models that allows calculating shap values fast using C++ code via Rcpp. catboost package is one in the scope of my interest. But for that, I need the information on how exactly the committee of trees is aggregated. To be honest I have no clue nor find anything in the documentation. Can you provide me with that information?

Best Regards
Szymon Maksymiuk

**Comment by LyzhinIvan** [comment]
> how exactly the committee of trees is aggregated
Hi, @maksymiuks! The final prediction of the trees ensemble in CatBoost is just the sum of predictions from each tree of the ensemble. Depends on `prediction_type`, one of the following post-processing steps can be applied to this final prediction:
1) `prediction_type=Class` - the output is a label of class with the greatest prediction.
2) `prediction_type=Probability` - Sigmoid function is applied for binary classification problems and Softmax for multi classification problems.
3) `prediction_type=LogProbability` - logarithm of Probability.
4) `prediction_type=Exponent` - exponent of predictions (default for Tweedie and Poisson).
