### ISSUE TITLE
Catboost installation on python docker slim image issue

### ISSUE THREAD

**Issue by pod2metra** [catboost/catboost#1491]
Problem:
It's impossible to install catboost on docker image. 

Dockerfile:

```
FROM python:3.9.0-slim as base

RUN pip install -U pip && pip install --upgrade setuptools && pip install catboost==0.24.2
```

docker build ./

error:
```
ERROR: Could not find a version that satisfies the requirement catboost==0.24.2 (from versions: 0.1.1.2)
ERROR: No matching distribution found for catboost==0.24.2
```

catboost version: 0.24.2
Operating System: 
CPU:
# GPU:

**Comment by LyzhinIvan** [comment]
Hi, @pod2metra! We don't build packages for python 3.9 right now, but will soon. Now you can use python 3.8.

**Comment by pod2metra** [comment]
Thank you, on python:3.8.6-slim install was completed.
