### ISSUE TITLE
Target contains only one unique value, but the dataset is imbalance.

### ISSUE THREAD

**Issue by minhlong94** [catboost/catboost#1496]
Problem: Classification on an imbalance dataset
catboost version: 0.24.2
Using Kaggle Kernel

I have a highly imbalance classification task. The target consists of n rows, where there is only few class `0` (sometimes only 1 row) and a lot of class `1`. When using sklearn `KFold` or `StratifiedKFold`, there are chances that the label only consists of one class (`1` for example), and it throws the error `CatBoostError: catboost/private/libs/target/target_converter.cpp:376: Target contains only one unique value`. I would like to know if there is any method to resolve this issue?

**Comment by LyzhinIvan** [comment]
You should generate folds properly. There is no need to fit model on constant target, so CatBoost doesn't do it. By the word, if you use StratifiedKFold with number of folds not greater than number of zeros, is shouldn't happen.

**Comment by pha377** [comment]
It is useful to allow fit model on constant target when you are fitting a model in several parts.
