### ISSUE TITLE
Makefile fails with error: No rule to make target '/home/edge-dev01/catboost/make/contrib/libs/cppdemangle/cxa_demangle.cpp

### ISSUE THREAD

**Issue by Tagussan** [catboost/catboost#1498]
Problem: Because current catboost does not support ARM architecture, I'm trying to build it with Makefile, which is [introduced here](https://github.com/catboost/catboost/issues/408#issuecomment-405340402). After I set `CC` and `CXX` in the Makefile, I got this error in any execution of makefiles in the make directory:
```
_CC_VERSION = '7 0'
_CXX_VERSION = '7 0'
make: *** No rule to make target '/home/edge-dev01/catboost/make/contrib/libs/cppdemangle/cxa_demangle.cpp', needed by '/home/edge-dev01/catboost/make/contrib/libs/cppdemangle/cxa_demangle.cpp.pic.o'.  Stop.
```
Do I need to set additional config parameter in the Makefile?

catboost version: branch master Nov. 24th, 2020
Operating System: Ubuntu 18.04 (using clang-7 package for compiler)
CPU: aarch64

**Comment by kizill** [comment]
We now support compilation with latest clang. Now everything works just as planned, sorry for that crazy delay 🙀
To compile without CUDA support with cross-compilation toolkit:
```
./ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app
```
To compile with SBSA CUDA with cross-compile toolkit:
```
./ya make -r -DHAVE_CUDA=yes --target-platform default-linux-aarch64 catboost/libs/model_interface/ -DCUDA_ROOT=/usr/local/cuda-11.3/
```
So now i'm closing as DONE 🥳
