### ISSUE TITLE
Catboost error: array_subset.h:650: TIndexedSubset >= srcSize

### ISSUE THREAD

**Issue by bm2609** [catboost/catboost#1499]
Problem:

Dear all, first of all I would like to thank you for writing this great module. I am using the Catboost classifier in Python with the following settings:

```
def build_model() -> CatBoostClassifier:
    cb = CatBoostClassifier(
        iterations=10000,
        early_stopping_rounds=1000,  
        loss_function='CrossEntropy',
        max_ctr_complexity=1,
        has_time=True,
        task_type="GPU",
        devices=None,
        random_seed=1988,
    )
    return cb


def make_param_grid() -> Dict:
    params = {
        'learning_rate': [round(num, 2) for num in np.arange(0.001, 0.17, 0.02).tolist()],
        'depth': np.arange(4, 11).tolist(),  
        'l2_leaf_reg': [1, 2, 3, 5, 8, 13, 21, 34],
        'random_strength': [1, 2, 3] 
    }
    return params
```

However, when using hyperparameter tuning, I get this error:

`_catboost.CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/helpers/array_subset.h:650: TIndexedSubset[8764] (766514) >= srcSize (766494)`

The number 766514  after `TIndexedSubset[8764]` correlates to number of rows in my training set. Unfortunately, I cannot explain this error. My first guess was that size of training set might have an impact, but it turned out that the error occurs for different sizes. 

Best ,
Ben

catboost version: 0.24.2
Operating System: Windows 
CPU: Intel Xeon E5 2690 v4
GPU: NVIDIA Tesla P40

**Comment by kizill** [comment]
Hello, we've missed this error. Can you check it on a new version and, if possible, send us a full code sample, that reproduces your error (for example, on a randomly filled dataframes)?
