### ISSUE TITLE
Windows: Did anyone succeed in installing R package?

### ISSUE THREAD

**Issue by akogay** [catboost/catboost#15]
Error during installing from zip file:
install.packages("C:/Users/kogayaa/Downloads/catboost-master.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'catboost-master/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

install github error:

 install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/Users/kogayaa/Desktop/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/kogayaa/AppData/Local/Temp/Rtmp8g9Ngq/devtools81cc45f52243/catboost-catboost-87e5a37/catboost/R-package"  \
  --library="C:/Users/kogayaa/Desktop/R-3.4.0/library" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/kogayaa/AppData/Local/Temp/Rtmp8g9Ngq/devtools81cc45f52243/catboost-catboost-87e5a37/catboost/R-package/src/../../../ya.bat make -r -o ../../..
[ya.bat] Error: Python not found 
make: *** [libcatboostr.dll] Error 1
Предупреждение: работающая команда 'make --no-print-directory -f "Makefile.win"' имеет статус 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/kogayaa/Desktop/R-3.4.0/library/catboost'
Error: Command failed (1)

**Comment by alex-danilin** [comment]
Error: Python not found

The problem must be here. Try to install Python.

**Comment by akogay** [comment]
@alex-danilin how do you fix that problem with Python?

I added path to Anaconda version of Python in my "Path" and it still ask about Python :(

**Comment by alex-danilin** [comment]
I have these values in Path for my user:
C:\Users\mrbubu\Anaconda2
C:\Users\mrbubu\Anaconda2\Scripts
C:\Users\mrbubu\Anaconda2\Library\bin

**Comment by AITikhonov** [comment]
Yes, I successed install R package, but only on Linux...

**Comment by pakuipers** [comment]
Also successful on Mac OS X.

**Comment by Mrugankakarte** [comment]
I guess it doesn't work with anaconda version. 
Install it from [here](https://www.python.org/downloads/) and try again.

I have python 3.5.2
I am getting some different error
```
Config was not generated due to errors in C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py
ERROR:root:In toolchain theyknow, detected system cl compiler from VS version 15.0
Traceback (most recent call last):
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 2290, in <module>
    main()
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 2277, in main
    tc_params["platform"]["target"]["arch"])
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 757, in print_full_build_type
    tc = Toolchain(toolchain_name)
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 660, in __init__
    self.toolchain_by_cxx_compiler_file_name()
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 698, in toolchain_by_cxx_compiler_file_name
    cxx_info[3](self)
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 706, in detect_msvc_
    detect_msvc(self)
  File "C:\Users\Mrugank\AppData\Local\Temp\Rtmpkt1u5c\devtools27e861fe54ec\catboost-catboost-7e4ba38\build\ymake_conf.py", line 1590, in detect_msvc
    vc_key = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\Vc7")
WindowsError: [Error 2] The system cannot find the file specified
```
If anyone knows what it means, please help.

Also when I try installing locally, it says `Warning in install.packages :
  package ‘catboost_0.1.1.2.tar.gz’ is not available (for R version 3.4.1)`

**Comment by Mrugankakarte** [comment]
@akogay  I got it working....
Check out #30

**Comment by PetoLau** [comment]
Hello,
I have this problem while installing catboost package on Windows 10:
```
TypeError: resolve_system_cxx() takes exactly 4 arguments (3 given)
make: *** [all] Error 1
```
Any suggestions? Thx

**Comment by annaveronika** [comment]
@PetoLau It's more safe to create a new issue or comment on an active one, because otherwise your comment might be lost.
@exprmntr Could you take a look?

**Comment by exprmntr** [comment]
`TypeError: resolve_system_cxx() takes exactly 4 arguments (3 given)` will be fixed in next version
