### ISSUE TITLE
Evaluation set fraction

### ISSUE THREAD

**Issue by glebmikha** [catboost/catboost#1500]
Hi! Do you have plans to add feature of just specifying a fraction of train set that we want to use? Because now we have to create eval set manually by slicing train. For example, sklearn has this feature in GradientBoostingClassifier, there is validation_fraction parameter. Please see usage example here https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_early_stopping.html . 

It would be very nice for speeding up the whole modeling process. Thank you!

P.S. Thank you for CatBoost. It's a so awesome tool. I love it so much.

**Comment by fingoldo** [comment]
It is really a big issue. It prevents from proper using of catboost as a part of pipeline, especially when validation set is required, because pipeline can have steps which change data cells based on the whole train subset. So, simply passing clf__eval_set to a pipeline won't work because, for instance, eval_ data won't undergo same decoding steps as train data within the pipeline. So it must be done at estimator level, if we want to use pipelines.
I tried subclassing CatBoostClassifier like this:
```python

from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

class CustomCatBoostClassifier(CatBoostClassifier):
    
    def __init__(self, val_size:float=0.05,**init_params):
        self.val_size=val_size
        return super().__init__(self,**init_params)
    
    def fit(self, X, y=None, **fit_params):
        if self.val_size==0:
            return super().fit(
                X,
                y=y,            

                **fit_params
            )            
        else:
            X_train_train, X_train_val, y_train_train, y_train_val = train_test_split(X, y, test_size=self.val_size,shuffle=True)
            return super().fit(
                X_train_train,
                y=y_train_train,            

                eval_set=(X_train_val,y_train_val),

                **fit_params
            )
```

however, I am getting error as presumably catboost tries to serialize someting behind the curtains:

> 
> ~/.local/lib/python3.7/site-packages/catboost/core.py in _prepare_train_params(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
>    1834         _check_param_types(params)
>    1835         params = _params_type_cast(params)
> -> 1836         _check_train_params(params)
>    1837 
>    1838         eval_set_list = eval_set if isinstance(eval_set, list) else [eval_set]
> 
> _catboost.pyx in _catboost._check_train_params()
> 
> _catboost.pyx in _catboost._check_train_params()
> 
> _catboost.pyx in _catboost._PreprocessParams.__init__()
> 
> /usr/local/bin/anaconda3/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
>     236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
>     237         separators=separators, default=default, sort_keys=sort_keys,
> --> 238         **kw).encode(obj)
>     239 
>     240 
> 
> /usr/local/bin/anaconda3/lib/python3.7/json/encoder.py in default(self, o)
>     177 
>     178         """
> --> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
>     180                         f'is not JSON serializable')
>     181 
> 
> TypeError: Object of type CustomCatBoostClassifier is not JSON serializable

Is there any recommended way to use validation in the pipeline?
Or at least make subclassed catboost JSON serializable?

**Comment by fingoldo** [comment]
Deat CatBoost developers, any response on adding validation_fraction functionality? It would make lives of many applied data scientists a lot easier...

**Comment by WildFrontier1986** [comment]
> Hi! Do you have plans to add feature of just specifying a fraction of train set that we want to use? Because now we have to create eval set manually by slicing train. For example, sklearn has this feature in GradientBoostingClassifier, there is validation_fraction parameter. Please see usage example here https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_early_stopping.html .
> 
> It would be very nice for speeding up the whole modeling process. Thank you!
> 
> P.S. Thank you for CatBoost. It's a so awesome tool. I love it so much.

It is great idea!

**Comment by fingoldo** [comment]
btw the most general solution would be to make evaluation set stratified/unstratified, shuffled/unshuffled, ie, exactly replicate train_test_split capabilities.

**Comment by fingoldo** [comment]
Note that, while it's being implemented natively, you can use a subclassing workaround:

```python

from sklearn.utils.validation import check_X_y, check_array, check_is_fitted, check_consistent_length
from sklearn.base import RegressorMixin, ClassifierMixin, TransformerMixin, BaseEstimator, clone
from sklearn.utils.estimator_checks import check_estimator, check_transformer_general
from sklearn.utils import check_random_state

class EstimatorWithEarlyStopping(BaseEstimator):
    """
        Adds early stoppping in pipeline to estimators that only accept fixed evaluation set, like Catboost.
    """
    def __init__(self, base_estimator=None, test_size=0.05, train_size=None, random_state=None, shuffle=True, stratify=None, plot: bool = False):
        self.plot = plot
        self.base_estimator = base_estimator
        self.test_size, self.train_size, self.random_state, self.shuffle, self.stratify = test_size, train_size, random_state, shuffle, stratify

    def fit(self, X=None, y=None, **fit_params):
    
        random_state = check_random_state(self.random_state)

        # Check that X and y have correct shape
        #X, y = check_X_y(X, y)
        
        self.random_state_ = random_state
        fitted_estimator = clone(self.base_estimator)
        
        if "CatBoost" in type(fitted_estimator).__name__:
            X_train, X_val, y_train, y_val = train_test_split(
                X, y, test_size=self.test_size, train_size=self.train_size, random_state=random_state, shuffle=self.shuffle, stratify=self.stratify
            )
            fitted_estimator.fit(X_train, y_train, eval_set=(X_val, y_val), plot=self.plot, **fit_params)            
        else:
            logger.warning(f"Early stoppping params for estimator of type {type(self.base_estimator)} unknown.")
            fitted_estimator.fit(X, y, **fit_params)
                    
        self.fitted_estimator_=fitted_estimator
        
        self.n_features_in_=X.shape[1]   
        
        return self

    def predict(self, X=None):

        # Check is fit had been called
        check_is_fitted(self)

        # Input validation
        #X = check_array(X)
        
        return self.fitted_estimator_.predict(X)


class RegressorWithEarlyStopping(EstimatorWithEarlyStopping, RegressorMixin):
    pass


class ClassifierWithEarlyStopping(EstimatorWithEarlyStopping, ClassifierMixin):
    pass
```

**Comment by fingoldo** [comment]
I noticed that eval_fraction is not specified in the docs. Someone, please add it so that people can find it ) It's also not clear what is it capable of: are shuffle, stratify supported, like in sklearn's train_test_split?

**Comment by andrey-khropov** [comment]
>  It's also not clear what is it capable of: are shuffle, stratify supported, like in sklearn's train_test_split?

It shuffles by default unless `has_time` training parameter has been specified.
It does stratified sampling if it is a classification problem.

You can see it [in the code here](https://github.com/catboost/catboost/blob/0770835f45eb8ac9cfa7c7b989c964e4ad893204/catboost/python-package/catboost/_catboost.pyx#L4480-L4483)
