### ISSUE TITLE
Custom metric evaluate() fails

### ISSUE THREAD

**Issue by OlegBEZb** [catboost/catboost#1501]
Good afternoon, colleagues!

Problem: 
I have implemented a custom metric (the code below) and replaced the previous ones (I have worked with RMSE, MAE and MAPE which performed without any problems) with a new one. The first strange thing is that I got a ValueError that I have nan in approxes list. It is strange because before the model have never predicted such values. Then I have hardcoded the residual value with a constant and tried again. After that I got the following error
 `CatBoostError: catboost/libs/metrics/metric.cpp:3848: Custom metric evaluate() returned incorrect value. Expected tuple of size 2, got tuple of size 0.`
I have hardcoded the return in the evaluate like [here](https://github.com/catboost/catboost/issues/1094#issuecomment-558288998) with 0.0, 0.0 . But the error is the same.
catboost version: 0.24
Operating System: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
CPU:   Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz

`class HuberCustomMetric(object):
    
    def __init__(self, k, shift):
        self.k = k
        self.shift = shift
        
    def get_final_error(self, error, weight):
        error / (weight + 1e-38)

    def is_max_optimal(self):
        return False

    def evaluate(self, approxes, target, weight):
        assert len(approxes) == 1
        assert len(target) == len(approxes[0])

        approx = approxes[0]

        error_sum = 0.0
        weight_sum = 0.0

        for i in range(len(approx)):
            resudial = approx[i] - target[i]
            if np.isnan(resudial):
                resudial = target[i]
                
            w = 1.0 if weight is None else weight[i]
            weight_sum += w
            error_sum += w * huber_custom_error(residual=resudial, k=self.k, shift=self.shift)

        return error_sum, weight_sum`

Thank you in advance!

**Comment by kizill** [comment]
Hello! Will figure out today.

**Comment by brandons209** [comment]
Coming across this issue today, not sure what to do to fix it. Can't find much on custom metrics with catboost, and this is the only thing I can really find on this specific issue. I looked into the code to try to find more info but can't seem to find much on it. I am using this in the multiclass setting.

**Comment by andrey-khropov** [comment]
The issue here is there is an error in `get_final_error` - it does not contain a return statement:

```
def get_final_error(self, error, weight):
    error / (weight + 1e-38)
```

According to the weird python rules it means it returns `None`.

CatBoost 1.2.2 now reports it a little bit better:

```
  File "_catboost.pyx", line 1177, in _catboost._MetricGetFinalError
TypeError: must be real number, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eval_metric_problem_gh1501.py", line 61, in <module>
    m.fit(feature, label)
  File "/Users/akhropov/.pyenv/versions/3.7/lib/python3.7/site-packages/catboost/core.py", line 5706, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
  File "/Users/akhropov/.pyenv/versions/3.7/lib/python3.7/site-packages/catboost/core.py", line 2324, in _fit
    train_params["init_model"]
  File "/Users/akhropov/.pyenv/versions/3.7/lib/python3.7/site-packages/catboost/core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4645, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4694, in _catboost._CatBoost._train
_catboost.CatBoostError: /Users/zomb-ml-platform-msk/go-agent-21.2.0/pipelines/BuildMaster/catboost.git/catboost/python-package/catboost/helpers.cpp:49: Traceback (most recent call last):
  File "_catboost.pyx", line 1177, in _catboost._MetricGetFinalError
TypeError: must be real number, not NoneType
```

If it is fixed as intented:

```
def get_final_error(self, error, weight):
    error / (weight + 1e-38)
```

everything works as expected.
