### ISSUE TITLE
Typo in documentation ("thajurt" instead of "that")

### ISSUE THREAD

**Issue by deepyaman** [catboost/catboost#1503]
Problem: Docs have "that" written as "thajurt" in multiple places on https://catboost.ai/docs/concepts/python-reference_utils_create_cd.html (likely copy-paste error). I'm more than happy to submit a PR to fix it (and would have), but I can't find a reference/docs in the repo, nor do I see a separate catboost-docs repo or documentation contribution guidelines.
catboost version: stable? latest? Not seeing an indicator on the docs.
Operating System: N/A
CPU: N/A
\# GPU: N/A

**Comment by kizill** [comment]
Fixed, thanks!
