### ISSUE TITLE
Monoforest kernel death (both .py and .ipynb)

### ISSUE THREAD

**Issue by sakalouski** [catboost/catboost#1507]
**Problem:**

When running any functionality with monoforest, kernel dies:

`model = CatBoostClassifier()`
`model.load_model('./model_test')`
`monoforest.explain_features(model)`

**Output:**

> uncaught exception:
>     address -> 0x107900000
>     what() -> "util/generic/hash.cpp:50: Key not found in hashtable: 0"
>     type -> yexception
> Aborted (core dumped)

The model file is attached - unzip before running.
[model_test.zip](https://github.com/catboost/catboost/files/5647027/model_test.zip)

At the same time everything work fine with a different model with less features and slightly different dataset:
[model_test_2.zip](https://github.com/catboost/catboost/files/5647058/model_test_2.zip)

________________________________________________
**Spec:**

Catboost version: 0.24.3
Operating System: tested on Ubuntu 20.04 and Windows 10
CPU: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
#GPU: N/A - only CPU was used for training.

**Comment by sakalouski** [comment]
Found the issue - if there is a categorical feature, kernel dies.

**Comment by LyzhinIvan** [comment]
Yes, monoforest supports only float and one-hot features. Categorical features are one-hot encoded by CatBoost if the number of categories is less or equal `one_hot_max_size` parameter. We will add check for cat features to monoforest.

**Comment by LyzhinIvan** [comment]
Fixed in 7e362faa0686ae5f2543474e5984813bc727b3e1
