### ISSUE TITLE
 No matching signature found "while fit() - ing the features and labels"

### ISSUE THREAD

**Issue by sarwarish97** [catboost/catboost#1508]
Problem: TypeError: No matching signature found "while fit() - ing the features and labels"
catboost version: 
Operating System: Windows ( working on colab)
CPU: i7
# GPU: colab GPU
![image](https://user-images.githubusercontent.com/34837506/101247103-467c0e00-373d-11eb-9af0-37c9325b6b58.png)
![image](https://user-images.githubusercontent.com/34837506/101247149-965ad500-373d-11eb-94c6-7526baede89d.png)
![image](https://user-images.githubusercontent.com/34837506/101247168-bab6b180-373d-11eb-89ce-11b581de9bec.png)

**Comment by sarwarish97** [comment]
**age_group is not present in X_train, it has been sliced off**

**Comment by kizill** [comment]
Sorry for such a long wait, but can you remember the type of y_train & y_test?

**Comment by kizill** [comment]
Reproduced and fixed in 1.0.0 release. Closing as fixed.

**Comment by andrey-khropov** [comment]
> Reproduced and fixed in 1.0.0 release. Closing as fixed.

Actually fixed in 1.0.1.
