### ISSUE TITLE
Failing to initialize CatBoostClassifier

### ISSUE THREAD

**Issue by amr544** [catboost/catboost#1509]
While running this command  `model = CatBoostClassifier()` I get the following error:

`  File "/usr/local/lib/python3.9/site-packages/catboost/core.py", line 882, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "/usr/local/lib/python3.9/site-packages/catboost/core.py", line 331, in __init__
    super(CatBoost, self).__init__(params)
RecursionError: maximum recursion depth exceeded while calling a Python object`

Any idea what's causing this error? 

python version: 3.9.0
catboost version: 0.1.1.2
Operating System: Mac OS Catalina 10.15.7
CPU: 2.6 GHz 6-Core Intel Core i7

**Comment by levitsky** [comment]
Be aware that you are using a three years outdated version of Catboost, because that's what `pip` pulls for you on Python 3.9. I just filed this as #1510.

**Comment by kizill** [comment]
Released in 0.24.4, please try!
