### ISSUE TITLE
Cannot Get Shap Values after using monotone_constraints argument

### ISSUE THREAD

**Issue by cc4019** [catboost/catboost#1512]
Problem: Cannot Get Shap Values after using monotone_constraints argument. Showing error: _catboost.CatBoostError: catboost/libs/fstr/util.cpp:114: Cannot calc shap values, model contains non zero approx for zero-weight leaf.

Arguments used:
dict(eval_metric='RMSE',
        iterations=500,
        learning_rate=0.1,
        od_type='Iter',
        od_wait=10,
        depth=4,
    ),
catboost version:0.24.3
Operating System: Linux
Using CPU

**Comment by kizill** [comment]
We are preparing a fix for that issue, hope it'll appear in next release!

**Comment by kizill** [comment]
Released in 0.24.4, please try it :)

**Comment by cc4019** [comment]
Hi all,

Thank you so much for the quick fix!!

Happy holidays!!
