### ISSUE TITLE
This program was compiled for SSE42 which no supported on your system ....

### ISSUE THREAD

**Issue by TangoXX** [catboost/catboost#1513]
Problem: 
![Снимок](https://user-images.githubusercontent.com/75798638/101793617-aba17c00-3b0e-11eb-88d9-c393ae866e81.PNG)

catboost version:  0.24.3
Operating System: Windows 7 64 bit
CPU: AMD Atlon(tm) X2 240 2.8- GHz
# GPU: NVIDIA Geforce 8600 GT

**Comment by kizill** [comment]
Hello! Sorry, but currently we don't support non sse4.2 CPU's.
You can try to overcome that problem by building catboost from soures with `ya make -DDISABLE_INSTRUCTION_SETS -DNO_SSE` flags on machine with sse4.2 instructions (maybe on cloud machines) and then use catboost build without any sse instructions on your local machine.
See https://github.com/catboost/catboost/issues/1009 for more information and feel free to ask how to overcome some problems.
