### ISSUE TITLE
quantize from file returns errors catboost.CatBoostError: catboost/libs/data/load_and_quantize_data.cpp:52: Categorical features are not supported in block quantization

### ISSUE THREAD

**Issue by botasb** [catboost/catboost#1516]
Problem: catboost.CatBoostError: catboost/libs/data/load_and_quantize_data.cpp:52: Categorical features are not supported in block quantization

When trying to execute the following line:
quantized_pool=quantize(data_path="/mnt/cat.csv", delimiter=",", column_description="/mnt/desc_cat", has_header=True, task_type="GPU", random_seed=32)

I get the error:
 catboost.CatBoostError: catboost/libs/data/load_and_quantize_data.cpp:52: Categorical features are not supported in block quantization

But all features in the file are numerical (either int or float).

catboost version: latest
Operating System: Ubunru 18.04
CPU:
# GPU:

**Comment by kizill** [comment]
Hello! We need some small sample - can you give us a sample of `cat.csv` and `desc_cat` (maybe with random data) that will help us reproduce your problem?

**Comment by kizill** [comment]
Closing as irreproducible for now, feel free to reopen!
