### ISSUE TITLE
`_get_tags()` is missing `pairwise`

### ISSUE THREAD

**Issue by Yard1** [catboost/catboost#1518]
Problem:
With the release of scikit-learn 0.24.0, the `_safe_split()` method in `sklearn/utils/metaestimators.py` has been modified to check for `pairwise` attribute through the `_get_tags()` method. Considering that Catboost's implementation of `_get_tags()` is missing `pairwise`, scikit-learn throws an exception in any method that uses `_safe_split()`, like `cross_validate()`. The solution would be to add `pairwise` to the dictionary returned by Catboost's `_get_tags()`.

**Comment by probeadd** [comment]
I got this too!

**Comment by kizill** [comment]
Fixed in master, will be in next release. Thanks!

**Comment by kizill** [comment]
Released in 0.24.4, please try it :)
