### ISSUE TITLE
Training Catboost models with Multiple Chunks of data

### ISSUE THREAD

**Issue by mathankumart** [catboost/catboost#152]
When I tried to load data of 22 GB csv file in panda dataframes for training, the process got crashed.. As I couldn't hold that big data in a single panda dataframe, is it possible to train catboost with multiple chunk of panda dataframes?

**Comment by annaveronika** [comment]
You could try training from file, this will not use additional memory for dataframe.
https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_pool-docpage/
So you need to pass filename when constructing Pool

**Comment by annaveronika** [comment]
Here is an example:
https://tech.yandex.com/catboost/doc/dg/concepts/python-usages-examples-docpage/#load-the-dataset-from-a-file

**Comment by annaveronika** [comment]
Also, if you want to work with large datasets it is more efficient to perform training on gpu. This might speed up the training up to 40 times. It is currently only commandline, but we'll add python in very short time.

**Comment by annaveronika** [comment]
About training on multiple chunks of data - we do not plan to train on multiple chunks of data on single machine, but it will be possible to train on multiple chunks on multiple machines when we finish
https://github.com/catboost/catboost/issues/153

**Comment by RiverShah** [comment]
I have a node with 8 GPUs. Each GPU has memory of 8GB. Am I limited to the quantised dataset fitting into 8GB or can the dataset be as large as 64GB if I select all devices during regressor initialization?
