### ISSUE TITLE
Площадь под кривой Precision-Recall

### ISSUE THREAD

**Issue by AlexanderSerbul** [catboost/catboost#1522]
Добрый вечер!

Спасибо за отличную, полезную в работе библиотеку! Молодцы!

Очень не хватает встроенной eval-метрики расчета площади под кривой Precision-Recall. AUC ненадежно работает на несбалансированных датасетах, которых в нашей практике большинство.

Добавьте пожалуйста. Спасибо!

**Comment by kizill** [comment]
Привет!
У нас уже есть нужна тебе метрика, просто задай `PRAUC` в качестве метрики.
Спасибо за теплые слова !
