### ISSUE TITLE
Результат сильно хуже после обновления с 22 версии

### ISSUE THREAD

**Issue by krumal** [catboost/catboost#1523]
Problem:
После обновления с версии с 22 (на 23.2 или на 24.3) я получаю результат сильно хуже на своей модели регрессии
параметры модели:
'task_type': 'GPU'
'iterations': 5000,
'learning_rate': 0.005,
'depth': 6,
'loss_function': 'RMSE',
'boosting_type': 'Plain', 
'random_seed': 0,
'l2_leaf_reg': 3, 
'score_function': 'Cosine', 
'leaf_estimation_method': 'Newton', 
'bootstrap_type': 'Bayesian',
'feature_border_type': 'GreedyLogSum',
'border_count': 128,  
'grow_policy': 'SymmetricTree',
'gpu_cat_features_storage': 'CpuPinnedMemory'

Подскажите пожалуйста, в чем может быть причина? 
Какие параметры попробовать изменить, добавить? 

Operating System: ubuntu 20.04
GPU: 2080s

**Comment by kizill** [comment]
Попробуйте выключить mvs бутстрап и вместо него использовать Байесовский бутстрап: `bootstrap_type=Bayesian`. Напишете потом, помгло или нет?

**Comment by kizill** [comment]
Если будет какая-то информация, которая нам поможет - переоткрывайте issue, пока закрываю так как никакой проясняющей информации не поступило.
