### ISSUE TITLE
support sklearn metric with OptunaSearchCV

### ISSUE THREAD

**Issue by ilgrad** [catboost/catboost#1527]
Problem: 
```
from optuna.integration import OptunaSearchCV
from optuna.distributions import IntUniformDistribution, UniformDistribution, CategoricalDistribution
import catboost as ctb

model_clf_ctb = ctb.CatBoostClassifier(
    learning_rate=0.03,
    loss_function='MultiClass',
    depth=9,
    iterations=200,
    random_seed=123,
    classes_count=9,
    logging_level='Silent')

param_clf_ctb = {'bagging_temperature': UniformDistribution(0.0, 1.0),
                 'random_strength': UniformDistribution(0.0, 1.0),
                 'rsm': UniformDistribution(0.0, 1.0),
                 'auto_class_weights': CategoricalDistribution(['None', 'Balanced']),
                 'l2_leaf_reg': UniformDistribution(0.0, 1.0)}

optuna_clf_ctb_search = OptunaSearchCV(
    estimator=model_clf_ctb,
    param_distributions=param_clf_ctb,
    #scoring=None,
    random_state=123,
    n_trials=20,
    verbose=1,
    n_jobs=-1,
    cv=5)

optuna_clf_ctb_search.fit(train, labels)
```
error:
ValueError: The key pairwise is not defined in _get_tags() for the class CatBoostClassifier.
catboost version: 0.24.4
Operating System: Fedora 33
CPU: i7-3520m

With error also if I use scoring='neg_log_loss'  and others from sklearn.metrics.SCORERS.keys().
as i understood  there is no connection between metrics sklearn and catboost.

**Comment by kizill** [comment]
Please, check twice that you are using proper version:             f.e. print `catboost.__version__`
Because in released version we definetly set pairwise tag to False
https://github.com/catboost/catboost/blob/0d107dd5d9cc08709030a50cc316d00de69f6f1e/catboost/python-package/catboost/core.py#L1526

**Comment by ilgrad** [comment]
Thank you, I restart jupyter and load version 0.24.4. everything is working)
