### ISSUE TITLE
Training CatBoost on huge data crashes PC (2 x RTX3090 = 48GB VRAM full)

### ISSUE THREAD

**Issue by CallShaul** [catboost/catboost#1530]
**Problem:** The GPU drivers seems to crash every now and then for unexpected reason stopping the calculation, it happens only using CatBoost GPU calculations. 
(according to windows task manager the max temperature of the GPU's are 60 - 73 degrees while working)
**CatBoost version:** 0.24.3
**Operating System:** Windows 10 Enterprise version 10.0.19042
**CPU:** i9-10900X with X299-WU8 motherboard and 128 GB RAM
**# GPU:** dual Gigabyte RTX 3090 24 GB (with latest drivers 460.89 and CUDA 11.1)

![image](https://user-images.githubusercontent.com/52006780/103538825-a205fc80-4e9f-11eb-9371-1d4d2a9884c8.png)

![image](https://user-images.githubusercontent.com/52006780/104731423-5592aa80-5744-11eb-8f95-bb76063d9f48.png)

Comparing to normal operation device manager:
![image](https://user-images.githubusercontent.com/52006780/104731321-3431be80-5744-11eb-8277-d78ee2e60638.png)

**Comment by CallShaul** [comment]
After upgrading to CatBoost version 0.24.4 instead of driver crashes, this error happens (every now and then):

![image](https://user-images.githubusercontent.com/52006780/103568412-28d1ce00-4ece-11eb-84c0-4e4f7f04ac1e.png)

**Comment by CallShaul** [comment]
Update: it seems this crash happens when calculation is done with one fold, starting the next one.
Still no solution for running 5-folds straight with a crash between each.

**Comment by CallShaul** [comment]
Update: drivers crash happens during training as well, not only between folds.

![image](https://user-images.githubusercontent.com/52006780/103894208-42099300-50f7-11eb-8ec9-3e56ee5613a8.png)

**Comment by russellbrooks** [comment]
Potentially related – I've been trying to debug some odd behavior when using multiple GPUs in a groupwise ranking problem.

I am able to use CPU only or a single GPU successfully (v100), however for the exact same dataset and model parameters when using multiple GPUs (4 or 8 v100s) I immediately get this error on the first iteration: 

> CatBoostError: catboost/cuda/methods/pairwise_oblivious_trees/pairwise_scores_calcer.cpp:24: got invalid split (policy = BinaryFeatures, policyIdx = 0, deviceIdx = 0, split.Index = 4294967295, split.FeatureId = 4294967295, split.BinId = 4294967295, split.Score = inf), this may be caused by anomalies in your data (e.g. your target absolute value is too big) that cause numeric errors during training


Throwing in a "logging_level": "Debug" doesn't seem to output anything more specific either unfortunately. I've ensured that all values for the ranking relevance label are between 0-1. Also sometimes it seems to throw a CUDA OOM error, despite being able to fit onto a single GPU without issues.

That's all with:
Driver Version: 450.51.06
CUDA Version: 11.0

**Comment by CallShaul** [comment]
Update: crash still occurs with the latest Nvidia driver 461.09 and CUDA 11.2.

**Comment by CallShaul** [comment]
Update: RE-installed windows 10, still error occurs.

**Comment by CallShaul** [comment]
**Important update- a workaround may be found, yet issue still exists:**

using `import catboost` instead of 'from catboost import Pool, CatBoostClassifier'
**and not defining learning rate** (letting catboost define the learning rate by it's own)
seems to stop the driver from crashing.

When I'm defining the learning rate my self, (to a value about half of the value found by catboost previously) - the crash happens again.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for your effort!

In the screen-shot, the card is marked as having some problems (the exclamation mark).
Did you check what is that?

It may also be helpful to check the events related to the card in the Event Viewer.

Another option is to decrease the amount of the video RAM used by CatBoost -- you may search for gpu_ram_part here https://catboost.ai/docs/concepts/python-reference_parameters-list.html

**Comment by CallShaul** [comment]
Thank you @Evgueni-Petrov-aka-espetrov ,
I can't get more info regarding the GPU driver exclamation mark since I am working on the computer remotely,
and in 90% of the crashes I lose connection with the remote computer, and only reconnecting after restart.
it was a rare even being able to connect to it remotely and actually see the driver issue.

I've tried setting gpu_ram_part to 0.8, still getting crashes.
I've tried putting the first line of the Catboost calculation function as `import catboost` in order to try and 
re-import it, since I am suspecting it has something to do with the k-fold way of work,
I never had the issue when running one time calculation in a process and then closing it,
as far as I've noticed it only happens when performing Catboost calculation again and again using a loop in the same python process (k-folding the data), which is why I suspect a relation to issue #433

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Could you please ask your IT engineers to check the card? Exclamation mark typically means that the device is installed incorrectly.

If we had a small reproducer, we could try to reproduce/debug on our side.

**Comment by CallShaul** [comment]
Before Catboost calculation crashes the GPU drivers the device manager looks 100% like shown below,
I will try to run a siginificant few hours calculation using PyTorch on the GPUs, to check their status with a different package.
the IT managers claim the computer is ok, we even re-installed windows 10...

![image](https://user-images.githubusercontent.com/52006780/104731686-bf12b900-5744-11eb-9d9f-a0a99b29cf8e.png)

**Comment by CallShaul** [comment]
@Evgueni-Petrov-aka-espetrov got you some windows logs from the Event Viewer as you asked for:

![image](https://user-images.githubusercontent.com/52006780/104765813-2d21a500-5772-11eb-9c16-ca20e7c68aee.png)

![image](https://user-images.githubusercontent.com/52006780/104765858-43c7fc00-5772-11eb-99b1-f08f34b3a5c4.png)

![image](https://user-images.githubusercontent.com/52006780/104765906-58a48f80-5772-11eb-88c6-d31cda2d2cd7.png)

![image](https://user-images.githubusercontent.com/52006780/104765945-665a1500-5772-11eb-823e-44630d2f8d2a.png)

**Comment by CallShaul** [comment]
Another GPU drivers crash **while performing first training**

![image](https://user-images.githubusercontent.com/52006780/104801375-182c2c80-57d9-11eb-863d-6d67e8a41c00.png)

**Comment by George713** [comment]
Hi @CallShaul,

did you find a solution?

Best,
George

**Comment by CallShaul** [comment]
> 
> 
> Hi @CallShaul,
> 
> did you find a solution?
> 
> Best,
> George

Apparently 2x3090 with i9-10900x in the same case create too much heat (obviously...) and that was the reason for all those weird crashes. The solution was creating costume fan speed curve using MSI afterburner and increasing all of systems fans including GPU's fans to the maximum once working starts, and opening PC case where possible. since then everything works like charm :)
