### ISSUE TITLE
please explain error: target_converter.cpp:228: Unknown class label

### ISSUE THREAD

**Issue by gitpickle** [catboost/catboost#1531]
Problem: target_converter.cpp:228: Unknown class label
catboost version: 0.24.4
Operating System: Windows 10
CPU: Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
# GPU: n/a

Hi, I am calling the following and receiving error: **target_converter.cpp:228: Unknown class label**.

model.fit(
    X_train, y_train,
    cat_features=categorical_features_indices,
    eval_set=(X_validation, y_validation),
    logging_level='Debug',  # you can uncomment this for text output
    plot=True
);

y_train
7613      1
735       1
12380     0
11914     2
323       6
         ..
11964     1
5191     11
5390      1
860       1
7270      1
Name: LOS, Length: 9821, dtype: int64

X_train.dtypes
PROCEDURE_DESCRIPTION    object
PRIMARY_SURGEON          object
dtype: object

y_train.dtypes
dtype('int64')

It cannot be the case that target label values in y are missing in X because the target column in Y does not exist in X.  I verified that the row numbers match:

X_train.shape
(9821, 2)
y_train.shape
y_train.shape
(9821,)

also:

categorical_features_indices
array([0, 1], dtype=int64)

I am confused as to how this is possible and am not sure what to do about it.

Thanks for your help,
Mike

**Comment by gitpickle** [comment]
Here is the full stack trace:

---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-77-d9459909be3b> in <module>
----> 1 model.fit(
      2     X_train, y_train,
      3     cat_features=categorical_features_indices,
      4     eval_set=(X_validation, y_validation),
      5     logging_level='Debug',  # you can uncomment this for text output

C:\Apps\Anaconda3\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4300             self._check_is_classification_objective(params['loss_function'])
   4301 
-> 4302         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4303                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
   4304                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)

C:\Apps\Anaconda3\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1804 
   1805         with log_fixup(), plot_wrapper(plot, [_get_train_dir(self.get_params())]):
-> 1806             self._train(
   1807                 train_pool,
   1808                 train_params["eval_sets"],

C:\Apps\Anaconda3\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1256 
   1257     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1258         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1259         self._set_trained_model_attributes()
   1260 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/private/libs/target/target_converter.cpp:228: Unknown class label: "57"

**Comment by LyzhinIvan** [comment]
This error means that your `y_validation` contains labels that are not presented in `y_train`.
