### ISSUE TITLE
[Question] Categorical encoding for ranking tasks

### ISSUE THREAD

**Issue by lspataro26** [catboost/catboost#1536]
Hi everybody,
I am not sure if this is the right place to ask this, please let me know if not.
I was wondering how the categorical encoding works when we are training using a ranking objective, for example YetiRank.
Is there any difference in encoding based on the ranking objective function?

Thank you :)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi @lspataro26 :)

Cat features encoding does not depend on the objective -- you may check https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html

You may also join https://t.me/catboost_en and ask questions there.

**Comment by lspataro26** [comment]
> Hi @lspataro26 :)
> 
> Cat features encoding does not depend on the objective -- you may check https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html
> 
> You may also join https://t.me/catboost_en and ask questions there.

Hi, 
thank you so much for your answer.

The link you shared talks about several steps.
Step 2 mention that the method is determined by the loss function but the ranking example is not mentioned.
I guess the rank is treated as Multiclassification?

Once the integer labels are created I guess the method involves creating the buckets between query groups (for example counting elements at position 2 across groups with label 2)?
If this is the case, the encoding is not going to reflect the target that for ranking is an inter group target (for instance element_2 is better than element_1 that in turn is better than element_3).

Am I missing something?
Thanks :)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
In ranking, labels are processed same way as in regression.
CatBoost uses groups to calculate loss and its derivatives.
For details, you may refer to https://catboost.ai/docs/concepts/loss-functions-ranking.html

**Comment by Liortabori** [comment]
> Hi @lspataro26 :)
> 
> Cat features encoding does not depend on the objective -- you may check https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html
> 
> You may also join https://t.me/catboost_en and ask questions there.

Hey Espetrov!
I looked into the documentation and didnt find an answer. Can you please help me understand if the calculation of CTR takes into account the row weight that was given to the Pool?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
I am back! Please excuse my being silent.
No, CTRs are not weighted.
