### ISSUE TITLE
cannot build without AVX

### ISSUE THREAD

**Issue by ilgrad** [catboost/catboost#1539]
Problem: llegal instruction (core dumped)
catboost version: 0.24.4
Operating System: fedora 33
CPU:  AMD Phenom(tm) II X6 1100T  instructions: MMX(+), 3DNOW!(+), SSE(1, 2, 3, 4A), AMD-V, x86-64

**Comment by kizill** [comment]
Can you try building with hacks from https://github.com/catboost/catboost/pull/1030 and https://github.com/catboost/catboost/issues/1009
Please, try building like this `ya make -r -DNOSSE  -DDISABLE_INSTRUCTION_SETS=yes` ?

**Comment by ilgrad** [comment]
../../../ya make -r -DNOSSE -DDISABLE_INSTRUCTION_SETS=yes
Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/525772289a03dbadc47d2b47528b627a [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/479623/1940089615 [..............................................................................................] OK
Illegal instruction (core dumped)

**Comment by kizill** [comment]
You need temporary access to some modern CPU to build catboost for your osn cpu, sorry for that !

**Comment by ilgrad** [comment]
ok), thx
