### ISSUE TITLE
Correct parsing of dataset lines with ""

### ISSUE THREAD

**Issue by mathankumart** [catboost/catboost#154]
train_pool = Pool(TRAIN_FILE, column_description=CD_FILE,delimiter=',') throwing following error:

_catboost.CatboostError: catboost/libs/data/load_data.cpp:365: Factor world" in column 4 and row 1 is declared as numeric and cannot be parsed as float. Try correcting column description file.

**Column Description file:**
0       Target
1       Num
2       Categ

**Sample Data:**
0,1,"Madurai,India"

**Comment by annaveronika** [comment]
We split data by ',' symbol. If you want better splitting, please consider using python dataframe, or use other delimiter.

**Comment by annaveronika** [comment]
Actually that's a good idea for contributing to catboost!

**Comment by annaveronika** [comment]
This is fixed now in code and will be out on pypi in the next release.
