### ISSUE TITLE
Compile from source on Ubuntu 20.04 with CUDA 11

### ISSUE THREAD

**Issue by GFuhr** [catboost/catboost#1540]
Problem: cannot install from sources
catboost version: 0.24.4
Operating System: Ubuntu 20.04

Python version 3.8
Cuda V11.0.194
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

I tried to build python package from source using the following command : 
../../../ya make -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/softs/python3/python3-config  -DHAVE_CUDA=yes -DCUDA_ROOT=/softs/libs/cuda_11.0 -o/opt/softs/libs/catboost/0_24_4 -DUSE_ARCADIA_CUDA_HOST_COMPILER=no

it leads to the following error : 
------- PREPARE $(CUDA_HOST_TOOLCHAIN-sbr:971092418)
ERROR: '971092418'

Guillaume

**Comment by kizill** [comment]
Can you try passing -DCUDA_HOST_COMPILER=path/to/gcc ?

**Comment by GFuhr** [comment]
I did it but I still have issues (new ones)

First, -gencode arch=compute_30,code=compute_30 is not accepted anymore my cuda so I commented the line in catboost/cuda/cuda_lib/default_nvcc_flags.make.inc

Then when I tried again I have now these errors : 
gcc: error: unrecognized command line option '-Xclang'
gcc: error: unrecognized command line option '-fdebug-compilation-dir'
gcc: error: unrecognized command line option '-Xclang'

Is clang mandatory to compile catboost?

Regards
Guillaume

**Comment by kizill** [comment]
Sorry, currently we don't support gcc for catboost compilation, our build system is bound to clang compiler family.

**Comment by kizill** [comment]
Sorry, i've found that clang also don't work, created internal bug for our devtools team.

**Comment by mikematusiak** [comment]
Yeah, any news here? :)

**Comment by kizill** [comment]
By now, CatBoost fully supports cuda 11.X and all artifacts since 0.26 release are built for cuda 11.
