### ISSUE TITLE
YetiRankPairwise bug with binary features and multiple GPUs

### ISSUE THREAD

**Issue by russellbrooks** [catboost/catboost#1552]
Problem: Using YetiRankPairwise on multiple GPUs breaks if any binary features are present.
catboost version: 0.24.4
Operating System: Ubuntu 18.04.4
CPU: 8-64
GPU: 2-16 (Tesla V100s)
Driver Version: 450.51.06
CUDA Version: 11.0

I noticed the odd behavior in a groupwise ranking model when using multiple GPUs. I was able to use CPU only or a single GPU successfully, however for the exact same dataset and model parameters when using multiple GPUs, the following error occurs on the first iteration: 

Example error message:
> CatBoostError: catboost/cuda/methods/pairwise_oblivious_trees/pairwise_scores_calcer.cpp:24: got invalid split (policy = BinaryFeatures, policyIdx = 0, deviceIdx = 0, split.Index = 4294967295, split.FeatureId = 4294967295, split.BinId = 4294967295, split.Score = inf), this may be caused by anomalies in your data (e.g. your target absolute value is too big) that cause numeric errors during training

The ranking relevance labels were ensured to be between 0-1, and using ` "logging_level": "Debug"` raises the same error without additional context. After removing all binary features, YetiRankPairwise works in the multi-GPU setting.

In the catboost Telegram channel, Евгений Петров mentioned that there's an interally-tracked bug for this already and I'm opening this public github issue to go alongside that. Also mentioned as an intermediate workaround:
> As a workaround, you may combine binary features into one float feature, e.g. `b0, b1, b2 -> b0 + 2*b1 + 4*b2`.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Fixed in this commit https://github.com/catboost/catboost/commit/e344fdd7c6907b24fdd751326254e812b8ea75a6
