### ISSUE TITLE
Segmentation fault when predicting on pool with baseline

### ISSUE THREAD

**Issue by david-cortes** [catboost/catboost#1553]
Problem: Segmentation fault
catboost version: 0.24.4
Operating System: debian bullseye
CPU: ryzen 7 2700

The following example will oftentimes throw a segmentation fault:
```python
import numpy as np
import catboost

np.random.seed(123)
X = np.arange(10).reshape((5,2)).astype(np.float64)
y = np.random.randint(3, size=5)
pool = catboost.Pool(X, label=y)
model = catboost.CatBoostClassifier(logging_level="Silent").fit(pool)
baseline = np.random.normal(size=(5,2))
pool2 = catboost.Pool(X, baseline=baseline)
model.predict(pool2, prediction_type='Probability')
```
```
Allocator error: virtual memory is over fragmented
Aborted
```

Valgrind suggests two important things:
* Conditional jump or move depends on uninitialised value(s)
* Address 0x0 is not stack'd, malloc'd or (recently) free'd --> the code is likely dereferencing a null pointer somewhere

The function at fault seems to be this:
```
ApplyModelMulti(TFullModel const&, NCB::TDataProviderTemplate<NCB::TObjectsDataProvider> const&, bool, EPredictionType, int, int, int)
```

**Comment by kizill** [comment]
In that example catboost sees 3 different classes and switches to multiclass loss. Then, you are passing 2-dimensional baseline for 3-dimensional model.
Thank you, fixed in master!

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!
