### ISSUE TITLE
Python CatBoostRegressor does not predict with small inputs

### ISSUE THREAD

**Issue by avidale** [catboost/catboost#156]
When applying the fitted model to matrix 1*1, it gives an error:
`CatboostError: Input data has invalid shape or empty: (1, 1). Must be 2 dimensional`

The problem is that `catboost.core.Pool._check_data_empty` checks for input size are too strict. **This method should be rewritten**.
As a result, the following code throws an error in the last line:
```
import catboost
import numpy as np
x_train3 = np.array([[1,2,3,], [2,3,4], [3,4,5]])
x_train1 = np.array([[1], [2], [3]])
y_train = np.array([1,2,3])
x_test3_2 = np.array([[4,5,6], [5,6,7]])
x_test3_1 = np.array([[4,5,6,]])
x_test1_2 = np.array([[4], [5]])
x_test1_1 = np.array([[4]])
model3 = catboost.CatBoostRegressor().fit(x_train3, y_train)
model1 = catboost.CatBoostRegressor().fit(x_train1, y_train)
print(model3.predict(x_test3_2)) # OK
print(model3.predict(x_test3_1)) # OK
print(model1.predict(x_test1_2)) # OK
print(model1.predict(x_test1_1)) # Throws an error!
```

It is already mentioned [on stackowerflow](https://stackoverflow.com/questions/47039915/catboost-understanding-conversion-of-categorical-values).

I propose to replace the check in the line 194 of `core.py`
`if not len(data_shape) == 2 or not sum(data_shape) > 2:`
by 
`if not len(data_shape) == 2 or not min(data_shape) > 0:`

**Comment by annaveronika** [comment]
would you make a pull request with your change?

**Comment by annaveronika** [comment]
Thank you for the fix!
