### ISSUE TITLE
CatBoost crashes Kaggle kernel without message

### ISSUE THREAD

**Issue by minhlong94** [catboost/catboost#1564]
Problem: CatBoost crashes Kaggle kernel without message
catboost version: 0.24.4
Operating System: Kaggle kernel

Here is my Kaggle notebook: https://www.kaggle.com/aeryss/predict-future-sales-training-inference
When tuning hyperparam with hyperopt, the kernel automatically crashes without giving any message. I closely monitor the hardware resource, and there is no sudden increase in RAM or GPU Memory. Moreover, sometime it crashes at the very first iteration, sometime it crashes after 3-4 iterations.

Although there are 65 columns in the DF, but before that I tried with only ~30 columns, the kernel still crashed exactly like that.

**Comment by kizill** [comment]
Fixed in master - from now on CatBoost will throw exceptions instead of calling `abort()`
