### ISSUE TITLE
Export model to json/byte_str

### ISSUE THREAD

**Issue by arainboldt** [catboost/catboost#1567]
Problem: Exporting CatBoost model to memory for storing in a Postgres db

Hi,

I'm trying to build a pipeline for storing and loading models in production where there aren't read/write permission to store a model to disk, but rather only to a postgres db. How can I export a fitted catboost model to a json/byte_str in memory for storing and loading directly to the db?

Thanks,

Andrew

**Comment by kizill** [comment]
We have undocumented function ```_serialize_model``` that returnes ```bytes``` object with model, that you should treat like a binary blob.
To restore from ```bytes``` we have a method ```.load(blob=your_model_bytes)```.

**Comment by chelgd** [comment]
@kizill does _serialize_model use cbm like serialization?

**Comment by andrey-khropov** [comment]
> [@kizill](https://github.com/kizill) does _serialize_model use cbm like serialization?

Yes
