### ISSUE TITLE
Error and Kernel Crash for Shap Calculation

### ISSUE THREAD

**Issue by ThomasWolf0701** [catboost/catboost#1568]
Problem: Error or Kernel Crash for SHAP calculation
catboost version: 0.24.4
Operating System: Windows 10
CPU:  Intel Core i7

I attached both the featureMatrix and the model using pickles:
[errorReproduceObjects.zip](https://github.com/catboost/catboost/files/5921893/errorReproduceObjects.zip)

The model uses MutliRMSE and 
bestModel.predict(transformedMatrix) works fine

bestModel.predict(transformedMatrix)
Out[44]: 
array([[-4.84283473, -4.66173853],
       [-4.03272354, -3.80896785],
       [-2.61701992, -2.22272565],
       ...,
       [-4.5486192 , -4.31635738],
       [-2.81394494, -2.38203556],
       [-4.02415018, -3.65515251]])

When running the following code I get a Kernel crash when using multiple cores and an error when
using only one core:

bestModelShap =  bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

Traceback (most recent call last):

  File "<ipython-input-41-a812cb3ad5db>", line 1, in <module>
    bestModelShap =  bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 2555, in get_feature_importance
    fstr, feature_names = self._calc_fstr(type, data, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices,

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 1329, in _calc_fstr
    return self._object._calc_fstr(type.name, pool, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices, shap_calc_type)

  File "_catboost.pyx", line 4408, in _catboost._CatBoost._calc_fstr

  File "_catboost.pyx", line 4437, in _catboost._CatBoost._calc_fstr

CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/model/scale_and_bias.h:63: Internal CatBoost Error (contact developers for assistance): Asked one-dimensional bias, has 2.Non single-dimension approxes are not supported

When I use the SHAP package instead of the catboost internal function  I get a Kernel crash.

 explainer = shap.TreeExplainer(bestModel["m"]) 
      bestModelShap = explainer.shap_values( transformedMatrix)
     
Kernel died, restarting

Restarting kernel... 

[SpyderKernelApp] WARNING | No such comm: f2b6ca35666511eb9cf99cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: 382dbce3666711eb95589cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: ee4c9163666811ebb4899cb6d01cd292

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!
