### ISSUE TITLE
Surprising behavior of Catboost for large l2_leaf_reg

### ISSUE THREAD

**Issue by shifwang** [catboost/catboost#1569]
Problem:
When I use catboost on my data, I encounter a surprising issue. It can be reproduced using this following toy case, when l2_leaf_reg is large, catboost splits a node where all the data points have the same response. Could you please shed some light on why this can happen?

```
from catboost import CatBoostRegressor
import numpy as np
X = np.arange(0, 100)[:, None]
y = np.zeros((100,))
y[5] = 1  # y = 1 only when X = 5.
cat = CatBoostRegressor(iterations=1, depth=2, learning_rate=1, bootstrap_type="No", random_strength=0, 
                        l2_leaf_reg=1)  # small l2 reg
cat.fit(X, y)
print(cat.get_borders()) # {0: [4.5, 5.5]} # two splits isolate X=5, which makes sense.
cat = CatBoostRegressor(iterations=1, depth=2, learning_rate=1, bootstrap_type="No", random_strength=0, 
                        l2_leaf_reg=1e5)  # large l2 reg 
cat.fit(X, y)
print(cat.get_borders()) # {0: [5.5, 52.5]} # the second split is at X = 52.5 but all y with X > 5.5 is zero.
```

catboost version: 0.24.4
Operating System: Linux

**Comment by ek-ak** [comment]
Thanks for your question.
1. As known large l2 regularization coefficient leads to model under-fitting. You can check the leaf values in your example - they are closed to zero (`cat.get_leaf_values()`). 
2. By default CatBoost uses oblivious tree structure - it means that on each level docs are split with the same condition. ([documentation](https://catboost.ai/docs/concepts/parameter-tuning.html#tree-growing-policy) ) This condition could be trivial for some branches of decision tree as in your example, but never trivial for all branches. You can use `cat.plot_tree(0) `function to see tree structure).

**Comment by shifwang** [comment]
Thank you for your answer.
