### ISSUE TITLE
Problem with automatic one-hot encoding

### ISSUE THREAD

**Issue by dickreuter** [catboost/catboost#1572]
Problem:
I have an np array that I pass into catboost to train, and one of the columns contains categories.

I was expecting that catboost would one-hot encode it automatically, but instead I get:
`Bad alue for num_feature[non-default_doc_idx=0, feature_idx=6]="category 1": cannot vonvert 'category 1' to float`

Is there any way I can avoid this error and have catboost handling the one-hot encoding, or do I have to do it myself?

**Comment by andrey-khropov** [comment]
1. CatBoost assumes that all features' columns contain numeric features by default, you have to specify which features are categorical explicitly by providing `cat_features` parameter with either features' indices or features' names (this parameter can be passed to either `Pool` constructor or `CatBoostClassifier.fit` or `CatBoostRegressor.fit` function). See examples: https://catboost.ai/docs/concepts/python-usages-examples.html.
2. CatBoost processes categorical features as either one-hot encoded (internally, no preprocessing required) or creates derived numeric features based on some statistics (these are called Ctrs), see https://catboost.ai/docs/features/categorical-features.html.

**Comment by andrey-khropov** [comment]
Automatic detection of categorical features will be implemented in #1386.
