### ISSUE TITLE
MultiRMSE objective and SHAP values

### ISSUE THREAD

**Issue by andrei-advisa** [catboost/catboost#1578]
Hi! I'm trying to compute SHAP values with MultiRMSE objective with 3-dimensional target. 

* Problem: After running this statement:
`
shap_values = model.get_feature_importance(Pool(X,y),type=EFstrType.ShapValues,verbose=200,thread_count=6)
`
I get uncaught exception in:
`    what() -> "catboost/libs/model/scale_and_bias.h:63: Internal CatBoost Error (contact developers for assistance): Asked one-dimensional bias, has 3.Non single-dimension approxes are not supported"
    type -> TCatBoostException
` 
* catboost version: 0.24.4
* Operating System: Linux amd64
* CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
* GPU: not used

Any recommendations how can I fix that?

**Comment by ThomasWolf0701** [comment]
https://github.com/catboost/catboost/commit/3e93ca0aa1c50dd4cf3727ef56a7b0db3e6c57a0
