### ISSUE TITLE
calc_feature_statistics not plotting

### ISSUE THREAD

**Issue by dickreuter** [catboost/catboost#1581]
When running the example script that is given on the catboost website (https://catboost.ai/docs/concepts/python-reference_catboost_calc_feature_statistics.html), no plot appears at the end, but only empty space:

```
from catboost import CatBoost
import numpy as np

train_data = np.random.rand(200, 10)
label_values = np.random.rand(200)

model = CatBoost()
model.fit(train_data, label_values)

res = model.calc_feature_statistics(train_data,
                                    label_values,
                                    feature=2,
                                    plot=True)
```

**Comment by kizill** [comment]
Hello!
If you are running in jupyter lab, using visual studio code or jupyter notebook hosted in Google Colaboratory - please wait for fixing issue #262 , ETA is May 2021.
If you are hosting you own jupyter notebook - please follow instructions from this documentation page https://catboost.ai/docs/installation/python-installation-additional-data-visualization-packages.html
Thank you!
