### ISSUE TITLE
setup.py: function build_with_make references a nonexistent file

### ISSUE THREAD

**Issue by foreignmeloman** [catboost/catboost#1589]
This line references a nonexistent file:

https://github.com/catboost/catboost/blob/ba6b9343231a055b75056a055cc44a8747792028/catboost/python-package/setup.py#L225

My guess is that `make/app.CLANG11-LINUX-X86_64.makefile` should be it. Probably the maintainer forgot to update `setup.py` after generating the new makefile.

Following lines should probably also be updated since the new makefile requires clang 11:
https://github.com/catboost/catboost/blob/ba6b9343231a055b75056a055cc44a8747792028/catboost/python-package/setup.py#L228
https://github.com/catboost/catboost/blob/ba6b9343231a055b75056a055cc44a8747792028/catboost/python-package/setup.py#L229

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for investigation!
