### ISSUE TITLE
Which CUDA version is compatible with catboost-0.24.4?

### ISSUE THREAD

**Issue by hashfury42** [catboost/catboost#1591]
Problem: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version

catboost version: catboost-0.24.4
Operating System: win10 x64
CPU:
GPU: GTX 1070

GPU doesn't work after I updated the catboost lib, so can anyone tell me which cuda shoud I install ?

**Comment by LyzhinIvan** [comment]
Hi, @hashfury42!

From the [documentation](https://catboost.ai/docs/concepts/python-installation.html): 

> Training on GPU requires NVIDIA Driver of version 418.xx or higher.
