### ISSUE TITLE
QuickStart fails on Windows, Python 3.5

### ISSUE THREAD

**Issue by Arturus** [catboost/catboost#16]
Succesful installation:
C:\Users\asuil_000>pip install catboost
Collecting catboost
  Downloading catboost-0.1.1.2-py3-none-win_amd64.whl (2.3MB)
    100% |################################| 2.3MB 361kB/s
Requirement already satisfied: numpy in c:\app\anaconda3\lib\site-packages (from catboost)
Requirement already satisfied: pandas in c:\app\anaconda3\lib\site-packages (from catboost)
Requirement already satisfied: six in c:\app\anaconda3\lib\site-packages (from catboost)
Requirement already satisfied: python-dateutil>=2 in c:\app\anaconda3\lib\site-packages (from pandas->catboost)
Requirement already satisfied: pytz>=2011k in c:\app\anaconda3\lib\site-packages (from pandas->catboost)
Installing collected packages: catboost
Successfully installed catboost-0.1.1.2

Error after runing first example on QuickStart page:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\app\Anaconda3\lib\site-packages\catboost\core.py in <module>()
     17 try:
---> 18     from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     19 except ImportError:

ImportError: No module named '_catboost'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-e29c96272905> in <module>()
      1 import numpy as np
----> 2 from catboost import CatBoostClassifier
      3 # initialize data
      4 train_data = np.random.randint(0, 100, size=(100, 10))
      5 train_label = np.random.randint(0, 2, size=(100))

C:\app\Anaconda3\lib\site-packages\catboost\__init__.py in <module>()
----> 1 from .core import Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv  # noqa
      2 try:
      3     from .widget import CatboostIpythonWidget  # noqa
      4 except:
      5     pass

C:\app\Anaconda3\lib\site-packages\catboost\core.py in <module>()
     18     from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     19 except ImportError:
---> 20     from ._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     21 
     22 from contextlib import contextmanager

ImportError: DLL load failed: The specified module could not be found.

**Comment by Donskov7** [comment]
This is because python 3.5 is specific, we load new version for python3.5 in pypi, try reinstall catboost:
`pip install catboost --no-cache-dir`

*if it doesn't help try to make wheel by yourself:
https://tech.yandex.com/catboost/doc/dg/concepts/python-installation-docpage/
1. Clone the repository:
`git clone https://github.com/catboost/catboost.git`
2. go to catboost/catboost/python-package
3. run `python mk_wheel.py`
Here at the result you get some `.whl` file 
4. run `pip install catboost-...whl`

**Comment by Donskov7** [comment]
Seems it has been fixed, please try to reinstall CatBoost.

**Comment by Arturus** [comment]
catboost-0.1.1.5 works perfectly, thanks!
