### ISSUE TITLE
Callback for trial prunning in Optuna

### ISSUE THREAD

**Issue by pplonski** [catboost/catboost#1604]
The Optuna is a hyperparameters optimization framework. It has the option to stop unpromising trials. It has integration for Xgboost and LightGBM for pruning unpromising runs. Is there an option to have a callback in CatBoost to check the learning progress during the training?

I set the issue in the Optuna repository: https://github.com/optuna/optuna/issues/2464

Tuning with pruning gives much better results because much more trials can be checked.

**Comment by andrey-khropov** [comment]
We're working on the callback issue #1304. The results are expected to be available in about 2 months.
