### ISSUE TITLE
Metric GPU warning overlays graph

### ISSUE THREAD

**Issue by Theghios** [catboost/catboost#1608]
Problem: On Jupyter notebook when using GPU a warning overlays the graph which makes impossible to check progression 
Warning `Metric PRAUC is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time`

Please see image for code and effect

catboost version: catboost-0.24.4-cp38-none-manylinux1_x86_64.whl
Operating System: Linux
GPU: GTX1080
![image](https://user-images.githubusercontent.com/15112923/110978023-c6c49780-835a-11eb-80e9-c50ae0facb6b.png)

**Comment by kizill** [comment]
This look like either browser render engine glitch or jupyter notebook bug, i tried reproducing it, bug doesn't appear on latest Chromium & jupyter notebook. Please, can you try upgrading your browser (or trying alternative one)?

**Comment by kizill** [comment]
Closing as irreproducible, please feel free to reopen if suggested solutions won't work.
