### ISSUE TITLE
Catboost dumping a file named Core

### ISSUE THREAD

**Issue by nirupamkar** [catboost/catboost#1611]
While doing training Catboost is dumping a file named "core" in the same directory which has got size line 60-70GB. Using parameter like "train_dir" did not resolve the issue. Could you please help me to understand what config I must use to make sure this file is not dumped or gets dumped in a predefined location?

version - 0.24.4

**Comment by kizill** [comment]
Hello! This behaviour means catboost actually crashes at some point. Could you try enabling debug logs by setting ```logging_level='Debug'``` in python or ```--logging-level Debug``` for CLI

**Comment by kizill** [comment]
Closing as we can't reproduce with provided information.
