### ISSUE TITLE
Unable to pip install catboost==0.16.0

### ISSUE THREAD

**Issue by jvschoen** [catboost/catboost#1613]
Problem: running `pip install catboost==0.16.0` results in 
```
ERROR: Could not find a version that satisfies the requirement catboost==0.16.0
ERROR: No matching distribution found for catboost==0.16.0
```
catboost version: `0.16.0`
Operating System: 
```NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
CPU: N/A
# GPU: N/A

**Comment by andrey-khropov** [comment]
It's because Ubuntu 20.04.1 has Python 3.8 by default and CatBoost started to support python 3.8 only since release 0.20.
So, if you really need such an outdated version of CatBoost use earlier python version.

**Comment by jvschoen** [comment]
Great! Thanks.

**Comment by jvschoen** [comment]
@andrey-khropov It looks like I still get the error when trying `catboost==0.20`:
```ERROR: Could not find a version that satisfies the requirement catboost==0.20 (from versions: 0.1.1.2, 0.24.4, 0.25, 0.25.1) ERROR: No matching distribution found for catboost==0.20```

**Comment by jvschoen** [comment]
Looks like my docker instance is running python 3.9, so that's likely the problem.
