### ISSUE TITLE
GPU multiclass training ignores one of the classes

### ISSUE THREAD

**Issue by kazeevn** [catboost/catboost#1615]
Problem: with `task_type=GPU` and five-class classification problem the model ignores the last class
catboost version: 0.24.4, installed from conda
Operating System: Ubuntu 20.04.1 LTS + conda
CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
GPU: 4xTesla K80,  Driver Version: 450.102.04   CUDA Version: 11.0

See the attached example with the code and environment: [catboost_GPU_fail.zip](https://github.com/catboost/catboost/files/6175105/catboost_GPU_fail.zip)

The output I get is:
```
0.24.4
Training with task_type=CPU
{'AUC:class=0': [0.9416125, 0.994775], 'AUC:class=1': [0.8686875000000001, 0.97825], 'AUC:class=2': [0.8569, 0.988025], 'AUC:class=3': [0.8353125, 0.98045], 'AUC:class=4': [0.9323875, 0.99485]}
[[0.7777114  0.19982619 0.01117459 0.00558069 0.00570713]]
Training with task_type=GPU
Warning: less than 75% gpu memory available for training. Free: 7962.75 Total: 11441.1875
Warning: less than 75% gpu memory available for training. Free: 8093.75 Total: 11441.1875
Warning: less than 75% gpu memory available for training. Free: 1525.5 Total: 11441.1875
Warning: less than 75% gpu memory available for training. Free: 8441.75 Total: 11441.1875
{'AUC:class=0': [0.968, 0.9937], 'AUC:class=1': [0.913475, 0.980125], 'AUC:class=2': [0.7880875, 0.982125], 'AUC:class=3': [0.6688375, 0.8963], 'AUC:class=4': [0.5, 0.5]}
```
When training on CPU, 1-vs-all AUC for class 4 is around 0.9, when training on GPU, 0.5.

**Comment by kizill** [comment]
Fixed in 0.25.1 release, now we use fair probability calculation with softmax over raw predictions.
