### ISSUE TITLE
catboost tutorial for feature selection

### ISSUE THREAD

**Issue by m1ckyro5a** [catboost/catboost#1617]
There is no tutorial for new feature selection catbost algorighm.
I will work on it

**Comment by LyzhinIvan** [comment]
Here there is such tutorial: https://github.com/catboost/catboost/blob/master/catboost/tutorials/feature_selection/select_features_tutorial.ipynb

**Comment by comorado** [comment]
Hello @LyzhinIvan I have questions about the feature selection implementation. What model is used for calculation of the loss function and what model is used for calculation of the Shapley values? 
I've obtained the following plot of loss function vs number of the the features removed. In my understanding each red box is a full model build, I've specified 12 iteration (models). 
![image](https://user-images.githubusercontent.com/3743980/117048848-49693380-acc8-11eb-813a-5803719ae010.png)
Is it true that loss function is calculated on the intermediate models which might include features which have been removed? Between iterations: Are Shapley values are calculated on the smaller models, e.g. models used to calculate shapley values do not include features removed?

**Comment by LyzhinIvan** [comment]
Hi, @comorado!

You understood correctly - each red box is a full model build without features removed so far. Shap Values are calculated using model from last red box. The only difference is that we use subset of data for shap calculation.
