### ISSUE TITLE
Is catboost portable between R and python?

### ISSUE THREAD

**Issue by flippercy** [catboost/catboost#1618]
Is catboost portable between R and python like xgboost and lightGBM? 

Thank you.

**Comment by andrey-khropov** [comment]
What do you mean by that? That models trained by CatBoost python can be loaded in R and vice versa? Generally, that's true - the model format is the same.

CatBoost also supports saving and loading models in the variety of well-known portable model formats like CoreML, ONNX, PMML, you can even apply models trained using other packages this way: https://github.com/catboost/tutorials/blob/master/apply_model/fast_light_gbm_applier.ipynb

**Comment by flippercy** [comment]
Yes that's what I mean. Assume I have a catboost model built in Python, how can I load it in R, please?

Appreciate your help.

**Comment by andrey-khropov** [comment]
Save it to the file using python package's [save_model method](https://catboost.ai/docs/concepts/python-reference_catboost_save_model.html)
Load that file in R using [load_model method](https://catboost.ai/docs/concepts/r-reference_catboost-load_model.html)
