### ISSUE TITLE
INTEGER() can only be applied to a 'integer', not a 'NULL'

### ISSUE THREAD

**Issue by inoddy** [catboost/catboost#1620]
Problem:INTEGER() can only be applied to a 'integer', not a 'NULL'
catboost version:25.0 for R4.0.2
Operating System:Windows 8.1, Ubuntu 20.4
CPU:Intel
# GPU:NVIDIA

I get in both Windows and Ubuntu R

Error in catboost.from_matrix(as.matrix(preprocessed), label, cat_features,  : 
  INTEGER() can only be applied to a 'integer', not a 'NULL'

when I execute the demo code

library(catboost)

train_path = system.file("extdata", 
                         "adult_train.1000", 
                         package="catboost")
test_path = system.file("extdata", 
                        "adult_test.1000", 
                        package="catboost")

column_description_vector = rep('numeric', 15)
cat_features <- c(3, 5, 7, 8, 9, 10, 11, 15)
for (i in cat_features)
  column_description_vector[i] <- 'factor'

train <- read.table(train_path, 
                    head = F, 
                    sep = "\t", 
                    colClasses = column_description_vector, 
                    na.strings='NAN')
test <- read.table(test_path, 
                   head = F, 
                   sep = "\t", 
                   colClasses = column_description_vector, 
                   na.strings='NAN')
target <- c(1)
train_pool <- catboost.load_pool(data=train[,-target], 
                                 label = train[,target])

**Comment by OmarVivas** [comment]
I'm a catboost fans, I wait a lot of days to install the new version, but it dosen't work again :(.

I get the same error  when I execute **pool <- catboost.load_pool(data_matrix[, -target], label = data_matrix[, target])**

**Error in catboost.from_matrix(data, label, cat_features, pairs, weight,  : 
  INTEGER() can only be applied to a 'integer', not a 'NULL'**

Please fix it, I'm looking forward to use catboost again

**Comment by kizill** [comment]
We released 0.25.1 with fix to both issues, please check again (and report if new bugs appear 🤗 )
