### ISSUE TITLE
Where the _init_cat_features function is defined?

### ISSUE THREAD

**Issue by h-amirkhani** [catboost/catboost#163]
In the line 325 of [the core.py file](https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/core.py), the _init_cat_features function is called, but I cannot find its definition in the code. Where can I find it?

**Comment by nikitxskv** [comment]
@h-amirkhani Hello!
You can find it [here](https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L439).
