### ISSUE TITLE
scala 2.11 dependency

### ISSUE THREAD

**Issue by yair4Data** [catboost/catboost#1632]
Problem: the 2.11.11 scala jars dependency (like scala-library , scala-reflect) has vulnerability issues as discussed here:
[https://www.scala-lang.org/news/security-update-nov17.html](url)

please upgrade to 2.11.12 onwards.

catboost version: 0.25-rc3
Operating System: linux

**Comment by andrey-khropov** [comment]
Released in 0.26.
