### ISSUE TITLE
Whether to support compilation on ARM server

### ISSUE THREAD

**Issue by huangyc-11** [catboost/catboost#1635]
Problem: Can the current catboost version be compiled on an arm server, centos or ubuntu system？

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Our makefiles from catboost/make do not support arm.
You may try to adjust these files to work for arm, and then fix a few problems like the one below. 
`candidate template ignored: deduced conflicting types for parameter 'T' ('long long' vs. 'unsigned int')`

**Comment by huangyc-11** [comment]
When can we support it? It's more important to me

**Comment by LyzhinIvan** [comment]
The main issue about ARM support is #1526. I close this issue as duplicate.
