### ISSUE TITLE
catboost-prediction jar of latest released version is missing in maven

### ISSUE THREAD

**Issue by yair4Data** [catboost/catboost#1637]
Problem: ai.catboost:catboost-common:0.25:jar is missing is official maven repository (mvnrepository.com)
latest version is 0.24
catboost version: 0.25.1

please prioritize that if possible, the 0.25.1 version have much better performance for our use case than 0.24.2 , and we rely on the java jar for serving.

**Comment by andrey-khropov** [comment]
catboost-prediction Maven artifact has been updated to 0.25.1

**Comment by jean-helsinki** [comment]
Most of the remaining libraries are also not updated to the current release, and there are a lot of fixes in it. 
https://mvnrepository.com/artifact/ai.catboost?sort=newest
