### ISSUE TITLE
Provision for ignoring input row if it is not parsable as per column description

### ISSUE THREAD

**Issue by mathankumart** [catboost/catboost#165]
In the training file(csv or tsv) in case of input line being not parsable, it will be a good to have option of ignoring that input just like error_bad_lines=False in pandas

**Comment by annaveronika** [comment]
In this case we will hide problems from user about which he might not know. We want to warn user about all possible problems, so we don't want to do such things.

**Comment by mathankumart** [comment]
How about providing the option for suppressing exception with warning ? Since it is a user opting for the option, it'll be a helpful feature especially when trying to load big data from various sources.
