### ISSUE TITLE
[catboost4j-spark] Error about "Auto-stop PValue" when using odType "Iter" and odWait

### ISSUE THREAD

**Issue by candalfigomoro** [catboost/catboost#1651]
Problem:
I've tried to enable early stopping with the earlyStoppingRounds parameter, but it didn't work (see issue #1649).
So I'm trying to enable it by setting the `odType` and `odWait` parameters.

However, when I set them, e.g.
```
classifier = catboost_spark.CatBoostClassifier(
    threadCount=1,
    iterations=100,
    odType=catboost_spark.EOverfittingDetectorType.Iter,
    odWait=10,
)
```

I get the following error
```
uncaught exception:
    address -> 0x107028410
    what() -> "catboost/private/libs/options/overfitting_detector_options.cpp:39: Auto-stop PValue is not a valid parameter for Iter overfitting detector."
    type -> TCatBoostException
```

But I didn't set any "Auto-stop PValue" (I don't use `odPval`) and I correctly set the `odWait` parameter.

catboost version: catboost-spark_2.4_2.12-0.25 (PySpark)

@andrey-khropov

**Comment by andrey-khropov** [comment]
Released in 0.26.
