### ISSUE TITLE
Catbooost C++ and python prediction gives different Result for Only Float Features

### ISSUE THREAD

**Issue by ashgen** [catboost/catboost#1652]
I am trying to replicate the the model trained on python to c++ prediction . However the results are not matching at all 

          0         1         2         3         4         5         6         7         8         9        10        11        12        13        14        15         t
0  1.112272 -0.345324  0.608056  0.641006 -0.712082  1.159150 -1.718945  0.417466 -0.400054  2.280909 -2.271720  0.225145  0.866331  1.387139 -1.032577  1.137695 -0.673914
1 -0.358203  0.300349 -1.113812 -0.321359  0.047448  1.244166  0.844847 -1.529851  2.224139  0.392710 -0.006417  0.472805 -0.749836  0.980675  0.154229 -1.186375 -0.251184
2 -0.227977  0.894644 -1.328406 -0.904516  0.054193 -0.862960 -1.062037  0.563226  0.786889 -0.304702 -0.069550 -0.718388 -1.704961  0.290527 -0.641019 -1.216624 -0.869005
3  0.155588  2.081781  0.038588 -0.562489 -0.105514  0.730646  0.319236  0.163729 -0.891123  0.985429  1.317130 -1.373329  0.505623 -0.899020 -0.159352 -0.467593  0.401559
4  0.973994 -0.501975 -0.242362  0.351762 -1.074005  1.339779  0.528939  0.102713  0.396976  0.905164 -0.111086  0.779234 -0.394803  1.223582  0.264499 -0.217201 -0.075871

The python result is in t column and 15 column is the C++ result . I am also attaching the C++ Code 

int main() {
  modelPrediction *cat_model = new catboostModel("/home/ashish/git/ogha-research/model_store/future_model_20200901_20200915.cbm");
  int N = 1000000;
  arma::uvec indices = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
  arma::vec test;
  arma::mat result(N,16);
  typedef std::chrono::high_resolution_clock Clock;
  for (int i = 0; i < N; i++) {
    arma::vec features(15, arma::fill::randn);
    auto begin = Clock::now();
    auto res=cat_model->predict(features);
    auto end = Clock::now();
    features[15]=res;
    result.row(i)=features;
    std::cout << std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin).count() << std::endl;
  }
  result.save("/home/ashish/res.csv",arma::csv_ascii);

  return 0;
}

Problem: C++ and python results are not matching 
catboost version:0.25.1
Operating System:Ubuntu 20.04
CPU: i7-8700k
# GPU:

**Comment by ek-ak** [comment]
Hello! Could you provide minimal reproduce example with model so we could reproduce this error?

**Comment by ashgen** [comment]
Hi Ek ,

I have been able to resolve the issue . 

Ashish
