### ISSUE TITLE
[catboost4j-spark] CatBoost Spark with Categorical Features

### ISSUE THREAD

**Issue by nvithayapale** [catboost/catboost#1653]
I cannot find the example of using the dataset with categorical features to train catboost in Spark.

For example, if the train data is

val trainData = Seq(
  Row(Vectors.dense(0.1, 0.2, 0.11), "1","0.12"),
  Row(Vectors.dense(0.97, 0.82, 0.33), "2", "0.22"),
  Row(Vectors.dense(0.13, 0.22, 0.23), "3", "0.34"),
  Row(Vectors.dense(0.8, 0.62, 0.0), "2", "0.1")
)

where the second column is categorical feature column. When we create Pool and fit the model using `regressor.fit(trainPool, Array[Pool](evalPool))`, it doesn't seem to incorporate categorical column.

Does the current version of catboost Spark support this?

**Comment by andrey-khropov** [comment]
Yes. CatBoost for Spark supports Categorical features with the standard Spark ML way - using DataFrame schema feature attributes.

You can see examples in the tests:

* For Scala. [Adding attributes to schema](https://github.com/catboost/catboost/blob/9248593d0ae198b11e9964addc912de9ecd36722/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/PoolTestHelpers.scala#L14-L41), examples is tests: [1](https://github.com/catboost/catboost/blob/9248593d0ae198b11e9964addc912de9ecd36722/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/CatBoostRegressorTest.scala#L587), [2](https://github.com/catboost/catboost/blob/9248593d0ae198b11e9964addc912de9ecd36722/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/CatBoostRegressorTest.scala#L663), [3](https://github.com/catboost/catboost/blob/9248593d0ae198b11e9964addc912de9ecd36722/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/CatBoostRegressorTest.scala#L929)
* For PySpark. [Adding attributes to schema](https://github.com/catboost/catboost/blob/9248593d0ae198b11e9964addc912de9ecd36722/catboost/spark/catboost4j-spark/core/src/test/python/pool_test_helpers.py#L19-L46).
