### ISSUE TITLE
ya make: NFS support

### ISSUE THREAD

**Issue by cdahnken** [catboost/catboost#166]
Compiling a fresh clone results in a bad file descriptor error
...
  File "devtools/ya/exts/filelock.py", line 102, in acquire
    return self._lock.acquire()
  File "devtools/ya/exts/filelock.py", line 45, in acquire
    self._locker(self._lock)
  File "devtools/ya/exts/filelock.py", line 36, in <lambda>
    self._locker = lambda lock: flock(lock, LOCK_EX)
IOError: [Errno 9] Bad file descriptor
...
when executing ./ya make -r. The crash happens in the externally downloaded ya-bin.

Operating system is 

 cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

Chris

**Comment by exprmntr** [comment]
Hello @cdahnken 

Can you try this workaround: remove `~/.ya` and re-run `./ya make -r`? Also full stacktrace and logs of `./ya -v make -v -r`  will be helpful.

**Comment by cdahnken** [comment]
Hi @exprmntr 
I removed ~/.ya and did execute (./ya -v make -v -r 2>&1) | tee  ya.out

ya.out attached (hope that works).

Chris

[ya.txt](https://github.com/catboost/catboost/files/1454263/ya.txt)

**Comment by cdahnken** [comment]
Hi @exprmntr  once more,

just noticed I was executing on the wrong machine (wrong OS). Doesn't make a difference, however. Output attached.

Chris
[ya-7.4.txt](https://github.com/catboost/catboost/files/1454349/ya-7.4.txt)

**Comment by exprmntr** [comment]
It seems like we have some problems with NFS now.

Have you any local file system? You can set environment variable YA_CACHE_DIR (`export YA_CACHE_DIR=/path/to/dir`) to use it for build caches.

**Comment by cdahnken** [comment]
I don't have a local directory other than /tmp that I can access without root permissions. I put everything into /tmp/catboost and set the YA_CACHE_DIR=/tmp/catboost/cache and redid the whole process. It went further now and then stops since CUDA is not configured. I guess that can be fixed easily, I might have seen that in the documentation.

Attached the output

[ya.txt](https://github.com/catboost/catboost/files/1454586/ya.txt)

**Comment by exprmntr** [comment]
To build anything with CUDA you need to have CUDA Toolkit installed (from https://developer.nvidia.com/cuda-80-ga2-download-archive for example) and run `ya make` with `CUDA_ROOT` flag (e.g. `ya make -r -DCUDA_ROOT=/usr/local/cuda-8.0 catboost/cuda/app`). 

Or you can build something that does not require CUDA: `ya make -r catboost/app` will build CPU-only version.

**Comment by sab** [comment]
DEVTOOLS-3945 (internal issue ID)

**Comment by annaveronika** [comment]
We decided to not support NFS. We provided make files, please use it if ya make doesn't work for you.
