### ISSUE TITLE
Interaction between has_time parameter and bagging

### ISSUE THREAD

**Issue by brunofacca** [catboost/catboost#1663]
Hello, thank you for this great library.

When using CatBoost with time series data, does setting `has_time=True` affect the random sampling used in bagging (when the `subsample` parameter is set to a value `< 1.0`) in any way?

**Comment by andrey-khropov** [comment]
They are independent.

`has_time` means there will be no random permutation of the training data on different stages (as described in the documentation for this parameter at https://catboost.ai/docs/concepts/python-reference_parameters-list.html). 

But subsampling can be used regardless of `has_time` value, its logic does not depend on objects order.

**Comment by brunofacca** [comment]
Thank you!
