### ISSUE TITLE
Current release of catboost-spark is not fully published on mavencentral

### ISSUE THREAD

**Issue by jean-helsinki** [catboost/catboost#1664]
Problem: Most of the remaining libraries and artifacts are also not updated to the current release, and there are a lot of fixes in it.
https://mvnrepository.com/artifact/ai.catboost?sort=newest

**Comment by andrey-khropov** [comment]
1) mvnrepository seems to fails to show versions for artifacts that contain '_<spark_compat_version>_<scala_compat_versio n>' properly, it just redirects to catboost-spark.

Search on maven.com shows versions properly: https://search.maven.org/search?q=catboost

2) catboost-spark hasn't been updated from 0.25 to 0.25.1, I'll fix this for consistency, but all the main changes from 0.25 to 0.25.1 do not affect CatBoost for Spark.

**Comment by andrey-khropov** [comment]
Versions are now in sync
