### ISSUE TITLE
Catboost Error 

### ISSUE THREAD

**Issue by kklo123** [catboost/catboost#1665]
Problem: problem occurred when running model.fit()
catboost version: 0.25.1
Operating System:Windows 10

Then an error occurred:
CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/tools/enum_parser/enum_serialization_runtime/enum_runtime.cpp:32: Key 'lter' not found in enum EOverfittingDetectorType. Valid options are: 'None', 'Wilcoxon', 'IncToDec', 'Iter'.

**Comment by LyzhinIvan** [comment]
Because 'lter' != 'Iter'.

**Comment by kklo123** [comment]
thanks. how to solve?

**Comment by LyzhinIvan** [comment]
> thanks. how to solve?

Just use `od_type='Iter'` instead of `od_type='lter'`.

**Comment by kklo123** [comment]
thanks.
