### ISSUE TITLE
Place scripts in share/jupyter/nbextensions/catboost directory

### ISSUE THREAD

**Issue by DonJayamanne** [catboost/catboost#1673]
Problem: The catboost widget does not load in VS Code
catboost version: N/A
Operating System: N/A
CPU: N/A
# GPU: 

I'm one of the maintainers of the [Jupyter extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter). 

Thanks for creating this awesome package. Some of the users of this package are using VS Code, and they're unable to get the widget working in VS Code. The Jupyter extension in VS Code supports a number of Widgets (if not all) that work in Jupytere Notbooks/Labs.

See here for user issues in VS Code Jupyter related to catboost (https://github.com/microsoft/vscode-jupyter/issues/1684, https://github.com/microsoft/vscode-jupyter/issues/5555, https://github.com/microsoft/vscode-jupyter/issues/1913, https://github.com/microsoft/vscode-jupyter/issues/841, https://github.com/microsoft/vscode-jupyter/issues/596).

The reason for this is the widget is loaded dynamically in Python code as follows, and the VS Code webview used to render output doesn't allow direct access to the file system due to security reasons. 

```python
        with open(self._get_static_path('CatboostIpythonPlotly.js')) as f:
            js += f.read()
        with open(self._get_static_path('CatboostIpythonInit.js')) as f:
            js += f.read()
        html = """
            <style>
                {}
            </style>
            <script>
                {}
            </script>
        """.format(css, js)

        display(HTML(html))
```

The way we (Jupytr Exenison in VS Code) get around this is by placing the necessary scripts into a separate location. However we're unable to locate these scripts as they ar not in the standard locationi for other (widget) scripts in Jupyter.

Based on Jupyter documentation & cookie cutter such scripts would go into `share/jupytr/nbextensions/` folder (see here https://github.com/jupyter-widgets/widget-cookiecutter, https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html).

Additionally placing this on a CDN would be even better (would ensure this works in [voila](https://github.com/voila-dashboards/voila), vs code code spaces, & other such environments

See here for details on Jupyter https://ipywidgets.readthedocs.io/en/latest/migration_guides.html#updating-the-python-code

If placed there these widgets would work outside classic Jupyter Notebooks & Labs (which happens to be a supported scenario by the jupyter architecture).

Would it bee possible to make this change.
I'd be happy to submit a PR if you are willing to accept one that addresses this issue.

Thanks

**Comment by DonJayamanne** [comment]
Additionally placing this on a CDN would be even better (would ensur this works in [voila](https://github.com/voila-dashboards/voila), vs code code spaces, & other such environments

**Comment by LyzhinIvan** [comment]
Hi, @DonJayamanne! 

Yesterday we have merged PR https://github.com/catboost/catboost/pull/1636 that enables our widget to work in Jupyter Lab and VsCode. It will be a part of the next release.

**Comment by DonJayamanne** [comment]
Wow, thanks slot.

Any chance of getting the scripts on a cdn as well. And that's our preferred approach.

That would be perfect, then it'll work in other scenarios too - cloud, remote, voila, docker.
Thank you very much, this will greatly help our users.

**Comment by LyzhinIvan** [comment]
Hi, @DonJayamanne! 

I've published our widget at NPM https://www.npmjs.com/package/catboost-widget. And it is automatically available through jsDelivr CDN https://cdn.jsdelivr.net/npm/catboost-widget. Please check that it works fine in voila.

**Comment by jasongrout-db** [comment]
First, thanks for all your work on this awesome project!

> I've published our widget at NPM https://www.npmjs.com/package/catboost-widget. And it is automatically available through jsDelivr CDN https://cdn.jsdelivr.net/npm/catboost-widget. Please check that it works fine in voila.

It looks like the AMD modules that you are building are not actually available in NPM because the package.json `files` attribute is not set up to include them. Note that the dist/ directory is not available at https://www.jsdelivr.com/package/npm/catboost-widget

In order to package up that dist directory, you'll need to add the dist directory to the package.json `files` attribute, like is done in the widget cookiecutter here: https://github.com/jupyter-widgets/widget-cookiecutter/blob/3aa8c7accdc3fd815a01805df45df869d81454a3/%7B%7Bcookiecutter.github_project_name%7D%7D/js/package.json#L18-L21

```
  "files": [
    "src/**/*",
    "dist/**/*"
  ],
```

**Comment by jasongrout-db** [comment]
> It looks like the AMD modules that you are building are not actually available in NPM because the package.json `files` attribute is not set up to include them.

I opened an issue for this at https://github.com/catboost/catboost/issues/2134
