### ISSUE TITLE
target_converter.cpp:376: Target contains only one unique value

### ISSUE THREAD

**Issue by nush12** [catboost/catboost#1676]
Problem: Get this error when I try to fit a model data is exactly like this 
and hyper parameters are as below. Not sure, my target is not unique values.

{'depth': 4, 'learning_rate': 0.14, 'l2_leaf_reg': 9.967570714427186, 
               'iterations': 180, 'loss_function': 'Logloss', 'logging_level': 'Silent'}

X1 | X2 | X3 | X4 | X6 | X7 | target
-- | -- | -- | -- | -- | -- | --
2019 | 2 | 8.42 | 9.58 | 0 | 1 | 1
2019 | 3 | 8.42 | 9.58 | 0 | 1 | 1
2019 | 4 | 8.42 | 9.58 | 1 | 1 | 0
2019 | 5 | 8.42 | 9.58 | 0 | 1 | 0
2019 | 6 | 8.42 | 9.58 | 0 | 1 | 0
2019 | 7 | 8.42 | 9.58 | 1 | 1 | 0
2019 | 8 | 8.42 | 9.58 | 0 | 1 | 1
2019 | 9 | 8.42 | 9.58 | 0 | 1 | 0
2019 | 10 | 8.42 | 9.58 | 0 | 1 | 0
2019 | 11 | 8.42 | 9.58 | 1 | 1 | 1
2019 | 12 | 8.42 | 9.58 | 1 | 1 | 1
2020 | 1 | 8.49 | 9.69 | 0 | 1 | 1
2020 | 2 | 8.49 | 9.69 | 0 | 1 | 1

catboost version: '0.25.1'
Operating System:  Windows 10.0.19042 Build 19042
CPU: 
# GPU:

**Comment by nush12** [comment]
CPU - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by nush12** [comment]
any update on this?

**Comment by LyzhinIvan** [comment]
Hi,  @nush12!

Please, provide full script - I can't reproduce it.

**Comment by andrey-khropov** [comment]
I also cannot reproduce and no additional info has been provided.
