### ISSUE TITLE
When predict() is called on empty dataframe, I am getting "Process finished with exit code 136 (interrupted by signal 8: SIGFPE)"

### ISSUE THREAD

**Issue by ibobak** [catboost/catboost#1679]
Problem:
catboost version: 0.25.1
Operating System: Ubuntu 18.04.2 LTS
CPU: 64x Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
GPU: no

My mistake was that I generated an empty dataframe (with all needed columns - all features on place) and did a call to
```
model.predict(Pool(data=pdf_test, cat_features=cat_features))
```

But somewhere in catboost there is a bug:   it crashes with
```
Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```
if such call is made.

Before this it is calculating somethimg,  calculating, calculating.... almost for a minute.  One cpu core is totally busy as if something is happening... and finally BANG!  

I was searching for several hours of what might be the problem until I realized that the problem is that your code doesn't absolutely check for 0 rows in the dataframe.

**Comment by LyzhinIvan** [comment]
Fixed by ad78255c143ebe82b7f94428abea3417b9d60033
