### ISSUE TITLE
baseline problems

### ISSUE THREAD

**Issue by DBusAI** [catboost/catboost#168]
I have a binary classification problem. How could i add baseline? It support only `prediction_type='RawFormulaVal'`, but `base_model.predict(pool, prediction_type='RawFormulaVal')` returns only 1 column, so I have 
**CatboostError: Baseline must be 2 dimensional data, 1 column for each class.**
Also, baseline option i need for dynamic change of learning_rate after N iterartion (it sounds like workaround for me)
So, could you add learning_rates as array please, or collback function for dynamic change of parameters& **Thx**

**Comment by annaveronika** [comment]
Thank you for the report, we'll fix the baseline soon

**Comment by annaveronika** [comment]
it's fixed now
