### ISSUE TITLE
how can I predict on gpu?

### ISSUE THREAD

**Issue by hickskin** [catboost/catboost#1686]
how can I predict on gpu?
I did not see parameter to set gpu for prediction....
https://catboost.ai/docs/concepts/python-reference_catboostclassifier_predict.html

I was able to train the model on gpu.

**Comment by hickskin** [comment]
I trained the model on GPU and saved it. But, when I predict using the saved model, it uses CPU only and not the GPU and prediction is slower.

**Comment by kizill** [comment]
Hello, this issue is a duplicate of #972, we are finishing this task so subscribe to related issue :)
