### ISSUE TITLE
is there documentation \ examples for using embedding_features?

### ISSUE THREAD

**Issue by ophiry** [catboost/catboost#1689]
from this part of the code: https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/core.py#L411 it appears that catboost supports embeddings inputs, but I couldn't find any example \ documentation about the expected input structure

**Comment by LyzhinIvan** [comment]
Hi, @ophiry!
Embedding features are not documented properly yet. There is small description in [Release Notes](https://github.com/catboost/catboost/releases/tag/v0.24.2) and small example in the end of [this tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/events/2020_11_18_catboost_tutorial/text_embedding_features.ipynb).
