### ISSUE TITLE
Probability is not consistent with class

### ISSUE THREAD

**Issue by Sapaud** [catboost/catboost#169]
Hi,
I have a binary classification problem, I try to use CatBoostClassifier.predict() function to ouput a sample's probablity, the function ouputs a probability haigher than 0.5, however, when I predict the same sample's class, the function outputs class 0. How can I fix it?

**Comment by annaveronika** [comment]
This should not happen, because we calc class == proba > 0.5 https://github.com/catboost/catboost/blob/master/catboost/libs/algo/eval_helpers.cpp#L94

Could you provide data+code that lead to this problem?

**Comment by Sapaud** [comment]
I'm sorry, maybe I have made some mistakes before. But I still have some confuse.
and I'm sorry I can't provide data, here are some code and results
dataset**'s types are all pd.DataFrame
train label is in {0,1}
train:
![1](https://user-images.githubusercontent.com/32292416/33022166-342e35da-ce3f-11e7-8a8f-1182bcc6c1a0.png)

predict probability:
![2](https://user-images.githubusercontent.com/32292416/33022191-45af5366-ce3f-11e7-8023-7ff3b3e79e7e.png)

predict class:
![default](https://user-images.githubusercontent.com/32292416/33022738-1c2f8aea-ce41-11e7-9520-038771882821.png)


when predict probability, the function output a 1-d ndarray (call A) before which I didn't save, now I run it again, it ouput a 2-d (call B) ndarray, which column is the real probability? And the results before, namely 1-d ndarray A, just like the first columns of 2-d ndarray, namely A = B[:,0]

**Comment by nikitxskv** [comment]
@Sapaud, Hello!
The probability of the first class is in the second column. It is standart skearn format.
