### ISSUE TITLE
CatBoostError: catboost/private/libs/options/overfitting_detector_options.cpp:48: Wait iterations in OD-detector should be > 0

### ISSUE THREAD

**Issue by sridharnomula** [catboost/catboost#1690]
Problem:
catboost version: 0.24.4
Operating System: Linux
CPU:
# GPU:1

Model ran for the first time, but is not running with same setup again.

**Comment by LyzhinIvan** [comment]
Hi, @sridharnomula!

We need more details to investigate the problem. Please, provide a reproducible example.

**Comment by andrey-khropov** [comment]
No feedback, feel free to reopen with more detailed data if the issue can still be reproduced.
