### ISSUE TITLE
[ci] Unused continuous integration configs

### ISSUE THREAD

**Issue by jameslamb** [catboost/catboost#1700]
I was looking through this repo tonight and noticed that there are some configs and other files for the continuous integration (CI) services [Appveyor](https://www.appveyor.com/) and [Travis](https://travis-ci.org/).

I noticed that these configs have not been updated in a few years. And when I last contributed to this repo about 3 months ago (#1548), I did not see any indication that automatic checks were running on these services.

Has this project stopped using Appveyor and Travis? If so, would maintainers accept a pull request that removes files related to those services?

* https://github.com/catboost/catboost/blob/e91e152975fef228825f6d0f5b2212f5859ead17/.appveyor.yml
* https://github.com/catboost/catboost/blob/e91e152975fef228825f6d0f5b2212f5859ead17/.travis.yml
* https://github.com/catboost/catboost/tree/e91e152975fef228825f6d0f5b2212f5859ead17/ci/appveyor
* https://github.com/catboost/catboost/tree/e91e152975fef228825f6d0f5b2212f5859ead17/ci/travis

Thanks for your time and consideration.

**Comment by kizill** [comment]
Thank you for that reminder :) Will delete them soon.
