### ISSUE TITLE
model_dataset_compatibility.cpp:81:  

### ISSUE THREAD

**Issue by JustMyry** [catboost/catboost#1709]
Problem: model_dataset_compatibility.cpp:81:  
catboost version: catboost 0.25.1
Operating System: Windows 10
CPU: Ryzen 7 2700x
# GPU: GTX 1660 Super

I run into this problem when I send data to the model for prediction. How can I solve it? 
I did not understand exactly what I mistake was

C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:81: At position 0 should be feature with name Il (found 0).

**Comment by ek-ak** [comment]
Hello! Thank you for your question.
This means that 
1) model was trained on dataset with feature "Il" at position 0
2) the dataset on which you failed to obtain predictions has feature name for feature at position 0 (and this name is "0")

Please check that data columns in your data for prediction are in correct order and check data feature names (also everything will work if data has no feature names at all).
