### ISSUE TITLE
catboost `cv` function freezes with scikit-learn splitter object passed as `folds` parameter

### ISSUE THREAD

**Issue by 2korzhik** [catboost/catboost#1710]
Problem: 
catboost version: **0.25.1**
Operating System: **Debian GNU/Linux 10 (buster)**
CPU: **Intel Xeon Processor (Cascadelake)**

I am implementing crossvalidation using catboost **cv** function and want to use my own splitter. 
My dataset consists of more than **4 million objects** and contains group column with over **90 000 unique groups**. 
I have encountered the fact that under such conditions the **cv** function starts and runs infinitely long time.
The only thing you can see is that one of CPU core is working at 100% for hours and that's it.
The problem disappears if the number of unique groups is reduced by several orders of magnitude.
Also the problem does not reproduce If you iterate the results of _split()_ method of the splitter object manually. 
This leads me to conclude that the problem is in the implementation of the cv function.

**Code to reproduce the problem**

```python
from catboost import Pool, cv
import numpy as np
import pandas as pd

from sklearn.datasets import make_classification
from sklearn.model_selection import GroupKFold

# Data preparation
n_samples=4000000
n_features=4
random_state=0
n_groups=90000 #

X, y = make_classification(n_samples=n_samples, n_features=n_features, random_state=random_state)

X = pd.DataFrame(X, columns=['{}_{}'.format('f', i) for i in range(n_features)])
y = pd.Series(y, name='target')

group_choises = list(map(str, list(range(1, n_groups))))
X['group_col'] = pd.Series(np.random.choice(group_choises, size=n_samples))
                     
y = y[X.sort_values('group_col').index].reset_index()['target']                     
X.sort_values('group_col', inplace=True, ignore_index=True)

groups = X.group_col.values

# Example of code that works flawlessly:
splitter = GroupKFold(n_splits=5)
for train_idxs, test_idxs in splitter.split(X, y, groups):
    print('train  test')
    print(len(groups[train_idxs]), len(groups[test_idxs]))
    print(len(y[train_idxs]), len(y[test_idxs]))
    print()

# Example of code that works infinitely long time:
train_pool = Pool(data=X, label=y, has_header=True, group_id=groups)
splitter = GroupKFold(n_splits=5)

params = {
    'iterations': 2,    
    'learning_rate': 0.5,
    'loss_function': 'Logloss',
    'custom_loss': ['Accuracy'],
    'eval_metric': 'AUC',
}

cv_data = cv(
    params = params,
    pool = train_pool,
    verbose = False,
    plot=True,
    folds = splitter
)
```

**Comment by kizill** [comment]
Fixed in master, fix will be available in the nearest release this week.
