### ISSUE TITLE
Cannot import name 'metrics' from 'catboost'

### ISSUE THREAD

**Issue by acnazarejr** [catboost/catboost#1712]
I'm following the Catboost basic tutorial and when try to import metrics from catboost I'm receiving the following error: 

"cannot import name 'metrics' from 'catboost'"

catboost version: 0.25.1
Operating System: Windows (I try google colab also)

**Comment by kizill** [comment]
Sorry for that! That tutorial is a part of next release, as catboost.metrics module will be available in next release, 0.26 by the end of current week.

**Comment by hit002usa** [comment]
@kizill thanks

**Comment by tle4336** [comment]
@kizill I am encountering this issue even though I installed `catboost` version `2.6.0` successfully in pycharm 2022 (OS = Windows 10 64x bit). 
`for metric_name, metric_param_sets in _catboost.AllMetricsParams().items():
AttributeError: module 'catboost._catboost' has no attribute 'AllMetricsParams'`
