### ISSUE TITLE
Unable to define custom metric for multiregression

### ISSUE THREAD

**Issue by infoshoc** [catboost/catboost#1713]
Problem: Unable to define a custom metric for multi regression.
catboost version: 0.25.1
Operating System: MacOS
CPU: 1

Even the most generic 
```
class Metric(object):
    def is_max_optimal(self):
        return True
    def evaluate(self, *args, **kwargs):
        return 0.0
    def get_final_error(self, *args, **kwargs):
        # Returns final value of metric based on error and weight
        return 0.0    
reg = CatBoostRegressor(iterations=300, 
                        eval_metric=Metric,
loss_function='MultiRMSE')
```

fails with 
CatBoostError: catboost/libs/metrics/caching_metric.cpp:1047: Metric [] requires one-dimensionaltarget

Is it supported? Thank you!

**Comment by ThomasWolf0701** [comment]
yes it is, here´s an example

from catboost import  MultiRegressionCustomMetric
#from catboost import  MultiRMSEMetric
#from catboost import MultiRegressionCustomObjective

class MultiRMSEMetric(MultiRegressionCustomMetric):
    def is_max_optimal(self):
        return False # greater is better

    def evaluate(self, approxes, targets, weight):
       

        output_weight = 1 # weight is not used
        
        score =  mean_absolute_percentage_error(targets,approxes)
 
        return score, output_weight

    def get_final_error(self, error, weight):
        return error

**Comment by kizill** [comment]
Thank you @ThomasWolf0701 for quick answer :) 
@infoshoc if you have any additional questions, please reopen :)
