### ISSUE TITLE
cannot import name 'metrics' from 'catboost'

### ISSUE THREAD

**Issue by geilerloui** [catboost/catboost#1714]
Problem: I have the following message
ImportError: cannot import name 'metrics' from 'catboost' (/Users/****/opt/anaconda3/lib/python3.8/site-packages/catboost/__init__.py)
I have also tried with the google colab from your tutorial (https://github.com/catboost/tutorials/blob/master/python_tutorial.ipynb) and another jupyter notebook in AWS I have the same error everywhere. 
catboost version: 0.25.1 I have also tried with 0.24.4
Operating System: Mac OS
CPU:
# GPU:

**Comment by kizill** [comment]
Sorry for that! That tutorial is a part of next release, as catboost.metrics module will be available in next release, 0.26 by the end of current week.
You can use previous revision of tutorial from 0.25.1 tag:
https://github.com/catboost/catboost/blob/v0.25.1/catboost/tutorials/python_tutorial.ipynb

**Comment by kizill** [comment]
0.26 released, will work from now on :)

**Comment by tle4336** [comment]
It still doesn't work for me...
