### ISSUE TITLE
Request: cat feature support for GridSearchCV 

### ISSUE THREAD

**Issue by JackyKoh** [catboost/catboost#172]
When using Sklearn's GridSearchCV with catboost. You are unable to pass through the cat features array through the .fit function of GridSearchCV. I would suggest allowing cat feature to be an optional parameter for the model function

example of issue:
```
cat_features = [0,1,2,3,8,9,10,11]
params = {'depth': [4, 6, 8],
          'random_seed' : [400, 100, 200],
          'learning_rate' : [0.01, 0.03, 0.1]}
cb = CatBoostRegressor(loss_function='RMSE', iterations = 500, learning_rate=0.03)
cb_model = GridSearchCV(cb, params, scoring='neg_mean_squared_error', cv = 5)
cb_model.fit(X_train, Y_train, cat_features)
#returns error
```
`cb_model.fit(train_pool) 
`
doesn't work either

proposed solution:
`cb = CatBoostRegressor(loss_function='RMSE', iterations = 500, learning_rate=0.03, cat_features)
`

**Comment by annaveronika** [comment]
Sorry for a long response! We are thinking on how to do this better. We'll write when decided.

**Comment by annaveronika** [comment]
We'll do that

**Comment by andrey-khropov** [comment]
@JackyKoh 

> You are unable to pass through the cat features array through the .fit function of GridSearchCV.

`cb_model.fit(X_train, Y_train, cat_features)`

Pass it like that and it should work (because 3rd positional argument for GridSearchCV.fit is groups):

`cb_model.fit(X_train, Y_train, cat_features = cat_features)`

**Comment by sriramkraju** [comment]
**I tried as below:**
______________________________________________________________________________________________________
categorical_features_indices = np.where((X.dtypes != np.int) & (X.dtypes != np.float))[0];
print(categorical_features_indices)

[0 1 2 3 4 5 6 9]
________________________________________________________________________________________________________
from sklearn.pipeline import Pipeline as pl
steps = [
         ("model", CatBoostRegressor(random_seed=40))
        ]
pipe = pl(steps)
________________________________________________________________________________________________________
grid = GridSearchCV(pipe, param_grid, cv=kf,scoring='neg_mean_squared_error')
grid.fit(X_train, y_train,cat_features = categorical_features_indices)
________________________________________________________________________________________________________
**and got the below error.**

**ValueError: not enough values to unpack (expected 2, got 1)**

File attached:

[Gridsearch_CatboostRegressor_Error.zip](https://github.com/catboost/catboost/files/1999056/Gridsearch_CatboostRegressor_Error.zip)

**Comment by sriramkraju** [comment]
@ annaveronika
Is there a tentative date when this feature will be available?

**Comment by annaveronika** [comment]
@sriramkraju Could you try with latest sklearn version?

**Comment by sriramkraju** [comment]
@annaveronika 

I have the latest version:

import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

**The scikit-learn version is 0.19.1.**

**Comment by andrey-khropov** [comment]
@sriramkraju 


> from sklearn.pipeline import Pipeline as pl
> steps = [
> ("model", CatBoostRegressor(random_seed=40))
> ]
> pipe = pl(steps)

> grid = GridSearchCV(pipe, param_grid, cv=kf,scoring='neg_mean_squared_error')
> grid.fit(X_train, y_train,cat_features = categorical_features_indices)

> and got the below error.

> ValueError: not enough values to unpack (expected 2, got 1)

 You get that error because you don't use CatBoostRegressor directly but use it inside Pipeline. To pass parameters to a certain step in the pipeline you should prefix them with '<step_name>__' (see http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html). 

So, for your example the correct code is:

> grid.fit(X_train, y_train, model__cat_features = categorical_features_indices)

**Comment by umoarsman** [comment]
@andrey-khropov 
I implemented the fix above 

grid.fit(X_train, y_train, model__cat_features = categorical_features_indices)

and still get a "could not convert string to float" on my a categorical column. Note that I changed "model" to "clf" in my code, as that's what I defined the classifier as in my pipeline.

**Comment by sriramkraju** [comment]
@andrey-khropov

Thanks.The below code worked for me. 
grid.fit(X_train, y_train, model__cat_features = categorical_features_indices)

@umoarsman 
Try passing the indexes for the categorical features as below:
categorical_features_indices = np.where(X_train.dtypes == np.object)[0];
print(categorical_features_indices) 
[0 1 2 3 4 5 6 9]

**Comment by hugoncosta** [comment]
Maybe you should try hyperopt? It's the library used in the [python tutorials](https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_python_tutorial.ipynb), different syntax than GridSearch, same result.

**Comment by annaveronika** [comment]
Now it is possible to pass cat_features when constructing the estimator object, so it should work fine with GridSearchCV. Please try the latest version from github. The next version on pypi will come later - most probably in September.

**Comment by PhilipMachineLearning** [comment]
> Now it is possible to pass cat_features when constructing the estimator object, so it should work fine with GridSearchCV. Please try the latest version from github. The next version on pypi will come later - most probably in September.

Hi thanks for the updates - I have tried this in with loss_function='MultiClass' but the examples given above do not seem to work. Did you create any documentation with this update?

**Comment by davins90** [comment]
Hi guys, is there any news on solving these issues? thanks

**Comment by andrey-khropov** [comment]
> Hi guys, is there any news on solving these issues? thanks

What issues?
I don't have any issues with `cat_features` and `GridSearchCV` right now with the examples above.

They work for me with CatBoost 1.0.3 and sklearn version 0.24.2 including cases when `loss_function` is `MultiClass`:

If we specify parameters in the constuctor of `CatBoostClassifier` (or `CatBoostRegressor`) 

```py
import sklearn
import sklearn.model_selection
import catboost


print ('sklearn version', sklearn.__version__)
print ('catboost version', catboost.__version__)

X_train = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14],
    [16, 17, 18]
]

y_train = [0, 1, 2, 1, 2, 0]

param_grid = {
    'depth': [4, 6, 8],
    'random_seed' : [400, 100, 200],
    'learning_rate' : [0.01, 0.03, 0.1]
}

model = catboost.CatBoostClassifier(loss_function='MultiClass', cat_features=[0,1,2])

grid_search = sklearn.model_selection.GridSearchCV(model, param_grid, cv=2, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)
```

If we specify parameters to Pipeline stages:

```py
import sklearn
import sklearn.model_selection
import sklearn.pipeline
import catboost


print ('sklearn version', sklearn.__version__)
print ('catboost version', catboost.__version__)

steps = [
    ("model", catboost.CatBoostClassifier(loss_function='MultiClass', random_seed=40))
]
pipe = sklearn.pipeline.Pipeline(steps)

X_train = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14],
    [16, 17, 18]
]

y_train = [0, 1, 2, 1, 2, 0]

param_grid = {
    'model__depth': [4, 6, 8],
    'model__random_seed' : [400, 100, 200],
    'model__learning_rate' : [0.01, 0.03, 0.1]
}

grid_search = sklearn.model_selection.GridSearchCV(pipe, param_grid, cv=2, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train, model__cat_features = [0, 1, 2])
```

**Comment by davins90** [comment]
Hi @andrey-khropov  and thanks for your useful answer, i was having problem with another preprocessing step in the pipeline from sklearn (with an imputation step). 

Why don't you use the grid_search method from CatBoost? Is it not useful in a pipeline sklearn object? Thanks
