### ISSUE TITLE
Which algorithm handle embeddings_features ?

### ISSUE THREAD

**Issue by dangchienhsgs** [catboost/catboost#1720]
I saw in fit() function of class CatBoostClassifier has the option `embedding_features`:

```
embedding_features: list or numpy.ndarray, optional (default=None)
    If not none, giving the list of Embedding columns indices.
    Use only if X is not catboost.Pool and not catboost.FeaturesData
``` 

Can you guys explain how Catboost handles this? I found in official documentation and some papers but I did not find anything related ? 

Thanks,

**Comment by candalfigomoro** [comment]
It should be LDA (Linear Discriminant Analysis)

**Comment by dangchienhsgs** [comment]
Did the Java API has not support this feature ? I checked the code in branch master

**Comment by andrey-khropov** [comment]
> Have the Java API not support this feature ? I checked the code in branch master

It has been added to JVM API in 21f8d27a98d651038a237d350a08fe355e6e2e8a and will be included in the next release.
