### ISSUE TITLE
Segmentation fault in the middle of training

### ISSUE THREAD

**Issue by VGODIE** [catboost/catboost#1722]
Problem: Trained catboost during hyperparameter optimization with cross_validation on two GPUs with parameter random_strength which is very important for my purpose, several iterations of optimizations were OK: catboost trained and gave predictions but then suddenly i got segmentation fault. I have searched over previous issues and other google materials but I haven't found similar problem 
catboost version: 0.24.4
Operating System: Ubuntu 20.04
GPU: True

**Comment by VGODIE** [comment]
@david-waterworth I saw you faced somewhat the same can you tell please what exactly have you done to fix it ?

**Comment by david-waterworth** [comment]
@VGODIE from memory the issue I had was an out of memory due to the model being too large for my gpu's. I fixed it by lowering the depth of the trees.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@VGODIE Could you please provide a reproducer so that we could debug this issue?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@VGODIE ping
