### ISSUE TITLE
 Must use 'enum' tag to refer to type 'EApiPredictionType'

### ISSUE THREAD

**Issue by CristianCantoro** [catboost/catboost#1724]
* Problem: error in `catboost/libs/model_interface/c_api.h`
* catboost version: `master` (commit [43e7c27475fd2b8f6f16f845f6350837d5db522e](https://github.com/catboost/catboost/commit/a4e9e2f2f266a5cfe59f0f3d21fdeac6530c4aa9))
* Operating System: n/a
* CPU: n/a
* \# GPU: n/a

I am writing a program that uses `catboost/catboost/libs/model_interface/model_calcer_wrapper.h`, when I try to compile it with the following command:
```make
clang \
		-I../catboost \
		-L../catboost/catboost/libs/model_interface/ \
		-o solver \
		main.c lib.c \
		-lcatboostmodel \
		-lm
```

I get the following error:
```c++
In file included from main.c:10:
In file included from ./../catboost/catboost/libs/model_interface/model_calcer_wrapper.h:3:
./../catboost/catboost/libs/model_interface/c_api.h:100:69: error: must use 'enum' tag to refer to type 'EApiPredictionType'
CATBOOST_API bool SetPredictionType(ModelCalcerHandle* modelHandle, EApiPredictionType predictionType);
                                                                    ^
                                                                    enum 
1 error generated.
Makefile:4: recipe for target 'solver' failed
make: *** [solver] Error 1
```

To solve this I just modified in `catboost/catboost/libs/model_interface/c_api.h` (line 100):
```c++
CATBOOST_API bool SetPredictionType(ModelCalcerHandle* modelHandle, EApiPredictionType predictionType);
```

to:
```c++
CATBOOST_API bool SetPredictionType(ModelCalcerHandle* modelHandle, enum EApiPredictionType predictionType);
```

and this solves the error.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Enormous thanks @CristianCantoro !
Fixing this right now.
