### ISSUE TITLE
Getting Model decision threshholds & cutoffs? [Need Info]

### ISSUE THREAD

**Issue by ddofer** [catboost/catboost#1725]
I'm trying to understand how to get the prediction cutoff used by the model in making binary predictions. 
(I trained a model with imbalanced data, +- using class weights. I'm analyzing the results with a ROC-AUC plot, on cross validated predictions over the whole test set.
 I want to know what the cutoff was for the model, by default. Is it ">0.5"? (If so, how does that align with the output of "predict_proba" being probabilities and not just a confidence score?) 

Thnks!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi @ddofer! 
Here is a [link ](https://catboost.ai/docs/concepts/output-data_model-value-output.html#output-data_model-value-output__classification) to the relevant piece of documentation.
E.
