### ISSUE TITLE
Issue with installation in R.

### ISSUE THREAD

**Issue by Shafi2016** [catboost/catboost#1726]
I want to install catboost R version on window 10 but I am getting the error given below.
```
library(devtools) 
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
```

Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz' failed
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `INSTALL_opts`

Did you misspecify an argument?

**Comment by grag90** [comment]
Hello!
To help us reproduce your issue, please, write version of R and check that you are using latest version of R, devtools & other libraries.
This command works fine with latest R for windows within RStudio, so we need more details to reproduce your problem.
Also, please check a possible solution from https://github.com/r-lib/devtools/issues/2109#issuecomment-534169816_

**Comment by Shafi2016** [comment]
Thanks, First, download catboost pakage  (tgz)  then us following it worked. Perhaps it would be good to add this your instruction page. It may be helpful for others.

`install.packages("D:/catboost-R-Windows-0.26.tgz", repos = NULL, type = "source", INSTALL_opts = c("--no-multiarch", "--no-test-load"))
`
