### ISSUE TITLE
New 4.1. version throws on the same old code

### ISSUE THREAD

**Issue by snovik75** [catboost/catboost#174]
And the message is not informative. What additional info can I provide?

```
/usr/lib/python3.6/site-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot)
   1229         model : CatBoost
   1230         """
-> 1231         self._fit(X, y, cat_features, None, sample_weight, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot)
   1232         if y is not None:
   1233             setattr(self, "_classes", np.unique(y))

/usr/lib/python3.6/site-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, query_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot)
    563                 raise ImportError(str(e))
    564         with log_fixup():
--> 565             self._train(X, eval_set, params)
    566         if calc_feature_importance:
    567             setattr(self, "_feature_importance", self.get_feature_importance(X))

_catboost.pyx in _catboost._CatBoostBase._train()

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatboostError: library/json/writer/json_value.cpp:463: Not a string
```

And on the import I get this message:
```
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module '_catboost' does not match runtime version 3.6
  return f(*args, **kwds)
```

I installed through pip

**Comment by annaveronika** [comment]
Could you provide the code you were running?

**Comment by snovik75** [comment]
Nothing particular. Here is the code:
`        d_train = cb.Pool(X_train, y_train)

        self.model = cb.CatBoostClassifier(**self.params,
                                           iterations=10000,
                                           od_type='Iter', od_wait=70, random_seed=2906)

        d_valid = cb.Pool(X_valid, y_valid)
        self.model.fit(d_train, use_best_model=True, eval_set=d_valid, logging_level=False) `

Here are my params (actually I even dont have nans any more):
`params = {'loss_function': 'Logloss', 'eval_metric': 'AUC',
          'depth': 6,
          'learning_rate': 0.03,
          'rsm': 0.6,
          'nan_mode': 'Min',
         }`

It is all part of a big wrapper class but this is the core

**Comment by annaveronika** [comment]
Could you try logging_level=Silent? There is no False value for it, only Silent, Verbose, Info, Debug

**Comment by snovik75** [comment]
Yes, Silent is fine. Could you please keep the documentation up-to-date? At least for the breaking changes.

**Comment by annaveronika** [comment]
Sorry for that. We'll try to update the documentation in time.
