### ISSUE TITLE
Different predict outcomes using sklearn compared to catboost reported metrics while using class weights parameter

### ISSUE THREAD

**Issue by Chandra-Avinish** [catboost/catboost#1747]
Problem:

I am working on an imbalanced set with ratio of 1:17 for minority to majority class, the minority class is of interest(positive class),
while trying to specify class_weights parameter as {0: 1, 1: 17}, catboost reports a precision of around 70%, but when I use sklearn to evaluate metrics, the precision is just over the baseline giving ~7% precision, I believe this has been reported earlier but unable to find what is going wrong here.

catboost version:
Operating System:
CPU:
# GPU:

**Comment by LyzhinIvan** [comment]
The answer is here: https://github.com/catboost/catboost/issues/1577#issuecomment-781361575
