### ISSUE TITLE
Training with sparse matrix just terminates without error

### ISSUE THREAD

**Issue by step4** [catboost/catboost#1749]
**catboost version:** 0.26
**Operating System:** Windows 10
**CPU:** Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

**Problem:**
I try to build a simple text classifier with catboost and this kaggle bbc news data: [bbc_news_csv](https://www.kaggle.com/yufengdev/bbc-fulltext-and-category)
For the feature embedding I use sklearn's CountVectorizer and TfidfTransformer.
The TfidfTransformer returns a [Compressed Sparse Row matrix](http://scipy.github.io/devdocs/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix).
As written in the documentation, catboost supports sparse matrices.

So my problem is that, after executing the `model.fit` function the script just terminates without any errors or anything and the model does not train. 

This is my code:
```python
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer,CountVectorizer
from catboost import CatBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


df = pd.read_csv("bbc_text.csv").drop_duplicates()
df["text"] = df["text"].str.replace("  ", " ")
data = df["text"].values
label = df["category"].values

model_preproccess = Pipeline(
    [
        ("vect", CountVectorizer(min_df=0.01,),),
        ("tfidf", TfidfTransformer()),
    ]
)

model = CatBoostClassifier(logging_level="Verbose")

label_encoder = LabelEncoder()
label_enc = label_encoder.fit_transform(label)

X = model_preproccess.fit_transform(data)

model.fit(X, label_enc)
```
---
I also tried an even more simpler example which just works:
```python
import numpy as np
from catboost import CatBoostClassifier, Pool

from scipy.sparse import csr_matrix

train_data = np.random.rand(2000, 400)
train_data = csr_matrix(train_data)
train_labels = np.random.randint(0, 2, size=(2000))

model = CatBoostClassifier()

model.fit(train_data, train_labels)
```

So I don't know what the problem is and catboost just won't print any errors or indications what's wrong.

**Comment by LyzhinIvan** [comment]
Hi, @step4! This occurs because of unsorted indices in CSR matrix but CatBoost requires sorted indices. We will add check or sorting. Now you can just add `X.sort_indices()` before fit.
