### ISSUE TITLE
compiletime version 3.4 of module '_catboost' does not match runtime version 3.6

### ISSUE THREAD

**Issue by commadot** [catboost/catboost#175]
I have problem running CatBoost on Python 3.6, after running it, I got this exception:

> RuntimeWarning: compiletime version 3.4 of module '_catboost' does not match runtime version 3.6 return f(*args, **kwds)

I have Python in virtualenv and CatBoost installed here via pip:

Python version is 3.6:
`(catboost_env) $ python --version`
`Python 3.6.3`

Catboost  version is 
`(catboost_env) $ pip freeze`
`catboost==0.4.1`

This is the code:
```
pool = Pool(data, label, feature_names=head)

model = CatBoostClassifier(loss_function='MultiClass', random_seed=666,
                           od_type='Iter', od_wait=10, iterations=1)
model.fit(pool)
model.save_model('cb.model')
```

I have reinstalled catboost twice, tried with and without virtualenv, also tried it on CentOS 7, CentOS 6 and Mac OS, the same issue every time.

**Comment by annaveronika** [comment]
Is it a warning or an error?
Usually this problem is when you install catboost with some python and use with other. See https://github.com/catboost/catboost/issues/138

**Comment by annaveronika** [comment]
And please try the latest version.

**Comment by commadot** [comment]
Thank you @annaveronika  for your answer!

> Is it a warning or an error?

It is an error, because script fails after this message

> Usually this problem is when you install catboost with some python and use with other. See #138 

I am absoultely shure, that I installed catboost and run it with the same Python version.

> And please try the latest version.
```
(catboost_env) $  pip install --upgrade catboost
Collecting catboost
  Downloading catboost-0.5-cp36-none-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 84kB/s
Requirement already up-to-date: numpy in ./catboost_env/lib/python3.6/site-packages (from catboost)
Requirement already up-to-date: six in ./catboost_env/lib/python3.6/site-packages (from catboost)
Installing collected packages: catboost
  Found existing installation: catboost 0.4.1
    Uninstalling catboost-0.4.1:
      Successfully uninstalled catboost-0.4.1
Successfully installed catboost-0.5
```

```
(catboost_env) $ python cb.py
/home/igor/catboo/catboost_env/lib64/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module '_catboost' does not match runtime version 3.6
  return f(*args, **kwds)
```
After this server just reboots.

**Comment by aldanor** [comment]
Same problem.

On Python 3.6, Linux:

```sh
$ pip install catboost
Collecting catboost
  Downloading catboost-0.5-cp36-none-manylinux1_x86_64.whl (13.9MB)
Installing collected packages: catboost
Successfully installed catboost-0.5
```

```python
>>> from catboost import CatBoostRegressor
RuntimeWarning: compiletime version 3.4 of module '_catboost' does not match runtime version 3.6
```

**Comment by kizill** [comment]
Hello @aldanor, i want to reproduce your case. What linux distribution do you use?

**Comment by aldanor** [comment]
It's CentOS; with Python 3.6 through anaconda distribution.

**Comment by snovik75** [comment]
Same problem: archlinux, catboost through pip, system install of python (i.e. pacman)

**Comment by aldanor** [comment]
Any news on this? Seems like a lot of users are experiencing the same problem.

**Comment by kizill** [comment]
Sorry for the wait, i partially reproduced your problem (it crashes on `import catboost` for system python 2.7.5)
I'll try to fix this problem first, then i'll look at 3.4|3.6 problems.

**Comment by commadot** [comment]
Any news?

**Comment by annaveronika** [comment]
Should be fixed in last version.
