### ISSUE TITLE
Calculation of SHAP when there is mixture of features at tree's node

### ISSUE THREAD

**Issue by iteimouri** [catboost/catboost#1750]
Suppose I do have a train data that is a mix of categorical and numerical data. After modelling I would like to use the TreeExplainer to calculate the SHAP values for each feature. The problem I am concerned with is the way CatBoost encodes the categorical variables and the node of trees. This issue is somewhat appears on [issue 662](https://github.com/slundberg/shap/issues/662). 

From the answers one reads: "CatBoost has a special way of doing categorical splitting that (when used) essentially creates new features to split on that are not in the original set of input features. These features allow you to split whole groups of categories one way or the other. Support for these types of trees have not been added to SHAP yet." by @slundberg. 

To make this a little more clear suppose we have the following tree: 

![sample](https://user-images.githubusercontent.com/29966416/122943674-20cbf480-d36f-11eb-90c1-50041f18595e.jpg)

where you can see that the is a mixture of features at some of the nodes for instance `F1` and `F3`. Now the question is how does SHAP is being calculated if `F1` and `F3` are encoded to a combination? Does SHAP know the difference between `F1`, `F3` and the encoded combination of them? Also what if the value for one of these feature is missing? How does the tree proceed to the next nodes in CatBoost? In other words if `F1` has a value and `F3` has a missing value what happens to the encoded combination of the two feature? and consequently their SHAP values? 

Is there any worked example/tutorial on this to illustrate the matter?

**Comment by LyzhinIvan** [comment]
Hi, @iteimouri!

When we calculate SHAP inside CatBoost (if you call `model.get_feature_importance(data, type=EFstrType.ShapValues)`), we calculate SHAP for internal features firstly (union of source features and combinations), then we equally distribute combination SHAP value between its parts. 
About missing values processing you can read at our documentation https://catboost.ai/docs/concepts/algorithm-missing-values-processing.html.

**Comment by iteimouri** [comment]
Thank you @LyzhinIvan
