### ISSUE TITLE
Are the parameters in Catboost like the parameters C and gamma in SVM?

### ISSUE THREAD

**Issue by Wangpc-972** [catboost/catboost#1752]
Problem: Are the parameters in Catboost like the parameters C and gamma in SVM?
Catboost version:0.25
The parameters in SVM are like this：
```
    C : float, optional (default=1.0)
        Regularization parameter. The strength of the regularization is
        inversely proportional to C. Must be strictly positive. The penalty
        is a squared l2 penalty.

    gamma : {'scale', 'auto'} or float, optional (default='scale')
        Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.

        - if ``gamma='scale'`` (default) is passed then it uses
          1 / (n_features * X.var()) as value of gamma,
        - if 'auto', uses 1 / n_features.

        .. versionchanged:: 0.22
           The default value of ``gamma`` changed from 'auto' to 'scale'.
```
Thank you！

**Comment by ek-ak** [comment]
Hello! CatBoost has l2_leaf_reg parameter for L2 regularization. In gradient boosting trees there is no the exact analog of SVM gamma parameter, but if you need short list of parameter you could tune -- here is one https://catboost.ai/docs/concepts/parameter-tuning.html?lang=en

**Comment by Wangpc-972** [comment]
> Hello! CatBoost has l2_leaf_reg parameter for L2 regularization. In gradient boosting trees there is no the exact analog of SVM gamma parameter, but if you need short list of parameter you could tune -- here is one https://catboost.ai/docs/concepts/parameter-tuning.html?lang=en

Thank you for answering my question !!!!
