### ISSUE TITLE
I can't open catboost documentation

### ISSUE THREAD

**Issue by aceson28** [catboost/catboost#1754]
I don't know why I can't open catboost documentation about python package training parameter,
is there are some file (pdf) who tells us about anything in python package, so I can open it offline?

**Comment by andrey-khropov** [comment]
> I don't know why I can't open catboost documentation about python package training parameter,

Does it work for you now?

> is there are some file (pdf) who tells us about anything in python package, so I can open it offline?

No, unfortunately there is no documentation in a separate file. You may try to download CatBoost docs for offline viewing using some kind of web site download manager program like GetRight but it still requires that web site is available in the first place.

**Comment by aceson28** [comment]
i can open catboost Python quick start (https://catboost.ai/docs/concepts/python-quickstart.html)
usage example (https://catboost.ai/docs/concepts/python-usages-examples.html) although for example take a time and sometimes it cannot be open
but i can't open for Python Training parameter even  if only once

**Comment by Eve-Chen** [comment]
I'm experiencing similar issues, unable to access https://catboost.ai/docs. I have tried with different browsers(Chrome and Firefox) and still getting the same error: `Secure Connection Failed`.

**Comment by ul611** [comment]
I had the same ploblem. It looks like the documentation is unstable. Sometimes I need to reload the page many-many times to finally load it. I asked other people to browse it on their devices, and it also wasn't loading.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
According to https://www.site24x7.com/check-website-availability.html, catboost.ai loads in less than 2s worldwide
![image](https://user-images.githubusercontent.com/7053671/126741289-d389adfc-f328-4151-8210-1a9f6394b362.png)
