### ISSUE TITLE
[pyspark] Getting Internal CatBoost Error: "attempt to interpret non-binary feature as binary"

### ISSUE THREAD

**Issue by mrushad** [catboost/catboost#1759]
Problem: I'm getting this error when trying to fit.
```
ai.catboost.CatBoostError: catboost/libs/data/packed_binary_features.h:101: Internal CatBoost Error (contact developers for assistance): attempt to interpret non-binary feature as binary
```
Code is written in pyspark. The data is passed through a pipeline and generates the features and label columns but fails to fit CatBoostClassifier.
The code works fine on a small subset of the data.

catboost version: catboost-spark_2.3_2.11-0.26

Operating System: macOS catalina
CPU: Quad Core Intel i7

Any way to fix this error?

**Comment by andrey-khropov** [comment]
Fixed in trunk: https://github.com/catboost/catboost/commit/d91dcb0705bab03738e9c43d7cd3aabb2f3a594c. Will be released soon.

**Comment by andrey-khropov** [comment]
Deployed in release 1.0.3.
