### ISSUE TITLE
Compilation for ARM

### ISSUE THREAD

**Issue by felipehertzer** [catboost/catboost#1766]
Problem: Problems with compiling files to ARM 
catboost version: 26
Operating System: MacOS 11.4
CPU: Intel i7 2.8Ghz

**Details:**

I'm trying to compile the project on macos for an arm processor but I have found an error.

The first problem I am experiencing is in the catboost/build/platform/lld/ya.make file where two files are not mapped:
DECLARE_EXTERNAL_RESOURCE(LLD_ROOT sbr: 2203438202)
DECLARE_EXTERNAL_RESOURCE(LLD_ROOT sbr:2203437050)

**Is it possible to please map or update sbr 2203438202 and 2203437050 = in the catboost/build/mapping.conf.json file?**

In trying to debug the mapping problems, I changed the catboost/build/platform/lld/ya.make file to other versions of [darwin-arm64](https://storage.mds.yandex.net/get-devtools-opensource/471749/2234869115) but then ran into another issue in the catboost/build/platform/lld/ya.make file.

In LDFLAGS("-fuse-ld=$LLD_ROOT_RESOURCE_GLOBAL/ld" "-Wl,--no -rosegment") it looks for 'ld' file, but that file doesn't exist in the [darwin-arm64](https://storage.mds.yandex.net/get-devtools-opensource/471749/2234869115) package. To fix this I also tried switching to the 'ld' that comes with macos but it doesn't have support for the parameter --sysroot and threw an error as a result.

**Comment by gugaevkirill** [comment]
I also faced a compilation problem:
`../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/opt/homebrew/Caskroom/miniforge/base/envs/corrily2/bin/python3-config --target-platform arm64`

leads to that output (with error):
```
Downloading https://storage.mds.yandex.net/get-devtools-opensource/479623/d21ddef05b1cdb6e2842e412ee762536 [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/2311617300 [......................................] OK
Unsupported host platforms ARM64-DARWIN-X86_64 for tool c++, use one of CLANG10-DARWIN-X86_64, CLANG10-LINUX-X86_64, CLANG11-DARWIN-ARM64, CLANG11-DARWIN-X86_64, CLANG11-LINUX-PPC64LE, CLANG11-LINUX-X86_64, CLANG11-WIN-X86_64, CLANG12-DARWIN-ARM64, CLANG12-DARWIN-X86_64, CLANG12-LINUX-PPC64LE, CLANG12-LINUX-X86_64, CLANG12-WIN-X86_64, CLANG5-DARWIN-X86_64, CLANG5-LINUX-X86_64, CLANG50-DARWIN-X86_64, CLANG50-LINUX-X86_64, CLANG7-DARWIN-X86_64, CLANG7-LINUX-PPC64LE, CLANG7-LINUX-X86_64, CLANG7-WIN-X86_64, CLANG8-DARWIN-X86_64, CLANG8-LINUX-X86_64, CLANG9-DARWIN-X86_64, CLANG9-LINUX-X86_64, DEFAULT-DARWIN-ARM64, DEFAULT-DARWIN-X86_64, DEFAULT-LINUX-PPC64LE, DEFAULT-LINUX-X86_64, DEFAULT-WIN-X86_64, GCC102-ARM-NONE-EABI-LINUX-X86_64, GCC8-DARWIN-X86_64, GCC8-LINUX-X86_64, GCC82-DARWIN-X86_64, GCC82-LINUX-X86_64, MSVC2019-LINUX-X86_64, MSVC2019-WIN-X86_64, XCODE_11_1-DARWIN-X86_64, XCODE_12_1-DARWIN-X86_64
```

**Comment by kizill** [comment]
Everything should work now, just use command
`./ya make -r --target-platform DEFAULT-DARWIN-ARM64 catboost/app/` for CLI build. Tested it on master, works just fine :)
