### ISSUE TITLE
value error: the key pairwise is not defined in _get_tags() for the class catboostclassifier.

### ISSUE THREAD

**Issue by FrancisGatumuta** [catboost/catboost#1769]
Problem:
catboost version:
Operating System:
CPU:
# GPU:

**Comment by grag90** [comment]
Could you provide a code example with this bug?

**Comment by andrey-khropov** [comment]
No information to reproduce has been provided for a long time, so I'm closing this issue. Feel free to reopen it if there's a relevant example to repoduce the issue on.
