### ISSUE TITLE
allow_writing_files error

### ISSUE THREAD

**Issue by cooltyn** [catboost/catboost#177]
In python package v0.5 you removed or renamed training option `allow_writing_files`, but there is nothing in documentation about it.

> File "C:\Python36-64\lib\site-packages\catboost\core.py", line 1240, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "C:\Python36-64\lib\site-packages\catboost\core.py", line 485, in __init__
    super(CatBoost, self).__init__(params)
  File "_catboost.pyx", line 859, in _catboost._CatBoostBase.__init__
  File "_catboost.pyx", line 904, in _catboost._CatBoostBase._check_train_params
_catboost.CatboostError: st/catboost/libs/options/plain_options_helper.cpp:203: Error: unknown option allow_writing_files with value false

**Comment by Noxoomo** [comment]
Sorry, we missed this option after merging of CPU/GPU binaries. We will fix it in the next version (for those, who build from source is will be fixed after next code sync)

**Comment by annaveronika** [comment]
fixed in last version
