### ISSUE TITLE
How to archive the numerical features converted from categorical features by catboost?

### ISSUE THREAD

**Issue by IncubatorShokuhou** [catboost/catboost#1770]
How to archive the numerical features converted from categorical features by catboost? 
I want to get these features, and try to use these feature to train a new model with other algorithms.

**Comment by LyzhinIvan** [comment]
It is not possible to extract these features from CatBoost model, but you can try [this library](https://contrib.scikit-learn.org/category_encoders/catboost.html) which encodes categorical features like CatBoost.
