### ISSUE TITLE
CatBoost Pool Object

### ISSUE THREAD

**Issue by jamesawhite465** [catboost/catboost#1771]
How can process the CatBoost Pool object. I am trying to use the saved model and the pooled ( sample for prediction) data object and LIME together. The problem is LIME doesn’t play nice with Pooled data and I want to keep the encoding consistent with my previously encoded training data.

**Comment by LyzhinIvan** [comment]
As I understand, LIME uses raw features without any model-specific encoding. So you can use LIME without Pool. If your dataset contains numerical features only then your can get features from Pool by [get_features](https://catboost.ai/docs/concepts/python-reference_pool_get_features.html) method.

**Comment by Alanapiereid** [comment]
It doesn't work for me either.

I have a custom CatBoost classifier trained using Pool.

If I pass my data into LIME using Pool I get a type error:

```
from catboost import Pool
import pandas as pd

cat = CatBoostPipe().load()

sent = 'The allegations include misuse of funds and entitlements, misuse of staff, workplace bullying,intimidation, verbal abuse and harassment.'

df = pd.DataFrame([sent], columns=['Content'])

data = Pool(data=df[['Content']], text_features=['Content'])


class_names = list(set(y_train))
explainer = LimeTextExplainer(class_names=class_names)
exp = explainer.explain_instance(data, cat.predict_proba, num_features=8, top_labels=3, labels=[0, 0])
```
_____________________________________________________________________________________________________________________
```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_3652/3127332123.py in <module>
     33 class_names = list(set(y_train))
     34 explainer = LimeTextExplainer(class_names=class_names)
---> 35 exp = explainer.explain_instance(data, cat.predict_proba, num_features=8, top_labels=3, labels=[0, 0])
     36 print(exp)
     37 #exp.show_in_notebook(text=sent, labels=(0,))

~/dev_env/lib/python3.8/site-packages/lime/lime_text.py in explain_instance(self, text_instance, classifier_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    407             text_instance, bow=self.bow, mask_string=self.mask_string)
    408                           if self.char_level else
--> 409                           IndexedString(text_instance, bow=self.bow,
    410                                         split_expression=self.split_expression,
    411                                         mask_string=self.mask_string))

~/dev_env/lib/python3.8/site-packages/lime/lime_text.py in __init__(self, raw_string, split_expression, bow, mask_string)
    112             # the separator character from the split results.
    113             splitter = re.compile(r'(%s)|$' % split_expression)
--> 114             self.as_list = [s for s in splitter.split(self.raw) if s]
    115             non_word = splitter.match
    116 

TypeError: expected string or bytes-like object
```

If I pass a raw string to LIME I get an error from CatBoost:

`exp = explainer.explain_instance(sent, cat.predict_proba, num_features=8, top_labels=3, labels=[0, 0])`
_________________________________________________
CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=1]=" allegations include   funds and entitlements,   ,  bullying,intimidation and .": Cannot convert 'b' allegations include   funds and entitlements,   ,  bullying,intimidation and .'' to float
