### ISSUE TITLE
Predict with Virtual Ensembl does nothing in R

### ISSUE THREAD

**Issue by ThomasWolf0701** [catboost/catboost#1773]
Problem:

After training the model

library(catboost)

train_pool_path <- system.file("extdata", "adult_train.1000", package = "catboost")
test_pool_path <- system.file("extdata", "adult_test.1000", package = "catboost")
cd_path <- system.file("extdata", "adult.cd", package = "catboost")
train_pool <- catboost.load_pool(train_pool_path, column_description = cd_path)
test_pool <- catboost.load_pool(test_pool_path, column_description = cd_path)

fit_params <- list(
  iterations = 100,
  loss_function = 'RMSE',
  #ignored_features = c(4, 9),
  border_count = 32,
  depth = 5,
  learning_rate = 0.03,
  l2_leaf_reg = 3.5,
  train_dir = 'train_dir')
model <- catboost.train(train_pool,params =  fit_params)

test = catboost.predict(model,test_pool,prediction_type = 'VirtEnsembles')

I try to predict using Virt Ensembles but just get a normal prediction no distribution of predictions or anything like that:

> length(test)
[1] 1000

catboost version: 0.26
Operating System: Windows
CPU: Intel
# GPU:

**Comment by LyzhinIvan** [comment]
Hi, @ThomasWolf0701!

VirtEnsembles predict is not supported yet in R package. We will add it soon.

**Comment by kizill** [comment]
Fixed in 0.26.1
