### ISSUE TITLE
@Evgueni-Petrov-aka-espetrov I do not think the question has been answered fully. In the doc it also says that there is also permutation choosing the tree structure. Also, it is not clear whether we have to provide a datetime column or not. Could you be more specific?

### ISSUE THREAD

**Issue by renzeya** [catboost/catboost#1774]
@Evgueni-Petrov-aka-espetrov I do not think the question has been answered fully. In the doc it also says that there is also permutation choosing the tree structure. Also, it is not clear whether we have to provide a datetime column or not. Could you be more specific?

_Originally posted by @jcrichard in https://github.com/catboost/catboost/issues/1076#issuecomment-735259919_

**Comment by renzeya** [comment]
same question

**Comment by LyzhinIvan** [comment]
I've answered in the parent issue. https://github.com/catboost/catboost/issues/1076#issuecomment-882353310
