### ISSUE TITLE
Additional arguments to user-defined ranking metric

### ISSUE THREAD

**Issue by Sushentsev** [catboost/catboost#1777]
I want to use custom user-defined metric for validation. I found [this](https://catboost.ai/docs/concepts/python-usages-examples.html#custom-loss-function-eval-metric) very useful, but in order to calculate custom ranking metric I needed "group_id" data to "evaluate" call. Can I do this?

**Comment by LyzhinIvan** [comment]
No, it is not possible now and not planned.
