### ISSUE TITLE
New Metric Request

### ISSUE THREAD

**Issue by cmdkev** [catboost/catboost#1778]
It would be great to have FBeta, F2, or F0.5 metrics to be implemented without the need for a custom metric class defined by user.

catboost version: 0.26

**Comment by LyzhinIvan** [comment]
This is a good issue for contributing. It is pretty easy to implement it in the core of CatBoost. We will be glad to get your pull request.

**Comment by zikpefu** [comment]
Has this been implemented yet? I would like to take a crack at it.

**Comment by cmdkev** [comment]
Nope, I haven't had a chance to look into it. Not sure if its been implemented since I last used this library though. @zikpefu

**Comment by zikpefu** [comment]
@LyzhinIvan Instead of Fbeta could I do F2 and/or F0.5 instead?

**Comment by LyzhinIvan** [comment]
> @LyzhinIvan Instead of Fbeta could I do F2 and/or F0.5 instead or were these added as well?

It is not necessary, because Fbeta includes these cases (F:beta=2 and F:beta=0.5 respectively).

**Comment by LyzhinIvan** [comment]
Implemented in #2023. Will be available in the next release.
