### ISSUE TITLE
Is there a way to input sample weights to "select_features" method?

### ISSUE THREAD

**Issue by shivamtundele** [catboost/catboost#1779]
Problem: Is there a way to input sample weights to "select_features" method? I see no arguments for that. 
catboost version: 0.26
Operating System: AWS RHEL

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Sample weights may be passed to select_features inside CatBoost.Pool object.
Here is the doc https://catboost.ai/docs/concepts/python-reference_pool.html
