### ISSUE TITLE
Execution Fail with message "Killed: 9" on macOS

### ISSUE THREAD

**Issue by MasatoTakahashi** [catboost/catboost#178]
After training for a regression problem with long iteration (iterations = 150000), 
I got the message "Killed: 9" and the process was halted.

I'd tried both v0.4.1 and v0.5 with following R environment.
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer        

With shorter iteration, there's no such kind of error.

![untitled 2 jpeg](https://user-images.githubusercontent.com/3676961/33521772-f7263e50-d81e-11e7-944d-5520b62e9d0a.jpeg)

**Comment by annaveronika** [comment]
Do you have categorical features in your dataset?

**Comment by MasatoTakahashi** [comment]
Yes, the data contains some categorical features.
Unfortunately, the data cannot be distributed due to containing sensitive data.

By the way, I noticed that the process consume huge memory space (more than 30GB) before the failure occurred and also consumed almost all my mac cash memory.
That might be the result why the trouble happened.

**Comment by kizill** [comment]
When using catboost in python or R environment we build and store model in memory, and model could contain lots of CTR tables for lots of unique feature combination that algorithm can select during 150k iterations. Currently for relatively big datsets with cat features i recommend you to use CLI version
