### ISSUE TITLE
R installation in MAC OSX

### ISSUE THREAD

**Issue by Lrincones** [catboost/catboost#1781]
Problem: How to" Open the catboost/catboost/R-package directory from the local copy of the CatBoost repository
catboost version:0.26
Operating System:MAC OS Big Sur version 11.5
CPU: 3.1 GHz Dual-Core Intel Core i7
# GPU:
I installed the files are in the directory. However what does it mean the step 3
Open the catboost/catboost/R-package directory from the local copy of the CatBoost repository.
Apologies if it is a simple question, but what is the expected action at step3.

Thanks for your help

**Comment by Glemhel** [comment]
Hello!
You should use your terminal to install catboost this way.

1. Open your terminal and go to the folder you downloaded. You can see[ how to use 'cd' command](https://askubuntu.com/questions/232442/how-do-i-navigate-between-directories-in-terminal) to navigate in terminal.
When you do `ls -l` your terminal and see catboost folder, you can simply do `cd catboost/catboost/R-package` to achieve step 3 results.
2. In that folder(R-package), create file, for example 'tmp.R', and paste 2 code lines from step 4 into that file.
3. From terminal again, run the following: `Rscript tmp.R` or `R -f tmp.R`. It might take time to do the stuff, be patient :)

Feel free to ask any questions in case of problems!

**Comment by Lrincones** [comment]
Hi Glemhel  many thanks for your help. I follow the tips, I used "R -f tmp.R" at the terminal.
 Unfortunately I got this message.
> install.packages('devtools')
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted.
 
Sorry for not being able to worked it out :(   I like learning and be patient :)  in Italian Piano Piano va sano e va lontano :)

**Comment by Glemhel** [comment]
Sorry, I should have foreseen this problem.
Try the first line as `install.packages('devtools', repos='http://cran.us.r-project.org')`.
The problem is that one has to choose a source to download package from, but in `R -f` this could not be done.

Alternatively, if that does not work out, you could try open R console by simply typing `R`, and then execute commands line by line manually. The first line will ask you to choose source, choose any.
Good luck!

**Comment by Lrincones** [comment]
Hi Glemhel
Thanks for your help, **it did work** using the update for the first line. I ran the quick start demo and it worked.
Now the fun part, learning with the tutorials and applying it. :)
Again many thanks. 
PS: Apologies for having break your sunday peace.

**Comment by Lrincones** [comment]
I will close this issue since the installation worked. I would open a new one if I have any issues with the examples. Again thanks for the support

**Comment by Glemhel** [comment]
No problem, Lrincones, glad that it worked!
We will update R installation guide page so that such problems won't happen.

Wish you good and productive learning! Feel free to contact.
