### ISSUE TITLE
Unable to install Catboost_spark using pip

### ISSUE THREAD

**Issue by risesh** [catboost/catboost#1786]
Problem: Unable to install Catboost_spark using pip
catboost version: 0.26
Operating System: Linux

![image](https://user-images.githubusercontent.com/34802001/127274608-13d7a460-8f91-4d23-9fb4-560dfb4e6e5b.png)

**Comment by andrey-khropov** [comment]
CatBoost for Apache Spark is not distributed using pip but using Maven artifacts, you should use it in PySpark like that:

https://github.com/catboost/catboost/tree/master/catboost/spark/catboost4j-spark#python-pyspark

**Comment by ArijitSinghEDA** [comment]
@andrey-khropov  I followed the steps given in the document but I get the same error. It is mentioned that it is not supported for windows yet. Does it extend to WSL as well? I thought WSL is a linux enviorement so it should not be a problem

**Comment by andrey-khropov** [comment]
> Does it extend to WSL as well? I thought WSL is a linux environment so it should not be a problem

You are right, this limitation does not extend to WSL. CatBoost for Apache Spark should work in WSL (although I haven't checked it personally). If you install according [to the instructions](https://catboost.ai/en/docs/concepts/spark-installation) and have problems, please, create a separate GitHub issue.
