### ISSUE TITLE
Internal One Hot Encoder vs external one hot encoder (give better score) (Binary cls)

### ISSUE THREAD

**Issue by nurrochmanmuhammad** [catboost/catboost#1788]
Problem: Why internal One Hot Encoder vs external one hot encoder (give better score)? This is so confusing, why internal function give bad performance rather than processed with external encoder in sklearn.
catboost version: 0.26
Operating System: linux
CPU: colab
# GPU:

**Comment by ek-ak** [comment]
Hello! Please provide a reproducible example so we could see why this is happening.

**Comment by nurrochmanmuhammad** [comment]
---------------------------------------------------------------------Train-Test Prep.------------------------------------------------------------------------------

X_train=df[df.dt_id<='2021-01-31'][[features_columns]]
X_test=df[df.dt_id=='2021-02-28'][[features_columns]]

y_train=df[df.dt_id<='2021-01-31']['is_churn']
y_test=df[df.dt_id=='2021-02-28']['is_churn']

categ=X_train.select_dtypes(include='object').columns.tolist()#categorical col
nume=X_train.select_dtypes(include=float).columns.tolist()

X_train[categ]=X_train[categ].fillna('unk').astype('str')
X_test[categ]=X_test[categ].fillna('unk').astype('str')

X_train[nume]=X_train[nume].fillna(0)
X_test[nume]=X_test[nume].fillna(0)

----------------------------------------------------------------Internal OneHot----------------------------------------------------------------------------------
model=CatBoostClassifier(random_state=44,cat_features=categ,early_stopping_rounds=5,iterations=200,one_hot_max_size=10000)
model.fit(X_train,y_train)

results:
Prec. :0.647928
Recall:0.785761

----------------------------------------------------------------Sklearn OneHot-----------------------------------------------------------------------------------
numerical_transformer = SimpleImputer(strategy='constant', fill_value=0)

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant',fill_value='unk')),
    ('onehot', OneHotEncoder())
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, nume),
        ('cat', categorical_transformer, categ)
    ])

model=CatBoostClassifier(random_state=44,early_stopping_rounds=5,iterations=200)

pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', model)])

pipeline.fit(X_train, y_train)

results:
Prec. :0.759894
Recall:0.850344

**Comment by ek-ak** [comment]
Hello! This script is not reproducible (cause there is no data). Nevertheless are you sure that you specified enough iterations to train the model, was early stopping criteria triggered? Probably your model is just undertrained.

**Comment by nurrochmanmuhammad** [comment]
both stopped at max iterations. sorry , but the data was confidential.
internal onehot:
199:	learn: 0.0365004	total: 1m 4s	remaining: 0us

external onehot:
199:	learn: 0.0365690	total: 1m 4s	remaining: 0us

**Comment by ek-ak** [comment]
We recommend not to use such big  `one_hot_max_size`, ctrs will used for cat features with a bigger number of different values (https://catboost.ai/docs/features/categorical-features.html).
Regardless of that could you please set bigger amount of iterations like 5000 to trigger early_stopping?  "both stopped at max iterations"  means models are undertrained.

**Comment by nurrochmanmuhammad** [comment]
yes one_hot_max_size set to 10000 already surpass maximum number of possible onehot. I'll try, but with this early results already give enough question.
