### ISSUE TITLE
SetPredictionType in shared .so library is hidden

### ISSUE THREAD

**Issue by pavelgur** [catboost/catboost#1789]
Problem:
It seems to me that function
[CATBOOST_API bool SetPredictionType(ModelCalcerHandle* modelHandle, enum EApiPredictionType predictionType);](https://github.com/catboost/catboost/blob/5cfe2cb29771e93150e4534252186560568aa5d0/catboost/libs/model_interface/c_api.h#L100)
is marked as hidden (= cannot be used from outside the library). Here's nm utility output, for comparison:
```
$ nm libcatboostmodel.so | grep LoadFullModelFromFile
00000000004c31b0 T LoadFullModelFromFile
$ nm libcatboostmodel.so | grep SetPredictionType
00000000004c38e0 t SetPredictionType
```
The difference is "t" vs "T". Linker [doesn't export](https://stackoverflow.com/a/37534357/12804012) "t" to be used in outside the library.
catboost version: 0.26
Operating System: Linux
CPU: i7

**Comment by kizill** [comment]
Fixed in https://github.com/catboost/catboost/commit/89a0af0f00dfe69b47b669f2a8dcbe5b15be5c82#diff-89619bcc69cc695977e236d100eb0f6cb2667f60edfb04da4d684236f9810834, did you try to build it from master?

**Comment by pavelgur** [comment]
Not yet. OK let's consider it fixed then :)
