### ISSUE TITLE
Magic loss AUC

### ISSUE THREAD

**Issue by nnnet** [catboost/catboost#179]
Hi!
Ubuntu 16.04
catboost.__version__ = '0.5'

catboost.CatBoostClassifier(loss_function='AUC', learning_rate=0.1)
return
_catboost.CatboostError: catboost/libs/options/catboost_options.cpp:70: Unknown loss function AUC

now type auc lowercase

catboost.CatBoostClassifier(loss_function='auc', learning_rate=0.1)
return
_catboost.CatboostError: e/0001e0/catboost/libs/options/enums.h_serialized.cpp:1812: Key 'auc' not found in enum. Valid options are: 'Logloss', 'CrossEntropy', 'RMSE', 'MAE', 'Quantile', 'LogLinQuantile', 'MAPE', 'Poisson', 'QueryRMSE', 'MultiClass', 'MultiClassOneVsAll', 'PairLogit', 'R2', 'AUC', 'Accuracy', 'Precision', 'Recall', 'F1', 'TotalF1', 'MCC', 'PairAccuracy', 'Custom', 'UserPerObjErr', 'UserQuerywiseErr'. 

See - 'AUC' exist
Why not work in first case ?

Thanks!

**Comment by Noxoomo** [comment]
Hi!

Loss function (or objective function) is function that could be optimized by catboost.
We also have several metric-functions like AUC, F-measure, precision, etc. This functions can't be optimized directly, but could be computed to evaluate quality of model obtained by optimization of some loss-function (e.g. for GBDT one use logloss to learn classifier and then use AUC/Precission/Recall to evaluate quality of model).

**Comment by nnnet** [comment]
could you set an example of the correct code using AUC ?
Thanks!

**Comment by Noxoomo** [comment]
catboost.CatBoostClassifier(loss_function='Logloss',eval_metric='AUC', learning_rate=0.1) will optimize  Logloss as objective and print AUC-scores in stdout during learning

**Comment by annaveronika** [comment]
The main reason to use eval_metric is to use overfitting detector and use_best_model on some other metric than the optimized one

**Comment by JoshuaC3** [comment]
Looks like I am getting the exact same problem:

```

data = cat.Pool(train.drop('cible', axis=1), train.cible, cat_features=cat_feats_int,)

params = {
    'loss_function': 'CrossEntropy',
    'custom_metric': ['Logloss', 'AUC'],
    'eval_metric': 'AUC'
}

results = cat.cv(data, params=params, fold_count=5, plot=True,
                 early_stopping_rounds=15, metric_period=10,)
```

returns


`CatboostError: util/generic/hash.h:1652: Key not found in hashtable: AUC`

**Comment by annaveronika** [comment]
@JoshuaC3 Is this the 0.10.3 version? Could you check with the latest version?

**Comment by JoshuaC3** [comment]
Rolling back to 0.9.1.1 seems to work for now.

**Comment by DurojaiyeAbisoye** [comment]
> 

Was this ever resolved beyond rolling back?  Currently facing the same issue.
`Catboost version : '1.1.1'`

Code: 
```
import sklearn.datasets
import catboost as cb

X, y = sklearn.datasets.load_iris(return_X_y=True, as_frame=True)
data = cb.Pool(data = X, label=y)

param = {
    "objective": "MultiClassOneVsAll",
     "eval_metric": "AUC",
     'random_state' : 34,
     'max_depth' : 10,
      'learning_rate' : 0.1
}

history = cb.cv(params=param, num_boost_round=15,
                pool=data, nfold=5, stratified=True, plot=False) 

```


Error message : `CatBoostError: util/generic/hash_table.cpp:50: Key not found in hashtable: AUC`

It works when I set `'eval_metric'` to  `'Accuracy'` or `'TotalF1'`

**Comment by andrey-khropov** [comment]
> Looks like I am getting the exact same problem:
> 
> ```
> 
> data = cat.Pool(train.drop('cible', axis=1), train.cible, cat_features=cat_feats_int,)
> 
> params = {
>     'loss_function': 'CrossEntropy',
>     'custom_metric': ['Logloss', 'AUC'],
>     'eval_metric': 'AUC'
> }
> 
> results = cat.cv(data, params=params, fold_count=5, plot=True,
>                  early_stopping_rounds=15, metric_period=10,)
> ```
> 
> returns
> 
> `CatboostError: util/generic/hash.h:1652: Key not found in hashtable: AUC`

This is a separate issue. I've created https://github.com/catboost/catboost/issues/2758 for it.
