### ISSUE TITLE
.copy() on model not working properly

### ISSUE THREAD

**Issue by diditforlulz273** [catboost/catboost#1793]
Problem: .copy() on a model not working properly - after performing a copy some evaluation metrics get lost.
catboost version: 0.25.1
Operating System: Ubuntu 20.04
CPU: Threadripper 1950X
Minimal example:

from catboost import CatBoostClassifier, Pool

train_data = [[0, 3],
              [4, 1],
              [8, 1],
              [9, 1]]

train_labels = [0, 0, 1, 1]

eval_data = [[2, 1],
             [3, 1],
             [9, 0],
             [5, 3]]

eval_labels = [0, 1, 1, 0]

eval_dataset = Pool(eval_data,
                    eval_labels)

model = CatBoostClassifier(learning_rate=0.03,
                           custom_metric=['Logloss',
                                          'AUC:hints=skip_train~false'])

model.fit(train_data,
          train_labels,
          eval_set=eval_dataset,
          verbose=False)

print(model.best_score_)
print(model.evals_result_)

model2 = model.copy()
print(model2.best_score_)
print(model2.evals_result_)

**Comment by sakvaua** [comment]
Did you manage to overcome this? I tried both copy method and copy.deepcopy and nether one copies scores.

**Comment by diditforlulz273** [comment]
nope, still buggy

**Comment by andrey-khropov** [comment]
Fixed in CatBoost 1.2.3
