### ISSUE TITLE
An active CatBoost worker is already present in the current process after previous start failure

### ISSUE THREAD

**Issue by andrey-khropov** [catboost/catboost#1795]
catboost version: 0.26

**Comment by kizill** [comment]
Fixed in 0.26.1

**Comment by trover97** [comment]
Hello everyone!
I encountered this problem. I'm running catboost-spark on cloudera hadoop cluster (CDH). I don't have internet on this machine. I'm using common tabular data without categorical features (174, 25167),  (filna(-1)), DoubleType
Spark_version==2.4.0
Scala==2.11.12
Cluster with 5 nodes 16 cores on each node
Examples and driver stack trace : 
[code_example.txt](https://github.com/catboost/catboost/files/7972363/code_example.txt)
[error.txt](https://github.com/catboost/catboost/files/7972095/error.txt)
[spark_session.txt](https://github.com/catboost/catboost/files/7972096/spark_session.txt)
