### ISSUE TITLE
Error loading model from file (CatBoostError: catboost/libs/model/model.cpp:1153: Incorrect model file descriptor)

### ISSUE THREAD

**Issue by giovane-silva** [catboost/catboost#1797]
Problem: I'm running into this error message when I try to load my classifier from a file. It was working just fine until about 2 hours ago. It's in cbm format and dumped to file 2 days ago, using save_model function. There was no change in either file or environment in the mean time.
`model = cb.CatBoostClassifier()`
`model.load_model(file_name)`
Which returns the aforementioned error message: 

> CatBoostError: catboost/libs/model/model.cpp:1153: Incorrect model file descriptor

catboost version: 0.26
Operating System: Linux

**Comment by rbdm-qnt** [comment]
> Problem: I'm running into this error message when I try to load my classifier from a file. It was working just fine until about 2 hours ago. It's in cbm format and dumped to file 2 days ago, using save_model function. There was no change in either file or environment in the mean time. `model = cb.CatBoostClassifier()` `model.load_model(file_name)` Which returns the aforementioned error message:
> 
> > CatBoostError: catboost/libs/model/model.cpp:1153: Incorrect model file descriptor
> 
> catboost version: 0.26 Operating System: Linux

Were you able to solve this? Facing the same problem
