### ISSUE TITLE
handling of unseen categorical values

### ISSUE THREAD

**Issue by geoHeil** [catboost/catboost#18]
How are categorical values handles which were previously unseen in training?
What if there were 100 features and 50 categorical with let's assume 20 unseen features - is it possible to create a worse but still usable prediction from the remaining features?

**Comment by annaveronika** [comment]
The previously unseen values of categorical features is an often situation on practice.
CatBoost deels with it successfully using several approaches. There are several types of statistics that we calculate on categorical features. For those who uses target values, if the value is not seen a "prior" will be used. And for others we will also use information about count of appearances of this value (even if it was not seen in train, we can count this feature in test). Plus one-hot endcoding can be used.
You can read about it here
https://tech.yandex.com/catboost/doc/dg/concepts/algorithm-main-stages_cat-to-numberic-docpage/

**Comment by annaveronika** [comment]
Ok, I think I answered the question, so I'm closing the issue.  You should try it on your data, it should work well!

**Comment by geoHeil** [comment]
@annaveronika do I understand correctly that the prior basically translates to most frequent imputation? And that cat boost automatically infers it?

**Comment by annaveronika** [comment]
In current implementation prior is a constant value. We enumerate through several different priors when we are selecting the split. You can also pass your own prior as a parameter, if you think it will work better.
Default priors are 0, 0.5, 1

**Comment by Pascal-Iv** [comment]
Hey, 
you said 
"count of appearances of this value  [...]  count this feature in test"
Doesn't that introduce target leakage?  How would you do this in a product, online environment?

**Comment by Cheburum** [comment]
@annaveronika 
"even if it was not seen in train, we can count this feature in test"

Yes, if I have a new categorical value(not seen in train set), and I have only countInClass and totalCount values for this category, In theory, I can use it for prediction.

But how can it be made technically using CatBoost? How can I feed model with countInClass and totalCount for new cat value not seen in train set?
