### ISSUE TITLE
Feature request: --tree-count-limit option for feature importance

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#180]
Looks like "fstr" takes into account all trees in the model. It is good only with --use-best-model flag.

**Comment by annaveronika** [comment]
Ok, we’ll add it.

**Comment by annaveronika** [comment]
We added model.shrink functionality. I think this should be enough for this functionality, so closing the issue.

**Comment by khrisanfov** [comment]
@annaveronika Hi! Actually I found other solution. I can load a model in R then shrink it by best iteration and get feature importance, it works perfect.
