### ISSUE TITLE
Potential SEGV in TZeroCopyEvaluator::SetModelPtr

### ISSUE THREAD

**Issue by kazeevn** [catboost/catboost#1809]
Perhaps it is better to first check whether `ObliviousTrees == nullptr` before dereferencing it, i.e. if the conditional on [line 77](https://github.com/catboost/catboost/blob/master/catboost/libs/standalone_evaluator/evaluator.cpp#L77) is ever true, it will never be reached, as there will be a SEGV on [line 75](https://github.com/catboost/catboost/blob/master/catboost/libs/standalone_evaluator/evaluator.cpp#L75).

Credit to [Gerhard Raven@CERN](https://gitlab.cern.ch/lhcb/Rec/-/merge_requests/2511#note_4721553)

**Comment by kizill** [comment]
Fixed in master, thank you for noticing a bug :)
