### ISSUE TITLE
Bug in catboost.train() function in Linux-R package, version 0.26.1

### ISSUE THREAD

**Issue by nlistat** [catboost/catboost#1810]
Problem: 
There is a bug in Linux-R package, version 0.26.1, the learn_pool is missing in the catboost.train() function.

The correct code should be: 

` model$feature_importances <- catboost.get_featire_importance(model, learn_pool)
  rownames(model$feature_importance) <- colnames(learn_pool
`

catboost version: 0.26.1 (Linux-R)
Operating System: Linux

(A screenshot of catboost.train() function from my linux computer is attached)

![Linux_catboosttrain_bug](https://user-images.githubusercontent.com/50334522/129554810-b7088a89-1e01-4d8d-95fb-1bfce71bfc6f.png)

**Comment by nlistat** [comment]
The catboost.train() function works well in Windows-R package, version 0.26.1.

**Comment by nlistat** [comment]
In the linux computer, when I called catboost.train() function in R with following code
` catboost.train(train_pool, test_pool, fit_params)`

There was an error message as shown below:

![Catboost_ranl_error](https://user-images.githubusercontent.com/50334522/129702025-c6bff079-9cf9-4200-8468-72653dc96e9c.png)

**Comment by kizill** [comment]
I guess there could be some mixed-state installation on your Linux machine. Can you please try to fully uninstall catboost and then install it from scratch?

**Comment by nlistat** [comment]
Before I reported this error on github, I fully uninstalled catboost and reinstalled it on linux computer.
For installation, I downloaded the released version catboost-R-Linux-0.26.1.tgz from the catboost release page and then installed it in R.
However the error happened again after reinstallation.

**Comment by kizill** [comment]
We've reproduced your issue are preparing a fix, thank you!

**Comment by kizill** [comment]
Fixed in 131c37264850b8020e627c018084982b14b5d6ab
