### ISSUE TITLE
CatBoostError: You can't change params of fitted model.

### ISSUE THREAD

**Issue by shrey10926** [catboost/catboost#1821]
Problem: Can't perform hyperparameter tuning (using Optuna)
catboost version: 0.26.1
Operating System: Windows 10
CPU: i5-11th gen
# GPU: Intel Iris Graphics 

I have the following Optuna code:-

`def objective(trial):`
    
    model__iterations = trial.suggest_int('model__iterations', 1000, 5000)`
    model__learning_rate = trial.suggest_float('model__learning_rate', 0.01, 0.3, log = True)`
    model__depth = trial.suggest_int('model__depth', 2, 15)`
    model__subsample = trial.suggest_float('model__subsample', 0.1, 1.0)`
    model__random_strength = trial.suggest_uniform('model__random_strength', 10, 50)`
    model__l2_leaf_reg = trial.suggest_float('model__l2_leaf_reg', 3.0, 25.0)`
    
    params = {'model__iterations' : model__iterations,`
              'model__learning_rate' : model__learning_rate,` 
              'model__depth' : model__depth,`
              'model__subsample' : model__subsample,`
              'model__random_strength' : model__random_strength,` 
              'model__l2_leaf_reg' : model__l2_leaf_reg}`
                  
    pipe.set_params(**params)
    pipe.fit(train_x, train_y)
    pred = pipe.predict(test_x)`
    
    return np.sqrt(mean_squared_error(test_y, pred))
    
`lgbm_study = optuna.create_study(direction = 'minimize')`
`lgbm_study.optimize(objective, n_trials = 10)`

This gives the following error:- 

`[I 2021-08-27 10:53:58,923] Trial 0 finished with value: 0.7712473244375585 and parameters: {'model__iterations': 4655, 'model__learning_rate': 0.2280653015081744, 'model__depth': 13, 'model__subsample': 0.14991535972272607, 'model__random_strength': 13.758919259517874, 'model__l2_leaf_reg': 7.524751747488633}. Best is trial 0 with value: 0.7712473244375585.
[W 2021-08-27 10:53:58,926] Trial 1 failed because of the following error: CatBoostError("You can't change params of fitted model.")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-11-795fccfe2879>", line 19, in objective
    pipe.set_params(**params)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/pipeline.py", line 141, in set_params
    self._set_params('steps', **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/metaestimators.py", line 53, in _set_params
    super().set_params(**params)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/base.py", line 261, in set_params
    valid_params[key].set_params(**sub_params)
  File "/opt/conda/lib/python3.7/site-packages/catboost/core.py", line 3059, in set_params
    raise CatBoostError("You can't change params of fitted model.")
_catboost.CatBoostError: You can't change params of fitted model.
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-11-795fccfe2879> in <module>
     24 
     25 lgbm_study = optuna.create_study(direction = 'minimize')
---> 26 lgbm_study.optimize(objective, n_trials = 10)
     27 
     28 lgbm_study.best_params

/opt/conda/lib/python3.7/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    408             callbacks=callbacks,
    409             gc_after_trial=gc_after_trial,
--> 410             show_progress_bar=show_progress_bar,
    411         )
    412 

/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     73                 reseed_sampler_rng=False,
     74                 time_start=None,
---> 75                 progress_bar=progress_bar,
     76             )
     77         else:

/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    160 
    161         try:
--> 162             trial = _run_trial(study, func, catch)
    163         except Exception:
    164             raise

/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    265 
    266     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 267         raise func_err
    268     return trial
    269 

/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    214 
    215     try:
--> 216         value_or_values = func(trial)
    217     except exceptions.TrialPruned as e:
    218         # TODO(mamu): Handle multi-objective cases.

<ipython-input-11-795fccfe2879> in objective(trial)
     17               'model__l2_leaf_reg' : model__l2_leaf_reg}
     18 
---> 19     pipe.set_params(**params)
     20     pipe.fit(train_x, train_y)
     21     pred = pipe.predict(test_x)

/opt/conda/lib/python3.7/site-packages/sklearn/pipeline.py in set_params(self, **kwargs)
    139         self
    140         """
--> 141         self._set_params('steps', **kwargs)
    142         return self
    143 

/opt/conda/lib/python3.7/site-packages/sklearn/utils/metaestimators.py in _set_params(self, attr, **params)
     51                 self._replace_estimator(attr, name, params.pop(name))
     52         # 3. Step parameters and other initialisation arguments
---> 53         super().set_params(**params)
     54         return self
     55 

/opt/conda/lib/python3.7/site-packages/sklearn/base.py in set_params(self, **params)
    259 
    260         for key, sub_params in nested_params.items():
--> 261             valid_params[key].set_params(**sub_params)
    262 
    263         return self

/opt/conda/lib/python3.7/site-packages/catboost/core.py in set_params(self, **params)
   3057         """
   3058         if self.is_fitted():
-> 3059             raise CatBoostError("You can't change params of fitted model.")
   3060         for key, value in iteritems(params):
   3061             self._init_params[key] = value

CatBoostError: You can't change params of fitted model.`

**Comment by shrey10926** [comment]
If I have 50 trials I'll have to create 50 models! That would be time consuming

**Comment by LyzhinIvan** [comment]
> If I have 50 trials I'll have to create 50 models! That would be time consuming

No, model creation (`model = CatBoost(params)`) is very fast comparing to training time (`model.fit(pool)`).

**Comment by shrey10926** [comment]
But why do I have to create a model for each trial? For other models, I create one model and that's it. This is the first time I'm hearing to create multiple models.

**Comment by LyzhinIvan** [comment]
> But why do I have to create a model for each trial? For other models, I create one model and that's it. This is the first time I'm hearing to create multiple models.

Why do you fear to create several models? It costs nothing. Such behavior was implemented to protect results of a long training.

**Comment by astronaut-98** [comment]
> Can you be more specific?
