### ISSUE TITLE
callback demo?

### ISSUE THREAD

**Issue by nickhuangxinyu** [catboost/catboost#1824]
hi, catboost is a great tool.

but can you provide a demo for custom writting callback function?

For Example, my model is CatRegressor, my loss is RMSE, besides loss value, i also want to calculate corr(y, y_pred) for each iterations.

Can you provide a demo?

Thanks

**Comment by LyzhinIvan** [comment]
Hi, @nickhuangxinyu!

To calculate custom metric at each iteration check this tutorial https://github.com/catboost/catboost/blob/master/catboost/tutorials/custom_loss/custom_loss_and_metric_tutorial.ipynb.

**Comment by Neronjust2017** [comment]
Hi, @nickhuangxinyu , I think I find the solution.

> Hello! In CatBoost 0.26 we released support for callbacks, so your task is easily. We are preparing our new documentation, as this function still is not described, but you can look at example in our tests: https://github.com/catboost/catboost/blob/v0.26.1/catboost/python-package/ut/medium/test.py#L9726-L9738 I guess that's a good sample to start with.

https://github.com/catboost/catboost/issues/1862
