### ISSUE TITLE
build from source, get format error

### ISSUE THREAD

**Issue by jieYM** [catboost/catboost#1832]
Problem:build from source get error, when run command `python3 ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app`:
`ERROR: [Errno 8] Exec format error: '/root/.ya/tools/9ea4cb57c3_d/ya-bin'`

catboost version:lasted
Operating System: centos
CPU: aarch64

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Could you please run this command on an x86_64 machine?
Native builds for ARM are not supported yet.

**Comment by jieYM** [comment]
> Could you please run this command on an x86_64 machine?
> Native builds for ARM are not supported yet.

But my machine is base arm, run on x86_64 is useless for me. And i saw some issue said it is worked on arm already. It's any way I can try to install in arm?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
x86_64 is needed only to build ARM CatBoost executable file (or Python package).
The resulting artifact can run on ARM.
Support for native ARM builds is in progress.

**Comment by kizill** [comment]
Yes, now our build system reliably works only on x86_64 hosts, and only cross-compilation scenario is available for building for arm platforms.
