### ISSUE TITLE
java.lang.AbstractMethodError: ai.catboost.spark.Pool.org$apache$spark$ml$param$Params$_setter_$org$apache$spark$ml$param$Params$$paramMap_$eq(Lorg/apache/spark/ml/param/ParamMap;)V

### ISSUE THREAD

**Issue by luoyexuge** [catboost/catboost#1836]
Problem: error
catboost version: 
Operating System:
CPU:
# GPU:

**Comment by andrey-khropov** [comment]
Can you provide more context?

What OS, CatBoost for Apache Spark version do you use?

Please provide a code example to reproduce this error.

**Comment by andrey-khropov** [comment]
No feedback, feel free to reopen with more detailed data if the issue can still be reproduced.
