### ISSUE TITLE
Provide catboost conda package on conda-forge?

### ISSUE THREAD

**Issue by aldanor** [catboost/catboost#184]
With so many people having problems with version mismatches, or worried about downloading and running a proprietary 'ya make' binary, could pre-built conda package be possibly provided as well, e.g. on conda-forge?

**Comment by sab** [comment]
Good idea! We'll do it.

**Comment by eyadsibai** [comment]
Kindly include catboost-viewer too

**Comment by aldanor** [comment]
@annaveronika Any news re: this?

**Comment by sab** [comment]
@aldanor waiting for merge, https://github.com/conda-forge/staged-recipes/pull/5152

**Comment by sab** [comment]
Finally it's merged, https://github.com/conda-forge/catboost-feedstock

Installing `catboost` from the `conda-forge` channel can be achieved by adding `conda-forge` to your channels with:

```
conda config --add channels conda-forge
```

Once the `conda-forge` channel has been enabled, `catboost` can be installed with:

```
conda install catboost
```

**Comment by Ingvar-Y** [comment]
@sab Hi! Are you planning on updating conda package soon or are you waiting to do some hotfixes first?
