### ISSUE TITLE
How to set borders for CatBoost Regressor

### ISSUE THREAD

**Issue by TJUSIRIUS** [catboost/catboost#1841]
Problem: How to set borders for CatBoost Regressor
catboost version: '0.24.1'
Operating System: win10
CPU: 
Because of my mistake, i delete my best regressor cbm model, but the corrresponding 'cpp' file still exists. 

Now i want to set the leaf_values, borders, scale and bias to a new regressor in Python. But i can only find the two interfaces of 'set_leaf_values()' and 'get_borders()' . 

Is there has any way to set borders in the library? Or the only way is to create a '.py' format file, set params and run it?

**Comment by ek-ak** [comment]
Hello! If you model contains only float features (and maybe one hot encoded features) it is possible to describe an entire model in json format.  The easiest way to make such a hack I think will be to learn a new model on the same pool, save it in json format and then fix the model in json and convert back.  
https://github.com/catboost/tutorials/blob/master/model_analysis/model_export_as_json_tutorial.ipynb

**Comment by TJUSIRIUS** [comment]
Quite thanks, although changing the cpp to json is also hard for me ... (doge), i'll try
