### ISSUE TITLE
In the process of feature selection, is there a way to display the scores of all features?

### ISSUE THREAD

**Issue by Wangpc-972** [catboost/catboost#1843]
Hello CatBoost team:
I want to display the scores of all features, but there is no corresponding code after reading much information. Looking forward to your reply, thank you!

**Comment by LyzhinIvan** [comment]
Hi, @Wangpc-972!

Do you mean CatBoost `select_features` method? You can set `logging_level=Debug` to see scores of all features at each stage of features elimination process.

**Comment by BenMacKenzie** [comment]
I have a similar question:  I'd like to be able to interrogate all of the information available in the plot generated by select_features programatically.    Basically, is there any way to get the information contained in this file through the python api: https://catboost.ai/docs/concepts/output-data_features-selection.html?

CatBoost is the best!

**Comment by LyzhinIvan** [comment]
> Basically, is there any way to get the information contained in this file through the python api: https://catboost.ai/docs/concepts/output-data_features-selection.html?

Hi, @BenMacKenzie!
Yes, all points of the generated plot are contained in `loss_graph` property of a summary object returned by `select_features` method. The format is described by the link which you have provided.

**Comment by Wangpc-972** [comment]
> > Basically, is there any way to get the information contained in this file through the python api: https://catboost.ai/docs/concepts/output-data_features-selection.html?
> 
> Hi, @BenMacKenzie!
> Yes, all points of the generated plot are contained in `loss_graph` property of a summary object returned by `select_features` method. The format is described by the link which you have provided.

Thank you！I solved my problem.

**Comment by BenMacKenzie** [comment]
I must be missing something.  The only thing returned from model.select_features is a summary object which does not contain a loss graph.  I also don't see anything in the catboost_info directory.  Is there a parameter I need to set in order to get the loss graph?

**Comment by LyzhinIvan** [comment]
> I must be missing something. The only thing returned from model.select_features is a summary object which does not contain a loss graph. I also don't see anything in the catboost_info directory. Is there a parameter I need to set in order to get the loss graph?

Try to update CatBoost. It is available since 0.26.1.

**Comment by BenMacKenzie** [comment]
awesome! thanks!!
