### ISSUE TITLE
CatBoostClassifier's `calc_leaf_indexes` applied to validation data return the leaf indices where none of the training samples fell

### ISSUE THREAD

**Issue by andrewsonin** [catboost/catboost#1845]
Problem:

Hi there, I am trying to use the Catboost Classifier's leaf indexes as the meta-features to the logistic regression. And I came across the behavior of your library, which is that some leaves of the boosting trees does not contain at least one training sample.

```python
classifier = CatBoostClassifier()  # parameters omitted
classifier.fit(train_dataset, eval_set=eval_dataset, use_best_model=True)

X_train_leaves  = classifier.calc_leaf_indexes(train_dataset)
X_eval_leaves   = classifier.calc_leaf_indexes(eval_dataset)


from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder()
X_train_one_hot = one_hot_encoder.fit_transform(X_train_leaves)
X_val_one_hot   = one_hot_encoder.transform(X_val_leaves)
```

The last line throws the following error:

```python
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

...sklearn/preprocessing/_encoders.py in transform(self, X)
    469         check_is_fitted(self)
    470         # validation of X happens in _check_X called by _transform
--> 471         X_int, X_mask = self._transform(X, handle_unknown=self.handle_unknown,
    472                                         force_all_finite='allow-nan')
    473 

...sklearn/preprocessing/_encoders.py in _transform(self, X, handle_unknown, force_all_finite)
    134                     msg = ("Found unknown categories {0} in column {1}"
    135                            " during transform".format(diff, i))
--> 136                     raise ValueError(msg)
    137                 else:
    138                     # Set the problematic rows to an acceptable value and

ValueError: Found unknown categories [17, 55] in column 0 during transform
```

catboost version: 0.26.1
Operating System: RHEL Server 7.9
CPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz

I would like to know if this behavior is a bug, or if it is consistent with the internal logic of the training algorithm. Thank you!

**Comment by kizill** [comment]
Hello!
CatBoost builds symmetric trees (also known as oblivious) by default. That means that tree shares the same condition on each tree level. This means that it's totally okay, that a tree can contain a leaves with no objects in them during training. And also such trees are really fast in terms of inference throughput and delays - it is 8 times faster to infer model with oblivious tree of depth 6 than depthwise asymmetric trees with depth 6.

Anyway, CatBoost supports different tree shapes, and you can easily switch to Lossguide (like in LightGBM by default) or Depthwise (like in XGBoost by default), check our new documentation page about this paramter https://catboost.ai/en/docs-beta/references/training-parameters/common#grow_policy

Closing as fixed, as i guess everything is clear now.
Good luck with CatBoost, hope you'll enjoy it 🐱
