### ISSUE TITLE
Mssing `contrib/libs/libiconv`

### ISSUE THREAD

**Issue by david-cortes** [catboost/catboost#1848]
If trying to build the library from source, the script tries to reference a library `libiconv` under `contrib/libs`, but there's no such library in the source tree and thus the compilation fails.

**Comment by kizill** [comment]
Need more details: are you building with `ya make` or with `make -f ...` ?

**Comment by david-cortes** [comment]
With `ya make`, trying build it as an application (or library, don't remember the exact wording but it was in the examples given when calling `./ya` with no arguments)

**Comment by kizill** [comment]
I can't reproduce this :( What platform are you building on and what exact flags for build are you using?

**Comment by andrey-khropov** [comment]
We've switched to CMake-based build since release 1.2 and `libiconv` dependency is now [provided by conan](https://github.com/catboost/catboost/blob/e22b244ea04fe2d891127e2adbcb33e9dbce395d/conanfile.txt#L2), not from contrib.
