### ISSUE TITLE
Timestamp type column

### ISSUE THREAD

**Issue by dlihhats** [catboost/catboost#185]
The documentation at https://tech.yandex.com/catboost/doc/dg/concepts/input-data_column-descfile-docpage/ mentions Timestamp as one of the supported column types.
However, when I add such column to my column descriptions file, I get an exception from `catboost/libs/data/load_data.cpp:184` where Timestamp is missing from the availabe column types.

```
dmitri_lihhatsov@jupyter:~/fraud$ catboost --version
git info:
    Commit: b85e89ae123f544e5b7db63a04002e4a9e7f6e92
    Author: exprmntr <exprmntr@gmail.com>
    Summary: Update mk_wheel.py

Other info:
    Build by: dmitri_lihhatsov
    Top src dir: /home/dmitri_lihhatsov/catboost
    Top build dir: /home/dmitri_lihhatsov/.ya/build/build_root/n2z3/0002ba
    Hostname: jupyter
    Host information: 
        Linux jupyter 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nikitxskv** [comment]
@dlihhats, Hi!
Thank you for report.
It will be fixed in the next version.

**Comment by annaveronika** [comment]
fixed in last version
