### ISSUE TITLE
[C/C++ API] Make version available in c_api.h 

### ISSUE THREAD

**Issue by hassec** [catboost/catboost#1854]
Any chance we could include the catboost version in `c_api.h` such that one can query it and write code to e.g. workaround API breaking changes?

**Comment by kizill** [comment]
Did you prefer integer constants like 
```cpp
const int CATBOOST_APPLIER_MAJOR = 0;
const int CATBOOST_APPLIER_MINOR = 26;
const int CATBOOST_APPLIER_FIX = 1;
```
 of something like 
```cpp
#define CATBOOST_APPLIER_MAJOR 0
#define CATBOOST_APPLIER_MAJOR 26
#define CATBOOST_APPLIER_FIX 1
```
?

**Comment by hassec** [comment]
@kizill thanks for getting back to me :blush: 

I'd say using `#define` is the more common way libraries do it, so I'd suggest going that route.

**Comment by kizill** [comment]
Done!
