### ISSUE TITLE
Khronos ML summit

### ISSUE THREAD

**Issue by pboudier** [catboost/catboost#1856]
Hello,

I am the chair of a working group at Khronos developping standards for graphics and compute hardware accelerators (as well as a representative for Nvidia in those groups).

We are organizing a summit to gather feedback from the ecosystem, and influence the design of the next round of improvements, and I thought that you may be interested in being represented:
https://www.khronos.org/events/2021-invitation-to-the-khronos-machine-learning-summit

This summit is IP free, and will let you present your project and your needs for improvements in the ML ecosystem, as well as hearing from other companies.

regards,

Pierre Boudier
Software architect at Nvidia
chair of the Machine Learning TSG at Khronos

**Comment by kizill** [comment]
Thank you, will try to attend this meeting.
