### ISSUE TITLE
how does catboost handle NAN in X?

### ISSUE THREAD

**Issue by nickhuangxinyu** [catboost/catboost#1866]
I found there is some NAN in my input matrix X.

catboost still works, so, i want to know:

how does catboost handle NAN? make it as zero?

**Comment by kizill** [comment]
The following modes for processing missing values are supported:
* Missing values prohibited, their presence is interpreted as an error.
* Missing values are processed as the minimum value (less than all other values) for the feature. It is guaranteed that a split that separates missing values from all other values is considered when selecting trees.
* Missing values are processed as the maximum value (greater than all other values) for the feature. It is guaranteed that a split that separates missing values from all other values is considered when selecting trees.

The default processing mode is Min. The methods for changing the default mode are package-dependant
Read more at docs page https://catboost.ai/en/concepts/algorithm-missing-values-processing#numerical-features
