### ISSUE TITLE
SEGFAULT with newest version of catboost

### ISSUE THREAD

**Issue by PrimozGodec** [catboost/catboost#1877]
Problem:

catboost==1.0.0 segfaults in combination with PyQt==5.15.4 and PyQtWebEngine==5.15.4 on MacOS. It does not happen with catboost<1.0.0 and the same version of PyQt and PyQtWebEngine.

How to reproduce:

Install packages: `pip install catboost==1.0.0 PyQt==5.15.4 PyQtWebEngine==5.15.4`
Run script:
```
from PyQt5 import QtCore
QtCore.QLocale()
import catboost
import PyQt5.QtWebEngineWidgets
```

catboost version: 1.0.0

Operating System: macOS Big Sur 11.5.2 (20G95)
CPU: 3,1 GHz Dual-Core Intel Core i5
GPU: Intel Iris Plus Graphics 650 1536 MB

It also happens on macOS 11.15 (Github Actions: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20211002.1)

**Comment by LyzhinIvan** [comment]
@PrimozGodec,  @ThibaudReal  CatBoost v.1.0.1 has been released on PyPI, now it is safe to upgrade.

**Comment by PrimozGodec** [comment]
Thanks, @LyzhinIvan. I can confirm it works now. :)
