### ISSUE TITLE
used_ram_limit parameter raise error

### ISSUE THREAD

**Issue by richardalligier** [catboost/catboost#188]
Hello,
I don't find a way to specify a ram limit.

If I follow the documentation example and use this:
`model = CatBoostRegressor(loss_function='RMSE',logging_level='Verbose',used_ram_limit=2gb)`
I get that:
```
    model = CatBoostRegressor(loss_function='RMSE',logging_level='Verbose',used_ram_limit=2gb)
                                                                                            ^
SyntaxError: invalid syntax
```
As the documentation specify that this parameter is an int, I tried:
`model=CatBoostRegressor(loss_function='RMSE',logging_level='Verbose',used_ram_limit=2*1024*1024*1024)`

And I got that:
```
    model = CatBoostRegressor(loss_function='RMSE',logging_level='Verbose',used_ram_limit=2*1024*1024*1024)
  File "/usr/local/lib/python3.5/dist-packages/catboost/core.py", line 1529, in __init__
    super(CatBoostRegressor, self).__init__(params)
  File "/usr/local/lib/python3.5/dist-packages/catboost/core.py", line 485, in __init__
    super(CatBoost, self).__init__(params)
  File "_catboost.pyx", line 859, in _catboost._CatBoostBase.__init__
  File "_catboost.pyx", line 904, in _catboost._CatBoostBase._check_train_params
_catboost.CatboostError: catboost/libs/options/plain_options_helper.cpp:203: Error: unknown option used_ram_limit with value 2147483648
```

A link to the doc I used: https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_parameters-list-docpage/#python-reference_parameters-list

Thanks for your help !

**Comment by Noxoomo** [comment]
Hello!

Its bug (we missed this option during merge of GPU/CPU binaries), it'll be fixed in next version

**Comment by annaveronika** [comment]
fixed in last version
