### ISSUE TITLE
Unable to plot with "calc_feature_statistics"

### ISSUE THREAD

**Issue by johnkuangwork** [catboost/catboost#1882]
Run calc_feature_statistics with code:

model.calc_feature_statistics(test_dataset,feature='Sex',plot=True,prediction_type='Class')

I did turn "sex" into categorical variable under .fit function. But it keep saying "IndexError: list index out of range". 

------------

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_426068/2658994638.py in <module>
----> 1 model.calc_feature_statistics(test_dataset,feature='Sex',plot=True,prediction_type='Class')

~\Ana3\envs\work\lib\site-packages\catboost\core.py in calc_feature_statistics(self, data, target, feature, prediction_type, cat_feature_values, plot, max_cat_features_on_plot, thread_count, plot_file)
   3454         # draw only unique plots
   3455         if plot or plot_file is not None:
-> 3456             fig = _plot_feature_statistics(
   3457                 statistics_by_feature,
   3458                 pool_names,

~\Ana3\envs\work\lib\site-packages\catboost\core.py in _plot_feature_statistics(statistics_by_feature, pool_names, feature_names, max_cat_features_on_plot)
   6339         figs_with_names += _plot_feature_statistics_units(statistics, pool_names, feature_name, max_cat_features_on_plot)
   6340 
-> 6341     main_fig = figs_with_names[0][0]
   6342     buttons = []
   6343     for fig, feature_name in figs_with_names:

IndexError: list index out of range

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Please feel free re-open, if the issue is not fixed in your case.
