### ISSUE TITLE
speed-up-training page does not mention anything about Numpy + features_data approach for passing data to catboost pool

### ISSUE THREAD

**Issue by comorado** [catboost/catboost#1887]
Problem: Documentation 

Hello Catboost community page on the [Speed-up training](https://catboost.ai/en/docs/concepts/speed-up-training) does not mention anything about use of numpy arrays instead of pandas data frames for training on large data. We observed largest speedups in switching from Pandas to Numpy + features_data. 

It would be great if a note would be added to the speed-up-triaining page about alternative approach of passing data to catboost Pool using Numpy + features_data

Thank you.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks! We have updated the doc.
BTW, the doc is now on github, and our users may contribute via PR's.
https://github.com/catboost/catboost/tree/master/catboost/docs
