### ISSUE TITLE
.predict() doesn't use class_weights

### ISSUE THREAD

**Issue by alitirmizi23** [catboost/catboost#1888]
Problem: Prediction function of catboostclassifier not using class_weights
catboost version: 1.0.0

This is a repeat of a previous issue - predict doesn't use class_weights, which leads to different values of the metric when using the same evaluation set during training vs prediction. I believe this needs to be fixed and should be looked at more closely by the developers/maintainers.

**Comment by andrey-khropov** [comment]
No feedback.
