### ISSUE TITLE
core_ml to cbm

### ISSUE THREAD

**Issue by nav2** [catboost/catboost#189]
Hello CatBoost developers,

Compliments on a great package! Can you please help me to resolve one issue?

I use Python catboost module. I trained several CatBoost models on a very large dataset (about 33 million records, 500 variables) and saved them in files. I’m then loading the models and trying to use them on a new dataset (which matches the training set in terms of the number and types of variables). Surprisingly, for all these models I’m getting the following error when calling predict_proba:

libunwind: getEncodedP /home/donskov/arcadia/contrib/libs/libunwind_master/src/AddressSpace.hpp:269 - unknown pointer encoding

Any ideas about what is happening here? I have been using CatBoost a lot on similar data and never saw anything like that.

Your help would be greatly appreciated. Please let me know if you need any additional details.

Thank you,
nav2

**Comment by kizill** [comment]
Hi! What version of package do you use? If you are trying to load model trained with pre 0.4.1 package in >=0.4.1 version it will fail, because we've introduced stable binary format only in 0.4.1 :)

**Comment by kizill** [comment]
Also, what is the size of your trained model?

**Comment by nav2** [comment]
I used package v.0.1.1.6 (both to train models and to use them later).  Trained models contain 1000 or 2000 trees, with tree depth varying between 8 and 11.

**Comment by kizill** [comment]
@nav2, model format has changed dramatically since 0.1.1.6 and only get stable in v0.4, so now i can only recommend you to switch to the newest version.  BTW,  we've implemented lot's of speedups so you could train your models much faster.

**Comment by nav2** [comment]
So the error is caused by unstable format used in module v.0.1.1.6 to save trained models to files? Even though load_model works fine, and it's predict_proba which crashes?

**Comment by nav2** [comment]
The reason I'm sticking to v.0.1.1.6 is because I used this version to train hundreds of CatBoost models in one project of mine, spending many hundreds if not thousands of hours to do that. All those saved models worked fine, until I trained last 5 models on this very very big dataset. If I now switch to newer version to repeat last 5 experiments, will my 5 CatBoost models trained by new algorithm be comparable with all other models trained by older one? Or will I have to retrain all my previous models too, to have fair comparison?

**Comment by annaveronika** [comment]
Are there any categorical features?

**Comment by nav2** [comment]
No, all features are numerical.

**Comment by annaveronika** [comment]
You can convert all your models to coreML format using the version of catboost that you trained with. Documentation for that is here: https://tech.yandex.com/catboost/doc/dg/features/export-model-to-core-ml-docpage/#export-model-to-core-ml

We will provide a converter from coreML to our internal representation in about a week or two. Then you will not need to retrain the models. We'll write in this issue when the converter is provided. Sorry for inconvenience.

**Comment by annaveronika** [comment]
In 0.6.2 we released coreml import (oblivious trees) possibility, you only have to export your pre 0.5 models in coreml format, update catboost to 0.6.2 and import them from coreml. You can try this code snippets:
%%
model = CatBoost()
model.load_model('your_model.cbm')
model.save_model('your_model.coreml', format="coreml")
%%

After updating to 0.6.2 do:
%%
model = CatBoost()
model.load_model('your_model.coreml', format="coreml")
model.save_model('model.cbm')
%%
