### ISSUE TITLE
json_value.cpp:458: Not a double

### ISSUE THREAD

**Issue by gnomeby** [catboost/catboost#190]
Hello,

There is no example about using cv in documentation. So I created my example and it doesn't work:

params={
    'border': [0.6, 0.7, 0.8, 0.9],
    'depth': [6.0, 8.0, 10.0],    
    'eval_metric': 'F1',
}
catboost.cv(params, catboost.Pool(X_train))

Please help!

**Comment by annaveronika** [comment]
There are several tutorials with cv, for example this one:
https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_base_functions.ipynb

About your example: cv doesn't do grid search, it does only training, so it will not work with several depth and border.

Thanks for the feedback, we'll add example to docs also!
