### ISSUE TITLE
Catboost version 1.0.1.11072

### ISSUE THREAD

**Issue by freddyaboulton** [catboost/catboost#1900]
Hello!

I recently saw that version 1.0.1.11072 was uploaded to [pypi](https://pypi.org/project/catboost/1.0.1.11072/) but it's not tagged as an official release on github. Is that a legitimate version ready for production use or is it a release candidate? 

Asking cause I haven't seen that kind of version number for semver before.

Thank you.

**Comment by kizill** [comment]
The contents are fully okay, but version string is corrupted, sorry! I've just dropped it from pypi, we will publish 1.0.1 in a hour. Thank you for help :)
