### ISSUE TITLE
exit code 139 when using GPU prediction

### ISSUE THREAD

**Issue by vlomshakov** [catboost/catboost#1901]
Problem:
Hey! Unfortunately Catboost is still crashing for me with prediction on GPU. 
I've got seg fault: `Process finished with exit code 139`.
Snippet to reproduce the problem:
```
model = CatBoost({
        'loss_function': 'RMSE',
        'depth': 4,
        'iterations': 200,
        'learning_rate': 0.7,
        'task_type': 'GPU'
    })
X = numpy.random.rand(1000, 10)
y = numpy.random.rand(1000)
model.fit(X, y)
model.predict(X, task_type='GPU')
```
I've noticed that setting hyper-params (depth, iterations, learning_rate) causes the problem.

catboost version:  0.26.1 and 1.0.0
Operating System: Ubuntu 18.04.5 LTS
GPU: Tesla K80

Maybe it 's related to https://github.com/catboost/catboost/issues/1735

**Comment by kizill** [comment]
We are starting to investigate this case, sorry for such a long delay.
