### ISSUE TITLE
Rewriting library from C++ to Java

### ISSUE THREAD

**Issue by CamilYed** [catboost/catboost#1902]
Do you have any plans to rewrite catboost in C ++ to Java when Vector Api will be available:
https://openjdk.java.net/jeps/338

Benefits:
 - Easier code maintenance
 - Performance compares to C ++ (or better, due to the JIT compiler)
 - Security - no memory leaks
 - Much easier code testing

**Comment by kizill** [comment]
Hello!
Thank you for your idea! I guess there could be some technical interest in implementing GBDT in Java, but we definitely aren't planning to do this, as it's need's a lot of work without clear perspectives for success in the end. Of course, you can try to do this by yourself, for example, you can do some speedups to GBDT written fully in java like https://github.com/spbsu-ml-community/jmll or you can do it from scratch and contribute in another OSS Java ML library, like https://github.com/mimno/Mallet
Good luck to you and thanks again 😺

**Comment by andrey-khropov** [comment]
I'd also add that you can use third-party inference libraries written in pure Java to apply models trained by CatBoost (although there're some limitations, the most significant of which is that [Ctrs](https://catboost.ai/en/docs/concepts/algorithm-main-stages_cat-to-numberic) - specifically encoded features derived from categorical ones which are specific to CatBoost - are not supported by other libraries).

For example you can do this by exporting models to [PMML format](https://catboost.ai/en/docs/concepts/apply-pmml).
