### ISSUE TITLE
What is the consequence of too large (or too small) L2 regularization parameter?

### ISSUE THREAD

**Issue by Wangpc-972** [catboost/catboost#1906]
Hellow CatBoost team
I want to know if the regularization parameter `l2_leaf_reg` is too large (or too small), will CatBoost overfit or underfit?

**Comment by andrey-khropov** [comment]
Increasing `l2_leaf_reg` will increase the weight of the regularization penalty and hence the model will be less likely to overfit. But I'd recommend some parameter tuning to see what value is the best for your problem.
