### ISSUE TITLE
Public API for `is_maximizable_metric`

### ISSUE THREAD

**Issue by Innixma** [catboost/catboost#1915]
(Related Issue: #1890)
(CatBoost version v1.0.3)

Following the logic of [this commit](https://github.com/catboost/catboost/commit/a6963aa769ca90bb2ee37c3cf60bdbc3c40bcb0f), to determine if a string eval_metric `is_max_optimal==True` I can do the following:

```
eval_metric = 'Accuracy'
from catboost._catboost import is_maximizable_metric
is_max_optimal = is_maximizable_metric(eval_metric)
```

I can also do:

```
from catboost import metrics
eval_metric = metrics.Accuracy()
is_max_optimal = eval_metric.is_max_optimal()
```

Given `eval_metric = 'Accuracy'`, is there:

1. A way to do the same as  `is_max_optimal = is_maximizable_metric(eval_metric)` without having to use a private API?

or

2. A way to convert this automatically to the catboost metric object `catboost.metrics.Accuracy()` via the string alone?

In general I want to avoid using a private API function.

**Comment by LyzhinIvan** [comment]
`is_maximizable_metric` and `is_minimizable_metric` are public now.
