### ISSUE TITLE
max_pairs option?

### ISSUE THREAD

**Issue by pavelgur** [catboost/catboost#1919]
Problem:
> CatBoostError: catboost/private/libs/pairs/util.cpp:113: Toо many pairs should be generated for group: 13734090 , use max_pairs option to limit generated pair count

I can't see any mentioning of **max_pairs** in the documentation. Is it missing?.. Also, what's the workaround, to generate pairs manually for now?
Thank you.

catboost version: 0.26
Operating System: Linux
CPU: i7
GPU: None

**Comment by LyzhinIvan** [comment]
I guess you train a model with PairLogit loss function. [`max_pairs`](https://catboost.ai/en/docs/concepts/loss-functions-ranking#PairLogit) is a parameter of this loss function, you should specify it like this: `loss_function="PairLogit:max_pairs=1000"`. You can also pass manually generated pairs to the pool. ([docs](https://catboost.ai/en/docs/concepts/python-reference_pool#pairs))
