### ISSUE TITLE
Specify how many processors to use

### ISSUE THREAD

**Issue by castroavila** [catboost/catboost#1922]
Problem: I use CatBoostRegressor and when running it,  it used by default  every processor available on the machine. 
Is there any parameter (like n_jobs or similar) to set how many processor to use? I looked up on the doc, and didn't find any parameters to accomplish this.

catboost version: 1.0.0
Operating System: Ubuntu
CPU:
GPU:

Thanks in advance,
Manuel

**Comment by LyzhinIvan** [comment]
There is a `thread_count` option in the constructor of CatBoostRegressor.
