### ISSUE TITLE
Huge cv memory consumption

### ISSUE THREAD

**Issue by pavelgur** [catboost/catboost#1929]
Problem:
(CPU) Memory consumption is proportional to number of folds. It effectively limits that number depending on your RAM. Is there a way to make these folds non-owning?

catboost version: 0.26
Operating System: Linux
CPU: i7
GPU: None

**Comment by kizill** [comment]
You closed this issue, is it still a problem on 1.0.3 version?

**Comment by pavelgur** [comment]
Can't say, I just moved to a computing cloud with dozens of GBs of RAM :^)
