### ISSUE TITLE
allow_const_label=True does not seem to work with CatBoostClassifier

### ISSUE THREAD

**Issue by tristancinquin** [catboost/catboost#1933]
Hi, 

I am trying to get a CatBoostClassifier to work in a case where I only have one label. I saw that CatBoostClassifiers have the `allow_const_label` parameter for this. However, I still run into the error : `catboost.CatBoostError: catboost/private/libs/target/target_converter.cpp:374: Target contains only one unique value`. 

The error is reproducible with the following code : 
```
import catboost
model = CatBoostClassifier(allow_const_label=True)
model.fit([[1,1,1],[1,0,1],[0,1,1]], [1,1,1])
```

catboost version: 1.0.3
Operating System: MacOS 11.6.1
CPU: Yes
GPU: No

**Comment by andrey-khropov** [comment]
Fixed in https://github.com/catboost/catboost/commit/79f17024dff98c9952ef522fe90504199d26ab17
