### ISSUE TITLE
"Not enough memory for learning" on GPU

### ISSUE THREAD

**Issue by fingoldo** [catboost/catboost#1938]
**Problem:**

```python
CatBoostClassifier(
                text_features=[],
                text_processing=None,
                cat_features=cat_features,
                eval_metric="Accuracy",
                
                max_ctr_complexity=1,
                learning_rate=0.6,
                iterations=1000,
                task_type="GPU",
                early_stopping_rounds=200,
                logging_level='Debug'
            )
```
is fitted within a sklearn pipeline, and sometimes stumbles on the following  **error:**

```python
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/catboost/core.py", line 4718, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/catboost/core.py", line 2042, in _fit
    train_params["init_model"]
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/cuda/methods/greedy_subsets_searcher/compute_by_blocks_helper.cpp:310: Error: not enough memory for learning
```

**Memory usage before the .fit call**:  App is using 70.7Gb RAM, Tesla T4: 2.5/14.8Gb VRAM

**Remedies tried:**
I tried setting  gpu_cat_features_storage="CpuPinnedMemory", gpu_ram_part=0.75. With no luck.

**Question:**
What else would you recommend trying?
If I use task_type="CPU", it works, just VERY slowly. So need to stick with GPU, but how?

**OS, soft, & hardware info:**

catboost version:
1.0.3

Operating System:
Ubuntu 20.04.3 LTS

CPU:
Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz

GPU: Tesla T4

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Could you please try passing subsample=x to CatBoostClassifier for some small x (default is 0.66)?
This parameter controls the number of samples offloaded to gpu.

**Comment by fingoldo** [comment]
Thank you so much for your suggestion. For a few days it's running with new settings:

>                 bootstrap_type='Poisson',
>                 subsample=0.5,

and there are no errors. I am not 100% sure it helped once and forever, but at least it seems to have helped.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
😄
