### ISSUE TITLE
Incremental training with "init_model" fails when not all initial labels are present in new data

### ISSUE THREAD

**Issue by kvantricht** [catboost/catboost#1953]
Problem: Incremental training with "init_model" fails when not all initial labels are present
catboost version: 0.26.1
Operating System: CentOS Linux 7
CPU: Intel Xeon Processor
GPU: /

I am training a CatboostClassifier on 19 different output classes, which works fine. Then I'm incrementally training a new classifier using the earlier trained `init_model` and training on a new training dataset. The catch is that this dataset has only 17 of the original 19 unique labels. Catboost warns me already with: `Found only 17 unique classes in the data, but have defined 19 classes. Probably something is wrong with data.` 

but starts to train fine anyway. Only at the end (I assume when the model gets merged with the original one?) I get the following error message:
```
Exception has occurred: CatBoostError
catboost/libs/model/model.cpp:1716: Approx dimensions don't match: 19 != 17
```

Is it expected behavior that incremental training is not possible on only a subset of the original classes? If yes, then maybe a clearer error message should be given. It would be even better though if the code could handle this case, but maybe I'm overseeing some things that do not allow such functionality.

**Comment by Robert-Schimanek** [comment]
Same problem here... Will there be incremental support for changing input and output labels in the future?

**Comment by kevinpatelco** [comment]
@kvantricht Did you find any solution for this?

**Comment by kvantricht** [comment]
> @kvantricht Did you find any solution for this?

unfortunately no, up till now I am unable to do incremental training when not all classes are present in the new dataset.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
technically, you should patch here https://github.com/catboost/catboost/blob/5d02dabfd9c22ec6fe2cb8b964294bc30b27be9d/catboost/private/libs/labels/label_converter.cpp#L15
with
```diff
ndex: catboost/private/libs/labels/label_converter.cpp
===================================================================
--- catboost/private/libs/labels/label_converter.cpp    (revision 9774744)
+++ catboost/private/libs/labels/label_converter.cpp    (working copy)
@@ -24,14 +24,19 @@
                 << ", but have defined " << classesCount << " classes."
                 << " Probably something is wrong with data." << Endl;
         }
+        labels.reserve(classesCount);
+        for (auto classId : xrange(classesCount)) {
+            labels.emplace(classId, classId);
+        }
+    } else {
+        labels.reserve(targets.size());
+        int id = 0;
+        for (auto target : targets) {
+            Cout << "target " << target << " -> id " << id << Endl;
+            labels.emplace(target, id++);
+        }
     }
 
-    labels.reserve(targets.size());
-    int id = 0;
-    for (auto target : targets) {
-        labels.emplace(target, id++);
-    }
-
     return labels;
 }
```
rebuild, and specify classes_count=19 when you create your CatBoostClassifier's

however, doing this degrades quality of multi-class models where the real class count is less than classes_count

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
i think it is better to copy some samples from the dataset used to create init_model to the dataset used to continue training, so that the second dataset contains all the 19 labels

**Comment by Robert-Schimanek** [comment]
Incremental support ist still missing. Please reopen ticket.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
i think that we won't do this because improving models with biased data is questionable

those who need this may use the patch above

**Comment by kvantricht** [comment]
While that reasoning does make sense, it still looks to me that the exception handling could be improved here. It took me quite a while to figure out what was actually happening given this 
`Exception has occurred: CatBoostError
catboost/libs/model/model.cpp:1716: Approx dimensions don't match: 19 != 17`
