### ISSUE TITLE
catboost crashes jupyter notebook (sigill issue) many times

### ISSUE THREAD

**Issue by malembetirick** [catboost/catboost#1955]
Problem: catboost crashes jupyter notebook (sigill issue) when gridsearch/fit with sklearn scikit-learn splitter object (>=3 splits) runnin for 10000 iterations on big dataset (> 2 millions trained data and 1050 features data)
catboost version: 1.0.3
Operating System: ubuntu 20.04.3 LTS
CPU: Intel Xeon E5-2686 v4
GPU: tesla v100

Below the code:
```python
from catboost import CatBoostRegressor, Pool, MetricVisualizer, cv, CatBoost
from sklearn.model_selection import PredefinedSplit, ShuffleSplit, GroupKFold
ps = GroupKFold(n_splits=3)
model = CatBoostRegressor(
    iterations=10000, 
    loss_function='RMSE',
    early_stopping_rounds=500,
    task_type='GPU',
    devices='0'
)
grid = {
    'learning_rate': [0.01, 0.001, 0.0001, 0.1],
    'depth': [2, 4, 6, 8, 10],
    'l2_leaf_reg': [1, 3, 5, 7, 9],
    'boosting_type': ['Ordered', 'Plain']
}
grid_search_result = model.grid_search(grid, train_pool, plot=True, cv=ps, shuffle=False, search_by_train_test_split=False)
```

I have this issue on regression task and ranking task pairwise

**Comment by malembetirick** [comment]
I have also this when i train my model on cpu/gpu.

**Comment by kizill** [comment]
I've tried your code snippet and failed to reproduce on some sample datasets :( Can you please share a full reproducer with data? Maybe you can try to generate it with `sklearn.datasets.make_regression` or with some other pseudo-random generator.

**Comment by malembetirick** [comment]
Hi,
i finally find a way to fix this issue. It was a memory issue because of logging information that filled ram.
