### ISSUE TITLE
How to use another probability threshold when using eval_metrics method?

### ISSUE THREAD

**Issue by shikarukitake** [catboost/catboost#1958]
**Problem:** Hi. I calculate precision and recall with `model.eval_metrics` method. How I see this method use threshold equal to 0.5. How can I change the threshold of model to calculate precision and recall with another probability threshold?
I tried to change threshold with `model.set_probability_threshold`, but results of model.eval_metrics didn't changed.
**catboost version:** 1.0.3
**Operating System:** Red Hat Enterprise Linux Server 7.9 (Maipo)

**Comment by LyzhinIvan** [comment]
Hi, @shikarukitake! 
This is a bug - `model.eval_metrics` should use the threshold that was set by `model.set_probability_threshold`. We will fix this.

**Comment by LyzhinIvan** [comment]
Right now you can pass probability border as metric param like `Precision:proba_border=0.3`

**Comment by savelii-bogdanov** [comment]
> Hi, @shikarukitake! This is a bug - `model.eval_metrics` should use the threshold that was set by `model.set_probability_threshold`. We will fix this.
@LyzhinIvan LyzhinIvan

Good day! Ran into the same issue (was calculating f1 and seemed like ```model.set_probability_threshold``` did nothing). Is the bug fixed?
