### ISSUE TITLE
TypeError: Cannot convert 'b'FR'' to float

### ISSUE THREAD

**Issue by msultanmahmud** [catboost/catboost#1962]
I having the the following issue in catboost when my data is categorical. Could you please let me know how can I resolve it?
"TypeError: Cannot convert 'b'FR'' to float"

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
_catboost.pyx in _catboost.get_float_feature()

_catboost.pyx in _catboost._FloatOrNan()

_catboost.pyx in _catboost._FloatOrNanFromString()

TypeError: Cannot convert 'b'FR'' to float

During handling of the above exception, another exception occurred:

CatBoostError                             Traceback (most recent call last)
<ipython-input-80-0dc0baaab024> in <module>
      3 cat_model = CatBoostRegressor(loss_function='RMSE')
      4 # Fit model
----> 5 cat_model.fit( X_train, y_train,
      6                eval_set=(X_test, y_test),
      7                plot=True

**Comment by LyzhinIvan** [comment]
You should set `cat_features` option in `CatBoostRegressor` with list of categorical features indices.
