### ISSUE TITLE
CatBoostError: bad allocation

### ISSUE THREAD

**Issue by sujay003** [catboost/catboost#1963]
```
Learning rate set to 0.107067
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8412/3363438529.py in <module>
----> 1 cat.fit(X_train, y_train, plot=True)

E:\Conda\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   4714             CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
   4715 
-> 4716         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4717                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
   4718                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)

E:\Conda\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2035         with log_fixup(log_cout, log_cerr), \
   2036             plot_wrapper(plot, [_get_train_dir(self.get_params())]):
-> 2037             self._train(
   2038                 train_pool,
   2039                 train_params["eval_sets"],

E:\Conda\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1462 
   1463     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1464         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1465         self._set_trained_model_attributes()
   1466 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: bad allocation
```

**Comment by andrey-khropov** [comment]
Can you provide more details about how to reproduce this error:

* OS version
* CatBoost version
* Program code
* Dataset to reproduce on

?

**Comment by sujay003** [comment]
OS version : 'nt'
CatBoost version : '1.0.3' 
cant share program or dataset. But I can tell its a classification problem with 5 categorical and 2 numerical input. Target variable is multi label. 
Train set has around 300k data
Test set has around 200k data

**Comment by LyzhinIvan** [comment]
Hi, @sujay003!

Could you provide all options that you specify for CatBoost?
How many target variables do you have?
Does this error happens on a smaller bunch of data?

**Comment by sujay003** [comment]
params = {'iterations':5000,
'learning_rate':0.01,
'loss_function':'MultiClass'
'cat_features': cluster_categories,
'depth':6,
'eval_metric':'AUC',
'verbose':True,
#'od_type':"Iter", # overfit detector
'od_wait':500, # most recent best iteration to wait before stopping
'random_seed': SEED,
}
these are the parameters I have defined.
I have one target variable which has multiple lables.
Yes, this happens with smaller bunch of data

**Comment by LyzhinIvan** [comment]
> 'loss_function':'MultiClass'

How many classes do you have?

**Comment by sujay003** [comment]
20053

**Comment by LyzhinIvan** [comment]
It is pretty big number of classes. Maybe you have not enough RAM, because internally CatBoost requires at least O(n_classes^2) bytes for hessian calculation (~1.5GB in your case) and O(n_objects * n_classes) bytes for prediction values (~45GB in your case). Besides that there are other places that require significant amount of memory. For example, ctrs for categorical features. So I have such advises and questions for you:
1) How much memory do you have? 
2) Try to set `max_ctr_complexity=1`.
3) Try to set `leaf_estimation_method='Gradient'`.
4) Set `logging_level='Debug'` and send here an output log.

**Comment by sujay003** [comment]
I'm running it on HPC, I have 24 cores with 256gb RAM

**Comment by LyzhinIvan** [comment]
In this case I need debug log to understand at which step the error occurs.

**Comment by sujay003** [comment]
its giving same error, can we train model in batches ?, I looked for didn't find any solution

**Comment by LyzhinIvan** [comment]
If you want to train in batches, then you have found a size of dataset at which the error does not occur?
What do you see in debug log? When does the error occur? On loading data or at some iteration?

Training in batches can be implemented by sequential training several models and passing a previous model to `init_model` argument for next model.

**Comment by Karlheinzniebuhr** [comment]
same issue on win10 Python 3.8.13 Anaconda Catboost 1.1.1
n_classes:194
Memory: 32GB
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
c:\dev\Work\spaceman\segmentacion\segmentacion.ipynb Cell 7 in <cell line: 20>()
     [33](vscode-notebook-cell:/c%3A/dev/Work/spaceman/segmentacion/segmentacion.ipynb#X10sZmlsZQ%3D%3D?line=32) test_pool = Pool(X_test, y_test)
     [35](vscode-notebook-cell:/c%3A/dev/Work/spaceman/segmentacion/segmentacion.ipynb#X10sZmlsZQ%3D%3D?line=34) # Fit the model on the transformed training data
---> [36](vscode-notebook-cell:/c%3A/dev/Work/spaceman/segmentacion/segmentacion.ipynb#X10sZmlsZQ%3D%3D?line=35) model.fit(train_pool, eval_set=test_pool, plot=True, verbose=0)
     [38](vscode-notebook-cell:/c%3A/dev/Work/spaceman/segmentacion/segmentacion.ipynb#X10sZmlsZQ%3D%3D?line=37) # Save the model using pickle
     [39](vscode-notebook-cell:/c%3A/dev/Work/spaceman/segmentacion/segmentacion.ipynb#X10sZmlsZQ%3D%3D?line=38) with open(f'models/model_{label}.pkl', 'wb') as f:

File c:\ProgramData\Anaconda3\lib\site-packages\catboost\core.py:5128, in CatBoostClassifier.fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5125 if 'loss_function' in params:
   5126     CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
-> 5128 self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   5129           eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period,
   5130           silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   5131 return self

File c:\ProgramData\Anaconda3\lib\site-packages\catboost\core.py:2355, in CatBoost._fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2351 allow_clear_pool = train_params["allow_clear_pool"]
   2353 with log_fixup(log_cout, log_cerr), \
   2354     plot_wrapper(plot, plot_file, 'Training plots', [_get_train_dir(self.get_params())]):
-> 2355     self._train(
   2356         train_pool,
   2357         train_params["eval_sets"],
   2358         params,
   2359         allow_clear_pool,
   2360         train_params["init_model"]
   2361     )
   2363 # Have property feature_importance possibly set
   2364 loss = self._object._get_loss_function_name()

File c:\ProgramData\Anaconda3\lib\site-packages\catboost\core.py:1759, in _CatBoostBase._train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1758 def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1759     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1760     self._set_trained_model_attributes()

File _catboost.pyx:4623, in _catboost._CatBoost._train()

File _catboost.pyx:4672, in _catboost._CatBoost._train()

CatBoostError: bad allocation

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
1. used_ram_limit limits only ram used to store combination of categorical features https://catboost.ai/en/docs/references/training-parameters/performance#used_ram_limit
2. training a multi-classification model with C classes, trees of depth D, T execution threads, and `leaf_estimation_method=Newton` requires (C^2)*(2^D)*T*4 bytes of ram to store Hessians in addition to the ram required to store the datasets -- this is why `leaf_estimation_method=Gradient` fixes the problem

**Comment by kizill** [comment]
Related to resource estimation before training. https://github.com/catboost/catboost/issues/2275
