### ISSUE TITLE
Problem with pandas String dtype 

### ISSUE THREAD

**Issue by nhat-le** [catboost/catboost#1965]
Problem: It seems like for string categorical data, CatBoost works with `object` dtype but not `string` dtype in pandas columns.
For example, this code runs well:

```
Xtrain = pd.DataFrame(dict(id_=['abb', 'bcd']),
                      dtype='object')

ytrain = [1,2]
Pool(Xtrain, ytrain, cat_features=[0])
```

but this throws an error `TypeError: Cannot convert StringArray to numpy.ndarray`

```
Xtrain = pd.DataFrame(dict(id_=['abb', 'bcd']),
                      dtype='string')

ytrain = [1,2]
Pool(Xtrain, ytrain, cat_features=[0])
```

catboost version: 1.0.3
Operating System: MacOS
CPU: i7
GPU: None

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Thanks for reporting!

**Comment by tamargrey** [comment]
Currently running into this in multiple places. Is there any plan to get it fixed?

**Comment by clarklemke** [comment]
> Currently running into this in multiple places. Is there any plan to get it fixed?

+1 to @tamargrey, would love to be able to use String dtypes natively.

**Comment by tamargrey** [comment]
@andrey-khropov I can still run into the error described in this ticket. 

Having string columns directly as shown below does now work:

```python
    import pandas as pd 
    from catboost import CatBoostClassifier

    X = pd.DataFrame({
        "ints": pd.Series([1, 9, 5]),
        "strs": pd.Series(["a", "b", "c"], dtype="string")
    })
    y = pd.Series([1, 2, 5])

    clf = CatBoostClassifier(cat_features=["strs"])
    clf.fit(X, y)
```

However having string categories for the `category` dtype can still produce `TypeError: Cannot convert StringArray to numpy.ndarray`:

```python
    import pandas as pd 
    from catboost import CatBoostClassifier
    import pytest

    X = pd.DataFrame({
        "ints": pd.Series([1, 9, 5]),
        "strs": pd.Series(["a", "b", "c"], dtype="category")
    })
    y = pd.Series([1, 2, 5])

    X = X.astype({"strs": "string"}).astype({"strs":"category"})
    assert X["strs"].dtype.categories.dtype == "string"

    clf = CatBoostClassifier(cat_features=["strs"])
    with pytest.raises(TypeError, match="Cannot convert StringArray to numpy.ndarray"):
        clf.fit(X, y)
```

I recognize this is a pretty contrived way of getting string categories, but I have several places in my codebase that can produce string categories that are running into this error.

**Comment by andrey-khropov** [comment]
> @andrey-khropov I can still run into the error described in this ticket.
> 
> Having string columns directly as shown below does now work:
> 
> ```python
>     import pandas as pd 
>     from catboost import CatBoostClassifier
> 
>     X = pd.DataFrame({
>         "ints": pd.Series([1, 9, 5]),
>         "strs": pd.Series(["a", "b", "c"], dtype="string")
>     })
>     y = pd.Series([1, 2, 5])
> 
>     clf = CatBoostClassifier(cat_features=["strs"])
>     clf.fit(X, y)
> ```
> 
> However having string categories for the `category` dtype can still produce `TypeError: Cannot convert StringArray to numpy.ndarray`:
> 
> ```python
>     import pandas as pd 
>     from catboost import CatBoostClassifier
>     import pytest
> 
>     X = pd.DataFrame({
>         "ints": pd.Series([1, 9, 5]),
>         "strs": pd.Series(["a", "b", "c"], dtype="category")
>     })
>     y = pd.Series([1, 2, 5])
> 
>     X = X.astype({"strs": "string"}).astype({"strs":"category"})
>     assert X["strs"].dtype.categories.dtype == "string"
> 
>     clf = CatBoostClassifier(cat_features=["strs"])
>     with pytest.raises(TypeError, match="Cannot convert StringArray to numpy.ndarray"):
>         clf.fit(X, y)
> ```
> 
> I recognize this is a pretty contrived way of getting string categories, but I have several places in my codebase that can produce string categories that are running into this error.

I've fixed the last case in https://github.com/catboost/catboost/commit/906072180785b2716c211d784dc1f2cd7e5c727d

**Comment by tamargrey** [comment]
Thank you @andrey-khropov! Any idea when this might be released and if it would be in a minor or patch release?

**Comment by andrey-khropov** [comment]
> Thank you @andrey-khropov! Any idea when this might be released and if it would be in a minor or patch release?

Release 1.2 that contains this fix has been published.
