### ISSUE TITLE
CatBoostError: BrierScore metric shouldn't have use_weights parameter. Valid parameters are hints, proba_border.

### ISSUE THREAD

**Issue by blahiri** [catboost/catboost#1967]
Hi Team

I am using CatBoost for a binary classification task on a very highly imbalanced data (minority : majority = 1 : 1000). The total records count including both the classes is in the range of 1,600,000.

The CatBoost documentation [Classification: objectives and metrics](https://catboost.ai/en/docs/concepts/loss-functions-classification) mentions that weights can be used with BrierScore.

> BrierScore
> 
> User-defined parameters:
> 
> Use object/group weights to calculate metrics if the specified value is true and set all weights to 1 regardless of the input data if the specified value is false.
> 
> Default: true

However, I am getting the following error when using BrierScore as eval_metric,

<pre>
CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/metrics/metric.cpp:5757: 
BrierScore metric shouldn't have use_weights parameter. Valid parameters are hints, proba_border.
</pre>

Here's part of the code I am using

<pre>
clf_params = {
	'text_features': text_features,
	'cat_features': categorical_features,
	'auto_class_weights': 'Balanced',
	'bagging_temperature': 0,
	'boosting_type': 'Plain',
	'bootstrap_type': 'MVS',
	'boost_from_average': True,
	'border_count': 254,
	'counter_calc_method': 'SkipTest' ,
	'ctr_target_border_count': 1,
	'depth': 10,
	'eval_metric': 'BrierScore:use_weights = False',
	'grow_policy': 'Lossguide',
	'iterations': 500,
	'learning_rate': 0.1,
	'12_leaf_reg': 4,
	'loss_function': 'Logloss',
	'max_ctr_complexity': 4,
	'one_hot_max_size': 3,
	'penalties_coefficient': 1,
	'random_seed': 42,
	'random_strength': 17,
	'score_function': 'Cosine',
	'sampling_frequency': 'PerTree',
	'used_ram_limit': used_ram_limit, #12GB
	'text_processing': {
		"tokenizers" : [
			{
				'tokenizer_id': 'Space',
				'delimiter': ' ',
				'separator_type': 'ByDe1imiter',
				'lowercasing': 'True',
				'token_types': ['Word', 'Number']
				#'Languages': ['English']
			},
			{
				'tokenizer_ld': 'Sense',
				'separator_type': 'BySense',
				'lowercasing': 'True',
				' token_types': ['Word', 'Number'],
				#'Languages': ['English']
			}
		]
	}
}

# Initialize CatBoostCLassifier
model = CatBoostClassifier(**clf_params)
</pre>

And here's the part that generates the error mentioned above,

<pre>
model.fit(X_train,
	y_train,
	text_features = text_features,
	cat_features = categorical_features,
	eval_set = (X_test, y_test),
	early_stopping_rounds = 5,
	use_best_model = True,
	verbose = False
	)
</pre>

Am I missing something here ? Also, the documentation page above doesn't seem to mention anything about **hints** and **proba_border** under the heading of **BrierScore**.

I have attached a screenshot of the error traceback, in case it helps. Please let me know in case you need any further information from me.

Python 3.6.1 (Anaconda 4.4.0 64-bit)
catboost version: 1.0.0
Operating System: Windows 10 64-bit
CPU: Intel Core i5 8350U
GPU: None
RAM: 16GB

![CatBoostError](https://user-images.githubusercontent.com/96404169/147852413-4022af6b-feee-4a9f-9501-0e727dbd5414.jpg)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@blahiri Thanks for reporting! A fix is on its way.
After the fix is merged, could please check that weights impact the metric values as expected?

**Comment by blahiri** [comment]
Hi @Evgueni-Petrov-aka-espetrov , Thank you very much for the update. Yes I can check the issue after the fix is merged, and let you know the updates.
