### ISSUE TITLE
pr_num tb0 type meaning

### ISSUE THREAD

**Issue by chanansh** [catboost/catboost#1973]
Problem:
It's not clear what `pr_num tb0 type` etc means in `plot_tree`
![image](https://user-images.githubusercontent.com/5981644/148675841-02d52cce-2bd4-439e-a75a-0deca2e1c11e.png)
see https://catboost.ai/en/docs/concepts/python-reference_catboost_plot_tree

**Comment by kizill** [comment]
Hello! This cryptic message means the model used prior == 0 and CtrType==0 => Borders You can read about borders here in documentation: https://catboost.ai/en/docs/concepts/algorithm-main-stages_cat-to-numberic 
tb=0 - unused value for borders type, value > 6 means we are using 6-th border of this feature (in that case it means Counter(Pclass) > 6/16)
I've fixed output of this function to be more human readable, will appear in next release.
Thank you!

**Comment by kizill** [comment]
I'll close this issue, if you still have some questions - feel free to reopen :cat:
