### ISSUE TITLE
Trained Catboost with features' order is some numeric features + some categorical features + some numeric features. 

### ISSUE THREAD

**Issue by RucGuipeng** [catboost/catboost#1974]
Problem: Trained Catboost with features' order is some numeric features (n1_features) +  some categorical features (cat_features)+ some numeric features(n2_features). Now I want to apply this model, and I need to input categorical features and  numeric features where they are both in one list, what order of features should i use. like list1 = cat_features and list2 = n1_features + n2_features?
catboost version:
Operating System: 
CPU:
GPU:

**Comment by RucGuipeng** [comment]
I apply my model on some platform, not apply it where I train the model, only support input 2 lists, can not input a feature list by my self(where I can change the order as the order I trained the model)

**Comment by kizill** [comment]
Hello! If you are applying your model in Python and you are passing feature names, CatBoost will automatically reorder them internally in proper order while applying. So, the right answer - for python pass feature names and everything will work just fine. If you are using C++ or C API model interface for inferencing - just concatenate (n1_features + n2_features) in one float vector and pass concatenated categorical features vector in the same way.

**Comment by RucGuipeng** [comment]
Thanks a lot!
