### ISSUE TITLE
CatBoostError: Invalid type for cat_feature[non-default value idx=0,feature_idx=0]=149.99 : cat_features must be integer or string, real number values and NaN values should be converted to string.

### ISSUE THREAD

**Issue by k3ybladewielder** [catboost/catboost#1975]
catboost version: '1.0.3'
Operating System: Ubuntu 21.10

Problem:
Im trying to pass cat_features param and the error persists even passing as integer, string and the indices. I also check #608 but nothing works

```cat_feat = ['week', 'brand', 'pos']
cat_feats = list(range(len(db_hist[cat_feat].columns)))
# or
# cat_feats = np.where(db_hist.dtypes != float)[0]
num_feat = ['price', 'hist_price', 'hist_quant']
target_feat = 'quant'

db_pool = Pool(db_hist[num_feat], label=db_hist[target_feat], cat_features = cat_feats)

# criando e importando o modelo
cat_model = CatBoostRegressor(loss_function='RMSE', n_estimators=500, silent=True)
cat_model.fit(db_pool)

# predict
cat_preds = cat_model.predict(db_pool)

CatBoostError: Invalid type for cat_feature[non-default value idx=0,feature_idx=0]=149.99 : cat_features must be integer or string, real number values and NaN values should be converted to string.```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@k3ybladewielder the error message is about the value of the zeroth factor of the zeroth sample. if this is a categorical factor, then it should contain integers and strings only, and real numbers and nans should be converted to strings.

**Comment by k3ybladewielder** [comment]
> the error message is about the value of the zeroth factor of the zeroth sample. if this is a categorical factor, then it should contain integers and strings only, and real numbers and nans should be converted to strings.

contain only strings

**Comment by kizill** [comment]
Hello! 
`db_pool = Pool(db_hist[num_feat], label=db_hist[target_feat], cat_features = cat_feats)` - in this line, you select only numeric features to pass to Pool constructor and are marking some of them as categorical ones. I guess you want something like this:
```python
cat_feats = list(db_hist.select_dtypes('object', 'category').columns)
db_pool = Pool(db_hist.drop(target_feat, axis=1), label=db_hist[target_feat], cat_features = cat_feats)
...
```

**Comment by k3ybladewielder** [comment]
> Hello! `db_pool = Pool(db_hist[num_feat], label=db_hist[target_feat], cat_features = cat_feats)` - in this line, you select only numeric features to pass to Pool constructor and are marking some of them as categorical ones. I guess you want something like this:
> 
> ```python
> cat_feats = list(db_hist.select_dtypes('object', 'category').columns)
> db_pool = Pool(db_hist.drop(target_feat, axis=1), label=db_hist[target_feat], cat_features = cat_feats)
> ...
> ```

thanks
