### ISSUE TITLE
Catboost installation on Linux aarch64 using conda

### ISSUE THREAD

**Issue by VitalyPetrov** [catboost/catboost#1981]
Hi there!

I`m trying to install catboost on docker container launched on my local machine (Macbook Pro 13 M1). However I cannot find the required build for linux aarch:

```bash
~ > docker run -it condaforge/miniforge3 /bin/bash
(base) > uname -a
Linux 185767632d44 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
(base) > conda install -c conda-forge catboost
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - catboost

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-aarch64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Can you please clarify -- it it a normal behavior (there is no build for linux aarch yet) or there is something wrong on my attempt?

**Comment by proinsias** [comment]
I believe this is an issue with there being no build for this architecture yet – I can't install this **directly** (no Docker involved) on my M1 Mac either:

```bash
> python3 -m pip install catboost
ERROR: Could not find a version that satisfies the requirement catboost (from versions: none)
ERROR: No matching distribution found for catboost
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@VitalyPetrov 
CatBoost Python package for Arm64 should be build manually on an x86_64 host.
Here is a useful comment on this.
https://github.com/catboost/catboost/issues/1857#issuecomment-929690979

**Comment by arestifo** [comment]
Hi everyone, I have pre-built wheels and build instructions over at https://github.com/catboost/catboost/issues/2091#issuecomment-1248876930

**Comment by andrey-khropov** [comment]
>  I can't install this directly (no Docker involved) on my M1 Mac either:

@proinsias CatBoost works on M1 Macs natively since release 1.0.5 - https://github.com/catboost/catboost/issues/1526#issuecomment-1108508638. But some older pip versions do not recognize `universal2` tags. With the updated pip (at least 21.2+) I can successfully install and run CatBoost python package on M1 Mac.

**Comment by andrey-khropov** [comment]
For building CatBoost components for Linux aarch64 see my comments - https://github.com/catboost/catboost/issues/2091#issuecomment-1486551204 and below.

**Comment by andrey-khropov** [comment]
CatBoost 1.2 with Linux aarch64 wheels has been released so with the help of https://github.com/conda-forge/catboost-feedstock/pull/108 Conda packages are also available now.
