### ISSUE TITLE
Any plans to get catboost working in R on an M1 Mac?

### ISSUE THREAD

**Issue by agracian** [catboost/catboost#1985]
Problem: Any plans to get catboost working in R on an M1 Mac?  shared object ‘libcatboostr.so’ not found
catboost version: Any up to 1.0.4
Operating System: macOS Monterey 12.1 on a Mac M1 Mini
CPU: M1
GPU:

Using R version 4.1.2 (2021-11-01) -- "Bird Hippie"

Keep getting...

> library(catboost)
Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib):
 shared object ‘libcatboostr.so’ not found

**Comment by mscbuck** [comment]
There is a separate thread going on here regarding this: https://github.com/catboost/catboost/issues/1526

Simply put, still waiting. Last update was late November. There is a binary of an older version that seems to work that is linked in that thread

**Comment by kizill** [comment]
Released as part of 1.0.5

**Comment by mscbuck** [comment]
Should this one still be closed given that people are still receiving errors with R installs as outlined near the bottom of https://github.com/catboost/catboost/issues/1526 ?

**Comment by agracian** [comment]
Hi When trying to install 1.05 on my M1 Mac 
I get the following error:> BINARY_URL ="https://github.com/catboost/catboost/releases/download/v1.0.5/catboost-R-Darwin-1.0.5.tgz"> devtools::install_url(BINARY_URL, INSTALL_opts = c("--no-multiarch", "--no-test-load"))Downloading package from url: https://github.com/catboost/catboost/releases/download/v1.0.5/catboost-R-Darwin-1.0.5.tgz✓  checking for file ‘/private/var/folders/5f/mh2kfwkn6yd1nyzf95f01vf80000gn/T/RtmpjkPlzk/remotes16c6a3bf9fc/catboost/DESCRIPTION’ ...─  preparing ‘catboost’:✓  checking DESCRIPTION meta-information ...─  checking for LF line-endings in source and make files and shell scripts─  checking for empty or unneeded directories─  building ‘catboost_1.0.5.tar.gz’   * installing *source* package ‘catboost’ ...** using staged installation** R** inst** byte-compile and prepare package for lazy loading** help*** installing help indices** building package indices** checking absolute paths in shared objects and dynamic librariesERROR: some hard-coded temporary paths could not be fixed* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/catboost’* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/catboost’Warning message:In i.p(...) :  installation of package ‘/var/folders/5f/mh2kfwkn6yd1nyzf95f01vf80000gn/T//RtmpjkPlzk/file16c6679914a3/catboost_1.0.5.tar.gz’ had non-zero exit status
BestAlex    On Monday, 25 April 2022, 14:30:04 CEST, Stanislav Kirillov ***@***.***> wrote:  
 
 


Closed #1985.

**Comment by agracian** [comment]
Hi, When trying to install 1.05 on my M1 Mac 
I get the following error:> BINARY_URL ="https://github.com/catboost/catboost/releases/download/v1.0.5/catboost-R-Darwin-1.0.5.tgz"> devtools::install_url(BINARY_URL, INSTALL_opts = c("--no-multiarch", "--no-test-load"))Downloading package from url: https://github.com/catboost/catboost/releases/download/v1.0.5/catboost-R-Darwin-1.0.5.tgz✓  checking for file ‘/private/var/folders/5f/mh2kfwkn6yd1nyzf95f01vf80000gn/T/RtmpjkPlzk/remotes16c6a3bf9fc/catboost/DESCRIPTION’ ...─  preparing ‘catboost’:✓  checking DESCRIPTION meta-information ...─  checking for LF line-endings in source and make files and shell scripts─  checking for empty or unneeded directories─  building ‘catboost_1.0.5.tar.gz’   * installing *source* package ‘catboost’ ...** using staged installation** R** inst** byte-compile and prepare package for lazy loading** help*** installing help indices** building package indices** checking absolute paths in shared objects and dynamic librariesERROR: some hard-coded temporary paths could not be fixed* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/catboost’* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/catboost’Warning message:In i.p(...) :  installation of package ‘/var/folders/5f/mh2kfwkn6yd1nyzf95f01vf80000gn/T//RtmpjkPlzk/file16c6679914a3/catboost_1.0.5.tar.gz’ had non-zero exit status
BestAlex

    On Monday, 25 April 2022, 14:40:09 CEST, Michael Clutterbuck ***@***.***> wrote:  
 
 


Should this one still be closed given that people are still receiving errors with R installs as outlined near the bottom of #1526?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
To workaround this issue, please install with --no-staged-install @agracian

**Comment by agracian** [comment]
Thanks Evgueni,
devtools::install_url(BINARY_URL, INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))

seems to work
BestAlex 

    On Tuesday, 26 April 2022, 20:43:22 CEST, Evgueni Petrov ***@***.***> wrote:  
 
 


To workaround this issue, please install with --no-staged-install @agracian

**Comment by agracian** [comment]
Spoke too soon...
Get an error message when trying to load the library.
> library(catboost)Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib): shared object ‘libcatboostr.so’ not found 
Alex
    On Sunday, 1 May 2022, 08:24:51 CEST, Alexander Gracian ***@***.***> wrote:  
 
 Thanks Evgueni,
devtools::install_url(BINARY_URL, INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))

seems to work
BestAlex 

    On Tuesday, 26 April 2022, 20:43:22 CEST, Evgueni Petrov ***@***.***> wrote:  
 
 


To workaround this issue, please install with --no-staged-install @agracian

**Comment by mscbuck** [comment]
@agracian you can fix this by manually downloading the [libcatboostr-darwin.so](https://github.com/catboost/catboost/releases/download/v1.0.5/libcatboostr-darwin.so) file from the Releases page, renaming it to just `libcatboostr.so`, and manually placing it in the library's install directory

**Comment by agracian** [comment]
Thanks. It worked.
Appreciated.BestAlex    On Sunday, 1 May 2022, 08:26:38 CEST, Alexander Gracian ***@***.***> wrote:  
 
 Spoke too soon...
Get an error message when trying to load the library.
> library(catboost)Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib): shared object ‘libcatboostr.so’ not found 
Alex
    On Sunday, 1 May 2022, 08:24:51 CEST, Alexander Gracian ***@***.***> wrote:  
 
 Thanks Evgueni,
devtools::install_url(BINARY_URL, INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))

seems to work
BestAlex 

    On Tuesday, 26 April 2022, 20:43:22 CEST, Evgueni Petrov ***@***.***> wrote:  
 
 


To workaround this issue, please install with --no-staged-install @agracian

**Comment by faraanakomidi** [comment]
I am trying to install GLM3r in my mac Pro(12.6) 

I use this code :
devtools::install_github("GLEON/GLM3r", ref = "GLMv.3.1.0a3")
and I got this error :

Downloading GitHub repo GLEON/GLM3r@GLMv.3.1.0a3
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/8p/db7_6hmd27b8x9mzg6qh_5k00000gn/T/Rtmp3as7Dn/remotes45c6c103ec1/GLEON-GLM3r-a3c1fa0/DESCRIPTION’ ...
─  preparing ‘GLM3r’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘GLM3r_3.1.2.tar.gz’
   
* installing *source* package ‘GLM3r’ ...
** using staged installation
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
ERROR: some hard-coded temporary paths could not be fixed
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/GLM3r’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/8p/db7_6hmd27b8x9mzg6qh_5k00000gn/T//Rtmp3as7Dn/file45c1e882854/GLM3r_3.1.2.tar.gz’ had non-zero exit status
  
  
  I would appreciate it if you could help me to fix this problem.

**Comment by hamzeiehsan** [comment]
> 

try: devtools::install_github("GLEON/GLM3r", ref = "GLMv.3.1.0a3", INSTALL_opts="--no-staged-install")

**Comment by pworts** [comment]
I have been trying for 2 days to install catboost onto my M1 silicon mac. When I try in terminal using the R CMD INSTALL --no-test-load[my path here], using catboost_1.2.2, catboost-R-darwin-universal2-1.2.2, or catboost-R-Darwin-1.2.2,  I get this error: "ERROR: some hard-coded temporary paths could not be fixed"

When I try to install via R Studio two different ways I get this: > devtools::install_url('https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib', INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib
Error: Failed to install 'unknown package' from URL:
  Don't know how to decompress files with extension dylib
Warning message:
In devtools::install_url("https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib",  :
  Arguments in `...` must be used.
✖ Problematic argument:
• INSTALL_opts = c("--no-multiarch", "--no-test-load",
  "--no-staged-install")
ℹ Did you misspell an argument name?

and 

> install.packages("/my path/catboost_1.2.2.tar.gz", repos = NULL, type = "source")
ERROR: some hard-coded temporary paths could not be fixed

I also tried it with these other options: INSTALL_opts = "--no-test-load", "- -no-staged-install")

Looking for guidance before I start breaking stuff.

Thank you in advance

**Comment by mscbuck** [comment]
> I have been trying for 2 days to install catboost onto my M1 silicon mac. When I try in terminal using the R CMD INSTALL --no-test-load[my path here], using catboost_1.2.2, catboost-R-darwin-universal2-1.2.2, or catboost-R-Darwin-1.2.2, I get this error: "ERROR: some hard-coded temporary paths could not be fixed"
> 
> When I try to install via R Studio two different ways I get this: > devtools::install_url('https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib', INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install")) Downloading package from url: https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib Error: Failed to install 'unknown package' from URL: Don't know how to decompress files with extension dylib Warning message: In devtools::install_url("https://github.com/catboost/catboost/releases/download/v1.2.2/libcatboostr-darwin.dylib", : Arguments in `...` must be used. ✖ Problematic argument: • INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install") ℹ Did you misspell an argument name?
> 
> and
> 
> > install.packages("/my path/catboost_1.2.2.tar.gz", repos = NULL, type = "source")
> > ERROR: some hard-coded temporary paths could not be fixed
> 
> I also tried it with these other options: INSTALL_opts = "--no-test-load", "- -no-staged-install")
> 
> A third option where I put the file ("libcatboostr.so) into the libs folder has also not been recognized by r studio after restarting the session and quitting the app. Looking for guidance before I start breaking stuff.
> 
> Thank you in advance

You should not be trying to install the .dylib file, that is why. You need to be installing the .tar.gz

`devtools::install_url('https://github.com/catboost/catboost/releases/download/v1.2.2/catboost-R-darwin-universal2-1.2.2.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))
`

**Comment by pworts** [comment]
Thank you!  This worked perfectly!! No more gray hairs
