### ISSUE TITLE
why catboost can't deal nan features like Xgboost and LightGBM?

### ISSUE THREAD

**Issue by lyhue1991** [catboost/catboost#1987]

**Comment by k3ybladewielder** [comment]
CatBoost can handle missing values internally as [FAQ says](https://catboost.ai/en/docs/concepts/faq). 


> Does CatBoost require preprocessing of missing values?
> CatBoost can handle missing values internally. None values should be used for missing value representation.
> If the dataset is read from a file, missing values can be represented as strings like N/A, NAN, None, empty string and the like.
> Refer to the Missing values processing section for details.


But the documentation to [how do that](https://catboost.ai/en/docs/concepts/algorithm-missing-values-processing) is not much clear.

**Comment by kizill** [comment]
@k3ybladewielder Thank you for answer!
@lyhue1991 As @k3ybladewielder already set, CatBoost supports NaN values for numeric features. By default, in our quantization procedure (on data preprocessing stage before training) we are creating distinct bucket for such values, and we are placing it either on the left side of all the other values (may be considered as setting -inf value to them) or to the right side (substitution of +inf). And by distinct bucket i mean that we are filtering such values for building honest quantization grid for floats, then we are adding special bucket for such NaN values.

**Comment by Llamrei** [comment]
Nevermind, I see it is [here](https://github.com/catboost/catboost/blob/53b1d9dd3e832f9af70f1a434997f5a71d35df09/catboost/private/libs/quantization/utils.h#L69C5-L85C6)
