### ISSUE TITLE
DLL load failed while importing _catboost: The specified module could not be found.

### ISSUE THREAD

**Issue by zhixx018** [catboost/catboost#1988]
Problem: error meesage about catboost loading failure
catboost version: 1.0.3
Operating System: win11
CPU: intel i5
GPU:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12612/2110785635.py in <module>
      2 import numpy as np
      3 np.set_printoptions(precision=4)
----> 4 import catboost
      5 from catboost import datasets
      6 from catboost import *

D:\Programs\anaconda\envs\mlenv\lib\site-packages\catboost\__init__.py in <module>
----> 1 from .core import (
      2     FeaturesData, EFstrType, EShapCalcType, EFeaturesSelectionAlgorithm, Pool, CatBoost,
      3     CatBoostClassifier, CatBoostRegressor, CatBoostRanker, CatBoostError, cv, train, sum_models, _have_equal_features,
      4     to_regressor, to_classifier, to_ranker, MultiRegressionCustomMetric, MultiRegressionCustomObjective,
      5     MultiTargetCustomMetric, MultiTargetCustomObjective

D:\Programs\anaconda\envs\mlenv\lib\site-packages\catboost\core.py in <module>
     41 _typeof = type
     42 
---> 43 from .plot_helpers import save_plot_file, try_plot_offline
     44 from . import _catboost
     45 from .metrics import BuiltinMetric

D:\Programs\anaconda\envs\mlenv\lib\site-packages\catboost\plot_helpers.py in <module>
      1 import warnings
      2 
----> 3 from . import _catboost
      4 fspath = _catboost.fspath
      5 

ImportError: DLL load failed while importing _catboost: The specified module could not be found.

**Comment by zhixx018** [comment]
At the moment, I go back to 0.26.1 to solve this importing issue.

**Comment by kizill** [comment]
Hello!
Do this issue persist in 1.0.4 version?

**Comment by zhixx018** [comment]
Yes, the most updated version is functioning well on my end.

**Comment by kizill** [comment]
Great news! Thank you for testing:) Closing as solved😺
