### ISSUE TITLE
Pool Weights Confusion

### ISSUE THREAD

**Issue by AtomSub** [catboost/catboost#1989]
Problem: Length of weights list does not match length of data in python
`train_data = cat.Pool(data=train, cat_features=features, weight=weights)`

Where train is a pandas dataframe and weights is a list based on number of columns in the data.
I receive the error that the lengths don't match, but the values shown make it clear that the length being looked at for the data is the number of rows in the dataframe, not number of columns. 

Am I misunderstanding the purpose of the weight parameter? I would like to weight certain columns higher than others. 

If I can't do it this way, should I create separate models using different columns of the dataframe, then combine models?

**Comment by blahiri** [comment]
First, the general disclaimer. I am not from the CatBoost team, or associated with Yandex. I am just another user of CatBoost trying to be of any possible help.

Regarding your point, _I would like to weight certain columns higher than others_. I think you are looking for the `feature_weights` parameter _when initializing the model_.

<pre>
class CatBoostClassifier(iterations=None,
                         learning_rate=None,
                         depth=None,
                         ...
                         <b>feature weights=None</b>,
                         ...
                        )
</pre>

Here are the relevant links to help you out,

[CatBoostClassifier](https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier)

[feature_weights](https://catboost.ai/en/docs/references/training-parameters/common#feature_weights)

Feel free to replace classifier with regressor as needed. Also, note that this is used when initializing the model, _not when fitting the model, or passing data via a_ `Pool`·

The code snippet you have shown can be used if you wanted to _adjust the weights per row_.

cat.Pool(data= train, cat_features=features, `weight=weights`)

Here's the relevant link,

[Pool weight](https://catboost.ai/en/docs/concepts/python-reference_pool#weight)

Just FYI in case it helps, row-wise weights can also be specified when fitting the model by using the `sample_weight` parameter.

<pre>
fit(X,
    y=None,
    cat_features=None,
    text_features=None,
    <b>sample_weight=None</b>,
    ...
   )
</pre>

[sample_weight](https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier_fit#sample_weight)

Hope this helps.

**Comment by kizill** [comment]
@blahiri Thank you a lot  for such an extensive and correct answer!
@AtomSub as @blahiri have already written, you are passing a parameter, that sets weights per-row. If you need per-feature weights for score function , this is a parameter of training process, not a parameter of dataset. And it's controlled by `feature_weights` parameter. Feel free to reopen if any questions remain 😸

**Comment by AtomSub** [comment]
@kizill @blahiri I really appreciate you taking the time to help me out. I'll check those parameters out and let you know if I have any other questions.
