### ISSUE TITLE
Monotonic Constraints

### ISSUE THREAD

**Issue by Denisevi4** [catboost/catboost#199]
Hi guys,

XGBoost has Monotonic Constraints regularization where one can restrict a prediction to be monotonic as a function of selected variables. http://xgboost.readthedocs.io/en/latest/tutorials/monotonic.html

It would be nice for you to implement it. It appears to be an important regularization in some cases.

Thanks!

**Comment by annaveronika** [comment]
Good idea, thanks!

**Comment by samnolen** [comment]
I would like to work on this.

**Comment by annaveronika** [comment]
That would be great! That is a very interesting but complicated task. You need to read through the code to understand it first.
You start with libs/train_lib/train_model.cpp - it's where the training starts.
All the logic is in /libs/algo.

An important part of the algorithm is that it uses symmetric trees and builds them level by level.
Symmetric tree is a tree where nodes of each level use the same split. This allows to encode path to leaf with an idex.
For example, there is a tree with depth 2. Split on the first level is f1<2, split on the second level is f2<4.
Then the object with f1=5, f2=0 will have leaf with number 01b.

**Comment by JoshuaC3** [comment]
Another bonus for this is model interpretation. By fixing a major dependent variable to monotonic and see small to no drop in performance, you can justify doing this and make it much easier to explain what is going on to non-technical colleagues.

**Comment by aldanor** [comment]
Having monotonic constraints is pretty much a requirement in many areas, would definitely be nice to have it.

**Comment by HugoDLopes** [comment]
Hi, I'm feeling the need for it as well, and that's the only reason I cannot use Catboost right now. Is it in the pipeline for next release?

**Comment by AldrChist** [comment]
It worth to notice, that libraries like GBM and XGBoost are only provide locally monotonic functions and could violate monotonic restrictions while working with multidimentional deep trees ([link](https://groups.google.com/forum/#!topic/gbm-dev/qEFll2UbXnI)).

There are some papers on how to transform a locally monotonic tree to a globally monotonic ([link](https://dl.acm.org/citation.cfm?id=568577)), but these algorithms may be computational expensive and hard to integrate with the gradient boosting.

It seems that oblivious (or symmetric) trees in the CatBoost are much better suited for globally monotonic trees.

**Comment by annaveronika** [comment]
This is implemented in catboost 0.16.2

**Comment by yeonman** [comment]
in my case, when doing catboostregeressor i added  monotone_constraint like [-1,0,0, ...] 
after that,  saw too much drop in performance. 
usually is monotonic constraints affecting to model  more in catboost than in xgboost?

**Comment by diegoquezadac** [comment]
> This is implemented in catboost 0.16.2

Where is this implementation available ? I would love to see the actual code.

**Comment by andrey-khropov** [comment]
> > This is implemented in catboost 0.16.2
> 
> Where is this implementation available ? I would love to see the actual code.

See [this module](https://github.com/catboost/catboost/blob/master/catboost/private/libs/algo/monotonic_constraint_utils.h) and where it is used.
