### ISSUE TITLE
Unknown Class Labels

### ISSUE THREAD

**Issue by thyllmuller** [catboost/catboost#1996]
Problem: Trying to do multiclass, getting "Unknown class label:" problem
catboost version: 1.0.4
Operating System: Windows 11
CPU: i5 8600k 4.8ghz oc
GPU: 1080ti

> Traceback (most recent call last):
>   File "C:\Users\~\Project\MainCode2.py", line 40, in <module>
>     model.fit(X_train, y_train,
>   File "C:\Users\~\Programs\Python\Python39\lib\site-packages\catboost\core.py", line 4768, in fit
>     self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
>   File "C:\Users\~\Programs\Python\Python39\lib\site-packages\catboost\core.py", line 2089, in _fit
>     self._train(
>   File "C:\Users\~\Programs\Python\Python39\lib\site-packages\catboost\core.py", line 1516, in _train
>     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
>   File "_catboost.pyx", line 4402, in _catboost._CatBoost._train
>   File "_catboost.pyx", line 4451, in _catboost._CatBoost._train
> _catboost.CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:242: Unknown class label: "hi-nrg"

Code in question:

class_train, class_test = ClassTrain_Import.class_load() #Class train is distinct from test; test csv has no "top_genre" col.

class_train = class_train.dropna(how="any").copy()
class_train.drop(columns=["Id"])
class_train = class_train.reset_index().copy()
X = class_train.drop(columns=["top_genre"])
y = class_train["top_genre"]

X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.95)
X_test = class_test

cat_features_indices = np.where(X.dtypes != float)[0]

model = CatBoostClassifier(custom_loss=[metrics.Accuracy()],
                           logging_level='Silent')

model.fit(X_train, y_train,
          cat_features=cat_features_indices,
          eval_set=(X_validation, y_validation),
          # logging_level='Verbose',  # you can uncomment this for text output
          plot=True
          )

____

I have done some research, and I somewhat understand why it is throwing this error - however without me setting a training size of >.95 it will cause this error.

But, if I have not misunderstood, this makes my model quite bad if I cannot validate it on a big enough validation set?

Is there a method to improve the parameters such that I do not get this error? 

My assumption is that it does not find the same label in X and y - therefore it has the error. However, can this be ignored or can I improve this by some method? 

Thank you

**Comment by andrey-khropov** [comment]
This error means that you have some labels in `y_validation` that are not present in `y_train`. 
If you have such a situation it is likely that you should consider additional preprocessing instead of just completely random train_test_split. Like stratified sampling to ensure that classes are distributed in roughly similar proportions in both `train` and `validation` datasets .

If you insist on having labels in `y_validation` that are not present in `y_train` (the model will always mispredict on such samples because there have been no examples with such labels to train on) you can overcome this error by specifying all possible labels explicitly by passing them to `class_names` parameter of `CatBoostClassifier` like that:

```py
model = CatBoostClassifier(custom_loss=[metrics.Accuracy()],
logging_level='Silent',
class_names=list(set(y)))
```

**Comment by andrey-khropov** [comment]
Duplicate if #1531
