### ISSUE TITLE
Error displaying widget (plot) while training CatBoost

### ISSUE THREAD

**Issue by achomiczewski** [catboost/catboost#2002]
Problem: 
For some reason, when `plot = True` while lifting the model, the widget for model training can't be displayed and instead following error is included 
![image](https://user-images.githubusercontent.com/99646156/153834581-698558eb-2366-4416-8bf1-87967f6f0747.png)
the browser console additionally returns the following errors:
![image](https://user-images.githubusercontent.com/99646156/153834801-3f785c23-a8cc-450d-a2da-a00357a0f404.png)
![image](https://user-images.githubusercontent.com/99646156/153834825-1f78038a-6d96-4f7e-857c-4ddd0d1cbfb0.png)
![image](https://user-images.githubusercontent.com/99646156/153834858-12dec8bb-eaac-48d8-a9ab-d2fd0fc09e20.png)
![image](https://user-images.githubusercontent.com/99646156/153834886-eb314c2e-b5a2-4d60-9126-21c8a9bf0ac5.png)
![image](https://user-images.githubusercontent.com/99646156/153834922-4116dcd3-1241-4de3-bcbc-d4a9ec931e3c.png)
![image](https://user-images.githubusercontent.com/99646156/153834955-b413a9ba-b434-4367-9903-a55b78af0294.png)
catboost version: 1.0.4
Operating System:  Ubuntu 18.04.6 LTS (Bionic Beaver)
CPU: Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
GPU: Tesla V100-PCIE
GPU Drivers: Driver Version: 460.91.03    CUDA Version: 11.2

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Which Jypiter are you using?

**Comment by LyzhinIvan** [comment]
Hi, @achomiczewski! Is it a local jupyter notebook/lab or something like Google Colab?

**Comment by achomiczewski** [comment]
Hi @LyzhinIvan I am using 
jupyterhub                1.3.0                    pypi_0    pypi
jupyterlab                3.3.0b0                  pypi_0    pypi
currently.
The environment is remote, provided by my employer, very similar to https://hub.docker.com/r/jupyter/datascience-notebook (most likely, as far as my privileges go, with asserting such things).

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
according to one of our users, the problem with plots may be solved by reloading the jupyter notebook/lab

**Comment by marowu** [comment]
Hi, I was having a similar issue, the error was slightly different and I'm using jupyter notebook. Still, maybe the solution will work for you [achomiczewski](https://github.com/achomiczewski), as long as you're able to tweak the environment.

I've resolved the issue by downgrading jupyterlab-widgets to 1.1.1. To get a working set-up:
```
python3.10 -m venv ./
source ./bin/activate
pip install --upgrade pip setuptools
pip install catboost notebook 
pip install ipywidgets==7.7.2 jupyterlab-widgets==1.1.1
jupyter notebook
```
It is than possible to run 
```
from catboost import CatBoostClassifier, Pool

train_data = [[1, 3], [0, 4], [1, 7], [0, 3]]
train_labels = [1, 0, 1, 1]

model = CatBoostClassifier(learning_rate=0.03)

model.fit(train_data,
       train_labels,
       verbose=False,
       plot=True)
```
ref: https://catboost.ai/en/docs/features/visualization_jupyter-notebook#add-a-training-a-model-using

No other steps were required.

I hope this helps.

**Comment by OfficerChul** [comment]
above fix still didn't fix the error

**Comment by andrey-khropov** [comment]
> above solution still didn't fix the error

Which CatBoost version are you getting this error on? There were issues with ipywidgets and jupyterlab before version 1.2.1 but they had been resolved.

**Comment by OfficerChul** [comment]
> > above solution still didn't fix the error
> 
> Which CatBoost version are you getting this error on? There were issues with ipywidgets and jupyterlab before version 1.2.1 but they had been resolved.

For catboost, I am using `1.2.2`, for ipywidgets, I am using `7.7.2`, for jupyter lab, I am using `4.0.9`

**Comment by andrey-khropov** [comment]
> > > above solution still didn't fix the error
> > 
> > 
> > Which CatBoost version are you getting this error on? There were issues with ipywidgets and jupyterlab before version 1.2.1 but they had been resolved.
> 
> For catboost, I am using `1.2.2`, for ipywidgets, I am using `7.7.2`, for jupyter lab, I am using `4.0.9`

There might be issues with jupyterlab 4.x: #2533 . Can you try jupyterlab 3.x ?

**Comment by OfficerChul** [comment]
> > > > above solution still didn't fix the error
> > > 
> > > 
> > > Which CatBoost version are you getting this error on? There were issues with ipywidgets and jupyterlab before version 1.2.1 but they had been resolved.
> > 
> > 
> > For catboost, I am using `1.2.2`, for ipywidgets, I am using `7.7.2`, for jupyter lab, I am using `4.0.9`
> 
> There might be issues with jupyterlab 4.x: #2533 . Can you try jupyterlab 3.x ?

Thanks for your help. I just tried jupyter lab version 3.6, and it works now. Will jupyter lab version 4 also be compatible in the future?

**Comment by andrey-khropov** [comment]
> Will jupyter lab version 4 also be compatible in the future?

That's what https://github.com/catboost/catboost/issues/2533 is about.
