### ISSUE TITLE
catboost eval sample weight

### ISSUE THREAD

**Issue by renzeya** [catboost/catboost#2004]
Problem:
does it support eval data set sample weight?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
CatBoost accepts eval sets of type CatBoost.Pool which may specify sample weights.
https://catboost.ai/en/docs/concepts/python-reference_catboost_fit#eval_set
https://catboost.ai/en/docs/concepts/python-reference_pool_set_weight

If this scenario is not working for you, please post a reproducer here.
