### ISSUE TITLE
PMML format

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#201]
There is a converter to core ml format, which can be used to understand better the model structure.
https://github.com/catboost/catboost/blob/master/catboost/libs/model/coreml_helpers.cpp

**Comment by billy-odera** [comment]
> There is a converter to core ml format, which can be used to understand better the model structure.
> https://github.com/catboost/catboost/blob/master/catboost/libs/model/coreml_helpers.cpp

Can we have catboost in PMML format?

**Comment by annaveronika** [comment]
This is implemented now, please build from source or use or wait for the next release which will happen in a couple of days!
