### ISSUE TITLE
[Query] Passing Ordinal Data to CatBoost using Pandas CategoricalDtype

### ISSUE THREAD

**Issue by blahiri** [catboost/catboost#2013]
Hi Team 

Just wanted to check whether CatBoost takes `feature ordinality` into consideration if I specify Pandas `CategoricalDType` in the input dataframe. Here's a sample code snippet to help illustrate what I am asking, 

<pre>
from pandas.api.types import CategoricalDtype

df['Tier'] = df['Tier'].astype(CategoricalDtype(categories = ['TIER 2', 
                                                              'TIER 1', 
                                                              'TIER 0'
                                                             ], ordered = True))
</pre>

Python 3.6.1 (Anaconda 4.4.0 64-bit)
catboost version: 1.0.4
Operating System: Windows 10 64-bit
CPU: Intel Core i5 8350U
GPU: None
RAM: 16GB

**Comment by ek-ak** [comment]
Hello! CatBoost doesn't take into account  feature ordinality in that case.

**Comment by blahiri** [comment]
Hi, thank you for replying. So what is the best way to pass ordinal data to CatBoost? I would need some suggestions please.

**Comment by blahiri** [comment]
Hi, any updates on this please?

**Comment by LyzhinIvan** [comment]
You can do label encoding according to relative order of possible values and pass to CatBoost as simple numeric feature. Like this:
`df['Tier'] = df['Tier'].replace(to_replace=['Tier 0', 'Tier 1', 'Tier 2'], value=[0, 1, 2])`

**Comment by blahiri** [comment]
Perfect, thank you for the suggestion.
