### ISSUE TITLE
CatBoostError: Invalid loss_function='R2': for regressor use RMSE, MultiRMSE, SurvivalAft, MAE, Quantile, LogLinQuantile, Poisson, MAPE, Lq or custom objective object

### ISSUE THREAD

**Issue by blahiri** [catboost/catboost#2014]
Hi Team

I am trying to use the `R2` metric with CatBoostRegressor. The CatBoost documentation [Regression: objectives and metrics](https://catboost.ai/en/docs/concepts/loss-functions-regression) does mention `R2` as an available metric.

![image](https://user-images.githubusercontent.com/96404169/155845033-c4fdd6c2-10cd-4751-a8ed-82d285724cd1.png)

However, I am getting the following error when using R2 as objective and/or as eval_metric,

<pre>
CatBoostError: Invalid loss_function='R2': for regressor use RMSE, MultiRMSE, SurvivalAft, MAE, Quantile, 
LogLinQuantile, Poisson, MAPE, Lq or custom objective object
</pre>

Here's part of the code I am using

<pre>
clf_params = {
    'cat_features': categorical_features,
    'bagging_temperature': 0,
    'boosting_type': 'Plain',
    'bootstrap_type': 'MVS',
    'boost_from_average': True,
    'border_count': 254,
    'counter_calc_method': 'SkipTest',
    'ctr_target_border_count': 1,
    'depth': 10,
    'early_stopping_rounds': 50,
    'eval_metric': 'R2',
    'feature_border_type': 'MaxLogSum',
    'grow_policy': 'Lossguide',
    'iterations': 2000,
    'learning_rate': 0.1,
    '12_leaf_reg': 4,
    'max_ctr_complexity': 4,
    'max_leaves': 31,
    'objective': 'R2',
    'one_hot_max_size': 3,
    'penalties_coefficient': 1,
    'posterior_sampling': False,
    'random_seed': 42,
    'random_strength': 17,
    'score function': 'L2',
    'use_best_model': True,
    'used_ram_limit': used ram_limit
}

# Initialize CatBoostRegressor
model = CatBoostRegressor(**clf_params)
</pre>

And here's the part that generates the error mentioned above,
<pre>
model.fit(X_train, 
          y_train, 
          cat_features = categorical_features, 
          eval_set = (X_test, y_test), 
          early_stopping rounds = 50, 
          use_best_model = True, 
          verbose = False
         )
</pre>

Could you please look into it and advise. Surprisingly, the documentation page above doesn't seem to mention anything about `SurvivalAft` being an available regression metric.

I have attached a screenshot of the error traceback, in case it helps. Please let me know in case you need any further information from me.

Python 3.6.1 (Anaconda 4.4.0 64-bit)
catboost version: 1.0.4
Operating System: Windows 10 64-bit
CPU: Intel Core i5 8350U
GPU: None
RAM: 16GB

![image](https://user-images.githubusercontent.com/96404169/155845668-70a191ec-a9af-4860-a3b5-ae0ca3921e6c.png)

**Comment by blahiri** [comment]
Hi, any updates on this please?

**Comment by LyzhinIvan** [comment]
Hi, @blahiri!
Documentation of R2 says: "**Can't be used for optimization**". That means that you can't set it as objective.`eval_metric="R2"` works well.

**Comment by blahiri** [comment]
Thank you for the clarification. What about 'SurvivalAft'? The CatBoostError message shown above seems to mention SurvivalAft, but I can't seem to locate anything about it, or how to use it as a metric in the documentation pages.

**Comment by LyzhinIvan** [comment]
We forgot to add it to the documentation. You can read about it in [tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/regression/survival.ipynb).

**Comment by blahiri** [comment]
That helps. Thank you very much.
