### ISSUE TITLE
install R   shared object ‘libcatboostr.so’ not found

### ISSUE THREAD

**Issue by JianGuoZhou3** [catboost/catboost#2016]
Problem:  shared object ‘libcatboostr.so’ not found
catboost version: > install.packages("~/t12b/zhou/R/catboost-R-Windows-0.20.tgz", repos = NULL, type = .Platform$pkgType)
Operating System: centos7
CPU: 
GPU:

> 
> 
> 
> devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz' failed
Warning message:
Arguments in `...` must be used.
x Problematic argument:
• INSTALL_opts = c("--no-multiarch", "--no-test-load") 
> 
> devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz'
Warning message:
Arguments in `...` must be used.
x Problematic argument:
• INSTALL_opts = c("--no-multiarch", "--no-test-load") 
> install.packages("~/t12b/zhou/R/catboost-R-Windows-0.20.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/home/zhou/Rlib’
(as ‘lib’ is unspecified)
* installing *source* package ‘catboost’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib):
 shared object ‘libcatboostr.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/zhou/Rlib/catboost’
Warning in install.packages :
  installation of package ‘/home/zhou/t12b/zhou/R/catboost-R-Windows-0.20.tgz’ had non-zero exit status

**Comment by Metareflektor** [comment]
Did you find a solution to this error?

**Comment by Metareflektor** [comment]
> Problem: shared object ‘libcatboostr.so’ not found catboost version: > install.packages("~/t12b/zhou/R/catboost-R-Windows-0.20.tgz", repos = NULL, type = .Platform$pkgType) Operating System: centos7 CPU: GPU:
> 
> > devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
> > Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz
> > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > download from 'https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz' failed
> > Warning message:
> > Arguments in `...` must be used.
> > x Problematic argument:
> > • INSTALL_opts = c("--no-multiarch", "--no-test-load")
> > devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
> > Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz
> > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > cannot open URL 'https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Windows-0.20.tgz'
> > Warning message:
> > Arguments in `...` must be used.
> > x Problematic argument:
> > • INSTALL_opts = c("--no-multiarch", "--no-test-load")
> > install.packages("~/t12b/zhou/R/catboost-R-Windows-0.20.tgz", repos = NULL, type = .Platform$pkgType)
> > Installing package into ‘/home/zhou/Rlib’
> > (as ‘lib’ is unspecified)
> 
> * installing _source_ package ‘catboost’ ...
>   ** using staged installation
>   ** R
>   ** inst
>   ** byte-compile and prepare package for lazy loading
>   ** help
>   *** installing help indices
>   ** building package indices
>   ** testing if installed package can be loaded from temporary location
>   Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib):
>   shared object ‘libcatboostr.so’ not found
>   Error: loading failed
>   Execution halted
>   ERROR: loading failed
> * removing ‘/home/zhou/Rlib/catboost’
>   Warning in install.packages :
>   installation of package ‘/home/zhou/t12b/zhou/R/catboost-R-Windows-0.20.tgz’ had non-zero exit status

Did you find a solution to this error?

**Comment by andrey-khropov** [comment]
Well. The error here is pretty obvious - you're trying to install package version for Windows on a Linux host.
The proper name for Linux will be 

```R
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.20/catboost-R-Linux-0.20.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
```

We'll update the documentation to make it clearer.
