### ISSUE TITLE
can't compile Evaluation library on linux clang-12

### ISSUE THREAD

**Issue by pha377** [catboost/catboost#2017]
Problem: can't compile Evaluation library on linux clang-12
catboost version: 1.0.5
Operating System: Linux
CPU: AMD EPYC 7601 32-Core Processor x86_64
GPU: none

root@localhost:~/projects/catboost# make -f make/model_interface_static.CLANG12-LINUX-X86_64.makefile
mkdir -p '/root/projects/catboost/contrib/libs/cxxsupp/builtins'
cc --target=x86_64-linux-gnu -c -o '/root/projects/catboost/contrib/libs/cxxsupp/builtins/addtf3.c.pic.o' '-I/root/projects/catboost' '-I/root/projects/catboostontrib/libs/linux-headers' '-I/root/projects/catboost/contrib/libs/linux-headers/_nf' '-fdebug-prefix-map=/root/projects/catboost=/-B' '-fdebug-prefix-map=/rootug-prefix-map==/-T' -Xclang -fdebug-compilation-dir -Xclang /tmp -pipe -m64 -O3 -fexceptions -fno-common -fuse-init-array -fcolor-diagnostics -faligned-allocatisections -w -DFAKEID=9184729 '-DARCADIA_ROOT=/root/projects/catboost' '-DARCADIA_BUILD_ROOT=/root/projects/catboost' -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_ATURES -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -DN-DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1 -DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -fPIC -mssee4.2 -mpopcnt -mcx16 -fPIC '/root/projects/catboost/contrib/libs/cxxsupp/builtins/addtf3.c'
cc: error: unrecognized command-line option ‘--target=x86_64-linux-gnu’
cc: error: unrecognized command-line option ‘-Xclang’
cc: error: unrecognized command-line option ‘-fdebug-compilation-dir’
cc: error: unrecognized command-line option ‘-Xclang’
cc: error: unrecognized command-line option ‘-fuse-init-array’
cc: error: unrecognized command-line option ‘-fcolor-diagnostics’
cc: error: unrecognized command-line option ‘-faligned-allocation’; did you mean ‘-fsized-deallocation’?
make: *** [make/model_interface_static.CLANG12-LINUX-X86_64.makefile:253: /root/projects/catboost/contrib/libs/cxxsupp/builtins/addtf3.c.pic.o] Error 1

**Comment by pha377** [comment]
It compiles now, thanks!

**Comment by pha377** [comment]
Similar problem with 
make -f make/model_interface.CLANG12-LINUX-X86_64.makefile

g++: error: unrecognized command-line option ‘--target=x86_64-linux-gnu’
g++: error: unrecognized command-line option ‘-Xclang’
g++: error: unrecognized command-line option ‘-fdebug-compilation-dir’
g++: error: unrecognized command-line option ‘-Xclang’
g++: error: unrecognized command-line option ‘-fuse-init-array’
g++: error: unrecognized command-line option ‘-fcolor-diagnostics’
g++: error: unrecognized command-line option ‘-faligned-allocation’; did you mean ‘-fsized-deallocation’?
g++: error: unrecognized command-line option ‘-Wimport-preprocessor-directive-pedantic’
make: *** [make/model_interface.CLANG12-LINUX-X86_64.makefile:6155: /root/projects/catboost/catboost/libs/model_interface/c_api.cpp.pic.o] Error 1

**Comment by andrey-khropov** [comment]
> Similar problem with make -f make/model_interface.CLANG12-LINUX-X86_64.makefile
> 
> g++: error: unrecognized command-line option ‘--target=x86_64-linux-gnu’ g++: error: unrecognized command-line option ‘-Xclang’ g++: error: unrecognized command-line option ‘-fdebug-compilation-dir’ g++: error: unrecognized command-line option ‘-Xclang’ g++: error: unrecognized command-line option ‘-fuse-init-array’ g++: error: unrecognized command-line option ‘-fcolor-diagnostics’ g++: error: unrecognized command-line option ‘-faligned-allocation’; did you mean ‘-fsized-deallocation’? g++: error: unrecognized command-line option ‘-Wimport-preprocessor-directive-pedantic’ make: *** [make/model_interface.CLANG12-LINUX-X86_64.makefile:6155: /root/projects/catboost/catboost/libs/model_interface/c_api.cpp.pic.o] Error 1

That's because you use `g++` as a C++ compiler instead of `clang++`. These Makefiles are only compatible with CLang compiler.

Just set `CC` and `CXX` environment variables as described in documentation:

```
export CXX=/path/to/clang++
export CC=/path/to/clang
```

https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper.

P.S. Note that Makefiles are no longer provided in the master branch since we've switched to CMake-based builds. But building ``model_interface/static`` is broken for now in CMake build in master branch but it will be restored in a couple of days.
