### ISSUE TITLE
Json model

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#202]
As the first step - json model for models on numerical features only.

**Comment by annaveronika** [comment]
There is a converter to core ml format, which can be used to understand better the model structure.
https://github.com/catboost/catboost/blob/master/catboost/libs/model/coreml_helpers.cpp

**Comment by Denisevi4** [comment]
As a temporary solution I was able to convert CoreML to json. 

All done in Python here:

https://github.com/Denisevi4/CoreMLToJson

I didn't check thoroughly. But it seems make sense.

**Comment by annaveronika** [comment]
We finally did it! Now you can save the model as json, here is the pr: https://github.com/catboost/catboost/commit/92c83c84405556a6a9edac00be867b67ac5a615b
The documentation for that will be added soon.

We'll publish a new version on pypi soon - in a week or two. For now you can build from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/
