### ISSUE TITLE
make c++ library without ya is not working

### ISSUE THREAD

**Issue by mhq199657** [catboost/catboost#2025]
Problem:
I followed [this catboost doc](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper) and did 
```
export CXX=/path/to/clang++
export CC=/path/to/clang

make -f make/model_interface.CLANG12-LINUX-X86_64.makefile
```
but failed at
```
clang-12: error: no such file or directory: './catboost/catboost/libs/helpers/flatbuffers/guid.fbs.cpp'
```
I think there should be a codegen step missing.
catboost version: v1.0.4 and head
Operating System: rhel7
CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
GPU: None

**Comment by AlekseiSaff** [comment]
v1.0.6 still the same issue

**Comment by kizill** [comment]
We've switched to CMake and now everything just works. You can follow instructions from our documentation: https://catboost.ai/en/docs/installation/cli-installation-cmake-install
