### ISSUE TITLE
Confidence probability Score in catboostclassifier

### ISSUE THREAD

**Issue by mak-rayate** [catboost/catboost#2028]
Problem:Get Confidence probability Scores for each Predicted Result in Catboost Classifier
catboost version:1.0.4
Operating System:Windows
CPU:16 GB
GPU:NA

Hello All , 
I am stuck at below issue same as below link : 
[link](https://stackoverflow.com/questions/70323521/get-confidence-probability-scores-for-each-predicted-result-in-catboost-classifi)

Can anyone please help me how to get confidence score for each prediction in catboost classifier

**Comment by LyzhinIvan** [comment]
Hi, @mak-rayate! 
You can use `predict_proba` method to get probability for each label.

**Comment by mak-rayate** [comment]
Hey @LyzhinIvan , 

Thank you for reply , predict_proba is a factor can use as confidence score , but I want something like "how confidently class predicted for each test inputs " . I will try with predict_proba , for now closing the issue .
