### ISSUE TITLE
Allow keeping fixed `k` for `PrecisionAt:top={}.format(k)` metric

### ISSUE THREAD

**Issue by stancld** [catboost/catboost#2029]
Hello :]

Problem: Current implementation adjust the value of `k` w.r.t. to the maximum number of retrieved documents for a given query. However, in these edge cases, where `len(retrieved_documents) < k`, there's an ambiguity whether `k` should be kept fixed or adjusted w.r.t. `len(retrieved_documents)`. Is there any possibility of how to keep `k` fixed regardless of a number of retrieved documents?

Example:
```python
>>> from catboost.utils import eval_metric
>>> eval_metric(
...    [1, 1, 1, 1, 0],
...    [0.2] * 5,
...    group_id=[0] * 5,
...    metric="PrecisionAt:top=10"
... )[0]
0.8
```

Desired result:
```python
>>> from catboost.utils import eval_metric
>>> eval_metric(
...    [1, 1, 1, 1, 0],
...    [0.2] * 5,
...    group_id=[0] * 5,
...    metric="PrecisionAt:top=10"
...    keep_k_fixed=True  # or anything like that
... )[0]
0.4
```

catboost version: 1.0.3
Operating System: Ubuntu 20.04
CPU: - 
GPU: -

**Comment by LyzhinIvan** [comment]
Hi, @stancld! There is no such possibility now. Maybe, you want to make a pull request with this feature?

**Comment by LyzhinIvan** [comment]
We are not planning to add such feature. If you want to implement it yourself, feel free to reopen issue and link it with your PR.
