### ISSUE TITLE
Pool spark save

### ISSUE THREAD

**Issue by ciromanfredi** [catboost/catboost#2030]
Hello everybody,
I wanted to know if it is possible to save the catboost pool WITH SPARK (I saw that with python it is possible through the save method) ... I want to save as the Pool operation is extremely slow (without quantizing)? can someone give me details or explanations? Thanks to all and good luck

**Comment by andrey-khropov** [comment]
`Pool` class on Spark supports all usual caching and persistence operations for Datasets (`cache`, `checkpoint`, `localCheckpoint`, `persist`, `unpersist`).

Saving quantized `Pool` to some distributed storage like HDFS (which will be analogous to HDFS) is in progress.
