### ISSUE TITLE
Key 'MultiCrossEntropy' not found in enum ELossFunction

### ISSUE THREAD

**Issue by nbrown020** [catboost/catboost#2031]
Hello, I have been given some code, but am running into this error while trying to use catboost.

> Warning: Error in catboost.train: tools/enum_parser/enum_serialization_runtime/enum_runtime.cpp:32: Key 'MultiCrossEntropy' not found in enum ELossFunction. Valid options are: 'Logloss', 'CrossEntropy', 'CtrFactor', 'RMSE', 'Lq', 'MAE', 'Quantile', 'Expectile', 'LogLinQuantile', 'MAPE', 'Poisson', 'MSLE', 'MedianAbsoluteError', 'SMAPE', 'Huber', 'Tweedie', 'MultiClass', 'MultiClassOneVsAll', 'PairLogit', 'PairLogitPairwise', 'YetiRank', 'YetiRankPairwise', 'QueryRMSE', 'QuerySoftMax', 'QueryCrossEntropy', 'StochasticFilter', 'StochasticRank', 'PythonUserDefinedPerObject', 'PythonUserDefinedMultiRegression', 'UserPerObjMetric', 'UserQuerywiseMetric', 'R2', 'NumErrors', 'FairLoss', 'AUC', 'Accuracy', 'BalancedAccuracy', 'BalancedErrorRate', 'BrierScore', 'Precision', 'Recall', 'F1', 'TotalF1', 'MCC', 'ZeroOneLoss', 'HammingLoss', 'HingeLoss', 'Kappa', 'WKappa', 'LogLikelihoodOfPrediction', 'NormalizedGini', 'PRAUC', 'PairAccuracy', 'AverageGain', 'QueryAverage', 'PFound', 'PrecisionAt', 'RecallAt [... truncated]
>   143: catboost.train
>   142: eventReactiveValueFunc [/srv/shiny-server/app.R#831]
>    98: forecast
>    97: renderUI [/srv/shiny-server/app.R#384]
>    96: func
>    83: renderFunc
>    82: output$pred_up
>     1: runApp

However, I see this function when looking through the documentation. Why is this happening? An example of my code is below.

> model <- catboost.train(train_pool,  test_pool,
>     params = list(loss_function='MultiCrossEntropy',
>         eval_metric = 'MultiCrossEntropy',
>         iterations = 150, 
>         metric_period=10
>     ))

**Comment by LyzhinIvan** [comment]
Which version of CatBoost do you use? MultiCrossEntropy is available since v1.0.0

**Comment by nbrown020** [comment]
That ended up being the issue. Updating the version fixed it.
