### ISSUE TITLE
Classification: How are tree classes combined?

### ISSUE THREAD

**Issue by michal-sankot** [catboost/catboost#2033]
Problem: Classification - It's unclear how classes from individual trees are combined to get a result from the ensemble.

In no documentation I found a clear answer to how classes from individual decision trees are combined to get final class of a sample.
When we plot individual trees I believe that we can get an information whether sample is in a class or not by checking whether leaf value(RawFormulaVal) is greater than 0. (ref https://github.com/catboost/catboost/issues/1389). How is in combined afterwards?

Is it some weighted vote of individual trees? If so, where do the weights come from?

I'm specifically interested in binary classification case.

**Comment by LyzhinIvan** [comment]
Hi, @michal-sankot! The result of ensemble is a simple sum of results of all trees. Result of a single tree is not a class, it is some real value that minimizes objective function depending on previously built trees. So in binary classification case the predicted object class is 1 if a sum of predictions of all trees is greater than 0.

**Comment by michal-sankot** [comment]
Hi @LyzhinIvan,
thanks for reply. I understand that it's a sum of predictions and when it's greater than 0 it indicates that tested sample is of expected class.
And for clarification, those predictions, are they those displayed values of tree leaves when plotted? Or can they be calculated from those leaf values?
