### ISSUE TITLE
The classification tutorial fails

### ISSUE THREAD

**Issue by aviadr1** [catboost/catboost#2035]
Problem:
I am running the official catboost [classification tutorial](https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb) on colab

but one of the cells fail:
```

X_prepared = X_validation.values.astype(str).astype(object)
# For FeaturesData class categorial features must have type str

fast_predictions = model.predict_proba(
    data=FeaturesData(
        cat_feature_data=X_prepared,
        cat_feature_names=list(X_validation)
    )
)
print(fast_predictions)
```

fails with the error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-42-f6e51075722f>](https://localhost:8080/#) in <module>()
      5     data=FeaturesData(
      6         cat_feature_data=X_prepared,
----> 7         cat_feature_names=list(X_validation)
      8     )
      9 )

TypeError: predict_proba() got an unexpected keyword argument 'data'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-42-f6e51075722f>](https://localhost:8080/#) in <module>()
      5     data=FeaturesData(
      6         cat_feature_data=X_prepared,
----> 7         cat_feature_names=list(X_validation)
      8     )
      9 )

TypeError: predict_proba() got an unexpected keyword argument 'data'
```

catboost version:
1.0.4

Operating System:
Google Colab

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.5 LTS
Release: 18.04
Codename: bionic

CPU:

GPU:
None

**Comment by aviadr1** [comment]
I have created a trivial pull request to fix this issue
https://github.com/catboost/tutorials/pull/11

**Comment by LyzhinIvan** [comment]
Hi, @aviadr1! 
Thanks for your PR! There is one problem - we didn't configure syncing from tutorials repository, can you move your PR to our main repository (https://github.com/catboost/catboost), please? The corresponding tutorials folder is located [here](https://github.com/catboost/catboost/tree/master/catboost/tutorials).

**Comment by LyzhinIvan** [comment]
@aviadr1 , I've committed your fix in https://github.com/catboost/catboost/commit/6ac3ec965e31892fc30cfafa468aa06734b126dc. You can close your PR now.
