### ISSUE TITLE
CatBoostError: CatBoostRegressor Showing 'Bad value for num_feature' Errors on 'ignored_features'

### ISSUE THREAD

**Issue by blahiri** [catboost/catboost#2038]
Hi Team,

I am using `CatBoostRegressor` with a `Pandas DataFrame` which contains some columns that I don't want the model to train on (basically, ignore the columns), but I can't drop the columns from the DataFrame because I need them for post-processing after the model fitting is done.

The CatBoost documentation [CatBoostRegressor: Overview](https://catboost.ai/en/docs/concepts/python-reference_catboostregressor) does mention that `'ignored_features'` can be specified in the regressor initialization.

<pre>
class CatBoostRegressor(iterations=None,
                        learning_rate=None,
                        ...,
                        <b>ignored_features=None,</b>
                        ...,
                        posterior_sampling=None,
                        boost_from_average=None)
</pre>

I have passed the columns to be ignored in a Python list to the regressor initialization, as shown below,

<pre>
<b>ignored_features</b> = ['Actual Implementation End Date',
                    'Actual Implementation Start Date',
                    'MonthYear',
                    'Schedule End Date',
                    'Schedule Start Date',
                    'Z CHG SVY ANSWERS
                   ]

clf_params = {
    'cat_features': categorical_features,
    <b>'ignored_features': ignored_features,</b>
    'bagging_temperature': 1,
    'boosting_type': 'Plain',
    'bootstrap_type': 'Bayesian',
    'boost_from_average': False,
    'border_count': 254,
    'counter_calc_method': 'SkipTest·,
    'ctr_target_border_count': 1,
    'custom_metric': ['RMSE'],
    'depth': 10,
    'early_stopping_rounds': 50,
    'eval_metric': 'RMSEWithUncertainty',
    'feature_border_type': 'MaxlogSum',
    'grow_policy': 'Lossguide',
    'iterations': 2000,
    'learning_rate': 0.1,
    '12_leaf_reg': 4,
    'max_ctr_complexity': 4,
    'max_leaves': 31,
    'objective': 'RMSEHithUncertainty',
    'one_hot_max_size': 3,
    'penalties_coefficient': 1,
    'posterior_sampling': True,
    'random_seed': 42,
    'random_strength': 17,
    'score_function': 'L2',
    'use_best_model': True,
    'used_ram_ limit': used_ram_limit
}

# Initialize CatBoostRegressor
model = CatBoostRegressor(**clf_params)
</pre>

But I am getting an error complaining about `Bad value for num_feature` when trying to train the model,

<pre>
model.fit(X_train,
          y_train,
          cat_features = categorical_features,
          eval_set = (X_test, y_test),
          early_stopping_rounds = 50,
          use_best_model = True,
          verbose = False
         )
</pre>

The exact error message is given below,

<pre>
CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=0]="2021-09-01 00:00:00": Cannot convert 'b'2021-09-
01 00:00:00'' to float
</pre>

The `feature_idx=0` in the error message above is the `Actual Implementation End Date` feature, that I had passed in the `ignored_features` Python list intending for the model to ignore it.

Is there something I am doing wrong here? Maybe `ignored_features` has to be used in a different manner?

**P.S.** You will be able to tell from the `'objective': 'RMSEWithUncertainty'` and `'posterior_sampling': True` parameters that I am using this in a `virtual_ensembles_predict` model. Does that have anything to do with the error? In that case, please do advise.

I have attached a screenshot of the error traceback, in case it helps. Please let me know anytime you need any further information from me.

Python 3.6.1 (Anaconda 4.4.0 64-bit)
catboost version: 1.0.4
Operating System: Windows 10 64-bit
CPU: Intel Core i5 8350U
GPU: None
RAM: 16GB

![error_traceback](https://user-images.githubusercontent.com/96404169/159167241-a39a6f6c-0ccd-47e3-9e0d-ccdd42c28dd9.jpg)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
All categorical features, even those that are ignored, should be listed in categorical_feature.
Otherwise CatBoost tries to parse their values as floats.
I don't think that this error is related to RMSEWithUncertainty.

**Comment by blahiri** [comment]
Hi, thank you for your reply. So what you are basically saying is that I have to include the list of columns to be ignored both in the `cat_features` and `ignored_features` parameters?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
yep
