### ISSUE TITLE
Classification error - CUDA error 700

### ISSUE THREAD

**Issue by ChristosMaglaras** [catboost/catboost#2039]
Problem: Classification illegal memory access on random trial within optuna
catboost version: 1.0.4
Operating System: Win 10 Pro 10.0.19044
CPU: i9 9900KF
GPU: GTX 1080 2xSLI

7.2/8Gb vram at most is used on the trials that pass
occurs with both gpu's as well as either independently

Params:
{'iterations': 1000, 'loss_function': 'Logloss', 'learning_rate': 0.0021507803566705327, 'l2_leaf_reg': 0.10530879903216447, 'border_count': 22, 'depth': 4, 'boosting_type': 'Plain', 'bootstrap_type': 'Poisson', 'leaf_estimation_backtracking': 'Armijo', 'min_data_in_leaf': 16, 'one_hot_max_size': 12, 'has_time': True, 'random_seed': 42, 'task_type': 'GPU', 'devices': '0:1', 'subsample': 0.2479141447711061, 'auto_class_weights': 'Balanced'}

Error:
Application terminated with error: PyInit__catboost+1846156 (0x7FFA272C828C)
??+0 (0x7FFA26D72F2E)
??+0 (0x7FFA26E089FB)
??+0 (0x7FFA26E097DF)
??+0 (0x7FFA26E052F8)
PyInit__catboost+9873633 (0x7FFA27A6FFE1)
PyInit__catboost+9858995 (0x7FFA27A6C6B3)
PyInit__catboost+9850585 (0x7FFA27A6A5D9)
PyInit__catboost+9853131 (0x7FFA27A6AFCB)
??+0 (0x7FFA26F5D5DD)
PyInit__catboost+13347220 (0x7FFA27DC0094)
BaseThreadInitThunk+20 (0x7FFAA5137034)
RtlUserThreadStart+33 (0x7FFAA6162651)

(class TCatBoostException) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/cuda_lib/cuda_events_provider.h:61: CUDA error 700: an illegal memory access was encountered

Process finished with exit code -1073740791 (0xC0000409)

**Comment by ChristosMaglaras** [comment]
This issue persists into the latest release 1.0.5 which states "Fix CUDA error 700 caused by data race in mimalloc and CUDA driver." within the release notes.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for checking!
CUDA 700 may happen for a bunch of reasons.
In 1.0.5 we have fixed just one scenario.

**Comment by ChristosMaglaras** [comment]
Thank you for the reply, may I ask what the fixed scenario is as well as the general reasons CUDA 700 occurs? I have also seen that others have encountered this error. Thank you!

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@ChristosMaglaras 
cuda 700 means illegal memory access -- which may happen for various reasons
we have fixed in 1.0.5 a data race between cuda driver and mimalloc during catboost initialization under linux

**Comment by kizill** [comment]
Closing as inactive, please reopen if problem persists.
