### ISSUE TITLE
How to Generate Partial Dependency Plot in R?

### ISSUE THREAD

**Issue by sandeshregmi** [catboost/catboost#2042]
Is there a way to generate PDP in R from catboost model?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
nay, catboost r package does not work with pdp currently
it may be possible to twiddle [catboost/R-package/R/catboost.caret.R](https://github.com/catboost/catboost/blob/master/catboost/R-package/R/catboost.caret.R), and then pass something like [catboost\R-package\tests\testthat\test_caret_parameter_tuning.R ](https://github.com/catboost/catboost/blob/3f3e37fb8300e084e532bd3d3a930804ac0b21e7/catboost/R-package/tests/testthat/test_caret_parameter_tuning.R#L46) to pdp, as suggested here https://bgreenwell.github.io/pdp/articles/pdp.html
![image](https://user-images.githubusercontent.com/7053671/159846192-cca75ba2-b5c0-4ccd-b2af-4b21909de403.png)
we never tried to do this though...

**Comment by sandeshregmi** [comment]
wonderful! `pdp::partial()` works great with caret implemented catboost model. Thank you
