### ISSUE TITLE
Can't see plot

### ISSUE THREAD

**Issue by oferfeinstein** [catboost/catboost#2046]
Hello, 

I'm using jupyter notebook (remote connection) and I'm trying to create plots using the catboost, for example - while fitting the model, calc_feature_statistics...

The plot parameter is True and from the 'fit' function I'm getting the text:
"MetricVisualizer(layout=.....)" without plotting.

Using calc_feature_statistics I'm getting an empty plot. 
I tried to update the ipywidgets package and I also tried other solutions that I saw here but it doesn't work.
Any help, please?

Thanks in advance.

**Comment by andrey-khropov** [comment]
@oferfeinstein Can you recheck with CatBoost 1.2. This issue should be fixed by now.

**Comment by andrey-khropov** [comment]
Closing as there's no feedback. Feel free to reopen if the issue still persist with the lastest release of CatBoost.
