### ISSUE TITLE
Catboost save_model in pmml format as predict_proba

### ISSUE THREAD

**Issue by Rolanoir** [catboost/catboost#2050]
Problem: Currently, .save_model to pmml format for CatBoostClassiifier saves pmml with .predict functionality. Is it possible to add functionality of the predict_proba to the .save_model?

Image of the output field in the .pmml file for CatBoostClassifier
![image](https://user-images.githubusercontent.com/69794679/161420504-2179f983-43fb-4b21-8bda-aaac74d59714.png)

**Comment by joe-iles-cot** [comment]
+1 this. `.predict()` is fundamentally useless for any model implementation that requires threshold calibration.

**Comment by andrey-khropov** [comment]
Duplicate of #1487
