### ISSUE TITLE
catboost spark fit error

### ISSUE THREAD

**Issue by summer5e55** [catboost/catboost#2051]
Problem:TimeDelta cannot be cast to java.time.Duration error
catboost version: ai.catboost:catboost-spark_3.1_2.12:1.0.4
Operating System: DataBricks 9.1 LTS ML (includes Apache Spark 3.1.2, Scala 2.12) 
CPU:
GPU:
I have run into the following error.  I have run my model successfully without this error but when I run it again, it appears and the model cannot be run. Would really appreciate help with this. 
Also tried to run the starter code on your website, failed with the same error. 
![Screen Shot 2022-04-03 at 10 33 45 AM](https://user-images.githubusercontent.com/83364351/161433327-231b26cf-843f-4414-b964-49004bf2c2e7.png)

**Comment by summer5e55** [comment]
This ends up to be caused by a package installation conflict on Databricks cluster. After reinstallation it is resolved.

**Comment by IvanMatoshchuk** [comment]
> This ends up to be caused by a package installation conflict on Databricks cluster. After reinstallation it is resolved.

@summer5e55  can you, please, write which cluster and catboost version worked for you?  
Have the same issue with 10.5 ML (spark 3.2.1 scale 2.12) using ai.catboost:catboost-spark_3.2_2.12:1.0.6

**Comment by Rhys-Thompson** [comment]
> > This ends up to be caused by a package installation conflict on Databricks cluster. After reinstallation it is resolved.
> 
> @summer5e55 can you, please, write which cluster and catboost version worked for you? Have the same issue with 10.5 ML (spark 3.2.1 scale 2.12) using ai.catboost:catboost-spark_3.2_2.12:1.0.6

Did you get this resolved I'm having the same issue?

**Comment by harshit1742** [comment]
I am also facing the same issue.
I am using 10.4 ML LTS ai.catboost:catboost-spark_3.2_2.12:1.1.1

**Comment by ssabzevari-antuit** [comment]
Facing the same issue on 13.3 LTS and it also have a conflict with com.microsoft.azure:synapseml_2.12:0.11.3.

I am using ai.catboost:catboost-spark_3.4_2.12:1.2.5.
