### ISSUE TITLE
Catboost crashing / Memory Issues

### ISSUE THREAD

**Issue by nilslacroix** [catboost/catboost#2058]
Problem: Catboost on GPU crashes, takes up all the memory. CPU works fine
catboost version: 1.04
Operating System: Windows10
CPU: Ryzen1600
GPU: GTX1060 6GB

So when I run catboost on CPU, everything runs fine. On GPU however everything begins to stutter and freezes and even on very small datasets no result is produced. For that reason I only once saw an error message which said something along the lines
"Too many workers ... thread aborted because not enough memory"

When I look at nvidia-smi the GPU is idling but has 5 GB of ram in usage, system ram if fully occupied as well.

I tried to reproduce the error with this small benchmark:

```
from catboost import CatBoostRegressor

train_data = [[0, 3],
              [4, 1],
              [8, 1],
              [9, 1]]
train_labels = [0, 0, 1, 1]

model = CatBoostRegressor(iterations=1000,
                           task_type="GPU",
                           devices='0:1')
model.fit(train_data,
          train_labels,
          verbose=False)
```

The code works but a few things are strange:

1. It takes like 5 seconds to terminate
2. GPU Ram is at 5GB during computation (otherwise it idles at 500MB)
3. 200MB Ram from system

So there seems to be some memory issues? Is there any solution for these problems?

**Comment by nilslacroix** [comment]
I solved this issue myself. 

The problem occurs if for example in a scikit gridsearch` n_jobs = -1` is set, which is pretty much standard, to use all cpu cores. In this case hower it seems that so many jobs are spawned immediately, that the RAM is filled completely and everything stops working. Maybe there should be some exception or warning for this kind of behaviour?

**Comment by vitorglemos** [comment]
This happened with me too. When my n_jobs=-1, my CPU overflowed and RAM had consumption peaked haha

**Comment by fkjslee** [comment]
I'm crashed too, But I didn't use scikit's gridseach.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
> I'm crashed too, But I didn't use scikit's gridseach.

python 3.9 + catboost 1.1.1 throws an exception for the reproducer in this issue
```
_catboost.CatBoostError: catboost/cuda/methods/dynamic_boosting.h:198: Error: pool has just 4 groups or docs, can't use #2 GPUs to learn on such small pool
```

if we change devices='0:1' to devices='0', then training succeeds
