### ISSUE TITLE
CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:392: NaN values are not supported for target

### ISSUE THREAD

**Issue by KeranLi** [catboost/catboost#2061]
Problem: After modeling, when I wanna fit model, this error occurred. I haven't met it last time I use these code.

#CatBoost需要利用Pool工具处理数据集
train_data = Pool(data=train_x, label=train_y, weight=None)
eval_data = Pool(data=test_x, label=test_y, weight=None)
 # 训练模型,参数均用GridSearchCV搜索出SOTA
model = cb.CatBoostClassifier(loss_function='CrossEntropy', depth=6, iterations=500, l2_leaf_reg=4, learning_rate=0.12)
model.fit(train_data, eval_set=eval_data, plot=True)

Custom logger is already specified. Specify more than one logger at same time is not thread safe.
CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:392: NaN values are not supported for target

catboost version: 1.0.4
Operating System: win 10
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: RTX 3060

**Comment by KeranLi** [comment]
I ran these code again. The error changed:
CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/metrics/metric.cpp:6438: Max target greater than 1: 3

**Comment by LyzhinIvan** [comment]
Hi, @KeranLi!
The errors are self-explanatory:
* NaN values in target are supported for MultiRMSEWithMissingValuesOnly
* CrossEntropy requires that target values should be in [0, 1]

**Comment by KeranLi** [comment]
OK, got it! Thanks so much for ur help!发自我的手机-------- 原始邮件 --------发件人： Ivan Lyzhin ***@***.***>日期： 2022年4月18日周一 傍晚6:28收件人： catboost/catboost ***@***.***>抄送： "Keran,Li" ***@***.***>, Mention ***@***.***>主    题： Re: [catboost/catboost] CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:392: NaN values are not supported for target (Issue #2061)
Hi, @KeranLi!
The errors are self-explanatory:
NaN values in target are supported for MultiRMSEWithMissingValuesOnlyCrossEntropy requires that target values should be in [0, 1]
