### ISSUE TITLE
Where else can I get the source of catboost if Github blocks this repo and account?

### ISSUE THREAD

**Issue by IncubatorShokuhou** [catboost/catboost#2062]
Recently I notices that Github is blocking users/organizarions and repos from Russia. For example, `LightAutoML`  from sberbank ai lab, an automl tool that I used from time to time,  has been blocked, and I cannot access to it now. 
Does catboost group have any plans for this? For example, do you have an alternate repo?

**Comment by VlasovKirill** [comment]
So far, only accounts affiliated with sanctioned companies have been blocked by Github. CatBoost accounts and repo continue to operate normally. We are closely monitoring the situation and in case of blocking, we will inform our users about an alternative via our channels: 
- [Twitter](https://twitter.com/CatBoostML) 
- [Telegram chat](https://t.me/catboost_en)

Moreover, our official site [catboost.ai](https://catboost.ai) which also includes  documentation, is always available and our users can install the latest versions of CatBoost via PyPi, Conda or get artifacts from Maven central repository
