### ISSUE TITLE
Some questions about using second partial derivatives to minimize the loss function.

### ISSUE THREAD

**Issue by Wangpc-972** [catboost/catboost#2063]
Hello CatBoost Team：
When I saw this [part](https://catboost.ai/en/docs/concepts/algorithm-score-functions#second-order-functions), I  was confused by the following questions:
1. After applying the Taylor expansion to the loss function, what is the specific mathematical formula for this?
![1650327728(1)](https://user-images.githubusercontent.com/81344920/163897048-285372e5-d575-48aa-bd9f-b575ecc17f31.jpg)
2. After Taylor expansion, does leaf reorganization transform the formula from traversing samples to traversing leaf nodes? What are the specific steps to obtain the following formula?
![1650328155(1)](https://user-images.githubusercontent.com/81344920/163897581-db7e2d5f-0880-4153-96f7-1a4f488f68e0.jpg)

Looking forward to your reply！

**Comment by LyzhinIvan** [comment]
Hi, @Wangpc-972!

1) The specific formula for this term is 
![Screen Shot 2022-04-19 at 1 57 36 PM](https://user-images.githubusercontent.com/6265308/163989239-90b8cec8-b850-466b-8bee-e69ffbd68252.png)

2) Yes, we take this formula:
![Screen Shot 2022-04-19 at 1 55 15 PM](https://user-images.githubusercontent.com/6265308/163988924-5392a905-9b1d-46c1-a94f-95d7c36a2865.png)
and group items by leaf. But the latter formula (which you paste) is incorrect unfortunately. The correct steps are:
- group by leaf
![Screen Shot 2022-04-19 at 2 02 51 PM](https://user-images.githubusercontent.com/6265308/163989973-8d46bb33-28b2-4efa-864c-bb7a5ece78a0.png)
- minimize for each leaf independently
![Screen Shot 2022-04-19 at 2 05 56 PM](https://user-images.githubusercontent.com/6265308/163990452-03f3a720-811e-4ff2-8b71-31e50b571979.png)
- difference by leaf value
![Screen Shot 2022-04-19 at 2 07 11 PM](https://user-images.githubusercontent.com/6265308/163990634-39ba87e4-cfe0-437d-aab8-3fe786c89f38.png)
- optimal leaf value is
![Screen Shot 2022-04-19 at 2 10 33 PM](https://user-images.githubusercontent.com/6265308/163991139-c1479297-edc4-4a4a-83b3-2a980bb6145c.png)
 
The last formula is correct. We will add these steps in documentation.

**Comment by Wangpc-972** [comment]
> Hi, @Wangpc-972!
> 
> 1. The specific formula for this term is
>    ![Screen Shot 2022-04-19 at 1 57 36 PM](https://user-images.githubusercontent.com/6265308/163989239-90b8cec8-b850-466b-8bee-e69ffbd68252.png)
> 2. Yes, we take this formula:
>    ![Screen Shot 2022-04-19 at 1 55 15 PM](https://user-images.githubusercontent.com/6265308/163988924-5392a905-9b1d-46c1-a94f-95d7c36a2865.png)
>    and group items by leaf. But the latter formula (which you paste) is incorrect unfortunately. The correct steps are:
> 
> * group by leaf
>   ![Screen Shot 2022-04-19 at 2 02 51 PM](https://user-images.githubusercontent.com/6265308/163989973-8d46bb33-28b2-4efa-864c-bb7a5ece78a0.png)
> * minimize for each leaf independently
>   ![Screen Shot 2022-04-19 at 2 05 56 PM](https://user-images.githubusercontent.com/6265308/163990452-03f3a720-811e-4ff2-8b71-31e50b571979.png)
> * difference by leaf value
>   ![Screen Shot 2022-04-19 at 2 07 11 PM](https://user-images.githubusercontent.com/6265308/163990634-39ba87e4-cfe0-437d-aab8-3fe786c89f38.png)
> * optimal leaf value is
>   ![Screen Shot 2022-04-19 at 2 10 33 PM](https://user-images.githubusercontent.com/6265308/163991139-c1479297-edc4-4a4a-83b3-2a980bb6145c.png)
> 
> The last formula is correct. We will add these steps in documentation.

Thanks for your reply, but there is one more question, what does ϕ and ϕ 
leaf mean respectively? Are they the decision trees to be added to the current ensemble?

**Comment by LyzhinIvan** [comment]
![Screen Shot 2022-04-19 at 4 40 40 PM](https://user-images.githubusercontent.com/6265308/164016935-878b0bb0-deb3-4011-9396-31b0e40adaf1.png) is the value in leaf  ![Screen Shot 2022-04-19 at 4 41 52 PM](https://user-images.githubusercontent.com/6265308/164017201-290193ef-895d-4a19-a344-da72dded1f6c.png) of the current tree

![Screen Shot 2022-04-19 at 4 43 09 PM](https://user-images.githubusercontent.com/6265308/164017428-c09d7159-83e9-4fab-9c2b-5c1c663d3117.png) is a vector of all leaf values of the current tree

**Comment by Wangpc-972** [comment]
Thanks for your reply, but still have the following questions:

1. In this paper, it is mentioned that
![1650438851(1)](https://user-images.githubusercontent.com/81344920/164172229-4b75fa96-6066-430d-b39d-7c669e89c541.jpg)
 is obtained by ,
![1650438862(1)](https://user-images.githubusercontent.com/81344920/164172304-ad15ab07-e89f-478c-9591-43f72cb71983.jpg)
 and
![1650438871](https://user-images.githubusercontent.com/81344920/164172344-440cbf5e-f89a-42d8-a3d1-40d4243bc327.jpg)
 , but when minimizing the loss function, it is
![1650439006(1)](https://user-images.githubusercontent.com/81344920/164172468-1b96b14c-8cce-4bdf-89a1-a248c2c91c31.jpg)
 . Why?
![1650438041(1)](https://user-images.githubusercontent.com/81344920/164172198-609c629c-f800-4cac-9982-3fd7a5674d54.jpg)

2. All are loss functions, why is this [paper](https://catboost.ai/en/docs/concepts/educational-materials-papers#catboost-unbiased-boosting-with-categorical-features) different from the one on this [website](https://catboost.ai/en/docs/concepts/algorithm-score-functions)?

Looking forward to your reply！

**Comment by LyzhinIvan** [comment]
There is no contradiction actually, it is just omission that we don't mention on the website that these leaf values are not final and they are multiplied by `alpha` (`learning-rate`) then.
`learning-rate` is a way of regularization in some sense.

**Comment by Wangpc-972** [comment]
> There is no contradiction actually, it is just omission that we don't mention on the website that these leaf values are not final and they are multiplied by `alpha` (`learning-rate`) then. `learning-rate` is a way of regularization in some sense.

Thank you very much for your reply！！！
