### ISSUE TITLE
 Is there anyway to export the pool.cd file from a catboost.Pool object that has been inited by pandas.dataframe？

### ISSUE THREAD

**Issue by fengshansi** [catboost/catboost#2064]
Is there anyway to export the pool.cd file from a catboost.Pool object that has been inited by pandas.dataframe？

**Comment by LyzhinIvan** [comment]
There is no such method in `catboost.Pool`, but you can use [`catboost.utils.create_cd` ](https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd) function. Some `Pool` method can be also helpful to call it: 
[`Pool.get_cat_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_cat_feature_indices)
[`Pool.get_text_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_text_feature_indices)
`Pool.get_embedding_feature_indices`

**Comment by fengshansi** [comment]
> There is no such method in `catboost.Pool`, but you can use [`catboost.utils.create_cd` ](https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd) function. Some `Pool` method can be also helpful to call it: [`Pool.get_cat_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_cat_feature_indices) [`Pool.get_text_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_text_feature_indices) `Pool.get_embedding_feature_indices`



> There is no such method in `catboost.Pool`, but you can use [`catboost.utils.create_cd` ](https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd) function. Some `Pool` method can be also helpful to call it: [`Pool.get_cat_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_cat_feature_indices) [`Pool.get_text_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_text_feature_indices) `Pool.get_embedding_feature_indices`

Honestly speaking， I have read this create_cd function before I raise this issue. Some of the types such as doc_id I have never seen in the Pool object inited by pandas.Dataframe. That's why I raised this issue. Now I want to know whether the type like doc_id is only used for Pool object inited by csv file.

**Comment by fengshansi** [comment]
> There is no such method in `catboost.Pool`, but you can use [`catboost.utils.create_cd` ](https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd) function. Some `Pool` method can be also helpful to call it: [`Pool.get_cat_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_cat_feature_indices) [`Pool.get_text_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_text_feature_indices) `Pool.get_embedding_feature_indices`



> There is no such method in `catboost.Pool`, but you can use [`catboost.utils.create_cd` ](https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd) function. Some `Pool` method can be also helpful to call it: [`Pool.get_cat_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_cat_feature_indices) [`Pool.get_text_feature_indices`](https://catboost.ai/en/docs/concepts/python-reference_pool_get_text_feature_indices) `Pool.get_embedding_feature_indices`

Honestly speaking， I have read this create_cd function before I raise this issue. Some of the types such as doc_id I have never seen in the Pool object inited by pandas.Dataframe. That's why I raised this issue. Now I want to know whether the type like doc_id is only used for Pool object inited by csv file.

**Comment by LyzhinIvan** [comment]
Yes, `doc_id` can be specified only for pools created from file.

**Comment by fengshansi** [comment]
> 是的，`doc_id`只能为从文件创建的池指定。
If my statement is catboost.Pool(data=pd.Dataframe obj, label=pd.Dataframe obj, cat_features=cat_features). Is that  mean besides those  cat_features , other features are Num type in pool.cd file?

**Comment by LyzhinIvan** [comment]
Yes.
