### ISSUE TITLE
Confidence Interval - Probability - CatBoostRegressor

### ISSUE THREAD

**Issue by kasra94** [catboost/catboost#2065]
Hi CatBoost team,
I have been using `catboostregressor` and would like to know how to get confidence intervals or probability for each prediction. I tried `prediction_type=Probability` but the gives me `[0. 1.]` and it is not clear what they mean. Would appreciate it if you could help me with finding a way to calculate confidence intervals or probability.

**Comment by LyzhinIvan** [comment]
Answered in Telegram https://t.me/catboost_en/6379
