### ISSUE TITLE
Kernel dies when trying to import module

### ISSUE THREAD

**Issue by jvkater** [catboost/catboost#207]
When I try to import catboost in Jupyter notebook, the Kernel dies. 

I use Python 3.6.1 in Anaconda 4.4.0 (64-bit)  in Windows 10. Catboost was installed via 'pip install' command

Is there any way to fix this?

**Comment by NikitaChurkin** [comment]
I have the same issue (Python 3.6.3, Anaconda 5.0.1, Windows 10)

**Comment by fredtony** [comment]
Same here with the same version as @jvkater . Also installed with pip install

**Comment by fredtony** [comment]
I traced the source of the error to lines 26-32 of core.py:

try:
    from catboost.gpu._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc
except ImportError:
    try:
        from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc
    except ImportError:
        from ._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc

It cannot import the first two and it apparently cannot complete the third either. Right after this line the kernel dies. I hope this helps.

**Comment by kizill** [comment]
There is a bug in our allocator triggered by ASLR on Windows10. We want to release new version with fix today. Sorry for the wait!

**Comment by annaveronika** [comment]
The code is on github now, please try building from source, as described in documentation:
https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

It will be updated on pypi in version 0.5.2
