### ISSUE TITLE
In feature selection, how to calculate the contribution of the corresponding feature？

### ISSUE THREAD

**Issue by Wangpc-972** [catboost/catboost#2071]
Hello CatBoost Team:
When employing the ShapValues method to [select features](https://github.com/catboost/catboost/blob/master/catboost/tutorials/feature_selection/select_features_tutorial.ipynb), I noticed the feature selection steps below, but don't understand how to calculate the contribution vector  
![1650856352(1)](https://user-images.githubusercontent.com/81344920/165014783-ebea532f-6dca-4b4e-9211-a752ef231ab5.jpg)
of the feature？

![1650856300(1)](https://user-images.githubusercontent.com/81344920/165014792-d74c2e35-9e91-4185-8d7a-952457532feb.jpg)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
It is calculated as follows:
https://github.com/catboost/catboost/blob/b018e920cd5225a87c2e6484fca687d5b0bb97bf/catboost/libs/features_selection/recursive_features_elimination.cpp#L348

Basically, to simulate absence of a feature, for each object, we subtract the feature's SHAP value from the prediction.

**Comment by Wangpc-972** [comment]
> It is calculated as follows:
> 
> https://github.com/catboost/catboost/blob/b018e920cd5225a87c2e6484fca687d5b0bb97bf/catboost/libs/features_selection/recursive_features_elimination.cpp#L348
> 
> Basically, to simulate absence of a feature, for each object, we subtract the feature's SHAP value from the prediction.

Thank you for your reply！
I mean how to calculate the contribution vector  mathematically?
