### ISSUE TITLE
CatBoostError: bad object for id: nan

### ISSUE THREAD

**Issue by k3ybladewielder** [catboost/catboost#2073]
Im trying to train on binary classification model and the follow error occurs 

```CatBoostError: bad object for id: nan```
......
```CatBoostError: Invalid type for cat_feature.... = Nan: cat_features must be integer or string, real number values and NaN values should be converted to string."```

But even use nam_mode this occurs

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @k3ybladewielder 
please try something like

```python
from catboost import CatBoostClassifier

train_data = [['0', 3],
              ['4', 1],
              ['8', 1],
              ['nan', 1]]
train_labels = [0, 0, 1, 1]

model = CatBoostClassifier(iterations=10)

model.fit(train_data,
          train_labels,
          cat_features=[0],
          verbose=False)

```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
https://catboost.ai/en/docs/concepts/python-usages-examples#class-with-array-like-data1
