### ISSUE TITLE
Select relevant features when we have mix of categorical and numeric features

### ISSUE THREAD

**Issue by lalchand-pandia** [catboost/catboost#208]
Hi,
How we do we feature engineering when our data consists of larger number of categorical features

**Comment by annaveronika** [comment]
Sorry, I have not understood the question. Could you please clarify?

**Comment by lalchand-pandia** [comment]
Suppose our dataset has large number of features/attributes. Some of them are numeric i.e have float values and many of them are categorical. Since some features may be not useful. So how do we decide which features to be used while training our models like CatBoostRegressor or CatBoostClassifier.  Do we have code in CatBoost library which can help in deciding importance of features/attributes.

Hope this makes things clear. Let me know 
Thanks

**Comment by annaveronika** [comment]
There are currently no filters that you can use before training.
But we have feature_importances functionality - you can look, which features are the strongest in the formula. You can read about it here: https://tech.yandex.com/catboost/doc/dg/features/feature-importances-calculation-docpage/#feature-importances-calculation
We will also add soon functionality to check if new features are adding improvements to your existing formula.
