### ISSUE TITLE
Schedule R script with catboost results in error (Can't create train working dir: catboost_info)

### ISSUE THREAD

**Issue by vidarsumo** [catboost/catboost#2080]
Problem:
I'm scheduling an .R script in Windows (using Windows task scheduler) to run some code where I fit Catboost in a forecasting project. Catboost is used through the modeltime and treesnip R packages when creating the forecasts. If I run the code manually or source it I have no problem. But when I schedule the script to run automatically I get this error:

```
Error in catboost::catboost.train(learn_pool = d, params = list(iterations = 1971L,  : 
  C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info
```

catboost version: 1.0.5
Operating System: Windows 10 Pro
CPU: i9-9900K
GPU: None

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
the working directory for scheduled tasks under Windows is `%Windir%\System32\`
could you please specify an absolute path to a writable location in the train_dir parameter?
this should fix the problem

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
please reopen if this is not solved
