### ISSUE TITLE
plotting problems/usage question

### ISSUE THREAD

**Issue by JustM57** [catboost/catboost#209]
Hello! First of all I'd want say about plotting problems. I'm using python jupyter version - plots do not render every time when I start fitting my model. How can I fix this?
Second, is there a way not save only the best model, but to save model checkpoints every x epochs? I need this due to you can have only one eval metric, but sometimes you need best models for different metrics. Or I should just retrain the model?

**Comment by annaveronika** [comment]
We'll add model.shrink function, this will solve the first problem. #210

**Comment by annaveronika** [comment]
For now you can use apply function with fixed number of trees

**Comment by JustM57** [comment]
@annaveronika how to translate model.shrink into russian. Ty

**Comment by annaveronika** [comment]
обрезать модель до первых скольких-то итераций

**Comment by JustM57** [comment]
@annaveronika огонь, спасибо!

**Comment by JustM57** [comment]
@annaveronika and how much approximately should we wait till this version? Is it in develeping?

**Comment by annaveronika** [comment]
It is in development now, we'll add it first to github in matter of days, then on pypi, in matter of weeks. If you need it soon, you'll have to build from source.

**Comment by newbfg** [comment]
> plots do not render every time when I start fitting my model

Hi! Do you have problems plotting this way?
`import catboost

w = catboost.CatboostIpythonWidget('/path/to/trains')
w.update_widget(subdirs=True)`

And what ipywidgets version are you using?

**Comment by JustM57** [comment]
@newbfg Happy New Year! I've installed ipywidgets as it is said in the instructions. I'll check the version as soon as I get to work. Tbt It's a real real headache to restart(shutdown+start) the whole kernel 5 times in a row in order to get the plot(

**Comment by JustM57** [comment]
@newbfg installed catboost 0.5.2 still problems with plotting
ipywidgets Version: 7.0.5

**Comment by newbfg** [comment]
@JustM57 Hi! Sorry for the delay, I was offline during vacations.

I had same problems with migrating to ipywidgets 7.x. The best way to remove cache is to create new jupyter document and copy&paste your old content into it.

Please try it

**Comment by JustM57** [comment]
@newbfg it's akward, but kind of working.. Ctrl+C + Ctrl+V perform nice.(one try)

**Comment by annaveronika** [comment]
We mention this in documentation https://tech.yandex.com/catboost/doc/dg/features/visualization_jupyter-notebook-docpage/

We'll update documentation to make it more clear, for now I hope your problem is resolved.
