### ISSUE TITLE
Release linux arm64 wheels to pypi

### ISSUE THREAD

**Issue by tboddyspargo** [catboost/catboost#2091]
Problem: `ERROR: No matching distribution found for catboost`
catboost version: **1.0.5**
Operating System: **Debian/Ubuntu Linux**
CPU: **Aarch64 (arm64 - Apple Silicon)**
GPU: **Apple M1 Max**

# Request
I'd like to request wheel files for popular `linux` OS and `Aarch64`/`arm64` platforms. The use case is containerized applications running on host machines with those CPU architectures. Currently, containers running on such hosts must specify an alternative `linux/amd64` platform and rely on `qemu` emulation which negatively impacts performance of all components running within the container.

#1981 seems related, but since the author was only asking a clarification question, I wanted to open this issue as a more formal request to release packages supporting `linux/arm64`

# Steps to Reproduce
_On an aarch64/arm64 system with a recent version of `docker`_
```sh
docker run python:3.8-slim pip install catboost==1.0.5
```

> **NOTE:** If you are _not_ running on an `aarch64`/`arm64` platform, you may be able to add a `--platform=linux/arm64` to the above command to see the error documented above.

**Comment by rivershah** [comment]
Any timelines on this please?

**Comment by ivanychev** [comment]
Any update on this issue? `catboost` in currently unusable on `linux/arm64` servers and docker containers.

**Comment by arestifo** [comment]
Hi all!

No input on this for a while, so I put together some instructions you can use while we wait for an official `linux/arm64` release. These are definitely not perfect and could probably be simplified, but they worked for me.

I have pre-built (CPU-only) wheels [here](https://github.com/arestifo/custom-catboost-aarch64). If you want to build your own wheel, follow these instructions.

These instructions only build the CPU version of  `catboost`, if you want GPU support you can experiment with the last `mk_wheel.py` command (maybe try adding `-DHAVE_CUDA=yes` and `-DCUDA_ROOT=<your CUDA root>` flags, although I haven't tested it).

# Building wheel on `linux/arm64`
Start a Debian 11 Docker container. Note this requires an `x86_64` environment. Docker Desktop comes with the required `qemu` emulation to run this in most environments. The final built wheel will be in the directory you run the `docker run` command from.
```bash
docker run -it --platform=linux/amd64 -v $(pwd)/:/wheel_out debian:11
```

In the docker container, run the following commands.
```bash
apt update
apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev git
curl https://pyenv.run | bash
echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc
echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
exec "$SHELL"
```

Now that `pyenv virtualenv` is installed, run these commands to build the wheel. You need to be specific about the `$PYTHON_WANTED` variable, use <major>.<minor>.<patch>. (I used 3.9.14)
```bash
export PYTHON_WANTED="<replace with the version of Python you want to build the wheel for>"
pyenv install $PYTHON_WANTED
pyenv virtualenv $PYTHON_WANTED catboost_build
pyenv activate catboost_build
git clone https://github.com/arestifo/catboost
cd catboost/catboost/python-package/catboost
python3 ../mk_wheel.py --target-platform=default-linux-aarch64 -DPYTHON_BIN=/root/.pyenv/shims/python -DPYTHON_CONFIG=/root/.pyenv/versions/$PYTHON_WANTED/bin/python3-config -DHAVE_CUDA=no --build-widget=no
mv ../*.whl /wheel_out
```

Your wheel file should be in the directory you ran `docker run` from. 

Let me know if you have any issues with the commands! Enjoy `catboost` on native `linux/arm64` :)

**Comment by rivershah** [comment]
@arestifo Your instructions are entirely clear and I was able to use. May I please request that you add wheels for python 3.10 `/aarch /arm64` in your repo as that simplifies container building for the community till the `catboost` devs make this generally available. Thank you!

**Comment by arestifo** [comment]
@rivershah sure, I will add them when I get a chance!

**Comment by ryanshrott** [comment]
@arestifo I'm new to docker. I am getting the same error as the OP. Would you mind helping me modify this `Dockerfile` to include your commands?

```
FROM amd64/python:3.9-slim

EXPOSE 8501

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip3 install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
```


Requirements.txt:

```
catboost==1.1
deta==1.1.0
geocoder==1.38.1
geopy==2.2.0
joblib==1.1.0
nltk==3.7
```

**Comment by ryanshrott** [comment]
> 
@arestifo I tried that, but get this error on the first command:
$ docker run -it --platform=linux/amd64 -v $(pwd)/:/wheel_out debian:11

exec /bin/bash: exec format error

Any advice?

**Comment by arestifo** [comment]
@ryanshrott You need to make sure you have `arm64` emulation enabled, check the link [here](https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/)

**Comment by cycchow** [comment]
since I am using macOS, I would like to run, should I run the compilation in a x86_64 or arm64 host machine? since I did try both, but failed.

**Comment by caliKev** [comment]
Is it possible to build this on aarch64?I don’t have access to an x86 and the build keeps failing for me. 

@arestifo could you please publish a wheel for Catboost 1.1.1?

**Comment by andrey-khropov** [comment]
Do you need to build from the codebase that corresponds exactly to CatBoost version 1.1.1 ?

If you are ok with building from master you should try build using the following:

1) Prerequisites:
- python 3.7+
- CMake 3.18+
- CLang 12+
- Conan (1.57-1.59, 2.x won't work for now)
- Some build program (ninja is preferable but make is also possible) 

2) If catboost is cloned from github to the directory $catboost_src_dir :

```
cmake $catboost_src_dir -B $build_dir -G  $generator -DCMAKE_BUILD_TYPE=$build_type -DCMAKE_TOOLCHAIN_FILE=$catboost_src_dir/build/toolchains/clang.toolchain -DCATBOOST_COMPONENTS=$catboost_components
```

where

`$generator` - “Ninja" for Ninja or “Unix Makefiles” for make.
`$build_type` - build type - `Debug` or `Release`
`$catboost_components` - ";"-separated components from CatBoost to build (configure for all components if not specified):

 - `app` - build catboost app
 - `libs` - application libraries from `libs/model_interface`
 - `R-package` - for R package shared library
 - `python-package` - for Python package shared library
 - `jvm-packages` - for JVM applier
 - `spark` - for packages for Spark

`clang.toolchain` expects that `clang` will point to `clang` 12+, if the default `clang` has version less than 12 then you have to either replace `clang` with the `clang` with the newer version (like `clang-12`, `clang++-12`).
Or either copy the toolchain to the new file and make the necessary changes there and pass it to `CMAKE_TOOLCHAIN_FILE` instead. 

3. After cmake run either

```
ninja -C $build_dir $targets
```

or 

```
make -C $build_dir -j $build_threads_count  $targets
```
where `$targets` is space-separated list of binary artefacts to build:
- `catboost` - CLI app
- `_catboost` - python package shared library
-  `catboostmodel` - C/C++ applier shared library
-  `catboostmodel_static` - C/C++ applier static library with CatBoost dependencies linked in.
- `catboost_train_interface` - C/C++ train API shared library
- `catboost4j-prediction` - JVM applier JNI shared library
- `catboost4j-spark-impl` - Spark native JNI shared library part.
- `catboostr` - R package shared library

**Comment by andrey-khropov** [comment]
> since I am using macOS, I would like to run, should I run the compilation in a x86_64 or arm64 host machine? since I did try both, but failed.

Do you want to cross-compile from macOS to Linux aarch64? That's not possible right now. You can build on Linux aarch64 natively or cross-compile from Linux on x86-64.

The same situation is with macOS. You can build for macOS arm64 either natively or cross-build from macOS on x86_64. Note though that catboost release artifacts for macOS already contain universal binaries so they run natively on macOS on both x86-64 and arm64.

**Comment by andrey-khropov** [comment]
I've also updated setup.py that it now also works with new CMake-based build in master (for native compilation).

**Comment by caliKev** [comment]
Thanks I really appreciate the thorough replies. I have to go through it and figure out exactly what I need to build. I’m trying to get the ML functions on OpenBBterminal working.  I want to build and run on Linux aarch64 (raspberrypi)

**Comment by d1bevz** [comment]
> After cmake run either:
> 
> ```
> ninja -C $build_dir $targets
> ```

During this stage I get error ` ld.lld: error: undefined symbol: __aarch64_cas8_acq_rel`

**Comment by andrey-khropov** [comment]
@d1bevz 

Please add more context:

- What is your OS version and `libc` and `gcc` packages version (gcc could be used by conan to build some intermediate packages)
- Do I understand correctly that `lld` has the same version as clang (16) ?

**Comment by d1bevz** [comment]
@andrey-khropov Sure!

- OS: Debian 10.2.1-6 (in Mac Docker)
- I switched to `clang+llvm-15.0.3-aarch64-linux-gnu`, but resulted in the same error
- `libc` not installed or I don't know how to check a version 
- `gcc` version 10.2.1 20210110
- `lld` version 15.0.3

**Comment by josemiguelalves** [comment]
@arestifo, any updates on adding wheels for python 3.10 /aarch /arm64 in your repo?

**Comment by andrey-khropov** [comment]
> @arestifo, any updates on adding wheels for python 3.10 /aarch /arm64 in your repo?

You can try rc version of CatBoost python package: https://github.com/catboost/catboost/issues/2213#issuecomment-1515000094

**Comment by andrey-khropov** [comment]
With the release 1.2 wheels for Linux aarch64 now available on PyPI
