### ISSUE TITLE
pickle fails with Pool object

### ISSUE THREAD

**Issue by shgoren** [catboost/catboost#2097]
Problem: 
Pickle dump fails with Pool object.
error message:
`TypeError: no default __reduce__ due to non-trivial __cinit__`
From a few google searches I got that it's probably something to do with pickling cython code

catboost version: 1.0.5
Operating System: Ubuntu 16.04.7

Minimal code for reproducing error
```
import numpy as np
from catboost import Pool
import pickle
X = np.random.rand(10,5)
y = np.random.rand(10)
p = Pool(X, y)
with open("file", 'wb') as f:
    pickle.dump(p, f)
```

**Comment by LyzhinIvan** [comment]
Hi, @shgoren! 

You can use [`save`](https://catboost.ai/en/docs/concepts/python-reference_pool_save) method instead.
