### ISSUE TITLE
CatBoostError: catboost/libs/data/features_layout.cpp:511: Feature #8 is used in data to quantize, but not available in quantized info

### ISSUE THREAD

**Issue by k3ybladewielder** [catboost/catboost#2101]
Problem:
I couldn't reproduce the error with scikitlearn's make_classification so here's a description.
With a dataset with 8 features, all in the Dtype category, such as state, city, income range, age range (all sensitive information and cannot be disclosed)... When training the model and predicting the result OK, it works normally . But when trying to train another model or even the same one the following error occurs.

```CatBoostError: catboost/libs/data/features_layout.cpp:511: Feature #8 is used in data to quantize, but not available in quantized info```

catboost version: '1.0.5'
Operating System: Ubuntu 21.10

**Comment by LyzhinIvan** [comment]
Can you provide your script without data? I wanna look at parameters and order of steps you describe.

**Comment by k3ybladewielder** [comment]
yes

```cat_feats = list(x_itrain.select_dtypes(include=['category', 'object']).columns)
scale_pos = 5.3

cat_model_ind = CatBoostClassifier( task_type='CPU', leaf_estimation_iterations=4, iterations=1000, learning_rate=0.05, scale_pos_weight=scale_pos)
cat_model_ind.fit(x_itrain, y_itrain, eval_set= (x_itest, y_itest), cat_features = cat_feats, silent=True, use_best_model=True)```

**Comment by LyzhinIvan** [comment]
At which step it fails? What is the difference between parameters of two models?

**Comment by k3ybladewielder** [comment]
Fail on fit
The difference between the two had been the number of iterations. But when trying to look at the above model again the error occurs.

**Comment by LyzhinIvan** [comment]
This error can occur only if test dataset has more features than train dataset. Please check that your train and test datasets have equal number of features and you don't change x_itest between runs.

**Comment by k3ybladewielder** [comment]
Checked and train/test dataset dont change

**Comment by LyzhinIvan** [comment]
Then the situation when your provided script success/fail randomly is impossible. Try to create full reproducible script and provide it without data. 
By the way, what do you mean by "when trying to fit the above model again"? Do you re-run a cell with this code in Jupyter?

**Comment by k3ybladewielder** [comment]
I'm closing the issue.
I reviewed the code and found an error that changed the number of features in the test dataset. Thank you for your support

**Comment by k3ybladewielder** [comment]
I'm closing the issue.
I reviewed the code and found an error that changed the number of features in the test dataset. Thank you for your support
