### ISSUE TITLE
C++ build failing

### ISSUE THREAD

**Issue by swapnil96** [catboost/catboost#2107]
Problem: makefile to build c++ libs have "None" keyword in them which is not working with make. This issue is only in the master branch. I checked tag v1.0.6, there this issue was not there. But then this issue pops up https://github.com/catboost/catboost/issues/2025
catboost version: 1.0.6
Operating System: 5.14.0-1038-oem #42-Ubuntu SMP  x86_64  GNU/Linux
CPU: x86_64
GPU: Not used

**Comment by alishuja** [comment]
Is there any update regarding this issue? Or a workaround? Thanks!

**Comment by swapnil96** [comment]
@alishuja For now I am working with the shared lib file that is provided in the v1.0.6 release. So I am not building the lib myself rather using the shared lib provided by catboost

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
generation of makefiles has been fixed
please reopen this issue, if this is still broken
