### ISSUE TITLE
Does CatBoost model actually use GPU for prediction? 

### ISSUE THREAD

**Issue by Hhhh8** [catboost/catboost#2113]
Problem: Does CatBoost model actually use GPU for prediction? 

I wonder if the catboost model actually uses the gpu for prediction. I used gpu in colab and I saw gpu resources used when training, but not when predicting. It was almost the same when measuring time with GPU and CPU in task_type.

Here is the code I used.
```
from catboost import CatBoostClassifier
import numpy as np

x_train = np.random.rand(100, 10)
x_test = np.random.rand(10000, 10)
y = np.random.choice(['a','b'], 100)

clf = CatBoostClassifier(task_type='GPU')
clf.fit(x_train, y)
clf.predict(x_test, task_type='GPU')
```

Another confusing thing is that the task_type parameter is not in the documentation, but in the function docstring. Is the document simply in need of modification? https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier_predict

Looking at the release notes, 'Add model evaluation on GPU' function was added in version 0.26, and I saw the phrase 'Fix predict on GPU' in version 1.0.5 bugfix.

Does 'predict on GPU' mean to use gpu for evaluation, not prediction?

catboost version: 1.0.6
Operating System: Ubuntu 20.04.2 LTS
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
GPU: GeForce RTX 3060
Nvidia Drvier: 460.80
CUDA version: 11.2

**Comment by ek-ak** [comment]
Hello! Catboost сcould use GPU for prediction, but it does not need a lot of resources and you can't see it. For training catboost allocates practically entire GPU card, and you see it. If you run these test example in CPU-only environment, prediction on GPU fails. We will update the documentation.

**Comment by ElectroidDes** [comment]
> Hello! Catboost сcould use GPU for prediction, but it does not need a lot of resources and you can't see it. For training catboost allocates practically entire GPU card, and you see it. If you run these test example in CPU-only environment, prediction on GPU fails. We will update the documentation.

Please tell me, I didn't find in the documentation on which video cards Catboost can work, or more precisely what API CatBoost uses for calculations? CUDA (meaning only Nvidia), OpenCL, OpenGL computing shaders or Vulkan?

**Comment by andrey-khropov** [comment]
> > Hello! Catboost сcould use GPU for prediction, but it does not need a lot of resources and you can't see it. For training catboost allocates practically entire GPU card, and you see it. If you run these test example in CPU-only environment, prediction on GPU fails. We will update the documentation.
> 
> Please tell me, I didn't find in the documentation on which video cards Catboost can work, or more precisely what API CatBoost uses for calculations? CUDA (meaning only Nvidia), OpenCL, OpenGL computing shaders or Vulkan?

CUDA. It is clearly described in documentation: 
https://catboost.ai/en/docs/concepts/python-installation#gpu-system-requirements
https://catboost.ai/en/docs/installation/r-installation-conda-install
https://catboost.ai/en/docs/concepts/cli-installation#gpu-system-requirements
https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper
https://catboost.ai/en/docs/concepts/java-package
