### ISSUE TITLE
Error target_converter.cpp:379: Target with classes must contain only 2 unique values for binary classification

### ISSUE THREAD

**Issue by Manwithoutmind** [catboost/catboost#2116]
Problem:
cv_params = model.get_params()
cv_params.update({
    'loss_function': metrics.Logloss()
})
cv_data = cv(
    Pool(X, y, cat_features=categorical_features_indices),
    cv_params,
    plot=True
)

CatBoostError                             Traceback (most recent call last)
Input In [21], in <cell line: 5>()
      1 cv_params = model.get_params()
      2 cv_params.update({
      3     'loss_function': metrics.Logloss()
      4 })
----> 5 cv_data = cv(
      6     Pool(X, y, cat_features=categorical_features_indices),
      7     cv_params,
      8     plot=True
      9 )

File env\lib\site-packages\catboost\core.py:6501, in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, metric_update_interval, folds, type, return_models, log_cout, log_cerr)
   6499 with log_fixup(log_cout, log_cerr), plot_wrapper(plot, plot_dirs):
   6500     if not return_models:
-> 6501         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
   6502                 metric_update_interval, as_pandas, folds, type, return_models)
   6503     else:
   6504         results, cv_models = _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
   6505                                  metric_update_interval, as_pandas, folds, type, return_models)

File _catboost.pyx:5451, in _catboost._cv()

File _catboost.pyx:5483, in _catboost._cv()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:379: Target with classes must contain only 2 unique values for binary classification

catboost version: 1.0.6
Operating System: Win 64-bits
CPU:
GPU:

**Comment by andrey-khropov** [comment]
If you want binary classification (and if you use `Logloss` loss function this is what you are doing) your target / label data must contain only two distinct values for two classes.

The error states that your label data is not correct for this case because it contains more than two distinct values that is not suitable for binary classification.
