### ISSUE TITLE
CatBoost to classify DataFrames

### ISSUE THREAD

**Issue by algomaschine** [catboost/catboost#2123]
**Problem**: can I use CatBoost to classify around 40,000 different data series with various numeric properties (like stationarity, some other math metrics pre-calculated and assigned as features, some categorical labels, etc) in order to figure out which feature set can be used to curves that instruments that exhibit truly similar behavior?

catboost version: any
Operating System: windows server 2016
CPU: 32-core AMD
GPU: none

**Comment by algomaschine** [comment]
> if you mean some kind of clustering, then CatBoost is not applicable directly to build a model, CatBoost needs a training dataset which contains enough examples for each equivalence class

Well clustering is a way of classification, so I though CatBoost could give me a neat shortcut to find best categorization criteria. Also stable criteria, if that makes any sense....

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
my point is that, if the classes are known in advance, and there are enough examples for each class, then yes, CatBoost classifier is applicable 😃 
https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier

if we want to split our data into clusters according to some 'similarity', then CatBoost is not directly applicable

**Comment by algomaschine** [comment]
Oh thanks, I see. How about 'indirectly', can it propose some type of classification that would make sense?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
classification is assigning one of _known_ classes to a sample
grouping 'similar' samples is called clustering, _not_ classification
to get started with clustering, you may look at the k-means algorithm

**Comment by algomaschine** [comment]
Thank you, Evgueni.
