### ISSUE TITLE
[JVM] catboost-prediction crashes with text_features on JDK/JRE 11

### ISSUE THREAD

**Issue by andrey-khropov** [catboost/catboost#2132]
Problem: catboost-prediction crashes with text_features on JDK/JRE 11
catboost version: 1.0.6
Operating System: Mac OS 11.6.4
CPU: Intel i7

**Comment by dgno** [comment]
I have a problem that may be associated to this.  
Problem: catboost-prediction generates an EXCEPTION_ACCESS_VIOLATION - OpenJDK 17
catboost version: 1.0.6
OS: Windows 10 64 bit
CPU: AMD Ryzen 7
The model, which was generated in Python and for which prediction works in Python, loads fine, but running CatBoostPredictions.predict results in the access violation.  In addition to my own program, I also tried running the CatBoost4JPredictionTutorial.java and got the same result.  Log dump file attached, and here's the console output...

loaded model...
Adult dataset model metainformation
tree count: 100
prediction dimension: 1
used numeric feature count: 6
used categoric feature count: 8

predict....
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd3045bc5e, pid=14308, tid=30560
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3dbc5e]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\dev\workspace\cg-nlp-engines\hs_err_pid14308.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
[hs_err_pid14308.log](https://github.com/catboost/catboost/files/9155031/hs_err_pid14308.log)

#

**Comment by TodorKrIv** [comment]
I have a similar problem where the problematic frame is `V  [libjvm.so+0x8e0ade]` instead.

`# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc309847ade, pid=28382, tid=28414
#
# JRE version: OpenJDK Runtime Environment (11.0.15+10) (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x8e0ade]`

Using Java 8 worked for me with catboost v1.0.6.

**Comment by DanielThomas** [comment]
Same here when upgrading to JDK 17 from 8:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd71406e06b, pid=32266, tid=32699
#
# JRE version: OpenJDK Runtime Environment Zulu17.36+14-SA (17.0.4+8) (build 17.0.4+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu17.36+14-SA (17.0.4+8-LTS, mixed mode, sharing, tiered, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x88806b]  jni_ReleaseByteArrayElements+0x8b
```

Looking at the changes in 1.0.6 this destructor stood out. The `DeleteLocalRef` before the conditional `ReleaseByteArrayElements` call doesn't feel right to me, and `TJVMStringAsStringBuf` is only used for text features:

https://github.com/catboost/catboost/blob/21f8d27a98d651038a237d350a08fe355e6e2e8a/catboost/jvm-packages/catboost4j-prediction/src/native_impl/ai_catboost_CatBoostJNIImpl.cpp#L168-L171
