### ISSUE TITLE
Distribute AMD modules in the dist/ directory on CDN for the catboost-widget npm package

### ISSUE THREAD

**Issue by jasongrout-db** [catboost/catboost#2134]
In https://github.com/catboost/catboost/issues/1673#issuecomment-859593961, effort was made to distribute the catboost javascript via CDN. However, the AMD module built in the `dist/` directory from the webpack config (for use in the ipywidgets html manager, voila, etc.) is not being distributed with the npm package. We noticed this when we tried to use catboost from within the Databricks notebook, but I imagine you'd see the same thing if you tried to use the widgets from the ipywidgets html manager or Voila.

You can see that the `dist/` directory is not available at https://www.jsdelivr.com/package/npm/catboost-widget - that is what is needed (by convention) to load the widget as an AMD module in the ipywidgets html manager or Voila html manager.

I think the problem may be that the [package.json](https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/widget/js/package.json) file does not include an appropriate [`files`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files) key. We do this in the widget cookiecutter [here](https://github.com/jupyter-widgets/widget-cookiecutter/blob/3aa8c7accdc3fd815a01805df45df869d81454a3/%7B%7Bcookiecutter.github_project_name%7D%7D/js/package.json#L18-L21), for example. I think all you need to do is add this key to the [package.json](https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/widget/js/package.json) file:

```
 "files": [
    "src/**/*",
    "dist/**/*"
  ],
```
to ensure that the `dist/` directory files are packaged up in the npm package that is published.

**Comment by jasongrout-db** [comment]
@andrey-khropov - do you now when we might see a new release of the npm module? I'm excited to tell people that catboost works in Databricks and other frontends that rely on the files published in the dist/ directory.

**Comment by andrey-khropov** [comment]
> @andrey-khropov - do you now when we might see a new release of the catboost-widget npm module? I'm excited to tell people that catboost works in Databricks and other frontends that rely on the files published in the dist/ directory.

I'm making sure that other issues with the widget like #2266 are being resolved before the new release on npm. I expect the update to happen this week.

**Comment by jasongrout-db** [comment]
> I'm making sure that other issues with the widget like #2266 are being resolved before the new release on npm. I expect the update to happen this week.

Awesome. Let me know if you have any questions (I'm an ipywidgets maintainer).

**Comment by jasongrout-db** [comment]
> I expect the update to happen this week.

We see that a catboost release was published (1.2, thanks!). However, the npm catboost-widget package was not released to npm (https://www.npmjs.com/package/catboost-widget?activeTab=dependents is still on 1.0.0 from 2 years ago). In order for this issue to be fixed (i.e., for the dist/ files to be published to npm), the catboost-widget npm package also needs to be released. Can you do a release of `catboost-widget` on npm?

**Comment by dby-tmwctw** [comment]
Hi @andrey-khropov Checked just now on npm, the `catboost-widget` seems still not updated (1.0.0 from 2 years ago). May I know when will the npm package be released? If there is any blocker, I'm happy to help with it. Thanks!

**Comment by andrey-khropov** [comment]
I've updated catboost-widget package on npm to version 1.2.0 and checked that the problems originally mentioned in this issue are now fixed.

Unfortunately, I've bumped the version in catboost-widget's package.json only now in [45778c5](https://github.com/catboost/catboost/commit/45778c57dfe57e57d6e1493109cc29f0c21b2777) so CatBoost python-package from the release 1.2 will try to download the older catboost-widget 1.0.0 from npm CDN.

But for CatBoost python-package built from the master branch with revisions newer than [45778c5](https://github.com/catboost/catboost/commit/45778c57dfe57e57d6e1493109cc29f0c21b2777) everything works.

From now on we will synchronize version updates in the main CatBoost python package and the catboost-widget npm package: #2383

**Comment by jasongrout-db** [comment]
> Unfortunately, I've bumped the version in catboost-widget's package.json only now in [45778c5](https://github.com/catboost/catboost/commit/45778c57dfe57e57d6e1493109cc29f0c21b2777) so CatBoost python-package from the release 1.2 will try to download the older catboost-widget 1.0.0 from npm CDN.

Because the python package actually requested npm package `^1.0.0`, it actually works right now and picks up the 1.2.0 javascript. I can confirm catboost now shows the widget in Databricks. Thanks!
