### ISSUE TITLE
How to continue training from a saved/loaded model & prevent overfitting

### ISSUE THREAD

**Issue by markdregan** [catboost/catboost#2138]
Problem: There are two aspects to my question. Help with either is much appreciated. For context, I want to train a regression model in a training dataset & to eval against a test dataset - such that I can stop training before overfitting occurs. Now for my problem, the test dataset is very important to my problem (data is temporally ordered - eg forecast type). So I want to be able to a) load the previously trained model
b) get the params from the model 
c) continue to train this model using the test dataset
d) ideally prevent overfitting of this secondary training exercise (not sure how to articulate this)

Any guidance I can get on this objective/goal would be much appreciated. 

catboost version: 1.0.6
Operating System: Mac OS Monterey 21F79
CPU: Apple M1 Pro
GPU: Apple M1 Pro

**Comment by ek-ak** [comment]
Hello! 
1. You can use [get_all_params](https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier_get_all_params), get_param or get_params methods to obtain params.
2. You can continue training with  [init_model](https://github.com/catboost/catboost/issues/1176) option
3.  Required iterations number  for pool could be obtained like that: You define required iterations number with cross-validation. Cross-validation is trained on part of pool, so training on full pool needs a bit more iterations, like  `obtained_iterations * 1.1` .

**Comment by markdregan** [comment]
Thank you Ekaterina,

I have a few clarifying questions. Appreciate your guidance here.

1. When I load a previously trained model, are the model params "set" from the previous training iteration? ie. Have we done some work (via cross validation) to "lock in" the best model params for this dataset? Such that when I continue training using `init_model` we are constraining the leaning problem somewhat? Or are these params learned all over again?

2. Or are you suggesting differently - that I should obtain the "optimum" model params from cross validation. And then retrain the model on the entire dataset using these "optimum" params & defining the number of learning iterations to be some increment above the original "optimum learning" (eg. `obtained_iterations * 1.1`).

Scenario A:
- Train model on train_pool with CV on test_pool until happy with performance
- Get params of model trained (including obtained_iterations)
- Continue training using `init_model` using test_pool for (eg) 10% more iterations

Scenario B
- Train model on train_pool with CV on test_pool until happy with performance [same]
- Get params of model trained (including obtained_iterations) [same]
- Train a new model on train_pool + test_pool but by setting the params and learning iterations of this model based on above "optimum" params.

Many thanks
Mark
