### ISSUE TITLE
reproduce quantile regression

### ISSUE THREAD

**Issue by WILLCHEN05** [catboost/catboost#2139]
Problem: Hi Teams，I am trying to customize a segmented MAE loss function. As i know, the build-in quantile loss function of catboost is the special case of my customized segmented loss function. But i can not reproduce the quantile loss. Here is the code:

class MultiStageMAEObjective(object):
    def calc_ders_range(self, approxes, targets, weights):
        assert len(approxes) == len(targets)
        if weights is not None:
            assert len(weights) == len(approxes)
        
        der1 = 0
        der2 = 0
        result = []
        for index in range(len(targets)):
            if targets[index] - approxes[index] < -5:
                der1 = -0.27
                der2 = 0
            elif targets[index] - approxes[index] >= -5 and targets[index] - approxes[index] <= 0:
                der1 = -0.27
                der2 = 0
            elif targets[index] - approxes[index] > 0:
                der1 = 0.73
                der2 = 0
            else:
                if weights is not None:
                    der1 *= weights[index]
                    der2 *= weights[index]

            result.append((der1, der2))
        return result

Does it equal to the 'Quantile:alpha=0.73' function? Or do I miss some important info of the build-in quantile loss?

Thank you for your help!

catboost version:1.0.4
Operating System: macOS
CPU:
GPU:

**Comment by WILLCHEN05** [comment]
It seems that the build-in '**Quantile:alpha=0.73**' loss function use **Exact** leaf estimation method, but the customized loss function is not supported by **Exact** leaf estimation method, so it use '**Newton**' leaf estimation method. Is there any document of how **Exact** leaf estimation method works?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
here is the implementation of quantile loss
https://github.com/catboost/catboost/blob/cf7ee63d0b7031fc38c6b05f0b2bf15b167fce1f/catboost/private/libs/algo_helpers/error_functions.h#L454

your python code looks okay except the last `else` -- we multiply by weights regardless of `targets[index] - approxes[index] > 0`

`Exact ` leaf estimation predicts the exact quantile (taking sample weights into account) for the samples in each leaf

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
should you have further questions, please do not hesitate to reopen
