### ISSUE TITLE
linux aarch64 on PyPi

### ISSUE THREAD

**Issue by DylanModesitt** [catboost/catboost#2141]
Are there plans to publish linux aarch64 versions of the library for current or future releases? Last year, there was some mention that this was on the docket (#1472). I believe with graviton and other entry points, more and more users may find themselves on arm boxes - so it may be prudent to publish wheels.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
i close this because it duplicates of #2091 -- we hope to complete this soon
