### ISSUE TITLE
CatBoostClassifier consumes more memory in the new versions

### ISSUE THREAD

**Issue by PerformanceDetect** [catboost/catboost#2142]
### Problem
I have found that ```CatBoostClassifier``` has different memory usage in different versions. In my program, when the **catboost** version was **0.10.3**, the peak memory of ```CatBoostClassifier``` was **1.46MB**, but when I changed the **catboost** to the **latest version**, the memory consumption increased to **132MB**. I also tested other versions of catboost, and the detailed experiments The results are shown in the table below.
**My question is, why is there a new version that consumes more memory and is there a way to fix it?**

 Memory(MB) | Version
-- | --
 132 | 1.0.3
 131.76 | 0.25.1
131.70 | 0.24.4
131.66 | 0.23.2
131.68 | 0.23
131.65 | 0.20.2
21.42 | 0.17.5
19.02 | 0.16.5
18.99 |0.15.2
18 |0.12.2
**1.46** |**0.10.3**
### Catboost version:
1.0.3,0.25.1,0.24.4,0.23.2,0.23,0.20.2,0.17.5,0.16.5,0.15.2,0.12.2,0.10.3
### Code to Reproduce
**Dataset :** [dataset.zip](https://github.com/catboost/catboost/files/9252694/dataset.zip)
**Code :** 
```python
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

db_train=pd.read_csv('train.csv')
db_test=pd.read_csv('test.csv')

db_merged=pd.concat([db_train,db_test],ignore_index=True)
import nltk
import re
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
ps=PorterStemmer()
wn=WordNetLemmatizer()
corpus=[]
stopwords=set(stopwords.words('english'))
for i in range(0, len(db_merged)):

    review = re.sub('[^a-zA-Z]', ' ', db_merged['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [wn.lemmatize(word) for word in review if word not in stopwords]
    review = ' '.join(review)
    corpus.append(review)
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5500,ngram_range=(1,3))
tf=tfidf.fit_transform(corpus).toarray()

db_final=pd.DataFrame(data=tf)
Train=db_final[0:7613]
Test=db_final[7613:]
Train['target']=db_train['target']
X=Train.drop(['target'],axis=1)
y=Train.target
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
from sklearn import metrics
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf = PassiveAggressiveClassifier()
linear_clf.fit(X_train, y_train)
import time
start_time = time.time()
import tracemalloc
tracemalloc.start()
import catboost
from catboost import CatBoostClassifier
clf=CatBoostClassifier()
clf.fit(X_train, y_train)
y1 = clf.predict(X_test)
current3, peak3 = tracemalloc.get_traced_memory()
print("Get_dummies memory usage is {",current3 /1024/1024,"}MB; Peak memory was :{",peak3 / 1024/1024,"}MB")
over_time = time.time()
total_time = over_time - start_time
print("Time: %s s" % total_time)
```

### Device info
Operating System: Linux Ubuntu 16.04
CPU: Intel(R) Core(TM) i9-9900K CPU
GPU: TITAN V

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
i can reproduce your figures only approximately
i see a jump in ram consumption from 34m to 150m in release 0.20
i think that it is caused by the fix of https://github.com/catboost/catboost/issues/1079 which copies sliced dataframes to contiguous memory before passing to catboost
if we copy the dataframes before passing to catboost, then ram consumption goes back to 34m with 0.20

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
btw we have added to catboost text features support https://catboost.ai/en/docs/features/text-features

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
i also noticed a nice 8x speedup on 16 cores 108s with 0.10.3 -> 13s with 1.0.6

**Comment by PerformanceDetect** [comment]
Thanks for your quick reply!
I test the execution time from 0.10.3 to 1.0.3.  The new version has speed up the running time compared to the old version.
 Runtime(s) | Version
-- | --
12.60 | 1.0.3
12.27 | 0.25.1
13.05 | 0.24.4
13.48| 0.23.2
13.44 | 0.23
13.48 | 0.20.2
67.42 | 0.17.5
78.84 | 0.16.5
78.10 |0.15.2
72.72 |0.12.2
73.24 |**0.10.3**
> i also noticed a nice 8x speedup on 16 cores 108s with 0.10.3 -> 13s with 1.0.6
