### ISSUE TITLE
multiclass and gpu

### ISSUE THREAD

**Issue by frostyduck** [catboost/catboost#2144]
I received the following error 

`_catboost.CatBoostError: catboost/private/libs/options/catboost_options.cpp:936: On GPU loss MultiClass can't be used with ordered boosting
`

I know that GPU mode now supports MultiClass, but I can't figure out what my error means?

**Comment by chenuvjcjch** [comment]
same problem

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
dear @frostyduck 🤝
dear @chenuvjcjch 🤝
we are very much glad that you are giving catboost a try 😄  
most likely, boosting_type='Ordered' is set somewhere (maybe, by catboost itself, to reduce over-fitting for small datasets)
could you please try adding boosting_type='Plain' to the training options?
