### ISSUE TITLE
【Question】catboost for spark how to exit 

### ISSUE THREAD

**Issue by chencjiajy** [catboost/catboost#2151]
Problem: catboost for spark application not exit after finished, it hangs....., `spark.stop()` not work。 how to make the application exit after training. （ps:both IDEA and spark-submit not exit)
catboost version:1.0.6

[example](https://github.com/catboost/catboost/blob/313d5a014b000933feecd29f214220738cf64d85/catboost/spark/catboost4j-spark/core/src/test/scala/ai/catboost/spark/CatBoostRegressorTest.scala#L1474)

<img width="1123" alt="how to exit catboost for spark" src="https://user-images.githubusercontent.com/19321967/185774812-7b64a626-ca6b-4f4c-8590-c1d881cd2719.png">

**Comment by shuchih** [comment]
same problem here

**Comment by tqtensor** [comment]
We have the same problem.

**Comment by art777nn** [comment]
We have the same problem.

Tried to run different versions catboost-spark:
catboost-spark_3.4_2.13:1.2.2, 1.2, 1.2.1
catboost-spark_3.4_2.12:1.2.2, 1.2, 1.2.1

Context:
Kubernets 1.27.7 
Spark 3.4.2
Scala 2.13 or 2.12
Catboost 1.2.2
PySpark 3.4.2

Driver does not stop after fit call.

Attached extended logs that are an output after the python script is completed. You can see that at the end of logs PoolingHttpClientConnectionManager attempts to close idle connections infinitely.

Log line output:
`PoolingHttpClientConnectionManager: Closing connections idle longer than 60000 MILLISECONDS
`
[log_catboost.txt](https://github.com/catboost/catboost/files/14049389/log_catboost.txt)

**Comment by andrey-khropov** [comment]
Fixed in https://github.com/catboost/catboost/commit/2cdb8a2d52777538f3f07d8692132abd99dc18e2, the good news is that is was just auxiliary threads not shut down at the end of the program execution, the main computation logic had not been affected, the training, model prediction etc. results should be valid.

**Comment by art777nn** [comment]
> Fixed in [2cdb8a2](https://github.com/catboost/catboost/commit/2cdb8a2d52777538f3f07d8692132abd99dc18e2), the good news is that is was just auxiliary threads not shut down at the end of the program execution, the main computation logic had not been affected, the training results should be valid.

Thank you! This commit cured the application! Can you please tell me when we can expect a patch in maven?

**Comment by andrey-khropov** [comment]
> Can you please tell me when we can expect a patch in maven?

This week.

**Comment by KernelA** [comment]
I have the same issue on:
```
catboost-spark_3.3_2.12-1.2.7
Java11
Python 3.10
```
