### ISSUE TITLE
Accuracy changes each time I run my code.

### ISSUE THREAD

**Issue by rohans609** [catboost/catboost#216]
The accuracy of my model changes each time I run my code even though I haven't made any changes to the parameters of the CatboostClassifier. Sometimes I get a very high accuracy and sometimes it goes down.  I haven't been able to achieve the same accuracy(which is the highest till now) when I had run my code for the first time. what should I do?

**Comment by JustM57** [comment]
fix random seed

**Comment by annaveronika** [comment]
By default each time you have a new random seed. This seed is written in the model. If you want to reproduce some training that was done without fixed random seed, you need to check model.random_seed_
