### ISSUE TITLE
can I update a ready model?

### ISSUE THREAD

**Issue by algomaschine** [catboost/catboost#2166]
Problem: can a model stored into a file be updated with new data to retrain?
catboost version: latest
Operating System: any
CPU:
GPU:

**Comment by andrey-khropov** [comment]
You can update the model by using `init_model` parameter of the the `fit` function. See examples [here](https://catboost.ai/en/docs/concepts/python-usages-examples#training-continuation)

**Comment by algomaschine** [comment]
Many thanks! Sorry for bothering you! I could recall there was
something like this, but could not find it again :)

model2.fit(train_data, train_labels, init_model=ORIGINAL_MODEL_VARIABLE)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
as far as i understand this is solved, so i close the issue
