### ISSUE TITLE
please tell me where oblivious tree source code is ，thank

### ISSUE THREAD

**Issue by trianbin** [catboost/catboost#2169]
Problem:
catboost version:
Operating System:
CPU:
GPU:

**Comment by ek-ak** [comment]
Hi! Could you clarify what part of code do you need?

**Comment by trianbin** [comment]
Thanks! I need to implement source code of the oblivious tree and some of the material related to the oblivious tree

**Comment by trianbin** [comment]
> ?



> Thanks! I need to implement source code of the oblivious tree and some of the material related to the oblivious tree

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @trianbin 
you may start by looking at the following function (this is the cpu part)
https://github.com/catboost/catboost/blob/5a769854f2327c6db4def9d073a324b9507c8eba/catboost/private/libs/algo/greedy_tensor_search.cpp#L1152

**Comment by trianbin** [comment]
> hi @trianbin you may start by looking at the following function (this is the cpu part)
> 
> https://github.com/catboost/catboost/blob/5a769854f2327c6db4def9d073a324b9507c8eba/catboost/private/libs/algo/greedy_tensor_search.cpp#L1152

Thanks! Could you give me some of the material related to the oblivious tree such as theory and essay?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
it is really simple, no big thins -- just watch this short video
https://www.youtube.com/watch?v=lhaOYwOxCkE
