### ISSUE TITLE
Calculating Metrics using eval_metrics

### ISSUE THREAD

**Issue by davidcomfort** [catboost/catboost#217]
I am trying to calculate AUC for bench-marking purposes.When I fit with `eval_metric='AUC'`, the AUC is printed to stdout and appears to be accurate, but when I try using either `sklearn.metrics` or `eval_metrics`, it either gives me low AUC value (which does not match the one output during training (in the case of the former), or I cannot get the proper syntax to get AUC using the `eval_metrics` method (in the case of the former).  I am using the latest version of catboost (0.5.2) in Ubuntu 16.04 and Python 3.6.

I am trying the bench-mark catboost with the datasets and method by Szilard (https://github.com/szilard/benchm-ml).

Here is the code I am using:

> `import pandas as pd`
> `import numpy as np`
> 
> `train = pd.read_csv('train-0.1m.csv')`
> `test = pd.read_csv('test.csv')`
> 
> `train['dep_delayed_15min'] = np.where(train['dep_delayed_15min'] == 'Y', 1, 0)`
> `test['dep_delayed_15min'] = np.where(test['dep_delayed_15min'] == 'Y', 1, 0)`
> `train_labels = train['dep_delayed_15min'].values.tolist()`
> 
> `from catboost import CatBoostClassifier`
> `train_data = train[['Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'UniqueCarrier','Origin', 'Dest', 'Distance', ]].as_matrix()`
> `test_data = test[['Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'UniqueCarrier','Origin', 'Dest', 'Distance', ]].as_matrix()`  
> 
> `train_data = train_data.tolist()`
> `cat_features = [0,1,2, 4, 5, 6]`
> 
> `model = CatBoostClassifier(loss_function='Logloss', random_seed=42,eval_metric='AUC')`
> `# Fit model`
> `model.fit(train_data, train_labels, cat_features)`
> `999:	learn: 0.7521919	total: 1m 15s	remaining: 0us`

> `# Get predicted classes`
> `preds_class = model.predict(test_data, verbose=True)`
> `# Get predicted probabilities for each class`
> `preds_proba = model.predict_proba(test_data)`
> 
> `test_labels = test['dep_delayed_15min'].values.tolist()`
> `from sklearn.metrics import roc_auc_score`
> `print("roc_auc_score = {}".format(roc_auc_score(test_labels, preds_class)))`
> `roc_auc_score = 0.5067065305604439`
> 
> `from sklearn.metrics import roc_auc_score`
> `preds_class_train = model.predict(train_data)`
> `print("roc_auc_score = {}".format(roc_auc_score(train_labels, preds_class_train)))`
> `roc_auc_score = 0.6309600302638458`
> 
> `# Get predicted classes`
> `model.eval_metrics(data=[train_labels, preds_class_train], metrics=['Logloss', 'AUC'])`

> ---------------------------------------------------------------------------

> TypeError                                 Traceback (most recent call last)
> <ipython-input-94-368ec19bd9be> in <module>()
> ----> 1 model.eval_metrics(data=[train_labels, preds_class_train], metrics=['Logloss', 'AUC'])
> 
> ~/anaconda3/lib/python3.6/site-packages/catboost/core.py in eval_metrics(self, data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
>     820         prediction : dict: metric -> array of shape [(ntree_end - ntree_start) / eval_period]
>     821         """
> --> 822         return self._eval_metrics(data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
>     823 
>     824     @property
> 
> ~/anaconda3/lib/python3.6/site-packages/catboost/core.py in _eval_metrics(self, data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
>     783         if tmp_dir is None:
>     784             tmp_dir = tempfile.mkdtemp()
> --> 785         metrics_score = self._base_eval_metrics(data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
>     786         return dict(zip(metrics, metrics_score))
>     787 
> 
> _catboost.pyx in _catboost._CatBoostBase._base_eval_metrics()
> 
> _catboost.pyx in _catboost._CatBoost._base_eval_metrics()
> 
> _catboost.pyx in _catboost._CatBoost._base_eval_metrics()
> 
> TypeError: expected bytes, str found

**Comment by fses91** [comment]
I am having a similar issue, what was the problem?

**Comment by annaveronika** [comment]
@fses91 The initial issue seemes to be invalid, if I understand correctly.
Could you describe what exactly you are doing and what is the error you get?

**Comment by annaveronika** [comment]
Or let's create a new issue.

**Comment by fses91** [comment]
I opend an issue.
https://github.com/catboost/catboost/issues/236

**Comment by annaveronika** [comment]
Ok, thanks! We'll look into this.

**Comment by davidcomfort** [comment]
It looks like I made an error in the way I called the probabilities. Here is the corrected code:

`# Get predicted probabilities for each class`
`preds_proba = model.predict_proba(test_data)`

`from sklearn.metrics import roc_auc_score`
`print("roc_auc_score = {}".format(roc_auc_score(test_labels, preds_proba[:, 1])))`
