### ISSUE TITLE
FutureWarning spam - `iteritems`

### ISSUE THREAD

**Issue by robcaulk** [catboost/catboost#2179]
Problem: getting FutureWarning spam regarding core catboost code.
catboost version: catboost==1.0.6
Operating System: linux 18.04
CPU: Xeon E5 10 cor cpu
GPU: Titan V

I am getting the following log spam using CatboostRegressor on GPU:

```
/.env/lib/python3.8/site-packages/catboost/core.py:1411: FutureWarning:

iteritems is deprecated and will be removed in a future version. Use .items instead.
```

Any ideas why this is popping up?

**Comment by josh-at-cape** [comment]
I am getting the same error, but downgrading from pandas==1.5.0 to pandas==1.4.4 solved the problem. I'm thinking this might be related to the recent pandas release?

**Comment by robcaulk** [comment]
Well that lines up with our code - we also just bumped pandas to 1.5.0.

So it’s up to catboost to fix their iteritems or we make a PR to do it for them. Should be pretty easy to make. Question is if they would integrate it into a quick release or not.

**Comment by robcaulk** [comment]
I updated to catboost==1.1 and the FutureWarning spam continues.

**Comment by josh-at-cape** [comment]
Yes, it will. Looks like the other ticket didn't get approved in time. It
appears, at least on my side, to be an incompatibility with pandas==1.5.0.

**Comment by andrew-kovalenk0** [comment]
Гntil this issue is resolved, this warning could be suppressed like this:
`import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd`

**Comment by kizill** [comment]
Hello, that's awfully annoying warning, i've planned fix to be done ASAP. Sorry, i guess that is caused by bundled numpy cython bindings. @andrey-khropov is debugging that case.

**Comment by songtengfei95** [comment]
> Until this problem is fixed, this warning can be suppressed as follows: > > ``` > import warnings > warnings.simplefilter(action='ignore', category=FutureWarning) > > import pandas as pd > ```

> Until this problem is fixed, this warning can be suppressed as follows: > > ```` > import warnings > warnings.simplefilter(action='ignore', category=FutureWarning) > > import pandas as pd > ```

I wonder if this has an effect on the operation of the program？

**Comment by JiangpengLi86** [comment]
> > Until this problem is fixed, this warning can be suppressed as follows: > > `> import warnings > warnings.simplefilter(action='ignore', category=FutureWarning) > > import pandas as pd >`
> 
> > Until this problem is fixed, this warning can be suppressed as follows: > > ```` > import warnings > warnings.simplefilter(action='ignore', category=FutureWarning) > > import pandas as pd > ```
> 
> I wonder if this has an effect on the operation of the program？

Seems not. At least for now.
