### ISSUE TITLE
catboost 0.5.2 bagging temperature broke

### ISSUE THREAD

**Issue by JustM57** [catboost/catboost#218]
CatboostError: catboost/libs/options/bootstrap_options.cpp:32: Error: bagging temperature available for bayesian bootstrap only
Updated from version 0.5.0. Can no longer change bagging_temperature?

**Comment by Noxoomo** [comment]
Hello!

Default sampling scheme was accidentally change to another one, which doesn't support bagging temperature. We will fix it in the next package.

For now you could manually set bootstrap_type="Bayessian" and everything will work fine.

**Comment by annaveronika** [comment]
The fix is on github now, you could build from source. Will be also in the next version on pypi.
