### ISSUE TITLE
make MultiRMSE work with textual features 

### ISSUE THREAD

**Issue by fingoldo** [catboost/catboost#2188]
Problem:
Пробую регрессию с MultiRMSE с одной текстовой фичой (и несколькими столбцами таргета), получаю ошибку. С "обычной" RMSE (и одним столбцом таргета) работает отлично (добавлено в релизе 1.1). Прошу добавить поддержку MultiRMSE с текстовыми фичами, возможно, это не потребует много усилий, раз RMSE уже работает с ними.

```python
import numpy as np
import pandas as pd
import catboost as cb

model = cb.CatBoostRegressor(loss_function="MultiRMSE", task_type="CPU") # same for task_type="GPU"

inputs = pd.DataFrame(np.random.random(size=(10 ** 2, 3)), columns=list("ABC"))
inputs["D"] = inputs["C"].astype(str)
model.fit(inputs, np.random.random(size=(10 ** 2, 10)), silent=True, text_features=["D"])
```
падает с **CatBoostError: catboost/libs/data/target.h:315: Attempt to use multi-dimensional target as one-dimensional**.

catboost version:
1.1
Operating System:
Windows
CPU: Xeon 2670
GPU: GeForce RTX 2070

**Comment by andrey-khropov** [comment]
В релизе CatBoost 1.2 добавлена поддержка текстовых признаков с MultiRMSE.

**Comment by andrey-khropov** [comment]
Дубликат #2229
