### ISSUE TITLE
GPU Training doesn't work in Python on Windows

### ISSUE THREAD

**Issue by mr2dark** [catboost/catboost#219]
Win10 x64, Python 3.5.3 x64, catboost 0.5.2 (installed via pip) CUDA 8.0 1080Ti
When using just `task_type='GPU'` I get
```
line 468, in __train_model
    eval_set=(eval_data, eval_label))
  File "C:\Python35\lib\site-packages\catboost\core.py", line 1300, in fit
    self._fit(X, y, cat_features, None, sample_weight, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot)
  File "C:\Python35\lib\site-packages\catboost\core.py", line 573, in _fit
    self._train(X, eval_set, params)
  File "_catboost.pyx", line 1005, in _catboost._CatBoostBase._train
  File "_catboost.pyx", line 793, in _catboost._CatBoost._train
  File "_catboost.pyx", line 800, in _catboost._CatBoost._train
_catboost.CatboostError: /catboost/libs/train_lib/train_model.cpp:738: GPU Device not found.
```

When using `task_type='GPU', device_config=0` I get
```
line 465, in __train_model
    task_type=TASK_TYPE, device_config=0)
  File "C:\Python35\lib\site-packages\catboost\core.py", line 1249, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "C:\Python35\lib\site-packages\catboost\core.py", line 488, in __init__
    super(CatBoost, self).__init__(params)
  File "_catboost.pyx", line 952, in _catboost._CatBoostBase.__init__
  File "_catboost.pyx", line 997, in _catboost._CatBoostBase._check_train_params
_catboost.CatboostError: /catboost/libs/options/plain_options_helper.cpp:214: Error: unknown option device_config with value 0
```
The latter one, I assume, is due to the fact that plain_options_helper.cpp expects 'devices' (as for CLI), not 'device_config' (as designed for Python)

**Comment by Noxoomo** [comment]
Hi!
We will fix this option in the next package.

For now you could select devices you want to use with:
1) Passing devices option instead of device_config
2) Setting environment variables CUDA_VISIBLE_DEVICES to devices you want to use and don't specify option in package
3) If you have only one GPU, you could leave this option to default (None).

**Comment by mr2dark** [comment]
Hi!
I actually tried option 3 by default (see "When using just task_type='GPU' I get" in the original request).
I also had tried option 1 before I wrote the issue. There's some other mechanism which prevents usage of arbitrary keyword arguments, so it didn't work either.
I will try option 2 later this week and let you know about the results. Thank you!

**Comment by Noxoomo** [comment]
Sorry, i missed first part.
Here we can't find GPU device on your machine or load GPU-version of library: _catboost.CatboostError: /catboost/libs/train_lib/train_model.cpp:738: GPU Device not found.

We will check if there are any issues in package from pip

**Comment by Noxoomo** [comment]
Hi!

Sorry for delay.
We checked package on machine we have and package works fine with any (supported) python version.

Could you please provide results of import catboost.gpu._catboost ?

**Comment by mr2dark** [comment]
For 0.5.2 it was ImportError (couldn't find a DLL file).
After upgrading to 0.5.2.1 this error has gone away.

One question before closing if you don't mind: when do you expect MultiClass loss function will be suppored on GPUs?

**Comment by annaveronika** [comment]
Let's discuss this in https://github.com/catboost/catboost/issues/228
