### ISSUE TITLE
The create_cd helper doesn't support Text features

### ISSUE THREAD

**Issue by AlexeySalmin** [catboost/catboost#2193]
I don't see neither "text_features" in parameters nor the Text label in the code: https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/utils.py#L61

But the read_cd apparently do support them: https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/utils.py#L219

**Comment by andrey-khropov** [comment]
> One more issue: feature_names indices are shifted by one: https://github.com/catboost/catboost/blame/master/catboost/python-package/catboost/utils.py#L100
> 
> This is:
> 
>     1. Very strange and inconsistent with other arguments of the same function
> 
>     2. Not reflected in the documentation. Usage examples seem to assume that feature enumeration is consistent between feature_names and cat_features https://catboost.ai/en/docs/concepts/python-reference_utils_create_cd

It is indeed a bug. I've created a separate issue #2211 for this.
