### ISSUE TITLE
still problem with plotting with ipywidgets

### ISSUE THREAD

**Issue by JustM57** [catboost/catboost#220]
Previous issue was kind of solved and closed. But it seems to be bot a good solution. Talking about the issue.
When you start working with the old jupyter notebook - there is a probability p>0 that ipywidgets won't show any plot. I'd say more than 0.9.
As a answer I got a recommendation to recreate notebook and past the whole code from the previous one. Okay. This works. After I restarted my PC same issue as before appeared. It seems to be that there is really some bad cache in the notebook which prevents from plotting. I mean recreating notebook every time restarting PC doesn't seem to be a good way.
![2018-01-12 15-38-16](https://user-images.githubusercontent.com/16518742/34875877-250a61e2-f7b0-11e7-97f0-e79b5eb8e0cd.png)

**Comment by newbfg** [comment]
Notebook caching works like dark magic :( The only way helped me was creating new notebook with different name and copy&paste it's content.

**Comment by annaveronika** [comment]
Our best guess is that if you are using the old name of the notebook, you have old cache. So if you have created notebook with older version of ipywidget, you need to not only recreate it, but also rename it.
Let us know if there are problems after renaming notebook once.

**Comment by JustM57** [comment]
@newbfg So I guess it's mostly jupyter question either catboost widget? There might be a chat on gitter of jupyter. I'll try asking there.

PS. Anna please don't close the thread, maybe we can find a better solution
PS #2 These plot looks like plotly. Is it build the same way?

**Comment by JustM57** [comment]
@annaveronika it doesn't matter on changing widgets version. I lose the ability to see the plot after restarting PC. Some bad trace in cache(

**Comment by annaveronika** [comment]
Even if the notebook was created using the new version of widget?

**Comment by JustM57** [comment]
@annaveronika yes. Restart and and everything breaks. I have 4 versions of the same notebook for now, because it's not a good idea to learn 10-40k trees with learning rate 0.001 without plot. And higher learning rates do not work in my problem(

**Comment by newbfg** [comment]
I use plotly-js with different patches and hacks to make it work inside jupyter environment.
There was a problem with upgrading ipywidgets - jupyter uses old version of catboost widget js code with new notebook environment. The only way to fix it was recreate notebook.
Your problem really looks like it because plotting _sometimes_ doesn't work. I believe it's jupyter cache question.

We can also check what you have in js:
- open console (shift+command/ctrl+i) after first empty plot
- check for errors
- execute (chromium-based browsers)
`copy(JSON.stringify({widgets: window.catboostIpythonInstances, index: window.catboostIpythonIndex}))`
- paste it here

**Comment by JustM57** [comment]
@newbfg {}
![2018-01-17 21-33-28](https://user-images.githubusercontent.com/16518742/35060125-7782fe80-fbce-11e7-9229-dc14c3dd609d.png)

**Comment by shri-msk-2018-reviewer** [comment]
I've just installed all new things and I've got this
https://yadi.sk/i/dZ9EzbNL3Reakk
https://yadi.sk/d/oL-PHPdM3Reb2s

Please try it.

If you still have problems I need your data (if it's possible) for debugging

**Comment by newbfg** [comment]
Oops wrong profile :)

**Comment by JustM57** [comment]
@newbfg same issu after reboot
![2018-01-22 14-22-21](https://user-images.githubusercontent.com/16518742/35218574-2b6f6c80-ff80-11e7-8e37-b5ed0b1508db.png)
![2018-01-22 14-22-44](https://user-images.githubusercontent.com/16518742/35218577-2dcfd366-ff80-11e7-9c02-cd3b51db3be8.png)
![2018-01-22 14-24-55](https://user-images.githubusercontent.com/16518742/35218580-304b369e-ff80-11e7-83d9-490a35b3a55b.png)

**Comment by newbfg** [comment]
I have no idea why jupyter is working like this :(

**Comment by newbfg** [comment]
https://github.com/catboost/catboost/pull/248

**Comment by annaveronika** [comment]
In case if visualization doesn't work (this might happen if old version of widgets is in cache of browser) you need to refresh notebook page and restart kernel.
