### ISSUE TITLE
Installation of R package failed (Windows 10)

### ISSUE THREAD

**Issue by alevashov** [catboost/catboost#221]
Hi, I've tried to install catboot as R package at Win 10 64 bit machine, but it failed.

Extract from logs where as I see the problem happens:

 File "C:\Users\alex\AppData\Local\Temp\Rtmpc5AHu5\devtools3d904fb37bd\catboost-catboost-31d823d\build\ymake_conf.py", line 808, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe

Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/304a3130e6d9d7fbccdff5bd2e0a651c [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/451529472 [..............] OK
make: *** [all] Error 1
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'
* removing 'D:/users/alex/Documents/R/win-library/3.4/catboost'
Installation failed: Command failed (1)

R version:
version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer           

If it makes any difference I use R from RStudio.

**Comment by annaveronika** [comment]
#63 will solve your problem. We are currently working on that.
