### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by andrey-khropov** [catboost/catboost#2213]

**Comment by lutel** [comment]
I'm not sure if this right place to start, but tried to install catboost with python 3.11 on MacOS (Silicon) but no joy... Was working fine with python 3.10.7

pip install catboost
ERROR: Could not find a version that satisfies the requirement catboost (from versions: none)
ERROR: No matching distribution found for catboost

**Comment by andrey-khropov** [comment]
> Looks like package for cp311 is missing?

 Yes. There's no package with python 3.11 support yet. We're working on it.

**Comment by mkleinbort-ic** [comment]
Hi, any updates on this :) - I know you are working on it, just so I can plan the upgrade on our side.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @mkleinbort-ic 🤝 
thank you so much for your interest in catboost 😻 
we need to switch to cmake in our packaging scripts, and this may take some time

**Comment by manueldeprada** [comment]
Python 3.11 is already out and it is the default, being automatically updated in distributions like Fedora. 

I just was thrown a lot of errors because pip installs CatBoost 0.1.1 (since it is comaptible with all python versions)

This is misleading for users. Please update packages for python 3.11.

**Comment by manueldeprada** [comment]
Also for other people having my problem, there is a temporal solution:

Just go to [](https://pypi.org/project/catboost/#files), download the latest file and rename it from `catboost-1.1.1-cp310-none-manylinux1_x86_64.whl` to `catboost-1.1.1-cp311-none-manylinux1_x86_64.whl`.

Then do `pip install catboost-1.1.1-cp311-none-manylinux1_x86_64.whl`

**Comment by mkleinbort-ic** [comment]
> hi @mkleinbort-ic 🤝 thank you so much for your interest in catboost 😻 we need to switch to cmake in our packaging scripts, and this may take some time

Yep, love catboost - keep up the good work <3

**Comment by leo-gan** [comment]
Thank you for your beautiful `catboost`. 
I'm waiting for python 3.11 support. It is important :) Thanks!

**Comment by ddobrinskiy** [comment]
> Python 3.11 is already out and it is the default, being automatically updated in distributions like Fedora.
> I just was thrown a lot of errors because pip installs CatBoost 0.1.1 (since it is comaptible with all python versions)

It's never a good idea to rely on your default python installation for a project, I suggest you use a package manager like pipenv or conda to isolate your environments and stay on 3.10 until catboost supports 3.11

> This is misleading for users. Please update packages for python 3.11.

@manueldeprada  It's also never a good idea to demand upgrades/fixes from open source projects. They are free and open, and don't owe us anything.

This kind of tone demotivates developers and poisons the OSS culture.

**Comment by manueldeprada** [comment]
> > Python 3.11 is already out and it is the default, being automatically updated in distributions like Fedora.
> > I just was thrown a lot of errors because pip installs CatBoost 0.1.1 (since it is comaptible with all python versions)
> 
> It's never a good idea to rely on your default python installation for a project, I suggest you use a package manager like pipenv or conda to isolate your environments and stay on 3.10 until catboost supports 3.11
>

That is what i did, of course. 
> > This is misleading for users. Please update packages for python 3.11.
> 
> @manueldeprada It's also never a good idea to demand upgrades/fixes from open source projects. They are free and open, and don't owe us anything.
> 
> This kind of tone demotivates developers and poisons the OSS culture.


Thanks for pointing that out for me. I had a bad day and made an unfortunate comment. I already edited my comment, I really like catboost :). Have a nice day!! :smile:

**Comment by andrey-khropov** [comment]
CatBoost release with python 3.11 support is planned for next week.

**Comment by bijoythomas** [comment]
> CatBoost release with python 3.11 support is planned for next week.

That's awesome!. Thank you! 👍

**Comment by leo-gan** [comment]
> CatBoost release with python 3.11 support is planned for next week.

Cool! Andrey, Thank you for letting us know.

**Comment by lutel** [comment]
@andrey-khropov thank you & Happy Christmas!

**Comment by leo-gan** [comment]
> CatBoost release with python 3.11 support is planned for next week
Any news on the python 3.11 support? Any information on this? Thanks!

**Comment by kizill** [comment]
Hello! We are still in process of switching from ya.make to CMakeBuilds and are fixing some technical problems. I hope we'll ship 1.2 version before 3 February.

**Comment by Innixma** [comment]
Hi @kizill, I see in your milestones for CatBoost 1.2 that the date is Feb 19th. Is this the expected release date of CatBoost 1.2? This is relevant to our testing of AutoGluon 0.7, which is planned to release on Feb 15th, on if we should continue using CatBoost 1.1 or plan to add+test CatBoost 1.2. Thanks again for the awesome package!

**Comment by wkoot** [comment]
Awesome news! Any testing help needed?

**Comment by Crispy13** [comment]
Any news for the update?

**Comment by andrey-khropov** [comment]
> Hi @kizill, I see in your milestones for CatBoost 1.2 that the date is Feb 19th. Is this the expected release date of CatBoost 1.2? This is relevant to our testing of AutoGluon 0.7, which is planned to release on Feb 15th, on if we should continue using CatBoost 1.1 or plan to add+test CatBoost 1.2. Thanks again for the awesome package!

Unfortunately we've been having some significant issues with building on Windows after our building system transition from ya make to CMake. Current estimate is that the release 1.2 will be this week or early next week.

**Comment by GavrisAS** [comment]
Any news for the update?

**Comment by rivershah** [comment]
This is proving to be a very important blocker. Any update please? Can we do release for linux and wait for windows support down the line please? Thanks!

**Comment by andrey-khropov** [comment]
> Any news for the update?

Unfortunately there've been other issues preventing us from publishing the new release that have now been resolved so it will be published in the next few days.

It is also possible to build wheels yourself from source using `python setup.py bdist_wheel` or `python -m build --wheel`.

**Comment by sarthakkaushik** [comment]
@andrey-khropov @kizill - any new update on the issue ?

**Comment by csymvoul** [comment]
Hello everyone! I am getting the following error when I try to install catboost which is I guess related to the fact that it is not supported in Python 3.11. Do you have any news on that? 

```
ERROR: Could not find a version that satisfies the requirement catboost (from versions: none)
ERROR: No matching distribution found for catboost
```

**Comment by csymvoul** [comment]
I'm getting this error now:

**Comment by ddelange** [comment]
sorry, looks like I spoke too fast. should have first read the instructions which I linked to :)

it [looks](https://github.com/catboost/catboost/commit/baa6a058daa04a50d95f532c950a74787e7414ac) like @andrey-khropov is currently trying to fix PyPI release 🤞 

[![](https://http.cat/406)](https://http.cat/406)

**Comment by csymvoul** [comment]
no problem! waiting for your updated response!

**Comment by andrey-khropov** [comment]
> sorry, looks like I spoke too fast. should have first read the instructions which I linked to :)
> 
> it [looks](https://github.com/catboost/catboost/commit/baa6a058daa04a50d95f532c950a74787e7414ac) like @andrey-khropov is currently trying to fix PyPI release 🤞

Indeed. After that commit all is working.

You can try rc0 version (the package is called catboost-dev but the installed module (i.e. what you `import`) will be the usual `catboost`):

https://pypi.org/project/catboost-dev/1.2rc0/

It is now also possible to specify `widget` extra to install additional dependencies (https://catboost.ai/en/docs/installation/python-installation-additional-data-visualization-packages) like that:

```
python -m  pip install catboost-dev[widget]==1.2rc0
```

**Comment by csymvoul** [comment]
it seems to be working now! thanks a lot both @ddelange and @andrey-khropov!

**Comment by andrey-khropov** [comment]
Release 1.2 with wheels for python 3.11 is now available on PyPI.

**Comment by lutel** [comment]
Great work Andrey! All metta to you!

**Comment by andrey-khropov** [comment]
Packages on Conda now also include python 3.11 support.
