### ISSUE TITLE
need linux-aarch ya-bin 

### ISSUE THREAD

**Issue by daqingshu** [catboost/catboost#2214]
Problem: ymake: platform (linux-aarch64) not matched to any of ['linux-ppc64le', 'darwin-arm64', 'darwin', 'win32-clang-cl', 'linux']
catboost version: 1.1.1
Operating System: ubuntu 22.04
CPU: aarch64 LE Cortex-A72
GPU: NA

**Comment by andrey-khropov** [comment]
We've recently switched from Ya Make to CMake-based build. You can try to build on Aarch64 Linux now like that: https://github.com/catboost/catboost/issues/2336#issuecomment-1486546342

**Comment by andrey-khropov** [comment]
JFYI: documentation about building with CMake has been updated to reflect the latest changes: https://catboost.ai/en/docs/installation/build-native-artifacts.

Please close the issue if you can build CatBoost on Linux aarch64 now. 
BTW, CatBoost release 1.2 includes prebuilt artifacts for Linux aarch64 for all components (#2091).

**Comment by andrey-khropov** [comment]
CatBoost on Linux aarch64 can now be built using CMake.
