### ISSUE TITLE
"no CUDA-capable device is detected" error appears occasionally on AWS instances

### ISSUE THREAD

**Issue by bra-fsn** [catboost/catboost#2217]
### Problem: 
Occasionally I get the following error on AWS instances:
```
  File "/datasci/lib/python3.8/site-packages/bidderbot-0.0.1-py3.8.egg/bidderbot/transformers/all/zoltar/train_ctp.py", line 245, in train
    model.fit(train_pool, eval_set=eval_pool, verbose=True, plot=False, use_best_model=True)
  File "/datasci/lib/python3.8/site-packages/catboost/core.py", line 5007, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/datasci/lib/python3.8/site-packages/catboost/core.py", line 2278, in _fit
    self._train(
  File "/datasci/lib/python3.8/site-packages/catboost/core.py", line 1705, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4585, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4634, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 100: no CUDA-capable device is detected
```
The job is started in a container, the GPU driver is installed and seems to be working as Nvidia tools recognize it, for eg. `nvidia-smi` returns the GPU details just fine:
```
Timestamp                                 : Mon Nov  7 05:52:03 2022
Driver Version                            : 515.48.07
CUDA Version                              : 11.7

Attached GPUs                             : 1
GPU 00000000:00:1E.0
    Product Name                          : Tesla T4
    Product Brand                         : NVIDIA
    Product Architecture                  : Turing
    Display Mode                          : Disabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : 1560821108477
    GPU UUID                              : GPU-7d993888-5458-e701-cba6-5afff1421564
    Minor Number                          : 0
    VBIOS Version                         : 90.04.96.00.02
    MultiGPU Board                        : No
    Board ID                              : 0x1e
    GPU Part Number                       : 900-2G183-A800-001
    Module ID                             : 0
    Inforom Version
        Image Version                     : G183.0200.00.02
        OEM Object                        : 1.1
        ECC Object                        : 5.0
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GSP Firmware Version                  : 515.48.07
[...]
```

The next time I run exactly the same job it either works fine or returns the same error. I couldn't figure out why is that hesitation. First I suspected different underlying hardware/FW versions, that's why I have those details in the job outputs, but from the above I can confirm they are exactly the same in the working and failing case (although these might be a lie in the AWS virtualised environment).

catboost version: 1.0.6
Operating System: Ubuntu 22.04
CPU: various, in the above case it was a `g4dn.4xlarge`, so Intel Cascade Lake
GPU: see above

**Comment by rahulmisal27** [comment]
I am also facing similar issue with this type of instance. 

I am not sure why training with GPU with catboost on AWS is not reliable at all. I am struggling to find a good solution to this problem. 

Most of time training jobs fails with `corrupted size vs. prev_size` error , No matter which catboost version you use. 

One more question I was having that why AWS provides catboost only with CPU instance? They provide below comment in their [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/catboost.html) but which does not explain reason in simple words. 

> SageMaker CatBoost currently only trains using CPUs. CatBoost is a memory-bound (as opposed to compute-bound) algorithm. So, a general-purpose compute instance (for example, M5) is a better choice than a compute-optimized instance (for example, C5). Further, we recommend that you have enough total memory in selected instances to hold the training data.

**Comment by bra-fsn** [comment]
Closing this, because it doesn't seem to be a catboost issue.
After I could finally reproduce it consistently, I found what causes this.
One possible solution is described here:
https://bbs.archlinux.org/viewtopic.php?id=266915

**Comment by EvanZ** [comment]
@bra-fsn I have this same error but reading through that thread I don't understand what the actual problem is. Also I am not using Docker. What specifically did you need to do to fix this and do you think your fix was only relevant for Docker?
