### ISSUE TITLE
Need information - on how to configure the proxy to clone the repository

### ISSUE THREAD

**Issue by wabecerra** [catboost/catboost#222]
Hello, 

I am trying to install Catboost on a Win 10 64 bit machine. I followed the steps on the website: https://tech.yandex.com/catboost/doc/dg/concepts/r-installation-docpage/
But I am stuck at step 5, I do not know what values to put in: 

git config --global http.proxy http://**login:password@ip_address:port_number**
> login and password are the proxy credentials???
> ip_address is the IP address of the proxy server???
> port_number is the configured proxy port number???

What would be the proxy credentials, port, and server?

This question might be obvious to you but I kindly ask for any help. Thanks.

**Comment by annaveronika** [comment]
This is optional, if you have proxy. We'll clarify this in documentation, thanks for your feedback!

**Comment by annaveronika** [comment]
now this is fixed
