### ISSUE TITLE
Bug with Cross Validation

### ISSUE THREAD

**Issue by olegkorshunov** [catboost/catboost#2221]
Problem: Bug with Cross Validation ( 'task_type':'GPU')
catboost version: 1.1.1 
Operating System: Linux
CPU: Intel(R) Xeon(R) CPU @ 2.00GHz
GPU: Tesla T4

after I train catboost CV in 1st time everything is okay, but if I try train CV in second time and change "fold_count" I got an error
```
Training on fold [0/10]
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
[<ipython-input-6-75efc1527f1c>](https://localhost:8080/#) in <module>
      9   'early_stopping_rounds':3,
     10 } 
---> 11 cv_data = cv(**cv_params)

[/usr/local/lib/python3.7/dist-packages/catboost/core.py](https://localhost:8080/#) in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, plot_file, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, metric_update_interval, folds, type, return_models, log_cout, log_cerr)
   6649         if not return_models:
   6650             return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
-> 6651                     metric_update_interval, as_pandas, folds, type, return_models)
   6652         else:
   6653             results, cv_models = _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,

_catboost.pyx in _catboost._cv()

_catboost.pyx in _catboost._cv()

CatBoostError: catboost/cuda/methods/boosting_progress_tracker.cpp:171: Saved model's params are different from current model's params

```
![image](https://user-images.githubusercontent.com/44620818/201156712-60c3f458-d232-4bbb-9a88-8cd6053aebd6.png)
![image](https://user-images.githubusercontent.com/44620818/201156950-e26bfccb-e50a-4bc8-b631-2e2e9cc44177.png)

**Comment by Master-sniffer** [comment]
I have the same error even though I don't change folds. This problem seems to happen only with GPU and it is unclear if the bug was fixed

**Comment by andrey-khropov** [comment]
> I have the same error even though I don't change folds. This problem seems to happen only with GPU and it is unclear if the bug was fixed

Yes, it should be fixed even if you don't change folds. The fix will be included in the next release, you can also try to build from source from master and check if it works in your case.
