### ISSUE TITLE
Which CUDA version is compatible with catboost-1.1.1

### ISSUE THREAD

**Issue by skyking363** [catboost/catboost#2238]
CatBoostError: catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version

catboost version: catboost-1.1.1
Operating System: ubuntu 18.04
GPU: Tesla V100
Driver Version: 418.181.07  
CUDA Version: 10.1

GPU doesn't work after I updated the catboost , so can anyone tell me which cuda shoud I install ?
How do I configure my system to use the gpu?

**Comment by mirekphd** [comment]
As [docs](https://catboost.ai/en/docs/installation/cli-installation-binaries) say, CatBoost should work fine with CUDA 11.0 and later versions. Yours is 10.1, so too low.
