### ISSUE TITLE
Q. Custom metrics which based not only on preds and target

### ISSUE THREAD

**Issue by JustM57** [catboost/catboost#224]
Is possible to implement? Not for trees splitting, but for visualization. The metric I want to calculate is PNL. The easiest implemetation is a cumsum product of CI by signal. Signal is our target and CI is one of the features(need to be shifted in order to calculate PNL).
So PNL depends on set is calculated on. At the moment we use trick with shrinking by 1 tree each time and then plotly.
If it's possible, the next step is calculating PNL for SMA signal(simply moving average). I guess there isn't big difference, as we have the whole approxes list.

**Comment by JustM57** [comment]
![2018-01-16 16-39-38](https://user-images.githubusercontent.com/16518742/34992006-b411bd5c-fadc-11e7-8a8f-bf3b67d9213f.png)

**Comment by annaveronika** [comment]
The issue has been here for a while. We don't plan to implement this, so I'm closing as won't fix. Sorry if it dissapoints you, I hope you'll be able to implement this for your tasks if it will be needed.
