### ISSUE TITLE
Model predictions of type str when training labels are boolean

### ISSUE THREAD

**Issue by mkleinbort-ic** [catboost/catboost#2243]
Problem:

When I fit a `CatBoostClassifier` on a boolean target (using a pd.Series with True/False entries), the resulting model returns the strings `'True'`/`'False'` as the predicted labels - not `True`/`False`

Is there a reason for this? It introduces some annoying glue-code into my applications.

catboost version: 1.1.1

Operating System: Windows/Mac

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
duplicate of https://github.com/catboost/catboost/issues/1954
