### ISSUE TITLE
Catboost crashes when attempting to train a multilabel classifier with embedding features

### ISSUE THREAD

**Issue by mgh1** [catboost/catboost#2249]
Problem: Cannot use `embedding_features` with `CatBoostClassifier` when the loss_function is `MultiLogLoss`. This crashes when attempting to fit a model for a multilabel classification task. 

Example code to reproduce:

```
import pandas as pd
import catboost

features_df = pd.DataFrame({
    'f0': [0, 1, 2],
    'embedding1': [[0.0, 1.1, 0.0], [1.0, 2.1, 0.0], [0.11, 0.2, 0.3]]
})
label = [[0, 0], [0, 1], [1, 0]]

pool = catboost.Pool(features_df, label=label, embedding_features=['embedding1'])

model = catboost.CatBoostClassifier(iterations=10, loss_function='MultiLogloss')
model.fit(pool)

```

Catboost will throw an exception with this error message:

```
CatBoostError: catboost/libs/data/target.h:315: Attempt to use multi-dimensional target as one-dimensional
```

catboost version: 1.1.1
Operating System: Linux
CPU: Yes
GPU: Yes

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@mgh1 
we are glad to know you are trying catboost!

unfortunately, because of current implementation, multi-label classification does not work with texts and embeddings -- @andrey-khropov may provide more details

**Comment by adkinsty** [comment]
Why not simply turn the single feature 'embedding1' into three features?

**Comment by PhenomenaPh** [comment]
What is the current status of catboost's ability to perform multi-label classification?

**Comment by andrey-khropov** [comment]
> What is the current status of catboost's ability to perform multi-label text classification?

You can definitely use text features (see #1885, released in CatBoost 1.2) but there might be some issues with embedding features. I'll investigate.

**Comment by andrey-khropov** [comment]
> there might be some issues with embedding features.

In CatBoost 1.2 it works on CPU but fails with an error on GPU. We'll fix the GPU case.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
This error is occurs, if embedding encoders produces a binary feature

**Comment by dudelstein** [comment]
Hi, I'm still having this issue when training on Sagemaker with catboost version 1.2.7 on GPU with numerical embedding features. I made sure the embedding features are the last in my dataframe. Has anyone experienced this? 

Specifically: `_catboost.CatBoostError: catboost/private/libs/feature_estimator/feature_estimator.h:35: Attempt to call single feature writer on packed feature writer`
