### ISSUE TITLE
 marginal distribution of classes

### ISSUE THREAD

**Issue by nansy99** [catboost/catboost#2254]
Does a multiclass classifier have the feature to maintain the marginal distribution of classes?
(Python CatBoost 1.1.1)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @nansy99 !
thank you very much for trying catboost 😻 
if the training dataset contains only a small number of examples of some class, you may use class_weights or auto_class_weights
https://catboost.ai/en/docs/references/training-parameters/common#class_weights
https://catboost.ai/en/docs/references/training-parameters/common#auto_class_weights

[if i get your question right]

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Should you have questions, please do not hesitate to reopen
