### ISSUE TITLE
loading a 'cbm' model : Failed to read required number of bytes from stream

### ISSUE THREAD

**Issue by kezorhal** [catboost/catboost#2262]
Problem: I'm trying to test different, categorical features, learning rates and depths on a model. Models are saved in cbm format. When the model exceeds a certain size, I can't load it. `CatBoostRegressor().load_model("model.cbm")`
Before submitting this issue, I checked previous issues and didn't find a solution (https://github.com/catboost/catboost/issues/1908 and https://github.com/catboost/catboost/issues/1041)

An example of model that can't be loaded:
number of categorical features: 4
number of numerical features: 17
learning rate : 0.3
depth : 14
file *.cbm size : 174,3 Mo
train file size : 388.4 Mo
traine file shape: (2310116, 30)
train time : 80 min
"error message" : _" CatBoostError: util/stream/input.cpp:77: Failed to read required number of bytes from stream! Expected: 7994284, gained: 3891839!"_

VM GCP : n1-highmem-4 (4 vCPUs, 26 GB RAM)
catboost version: '1.0.6'
Operating System:  Debian 10 RAM: 26 Go
CPU: CPU platform: Intel Haswell
GPU:_

Thank you for your help

**Comment by andrey-khropov** [comment]
I cannot reproduce this error, so more detailed context is needed. Does this error occur if you run the code on real hardware, not in GCP VM?

I tried the following code on Ubuntu 20.04 (no Debian at hand) with Python 3.7.17 and CatBoost 1.0.6 and it worked without errors:

```py
import numpy as np
import pandas as pd

import catboost as cb

print (f'cb.version={cb.version.VERSION}')

n_samples = 2310116
n_features = 30
x_train_dict = {}

for i in range(n_features):
    x_train_dict[str(i)] = np.random.randint(100, size=n_samples)

x_train = pd.DataFrame(x_train_dict)
y_train = np.random.random_sample(n_samples)

model = cb.CatBoostRegressor(
    learning_rate=0.3,
    depth=14
)

model.fit(x_train, y_train, cat_features=[0,1,2,3])
model.save_model('model.cbm')

cb.CatBoostRegressor().load_model("model.cbm")
```

Model file size is abut 326Mb.

**Comment by kezorhal** [comment]
Hi 
I submitted this issue one year ago, as I can remember, the problem was the model wasn't correctly downloaded or saved.
I think it was not due to Catboost.
