### ISSUE TITLE
MultiRMSE: Catboost does not support multitarget on GPU yet

### ISSUE THREAD

**Issue by j29scott** [catboost/catboost#2264]
Problem: MultiRMSE doesn't work on GPUs yet
catboost version: 1.1.1
Operating System: 20.20 LTS
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
GPU: A100

This seems very useful for me. Is there any plan to get it included?

**Comment by ek-ak** [comment]
Hello! We plan to support MultiRMSE on GPU, but we have no time frame yet.

**Comment by fingoldo** [comment]
Upvoting as well.

**Comment by langkkl** [comment]
Hello everybody. I have a similar problem，I'd like to write a cuda supported loss function with c++，but I don't know how to start,Could anyone give we some suggests?

**Comment by j29scott** [comment]
Could anyone help point us to what would need to be done to get support for this very useful feature?

**Comment by andrey-khropov** [comment]
Implemented in https://github.com/catboost/catboost/commit/91a2eb0b5b3dac81ad2f03d961b784d472055bcf
