### ISSUE TITLE
GPU out of memory

### ISSUE THREAD

**Issue by TDL77** [catboost/catboost#2265]
Problem: При запуске на GPU выдает вот такую ошибку ( скрипт с сайта)
catboost version: 1.1.1
Operating System:  Windows 10 Home x64 (2009 build 19045)
CPU: 12th Gen Intel(R) Core(TM) i7-12700H
GPU: NVIDIA GeForce RTX 3070 Ti Laptop GPU, 4 GB
Intel(R) Iris(R) Xe Graphics, 1 GB

При запуске на GPU , выдает ошибку -- cuda out of memory 
На CPU все норм
После поставил новые дрова на видеокарту + CUDA 11.7 + cuDNN , но результат тот же

![2023-01-13_170844](https://user-images.githubusercontent.com/69913933/212523120-9aaeaf50-79df-4e38-90c0-17335514f166.png)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
спасибо, что пропробовал катбуст ❤️ 
что выдает nvidia-smi?

**Comment by TDL77** [comment]
![image](https://user-images.githubusercontent.com/69913933/212528800-6ef91d4d-c55b-40a4-b454-29d5946ef03a.png)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
пример с первого скриншота отрабатывает на меньшей карте и использует < 100Мб памяти на гпу
поэтому пока ситуация выглядит, как какие-то проблемы с окружением на твоей стороне

1. всё ли ок с версией cuda? по твоим словам -- 11.7, но на втором скриншоте -- 12.0
2. точно рядом с катбустом нет тензор флоу и т.п. питон-модулей, которые забирают себе всю гпу память?

я бы покопал в какую-то такую сторону

**Comment by TDL77** [comment]
снес все окружения , удалил CUDA и пр ..заново поставил дрова nvidia(она сама ставит CUDA12) ,
поставил конду и сделал окружение ,в него через конду поставил catboost ,
результат тот же , таже ошибка
Подскажи где еще копать ? как проверить из за чего это ошибка ?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
интересно! мы не тестируем с cuda 12, но вряд ли в ней дело
перепроверил, что на карте как ниже твой пример работает для catboost 1.1.1 на python 3.9 + cmd.exe и python 3.9 + powershell
![image](https://user-images.githubusercontent.com/7053671/212554775-2644a6ff-f812-4c70-b740-271aac51ab55.png)
видимо, что-то ограничивает размер памяти гпу, доступной катбусту
я бы попробовал запустить на карте какой-нибудь простой код с аллокацией 90% памяти

**Comment by TDL77** [comment]
спасибо все настроил ..запустил на GPU

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
> спасибо все настроил ..запустил на GPU

а что было? чтобы осталось для тех, кто придут после нас?
