### ISSUE TITLE
Predicting multiple times on a GPU will not get the same results

### ISSUE THREAD

**Issue by 814850963** [catboost/catboost#2268]
Problem: When I use GPU mode to predict data. Every time I get different result. I think the data should be the same because I use the same model to predict the same data. Is It a bug or something I forgot?

Code:

```python
X = pd.DataFrame(columns=X.columns, data=pipeline.fit_transform(X))
model = CatBoostClassifier()
# load model
model.load_model(modelPath) 
# validation prediction
pred_valid = model.predict_proba(X, task_type='GPU')[:,1]
```

catboost version: 1.1.1
Operating System: Linux Ubuntu20 LTS
# GPU:NVIDIA Tesla M60

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @814850963 🤝 
this might be a known bug in catboost 😞 
could you please check whether predictions are reproducible with thread_count=1?
thank you very much experimenting with catboost 😻

**Comment by 814850963** [comment]
@Evgueni-Petrov-aka-espetrov   Thank you for your reply. 
I try to use thread_count=1 for the prediction.

I made two predictions for the same dataset(1000 rows data). 
Comparing the two predictions, I found the same results, but there were still different results.
The result is much better than before, thank you.

Code:
```
model = CatBoostClassifier()
model.set_params(thread_count=1)
# load model
model.load_model(modelPath) 
# validation prediction
t1 = time.time()
pred_valid = model.predict_proba(X,task_type='GPU')[:,1]
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@814850963 
`set_params` sets parameters for `fit`, while the thread safety bug is in `predict_proba`
could you please call `predict_proba` as follows
```python
pred_valid = model.predict_proba(X,task_type='GPU', thread_count=1)[:,1]
```
please excuse me for omitting this point

**Comment by 814850963** [comment]
@Evgueni-Petrov-aka-espetrov 
This method successfully solved my problem. Thank you!
