### ISSUE TITLE
if the Model is higher then 2gb getting flat buffer verification failed error

### ISSUE THREAD

**Issue by vigneshgig** [catboost/catboost#2274]
Problem: unable to load the model, if the saved model size is greater than 2 GB , getting CatBoostError: catboost/libs/model/model.cpp:1176: Flatbuffers model verification failed.
how to load bigger model. 
I have trained the model with both symmetric and depthwise grow policy for 10 depth.
catboost version:1.1.1
Operating System: linux
CPU:Intel(R) Xeon(R) CPU @ 2.20GHz
GPU:A100-SXM4-40GB
@AlekSi @avm @mfcabrera @sandello 
Thanks

**Comment by kizill** [comment]
Hello! How many trees do you have in your model?

**Comment by kizill** [comment]
We use FlatBuffers representation for diffrenet parts of CatBoost model. In your case leaf values consume:
8 (bytes per single leaf, we store them as `double` ) *
2 ^ 10 (number of leafs in full binary tree of depth 10)
* 100000 number of trees
* Number of classes (I guess in your case there is >3 classes)

To solve your problem i'd recommend to reduce depth or use `Lossguide` tree shape with `max_leaves` set to, for example, 32 or 64
Also I'd recommend to use [overfitting detector](https://catboost.ai/en/docs/en/features/overfitting-detector-desc), to automatically stop training as your model converges.

Closing as that's not a problem we are planning to solve technically. Feel free to reopen this issue and ask you questions here. And also you can join our [Telegram chat](https://t.me/catboost_en) to ask your questions and get answers faster.
