### ISSUE TITLE
multiclass on gpu

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#228]
Add Multiclass mode to GPU training

**Comment by mikeun** [comment]
task_type = 'GPU'
ubuntu linux system

_catboost.CatboostError: catboost/libs/train_lib/train_model.cpp:738: GPU Device not found.

**Comment by annaveronika** [comment]
@mikeun Is this about multiclass?

**Comment by NikitaChurkin** [comment]
I receive the same error using Windows 10 ('loss_function': 'RMSE') when I set task_type = 'GPU': CatboostError: /catboost/libs/train_lib/train_model.cpp:738: GPU Device not found.

**Comment by mikeun** [comment]
@annaveronika This is a multiclass classification. I tried it with GPU and get error.

   def get_model(self):
        self.model = CatBoostClassifier()
        self.model.set_params(
            loss_function = 'MultiClass',
            eval_metric = 'Accuracy',
            iterations = self.conf.iterations,
            learning_rate = self.conf.learning_rate,
            depth=self.conf.depth,
            one_hot_max_size = self.conf.one_hot_max_size,
            # calc_feature_importance = self.conf.feature_importance,
            classes_count = self.conf.hm_labels,
            thread_count = self.conf.thread_count,
            # use_cpu_ram_for_cat_features = self.conf.use_cpu_ram_for_cat_features,
            name = self.conf.name,
            logging_level = self.conf.logging_level,
            train_dir = self.conf.folders['train'],
            snapshot_file = self.conf.snapshot_file,
            save_snapshot = self.conf.save_snapshot,
            task_type = self.conf.task_type,
            # device_config = '0'
            # ctr = None
        )

**Comment by annaveronika** [comment]
ok, let's discuss this problems in https://github.com/catboost/catboost/issues/230
This issue is about adding Multiclass mode to GPU training

**Comment by annaveronika** [comment]
@mikeun multiclass is not yet supported on GPU, so it will not work after fixing #230

**Comment by annaveronika** [comment]
this is done now! The latest version can be built from source.
