### ISSUE TITLE
File hashes are encoded incorrectly in the wheels' RECORD files

### ISSUE THREAD

**Issue by SpecLad** [catboost/catboost#2282]
Problem:

If you open any catboost wheel and look at the `catboost-*.dist-info/RECORD` file, you'll see entries like this:

```
catboost-1.1.1.data/data/etc/jupyter/nbconfig/notebook.d/catboost-widget.json,sha256=qpzzsOW31KT955agi-7NS--90I0iNiJCyLJQnRCHgKI=,69
catboost-1.1.1.data/data/share/jupyter/labextensions/catboost-widget/package.json,sha256=NpXd6mCWbOopORtPxUZ-MuE4ZYh9bgnWWiKqWKU8Tso=,1112
catboost-1.1.1.data/data/share/jupyter/labextensions/catboost-widget/static/remoteEntry.64b1a05fa8a34d8acb22.js,sha256=17wvZmxJBz_MLRm4uQvqPrhHc0kNkogx6eOsnDZZ-K0=,7171
...
```

Note the `=` at the end of each hash digest. That's not supposed to be there, per the [specification](https://packaging.python.org/en/latest/specifications/recording-installed-packages/#the-record-file):

> The hash is either an empty string or the name of a hash algorithm from `hashlib.algorithms_guaranteed`, followed by the equals character `=` and the digest of the file’s contents, encoded with the urlsafe-base64-nopad encoding (`base64.urlsafe_b64encode(digest)` **with trailing = removed**).

This is currently harmless, but I'm working on tightening up wheel validation in pip, so pip users might start seeing warnings when installing catboost.

I believe the incorrect encoding comes from here: https://github.com/catboost/catboost/blob/1bbd895eb751c41f253c5382d5f3040d86ff4ecd/catboost/python-package/mk_wheel.py#L237.

catboost version: 1.1.1
Operating System: Any
CPU: Any
GPU: Any

**Comment by kizill** [comment]
Hello! This will be fixed in #2278. Closing as partial duplicate.
