### ISSUE TITLE
[Visual Studio 2019] Not finding compilers?

### ISSUE THREAD

**Issue by yrzhanov** [catboost/catboost#2284]
Problem:
catboost version: 1.1.1
Operating System: Windows 10
CPU: Intel Core i9-10900X CPU @ 3.70GHz (20 CPUs)
GPU: NVIDIA GeForce GTX 970

F:\D\VariousCodes\CatBoost\catboost\app>..\..\ya make -r catboost\libs\model_interface\static
Config was not generated due to errors in F:\D\VariousCodes\CatBoost\build\ymake_conf.py
Traceback (most recent call last):
  File "F:\D\VariousCodes\CatBoost\build\ymake_conf.py", line 2562, in <module>
    main()
  File "F:\D\VariousCodes\CatBoost\build\ymake_conf.py", line 2555, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "F:\D\VariousCodes\CatBoost\build\ymake_conf.py", line 485, in __init__
    self.tc = self._get_toolchain_options()
  File "F:\D\VariousCodes\CatBoost\build\ymake_conf.py", line 645, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "F:\D\VariousCodes\CatBoost\build\ymake_conf.py", line 904, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe

Could you please advise how to set C and C++ compilers so that ya can detect them?
Thanks

**Comment by andrey-khropov** [comment]
Sorry for the delayed response.

Most likely you have to setup Visual Studio toolchain like that:

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.28
```

We'll update the docs about that.

Also, since https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb only CMake-based build is supported, but it has some issues on Windows - https://github.com/catboost/catboost/issues/2287#issuecomment-1429999257

**Comment by yrzhanov** [comment]
Thank you - I rerun setup (my version is 14.29.X), but it didn't help much. The response was:

F:\D\VariousCodes\CatBoost\catboost\app>..\..\ya make -r F:\D\VariousCodes\CatBoost\catboost\libs\model_interface\static
Warn: Persistent storage for results is not specified. Remove --no-src-links option (*nix systems) and/or use -o/--output option, see details in help.
Warn: Symlinks for the outputs are disabled on Windows. Use -o/--output option to explicitly specify the directory for the outputs
------- [CC] {FAILED} $(S)/library/cpp/logger/stream_creator.cpp
command C:\Users\yuri\.ya\tools\v3\2989597467/python F:/D/VariousCodes/CatBoost/build/scripts/fix_msvc_output.py cl C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /c /FoC:/Users/yuri/.ya/build/build_root/ns93/00000b/library/cpp/logger/stream_creator.cpp.obj F:/D/VariousCodes/CatBoost/library/cpp/logger/stream_creator.cpp /I C:/Users/yuri/.ya/build/build_root/ns93/00000b /I F:/D/VariousCodes/CatBoost /I F:/D/VariousCodes/CatBoost/contrib/libs/cxxsupp/libcxx/include /I F:/D/VariousCodes/CatBoost/contrib/libs/zlib/include /I F:/D/VariousCodes/CatBoost/contrib/libs/double-conversion /I F:/D/VariousCodes/CatBoost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /permissive- /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt /I C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include /Ox /Ob2 /Oi /DNDEBUG /MT /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4005 /wd4117 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DARCADIA_ROOT=F:/D/VariousCodes/CatBoost /DARCADIA_BUILD_ROOT=C:/Users/yuri/.ya/build/build_root/ns93/00000b /DFAKEID=10157985 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -DCATBOOST_OPENSOURCE=yes -DCATBOOST_OPENSOURCE=yes -DUSE_STL_SYSTEM /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++latest /Zc:__cplusplus /D_CRT_USE_BUILTIN_OFFSETOF -DCATBOOST_OPENSOURCE=yes -DCATBOOST_OPENSOURCE=yes failed with exit code 2 in C:\Users\yuri\.ya\build\build_root\ns93\00000b
F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2039: 'variant': is not a member of 'std'

F:\D\VariousCodes\CatBoost\contrib\libs\cxxsupp\libcxx\include\__numeric\transform_reduce.h(21): note: see declaration of 'std'

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2974: 'TSerializer': invalid template argument for 'T', type expected

F:\D\VariousCodes\CatBoost\util\ysaveload.h(235): note: see declaration of 'TSerializer'

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2988: unrecognizable template declaration/definition

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2143: syntax error: missing ';' before '>'

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C3855: 'TSerializer': template parameter 'T' is incompatible with the declaration

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2059: syntax error: '>'

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2143: syntax error: missing ';' before '{'

F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2447: '{': missing function header (old-style formal list?)
.....................................................................................
C++17 support is installed, but I have to set it manually in each project: from Legacy MSVC to ISO C17 (2018) Standard (/std:c17)
Apparently the script does not recognize C++17

Thanks,
    Yuri

**Comment by andrey-khropov** [comment]
> Thank you - I rerun setup (my version is 14.29.X), but it didn't help much. The response was:
> 
> F:\D\VariousCodes\CatBoost\catboost\app>....\ya make -r F:\D\VariousCodes\CatBoost\catboost\libs\model_interface\static Warn: Persistent storage for results is not specified. Remove --no-src-links option (*nix systems) and/or use -o/--output option, see details in help. Warn: Symlinks for the outputs are disabled on Windows. Use -o/--output option to explicitly specify the directory for the outputs ------- [CC] {FAILED} $(S)/library/cpp/logger/stream_creator.cpp command C:\Users\yuri.ya\tools\v3\2989597467/python F:/D/VariousCodes/CatBoost/build/scripts/fix_msvc_output.py cl C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /c /FoC:/Users/yuri/.ya/build/build_root/ns93/00000b/library/cpp/logger/stream_creator.cpp.obj F:/D/VariousCodes/CatBoost/library/cpp/logger/stream_creator.cpp /I C:/Users/yuri/.ya/build/build_root/ns93/00000b /I F:/D/VariousCodes/CatBoost /I F:/D/VariousCodes/CatBoost/contrib/libs/cxxsupp/libcxx/include /I F:/D/VariousCodes/CatBoost/contrib/libs/zlib/include /I F:/D/VariousCodes/CatBoost/contrib/libs/double-conversion /I F:/D/VariousCodes/CatBoost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /permissive- /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt /I C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include /Ox /Ob2 /Oi /DNDEBUG /MT /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4005 /wd4117 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DARCADIA_ROOT=F:/D/VariousCodes/CatBoost /DARCADIA_BUILD_ROOT=C:/Users/yuri/.ya/build/build_root/ns93/00000b /DFAKEID=10157985 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -DCATBOOST_OPENSOURCE=yes -DCATBOOST_OPENSOURCE=yes -DUSE_STL_SYSTEM /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++latest /Zc:__cplusplus /D_CRT_USE_BUILTIN_OFFSETOF -DCATBOOST_OPENSOURCE=yes -DCATBOOST_OPENSOURCE=yes failed with exit code 2 in C:\Users\yuri.ya\build\build_root\ns93\00000b F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2039: 'variant': is not a member of 'std'
> 
> F:\D\VariousCodes\CatBoost\contrib\libs\cxxsupp\libcxx\include__numeric\transform_reduce.h(21): note: see declaration of 'std'
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2974: 'TSerializer': invalid template argument for 'T', type expected
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(235): note: see declaration of 'TSerializer'
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2988: unrecognizable template declaration/definition
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2143: syntax error: missing ';' before '>'
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C3855: 'TSerializer': template parameter 'T' is incompatible with the declaration
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2059: syntax error: '>'
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2143: syntax error: missing ';' before '{'
> 
> F:\D\VariousCodes\CatBoost\util\ysaveload.h(654): error C2447: '{': missing function header (old-style formal list?) ..................................................................................... C++17 support is installed, but I have to set it manually in each project: from Legacy MSVC to ISO C17 (2018) Standard (/std:c17) Apparently the script does not recognize C++17
> 
> Thanks, Yuri

> Apparently the script does not recognize C++17

There're some issues with flags in the STL version used by CatBoost but even if they're fixed there will be some other errors due to Microsoft compiler bugs.

Please use the toolkit from 14.28.X series. It can be installed even if you have a different version by default.

**Comment by yrzhanov** [comment]
Thank you - I installed 14.28 in addition to default 14.29. Same building error. Do I need some flag that would select 14.28 and C++17?

**Comment by andrey-khropov** [comment]
> Thank you - I installed 14.28 in addition to default 14.29. Same building error. Do I need some flag that would select 14.28 and C++17?

Did you set up the proper toolkit version like that

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.28
```

before calling ya make?

**Comment by yrzhanov** [comment]
No, I didn’t think about it. However, this doesn’t run, surprisingly (as it did run with 14.29):

 

F:\D\VariousCodes\CatBoost\catboost\app>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.28

**********************************************************************

** Visual Studio 2019 Developer Command Prompt v16.11.24

** Copyright (c) 2021 Microsoft Corporation

**********************************************************************

The input line is too long.

The syntax of the command is incorrect.

 

The toolkit I installed is 14.28.29910

 

Thanks,

    Yuri

**Comment by yrzhanov** [comment]
Apparently setting 14.28 needs to be done from C:, not from any other disk… From C: “call” works.

 

However, the problem persists - 'variant': is not a member of 'std'

Hence, C++17 is still not being picked up.

 

Do you have any other ideas?

 

Thanks,

    Yuri

**Comment by andrey-khropov** [comment]
We've fixed many issues with the CMake build, especially on Windows and created a new [build_native.py tool](https://github.com/catboost/catboost/blob/master/build/build_native.py) to build using CMake.

See [the updated documentation](https://catboost.ai/en/docs/concepts/build-from-source).
[Documentation about the static C/C++ evaluation library](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper) has been significantly extended as well.

Building CatBoost C/C++ evaluation library with Ya Make had not been supported on Windows, but it is possible with the new CMake-based build system now.

> The input line is too long.

It's a well-known issue if vcvars.but is called repeatedly, see https://developercommunity.visualstudio.com/t/vcvarsallbat-reports-the-input-line-is-too-long-if/257260 for example. Basically, vcvars adds values to some environment variables like `Path` and can hit their length limits if run repeatedly.
