### ISSUE TITLE
Error Trying to Build

### ISSUE THREAD

**Issue by cconw** [catboost/catboost#2287]
Problem: Error building (make)
catboost version: whatever is on github (git clone)  1.1.1.1
Operating System: Windows 11
CPU: AMD 5600X
GPU: 3060

- Windows 11, Cuda (GPU Nvidia 3060), Visual Studio 2022.
- Is catboost not compatible with Visual Studio 2022 ? I know 2019 is recommended... any ideas? Thx  
- 
- Command line used:  ya make -r -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin
- note:  sdk is installed for VS 2022 

C:\Users\cc\catboost>ya make -r -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin
Config was not generated due to errors in C:\Users\cc\catboost\build\ymake_conf.py
Traceback (most recent call last):
File "C:\Users\cc\catboost\build\ymake_conf.py", line 2560, in
main()
File "C:\Users\cc\catboost\build\ymake_conf.py", line 2553, in main
build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
File "C:\Users\cc\catboost\build\ymake_conf.py", line 485, in init
self.tc = self._get_toolchain_options()
File "C:\Users\cc\catboost\build\ymake_conf.py", line 651, in _get_toolchain_options
return MSVCToolchainOptions(self, detector)
File "C:\Users\cc\catboost\build\ymake_conf.py", line 1783, in init
self.sdk_version = os.environ.get('WindowsSDKVersion').replace('\', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by cconw** [comment]
- **CLI w/ cmake** 

C:\Users\cc\catboost\catboost>cmake ./ -DCMAKE_BUILD_TYPE=Release -DPython3_ROOT_DIR=c:\users\cc\appdata\local\programs\
python\python310\
-- Building for: Visual Studio 17 2022
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- The C compiler identification is MSVC 19.34.31937.0
-- The CXX compiler identification is MSVC 19.34.31937.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: C:/Users/cc/AppData/Local/Programs/Python/Python310/python.exe (found version "3.10.9") found components: Interpreter
-- The CUDA compiler identification is NVIDIA 12.0.76
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/include (found version "12.0.76")
CMake Error at cmake/cuda.cmake:72 (message):
  clang++ not found
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)


CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)

      Reason given by package:
          Interpreter: Wrong major version for the interpreter "C:/Users/cc/AppData/Local/Programs/Python/Python310/python.exe"

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPython/Support.cmake:3245 (find_package_handle_standard_args)
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPython2.cmake:427 (include)
  cmake/yandex_common.cmake:3 (find_package)
  CMakeLists.txt:32 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/cc/catboost/catboost/CMakeFiles/CMakeOutput.log".
See also "C:/Users/cc/catboost/catboost/CMakeFiles/CMakeError.log".

**Comment by andrey-khropov** [comment]
1) Unfortunately installed Python2 is still required (I know it has been deprecated for a long time but it is still used in some auxiliary pockets of code. We are working on fixing this - #2297). I'll update the docs to reflect this.

2) There're some other issues with Windows builds with CMake + Visual Studio. I'm in the process of fixing them. If you cannot wait to be able to build CatBoost with some custom changes please rollback to some revision before c5c642ca0b8e093336d0229ac4b14c78db3915bb and apply your changes and build using ya.make (https://catboost.ai/en/docs/installation/cli-installation-local-copy-installation).

I'll write updates here when the current situation is resolved in the following days. Sorry for the inconvinience.

**Comment by cconw** [comment]
I will wait.  Thank you for your work and contribution.

**Comment by andrey-khropov** [comment]
> * Is catboost not compatible with Visual Studio 2022 ?

I've investigated the issue and unfortunately CatBoost won't build with Visual Studio 2022 due to Internal Compiler Errors.

I've created a specific issue for that: #2302.

**Comment by andrey-khropov** [comment]
I'm closing this issue in favor of #2302.
