### ISSUE TITLE
did this repo has yandex build system 

### ISSUE THREAD

**Issue by FashGek** [catboost/catboost#2288]
Problem:  how compile project with the ya.make
catboost version:
Operating System:
CPU:
GPU:

**Comment by andrey-khropov** [comment]
Yes, but we are in the process of switching fully to CMake-based builds.

Instructions on how to build from source are available in the documentation: https://catboost.ai/en/docs/concepts/installation, see 'build from source' sections.
All projects can be built with ya.make, some projects can be built with CMake or make but all projects will be built using CMake in the future releases.

**Comment by cconw** [comment]
> Yes, but we are in the process of switching fully to CMake-based builds.
> 
> Instructions on how to build from source are available in the documentation: https://catboost.ai/en/docs/concepts/installation, see 'build from source' sections. All projects can be built with ya.make, some projects can be built with CMake or make but all projects will be built using CMake in the future releases.

I've tried cmake w/ command prompt (and gui).  Can't get it to work -- keeps looking for python2 interpreter.  I don't quite get it.   Any quick suggestions?  Thanks in advance.

>  Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)

https://github.com/catboost/catboost/issues/2287

**Comment by andrey-khropov** [comment]
I'll wrote about the current situation [here](https://github.com/catboost/catboost/issues/2287#issuecomment-1429999257)

**Comment by andrey-khropov** [comment]
Documentation about building CatBoost has been updated to reflect the latest changes: https://catboost.ai/en/docs/concepts/build-from-source.

Python 2 dependency has been removed in #2297.
