### ISSUE TITLE
CatBoostRegressor can't training cycle with using GPU

### ISSUE THREAD

**Issue by Coder-Loser** [catboost/catboost#2292]
Problem:_catboost.CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/cuda/train_lib/train.cpp:351: Training continuation for GPU is not yet supported
catboost version:1.0.6
Operating System:Windows 10
CPU: Intel i5-9300H
GPU:GTX 1650

**Comment by BrianRostBAH** [comment]
Why was this closed as completed?  You list version 1.0.6 but I am still getting this error with version 1.2.
