### ISSUE TITLE
get_embedding_feature_indices returns empty list

### ISSUE THREAD

**Issue by evansfk** [catboost/catboost#2296]
Problem: Hi, I'm training a catboost classifier with numeric/categorical and embedding features. I pass the embeddings_feature indices in the Pool parameters, but when I call get_embedding_feature_indices() on the trained classifier, it returns the empty list ( [] ). Is it a bug? How can I ensure that the model uses the embedding features (right now I'm assuming it does because it takes much longer to train than without them). This happens both when training on CPU and GPU. Thanks!

catboost version: 1.1.1
Operating System: Ubuntu 20.04.5 LTS (Focal Fossa)
CPU: Intel(R) Xeon(R) CPU @ 2.00GHz
GPU: Tesla T4

**Comment by andrey-khropov** [comment]
yes, it is a known bug (#2273) which has already been fixed in master branch and will be included in the next release 1.2.
