### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by koonleong** [catboost/catboost#2306]
Problem: Cannot install CatBoostClassifier
catboost version:
Operating System: MacOS 13.2.1
CPU: M2
GPU:

Python version: 3.11.2

pip install catboost

Error message:
ERROR: Could not find a version that satisfies the requirement catboost (from versions: none)
ERROR: No matching distribution found for catboost

**Comment by andrey-khropov** [comment]
It is because python 3.11 is not supported yet (will be in the next release): #2213
