### ISSUE TITLE
CatBoost crashes Python when attempting to train on GPU

### ISSUE THREAD

**Issue by xaviernogueira** [catboost/catboost#2334]
Problem: When I try and train a model using the Python API setting `task_type='GPU'` I wittiness the "dedicated GPU memory" utilization shoot up to near 100% and then crashes Python before the training begins. 

I have tested the following and achieved the same result.
* Tiny training data (10 rows, 20 columns).
* Tiny # of iterations (set to 10).
* Use of a `catboost.Pool` vs `X, y` parameters.

The fact that it crashes the same way everytime tells me something else is wrong. Any advice?

catboost version: 1.1.1
Operating System: Windows 10
CPU: Intel(R) Xeon(R) E5-1650
GPU: NVIDIA Quadro K600, Driver Version 474.14, CUDA Version 11.4

**Comment by Karpovich-alex** [comment]
I also have a trouble with running catboost with `task_type="GPU"`
I try to use `CatBoostRegressor(task_type="GPU", devices="0:1", loss_function='MAE', ...)`, but It crashes the Jupyter kernel/
Unexpectedly, it works well with other loss_functions (like MAPE).

catboost version: 1.1.1
Operating System: Windows 10

**Comment by xaviernogueira** [comment]
@Karpovich-alex glad to hear I'm not the only one. Really would like to use MAE so that is a tad annoying. Hopefully we can get some guidance or dev attention.

**Comment by fkjslee** [comment]
My program is also crashed when I set task_type="GPU"

I tried "CrossEntropy", "LogLoss"

catboost version: 1.1.1
platform:  Linux Debian 5.4.143.bsk.8

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
> My program is also crashed when I set task_type="GPU"
> 
> I tried "CrossEntropy", "LogLoss"
> 
> catboost version: 1.1.1 platform: Linux Debian 5.4.143.bsk.8

could you please provide a reproducer?

**Comment by fkjslee** [comment]
sure, wait some minutes

**Comment by andrey-khropov** [comment]
> When I run this code, my jupyter will tell me "Kernel Restarting"

@fkjslee 

I cannot repoduce this error, I've tried with Classifier, Regressor, losses like 'Logloss', 'MultiClass', 'MAE' - no crashes.
But I have no immediate access so I've tested on Ubuntu 18.04.

What version of CUDA do you have and what GPU do you try to run on?

**Comment by andrey-khropov** [comment]
> When I run this code, my jupyter will tell me "Kernel Restarting"

Actually I was able to get an error when training on GPUs with less than 16Gb of RAM:

```
(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:303: Error: Out of memory. Requested 16000 MB; Free 11514.41816 MB
```

The issue here is the `depth` parameter. We'll investigate why it's high values lead to such big allocations even with small datasets.
This issue affects `SymmetricTree` and `Depthwise` grow policies. 

So the temporary solution is either get a card with more GPU RAM, decrease tree depth or use `grow_policy` `Lossguide`.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@fkjslee 
the last example in this issue has 250 features which means (250 * 128) possible splits (128 borders per feature by default)
for each split, we store a 65536-bins histogram of derivatives (8 bytes per bin)
in total, this is 250 * 128 * 65536 * 8 ~ 16Gb

**Comment by fkjslee** [comment]
thx for reply.
I'm busy in recent days and didn't notice your reply.

When I run this code again, it stops broken.

However, When I change len(features) from 250 to 500, it broken again.

```
import pandas as pd
from catboost import CatBoostClassifier, CatBoostRegressor
import numpy as np

n, c = 10000, 501

features_and_labels = np.random.randn(n, c)
fea_names = columns=[f"col_{i}" for i in range(c-1)]
df = pd.DataFrame(features_and_labels, columns=fea_names + ["col_500"])
splitor = np.random.rand(len(df)) < 0.7
df = df.fillna(0)
df_train, df_valid = df[splitor], df[~splitor]

clf = CatBoostRegressor(iterations=100,
                        learning_rate=0.1,
                        depth=16,
                        # loss_function='MAPE',
                        random_seed=20221001,
                        bagging_temperature=0.2,
                        metric_period=1,
                        allow_writing_files=False,
                        task_type="GPU"
                        )

clf.fit(df[fea_names], 
        df["col_500"], 
        cat_features=[],
        use_best_model=True,
        verbose=True,
        eval_set=(df_valid[fea_names], df_valid["col_500"]), 
        early_stopping_rounds=20,
        plot=False
       )
```

So, can you try this code again, if still can't repoduce this error. Tell me and I will try to find which line it broken.

**Comment by fkjslee** [comment]
> andrey-khropov

or, is there include any crash log in catboost? the jupyter just suddenly broken and leave little message.

**Comment by fkjslee** [comment]
or, is there include any crash log in catboost? the jupyter just suddenly broken and leave little message. @andrey-khropov

**Comment by andrey-khropov** [comment]
> thx for reply. I'm busy in recent days and didn't notice your reply.
> 
> So, can you try this code again, if still can't repoduce this error. Tell me and I will try to find which line it broken.

We did reproduce this error and found that the most likely cause is that you don't have enough GPU RAM:

https://github.com/catboost/catboost/issues/2334#issuecomment-1517360929
https://github.com/catboost/catboost/issues/2334#issuecomment-1517464039
