### ISSUE TITLE
Support Anaconda

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#234]
Request from our user:
Do you support Anaconda environments? I'm trying to get CatBoost working in PyCharm using an Anaconda environment as Python interpreter, but I continue to get the ModuleNotFoundError: No module named ''catboost'. I'm able to install using pip, but not conda, especially not conda with an -n flag specifying a particular conda environment.﻿

**Comment by annaveronika** [comment]
We are working on it now.

**Comment by annaveronika** [comment]
#184

**Comment by sab** [comment]
PR in conda and related discussion, https://github.com/conda-forge/staged-recipes/pull/5152

**Comment by sab** [comment]
CatBoost is now available on conda-forge.

Installing `catboost` from the `conda-forge` channel can be achieved by adding `conda-forge` to your channels with:

```
conda config --add channels conda-forge
```

Once the `conda-forge` channel has been enabled, `catboost` can be installed with:

```
conda install catboost
```
