### ISSUE TITLE
Is there an armv8 image available for download？

### ISSUE THREAD

**Issue by xiaoxiaojushi-ivan** [catboost/catboost#2340]
Problem:Is there an armv8 image available for download？
catboost version:v1.1.1

**Comment by andrey-khropov** [comment]
What do you mean by 'image' ?

CatBoost has multiple packages for different languages and use cases. There're not prebuilt artifacts for Linux aarch64 as of release 1.1.1 but macOS ones contain universal binaries that can run on both x86_64 and arm64 Mac computers natively.

**Comment by andrey-khropov** [comment]
CatBoost 1.2 with prebuilt artifacts for Linux aarch64 has been released. If this question is about something else then reopen it with a more detailed explanation.
