### ISSUE TITLE
What's the principle of 'yetirank'?I didn't find any information abount how to calculate or any implement of this loss_function

### ISSUE THREAD

**Issue by sysy007uuu** [catboost/catboost#2347]
What's the principle of 'yetirank'?I didn't find any information abount how to calculate or any implement of this loss_function, it just like a black box.
is there any formula to calculate this loss_function？

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @sysy007uuu !
thank you so much for trying catboost 😸 
here is the paper on YetiRank and YetiRankPairwise
https://catboost.ai/en/docs/concepts/educational-materials-papers#winning-the-transfer-learning-track-of-yahoos-learning-to-rank-challenge-with-yetirank
