### ISSUE TITLE
It seems that there is no 'ya' file in the root folder.

### ISSUE THREAD

**Issue by Crispy13** [catboost/catboost#2349]
> https://catboost.ai/en/docs/installation/python-installation-method-build-from-source-linux-macos

I tried to follow the instruction to build catboost for python 3.11.

But the command `../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=<path to the required python-config> [optional parameters]` did not run, because there is no 'ya' file in the root folder.

Did I do something wrong? I executed the command in `catboost/catboost/python-package/catboost` folder.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @Crispy13 !
many thanks for trying catboost!

yep, there is no ya anymore as we are moving to cmake

@andrey-khropov has recently commented on building catboost python package using cmake
https://github.com/catboost/catboost/issues/2242#issuecomment-1490949965

**Comment by andrey-khropov** [comment]
@Crispy13 

Documentation about building CatBoost has been updated to reflect the latest changes:  https://catboost.ai/en/docs/installation/python-installation-method-build-from-source.
