### ISSUE TITLE
May be a bug?

### ISSUE THREAD

**Issue by qiezikuangge** [catboost/catboost#2352]
Problem: The shape of the train_data is (200,4), and the shape of test_data is (200,5),(200,6) and others, the fitted model can predict success 
catboost version: 1.1.1
Operating System: WSL2.0 ubuntu
CPU: i5-9300 H
GPU:None

![image](https://user-images.githubusercontent.com/50002441/232363733-b68042d8-04be-48d7-b007-b16091e166f9.png)

**Comment by andrey-khropov** [comment]
That is normal.

You can provide additional feature columns to the `predict` - they will be simply ignored. It is a useful property if you've trained model on some data but then your ML workflow evolved by adding some new useful features. As long as new features are added at the end old models will still work and produce the same result as before using the subset of features they were trained on.
