### ISSUE TITLE
I want to debug the source code of catboost step by step, can you guide me on the steps to compile the source code of catboost on the windows machine

### ISSUE THREAD

**Issue by Longcuirong** [catboost/catboost#2357]
Problem:I want to debug the source code of catboost step by step, can you guide me on the steps to compile the source code of catboost on the windows machine
catboost version:the latest
Operating System:X64
CPU:
GPU:

**Comment by andrey-khropov** [comment]
We now have a convinient wrapper for CMake + Ninja called [`build_native.py`](https://github.com/catboost/catboost/blob/master/build/build_native.py) which can be called like that:

```
python .\build_native.py --build-root-dir <build_root_dir> --targets <,-separated target_list>
```

List of targets with their meaning can be found [here](https://github.com/catboost/catboost/issues/2091#issuecomment-1486551204).

If you want to build for debugging you should add `--build-type=Debug` option.

`build_native.py` supports `--dry-run` and `--verbose` options so you can just see what commands will be actually executed without actually running them and `--help` will display the detailed help with all the options.

**Comment by Longcuirong** [comment]
when I exec this command " python .\build_native.py --build-root-dir ./   --targets catboost --verbose":
my msvc is 14.28.29 and vs studio is 2019 V16.11.26:
![image](https://user-images.githubusercontent.com/18166739/233942822-3767a9ec-4a01-41a2-80da-85b2b7d9c676.png)
There are still many compilation errors, such as xx redefinition; different storage classes.
![image](https://user-images.githubusercontent.com/18166739/233944081-689a7d6b-fac3-4968-9902-f864fed9dbf9.png)

how should i solve it？Looking forward to your answer

**Comment by Longcuirong** [comment]
![image](https://user-images.githubusercontent.com/18166739/233945237-59158d0a-3213-4c22-8cb6-2908d2e82f92.png)

![image](https://user-images.githubusercontent.com/18166739/233945195-9b8fe745-fab4-4223-bf08-f3dff3635924.png)

**Comment by Longcuirong** [comment]
https://github.com/Longcuirong

**Comment by andrey-khropov** [comment]
> when I exec this `python .\build_native.py --build-root-dir ../ --targets catboost --build-type=Debug`

Have you used the directory pointed to `../` as a build directory for CatBoost build before? If so, please try to build with a clean build directory because CMake might have cached some variables that were misconfigured before.

**Comment by Longcuirong** [comment]
Thank you,When I try it again, that's ok

**Comment by andrey-khropov** [comment]
JFYI: documentation about building with CMake has been updated to reflect the latest changes: https://catboost.ai/en/docs/installation/build-native-artifacts

**Comment by ccylance** [comment]
@Longcuirong Hi, I have also been studying this algorithm recently. Can we add in WeChat?
