### ISSUE TITLE
Different losses

### ISSUE THREAD

**Issue by fses91** [catboost/catboost#236]
I have a problem when I training a CatBoostRegressor.

![t45pm](https://user-images.githubusercontent.com/10779148/35624769-43b93016-0690-11e8-8c97-dfc8d1576831.png)

As you can see in the image above I get a different error-rate during training compared if I calculate the error later again. I am using exactly the same data. I tried the same setup with other models XGB and LGBM, and there was no problem.

Is there anything I have to know about Catboost or are I am doing something wrong? It looks very strange to me.

I am trying to minimize RMSE

**Comment by fses91** [comment]
I found the error, I think there is a bug with version 0.6, I tried it with '0.5.2.1' and it worked as it should, maybe there is a bug in the predict function.

**Comment by annaveronika** [comment]
if you try saving with 0.5.2.1 and loading with 0.6 does the predict function return different results?

**Comment by kizill** [comment]
Reproduced a problem with model evaluation, working on it.

**Comment by kizill** [comment]
@fses91 we released catboost v0.6.1 with hotfixes for model evaluation issues. Could you try upgrade?

**Comment by fses91** [comment]
It works.
Thanks
