### ISSUE TITLE
Build the binary with CMake error

### ISSUE THREAD

**Issue by Longcuirong** [catboost/catboost#2362]
Problem:CMAKE ERROR
catboost version:1.1.1
Operating System: Windows 10
CPU: Yes
GPU: No
Info:
Ｉhave followed the doc. https://catboost.ai/en/docs/installation/cli-installation-cmake-install
vs toolset :14.2
vs studio : 2019
c++ standard: C++17
msvc: 14.28.29910
python3.6
When I exec :　cmake --build catboost　
Then :
Many build error appear,such as :can't find some class or xx is undefined

**Comment by andrey-khropov** [comment]
JFYI: documentation about building with CMake has been updated to reflect the latest changes: https://catboost.ai/en/docs/installation/build-native-artifacts
