### ISSUE TITLE
Unable to install Release catboost-R-Darwin-1.2 

### ISSUE THREAD

**Issue by mfansler** [catboost/catboost#2374]
Problem: Installation fails due to lack of .dylib in the tarball.
catboost version: 1.2
Operating System: macOS 11.7.4
CPU: Intel Core i9 (x86_64)
GPU: N/A

---

## Reproducible Failure

<details>

```r
$ mamba create -yn foo -c conda-forge r-base=4.2 r-remotes
$ mamba run -n foo --live-stream R -e 'remotes::install_url("https://github.com/catboost/catboost/releases/download/v1.2/catboost-R-Darwin-1.2.tgz")' 

R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remotes::install_url("https://github.com/catboost/catboost/releases/download/v1.2/catboost-R-Darwin-1.2.tgz")
Downloading package from url: https://github.com/catboost/catboost/releases/download/v1.2/catboost-R-Darwin-1.2.tgz

Running `R CMD build`...
* checking for file ‘/private/var/folders/w8/nk968ztx0t57drmyw557kl480000gn/T/RtmpcA8rLs/remotesfeb07a7a5562/catboost/DESCRIPTION’ ... OK
* preparing ‘catboost’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘catboost_1.2.tar.gz’
* installing *source* package ‘catboost’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘catboost’ in library.dynam(lib, package, package.lib):
 shared object ‘libcatboostr.dylib’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/mfansler/miniconda3/envs/foo/lib/R/library/catboost’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/w8/nk968ztx0t57drmyw557kl480000gn/T//RtmpcA8rLs/filefeb0757bd3bf/catboost_1.2.tar.gz’ had non-zero exit status
> 
```
</details>

BTW, it would be an improvement to the documentation if `remotes::install_url()` was recommended instead of `devtools::install_url()`.

## Workaround
Moving the `inst/libs/libcatboostr.so` to `inst/libs/libcatboostr.dylib` enables the package to be installed.

**Comment by andrey-khropov** [comment]
Interesting that it is not reproducible if I install R through [rig](https://github.com/r-lib/rig), tried most recent and not so recent R versions on both x86-64 and arm64 macOS. Everything works fine.

**Comment by andrey-khropov** [comment]
Looks like a regression from #1834, #1912.

**Comment by andrey-khropov** [comment]
> I'll try to check if tgz with a symlink libcatboostr.dylib -> libcatboostr.so will work.

Yes, this fixes it. `mamba` commands from the example in this issue now work. I've updated `catboost-R-Darwin-1.2.tgz` and `catboost-R-darwin-universal-1.2.tgz` in release 1.2 assets to include this change.

**Comment by andrey-khropov** [comment]
> it would be an improvement to the documentation if remotes::install_url() was recommended instead of devtools::install_url().

**Comment by mfansler** [comment]
Thanks for addressing this!

RE: `remotes` vs `devtools` - The `devtools::install_*` methods are simply re-exports of methods from `remotes`. The `remotes` package is a thin, dependency-free package, whereas `devtools` has a couple dozen dependencies. So, `remotes::install_url` is a more precise recommendation.

**Comment by mfansler** [comment]
I regard the main issue here as resolved. The `remotes` thing is just a suggestion, but if you want to this open to field that, I'll leave to your discretion.

Again, thanks for the prompt response!

**Comment by andrey-khropov** [comment]
> The `remotes` thing is just a suggestion, but if you want to keep this open to field that, I'll leave to your discretion.

That's a different issue so I created #2394.
