### ISSUE TITLE
Key not found in hashtable

### ISSUE THREAD

**Issue by pankismart** [catboost/catboost#238]
Hi,

While trying to fit data for a classification problem with catboost I am facing the following error:

```
File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 1456, in fit
    self._fit(X, y, cat_features, None, sample_weight, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 654, in _fit
    self._train(X, eval_set, params)
  File "_catboost.pyx", line 1022, in _catboost._CatBoostBase._train
  File "_catboost.pyx", line 809, in _catboost._CatBoost._train
  File "_catboost.pyx", line 816, in _catboost._CatBoost._train
_catboost.CatboostError: util/generic/hash.h:1654: Key not found in hashtable: 2143960668

```
Any suggestions?

**Comment by annaveronika** [comment]
Could you provide the full code that you are running?

**Comment by annaveronika** [comment]
Working on that, thanks for pointing out! For now you could try reading data from file, this should work.

**Comment by kizill** [comment]
I've radically fixed this problems in https://github.com/catboost/catboost/commit/b0d23b208e555c630ddc44fb8fff97f0b32a8efb , we will publish packets asap.

**Comment by kizill** [comment]
v0.6.1.1 release is on pypi and on releases page https://github.com/catboost/catboost/releases/tag/v0.6.1.1 , please try to upgrade.

**Comment by Zelazny7** [comment]
Fix works on my machine (see above). Thanks for the great work.

**Comment by weltherrschaf** [comment]
I'am still getting the same error after updating to v0.6.1.1 running the script Zelazny7 posted when using MRO 3.4.2. Running it under vanilla 3.4.3  it reports a different key:
`Error in catboost.train(train_pool, test_pool, fit_params) : 
  atboost/util/generic/hash.h:1654: Key not found in hashtable: -1291328762`
`

**Comment by kizill** [comment]
@weltherrschaf it's just strange, i roughly removed all the code that could trigger this bug. There is two possible reasons: we've built package from incorrect revison for your platform or you've problems with update installation. Please, provide your platform info and try to reinstall catboost v0.6.1.1 from scratch. Thank you.

**Comment by Zelazny7** [comment]
Confirming the same script also works on OSX

**Comment by weltherrschaf** [comment]
I tried again after cleaning the package from my library. Works! Sorry for the noise and thanks for the quick help.

**Comment by kizill** [comment]
Great, thank you all:) Closing issue.
