### ISSUE TITLE
Is there any version of CatBoost that can be compiled on Linux without errors using CMake?

### ISSUE THREAD

**Issue by pha377** [catboost/catboost#2380]
Dynamic library libcatboostmodel.(so|dll|dylib)
This is the fastest way to evaluate model. Library interface is C API but we provide simple C++ header-only wrapper. but you can easily use it's C API interface from any language you like. The code of library and small CMake usage example can be found in [model_interface]

Yes, the code could be find there but it will not compile at all

"make[2]: *** No rule to make target 'libcatboostmodel.so', needed by 'catboost_demo'.  Stop."

**Comment by andrey-khropov** [comment]
> "make[2]: *** No rule to make target 'libcatboostmodel.so', needed by 'catboost_demo'. Stop."

In the CMake example `libcastboostmodel.so` is used with [`IMPORTED_LOCATION`](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_LOCATION.html). It means that there is no rule to build it inside this CMake project CMake just assumes that this file already exists.

You can download a prebuilt version of the library from the released artfacts (see [the releases page](https://github.com/catboost/catboost/releases) ) (x86_64 and aarch64 architectures are supported) or build it from the source code, see [documentation here](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper#build)

**Comment by andrey-khropov** [comment]
We'll improve the documentation about CMake example project.
