### ISSUE TITLE
build_native.py SyntaxError: invalid syntax (on line 34)

### ISSUE THREAD

**Issue by pha377** [catboost/catboost#2381]
https://github.com/catboost/catboost/blame/d551d9c98f3383329e7748413056c0d9d76eb5dc/build/build_native.py#L34

**Comment by pha377** [comment]
python3 --version
Python 3.9.2

**Comment by andrey-khropov** [comment]
> python3 --version Python 3.9.2

This is really strange then.
Can you describe how to reproduce this with more details:

- OS type and version
- CPU architecture
- How was python installed
- CatBoost source code revision

?

**Comment by pha377** [comment]
python**3** /mnt/c/projects/catboost/build/build_native.py --help

**Comment by pha377** [comment]
Also I had to:

sudo pip3 uninstall conan
...Uninstalling conan-2.0.4

sudo pip3 install conan==1.59.0

**Comment by andrey-khropov** [comment]
> Also I had to:
> 
> sudo pip3 uninstall conan ...Uninstalling conan-2.0.4
> 
> sudo pip3 install conan==1.59.0

Yes, [that's mentioned in documentation that conan 2.x is not supported yet](https://catboost.ai/en/docs/installation/build-environment-setup-for-cmake#conan)
