### ISSUE TITLE
Local development difficulties

### ISSUE THREAD

**Issue by UriyaHarpeness** [catboost/catboost#2391]
Problem: Could not manage to setup a working mac or linux environment for building catboost from source.
catboost version: Branch `master`.
Operating System: MacOS / Linux.
CPU: Yes.
GPU: No.

Is there maybe some sort of `Dockerfile` that is setup for building catboost?
I have tried for quite some time setting up an environment on a local MacOS and on a Linux docker and didn't manage to do so even after a lot of tinkering around...

**Comment by andrey-khropov** [comment]
There's no Dockerfile right now (though we'll probably add something like that in the future - it is a good idea), but all the information about building CatBoost can be found here: https://catboost.ai/en/docs/concepts/build-from-source.

**Comment by UriyaHarpeness** [comment]
I can't seem to be able to reach https://catboost.ai, and I don't seem to be the only one, is this a known issue? And info about cause and resolve time?

And about the build: Do you happen to have a working local environment? Is there a way to share the apt / brew list or whichever steps it took to make?
I'm just not very optimistic about succeeding with the info on the link as it's pretty slim...

**Comment by andrey-khropov** [comment]
> I can't seem to be able to reach https://catboost.ai/, and I don't seem to be the only one, is this a known issue?

No it is not. I'm able to access it and I've checked with known website availability checkers and all of them report that it works for them:

https://downforeveryoneorjustme.com/catboost.ai
https://down.com/
https://isitdownorjust.me/catboost-ai/
https://www.websiteplanet.com/webtools/down-or-not/?dorn=catboost.ai

Can you share more details from where in the world are you trying to reach catboost.ai ?

**Comment by UriyaHarpeness** [comment]
Seems to be working from my phone, so I guess judt ignore my website comment.

Anything in relation to the build and local environment?

**Comment by UriyaHarpeness** [comment]
I didn't manage to make it work on my MacOS, but it did work on Linux with the python `build_native.py` script.
From here I can either close the issue, or use it to make a small `Dockerfile` for a working Linux environment.

What do you think @andrey-khropov?

**Comment by andrey-khropov** [comment]
> I didn't manage to make it work on my MacOS, 

I'm interested to hear what the issues are. 
Were you able to access the documentation on the website?
I am personally able to work on CatBoost on macOS on both x86-64 and arm64 architectures.

> but it did work on Linux with the python `build_native.py` script. From here I can either close the issue, or use it to make a small `Dockerfile` for a working Linux environment.
> 
> What do you think @andrey-khropov?

I think that Dockerfile might be helpful.

**Comment by whelme** [comment]
I also had problems accessing the necessary information, but such problems were only on macOS

**Comment by andrey-khropov** [comment]
We've created docker images with the build environment set up. See [the announcement](https://github.com/catboost/catboost/discussions/2786) .
