### ISSUE TITLE
R build fails on Linux due to 404

### ISSUE THREAD

**Issue by jeroen** [catboost/catboost#2397]
See: https://github.com/r-universe/mlr-org/actions/runs/5111743869

**Comment by andrey-khropov** [comment]
There's a bug with the version field of the artifacts names, it is `v1.2` but should be `1.2`, I'll fix the code in master but will make a copy with `v1.2` in the release artifacts as well.

**Comment by andrey-khropov** [comment]
> temporarily make a copy with v1.2 in the release artifacts as well.

Done. The mentioned pipeline should work now.
