### ISSUE TITLE
Wrong cv param order in python documentation

### ISSUE THREAD

**Issue by ei-grad** [catboost/catboost#240]
Documentation says that the `params` param should be first, but in real the pool param goes first.

![screenshot-2018-2-2 catboost cv yandex technologies](https://user-images.githubusercontent.com/78607/35712959-e4b5f15c-07d5-11e8-9111-753ecfa06c8e.png)

Also, `params` param is doubled in table.

**Comment by annaveronika** [comment]
thanks for pointing out! fix will be in next release of documentation.

**Comment by arka1985** [comment]
Please help to solve the error
![screen shot 2018-02-10 at 8 32 17 pm](https://user-images.githubusercontent.com/33415109/36063358-ceac1b34-0ea1-11e8-8f08-04d79637dead.png)

**Comment by annaveronika** [comment]
Change parameter order - first pool, then params

**Comment by annaveronika** [comment]
this is fixed now https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_cv-docpage/
