### ISSUE TITLE
What hash function does Catboost use?

### ISSUE THREAD

**Issue by benjaminwilson** [catboost/catboost#2400]
I can see, in the JSON export, the CTR values associated to each possible value of a categorical feature.  However, the categorical feature values are hashed.  Is the lookup from feature values to their hashes accessible via the Python API, or present in the JSON export?  Alternatively, can you tell me how the hashes are computed, so that I can build such a lookup?

Thanks for your help!

catboost version: 1.2

**Comment by benjaminwilson** [comment]
From the [C++ code](https://github.com/catboost/catboost/blob/e92d9f391ef6f3217bffdd9c50d19f5436fb41ee/catboost/libs/cat_feature/cat_feature.cpp#L5) it appears that the 32 least significant bits of a CityHash64 are used.  But what is the string that is being hashed, is it just the feature name?

**Comment by andrey-khropov** [comment]
> From the [C++ code](https://github.com/catboost/catboost/blob/e92d9f391ef6f3217bffdd9c50d19f5436fb41ee/catboost/libs/cat_feature/cat_feature.cpp#L5) it appears that the 32 least significant bits of a CityHash64 are used. But what is the string that is being hashed, is it just the feature name?

Categorical feature values are converted to UTF-8 strings representation (even if they were specified using different data type in Python data (e.g. 1 is represented as a string "1")) then these strings are treated as a byte array to compute CityHash64 from.

**Comment by benjaminwilson** [comment]
@andrey-khropov thanks for this - but what is the UTF-8 string that is being hashed?  Is it the feature value?

For context, I am trying to extract the CTR values that Catboost learned during training.  I've been using the JSON export.  I can see the CTR values in `jsonexport['ctr_data'][feature_identifier]['hash_map']`. This is a list that looks like 

```
hash_value, ctr_0, ctr_1, ..., ctr_k, hash_value, ctr_0, ctr_1, ..., ctr_k, hash_value, ... 
```

But what exactly is the hash value the hash of?

Thanks for your help!

**Comment by benjaminwilson** [comment]
I managed to work it out by tracing through the Python export (of a different, symmetric tree based model).  I can map the feature values to the hash values using the code below.  It could be cleaned up, but it does work.

Note: it is crucial thatthe no-longer-current version of Cityhash ([this one](https://github.com/Amper/cityhash/tree/4f02fe0ba78d4a6d1735950a9c25809b11786a56)) is used!

```python
from cityhash import CityHash64

MAX_INT = 0xffffffffffffffff
MAGIC_MULT = 0x4906ba494954cb65

def feature_value_hash(fv):
    """
    For the provided feature value (a string) return its corresponding key to the hash table of CTR values (a string).
    """
    ch = CityHash64(fv.encode('ascii'))
    ch_32_lsb = (np.uint64(ch) & np.uint64(0xffffffff)).astype(np.int32)
    return str((MAGIC_MULT * ((MAGIC_MULT * int(ch_32_lsb)) & MAX_INT)) & MAX_INT)
```

**Comment by kpatucha** [comment]
Combining both solutions gave me correct result (at least in CatBoostClassifier build with version 1.2.3)
```python
from clickhouse_cityhash.cityhash import CityHash64
import numpy as np
MAX_INT = 0xffffffffffffffff
MAGIC_MULT = 0x4906ba494954cb65

def feature_value_hash(fv):
    """
    For the provided feature value (a string) return its corresponding key to the hash table of CTR values (a string).
    """
    ch = CityHash64(fv.encode('ascii'))
    ch_32_lsb = (np.uint64(ch) & np.uint64(0xffffffff)).astype(np.int32)
    return str((MAGIC_MULT * ((MAGIC_MULT * int(ch_32_lsb)) & MAX_INT)) & MAX_INT)
```
