### ISSUE TITLE
Catboost Multiclass Classifier - Raw formula val

### ISSUE THREAD

**Issue by aashish-28** [catboost/catboost#2403]
![catboost_return](https://github.com/catboost/catboost/assets/88103804/0bacde80-8999-464d-9b5d-33ba2da2db44)
Problem:
After building a catboost multiclass model, one can use predict proba to find the probability (between zero and one) for each class for each object. (number of object X number of classes)

What is the rawformulaval? 

It returns a one dimensional array, length of number of objects. How does one convert between this and the probability?

**Comment by ek-ak** [comment]
Hello! Thank you for your question.
Probability = SoftMax(rawformulaval)

```
def soft_max(values):
    return [math.exp(val) / sum([math.exp(val) for val in values]) for val in values]
    
raw = model.predict(obj, 'RawFormulaVal')[0]
print(soft_max(raw))
print(model.predict(obj, 'Probability')[0])    
```
