### ISSUE TITLE
CatBoostError('(The process cannot access the file because it is being used by another process.)

### ISSUE THREAD

**Issue by tompellegrini** [catboost/catboost#2404]
Problem:

I'm using Optuna to tune a Catboost model and the error below keeps coming up. I ran a CatboostClassifier model with Optuna last month on the same machine and didn't have any problems. 

> Trial 89 failed with parameters: {'colsample_bylevel': 0.09823302119398741, 'learning_rate': 0.07107972276294149, 'depth': 7, 'l2_leaf_reg': 1.0740722974180645, 'subsample': 0.33390126454656827, 'bagging_temperature': 2.2829174753090427, 'model_size_reg': 0.1496496874051078, 'boosting_type': 'Plain'} because of the following error: CatBoostError('(The process cannot access the file because it is being used by another process.) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/util/system/file.cpp:857: can\'t open "catboost_info\\\\test\\\\events.out.tfevents" with mode WrOnly|CreateAlways|Seq (0x00000034)').

catboost version: 1.1.1
Operating System: Windows
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Here's the full error message: 

> Trial 89 failed with parameters: {'colsample_bylevel': 0.09823302119398741, 'learning_rate': 0.07107972276294149, 'depth': 7, 'l2_leaf_reg': 1.0740722974180645, 'subsample': 0.33390126454656827, 'bagging_temperature': 2.2829174753090427, 'model_size_reg': 0.1496496874051078, 'boosting_type': 'Plain'} because of the following error: CatBoostError('(The process cannot access the file because it is being used by another process.) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/util/system/file.cpp:857: can\'t open "catboost_info\\\\test\\\\events.out.tfevents" with mode WrOnly|CreateAlways|Seq (0x00000034)').
> Traceback (most recent call last):
>   File "C:\Users\tompe\anaconda3\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
>     value_or_values = func(trial)
>   File "C:\Users\tompe\AppData\Local\Temp\ipykernel_15320\3241752603.py", line 17, in catboost_objective
>     model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=0)
>   File "C:\Users\tompe\anaconda3\lib\site-packages\catboost\core.py", line 5730, in fit
>     return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
>   File "C:\Users\tompe\anaconda3\lib\site-packages\catboost\core.py", line 2355, in _fit
>     self._train(
>   File "C:\Users\tompe\anaconda3\lib\site-packages\catboost\core.py", line 1759, in _train
>     self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
>   File "_catboost.pyx", line 4623, in _catboost._CatBoost._train
>   File "_catboost.pyx", line 4672, in _catboost._CatBoost._train
> _catboost.CatBoostError: (The process cannot access the file because it is being used by another process.) C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/util/system/file.cpp:857: can't open "catboost_info\\test\\events.out.tfevents" with mode WrOnly|CreateAlways|Seq (0x00000034)
> [W 2023-06-05 14:27:15,536] Trial 89 failed with value None.

If it helps, here's the code to set up the parameters: 

> def catboost_objective(trial):
>     param = {  
>         
>         "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.01, 0.1),
>         "learning_rate": trial.suggest_float("learning_rate", .001, 0.1),
>         "depth": trial.suggest_int("depth", 1, 12),
>         "l2_leaf_reg":trial.suggest_float("l2_leaf_reg", .0001, 25.0),
>         "subsample": trial.suggest_float("subsample", 0.05, 1.0),
>         "bagging_temperature":trial.suggest_float("bagging_temperature", 0, 10),
>         "model_size_reg":trial.suggest_float("model_size_reg", 0.1, 1.0, log=True),
>         "boosting_type": trial.suggest_categorical("boosting_type", ["Ordered", "Plain"]),
>             }        
> 
>     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
>     model = CatBoostRegressor(**param)
>     model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=0)
>     y_pred = model.predict(X_test)
>     rmse = np.sqrt(mean_squared_error(y_test, y_pred))
>     return rmse

And the code to set up the Optuna study:

> study_catboost = optuna.create_study(sampler=TPESampler(), direction='minimize')
> study_catboost.optimize(catboost_objective, n_trials=1000)
> print('Number of finished trials:', len(study_catboost.trials))
> print('Best trial:', study_catboost.best_trial.params)

**Comment by tompellegrini** [comment]
Update: I uninstalled Catboost version 1.1.1 and installed version 1.2. The problem is still occurring.

**Comment by tompellegrini** [comment]
Another update: I ran a full 1,000 trial Optuna study with the same data model using XGBRegressor and had no problems. So it doesn't seem to be an Optuna issue.

**Comment by tompellegrini** [comment]
And here's the full stack trace I should have put above:

> 

> CatBoostError                             Traceback (most recent call last)
> > ~\AppData\Local\Temp\ipykernel_21292\1346990750.py in <module>
> >       1 study_catboost = optuna.create_study(sampler=TPESampler(), direction='minimize')
> > ----> 2 study_catboost.optimize(catboost_objective, n_trials=1000)
> >       3 print('Number of finished trials:', len(study_catboost.trials))
> >       4 print('Best trial:', study_catboost.best_trial.params)
> > 
> > ~\anaconda3\lib\site-packages\optuna\study\study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
> >     423         """
> >     424 
> > --> 425         _optimize(
> >     426             study=self,
> >     427             func=func,
> > 
> > ~\anaconda3\lib\site-packages\optuna\study\_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
> >      64     try:
> >      65         if n_jobs == 1:
> > ---> 66             _optimize_sequential(
> >      67                 study,
> >      68                 func,
> > 
> > ~\anaconda3\lib\site-packages\optuna\study\_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
> >     161 
> >     162         try:
> > --> 163             frozen_trial = _run_trial(study, func, catch)
> >     164         finally:
> >     165             # The following line mitigates memory problems that can be occurred in some
> > 
> > ~\anaconda3\lib\site-packages\optuna\study\_optimize.py in _run_trial(study, func, catch)
> >     249         and not isinstance(func_err, catch)
> >     250     ):
> > --> 251         raise func_err
> >     252     return frozen_trial
> >     253 
> > 
> > ~\anaconda3\lib\site-packages\optuna\study\_optimize.py in _run_trial(study, func, catch)
> >     198     with get_heartbeat_thread(trial._trial_id, study._storage):
> >     199         try:
> > --> 200             value_or_values = func(trial)
> >     201         except exceptions.TrialPruned as e:
> >     202             # TODO(mamu): Handle multi-objective cases.
> > 
> > ~\AppData\Local\Temp\ipykernel_21292\529374345.py in catboost_objective(trial)
> >      14     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
> >      15     model = CatBoostRegressor(**param)
> > ---> 16     model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=0)
> >      17     y_pred = model.predict(X_test)
> >      18     rmse = np.sqrt(mean_squared_error(y_test, y_pred))
> > 
> > ~\anaconda3\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
> >    5732             CatBoostRegressor._check_is_compatible_loss(params['loss_function'])
> >    5733 
> > -> 5734         return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
> >    5735                          use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description,
> >    5736                          verbose_eval, metric_period, silent, early_stopping_rounds,
> > 
> > ~\anaconda3\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, plot_file, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
> >    2355         with log_fixup(log_cout, log_cerr), \
> >    2356             plot_wrapper(plot, plot_file, 'Training plots', [_get_train_dir(self.get_params())]):
> > -> 2357             self._train(
> >    2358                 train_pool,
> >    2359                 train_params["eval_sets"],
> > 
> > ~\anaconda3\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
> >    1759 
> >    1760     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
> > -> 1761         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
> >    1762         self._set_trained_model_attributes()
> >    1763 
> > 
> > _catboost.pyx in _catboost._CatBoost._train()
> > 
> > _catboost.pyx in _catboost._CatBoost._train()
> > 
> > CatBoostError: (The process cannot access the file because it is being used by another process.) C:/Go_Agent/pipelines/BuildMaster/catboost.git/util/system/file.cpp:857: can't open "catboost_info\\learn\\events.out.tfevents" with mode WrOnly|CreateAlways|Seq (0x00000034)
> > 
> > ​

**Comment by tompellegrini** [comment]
I found the cause of the issue. I had the train_test_split within the catboost_objective function. When I moved it outside the function, I no longer received the error message. It seems performing the split within the function for catboost created some type of access error. I'm therefore closing this issue.

**Comment by arghyaabinbevproc** [comment]
I am still getting the same error.I have done my test train split outside catboost but i need to fit it on like :- obj.fit(X_train, y_train)
where obj is a python object using Catboost inherently.
But the error is inconsistent.Something to do with memory usage?

**Comment by Sagar-Tachtode** [comment]
[https://github.com/catboost/catboost/issues/2404](url)

**Comment by Sagar-Tachtode** [comment]
`os.listdir()`

**Comment by mck-star-yar** [comment]
I experience the same issue without doing any shinanigans to the model. Just simple catboost = CatboostRegressor() and then fit-predict on the data. For context, if that matters, I do validation procedure on manually implemented leave-one-out validation which takes out a slice of data, fits on the remaining dataset, and validates on left out the slice of data.

**Comment by Sagar-Tachtode** [comment]
Thanks, got it cleared.
