### ISSUE TITLE
Distributed training via the Python interface

### ISSUE THREAD

**Issue by dthiagarajan** [catboost/catboost#2406]
Hello Catboost community! 

Is there a plan to support distributed Catboost training through the Python interface (similar to the style in which I do distributed training for LightGBM as shown in [this issue](https://github.com/microsoft/LightGBM/issues/5896#issue-1724498284) I posted on their Github page).

**Comment by nikitxskv** [comment]
Hi @dthiagarajan !
We don't have distributed training interface like in LightGBM..
But we have pyspark: https://catboost.ai/en/docs/concepts/spark-quickstart-python

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi! 
thanks for trying catboost!

catboost already supports pyspark interface -- please see https://catboost.ai/en/docs/concepts/spark-quickstart-python

no plans to support lgbm interface so far

**Comment by dthiagarajan** [comment]
Is there any plan to support it? And is there a different entrypoint for distributed training besides [this function](https://github.com/catboost/catboost/blob/bc223fbc88f068da13050422780c93da5deb1932/catboost/libs/train_lib/train_model.cpp#L1507)?

**Comment by nikitxskv** [comment]
Unfortunately, there are no such plans
