### ISSUE TITLE
Why are the results in CPU and GPU different?

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#241]
I trained the models using CPU and GPU versions on the same data.
Both models showed test Logloss 0.6384168 (CPU) and 0.6381189 (GPU), almost the same.
But when I applied model in R on the test dataset (that didn't take part in the learning process), I got the following results:
Logloss: 0.6379182 (CPU) and 0.6650318 (GPU)
AUC: 0.6846803 (CPU) and 0.6368528 (GPU)
Accuracy: 0.6343 (CPU) and 0.6064 (GPU)
Clearly model result got with GPU is much worse.
The Logloss of the model got on CPU is approximately equal to the Logloss got during the learning process.
Could there be any error in the Logloss formula in GPU version or anything else?

**Comment by Noxoomo** [comment]
Hi, do you have categorical and float features in the pool at the same time?

**Comment by khrisanfov** [comment]
Hi, yes it is. My features:
0	Categ	X1
1	Num	X2
2	Categ	X3
3	Num	X4
4	Categ	X5
5	Num	X6
6	Target	Y
It is binary classification.

**Comment by Noxoomo** [comment]
Ok, then we've already find the problem and will ship fix soon: we don't save GPU model properly if there are categorical and numerical at the same time in dataSet (issue is presented since we've migrated to flatbuffers modes).

For now you could try to build CatBoost from last git revision

**Comment by khrisanfov** [comment]
Ok, I will try the last commit.

**Comment by khrisanfov** [comment]
I have tried the last commit now it works as expected - the results almost the same. Thanks for the fix.

**Comment by kdlin** [comment]
@khrisanfov Can you please verify if the problem has returned? I am running into the same issue with the latest version, 0.22.

**Comment by khrisanfov** [comment]
@kdlin Hello, I do not use CPU training at the moment, GPU only. If you have small difference it is ok because there is difference between GPU and CPU algorithm.

**Comment by kdlin** [comment]
@khrisanfov Thanks for the comment. I am using Python and CPU currently, and want to switch to GPU to speed it up. But GPU yields worse metrics and I need to improve the GPU metrics to match those from CPU. If you have any suggestions, that would be greatly appreciated.

**Comment by khrisanfov** [comment]
You can display and compare parameters by using this method https://catboost.ai/docs/concepts/python-reference_catboostclassifier_get_all_params.html
I prefer GPU because it is much faster than CPU. I didn't make loss comparisons for a long time.

**Comment by kdlin** [comment]
@khrisanfov Thanks. That is exactly what I am doing now.

**Comment by razamit** [comment]
Hi.
I am suffering the from the same issue. 
my results on GPU are about 50% worse than on CPU 
How can there be such a difference?

**Comment by LyzhinIvan** [comment]
> Hi.
> I am suffering the from the same issue.
> my results on GPU are about 50% worse than on CPU
> How can there be such a difference?

Hi, @razamit 
We know about quality drop on GPU relative to CPU. We will investigate it asap. The main issue about this problem is #1408.

**Comment by razamit** [comment]
@LyzhinIvan thanks. looking forward for a solution
