### ISSUE TITLE
Catboost Ranker does not recognize documented loss functions: YetiRank, NDCG, QueryAUC

### ISSUE THREAD

**Issue by carl-offerfit** [catboost/catboost#2410]
Problem: _catboost.CatBoostError: /Users/zomb-ml-platform-msk/go-agent-21.2.0/pipelines/BuildMaster/catboost.git/catboost/private/libs/options/catboost_options.cpp:263: Unknown loss function NDCG
catboost version: 1.2
Operating System: Mac
CPU: M1
GPU: 

```
        parameters = {
            'loss_function' : "NDCG"
            'iterations': 500,
            'depth' : 4,
            'learning_rate' : 0.01,
            'verbose': False,
            'random_seed': 0,
            'allow_writing_files' : False
        }
        model = CatBoostRanker(**parameters)
        model.fit(train_pool)
```

I get the same for YetiRank, QueryAUC and everything else I've tried. Based on this page, I thought this would work : https://catboost.ai/en/docs/concepts/loss-functions-ranking#ndcg.  Except QueryRMSE seems to work - everything else gives the same error. Is there a documentation somewhere of what is actually implemented?

Thanks!

**Comment by nov-stacy** [comment]
Hello! NDCG and QueryAUC are metrics and cannot be used as loss functions. YetiRank can be used, so check again, because there should not be such an error. In this table you can see all the metrics that can be used as a loss function: https://catboost.ai/en/docs/concepts/loss-functions-ranking#usage-information

**Comment by carl-offerfit** [comment]
Great, sorry for my misunderstanding. I guess I had a typo when I tried YetiRank because now I see it works. But i do have another issue which is that after fitting the model I'm trying to evaluate the YetiRank with 

```
        eval_metrics = model.eval_metrics("YetiRankPairwise")
```

And I'm getting this error:

```
_catboost.CatBoostError: /Users/zomb-ml-platform-msk/go-agent-21.2.0/pipelines/BuildMaster/catboost.git/catboost/libs/metrics/metric.cpp:6027: Unsupported metric: YetiRankPairwise
```

Do you know what I should use for this? Or should I open a new issue and close this one?

**Comment by nov-stacy** [comment]
Hello! YetiRank is loss function. It is not used as a metric. If you use this in training, then [PFound](https://catboost.ai/en/docs/concepts/loss-functions-ranking#PFound) is calculated instead. We will correct the documentation to make it clearer

**Comment by carl-offerfit** [comment]
Hi, sorry for the slow reply - I was traveling last week.

Okay I think I get it now - the docs say "An approximation of ranking metrics (such as NDCG and PFound). Allows to use ranking metrics for optimization."  So our goal is always to optimize ranking metrics such as NDCG and PFound. We use YetiRank to make the optimization work, but in the end we still evaluate on NDCG or PFound. We may then for example cross-validate different optimization metrics (YetiRank, YetiRankPairwise, etc.) and see which one gives the best NDCG. Is that right?

Is there a list of all the metrics supported by `eval_metrics`?

Thanks for your time!

**Comment by nov-stacy** [comment]
Hi! The list is there: https://catboost.ai/en/docs/concepts/loss-functions

**Comment by carl-offerfit** [comment]
Thank you!
