### ISSUE TITLE
Overall eval_metrics for a data set and model

### ISSUE THREAD

**Issue by carl-offerfit** [catboost/catboost#2420]
Problem: I am confused by the eval_metrics function. It takes parameters `ntree_start` and `ntree_end`. It says "To reduce the number of trees to use when the model is applied or the metrics are calculated, setthe range of the tree indices to[ntree_start; ntree_end)."

Why do you limit the number of trees to use when the model is applied? Normally if I fit a model with a certain number of trees in a cross validation, I use all of them. If I wanted less, I would have specified less (I do specify less on other cross validated runs.) It seems that to use all of the trees you ignore the parameters, but then you get one evaluation metric per tree. What does that mean? I am interested in getting the single overall evaluation metric for the dataset using all the trees. How do I do this?

Thank you for your time.

**Comment by carl-offerfit** [comment]
Okay, I think I get it: If I want the final eval metric including all trees I should call `eval_metrics` without specifying ntree_start and ntree_end, and then take the final value of the resulting series - because this is the metric after including all trees. Is that right?

Something like:

```
eval_metrics = model.eval_metrics(train_pool, test_metrics)
final_metrics = {metric : eval_metrics[metric][-1]  for metric in eval_metrics.keys()}
```

Is that the right idea? Thanks!

**Comment by andrey-khropov** [comment]
> Okay, I think I get it: If I want the final eval metric including all trees I should call `eval_metrics` without specifying ntree_start and ntree_end, and then take the final value of the resulting series - because this is the metric after including all trees. Is that right?
> 
> Something like:
> 
> ```
> eval_metrics = model.eval_metrics(train_pool, test_metrics)
> final_metrics = {metric : eval_metrics[metric][-1]  for metric in eval_metrics.keys()}
> ```
> 
> Is that the right idea? Thanks!

Yes, that's the idea. We'll try to make it more clear in the documentation.

**Comment by carl-offerfit** [comment]
Thanks!
