### ISSUE TITLE
encoding the target variable

### ISSUE THREAD

**Issue by algomaschine** [catboost/catboost#2431]
Gents, I'm predicting a float column that has distribution pretty much like below.
![disrtib](https://github.com/catboost/catboost/assets/20881228/56f5afcf-cd56-4865-a80c-f137e13439a3)

So there are different approaches that I'm testing (I'm really interested mostly in the direction and magnitude, not precise values).

1) split the target into classes like {-50,-40,30,20,10, 10,20,30,40,50} - and make 10 binary columns, do multiclassification within 1 model.
2) just assign the categories within one column {-50,-40,30,20,10, 0, 10,20,30,40,50} and forecast the category using 1 column.
3) make 1 distinct binary model per each category (as in classic methods before multiclassification existed).

Now I'm trying different variations and also different splittage of classes. However, is there a catboost official guideline which method is the best with this package? Been watching videos, reading some docs, but haven't really found an answer...

Thanks!

**Comment by ek-ak** [comment]
Hello!
You can solve this problem as a regression problem.  You will get float predictions,  but you can  round  obtained predictions and clip to [-50, 50] interval if you need later. 
You can use [CatBoostRegressor](https://catboost.ai/en/docs/concepts/python-reference_catboostregressor),  an example of the regression problem solution you can find in our tutorial: https://github.com/catboost/tutorials/blob/master/categorical_features/categorical_features_parameters.ipynb.
