### ISSUE TITLE
prediction throws CarboostError

### ISSUE THREAD

**Issue by myusernameisunique** [catboost/catboost#244]
CatboostError: catboost/libs/algo/apply.cpp:18: Insufficient float features count

All my features are categorical.

It trained just fine. I was actually surprised by how well my evaluation set's AUC was improving while it was training.

I declared all pools with correct categorical indices.

My process:
...
data preparation
convert columns to pandas categorical columns
...
model = catboost.CatBoostClassifier(...)
learn = catboost.Pool(...)
eval = catboost.Pool(...)
model.fit(learn, ..., eval_set=eval, ...)
model.save_model(...)
...
model = catboost.CatBoostClassifier()
model.load_model(...)
predict = catboost.Pool(...)
model.predict(predict, prediction_type='Probability')

then ..........
predictions = np.array(self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose))
  File "_catboost.pyx", line 1049, in _catboost._CatBoostBase._base_predict
  File "_catboost.pyx", line 858, in _catboost._CatBoost._base_predict
  File "_catboost.pyx", line 861, in _catboost._CatBoost._base_predict
_catboost.CatboostError: catboost/libs/algo/apply.cpp:18: Insufficient float features count 0<517

Any idea?

**Comment by annaveronika** [comment]
what version do you use? do you use gpu or cpu training?

**Comment by myusernameisunique** [comment]
catboost-0.6.1.1
and i am using cpu training.

I just realized my problem... it is absolutely not an issue with catboost. i have a "write_models" flag that was set to false (oops...). I was reading an old model which contained 517 float columns.

sorry to bother!

but thank you for responding so quickly!
