### ISSUE TITLE
self comment in custom loss

### ISSUE THREAD

**Issue by amirnachum15** [catboost/catboost#2442]
Problem: user defined loss function cannot optimize when there is a comment with the word 'self'
catboost version: 1.2

Here is a reproducible example:

    class RmseObjective(object):
        def calc_ders_range(self, approxes, targets, weights):
            # self
            assert len(approxes) == len(targets)
            if weights is not None:
                assert len(weights) == len(approxes)
            
            result = []
            for index in range(len(targets)):
                der1 = targets[index] - approxes[index]
                der2 = -1
    
                if weights is not None:
                    der1 *= weights[index]
                    der2 *= weights[index]
    
                result.append((der1, der2))
            return result

the code is taken from the following catboost tutorial (with the addition of the comment with self):
https://github.com/catboost/catboost/blob/master/catboost/tutorials/custom_loss/custom_loss_and_metric_tutorial.ipynb

**Comment by VlasovKirill** [comment]
Why did you decide that function cannot optimize and why do think that commented string might matter? I have compared the original loss with your example and I got pretty similar results.

**Comment by amirnachum15** [comment]
I guess you are correct and the commented string does not indicate a loss in performance. Then the issue is only the printed string in that case

**Comment by andrey-khropov** [comment]
> Then the issue is only the printed string in that case

What do you mean by that?

**Comment by andrey-khropov** [comment]
No feedback, feel free to reopen with more detailed data if the issue can still be reproduced.
