### ISSUE TITLE
Catboost training uncaught exception: address -> / what() -> / type ->

### ISSUE THREAD

**Issue by elutins** [catboost/catboost#2445]
### Problem:

I am deploying a model using catboost version `0.24.3` (this error may be due to a version issue, but am running on an older Catboost version for internal compatibility reasons) and running in production on an AWS Batch instance. Running into the following `uncaught exception`. 

```
uncaught exception: 
    address -> 0x1079213c0
    what() -> "map::at:  key not found"
    type -> std::out_of_range
```

I have attempted to increase the resources allocated to the compute instance, however that does not solve the issue. Is there a known root of the problem or solution? Thanks in advance

catboost version: `0.24.3`
Operating System: `Linux`
CPU: ✅ 
GPU: ❌

**Comment by andrey-khropov** [comment]
This is a very generic error that means somewhere in C++ code [std::map::at](https://en.cppreference.com/w/cpp/container/map/at) has been called with a key that is not in this map container as an argument.

More detailed info is need to check what is going on. Are you able to get a full stack trace when getting this error? Can you run it under a debugger?

**Comment by andrey-khropov** [comment]
No feedback, feel free to reopen with more detailed data if the issue can still be reproduced.
