### ISSUE TITLE
GPU - Python terminated with SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by ctlaltdefeat** [catboost/catboost#245]
Hi,

I built the python wheel of catboost from source a few hours ago (pointing to CUDA 9.1 with a GTX 1080) on Linux.
When trying to fit a model on the GPU, python terminates with a segmentation fault ("python terminated by signal SIGSEGV (Address boundary error)"). I'm fitting with "debug" level, and the error occurs before any info is printed. Fitting on the CPU works fine.

I would be happy to provide any logs or dumps if you could point me to them.

**Comment by kizill** [comment]
Can you try to reproduce crash with CLI binary, possibly under gdb, to collect stacktrace?

**Comment by Noxoomo** [comment]
And:
1) Did you compiled cat boost with another cuda version from the same source directory?  
2) What compiler do you use? (gcc/clang versions)

**Comment by ctlaltdefeat** [comment]
My default compiler is gcc 7, but I also have gcc6 on my system (required for CUDA 9.1). Could the issue be that catboost was compiled with gcc7? How could I try compiling with gcc6 through ya?

When trying to compile the CLI binary I get an error:

```error: zlib is not available```

which is weird, because the python wheel compilation went smoothly.

I'm hesitant to install another cuda version side by side as I feat that would mess things up.

**Comment by Noxoomo** [comment]
Could you check python package compilation:
 in python-package/catboost run
` ya make -r -DPYTHON_CONFIG=$PYTHON_DIR/bin/python-config -DPYTHON_BIN=$PYTHON_DIR/bin/python -DUSE_ARCADIA_PYTHON=no -DCUDA_ROOT=$PATH_TO_CUDA`
If everything works, then check that compiled this way catboost terminates with segfault. (you could add to PYTHONPATH path to python-package dir)


>  How could I try compiling with gcc6 through ya?

ya uses system compile for building CUDA. You could change default system compiler via update-alternatives in ubuntu (update-alternatives --config gcc and update-alternatives --config  g++).

**Comment by ctlaltdefeat** [comment]
I compiled the python wheel with gcc6 by symlinking gcc to gcc6 and putting that into my path temporarily, and now training with GPU works.

**Comment by ctlaltdefeat** [comment]
Doesn't happen on the newest master, I instead get a ```_catboost.CatboostError: std::bad_cast``` error. 
That should be a separate issue though.
