### ISSUE TITLE
Update R installation guide

### ISSUE THREAD

**Issue by grayskripko** [catboost/catboost#247]
according to [this thread](https://www.reddit.com/r/MachineLearning/comments/7ujxto/n_new_version_of_catboost_gradient_boosting/dtla81f/)

Please add this kind of installation 
```
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.6.1/catboost-R-Windows-
0.6.1.tgz', INSTALL_opts = c("--no-multiarch"))  # or ... args = c("--no-multiarch"))
```
as the preferable way for Windows

**Comment by sab** [comment]
Done, https://tech.yandex.com/catboost/doc/dg/concepts/r-installation-docpage/#binary-installation
