### ISSUE TITLE
Catboost_spark doesn't recognise setAutoClassWeights and setScalePosWeight 

### ISSUE THREAD

**Issue by kamranesmaeili** [catboost/catboost#2470]
Problem: catboost pyspark implementation doesn't recognise setAutoClassWeights and setScalePosWeight as additional commands. For instance when I try setScalePosWeight(3.0) I get an error saying _unknown option {scale_pos_weight} with value "3"_. Without using these I am able to train the model without any issues. Following are the code:
- Catboost_spark.CatBoostClassifier(featuresCol='features', labelCol='label', evalMetric='AUC) - works well.
- Catboost_spark.CatBoostClassifier(featuresCol='features', labelCol='label', evalMetric='AUC).setAutoClassWeights('Balanced')
- Catboost_spark.CatBoostClassifier(featuresCol='features', labelCol='label', evalMetric='AUC).setScalePosWeight(3.0)
```
catboost version: catboost-spark_3.2_2.12:1.2 (maven) - spark 3.2.1 and scala 2.12
Operating System: EMR cluster
CPU: master node of m4.2xlarge and executor nodes of r4.xlarge (4 and 8V cores and 32 GiB memory)
GPU: N/A
```

**Comment by andrey-khropov** [comment]
1) AutoClassWeights issue.

You should use enum value of type `EAutoClassWeightsType` instead of string, as [described in API documentation](
https://catboost.ai/docs/catboost-spark/3.0_2.12/latest/api/python/api/catboost_spark.CatBoostClassifier.html#catboost_spark.CatBoostClassifier.setAutoClassWeights).

The proper syntax is 

```py
catboost_spark.CatBoostClassifier(featuresCol='features', labelCol='label', evalMetric='AUC).setAutoClassWeights(catboost_spark.EAutoClassWeightsType.Balanced)
```

I've checked and it works.

**Comment by andrey-khropov** [comment]
2) scalePosWeight support has been fixed in https://github.com/catboost/catboost/commit/b37c1d567db92bca66503945ff394784908ce6e2
