### ISSUE TITLE
Static linkage problem

### ISSUE THREAD

**Issue by SetSplin** [catboost/catboost#2475]
Hello. I have problems with static linkage of libcatboostmodel_static. 

I build lib using `build_native.py` script (only catboostmodel_static target). And keep getting symbol redefinition link errors. It seems to be impossible with simple tweaks to disable the cxxrt realization of std::exception and other stuff from cxxrt. So is there a way to link catboostmodel_static with project in which we use standart stl implementation?

**Comment by andrey-khropov** [comment]
Can you give more details, please? 

- OS
- CatBoost Revision.
- How exactly do you build catboostmodel_static and how do you build your application with it?

**Comment by andrey-khropov** [comment]
No feedback, feel free to reopen with more detailed data if the issue can still be reproduced.
