### ISSUE TITLE
Send is not implemented for model struct in rust

### ISSUE THREAD

**Issue by FarhadF** [catboost/catboost#2482]
Problem: Send is not implemented for model in Rust, means model cannot be transferred across thread boundaries. But #272 states that its threadsafe!
catboost version: 1.2
Operating System: Linux
CPU: x86
GPU: -

**Comment by andrey-khropov** [comment]
@FarhadF. Please, [agree to the CLA](https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md). I've checked the diff - tests have been passed successfully.
