### ISSUE TITLE
How to generate a column-description (.cd) from an arbitrary CSV file?

### ISSUE THREAD

**Issue by salamanders** [catboost/catboost#2488]
Problem:  I've been given a flat CSV.  **Is there an easy way to make a column description file?**  I'm trying to run a command line version of catboost to see how well it does against some other options we have.

1. The CSV has a header row.  It doesn't have any "silly" stuff like quotes or commas - it parses easily.
2. It has missing values scattered across most columns.  (especially the target label column!)
3.  Some columns are strings, others are positive ints, others are double.  But at least they are consistent -- if I sample the first 100 rows and ignore nulls, I can figure out the type.
4. I know the column header name of the label class column, but that is all I know (it could be in any order). 
catboost version: latest
Operating System: linux
CPU: n/a
GPU: n/a

I've tried hand-crafting the cd file, and I must be messing something up, I keep getting various errors.

> Incorrect CD file. Invalid line number #0: /src/catboost/catboost/libs/column_description/cd_parser.cpp:61: Invalid column index: index = 1, columnsCount = 1

> Pool should have at least one factor

> Incorrect CD file. Invalid line number #1: /src/catboost/catboost/libs/column_description/cd_parser.cpp:61: Invalid column index: index = 1, columnsCount = 1

**Comment by andrey-khropov** [comment]
> Is there an easy way to make a column description file?

Format is simple enough that you can either create it by hand or generate programmatically easily.

The minimum that you need to have in CD file is all non-feature column indices and types (like Target, Weight etc.).
For all the columns that are not specified in CD file they are assumed to be numerical features by default.
However if you have categorical, text or embedding features you have to add the corresonding columns to the CD file (the index and the column type are necessary and the name (the third column) is optional).

If you have the header in the data file you must pass `--has-header` flag to the CLI binary, it will ensure that the first row in the file won't be interpreted as usual values data and as would be used to get column names instead (so you don't need to specify all feature names in CD file's third column).

> I know the column header name of the label class column, but that is all I know (it could be in any order).

You have to get Label column index. CD file requires column indices to be specified now.

> I keep getting various errors.

Please provide a small reproducible example (CD file and data file contents).

**Comment by andrey-khropov** [comment]
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.
