### ISSUE TITLE
Adding cross-validation parameters in model.fit()

### ISSUE THREAD

**Issue by grisme** [catboost/catboost#249]
Hi! 
I can not find the parameters for cross-validation somewhere other than the function [cv](https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_cv-docpage/). Do you plan to add a parameter for this? 
I would like to be able to write like this: `model.fit(train_data, train_label, folds_count=5)`

**Comment by annaveronika** [comment]
We don't plan to provide model.fit with cv interface. Because what would be the result of this operation? The interface should be consistent with current fit function.
What's the problem with using cv(pool, params, fold_count)?

**Comment by grisme** [comment]
Can I somehow save the model, which has turned out after `cv` call?

**Comment by annaveronika** [comment]
What is your scenario, how do you want to use it?

**Comment by grisme** [comment]
It seems that I did not quite understand the idea of cross-validation. Now I read about it and understood better.
