### ISSUE TITLE
Catboost v1.2.1.1 __version__ contains additional metadata

### ISSUE THREAD

**Issue by janvdp** [catboost/catboost#2495]
Problem: __version__ for `v1.2.1.1` returns `1.2.1.1.16848`.
catboost version: 1.2.1.1
Operating System: Mac and Linux
CPU:
GPU:

Reproduce:

Install:
```bash

pip install catboost
```

In python:
```python
import catboost
print(catboost.__version__)
```

Additionally, the source code and releases on github are still on 1.2.1.

**Comment by andrey-khropov** [comment]
It has been published by mistake and will be deleted from PyPI. We're sorry.

P.S. The code itself isn't broken so if you used it for training or prediction there's nothing with the results.

**Comment by janvdp** [comment]
Thanks for the feedback, no worries. Glad you have it covered!

**Comment by andrey-khropov** [comment]
The last catboost version has been updated to 1.2.2

**Comment by janvdp** [comment]
Thanks for the update! Already adding support for it :)
