### ISSUE TITLE
Build _catboost lib for iOS

### ISSUE THREAD

**Issue by serhii-vlasiuk** [catboost/catboost#2496]
Can I build _catboost library for iOS platform?

**Comment by andrey-khropov** [comment]
No. iOS is not supported right now. But you can export your model in Apple CoreML format and apply it on iOS: https://catboost.ai/en/docs/concepts/export-coreml

**Comment by serhii-vlasiuk** [comment]
Do you have in plans support build _catboost library for iOS?

**Comment by andrey-khropov** [comment]
> Do you have in plans support build _catboost library for iOS?

That's unlikely. iPhones and iPad are not very suitable for training Machine Learning models. On the other hand, catboostmodel library for applying models might be supported in the future.
