### ISSUE TITLE
Build _catboost.so for MacOS arm64

### ISSUE THREAD

**Issue by serhii-vlasiuk** [catboost/catboost#2503]
Hi, 

While building library for MacOS arm64 getting such errors

Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include/emmintrin.h:14:2: error: “This header is only meant to be used on x86 and x64 architecture”

Is it possible to build library for arm64 arch?

**Comment by andrey-khropov** [comment]
I (and our CI for releases) are able to build `lib_catboost.so` without such problems. 

Can you describe in more details:
- your environment (OS version, CPU, XCode version, python version, CMake version, conan version)
- catboost source revision you build from
- what commands exactly do you run

?

**Comment by andrey-khropov** [comment]
No detailed information is provided, so I'm closing this issue.

**Comment by faucct** [comment]
Same. Versions:

OS version – 14.4.1 (23E224)
CPU – some Mac ARM processor, M1 Pro laptop

```
faucct-osx:catboost faucct$ xcode-select -version
xcode-select version 2406.
faucct-osx:catboost faucct$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 15.3.0.0.1.1708646388
volume: /
location: /
install-time: 1710312637
```

Command Line Tools for Xcode                       15.3       13.03.2024, 10:50:51  
Python 3.12.3
cmake version 3.27.6
Conan version 1.64.1

**Comment by andrey-khropov** [comment]
> Revision – [44f8d19](https://github.com/catboost/catboost/commit/44f8d197dfddd680e38b6f3524151286e1c9b834) 
> Command – `python3 build/build_native.py --build-root-dir=./build_no_cuda --targets catboost`

Yes, the build has been broken in this revision.
Please try some revision after the fix - https://github.com/catboost/catboost/commit/7a9ad298f71e0aae9af36d9c8ad55acf1e02ccc0 or later.
