### ISSUE TITLE
Python model predicts and exported cpp model predicts are not equal (without cat features)

### ISSUE THREAD

**Issue by StarodubtsevDV** [catboost/catboost#2513]
Hello, catboost team!
catboost version: 1.2.1
Operating System: ubuntu-22.04

I am trying to use catboost multiclasses classifier (with 3 classes) exported to CPP code by next command:
```model.save_model('cpp_catboost.cpp', format = 'cpp')```

So, after that as result we got cpp file with weights and needed functions. I use ApplyCatboostModelMulti() to classify our feature data without categorical features. I've got an array with 3 numbers, after that I've got the index of the maximum array value as class label.
So, I made a comparison with python model classification results and cpp model was wrong in 50% cases.

Could you please tell me what I do wrong?

**Comment by andrey-khropov** [comment]
Fixed in https://github.com/catboost/catboost/commit/70d7459524b87915ef247ceb28972f2b620d5954
