### ISSUE TITLE
Cgroups v2 should be supported in info.cpp

### ISSUE THREAD

**Issue by elukey** [catboost/catboost#2518]
Hi folks!

IIUC catbost's `info.cpp` supports only cgroups v1, and it would be great if you could extend the support to v2 as well.
XGBoost is doing a similar thing in https://github.com/dmlc/xgboost/issues/9622

From a quick peek in https://github.com/catboost/catboost/blob/master/util/system/info.cpp#L52 it seems that only the old format is recognized.

Thanks in advance!

**Comment by elukey** [comment]
The xgboost code uses the file `/sys/fs/cgroup/cpu.max` for cgroups v2, that has this format:

```
200000 100000
```
> It's in the following format: $MAX $PERIOD which indicates that the group may consume up to $MAX in each $PERIOD duration.

**Comment by andrey-khropov** [comment]
Fixed in PR https://github.com/catboost/catboost/pull/2519.
