### ISSUE TITLE
eval_metrics in R

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#252]
The python library has eval_metrics method, which calculates metric value on every iteration and returns for each requested metric its values on each iteration. We need to do the same for R. This will also allow for visualisation of metric values.

**Comment by PhilippPro** [comment]
[http://mlr-org.github.io/mlr-tutorial/devel/html/measures/index.html](http://mlr-org.github.io/mlr-tutorial/devel/html/measures/index.html)

**Comment by annaveronika** [comment]
The calculation of metrics needs to be in C++, it's time critical and needs to be parallelized. That's why we write for metrics our own code.
But this issue is not about code of metrics calculation. I have updated the description, so that it's more clear.

**Comment by PhilippPro** [comment]
The calculation of metrics in general is not time consuming (at least the measures I know, maybe you can prove me wrong), so this is not the problem. It is even important for the user to be able to look how the measure is implemented which is a reason for implementing it in R.

**Comment by PhilippPro** [comment]
Ok, from this side it makes sense. On the other hand, the user maybe wants to specify his own metric.

**Comment by annaveronika** [comment]
This is possible for python, see documentation. But in this case it might work slower.
