### ISSUE TITLE
Load PreQuantized Data for Fitting

### ISSUE THREAD

**Issue by mrhantato** [catboost/catboost#2521]
Hi CatBoost team,

I am wondering whether there is a way to load Pre-Quantized data to skip the quantization process for CatBoost fitting. Thank you so much!

**Comment by ek-ak** [comment]
Hello!  Sorry for the long answer. Yes, you can load pre-quantized data, here is example:
https://catboost.ai/en/docs/concepts/speed-up-training#reusing-quantized-datasets
