### ISSUE TITLE
Control catboost weights in function of sample size

### ISSUE THREAD

**Issue by Leprechault** [catboost/catboost#2528]
I'd like to know if you have any way to control catboost weights in the function of sample size. In my case I have a dataset of 4 areas, area 1 size 24508, area 2 with 44304 and area 3 with 128 values. I don't like to make several bootstraps with size 128, but create some weights in the model. Is this possible in catboost?

Thanks in advance!

**Comment by andrey-khropov** [comment]
> I'd like to know if you have any way to control catboost weights in the function of sample size. In my case I have a dataset of 4 areas, area 1 size 24508, area 2 with 44304 and area 3 with 128 values. I don't like to make several bootstraps with size 128, but create some weights in the model. Is this possible in catboost?

I don't quite get what kind of weights exactly do you want. If you want dataset samples to be taken into account 
with different weights during learning - yes, it is possible.

* In input data files using Columns Description file (for all APIs): https://catboost.ai/en/docs/concepts/input-data_column-descfile#weight
* In python API: https://catboost.ai/en/docs/concepts/python-reference_pool#weight
* In PySpark (JVM API is similar): https://catboost.ai/docs/catboost-spark/3.0_2.12/latest/api/python/api/catboost_spark.Pool.html#catboost_spark.Pool.setWeightCol

**Comment by Leprechault** [comment]
Thanks for your answer @andrey-khropov, but my ideia in R language is:

````
# R language
# Package: catboost
library(catboost)


# X data (predictors)
x_train <- data.frame(x_numeric_1=c(1,2,3,4,5,6,7),
  x_numeric_2=c(1,3,5,1,3,5,1),
  x_categorical_1=c("a","a","a","a","b","b","b"))

# Here a I'd like to given weights in function of  `  x_categorical_1` size, "a" are 4 values (7/4=0.6) and b (7/3=0.4):

# w data (observation weights)
w_train <- c(0.6,0.6,0.6,0.6,0.4,0.4,0.4)

# y data (target)
y_train <- c(1,3,1,4,1,5,1)

# Create the model

x_train_learn_pool <-catboost::catboost.load_pool(x_train)
  
# Fit the model
model.f <- catboost.train(data = x_train_learn_pool,
    label = y_train,
    weight = w_train
  )
#

# Fit model
test_predictions <- catboost::catboost.predict(model.f,x_train_learn_pool)
test_predictions
#

Error in catboost.train(data = x_train_learn_pool, label = y_train, weight = w_train) : 
  unused arguments (data = x_train_learn_pool, label = y_train, weight = w_train)
``` 
 But, when I try to use `weight` my model doesn't work. Please, any help with it?

**Comment by andrey-khropov** [comment]
You are passing `weight` and `label` to the wrong function. They are considered parts of the dataset. so you should pass them to `load_pool` instead of `train`, like that:

```R

# X data (predictors)
x_train <- data.frame(x_numeric_1=c(1,2,3,4,5,6,7),
  x_numeric_2=c(1,3,5,1,3,5,1),
  x_categorical_1=c("a","a","a","a","b","b","b"))

# Here a I'd like to given weights in function of   x_categorical_1 size, "a" = 4 values (7/4=0.6) and b = 3 values (7/3=0.4):

# w data (observation weights)
w_train <- c(0.6,0.6,0.6,0.6,0.4,0.4,0.4)

# y data (target)
y_train <- c(1,3,1,4,1,5,1)

# Create the model

x_train_learn_pool <-catboost::catboost.load_pool(data = x_train_learn_pool,
    label = y_train,
    weight = w_train)
  
# Fit the model
model.f <- catboost.train(learn_pool = x_train_learn_pool)
#
``` 

See the documentation: https://catboost.ai/en/docs/concepts/r-reference_catboost-load_pool, https://catboost.ai/en/docs/concepts/r-reference_catboost-train .

P.S. Sorry for the delayed response, it somehow slipped through the cracks.
