### ISSUE TITLE
Building catboost from source on macos fails with linkage errors

### ISSUE THREAD

**Issue by 7sharp9** [catboost/catboost#2531]
Problem:  Building catboost from source on macos fails with linkage errors
catboost version: latest from GitHub
Operating System: macOS Sonoma 14.1
CPU: Intel Xeon W 3.5Ghz
GPU: AMD Radeon Pro W5700X

Running the following command:

```
❯ python build/build_native.py --targets catboostmodel_static --build-root-dir=./build_model_static --macos-universal-binaries --macosx-version-min=11.0
```
I get the following error:

```
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
clang -c -I. -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src -I.. -I../include -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/../include -I../srclib -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/../srclib -I../lib -m64 -O3 -DNDEBUG -DINSTALLDIR=\"//bin\" -DLOCALEDIR=\"//share/locale\" /Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/iconv_no_i18n.c
clang -c -I. -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src -I.. -I../include -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/../include -I../srclib -I/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/../srclib -I../lib -m64 -O3 -DNDEBUG -DINSTALLDIR=\"//bin\" -DLOCALEDIR=\"//share/locale\" /Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/src/src/iconv.c
/bin/sh ../libtool --mode=link clang -m64 -m64 -O3 iconv_no_i18n.o ../srclib/libicrt.a ../lib/libiconv.la  -o iconv_no_i18n
libtool: link: clang -m64 -m64 -O3 iconv_no_i18n.o -o .libs/iconv_no_i18n  ../srclib/libicrt.a ../lib/.libs/libiconv.dylib
ld: archive member '/' not a mach-o file in '/Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/build-release/srclib/libicrt.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [iconv_no_i18n] Error 1
make: *** [all] Error 2
libiconv/1.15:
libiconv/1.15: ERROR: Package '8cdd868059c914813cf179147cef8c2637fb902a' build failed
libiconv/1.15: WARN: Build folder /Users/davethomas/.conan/data/libiconv/1.15/_/_/build/8cdd868059c914813cf179147cef8c2637fb902a/build-release
ERROR: libiconv/1.15: Error in build() method, line 126
	autotools.make()
	ConanException: Error 2 while executing make -j16
CMake Error at cmake/conan.cmake:668 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:45 (conan_cmake_install)
  ```

I tried building the non static version and its just the same.  Is there a static version available thats prebuilt?

**Comment by 7sharp9** [comment]
[build.txt](https://github.com/catboost/catboost/files/13328081/build.txt)

Here is the full buils output, any suggestions would be great!

**Comment by 7sharp9** [comment]
There was this in the log:
```
libiconv/1.15: WARN: Package binary is corrupted, removing: 8cdd868059c914813cf179147cef8c2637fb902a
Version ranges solved
    Version range '>=1.2.11 <2' required by 'pcre/8.45' resolved to 'zlib/1.3' in local cache
```
So I ran `conan remove libiconv`

Still the same linker error at the end but no mention of a corrupted libiconv

Heres the full log:  
[build.txt](https://github.com/catboost/catboost/files/13328121/build.txt)

**Comment by andrey-khropov** [comment]
This is a weird error in `libiconv` dependency built by `conan`.

I tried to run on macOS 12.7.1 on Intel-based MacBook the build command that you used and it works without problems on commit https://github.com/catboost/catboost/commit/b8697effb792868e370539d2c84c6cecaea698f6 .

I can see from the logs that the conan version 1.61.0 is used [despite that versions 1.57.0 - 1.59.0 are currently recommended ](https://catboost.ai/en/docs/installation/build-environment-setup-for-cmake#conan). But this was not the cause of the problem. Build works for me with conan 1.61.0 as well.

To try to fully reproduce this I need versions of the other components used:
- CMake
- XCode

**Comment by 7sharp9** [comment]
I tried with 1.59 and there was still the same conan error, in another tread it was mentiend that the latest Conan 2.x didnt work, I think 1.61 was the most recent version before 2.0 came out.

**Comment by 7sharp9** [comment]
My cmake is 3.27.7, XCode is 15.0.1

**Comment by andrey-khropov** [comment]
@7sharp9 

libiconv dependency has been removed in the commit https://github.com/catboost/catboost/commit/2f4bc902e1cd00232b81e322d6a0f589e17c651c#diff-b9cdea54fc80ed5a96613be330314146ffeb6c3867f1278b5f8e2dd7900a6f07.

Can you recheck the build?

**Comment by andrey-khropov** [comment]
No detailed information is provided and since CatBoost no longer depends on `libiconv` I can build on macOS without problems.
