### ISSUE TITLE
Windows 11 CatBoost build error: catboost\contrib\libs\cxxsupp\libcxx\include\stdlib.h(147): error C3861: “__builtin_fabsl”: identifier not found

### ISSUE THREAD

**Issue by leiless** [catboost/catboost#2535]
Problem:
Windows 11 (with Visual Studio Community 2019) CatBoost build error:

```
C:\Users\20562\Desktop\catboost\contrib\libs\cxxsupp\libcxx\include\stdlib.h(138): error C3861: “__builtin_fabsf”: identifier not found
C:\Users\20562\Desktop\catboost\contrib\libs\cxxsupp\libcxx\include\stdlib.h(142): error C3861: “__builtin_fabs”: identifier not found
C:\Users\20562\Desktop\catboost\contrib\libs\cxxsupp\libcxx\include\stdlib.h(147): error C3861: “__builtin_fabsl”: identifier not found
```

catboost version:
`c525f504fa589c0490eda12c375a574f1f26c130` (Nov 16, 2023)
https://github.com/catboost/catboost/tree/c525f504fa589c0490eda12c375a574f1f26c130

Operating System:
Version Windows 11 Professional
Version 22H2
Installation date 2023/11/20
Operating system version 22621.2715
Experience Windows Feature Experience Pack 1000.22677.1000.0

CPU: 12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz

GPU: None

Packages versions:
* python: 3.11.6
* cmake: 3.22.6
* ninja: 1.11.1
* conan: 1.58.0
* MSVC: Visual Studio Community 2019 (msvc-toolset = 14.29.30133) + Win 10 SDK

Build command:
```powershell
./build_native.py --targets catboostmodel --build-root-dir out --build-type=Debug --msvs-version 2019 --msvc-toolset 14.29.30133
```

**Comment by leiless** [comment]
Full build log: https://pastebin.com/1w63XDVE

**Comment by andrey-khropov** [comment]
@leiless For Windows without CUDA we've switched to clang-cl compiler. I've fixed this issue. Please check if everything works for you now. But you'll have to install Clang-cl compiler provided in the Visual Studio installation (see https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#install-1)

**Comment by leiless** [comment]
Thanks so much! I'll try sometime later.
