### ISSUE TITLE
Error using Pyspark catboost-spark recommended quickstart (CatBoostClassifier.fit() got an unexpected keyword argument 'eval_set')

### ISSUE THREAD

**Issue by Robin-Lord** [catboost/catboost#2536]
Problem: When running the recommended CatBoostClassifier quickstart for Pyspark I get the error "(CatBoostClassifier.fit() got an unexpected keyword argument 'eval_set')"

catboost version: 1.0.6

Operating System: Linux (Kaggle notebook)

CPU: Intel(R) Xeon(R) CPU @ 2.20GHz

GPU: With and without NVIDIA Tesla T4.

**More context**

I've been trying to set up Catboost to work with Pyspark in a Colab notebook (specifically a Kaggle integrated notebook).

As a starting point I've pip installed pyspark 3.1 and copied the "Binary Classification" quickstart code from the (impressively detailed) [catboost documentation](https://catboost.ai/en/docs/concepts/spark-quickstart-python).

```
!pip install pyspark==3.1.2
from pyspark.sql import Row,SparkSession
from pyspark.ml.linalg import Vectors, VectorUDT
from pyspark.sql.types import *


spark = (SparkSession.builder
  .master("local[*]")
  .config("spark.jars.packages", "ai.catboost:catboost-spark_3.1_2.12:1.0.6")
  .appName("ClassifierTest")
  .getOrCreate()
)
import catboost_spark
    
srcDataSchema = [
    StructField("features", VectorUDT()),
    StructField("label", StringType())
]

trainData = [
    Row(Vectors.dense(0.1, 0.2, 0.11), "0"),
    Row(Vectors.dense(0.97, 0.82, 0.33), "1"),
    Row(Vectors.dense(0.13, 0.22, 0.23), "1"),
    Row(Vectors.dense(0.8, 0.62, 0.0), "0")
]
    
trainDf = spark.createDataFrame(spark.sparkContext.parallelize(trainData), StructType(srcDataSchema))
trainPool = catboost_spark.Pool(trainDf)
    
evalData = [
    Row(Vectors.dense(0.22, 0.33, 0.9), "1"),
    Row(Vectors.dense(0.11, 0.1, 0.21), "0"),
    Row(Vectors.dense(0.77, 0.0, 0.0), "1")
]
    
evalDf = spark.createDataFrame(spark.sparkContext.parallelize(evalData), StructType(srcDataSchema))
evalPool = catboost_spark.Pool(evalDf)
    
classifier = catboost_spark.CatBoostClassifier()
    
# train a model
model = classifier.fit(trainPool, eval_set=[evalPool])

# apply the model
predictions = model.transform(evalPool.data)
predictions.show()

# save the model
savedModelPath = "/my_models/binclass_model"
model.write().save(savedModelPath)

# save the model as a local file in CatBoost native format
savedNativeModelPath = './my_local_models/binclass_model.cbm'
model.saveNativeModel(savedNativeModelPath)


# load the model (can be used in a different Spark session)

loadedModel = catboost_spark.CatBoostClassificationModel.load(savedModelPath)

predictionsFromLoadedModel = loadedModel.transform(evalPool.data)
predictionsFromLoadedModel.show()


# load the model as a local file in CatBoost native format

loadedNativeModel = catboost_spark.CatBoostClassificationModel.loadNativeModel(savedNativeModelPath)

predictionsFromLoadedNativeModel = loadedNativeModel.transform(evalPool.data)
predictionsFromLoadedNativeModel.show()

```

When I run it, I get a few things come up. A warning which may or may not be relevant

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/conda/lib/python3.10/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

A bunch of what seem to be success printouts, another warning which might be relevant

`23/11/16 08:27:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
`
And then the error I mention in the title of this post;

```

TypeError                                 Traceback (most recent call last)
Cell In[1], line 42
     39 classifier = catboost_spark.CatBoostClassifier()
     41 # train a model
---> 42 model = classifier.fit(trainPool, eval_set=[evalPool])
     44 # apply the model
     45 predictions = model.transform(evalPool.data)

TypeError: CatBoostClassifier.fit() got an unexpected keyword argument 'eval_set'
```

**Comment by Robin-Lord** [comment]
Turns out it'll accept

model = classifier.fit(trainPool, evalDatasets=[evalPool])

Perhaps a version mismatch in the quickstart code, or maybe those errors meant it fell back to an earlier version? 

In any case I have a patch for now

**Comment by andrey-khropov** [comment]
> Turns out it'll accept
> 
> model = classifier.fit(trainPool, evalDatasets=[evalPool])
> 
> Perhaps a version mismatch in the quickstart code, or maybe those errors meant it fell back to an earlier version?
> 
> In any case I have a solution for now

Yes, the proper argument name is `evalDatasets`, it's a bug in the examples in documentation, I'll fix it.

By the way, prefer using the last version from [CatBoost releases](https://github.com/catboost/catboost/releases) not the version in the examples that might be outdated.
