### ISSUE TITLE
fit error

### ISSUE THREAD

**Issue by JustM57** [catboost/catboost#254]
---------------------------------------------------------------------------
CatboostError                             Traceback (most recent call last)
<ipython-input-154-774e6a4e3ba7> in <module>()
     27     eval_set=[X_test, y_test],
     28     #logging_level='Verbose',  # you can uncomment this for text output
---> 29     plot=True
     30 )
     31 

/usr/local/lib/python3.5/dist-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot)
   1471         model : CatBoost
   1472         """
-> 1473         self._fit(X, y, cat_features, None, sample_weight, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot)
   1474         if y is not None:
   1475             setattr(self, "_classes", np.unique(y))

/usr/local/lib/python3.5/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, query_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot)
    660                 raise ImportError(str(e))
    661         with log_fixup():
--> 662             self._train(X, eval_set, params)
    663         if calc_feature_importance:
    664             setattr(self, "_feature_importance", self.get_feature_importance(X))

_catboost.pyx in _catboost._CatBoostBase._train()

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatboostError: (Too many open files) util/system/file.cpp:619: can't open "/proc/3044/statm" with mode RdOnly|Seq (0x00000028)

catboost 0.6.2
stopped plotting on 1400th tree

**Comment by annaveronika** [comment]
This should be fixed now, please try building from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/

Closing the issue. Feel free to reopen, if something doesn't work for you.
