### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [catboost/catboost#2547]
Hello!

I may have found a security issue in latest version of Catboost. Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by andrey-khropov** [comment]
> Hello!
> 
> I may have found a security issue in latest version of Catboost. Following responsible disclosure, is there an email or other private channel where I could share the details? Thank you

We'll create a proper mechanism, for now you can write to me personally in a secret chat on Telegram (@A\*\*\*ei_Kh\*\*\*ov - replace * with the proper letters)

**Comment by andrey-khropov** [comment]
We've added a security policy in https://github.com/catboost/catboost/commit/0033be6355f5ab112a72e506206ff04bc4021164
