### ISSUE TITLE
catboost on spark an error occurred:java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by 18811528836** [catboost/catboost#2552]
Problem:
catboost version:catboost-spark_3.1_2.12 1.2.2
Operating System:scala spark
CPU:None
GPU:None
An error occurred during the prediction phase：java.lang.OutOfMemoryError: Java heap space.
The amount of data is 2 billion,However, when the amount of data is reduced to millions, it runs normally

**Comment by andrey-khropov** [comment]
What is your cluster configuration? How much memory on cluster hosts is reserved for JVMs?

**Comment by andrey-khropov** [comment]
No info provided for a long time, I'm closing this issue. Feel free to reopen with additional information.
