### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by pashna** [catboost/catboost#256]
I found that if during the training process eval_set is used then deserialization doesn't work (both with pickle and sklearn.externals.joblib). I'm using the latest (0.6.1.1) version of catboost.

Stacktrace:
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py in load_build(self)
   1505         setstate = getattr(inst, “__setstate__“, None)
   1506         if setstate is not None:
-> 1507             setstate(state)
   1508             return
   1509         slotstate = None
_catboost.pyx in _catboost._CatBoostBase.__setstate__()
_catboost.pyx in _catboost._CatBoostBase._set_test_eval()
_catboost.pyx in _catboost._CatBoost._set_test_eval()
_catboost.pyx in _catboost._CatBoost._set_test_eval()
TypeError: ‘float’ object is not iterable

**Comment by annaveronika** [comment]
I think it's the same problem as #173 
Closing as duplicate. Adding a help_wanted label.
