### ISSUE TITLE
Support loading from snapshot for models with categorical features

### ISSUE THREAD

**Issue by fingoldo** [catboost/catboost#2561]
Problem:
catboost version:
1.2.2
Operating System:
Windows

```python
model = CatBoostClassifier()
model.load_model("catboost_info/last_catboost_snapshot.dat", format="CpuSnapshot")
```

> CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/model_import_snapshot.cpp:25: Can't load model trained on dataset with categorical features from snapshot

**Comment by ek-ak** [comment]
Hello!
Snapshot files are not supposed to be used as a full-fledged model, they have not enough information inside. You need to finish training process to obtain full model, that have all required information (and their size is much larger).  If you decided to interrupt the training earlier, you can decrease iterations value, when you continue training from snapshot.
