### ISSUE TITLE
how to use catboost.Pool and multiple labels for training?

### ISSUE THREAD

**Issue by wht0948** [catboost/catboost#2562]
I now have a training data and multiple labels, and I need to train a model for each label.

I currently use the following method:
m1.fit(train, label1)
m2.fit(train, label2)
m3.fit(train, label3)

I hope to speed up the training in the following way:
train_pool = Pool(train)
m1.fit(train_pool , label1)
m2.fit(train_pool , label2)
m3.fit(train_pool , label3)

The above code will report an error because label cannot be entered if the input training dataset type is catboost.Pool.

I want to know how to define a pool to train multiple labels.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @wht0948 ❤️ 
here is an example https://github.com/catboost/catboost/blob/7e62840c08b640da37b7b608f0f57f35514c8793/catboost/python-package/ut/medium/test.py#L351

**Comment by wht0948** [comment]
> hi @wht0948 ❤️ here is an example
> 
> https://github.com/catboost/catboost/blob/7e62840c08b640da37b7b608f0f57f35514c8793/catboost/python-package/ut/medium/test.py#L351

I need to train multiple models, each model outputs a prediction.  this example here can only be used for RMSE, but cannot be used for other loss.
The current situation is that each model needs to re-initialize the pool, which is slow and takes up memory.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
in general case there is no good solution because target is used to digitize categories, texts, and embeddings

technically, it's possible to edit target column in a catboost.Pool if all columns are numeric
this is not implemented though

**Comment by andrey-khropov** [comment]
> The current situation is that each model needs to re-initialize the pool, which is slow and takes up memory.

Actually, if you create an CatBoost-friendly features data layout (like pandas DataFrame or numpy.ndarray with data in 'F' order) Pool creation time should be very fast (and it won't require additional memory for features storage, only for the label, which takes much less space as it is only one or maximum a few columns compared to many features), see the discussion here: https://github.com/catboost/catboost/issues/2542 .

**Comment by wht0948** [comment]
> > The current situation is that each model needs to re-initialize the pool, which is slow and takes up memory.
> 
> Actually, if you create an CatBoost-friendly features data layout (like pandas DataFrame or numpy.ndarray with data in 'F' order) Pool creation time should be very fast (and it won't require additional memory for features storage, only for the label, which takes much less space as it is only one or maximum a few columns compared to many features), see the discussion here: #2542 .
> 
> P.S. But this works optimally if all or most of your features are numerical, other feature types require additional preprocessing.

Thanks, this is useful
