### ISSUE TITLE
How to use two labels, one to calculate the split point and one to calculate the score？

### ISSUE THREAD

**Issue by wht0948** [catboost/catboost#2569]
I now have two labels A and B. I hope to use label A to train the tree model, but the final tree model outputs label B. In other words, one label is used to calculate the split gain, and the other label is used to calculate the score of the sample in the leaf node. , is there a way to achieve it?

Corresponding to deep learning, it is to fix the parameters of a model and only train a linear layer to predict new tasks.

**Comment by ek-ak** [comment]
Hello! There is no api to solve this problem in an elegant way cause this method is not well suited for ensembles of decision trees. The time difference to get a completely new model compared to recalculating the values in the leaves is not so big, and the quality is much higher.
If for some particular reason you want model that differs only in leaf values - you can change leaves values yourself  in JSON model format.
