### ISSUE TITLE
Capstone @ Washington State University 

### ISSUE THREAD

**Issue by karasjoh000** [catboost/catboost#257]
Hi, 

I will have a capstone project at Washington State University where I need to work for a company to implement a software for my learning experience. I did not find any contact for the MIR @ yandex so I just opened this as an issue. I am interested in machine learning, will there be an opportunity at yandex? Attached is the capstone project details. 

John Karasev
Computer Science Student at Washington State University Vancouver
[Capstone_RFP_2017.pdf](https://github.com/catboost/catboost/files/1735805/Capstone_RFP_2017.pdf)

**Comment by annaveronika** [comment]
Hi, please write to ml_yandex@yandex-team.ru
