### ISSUE TITLE
TypeError: argument of type 'Pool' is not iterable

### ISSUE THREAD

**Issue by xiechenhao** [catboost/catboost#259]
kaggle_titanic_catboost_demo
when running this cell 
cv_data = cv(
    model.get_params(),
    Pool(X, label=y, cat_features=categorical_features_indices),
)
raise this  TypeError: argument of type 'Pool' is not iterable
![default](https://user-images.githubusercontent.com/32444357/36515773-fa76caee-17b5-11e8-95ba-13186092422c.JPG)

**Comment by annaveronika** [comment]
Please, change parameter order, first pool, then params.

**Comment by nursnaaz** [comment]
Thanks, @annaveronika. It worked for me.
