### ISSUE TITLE
Incorrect Documentation in algorithm-main-stages_bootstrap-options.md

### ISSUE THREAD

**Issue by crn4tt** [catboost/catboost#2598]
Problem: One place in the documentation (![here](https://github.com/catboost/catboost/blob/master/catboost/docs/en/concepts/algorithm-main-stages_bootstrap-options.md?plain=1#L23)) says "only GPU support", another (![here](https://github.com/catboost/catboost/blob/master/catboost/docs/en/concepts/algorithm-main-stages_bootstrap-options.md?plain=1#L85)) says "only CPU support".

![изображение](https://github.com/catboost/catboost/assets/74592714/8c77e033-067a-4e38-9b9a-ae379adcc0c1)

![изображение](https://github.com/catboost/catboost/assets/74592714/e249b4ad-14fc-4597-8f0e-6403cf483716)

**Comment by andrey-khropov** [comment]
Actually, MVS is now supported on both CPU and GPU, I've corrected the documentation in https://github.com/catboost/catboost/commit/3240993aef906a4824e685d04c270a1fbfe13f5e
