### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by cliverenwood** [catboost/catboost#2599]
Problem: Trying to run freqtrade ai via freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor --strategy-path freqtrade/templates
catboost version: unknown
Operating System: Ubuntu 22.04.4 LTS

I am trying to run the freqtrade ai and i am facing the "Illegal Instruction" error. Full text:
freqtrade.plugins.pairlistmanager - INFO - Whitelist with 2 pairs: ['1INCH/USDT:USDT', 'ALGO/USDT:USDT']
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)

I checked the kernel log and saw:
kernel: traps: freqtrade[7586] trap invalid opcode ip:7f4f02415979 sp:7ffdb51aa910 error:0 in _catboost.so[7f4f016a9000+1985000]

How to fix this? Import in python console would show the same.

**Comment by andrey-khropov** [comment]
- What CatBoost version are you using?
- What CPU do you run it on?

**Comment by cliverenwood** [comment]
Is there a way to find out the version without python console? Because i get the sam3 error when i try there. 

Processor: Intel(R) Core(TM)2 Duo CPU P8600 @ 2.40GHz
