### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by uns1** [catboost/catboost#260]
When I import CatBoostClassifier from catboost in Python, I get this error:

> Segmentation fault (core dumped)

I'm running it on the following set up:

> OS : Ubuntu 16.04.4 LTS
> Python Version : Python 3.5.2
> CatBoost Version : 0.6.2

I used pip to install catboost and everything went fine in the installation process.

**Comment by Ilwapoi** [comment]
hi @uns1 , in my case (https://github.com/catboost/catboost/issues/233) i decided this problem with compile wheep-package on local machine and install from self-constructed wheel package after.
May be it willusefull for you.
