### ISSUE TITLE
Upgrade scikit-learn 1.4.0 to 1.4.1

### ISSUE THREAD

**Issue by celestinoxp** [catboost/catboost#2600]
Problem: scikit-learn have a critical bug (https://github.com/scikit-learn/scikit-learn/pull/28241)
catboost version: latest
Operating System: n/a
CPU: n/a
GPU: n/a

In contrib folder you have scikit-learn 1.4.0, you should update to 1.4.1

**Comment by andrey-khropov** [comment]
Thank you for bringing this to our attention. However, if you use CatBoost the version of `scikit-learn` installed in your python environment will be used (if needed).`scikit-learn` version in contrib is used only for tests internally.

**Comment by celestinoxp** [comment]
@andrey-khropov I understood. I made a pull-request in pycaret where the tests failed due to the scikit-learn bug, so it is likely that your tests may fail due to this problem... after upgrading from 1.4.0 to 1.4.1 all tests have passed... I hope I have helped to make your work easier...
