### ISSUE TITLE
TypeError: expected bytes, str found using eval_metric

### ISSUE THREAD

**Issue by Justin-Tan** [catboost/catboost#261]
Using the Pool input format with input Pandas dataframes:
```
    pool_train = catboost.Pool(df_X_train, label=df_y_train, feature_names=df_X_train.columns.tolist())
    pool_test = catboost.Pool(df_X_test, label=df_y_test, feature_names=df_X_test.columns.tolist())
    model = catboost.CatBoostClassifier(**hyp_params)
    model.fit(pool_train, eval_set=pool_test)
    eval_metrics = ['AUC']
    train_metrics = model.eval_metrics(pool_train, metrics=eval_metrics)
    test_metrics = model.eval_metrics(pool_test, metrics=eval_metrics)
```
Everything works until attempting to retrieve the eval metrics on the test dataset, when I get the following error:

```
    train_metrics = model.eval_metrics(pool_train, metrics=eval_metrics)
  File "/home/jtan/anaconda3/envs/cats/lib/python3.6/site-packages/catboost/core.py", line 916, in eval_metrics
    return self._eval_metrics(data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
  File "/home/jtan/anaconda3/envs/cats/lib/python3.6/site-packages/catboost/core.py", line 878, in _eval_metrics
    metrics_score = self._base_eval_metrics(data, metrics, ntree_start, ntree_end, eval_period, thread_count, tmp_dir)
  File "_catboost.pyx", line 1076, in _catboost._CatBoostBase._base_eval_metrics
  File "_catboost.pyx", line 908, in _catboost._CatBoost._base_eval_metrics
  File "_catboost.pyx", line 912, in _catboost._CatBoost._base_eval_metrics
TypeError: expected bytes, str found
```

I use Catboost 0.6.2 and Python 3.6.4.

**Comment by sairajreddy** [comment]
Hi, though I don't have direct answer or solution to your problem -- I can suggest an alternative. 
Use sklearn's metrics method to serve the purpose. 

Surprisingly Catboost tutorials don't include eval_metrics(), they used sklearn _metrics_ . 
Check out an example from official Catboost Tutorials : https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_base_functions.ipynb

**Comment by shiquanwang** [comment]
I tried using b'AUC' to get `eval_metrics` working then get the error message:
`_catboost.CatboostError: Invalid metric type: must be string().`

**Comment by annaveronika** [comment]
@shiquanwang It seems to me like a different problem. Could you please create a new issue and provide the code that you are running and library version?

**Comment by sairajreddy** [comment]
@annaveronika Could you please look into the issue in this thread? Catboost's `eval_metrics()` method seems to be buggy. 

Also, will be happy if you could provide usage examples of `eval_metrics()` in the tutorial. Thanks!

**Comment by annaveronika** [comment]
The fix is on github, could you please check if it works now for you? To do that you need to build from source (https://tech.yandex.com/catboost/doc/dg/concepts/python-installation-docpage/)

**Comment by annaveronika** [comment]
This is now on pypi in version 0.7

**Comment by annaveronika** [comment]
I'm closing the issue, please reopen if something is not working.
