### ISSUE TITLE
Error: catboost metric [MultiLogloss] and loss [HammingLoss] are incompatible

### ISSUE THREAD

**Issue by oliver-seliom** [catboost/catboost#2610]
**Problem**: 

I get the following error when trying multi-class following the tutorial: https://github.com/catboost/tutorials/blob/master/classification/multilabel_classification_tutorial.ipynb

_catboost metric [MultiLogloss] and loss [HammingLoss] are incompatible_

**This error only occurs when training with GPU**, not sure why training with CPU is ok.

```python
clf = CatBoostClassifier(
    loss_function='MultiLogloss',
    eval_metric='HammingLoss',
    iterations=500,
    class_names=Y_train.columns.tolist(),
    task_type='GPU',
    devices='0:1',
)
clf.fit(train_pool, eval_set=test_pool, metric_period=1, verbose=1)
```
catboost version: latest
Operating System: Linux
GPU: T4

**Comment by andrey-khropov** [comment]
[HammingLoss is not currently supported on GPU](https://catboost.ai/en/docs/concepts/loss-functions-multilabel-classification#usage-information), we'll improve an error message, though.
