### ISSUE TITLE
Typo in docstring of Python package catboost.CatBoostRegressor.grid_search()

### ISSUE THREAD

**Issue by monirsc** [catboost/catboost#2614]
In the docstring of the Python package version of `catboost.CatBoostRegressor.grid_search()`, the second sentence says `Aafter calling this method model is fitted and can be used, if not specified otherwise (refit=False).`. The typo is found in the word `Aafter` which should be `After`.

catboost version: 1.2.3

**Comment by andrey-khropov** [comment]
Thanks, fixed. Actually if you don't mind [signing the CLA](https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md) you can easily [create PRs for such small fixes right from the GitHub web interface](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository).
