### ISSUE TITLE
Get all candidate splits for catboosttregressor

### ISSUE THREAD

**Issue by ZexuanSun** [catboost/catboost#2616]
Problem: Hi, could you please tell me how to get access to all the candidate splits for the catboostregressor? I need them to do some calculations. I checked the source code, but I think I could not find them. In the Quantization section of your documentation, you said that we can set different methods to calculate the splits. I could not find which parameter to set, either. Thanks.
catboost version:
Operating System:
CPU:
GPU:

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi @ZexuanSun!

The vector of splits for symmeric trees on cpu is created here
https://github.com/catboost/catboost/blob/eae61e3bc36329d7169260c8a6bf10a6f7bb164e/catboost/private/libs/algo/greedy_tensor_search.cpp#L1185

Regarding the second question:

calculation of quantization borders is controlled by feature_border_type parameter
https://catboost.ai/en/docs/references/training-parameters/quantization#feature_border_type

you may specify it for each feature independently with per_float_feature_quantization
https://catboost.ai/en/docs/references/training-parameters/quantization#per_float_feature_quantization

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Should you have more questions, please reopen this issue, or create a new one ❤️
