### ISSUE TITLE
visualization in jupyter lab error

### ISSUE THREAD

**Issue by jermaine1ronquillo** [catboost/catboost#262]
I got the following error running catboost in Jupyter Lab
"Failed to display Jupyter Widget of type CatboostIpythonWidget."

**Comment by newbfg** [comment]
What ipywidgets and catboost version do you have?
Could you open a browser console and check for errors please? Cmd+shift+i (or ctrl+shift+i)

**Comment by jermaine1ronquillo** [comment]
This is the error from Jupyter Lab
"
Failed to display Jupyter Widget of type CatboostIpythonWidget.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.
"

versions:
catboost                  0.6.1                     <pip>
ipywidgets                7.1.1                    py36_0  


error on console:
"Error: Object 'jupyter.widget' not found in registry"

**Comment by newbfg** [comment]
I need to check jupyter lab compatibility

**Comment by herbzhao** [comment]
I had the same error:
My jupyterlab and catboost are all freshly installed. 
```Failed to display Jupyter Widget of type MetricVisualizer.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.```

**Comment by mcgbride** [comment]
Same issue for me: I get a 'Error displaying widget'
Config:
   jupyterlab 0.31.12
   catboost 0.7.2.3
   ipywidgets 7.0.5

Things I've already tried:
1. from console before launching Jupyter lab:
> jupyter nbextension enable --py widgetsnbextension

2. Added various imports:
   from __future__ import print_function
   from ipywidgets import interact, interactive, fixed, interact_manual
   import ipywidgets as widgets
   from IPython.display import display

Neither of these display the widget. I always get the same error: 'Error displaying widget'

BTW, I installed catboost into my python 3.6 conda install, using pip. However, the notebook I'm using, from here:
   https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_python_tutorial.ipynb

was using a Python2 kernel. I'm trying to adapt it to Python3, which may be at the root of the issue. 

Thanks for any insight!

**Comment by herbzhao** [comment]
I think the jupyterlab is probably the issue here, as it is still fairly new thing. My experience with plotly was the same that Jupyterlab won't work with it. However, there is a renderer you can install to display the image. https://github.com/jupyterlab/jupyter-renderers 

I have installed the plotly one, which I believe is what behind catboost's visualisation, so far no luck in displaying the figure

**Comment by mcgbride** [comment]
@herbzhao - Thank you so much for your response. I'll try out the renderer you suggest.

**Comment by LeData** [comment]
Javascript widgets were purposefully made unavailable in Jupyter lab. From Jupyter Lab's Github:
https://github.com/jupyterlab/jupyterlab/issues/3748

Yandex would have to write a jupyter lab extension. Still works in jupyter notebooks though.

**Comment by pccampbell** [comment]
Was this closed because you decided not to create the Jupyter Lab extension or for some other reason. Was fairly confusing trying to diagnose this error.

**Comment by mcgbride** [comment]
I believe that the problem was that Jupyter lab couldn’t / wouldn’t execute
javascript widgets. I did not close the issue — it’s outstanding, I believe
— but I was able to get the plugin to work using Jupyter ‘classic’. Thanks!

- Gary

**Comment by pccampbell** [comment]
Looks like Anna closed the issue to me, not a huge deal. Gotcha I guess I'm misunderstanding something. To me it sounded like Lab can run doesn't directly support in-line JS, but if you wanted to create a custom JS widget that works in lab you would create a jupyter lab extension for it. Not sure what the scope of porting it to an extension is.

**Comment by mcgbride** [comment]
Thanks again for the follow up, Peter. I don’t intend to write a custom JS
widget for this; my need for the functionality expired a few months ago. I
hope someone does, though, in the future, as it’s a pretty cool widget, and
I think the Jupyter community is moving toward Lab as the de facto standard.

Cheers,
Gary

**Comment by newbfg** [comment]
Hi! There is no possibility to create third-party widgets in jupyterlab yet.
We need `ipywidgets` to do that - https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#the-ipywidgets-third-party-extension.
Current status `Note: The ipywidgets third party extension has not yet been released.`

**Comment by annaveronika** [comment]
It looks like JupyterLab just made a 1.0 release, and it might be possible to create third-party widges there.
We'll look into this.

**Comment by funkindy** [comment]
@annaveronika any updates on this? Would be really great to get plotting works in jlab.

**Comment by annaveronika** [comment]
We are not working on that, we would very much appreciate any help!

**Comment by Installka** [comment]
ipywidgets have JupyterLab extension now - https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension. Maybe it will help to start working on it?)

**Comment by david-waterworth** [comment]
Any progress on this, I'm using the python extension for vscode and it would be nice to get catboost plotting to work with it?

**Comment by JeroenSchmidt** [comment]
> ipywidgets have JupyterLab extension now - https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension. Maybe it will help to start working on it?)

It does not appear to work for me

**Comment by data-RanDan** [comment]
any updates?

**Comment by DMS-999** [comment]
... no updates... no solutions... sad

**Comment by OfficerChul** [comment]
here is February 2024, any updates here?

**Comment by andrey-khropov** [comment]
> here is February 2024, any updates here?

If you use CatBoost >= 1.2.1 it should work, do you still have problems?

**Comment by OfficerChul** [comment]
> > here is February 2024, any updates here?
> 
> If you use CatBoost >= 1.2.1 it should work, do you still have problems?

For catboost, I am using `1.2.2`, for ipywidgets, I am using `7.7.2`, for jupyter lab, I am using `4.0.9`

**Comment by cleemesser** [comment]
> > > here is February 2024, any updates here?
> > 
> > 
> > If you use CatBoost >= 1.2.1 it should work, do you still have problems?
> 
> For catboost, I am using `1.2.2`, for ipywidgets, I am using `7.7.2`, for jupyter lab, I am using `4.0.9`

Just to bump this:  I see catboost visualization working in vscode's notebook implementation, but not in jupyterlab 4.x 
The documentation says that this is a [known issue] (https://github.com/catboost/catboost/issues/2533).  I see the same thing.
```
catboost.__version__
'1.2.5'
ipywidgets.__version__
'8.1.3'
```
```
jupyter --version
Selected Jupyter core packages...
IPython          : 8.22.2
ipykernel        : 6.29.3
ipywidgets       : 8.1.2
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.14.0
jupyterlab       : 4.1.6
nbclient         : 0.10.0
nbconvert        : 7.16.3
nbformat         : 5.10.4
```
