### ISSUE TITLE
Python package--build from source failed

### ISSUE THREAD

**Issue by ccylance** [catboost/catboost#2621]
Problem: build from source failed
Catboost version: latest source code
Operating System: OS 14.0
CPU: Apple M1 Pro

I downloaded the latest code from GitHub and prepared to build the Python Whl package according to the official website instructions, but it showed an error. 

![image](https://github.com/catboost/catboost/assets/54780246/ea1f8365-db5e-48bd-8b9b-60a7b1b502ed)

BTW, does there exist any debug mode for catboost? Really feel confused about how the tree is built. I tried using plain mode and plot the tree structure but found that the tree is also a symmetric tree.

**Comment by andrey-khropov** [comment]
> Problem: build from source failed Catboost version: latest source code Operating System: OS 14.0 CPU: Apple M1 Pro
> 
> I downloaded the latest code from GitHub and prepared to build the Python Whl package according to the official website instructions, but it showed an error.

What is your python version, pip version and do you have `setuptools`, `wheel` and `build` python packages installed?

> 
> BTW, does there exist any debug mode for catboost? Really feel confused about how the tree is built. I tried using plain mode and plot the tree structure but found that the tree is also a symmetric tree.

You can build CatBoost from source with build type set to `Debug` either using `build_native.py` with the option [`--build-type=Debug`](https://github.com/catboost/catboost/blob/752bf2562f02e638d9bc80544390e25512b85677/build/build_native.py#L72) or by when invoking CMake directly and specifying [`CMAKE_BUILD_TYPE`](https://catboost.ai/en/docs/installation/build-native-artifacts#cmake-options-and-definitions).

If you are talking about debug mode in a sense that more additional information is output then:

- I think there are too many things and scenarios for what should be output and what not to build a some kind of universally useful debug mode. But we are open to suggestions.

- CatBoost is open source so you can modify the source code to output what is useful in your debugging case.

**Comment by ccylance** [comment]
> What is your python version, pip version and do you have setuptools, wheel and build python packages installed?
Python: 3.9.6
pip: 24.0
setuptools: 69.2.0pip
wheel: 0.37.0
build: 1.2.1

BTW, I noticed that the piror_numerator might be different in one tree of different depths. Why is this？

**Comment by ccylance** [comment]
@andrey-khropov Ok, let's continue discussing the build failure issue here.

**Comment by andrey-khropov** [comment]
> ![image](https://private-user-images.githubusercontent.com/54780246/318769183-ea1f8365-db5e-48bd-8b9b-60a7b1b502ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjg4MDcsIm5iZiI6MTcxMjEyODUwNywicGF0aCI6Ii81NDc4MDI0Ni8zMTg3NjkxODMtZWExZjgzNjUtZGI1ZS00OGJkLThiOWItNjBhN2IxYjUwMmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YWNjMWFjMzY4NmQ3NjVjYzVhMTY0ODdjNzQzZjhjODlkNDM0MDc1ZjA3YjY0NGY2ZmI0ODk0MmM4ZGJjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gWAqCPTijGNnX4mgLtVs-k2ytxyxQ9HCjm07WXZ14RI)

What revision of the the source code did you use exactly? 

Your error is reported on line 311. but this code with `user_options` [has been on line 312 for quite some time](https://github.com/catboost/catboost/blob/643f234ce40b25379f22602c0ee652c12f8f497b/catboost/python-package/setup.py#L312).

**Comment by andrey-khropov** [comment]
> I am using the latest version from git. I previously made some modifications to the code because I wanted to use GPT to fix the problem. So I pull the code again and try to compile, it showed a new error ![image](https://private-user-images.githubusercontent.com/54780246/319102107-32e42b19-c96b-4ea9-b858-196588a24ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzM2MzcsIm5iZiI6MTcxMjEzMzMzNywicGF0aCI6Ii81NDc4MDI0Ni8zMTkxMDIxMDctMzJlNDJiMTktYzk2Yi00ZWE5LWI4NTgtMTk2NTg4YTI0ZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZGUxNjhkMjM3ZjQ1YzYzNTVjYWE5NjFmNzkzMTU5MTYyNjMwNGNhMzk4YzgzMGYxZGFkMDFhNjZmYTJkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4UB3rhpH9w-hmUdLaDnzeK74qMkPUl3C5mNypf8tp1s) @andrey-khropov

This is very weird and I don't think it depends on CatBoost. Try to cleanup `.eggs` directory and run the build command again.

**Comment by ccylance** [comment]
@andrey-khropov  Python Conan dependencies works well but the build process occurred new error after cleaning .egg directory. 
![image](https://github.com/catboost/catboost/assets/54780246/601a6894-6463-4745-b332-f6ef70dd1181)

**Comment by andrey-khropov** [comment]
> @andrey-khropov Python Conan dependencies with version 2.2.3

Version of what? CatBoost does not have version 2.2.3 yet.

> works well but the build process occurred new error after cleaning .egg directory. 

It prints that the `Conan install failed`, check the messages above to get the original error during the conan packages installation.

P.S. Please insert text as text, not images, it will be easier to find, quote and copy-paste.

**Comment by ccylance** [comment]
@andrey-khropov  The source code of Catboost is the latest one pulled from GitHub. I installed Conan using pip, and the version of Conan is 2.2.3. So it's confusing why this error would occur.

**Comment by andrey-khropov** [comment]
> @andrey-khropov The source code of Catboost is the latest one pulled from GitHub. I installed Conan using pip, and the down the version of Conan to 1.62.0. But another error occured:
> 
> ```
> FAILED: util/draft/CMakeFiles/util-draft.dir/ip.cpp.o
> /usr/bin/clang++ -DCATBOOST_OPENSOURCE=yes -I../../../../ -I. -I../../../../contrib/libs/linux-headers -I../../../../contrib/libs/linux-headers/_nf -I../../../../contrib/libs/cxxsupp/libcxx/include -I../../../../contrib/libs/cxxsupp/libcxxrt/include -I../../../../contrib/libs/clang16-rt/include -fexceptions -fno-common -fcolor-diagnostics -faligned-allocation -fdebug-default-version=4 -ffunction-sections -fdata-sections -Wall -Wextra -Wno-parentheses -Wno-implicit-const-int-float-conversion -Wno-unknown-warning-option -pipe -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__LONG_LONG_SUPPORTED -D_GNU_SOURCE -DLIBCXX_BUILDING_LIBCXXRT -fuse-init-array -D_FILE_OFFSET_BITS=64 -m64 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -D_YNDX_LIBUNWIND_ENABLE_EXCEPTION_BACKTRACE -Woverloaded-virtual -Wimport-preprocessor-directive-pedantic -Wno-undefined-var-template -Wno-return-std-move -Wno-defaulted-function-deleted -Wno-pessimizing-move -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -Wno-ambiguous-reversed-operator -Wno-deprecated-volatile -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSSE3_ENABLED=1 -DSSE41_ENABLED=1 -DSSE42_ENABLED=1 -DPOPCNT_ENABLED=1 -DCX16_ENABLED=1 -fPIC -DLIBCXX_BUILDING_LIBCXXRT -nostdinc++ -D_libunwind_ -std=c++2a -MD -MT util/draft/CMakeFiles/util-draft.dir/ip.cpp.o -MF util/draft/CMakeFiles/util-draft.dir/ip.cpp.o.d -o util/draft/CMakeFiles/util-draft.dir/ip.cpp.o -c ../../../../util/draft/ip.cpp
> clang: error: unknown argument: '-fdebug-default-version=4'
> ```

That means that your `clang` version is very old. ['-fdebug-default-version' argument is supported since clang 10.x](https://github.com/llvm/llvm-project/commit/8d8f9c24407461fadf1730e80ebcf7c767254715).

[CatBoost requires newer `clang` versions to build](https://catboost.ai/en/docs/installation/build-environment-setup-for-cmake#compilers,-linkers-and-related-tools).
