### ISSUE TITLE
Different Between PairLogitPairwise and PairLogit and Impact on Categorical Values

### ISSUE THREAD

**Issue by ManRev** [catboost/catboost#2625]
### Discussed in https://github.com/catboost/catboost/discussions/2624

<div type='discussions-op-text'>

<sup>Originally posted by **ManRev** April  3, 2024</sup>
I have binary variables only and use two models:

pool = Pool(X, y, cat_features=cat_features, group_id=group_id)
model1 = CatBoostRanker(eval_metric="**PairLogit**", pool... ) and model2 = CatBoostRanker(eval_metric="**PairLogitPairwise**", pool... )

- model1 provides a tree that looks normal (a node is for instance [Xi = 0]). 
- model2, however, behaves very weirdly. A node is, for instance [{Xi} counter_type=Counter prior_numerator=0, value>10].

It seems that model2 turns all the variables into numerical variables. But even that doesn't make any sense: the value of Xi is 0 or 1, why is the node displaying e.g., value>10?

Could you explain me what is happening?</div>

**Comment by andrey-khropov** [comment]
You likely meant `loss_function`, not `eval_metric` here. If that is the case it works as expected:

Categorical features can be treated as either:
 * 'one-hot' - that means all splits will just compare the value of the feature with some constant
 * 'ctrs' - that means special statistics will be computed that will then be used as numerical features (see https://catboost.ai/en/docs/concepts/algorithm-main-stages_cat-to-numberic ). 

Which mode will be selected for a particular categorical feature depends on its cardinality and other factors that are described here:

https://catboost.ai/en/docs/features/categorical-features

It is stated there that:

> The following loss functions use Pairwise scoring:

>   - YetiRankPairwise
>   - **PairLogitPairwise**
>   - QueryCrossEntropy

> Pairwise scoring is slightly different from regular training on pairs, since pairs are generated only internally during the training for the corresponding metrics. **One-hot encoding is not available for these loss functions.**

So, for `loss_function='PairLogitPairwise'` all categorical features will be processed using `ctr` statistics. For `PairLogit` on the other hand usual logic with `one_hot_max_size` is used and for Ranking it means all categorical features with a cardinality (number of unique values) of 10 or less will be processed as one-hot (unless you change this parameter from its default value, of course).

 > the value of Xi is 0 or 1, why is the node displaying e.g., value>10
 
 `ctr` statistics can have different values distributions compared to original values of the categorical feature, so such thresholds are possible. 

 P.S.

```
pool = Pool(X, y, cat_features=cat_features, group_id=group_id)
model1 = CatBoostRanker(eval_metric="PairLogit", pool... ) and model2 = CatBoostRanker(eval_metric="PairLogitPairwise", pool... )
```

What you are writing here won't work as `CatBoostRanker` cannot accept datasets in its constructor, only `fit` function does.
