### ISSUE TITLE
C++ standalone evaluator multiclass support

### ISSUE THREAD

**Issue by izaac-s** [catboost/catboost#2638]
Problem: Dear Catboost experts, from what I can tell, the C++ standalone evaluator does not support multiclass models. I looked into adding support myself, but I think since the current implementation allows only one value per leaf, it does not seem possible. Is there a way to do this for the C++ standalone evaluator? Many thanks
catboost version:
Operating System:
CPU:
GPU:

**Comment by andrey-khropov** [comment]
Usage of standalone evaluator is not recommended and new features like multiclass support won't be added to it. Please use either [C/C++ evaluation library](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper) or [model exported as C++ code](https://catboost.ai/en/docs/concepts/c-plus-plus-api_applycatboostmodel). Both of them support multiclassification model. 

P.S. In the documentation of [model exported as C++ code](https://catboost.ai/en/docs/concepts/c-plus-plus-api_applycatboostmodel) it says that multiclassification models are not supported, but this is outdated information that will be fixed soon.
