### ISSUE TITLE
Documentation: broken links

### ISSUE THREAD

**Issue by ibobak** [catboost/catboost#2642]
On this site https://catboost.ai/en/concepts/algorithm-main-stages

There are two links:
[Choosing the tree structure](https://catboost.ai/en/concepts/algorithm-main-stages_choose-tree-structure). This stage is affected by the set [Bootstrap options](https://catboost.ai/en/concepts/algorithm-main-stages_bootstrap-options).

Both are producing 404 not found page
![image](https://github.com/catboost/catboost/assets/8807043/cb3faa3a-3226-45fd-96fa-28753fd90dea)

**Comment by andrey-khropov** [comment]
How do you get these links?

There are no pages 
https://catboost.ai/en/concepts/algorithm-main-stages, 
https://catboost.ai/en/concepts/algorithm-main-stages_choose-tree-structure, 
https://catboost.ai/en/concepts/algorithm-main-stages_bootstrap-options 
indeed. But that's expected.

The correct addresses contain `/docs/` part in the urls and they work:

https://catboost.ai/en/docs/concepts/algorithm-main-stages ,
https://catboost.ai/en/docs/concepts/algorithm-main-stages_choose-tree-structure , 
https://catboost.ai/en/docs/concepts/algorithm-main-stages_bootstrap-options

**Comment by andrey-khropov** [comment]
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.
