### ISSUE TITLE
Problem with eval_set in CatBoostRegressor

### ISSUE THREAD

**Issue by selkurdy** [catboost/catboost#265]
I am getting an error when using eval_set,
  File "C:\Users\Sami\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\catboost\core.py", line 1529, in __init__
    super(CatBoostRegressor, self).__init__(params)
  File "C:\Users\Sami\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\catboost\core.py", line 483, in __init__
    self._check_params(params)
  File "C:\Users\Sami\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\catboost\core.py", line 515, in _check_params
    raise CatboostError("Invalid param `{}`.".format(param))
_catboost.CatboostError: Invalid param `eval_set`.

The code that generated this is:
        Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=42)  
        evalset = (Xtest,ytest)
        model = CatBoostRegressor(iterations=cmdliterations, 
                                learning_rate= cmdllearningrate, 
                                depth=cmdldepth,
                                loss_function= 'RMSE',
                                use_best_model=True,
                                od_type = 'IncToDec',
                                od_pval = cmdlodpval,
                                eval_metric = 'RMSE',
                                eval_set = evalset,
                                random_seed=42)

**Comment by Noxoomo** [comment]
You should pass eval_set to fit function, not to CatBoostRegressor constructor
