### ISSUE TITLE
R: Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by grayskripko** [catboost/catboost#2658]
Problem:
According to the docs, I use

```
install.packages('remotes')
remotes::install_github('catboost/catboost', subdir = 'catboost/R-package')
```

My output
```
* installing *binary* package ‘remotes’ ...
* DONE (remotes)
The downloaded source packages are in
    ‘/tmp/RtmpYLzrYI/downloaded_packages’
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/catboost/catboost/contents/catboost/R-package/DESCRIPTION?ref=HEAD'
Execution halted
```

I expected this approach should work in a clean docker build. What could I miss? Or do you have any reference to catboost in R dockerfile?

catboost version:  the latest
Operating System: linux 
CPU: I use aws codebuilder. I don't think this value is relevant
GPU: -

**Comment by andrey-khropov** [comment]
Looks like a network connectivity issue.

Does a direct request of `https://api.github.com/repos/catboost/catboost/contents/catboost/R-package/DESCRIPTION?ref=HEAD` (for example, using `wget` or `curl`) works from your docker build?

**Comment by grayskripko** [comment]
There is a limit like 60 unauthorized requests from one IP to github. Seems Aws Codebuilder reaches this limit that's why `remotes::install_github` won't work until you add `GITHUB_PAT` system variable to the codebuilder project. Then I had to pass the variable to the build adding these two lines to the Dockerfile

```
ARG GITHUB_PAT
ENV GITHUB_PAT=$GITHUB_PAT
```
