### ISSUE TITLE
Jupyter Notebook Kernel died after CatBoostRegressor().fit(X_train, y_train) starts

### ISSUE THREAD

**Issue by DmitryKravchuk1991** [catboost/catboost#267]
I have installed catboost 1.1.3 using pip on Windows Server 2012 today and tryed to check CatBoostRegressor:

from catboost import CatBoostRegressor

model = CatBoostRegressor()
model.fit(X_train, y_train)

I have run it in Jupyter Notebook and kernel died. Also i have tryed to run it from cosole as a .py script and got another error, but kernel did not die this way.

What should i do to make possible use catboost from Jupyter Notebook?

**Comment by annaveronika** [comment]
I don't think we have version 1.1.3, but it sounds like you are using some old version. Could you try 0.6.2 from pypi?

**Comment by kizill** [comment]
Sorry, but why are you using such an old version? We had fixed LOTS of bug since 0.1.1.3

**Comment by DmitryKravchuk1991** [comment]
Yeap - i've installed 0.6.2 version from pypi - https://pypi.python.org/pypi/catboost/0.6.2
It' strange but conda list showed me catboost 1.1.3 as info about package. So it's still failing in jupyter notebook...

**Comment by DmitryKravchuk1991** [comment]
I have checked out version - it is 0.6.2 as you said. Conda list command show it as 0.1.1.3 after pip installation. So kernel crushs anyway.

**Comment by DmitryKravchuk1991** [comment]
It goes well after reinstall - thanks for patience.
