### ISSUE TITLE
Tests are failing for catboost python-package component.

### ISSUE THREAD

**Issue by Pratikt2312** [catboost/catboost#2672]
Problem: Tests for catboost python-package are failing with following error 
```
[root@ab22f3d881da medium]# python3 -m pytest
==================================================================== test session starts ====================================================================
platform linux -- Python 3.11.5, pytest-8.2.0, pluggy-1.5.0
rootdir: /catboost/catboost/python-package
configfile: pyproject.toml
plugins: anyio-4.3.0
collected 0 items / 2 errors

========================================================================== ERRORS ===========================================================================
_____________________________________________________ ERROR collecting ut/medium/test_catboost_utils.py _____________________________________________________
ImportError while importing test module '/catboost/catboost/python-package/ut/medium/test_catboost_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_catboost_utils.py:3: in <module>
    from catboost_pytest_lib import test_output_path, local_canonical_file
E   ModuleNotFoundError: No module named 'catboost_pytest_lib'
__________________________________________________________ ERROR collecting ut/medium/test_whl.py ___________________________________________________________
ImportError while importing test module '/catboost/catboost/python-package/ut/medium/test_whl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_whl.py:1: in <module>
    import yatest.common
E   ModuleNotFoundError: No module named 'yatest'
================================================================== short test summary info ==================================================================
ERROR test_catboost_utils.py
ERROR test_whl.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 2 errors in 1.57s =====================================================================
```

catboost version: 1.2.2
Operating System: Red Hat Enterprise Linux 9.3 (Plow)
CPU: Power9
Architecture: ppc64le
Python-3.11.5

Additional information: I am able to built wheel for catboost (python-package)1.2.2 successfully but when I try to run test 
                                      on it in ```catboost/python-package/ut/medium```  then facing above errors. I am following 
                                      https://catboost.ai/en/docs/concepts/development-and-contributions  this document to run test on python 
                                      package.
I would like to know if there is any other test setup required to run test on python-package or I'm missing any configuration steps,
maybe if you have some clue what's going wrong here! 
Any suggestions and pointers regarding the same will be helpful.
Thanks!

**Comment by Pratikt2312** [comment]
Hi @andrey-khropov Have you had a chance to look into this issue? Please let me know if you need any additional information.

**Comment by andrey-khropov** [comment]
> Hi @andrey-khropov Have you had a chance to look into this issue? Please let me know if you need any additional information.

Sorry for the delayed response.

You are using version 1.2.2 but there were issues with tests at that moment that have been fixed in https://github.com/catboost/catboost/commit/54c447b2a0bdec28525aa67e5d63028c478dd80e. The issue with test_whl has been fixed in https://github.com/catboost/catboost/commit/3f19985790bfa002933d34e11edd322217a52417 . 

You can use revisions after these in the master branch or the last stable version (currently 1.2.5) depending on your needs.

One note: please ensure that your python installation has numpy < 2.0.x, numpy 2.0.x is not supported yet (in progress): #2671

**Comment by Pratikt2312** [comment]
Hi @andrey-khropov Can you please help?

**Comment by andrey-khropov** [comment]
> Hi @andrey-khropov Can you please help?

What do you mean exactly? I've described why tests were failing and that they are fixed now. Just use newer revisions.

**Comment by andrey-khropov** [comment]
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.
