### ISSUE TITLE
NodeJS: Crash during Model instantiation

### ISSUE THREAD

**Issue by nemphys** [catboost/catboost#2686]
Problem: 

The node process (node v20.14.0) crashes with the following error: "dyld[36861]: missing symbol called" as soon as "let model = new catboost.Model();" is called.

catboost version: 1.25.1
Operating System: macOS Sonoma 14.5 (23F79)
CPU: Apple M2 Max
GPU: Apple M2 Max

**Comment by ankur-kalita** [comment]
can you please assign this issue to me ?

**Comment by andrey-khropov** [comment]
The release 1.25.1 uses old `catboostmodel` library for the main release 0.25.1 that do not have macOS arm64 support.
New release 1.26.0 uses `catboostmodel` library from the main release 1.2.7 that does have macOS arm64 support.

Alternatively you can also build the package from sources yourself. 

https://catboost.ai/docs/en/concepts/apply-node-js#installation
