### ISSUE TITLE
Unexpected Behaviour with CatBoost AFT model

### ISSUE THREAD

**Issue by kenzeng24** [catboost/catboost#2698]
catboost version: 1.2

According to the notebook here: https://github.com/catboost/tutorials/blob/master/regression/survival.ipynb, catboost AFT models require two inputs 'y_lower and 'y_upper'. However, in the case that target is not correctly formatted, the model either produces a kernel level error "The Kernel crashed while executing code in the current cell or a previous cell." or sometimes the model actually fits. If the model expects two columns, why does it behave this way? And what does the model actually do when the y provided only contains one column? 

```python
from catboost import CatBoostRegressor
import numpy as np
import pandas as pd

event_time = np.random.exponential(scale=1, size=100)
event = np.random.randint(0, 2, size=100)
# Example data
data = pd.DataFrame({
    'feature1': np.random.randn(100),
    'feature2': np.random.randint(0, 2, size=100),
    'y_lower': event_time, 
    'y_upper': np.where(event == 1, event_time, -1) # 1 if censored, 0 if event occurred
})
# expected use case 
model = CatBoostRegressor(loss_function='SurvivalAft:dist=Normal', eval_metric='SurvivalAft',verbose=0)
model.fit(data[['feature1', 'feature2']], data[['y_lower', 'y_upper']])
predictions = model.predict(data[['feature1', 'feature2']])
```

And depending on the initialized data, sometimes the following runs and sometimes it crashes. 

```python 
# unexpected use case
model = CatBoostRegressor(loss_function='SurvivalAft:dist=Normal', eval_metric='SurvivalAft',verbose=0)
model.fit(data[['feature1', 'feature2']], data[['y_upper']])
```

**Comment by ek-ak** [comment]
Hello!
Thank you for you bug report. I failed to reproduce crash with you code: given example (`unexpected use case`) fails with error `CatBoostError: /src/catboost/catboost/private/libs/target/data_providers.cpp:551: Survival regression objective/metrics require 2-dimensional target` as it should. Maybe you can give a stable reproducer (with a fixed random state)? And please update to the latest catboost package version.

**Comment by andrey-khropov** [comment]
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.
