### ISSUE TITLE
CatBoostRegressor Cox Model Increasing Test and Train Error

### ISSUE THREAD

**Issue by marcoistasy** [catboost/catboost#2706]
I am currently training a `CatBoostRegressor `survival model using the `Cox` loss function as per this [tutorial](https://github.com/catboost/tutorials/blob/master/regression/survival.ipynb): .

However, when training my model, I keep on running into an issue in which the both the **train and test error are increasing during training** (please see the attached screenshot). This behaviour exists even if I reduce my feature space / alter it in any way. I am not sure if this is a bug in the CatBoostRegressor or user error.

My catboost version is 1.2.3 and I am training on Linux CPU.

![image](https://github.com/catboost/catboost/assets/7032741/fea250d0-b78e-4e5e-9869-907b647ee1cc)

**Comment by andrey-khropov** [comment]
Please, use the new version 1.2.5. 

There had been a number of issues regarding Cox implementation fixed in it: https://github.com/catboost/catboost/releases/tag/v1.2.5

**Comment by darentsai** [comment]
@andrey-khropov 
v1.2.5 also has an unsolved issue: https://github.com/catboost/catboost/issues/2701 for Cox loss.

**Comment by andrey-khropov** [comment]
> @andrey-khropov v1.2.5 also has an unsolved issue: #2701 for Cox loss.

As far as I understand this issue means only that the sign of the metric is negative instead of positive, other than that it should work (compared to versions <= 1.2.3).

**Comment by marcoistasy** [comment]
Upgrading did the trick! Thank you!
