### ISSUE TITLE
Allow nan's on Multilabel classification

### ISSUE THREAD

**Issue by sw33zy** [catboost/catboost#2709]
catboost version: 1.2.5
Operating System: Linux
CPU: Intel i7-9700 (8) @ 4.700GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev.

Problem: 

I was looking for something like `MultiRMSEWithMissingValues` for multilabel classification which would allow nan's on the target. I tried implementing a custom loss and metric using `MultiTargetCustomObjective` and `MultiTargetCustomMetric` but I'm getting a `CatBoostError: /src/catboost/catboost/libs/metrics/metric.cpp:6769: metric/loss-function PythonUserDefinedMultiTarget do not allows nan value on target`.

I also tried setting the weights of the nan samples to 0 like so:

```
        w = None
        if y.ndim == 2:
            w = np.where(np.isnan(y), 0, 1)
            y = np.nan_to_num(y)

        train = cb.Pool(x, y, weight=w)
```

But got `Invalid weight value type=<class 'numpy.ndarray'>: must be 1 dimensional data with int, float or long types.`
Any help is appreciated!

**Comment by andrey-khropov** [comment]
> But got Invalid weight value type=<class 'numpy.ndarray'>: must be 1 dimensional data with int, float or long types.

The error message states the cause of the problem correctly: you are trying to pass 2-dimensional `w` matrix to the `weight` argument that accepts single-dimensional array of weights for all samples. If you want to set weight of the sample to 0 if the corresponding label values for this sample contain `nan` you need to aggregate over all target columns.

**Comment by sw33zy** [comment]
I am aware of that, but what I was trying to achieve was handling cases where only some labels of the same sample are nan

**Comment by andrey-khropov** [comment]
> I am aware of that, but what I was trying to achieve was handling cases where only some labels of the same sample are `nan`

And what weight do you want for such samples?
