### ISSUE TITLE
Undefined reference to `PredictSpecificClassFlat'

### ISSUE THREAD

**Issue by bizywizy** [catboost/catboost#2715]
Problem: 
Linker fails to find `PredictSpecificClassFlat` function in libcatboostmodel library.
```c
// main.c

#include "catboost/c_api.h"

int main() {
    PredictSpecificClassFlat(NULL, 0, NULL, 0, 0, NULL, 0);
    return 0;
}
```

```Dockerfile
# Dockerfile

FROM debian

RUN apt-get update && apt-get install -y \
    wget \
    clang

RUN mkdir -p /usr/local/lib /usr/local/include/catboost

RUN wget https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel-linux-aarch64-1.2.5.so -O /usr/local/lib/libcatboostmodel.so \
    && wget https://raw.githubusercontent.com/catboost/catboost/v1.2.5/catboost/libs/model_interface/c_api.h -O /usr/local/include/catboost/c_api.h

WORKDIR /app
COPY main.c main.c

RUN clang main.c -lcatboostmodel
```

```bash
> docker build .
...
 > [7/7] RUN clang main.c -lcatboostmodel:
0.130 /usr/bin/ld: /tmp/main-4c23d9.o: in function `main':
0.130 main.c:(.text+0x30): undefined reference to `PredictSpecificClassFlat'
0.131 clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

catboost version: 1.2.5
Operating System: linux

**Comment by soysaucewaso** [comment]
Same thing happened for me on a mac with libcatboostmodel.dylib

**Comment by andrey-khropov** [comment]
> Operating System: linux

Just to clarify things.

You are running on Linux aarch64 and want to build docker image for Debian aarch64, right?

**Comment by andrey-khropov** [comment]
> Same thing happened for me on a mac with libcatboostmodel.dylib



> Same thing happened for me on a mac with libcatboostmodel.dylib

Can you be more specific and provide steps to reproduce the issue?

**Comment by bizywizy** [comment]
> > Operating System: linux
> 
> Just to clarify things.
> 
> You are running on Linux aarch64 and want to build docker image for Debian aarch64, right?

Sorry, host machine is macos 14.4.1 (m2 chip) and build docker image for debian aarch64

**Comment by soysaucewaso** [comment]
On Mac M1, ran:
wget https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.dylub -O /usr/local/lib/libcatboostmodel.dylib
wget https://raw.githubusercontent.com/catboost/catboost/v1.2.5/catboost/libs/model_interface/c_api.h -O /usr/local/include/catboost/c_api.h

Output showing that [build link](https://github.com/catboost/catboost/releases/download/v1.2.5/libcatboostmodel.dylib) doesn't implement PredictSpecificClassFlat:

waso$cat /usr/local/include/catboost/c_api.h | grep PredictSpecific
CATBOOST_API bool PredictSpecificClassFlat(
CATBOOST_API bool PredictSpecificClass(
CATBOOST_API bool PredictSpecificClassText(
CATBOOST_API bool PredictSpecificClassTextAndEmbeddings(
CATBOOST_API bool PredictSpecificClassSingle(
CATBOOST_API bool PredictSpecificClassWithHashedCatFeatures(
CATBOOST_API bool PredictSpecificClassWithHashedCatFeaturesAndTextFeatures(
CATBOOST_API bool PredictSpecificClassWithHashedCatFeaturesAndTextAndEmbeddingFeatures(
waso$nm -g /usr/local/lib/libcatboostmodel.dylib | grep PredictSpecific
00000000000942c8 T _PredictSpecificClass
0000000000094b5c T _PredictSpecificClassSingle
00000000000945a0 T _PredictSpecificClassText
0000000000094874 T _PredictSpecificClassTextAndEmbeddings
0000000000094e24 T _PredictSpecificClassWithHashedCatFeatures
0000000000095348 T _PredictSpecificClassWithHashedCatFeaturesAndTextAndEmbeddingFeatures
00000000000950bc T _PredictSpecificClassWithHashedCatFeaturesAndTextFeatures

**Comment by andrey-khropov** [comment]
Unfortunately, `PredictSpecificClassFlat` had been missing from the list of the symbols to be exported from the library. I fixed that, the prebuilt binaries will be available in the next release (unstable versions are also available from CI - https://github.com/catboost/catboost/discussions/2708), you can also build the library from source from the stable release tag but patch `calcer.exports` before building as in https://github.com/catboost/catboost/commit/bad3790ed533f78ed58ee4e33674b1c8b568cd8d
