### ISSUE TITLE
C API Thread Safety

### ISSUE THREAD

**Issue by hanky** [catboost/catboost#272]
Hi!

I didn't find any information in the official documentation on whether C API functions are thread safe.

So, is it safe to call functions like `CalcModelPrediction` on a single `ModelCalcerHandle` simultaneously from different threads?

**Comment by kizill** [comment]
Yes, C API is thread safe and all `const` methods in `TFullModel` class are also threadsafe. We will notice that in documentation, thank you!

**Comment by annaveronika** [comment]
We've written this in documentation: https://tech.yandex.com/catboost/doc/dg/concepts/c-plus-plus-api-docpage/
