### ISSUE TITLE
“Help! I encountered an error while installing the CatBoost R package for MacBook, and the installation failed. The detailed error is as follows.”

### ISSUE THREAD

**Issue by wujian-njau** [catboost/catboost#2742]
Problem:
catboost version:1.2.7
Operating System:macOS
CPU: m3
GPU:

install.packages("~/Downloads/catboost-R-darwin-universal2.tgz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  using pax extended headers
* installing *source* package ‘catboost’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
ERROR: some hard-coded temporary paths could not be fixed
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/catboost’
Warning in install.packages :
  installation of package ‘/Users/wujian/Downloads/catboost-R-darwin-universal2.tgz’ had non-zero exit status

**Comment by andrey-khropov** [comment]
This issue is described in documentation in [the 'Troubleshooting' section](https://catboost.ai/en/docs/installation/r-installation-binary-installation#troubleshooting).

Just add "--no-staged-install" option to INSTALL_opts parameter.

**Comment by wujian-njau** [comment]
> This issue is described in documentation in [the 'Troubleshooting' section](https://catboost.ai/en/docs/installation/r-installation-binary-installation#troubleshooting).
> 
> Just add "--no-staged-install" option to INSTALL_opts parameter.

thanks!!!!!
