### ISSUE TITLE
Training on GPU in python

### ISSUE THREAD

**Issue by ShixAJ** [catboost/catboost#276]
I'm trying to make Catboost train on GPU but can't make it work.
I have Cuda version 8 installed.
When I add task_type='GPU' and run it I get this error:
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    model = CatBoostClassifier(custom_loss=['Accuracy'], random_seed=42, logging_level='Silent', task_type='GPU')
  File "/usr/local/lib/python3.6/dist-packages/catboost/core.py", line 1469, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "/usr/local/lib/python3.6/dist-packages/catboost/core.py", line 533, in __init__
    super(CatBoost, self).__init__(params)
  File "_catboost.pyx", line 994, in _catboost._CatBoostBase.__init__
  File "_catboost.pyx", line 1039, in _catboost._CatBoostBase._check_train_params
_catboost.CatboostError: catboost/libs/options/json_helper.h:194: Error: change of option metrics is unimplemented for task type GPU and was not default in previous run

Can you tell me what I should do to make it work(steps I should follow...)

**Comment by annaveronika** [comment]
custom_loss=['Accuracy'] - custom_loss is not yet supported on GPU. We'll work on better error message.

If you train on GPU you can use eval_metrics with trained model to see metric values on each iteration.

**Comment by ShixAJ** [comment]
Oh thanks it fixed the current error but got another error after removing custom_loss

catboost.CatboostError: catboost/cuda/cuda_lib/cuda_base.h:271: CUDA error: no CUDA-capable device is detected 38

**Comment by Noxoomo** [comment]
1) Could you try command line version? 
2) What GPU do you use? Could you run _nvidia-smi_ and check, that GPU is available?

**Comment by ShixAJ** [comment]
nvidia-smi is giving me error.
Failed to initialize NVML: Driver/library version mismatch

sudo dmesg | grep NVRM is giving me:

NVRM: loading NVIDIA UNIX x86_64 Kernel Module  384.98  Thu Oct 26 15:16:01 PDT 2017 (using threaded interrupts)
[    8.979186] NVRM: Your system is not currently configured to drive a VGA console
[14068.923998] NVRM: API mismatch: the client has the version 384.111, but
               NVRM: this kernel module has the version 384.98.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
I think the driver on linux isn't installed correctly or something

**Comment by Noxoomo** [comment]
So, you have system issues, thats why CatBoost doesn't work
Try to install latest NVIDIA drives

**Comment by ShixAJ** [comment]
yeah I'm gonna fix the drivers.

**Comment by sab** [comment]
Closed

**Comment by meetdave06** [comment]
@annaveronika

_catboost.CatboostError: catboost/libs/options/json_helper.h:194: Error: change of option metrics is unimplemented for task type GPU and was not default in previous run

 I am also facing the same error. I am trying to use eval_metric="AUC". Also tried custom_metric="AUC". It also gave the same error.

Also can you elaborate on this ?

> If you train on GPU you can use eval_metrics with trained model to see metric values on each iteration.

**Comment by Noxoomo** [comment]
GPU version doesn't support custom metrics currently

**Comment by itcyrichy** [comment]
What about google colab? Same issue happens
