### ISSUE TITLE
Android arm64-v8 catboost native *.so

### ISSUE THREAD

**Issue by imanbingi** [catboost/catboost#2762]
Problem: 

I've been trying to cross- build the native artifact "_catboost" for android-arm64-v8 for the past 3 days.
Followed through all the instructions, got all going only to hit a dead end:
Error  ninja unknown target "_catboost".
However if I build for the host machine(x86_64) all is well.
Any help/advise is appreciated.

catboost version: 1.2.7
Operating System: Ubuntu 24.04 LTS
CPU:x86_64
GPU:

**Comment by andrey-khropov** [comment]
Only inference libraries (`catboostmodel`, `catboostmodel_static` targets) are supported for Android. Why do you want to build `_catboost` target (native library for python package) for Android? Do you want to run training on Android?

**Comment by imanbingi** [comment]
Thank you for your attention.
I needed to evaluate on android but did'nt know (catboostmodel, catboostmodel_static are for evaluation).
Successfully built catboostmodel.
