### ISSUE TITLE
Update node package

### ISSUE THREAD

**Issue by t0mstah** [catboost/catboost#2769]
Problem: Can we update the npm package to pull in latest code changes?
catboost version: 1.25.1
Operating System: MacOS
CPU:
GPU:

Need to update from 1.25.1 to 1.25.2

**Comment by t0mstah** [comment]
@andrey-khropov since it looks like you are the maintainer? Thanks!

**Comment by andrey-khropov** [comment]
I expect to release it tomorrow.
