### ISSUE TITLE
Doc links are broken

### ISSUE THREAD

**Issue by mattmills49** [catboost/catboost#2775]
Problem: When I click on Documentation from the main catboost.ai page it leads me to the following URL `https://catboost.ai/docs/en/docs/en/` where I get a 404 Error not found. This also happened to direct links to training parameters from google. I'm on Google Chrome on a VPN. 

Another example is on the python training parameters page (https://catboost.ai/en/docs/references/training-parameters/) if you click on the side bar for a specific parameter it brings you to the following URL:
`https://catboost.ai/en/docs/references/training-parameters/en/references/training-parameters/#random_strength` which is broken link. If you scroll to the parameter directly and click on the link you get the correct URL:
`https://catboost.ai/en/docs/references/training-parameters/#random_strength`. 

catboost version:
Operating System:
CPU:
GPU:

**Comment by andrey-khropov** [comment]
We're fixing this with the highest priority!

**Comment by andrey-khropov** [comment]
> I also get the same issue. I cant access to the documentation.

I've checked and I don't see problems mentioned in this issue right now. Links work.
Do you have problems accessing the whole catboost.ai website ? There is an issue #2604 about this.
