### ISSUE TITLE
Error in building Python GPU package in Windows

### ISSUE THREAD

**Issue by Mechanix12** [catboost/catboost#278]
Hi!
I try to build GPU supported package for python.
But get this error: 
C:\github_repos\catboost>ya make -r -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0" -DPYTHON_INCLUDE="/I C:/Python27/include/" -DPYTHON_LIBRARIES="C:/Python27/libs/python27.lib"
Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
Config was not generated due to errors in C:\github_repos\catboost\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\github_repos\catboost\build\ymake_conf.py", line 2247, in <module>
    main()
  File "C:\github_repos\catboost\build\ymake_conf.py", line 2240, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\github_repos\catboost\build\ymake_conf.py", line 468, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\github_repos\catboost\build\ymake_conf.py", line 582, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "C:\github_repos\catboost\build\ymake_conf.py", line 840, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe

I already have installed VS 2017, with VC++ 2017 toolkit 
![default](https://user-images.githubusercontent.com/32762250/37761902-f2b8229a-2dcb-11e8-8039-55f7cf1223eb.png)

**Comment by annaveronika** [comment]
We will update documentation soon, currently it doesn't contain all the steps.
You need to do step 7 from "build R package for windows". Let us know if it helped.

**Comment by Mechanix12** [comment]
It didn't helped, get same error.

**Comment by exprmntr** [comment]
Hello @Mechanix12 

Is cl.exe in PATH? Can you try to enable msvc toolset by [this instruction](https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx)?

**Comment by annaveronika** [comment]
@Mechanix12 Have you tried the instruction? Did it help?

**Comment by Mechanix12** [comment]
I get new error:
`Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
------- [CC] {FAILED} $(S)\catboost\cuda\cuda_lib\tasks_impl\memory_allocation.cpp
command C:\Users\mecha\.ya\tools\v3\173608136/python C:\github_repos\catboost\build\scripts\fix_msvc_output.py cl C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\mecha\.ya\build\build_root\9ls6\000005\catboost\cuda\cuda_lib\tasks_impl\memory_allocation.cpp.obj C:\github_repos\catboost\catboost\cuda\cuda_lib\tasks_impl\memory_allocation.cpp /I C:\Users\mecha\.ya\build\build_root\9ls6\000005 /I C:\github_repos\catboost /I C:\github_repos\catboost\contrib\libs\cxxsupp\libcxx\include /I C:\github_repos\catboost\contrib\libs\libf2c /nologo /Zm500 /GR /bigobj /FC /EHsc /errorReport:prompt /Zc:inline /DFAKEID=cython0_28_1_try5 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\winrt /IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\include /Ox /Ob2 /Oi /DNDEBUG /MT /Z7 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /DSSE_ENABLED=1 /DSSE2_ENABLED=1 /DSSE3_ENABLED=1 /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS -DCATBOOST_OPENSOURCE=yes -IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0/include -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_WINDOWS_KITS_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0 /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\include /DSTRICT /DNOMINMAX /DWIN32_LEAN_AND_MEAN failed with exit code 2
c:\github_repos\catboost\contrib\libs\cxxsupp\libcxx\include\limits.h(49): fatal error C1083:  уда  фай чен: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\include/limits.h: No such file or directory,
Failed`

**Comment by char256** [comment]
when i tried to add some print sentences in file ymake_conf.py, there is nothing showed in terminal, and i also tried logging.debug and sys.stderr.write, there is also nothing in terminal and log file, how can i print something to help me? thanks

**Comment by dbakshee** [comment]
Hi @Mechanix12 
Thank you for the log. 
It looks like there are issues with environment settings on your computer. Look, the compiler is taken from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe` and it would be expected to locate its header files nearby. However, it is directed to locate the headers in `/DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\include`. 

May it happen that some environment variable points to nonexistent or incomplete installation of VS at `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC` ?

**Comment by annaveronika** [comment]
We have an updatad instruction for building the package on Windows https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-windows-docpage/. Plus we now have static linkage with CUDA, so in most cases you don't need to build the package.
Does this solve your problem?
