### ISSUE TITLE
Add custom meta information fields 

### ISSUE THREAD

**Issue by antongoy** [catboost/catboost#282]
Hi, Catboost team!

We’re adopting Catboost for a production system. Catboost model is delivered as a .cbm file to production servers. Within the current setting we have to deliver additional meta information (human readable model name, model version, threshold) as a separate file alongside a .cbm file .

For coreml models there is export_parameters parameter in save_model but it has only a fixed set of fields.

Is it possible to add custom fields into the cbm model for deploy purposes?

**Comment by annaveronika** [comment]
Yes, we plan to do this. I'll update the issue with dates when decided, but it's one of the top priority plans now.
