### ISSUE TITLE
 Error in using use_cpu_ram_for_cat_features in model.fit

### ISSUE THREAD

**Issue by meetdave06** [catboost/catboost#284]
Problem: Can't use use_cpu_ram_for_cat_features in model.fit. I am trying to run it on GPU.

```
   use_cpu_ram_for_cat_features=True)
  File "/home/dolores/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 1469, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "/home/dolores/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 531, in __init__
    self._check_params(params)
  File "/home/dolores/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 563, in _check_params
    raise CatboostError("Invalid param `{}`.".format(param))
_catboost.CatboostError: Invalid param `use_cpu_ram_for_cat_features`.
```

catboost version: 0.7
Operating System: Ubuntu 14.04.1
CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
GPU : GeForce GTX 1080, Vendor: NVIDIA Corporation 8GB
Nvidia-version : NVIDIA-SMI 375.39 Driver Version :375.39
C++ : g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
Python : anaconda3 python3.6

**Comment by Noxoomo** [comment]
Hi!

This option is called  _gpu_cat_features_storage_ now, and possible values CpuPinnedMemory or GpuRam.  Plus we forgot to add it to list of known options, so python library will raise an error, fix will be on GitHub in several hours, for python-package you'll need to wait a little longer.

Documentation also will be fixed soon

**Comment by meetdave06** [comment]
@Noxoomo  Thanks for the quick response.  I have installed using pip, so I guess I will have to wait for the catboost pip package to be updated.

**Comment by meetdave06** [comment]
@Noxoomo  Thanks for the suggestion. I was training  on 50million rows with 5 categorical variables and 7 predictors. I have three Nvidia 1080 GPU with 8 GB RAM each. Still it gave segmentation fault. Will try out the steps that you suggested. Thanks

**Comment by meetdave06** [comment]
@Noxoomo Ohh great!! I will try out the option this weekend. You can close the issue.
