### ISSUE TITLE
Error in building Python GPU package in Ubuntu

### ISSUE THREAD

**Issue by Mechanix12** [catboost/catboost#287]
Get this error:
~/Documents/git_reps/catboost$ ./ya make -r -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda
Config was not generated due to errors in /home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py
Traceback (most recent call last):
  File "/home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py", line 2248, in <module>
    main()
  File "/home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py", line 2242, in main
    build.print_build()
  File "/home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py", line 514, in print_build
    self._print_other_settings(compiler)
  File "/home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py", line 612, in _print_other_settings
    python.configure_posix()
  File "/home/alexandr/Documents/git_reps/catboost/build/ymake_conf.py", line 1974, in configure_posix
    raise Exception('System non fixed python can be used only with OS_SDK=local')
Exception: System non fixed python can be used only with OS_SDK=local

**Comment by Mechanix12** [comment]
Get new error:
~/Documents/git_reps/catboost$ ./ya make -r -DUSE_SYSTEM_PYTHON=2.7 -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda
Error[-WBadFile]: in $S/contrib/python/scipy-0.18.1/scipy/stats/ya.make: cannot find source file: statlibmodule.c
Configure error (use -k to proceed)

**Comment by alexeypronkin** [comment]
Try to redownload by save as zip at github, it seems that some files in the contrib/python/scipy-0.18.1/ are lost.

**Comment by Mechanix12** [comment]
It didn’t help, same error...

**Comment by nikitxskv** [comment]
@Mechanix12 Hello!
Try to add to `-DOS_SDK=local` flag to the build command

**Comment by Mechanix12** [comment]
@nikitxskv 
Hi!
Same error:
~/Documents/git_reps/catboost-master$ ./ya make -r -DUSE_SYSTEM_PYTHON=2.7 -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda
Error[-WBadFile]: in $S/contrib/python/scipy-0.18.1/scipy/stats/ya.make: cannot find source file: statlibmodule.c
Configure error (use -k to proceed)

**Comment by Noxoomo** [comment]
Did you make CatBoost from python-package/catboost directory?

**Comment by SergeyBridge** [comment]
@Mechanix12 I had the same error:

`Exception:` System non fixed python can be used only with `OS_SDK=local`

I changed parameter  -DPYTHON_CONFIG=python3-config into -DPYTHON_CONFIG=3.6 
used make from 

`git/catboost/catboost/python-package/catboost`

and problem was due.

**Comment by Mechanix12** [comment]
@SergeyBridge  Hi!
May be i missing something, can you please provide example of full bash command?
Sorry, i newbie in Linux...
Thanks!

**Comment by SergeyBridge** [comment]
@Mechanix12 
While your parameters include -DCUDA_ROOT=/usr/local/cuda I suppose you use CUDA 
./ya make -r -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda

0. To install CUDA8+Catboost I have reinstalled Ubuntu 16.04 for ~10 times :)))))
1. Ubuntu 16.04 already has Python 2.7 AND Python 3.5.1 installed, so if you will install one or few more Python instances, you should know what you do. (By mistake I installed 5 instances of Python at one system) You do not need to install Python!
2. To install  CUDA8+catboost from source I did the following : 
-install new Ubuntu 16.04
- install NVIDIA driver for your GPU
- install CUDA8 from [here](https://developer.nvidia.com/cuda-80-ga2-download-archive)
-install the newest Anaconda, (don't install Python, it will be automatically installed by Anaconda !)
$sudo apt update
$which python
>> /home/sergey/anaconda3/bin/python
$which pip
>>/home/sergey/anaconda3/bin/pip
$pip install numpy
I'm not sure you need numpy to be installed, but I had it already installed

then strictly  follow instructions from [catboost](https://tech.yandex.com/catboost/doc/dg/concepts/python-installation-docpage/#python-installation)

Good luck!

**Comment by annaveronika** [comment]
Everything should work with the latest github version. Please try pulling the latest version and building again. I'm closing the issue, please, feel free to reopen if something doesn't work for you.
