### ISSUE TITLE
Example of target variable specification needed

### ISSUE THREAD

**Issue by aparamon** [catboost/catboost#292]
My train data is organized as csv file (with header) with many numerical feature columns and one numerical target variable column.  However, it's not clear neither from
https://tech.yandex.com/catboost/doc/dg/concepts/cli-usages-examples-docpage
nor from
https://tech.yandex.com/catboost/doc/dg/concepts/input-data_values-file-docpage/#input-data_values-file
how to specify the name of target variable column from the command line.

It would be great if an example including complete --column-description file was included in the docs.

**Comment by annaveronika** [comment]
You need to provide a cd file with description of columns. The example of the file is already in documentation. Go to Data format description -> Input data -> Column description
https://tech.yandex.com/catboost/doc/dg/concepts/input-data_column-descfile-docpage/#input-data_column-descfile

**Comment by aparamon** [comment]
Exactly: from that document it's unclear how to specify the name of target variable.
Suppose I have a csv file with 12 numerical factors *i1, i2, ..., i12* and the target variable *t*. What would be the correct specification? The document you mentioned doesn't provide a clear method of specifying the target, only the column formats.

**Comment by annaveronika** [comment]
You need to specify the column index. It's zero-based, so you will have to write
12<\t>Target<\n>
in cd file

**Comment by aparamon** [comment]
Thank you! But please check: the description of "Target" option is missing from
https://tech.yandex.com/catboost/doc/dg/concepts/input-data_column-descfile-docpage/#input-data_column-descfile

**Comment by annaveronika** [comment]
It's because "Target" is a deprecated name. You should use Label instead. Description for this is provided in docs.

**Comment by aparamon** [comment]
Hmm, I could argue that "Target" is more widely-used term than "Label", especially for regression. Could you please update the description for type Label to additionally include term Target?

**Comment by annaveronika** [comment]
I would rather have a single name for this. It's better to use the supported one, because other will probably at some point be deleted.
As for which one - both are used, but in other gbdt libraries term label is used, so we decided to go with the same interfaces.

**Comment by aparamon** [comment]
It is fine. Just adding a notion of "Target variable" in the description text for type "Label" (as a synonym), would save a bit of people's time ;-)

**Comment by annaveronika** [comment]
ok, will add this!

**Comment by diff7** [comment]
Yup, it is still confusing label / target thing, please make it clearer. I found the answer to my question in this thread, not in the official documentation.

**Comment by annaveronika** [comment]
@diff7 Sure, we'll improve the documentation. If you experience problems in documentation, please let us know. The most helpful thing would be to say what exactly in which part of documentation we should change.

**Comment by annaveronika** [comment]
We already changed documentation of Label column, not it says "The target variable (in other words, the object's label value)."

**Comment by diff7** [comment]
I am sorry, I was looking in Quick start and it was in Column descriptions.

**Comment by annaveronika** [comment]
We want to make the documentation as clear as possible. We don't always see if it is hard to find something, because we know where to find things. If you are struggling with finding some description, please think how to do it better and report to us - we will change the docs.

**Comment by annaveronika** [comment]
For now we'll update parameters of Pool constructor (description of label) and of fit (description of y).
