### ISSUE TITLE
question about c++ api

### ISSUE THREAD

**Issue by olesyaksyon** [catboost/catboost#293]
Problem: I am trying to use ready model on cpp lang. I have 1742 features. I am doing it like that:

    ModelCalcerHandle* modelHandle;
    modelHandle = ModelCalcerCreate();

    const float * descriptors = retrieval.get_descriptors(); //guaranteed 1742 array

    if (LoadFullModelFromFile(modelHandle, "./model_catboost")) {

        int *features = new int[1742];

        for (int i = 0; i < 1742; i++) {
            features[i] = i;
        }

        const int *features_const = features;

        double result[1];

        CalcModelPredictionWithHashedCatFeatures(
                modelHandle,
                1,
                &descriptors,
                1742,
                &features_const,
                1742,
                result,
                1
        );

    }

But in my model results 0 or 1 (binary classification), here I receive in result something like 1.64 or 6.74. How should I read such result? Am I doing something wrong?

catboost version: latest
Operating System: Ubuntu 16 04

**Comment by annaveronika** [comment]
If you are using binary classification, then to get probabilities you need to get sigmoid from the result.

**Comment by olesyaksyon** [comment]
thank you!
