### ISSUE TITLE
cpp valgrind error

### ISSUE THREAD

**Issue by olesyaksyon** [catboost/catboost#295]
Problem: 
How can I fix the valgrind error?

code:

int features[descriptor_size];
for (int i = 0; i < descriptor_size; i++) {
        features[i] = i;
 }

const int *features_const = features;

ModelCalcerHandle* modelHandle = ModelCalcerCreate();
const float * descriptors = retrieval.get_descriptors(); //the pointer is not empty guaranteed

 double result[1];
 CalcModelPredictionWithHashedCatFeatures(
                    modelHandle,
                    1,
                    &descriptors,
                    descriptor_size,
                    &features_const,
                    descriptor_size,
                    result,
                    1
);

valgrind error:
==14622== Use of uninitialised value of size 8
==14622==    at 0x4E59BCF: void CalcTreesSingleDocImpl<true, false>(TFullModel const&, unsigned char const*, unsigned long, unsigned int*, unsigned long, unsigned long, double*) (formula_evaluator.cpp:414)
==14622==    by 0x4E9055D: __invoke<void (*&)(const TFullModel &, const unsigned char *, unsigned long, unsigned int *, unsigned long, unsigned long, double *), const TFullModel &, const unsigned char *, unsigned long, unsigned int *, unsigned long, unsigned long, double *> (type_traits:4362)
==14622==    by 0x4E9055D: __call<void (*&)(const TFullModel &, const unsigned char *, unsigned long, unsigned int *, unsigned long, unsigned long, double *), const TFullModel &, const unsigned char *, unsigned long, unsigned int *, unsigned long, unsigned long, double *> (__functional_base:350)
==14622==    by 0x4E9055D: std::__y1::__function::__func<void (*)(TFullModel const&, unsigned char const*, unsigned long, unsigned int*, unsigned long, unsigned long, double*), std::__y1::allocator<void (*)(TFullModel const&, unsigned char const*, unsigned long, unsigned int*, unsigned long, unsigned long, double*)>, void (TFullModel const&, unsigned char const*, unsigned long, unsigned int*, unsigned long, unsigned long, double*)>::operator()(TFullModel const&, unsigned char const*&&, unsigned long&&, unsigned int*&&, unsigned long&&, unsigned long&&, double*&&) (functional:1562)
==14622==    by 0x4E428E7: operator() (functional:1923)
==14622==    by 0x4E428E7: CalcGeneric<(lambda at /home/olesya/catboost/catboost/libs/model/model.cpp:336:9), (lambda at /home/olesya/catboost/catboost/libs/model/model.cpp:339:9)> (formula_evaluator.h:209)
==14622==    by 0x4E428E7: TFullModel::Calc(TVector<TArrayRef<float const>, std::__y1::allocator<TArrayRef<float const> > > const&, TVector<TArrayRef<int const>, std::__y1::allocator<TArrayRef<int const> > > const&, unsigned long, unsigned long, TArrayRef<double>) const (model.cpp:334)
==14622==    by 0x4E3B54C: Calc (model.h:437)
==14622==    by 0x4E3B54C: CalcModelPredictionWithHashedCatFeatures (model_calcer_wrapper.cpp:106)
==14622==    by 0x40637D: main (main.cpp:67)

catboost version: latest
Operating System: Ubuntu 16 04

**Comment by annaveronika** [comment]
Very sorry for such a long reply! We'll try to reproduce and get back to you in this issue.
