### ISSUE TITLE
Choose best iteraation only after a number of iterations

### ISSUE THREAD

**Issue by bangeneticalgorithms** [catboost/catboost#297]
Problem:  I would like to only use the best iteration (best Test using the eval set) after a set number of iterations. For example, if I run a model for 1000 iterations, can I force Catboost to only use the best iteration after 100 iterations? I want to ignore if a eval set fits very well within the first few iterations. What parameters in CatBoostClassifier(or CatBoostClassifier.fit) or CatBoosRegressor(or CatBoostRegressor.fit) can I use to force catboost to ignore the best test within the first n iterations (where n<N, where N is the total number of iterations)
catboost version: 0.6.3
Operating System: Ubuntu 14.04

**Comment by dlihhats** [comment]
I'd recommend either tuning the learning rate, the depth or another parameter to ensure that the best iteration comes after the 100th, or setting `use_best_model` to False and then specifying the boundaries of the first and last trees for the model to use during inference.

**Comment by annaveronika** [comment]
@bangeneticalgorithms Yes, @dlihhats's advice is the way to go - firstly decrease learning rate, if it doesn't help set use_best_model=False. To use first k iterations you can also use model.shrink() function.

**Comment by annaveronika** [comment]
Actually we can allow use_best_model=int - this will solve your problem

**Comment by annaveronika** [comment]
We implemented best_model_min_trees parameter. You can build from source and use it.
Also if you would share your dataset where you have metric spike in the start of the training, it would be very helpful, since we want to debug when this situations happen.

**Comment by annaveronika** [comment]
Closing the issue as fixed, let me know if you have any questions!
