### ISSUE TITLE
R package need Python?

### ISSUE THREAD

**Issue by akogay** [catboost/catboost#3]
> install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/***/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/***/AppData/Local/Temp/Rtmp8g9Ngq/devtools81cc29ef78b3/catboost-catboost-37378d2/catboost/R-package"  \
  --library="C:/Users/kogayaa/Desktop/R-3.4.0/library" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/***/AppData/Local/Temp/Rtmp8g9Ngq/devtools81cc29ef78b3/catboost-catboost-37378d2/catboost/R-package/src/../../../ya.bat make -r -o ../../..
**[ya.bat] Error: Python not found** 
make: *** [libcatboostr.dll] Error 1
Предупреждение: работающая команда 'make --no-print-directory -f "Makefile.win"' имеет статус 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/kogayaa/Desktop/R-3.4.0/library/catboost'
Error: Command failed (1)

**Comment by ferrr** [comment]
Yes, our build system requires Python installation.

**Comment by grayskripko** [comment]
terminal:
```
where /R C:\ python.exe
```
Then you can use any of those paths and append it to your system PATH variable. I used C:\RBuildTools\3.4\mingw_64\opt\bin\
