### ISSUE TITLE
Building and installing problem in R

### ISSUE THREAD

**Issue by metariat** [catboost/catboost#301]
# Problem: 

Having problems with the proxy, I try to install catboost for R from a local copy in Windows following [this instruction.](https://tech.yandex.com/catboost/doc/dg/concepts/r-installation-docpage/#local-copy-installation-windows)

The only difference is that I didn't download catboost repo via gitbash but manually via the website.

- I've installed python and add it to the path.
- I've installed **Visual Studio Community 2017**, with Windows Platform development and Desktop Development with C++ options.
- I've installed also VC++ 2015.3 v140 toolset for desktop (x86,x64) and VC++ 2017 v141 toolset (x86,x64) options.

No problems nor warning until here.

Then I set the working directory to the catboost R-package. Then use devtools to build and install the package.

Here I have the following warnings with build:

```
> devtools::build()
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  "C:\Users\xq.do\Downloads\catboost-master\catboost-master\catboost\R-package"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\xq.do\Downloads\catboost-master\catboost-master\catboost\R-package/DESCRIPTION' ... OK
* preparing 'catboost':
* checking DESCRIPTION meta-information ... OK
* cleaning src
Warning: C:/Users/xq.do/AppData/Local/Temp/RtmpCaOZOZ/Rbuild1f043c9b6da4/catboost/man/catboost.train.Rd:56: unknown macro '\t'
Warning: C:/Users/xq.do/AppData/Local/Temp/RtmpCaOZOZ/Rbuild1f043c9b6da4/catboost/man/catboost.train.Rd:56: unknown macro '\t'
Warning: C:/Users/xq.do/AppData/Local/Temp/RtmpCaOZOZ/Rbuild1f043c9b6da4/catboost/man/catboost.train.Rd:56: unknown macro '\t'
Warning: C:/Users/xq.do/AppData/Local/Temp/RtmpCaOZOZ/Rbuild1f043c9b6da4/catboost/man/catboost.train.Rd:56: unknown macro '\t'
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'catboost_0.7.2.tar.gz'

[1] "C:/Users/xq.do/Downloads/catboost-master/catboost-master/catboost/catboost_0.7.2.tar.gz"
```

and the following errors with install:

```
> devtools::install()
Installing catboost
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/xq.do/Downloads/catboost-master/catboost-master/catboost/R-package"  \
  --library="C:/documents/xq.do/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/xq.do/Downloads/catboost-master/catboost-master/catboost/R-package/src/../../../ya.bat make -r -o ../../..
ERROR: <urlopen error timed out>
ERROR: <urlopen error timed out>
ERROR: <urlopen error timed out>
ERROR: <urlopen error timed out>
ERROR: <urlopen error timed out>
ERROR: <urlopen error timed out>
make: *** [all] Error 1
Warning: l'exécution de la commande 'make --no-print-directory -f "Makefile.win"' renvoie un statut 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/documents/xq.do/Documents/R/win-library/3.4/catboost'
In R CMD INSTALL
Error: Command failed (1)
```

Here is my R session information:

```
> session_info()
Session info ----------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2018-04-06                  

Packages --------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.4   2018-03-15 local         
 compiler    3.4.4   2018-03-15 local         
 datasets  * 3.4.4   2018-03-15 local         
 devtools  * 1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics  * 3.4.4   2018-03-15 local         
 grDevices * 3.4.4   2018-03-15 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods   * 3.4.4   2018-03-15 local         
 stats     * 3.4.4   2018-03-15 local         
 tools       3.4.4   2018-03-15 local         
 utils     * 3.4.4   2018-03-15 local         
 withr       2.1.2   2018-03-15 CRAN (R 3.4.4)
 yaml        2.1.18  2018-03-08 CRAN (R 3.4.4)
```

# catboost version: 0.7.1
**Operating System:** Windows 7 Enreprise 64 bits (6.1, version 7601)
CPU: Intel(R) Core(TM) i5-6300U CPU @2.40GHz (4CPUs), ~2.4GHz
# GPU: Intel(R) HD Graphics 520

**Comment by hugoncosta** [comment]
This one worked welll for me: https://tech.yandex.com/catboost/doc/dg/installation/r-installation-binary-installation-docpage/

**Comment by annaveronika** [comment]
@metariat Have you installed the library, does the instruction work for you?

**Comment by metariat** [comment]
@annaveronika yes, I have installed successfully but only the previous version of catboost with the following code: 

`devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.6.1.1/catboost-R-Windows-0.6.1.1.tgz', args = c("--no-multiarch"))`

**Comment by annaveronika** [comment]
Does it not work with the latest version?

**Comment by StatMixedML** [comment]
Having problems with the R installation of catboost v0.9 using devtools::install_url("URL"). To install previous versions, I used to use

**devtools::install_url("https://github.com/catboost/catboost/releases/download/v0.8.1/catboost-R-Linux-0.8.1.tar")**

I checked the release page but there is no link as "catboost-R-Linux-0.9.tar". Any suggestion how to do it for the new version? 

Thanks

**Comment by kizill** [comment]
@StatMixedML sorry for missing prebuilt package, we have some problems with CI for now. If you could wait, i can build linux & mac R packages today and put them on releases page. Also, as you are on linux it should be really easy to build package from github with R devtools: https://tech.yandex.com/catboost/doc/dg/installation/r-installation-github-installation-docpage/
