### ISSUE TITLE
GPU: CatboostError: Feature is empty 

### ISSUE THREAD

**Issue by SergeyBridge** [catboost/catboost#302]
Problem: {CatboostError: catboost/cuda/gpu_data/compressed_index_builder.h:158: Feature is empty
The pool is loaded from file, and it is OK for CPU mode, but raise an error with GPU mode:

    #model = CatBoostRegressor(loss_function='RMSE',iterations=10000, depth=8, learning_rate=0.02,
    #                     od_type='Iter', od_wait=40, has_time=True, # od_pval=10e-7,
    #                     task_type='CPU', thread_count=4, 
    #                     rsm=0.2,
    #                     l2_leaf_reg=3,
    #                     random_seed=1000,
    #                     train_dir='./catboost_train_dir')

    model = CatBoostRegressor(loss_function='RMSE', eval_metric='RMSE',
                         iterations=10000, depth=8, learning_rate=0.02,
                         has_time=True, od_type='Iter', od_wait=40, # od_pval=10e-7,
                         task_type='GPU', boosting_type='Plain', border_count=32,
                         thread_count=4, #rsm=0.2,
                         l2_leaf_reg=3,
                         random_seed=1000,
                         train_dir='./catboost_train_dir')
        
    train_pool = Pool(data=get_pool(step=step, period_id='train')['fname'], 
                      column_description=get_pool(step=step, period_id='train')['CDfname'], 
                      has_header=True, thread_count=4)
    eval_pool = Pool(data=get_pool(step=step, period_id='eval')['fname'], 
                      column_description=get_pool(step=step, period_id='eval')['CDfname'], 
                      has_header=True, thread_count=4)

    
    model.fit(X=train_pool, 
              use_best_model=True, eval_set=eval_pool, 
              logging_level='Verbose')

}
catboost version: {0.6.3}
Operating System: {Ubuntu 16.04}
CPU: {i5}
GPU: {GTX 480}

**Comment by Noxoomo** [comment]
Please update to latest catboost version and check, if problem'll be reproduced

**Comment by SergeyBridge** [comment]
Vasily! thanks again...
I'm a newbie at linux(ubuntu), is there a lite way to update catboost version or it is necessery to remove the old library  and install a new one?

**Comment by Noxoomo** [comment]
1) For  packages from pip it's simple pip install --upgrade catboost
2) If you are building from source, then it depends of how you installed package. Basically you need to compile new version and replace python-package from old to new one

**Comment by SergeyBridge** [comment]
I built from source, and having such an error
`raise` Exception('System non fixed python can be used only with `OS_SDK=local')`
with this parameters
` ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda'

I have already used make catboost library on this system (ubuntu 16.04), and now it doesn't installing

**Comment by Noxoomo** [comment]
../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda -DOS_SDK=local should work

**Comment by SergeyBridge** [comment]
Yes, Vasily, it does work!
Everything has compiled. Thank you!
The catboost's version now is 0.7.2.1

But the problem remains. 
1. I've got pool: train, eval and test from file
2. it is not very much
3. The pool for CPU mode works well for me
4. the pool doesn't work with GPU mode. IPython error : The kernel was died and will restart automatically

**Comment by Noxoomo** [comment]
With the same error? "CatboostError: catboost/cuda/gpu_data/compressed_index_builder.h:158: Feature is empty" or just died?

**Comment by Noxoomo** [comment]
And do you have NaN's in data?

**Comment by SergeyBridge** [comment]
An error has changed. Now I have only popup window
`The kernel appears to have died. It will restart automatically.`

And, for now I only have pools saved on disk as generated or prepared features. How can I check pool for NaN data?

**Comment by Noxoomo** [comment]
seems like now problem somewhere else.
Could you run the same script without Jupyter notebook?

**Comment by SergeyBridge** [comment]
Vasily! 

1.When I'm using read pool from file without notebook, my model works well in CPU mode and crashes with the same pool in GPU mode with error:
$python model.py

`Application` terminated with error: (TCatboostException) catboost/cuda/cuda_lib/cuda_base.h:257: CUDA error: invalid device function 8
uncaught exception:
    address -> 0x107a01748
    what() -> "catboost/cuda/cuda_lib/cuda_base.h:257: CUDA error: invalid device function 8"
    type -> TCatboostException
Aborted (core dumped)

Here is code to load pool from file :
`train_pool = Pool(data=get_pool(fname,  column_description=CDfname, 
                           has_header=True, thread_count=4)`

2.When I load same pool from pandas, GPU and CPU works well for me !

`        train_pool = Pool(data= reg_features.loc[train], label = ylabel.loc[train, reg], 
                          has_header=True, cat_features=cat_features,  thread_count=4)
`

**Comment by Noxoomo** [comment]
You should do a little bit more than just ya make to build for GPUs with compute capability 2.0 (https://tech.yandex.com/catboost/doc/dg/concepts/cli-installation-docpage/)

> 
> (Optionally) CUDA of compute capability 2.0 users must replace the -gencode arch=compute_30,code=compute_30 substring with -gencode arch=compute_20,code=compute_20 in all ya.make files of the cloned repository.
> 
> For example, Linux users can run the following sed command from the root of the local copy of the CatBoost repository:
> find ./ -type f -name ya.make -exec sed -i 's/compute_30/compute_20/g' {} +

**Comment by SergeyBridge** [comment]
Vasily, 
1. I forgot to do the replacing compute capality, I'm sorry and thank you. I've recompiled the catboost library, now it works ok.
2. I have ran the model from CLI, without jupiter notebook, it works well with CPU mode for big and small size pools. ( The big pool size allocate 12.5Gib disk space and ~6Gib RAM )
3. For GPU mode CLI version works well on small pool, for the big pool it stops with error:

**python ./_model.py
numpy =  1.14.0
pandas =  0.22.0
catboost =  0.7.2.3
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0]
step 1 starting 0:00:01
train_pool got: step=1 0:02:31
eval_pool got: step=1 0:00:02
Random seed 1000
Application terminated with error: (NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:294: Error: Out of memory. Requested 1070.546387; Free 1010.952393
uncaught exception:
    address -> 0x107a02288
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:294: Error: Out of memory. Requested 1070.546387; Free 1010.952393"
    type -> NCudaLib::TOutOfMemoryError
Aborted (core dumped)**

**Comment by Noxoomo** [comment]
Error is pretty self-explainable: you don't have enough GPU memory to fit on big dataset

**Comment by Noxoomo** [comment]
You could try to add option: gpu_cat_features_storage: CpuPinnedMemory

**Comment by SergeyBridge** [comment]
gpu_cat_features_storage: CpuPinnedMemory doesn't work, the same error.

I guess that my GPU  GTX480 is an old styled, but  my pool is not the biggest pool in the world!
I will obviously impact to cases when the pool is huge and not enough GPU memory to fit on dataset which bigger, bigger and bigger.

To calculate my pool what could I do more ? 
And, Thank you for your help ))))

**Comment by Noxoomo** [comment]
How many categorical features in your dataset? and how many float ones?
one more option is to set max_ctr_complexity=1, but this'll reduce quality
Plus  border_count=15 will reduce memory for float feature in exchange for less quality

**Comment by Noxoomo** [comment]
Also GPU has experimental feature for border-ctrs: you could set simple_ctr option to Borderes:PriorEstimation=BetaPrior,FeatureFreq  and this also reduce memory requirements for categorical features

**Comment by SergeyBridge** [comment]
Ok, Vasily! 
I've got the result calculation without GPU, and need to take pause for this problem, may be later...
1. Now I assume that GPU mode is available for tasks with train pool no more then ~11Gib for every model (for 1080ti or V100)?
2. If I could have 2 GPU cards with total memory 11*2=22Gib, the memories does not summarizing and my strategy consists of doing models in parallel, so I can't compute the model with, i.e. 18Gib data pool?

**Comment by Noxoomo** [comment]
1) V100 has 32GB version, Tesla M40/P40 are 24GB memory per one card
2) Maximum train pool size depends on number of categorical features. For dataset without cat features 11GB of GPU memory is enough to learn on matrix with approximately 1000 columns and 10M rows (or even 2 times bigger matrix, if you use just 15 borders per features), For categorical features maximum size depends on categorical features cardinality and can;t be easily estimated
3) 2 GPUs usually allows to learn on x2 bigger datasets.

**Comment by SergeyBridge** [comment]
Ok, 
Thank you
