### ISSUE TITLE
How does eval_metrics calculate metrics, when it doesn't take the true labels?

### ISSUE THREAD

**Issue by bangeneticalgorithms** [catboost/catboost#303]
Problem: According to the docs, the parameter  **data**, is specified as the input dataset. But how can the function calculate the correct metrics when it doesn't have the true labels as it is called in here #285.

I tried to call eval_metrics the way is called in #217.

The two ways eval_metrics are called are,
`model.eval_metrics(data=testX, metrics=["R2"])`
and
`model.eval_metrics(data=[testY,preds], metrics=["R2"])`

The second version runs into an error
`_catboost.CatboostError: catboost/libs/algo/apply.h:52: Insufficient float features count 143<8708`

But the first version doesn't make intuitive sense because the function takes the inputs (and assuming it internally produces the predictions), it doesn't take the labels to compare to evaluate the metrics

catboost version: {0.7.2}
Operating System: {Ubuntu 14.04}

**Comment by nikitxskv** [comment]
@bangeneticalgorithms Hello!
We will correct the documentation to make it clearer.
Meanwhile, use `catboost.Pool` class to store the dataset:
```
test_pool = catboost.Pool(testY, preds)
model.eval_metrics(test_pool, metrics=["R2"])
```
