### ISSUE TITLE
Purpose of the cross validation

### ISSUE THREAD

**Issue by herbzhao** [catboost/catboost#304]
Hi all, 
Sorry I am fairly new to machine learning field. In the catboost, we can run cross-validation for our trained model. And it will output accuracy throughout different iterations. 

Does cv **alter our models**? Or it is purely used as a way to **check how well our models perform**. 

It seems like cv still involves training the model as different iterations behave differently. If cv is changing the model, does it change the model which we `model.get_params()` for?

**Comment by nikitxskv** [comment]
Hi @herbzhao!
CV simultaneously trains several models with the same parameters. These models train on different parts of the input dataset.
CV doesn't change your `model` and just get its params.
Сross-validation is the most honest way to evaluate the quality of your model.
