### ISSUE TITLE
CatBoostClassifier throws error for simple binary classification, but works when loss_function='MultiClass'

### ISSUE THREAD

**Issue by vivekk-ezdi** [catboost/catboost#306]
#### Problem: 
CatBoostClassifier throws error for simple binary classification

#### Reproducible code:
```
import numpy as np
from catboost import CatBoostClassifier

X = np.array([[1, 1], [1, 2], [1, 3], [2, 1], [2, 2], [2, 3]])
y = np.array([1, 1, 1, 2, 2, 2])
estimator = CatBoostClassifier(verbose=False)
estimator.fit(X, y)
```

#### Expected Results
 No error should be thrown

#### Actual Results
```
Traceback (most recent call last):

  File "<ipython-input-81-7ab8c5b5d9b1>", line 1, in <module>
    runfile('/home/local/EZDI/vivek.k/ascxczx.py', wdir='/home/local/EZDI/vivek.k')
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)
  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)
  File "/home/local/EZDI/vivek.k/ascxczx.py", line 73, in <module>
    estimator.fit(X, y)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 1634, in fit
    self._fit(X, y, cat_features, None, sample_weight, None, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 780, in _fit
    self._train(train_pool, eval_set, params, allow_clear_pool)
  File "_catboost.pyx", line 1079, in _catboost._CatBoostBase._train
  File "_catboost.pyx", line 854, in _catboost._CatBoost._train
  File "_catboost.pyx", line 862, in _catboost._CatBoost._train
CatboostError: catboost/libs/train_lib/preprocess.cpp:43: All train targets are greater than border
```

Now when we supply `loss_function='MultiClass'`, it fits correctly and the following code runs without any error.
```
import numpy as np
from catboost import CatBoostClassifier

X = np.array([[1, 1], [1, 2], [1, 3], [2, 1], [2, 2], [2, 3]])
y = np.array([1, 1, 1, 2, 2, 2])
estimator = CatBoostClassifier(verbose=False, loss_function='MultiClass')
estimator.fit(X, y)
```

#### System Information
Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
('Python', '2.7.6 (default, Nov 23 2017, 15:49:48) \n[GCC 4.8.4]')
('NumPy', '1.14.2')
('SciPy', '1.0.1')
('Scikit-Learn', '0.19.1')
('Catboost', '0.7.2.3')

**Comment by vivekk-ezdi** [comment]
@annaveronika But then in the predictions it returns 0 and 1 labels in place of 1 and 2 respectively.

**Comment by annaveronika** [comment]
That's right - the 0 class or the 1 class. Again - it is done this way because we want to be able to train with not binary values in target. For example you have possible values -1,0,2,3,4 and want to do binary classification with border 2.5. Then all objects with labels -1,0,2 are considered 0 class and with labels 3,4 - 1 class.
It is also possible to calculate probabilities using predict_proba. In this case first column will be probability of class 0 and second column - probability of class 1.

**Comment by vivekk-ezdi** [comment]
Hi, thanks for clarifying this. I think it would be good if this is documented somewhere. Please point me to it if its already done. 

This issue is somewhat related to issue #305.  My actual use-case was that I am trying to compare different algorithms (scikit ones and this) on my data with class labels `1,2`. And noticed that error. All scikit-learn estimators will automatically encode the labels internally.   

Thanks again.

**Comment by burgalon** [comment]
Hi, a bit diverging from the initial main topic:
@annaveronika - Is there a way to run CatBoost with something like BinaryCroosEntropy for multi label binary classification? e.g: labels would be `[[0,0], [0,1], [1,1]]`

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi burgalon,
1. CatBoost does not support vector labels. But this may change (https://github.com/catboost/catboost/issues/547).
2. The tutorial shows how to use ranking instead of multiclassification with many classes.
