### ISSUE TITLE
used_ram_limit parameter in python

### ISSUE THREAD

**Issue by LeData** [catboost/catboost#309]
Problem: The python documentation seems to be copied from the command line one. There is no was to pass 2gb as a parameter as it is not accepted as a string and is for sure not an unsigned integer.

From the doc:
```
The maximum amount of memory available to the CTR calculation process.

Format:
<size><measure of information>
Supported measures of information (non case-sensitive):
MB
KB
GB
For example:
2gb
```

catboost version: 0.7.2.1

**Comment by annaveronika** [comment]
The fix for this in on github now, now python supports passing strings.
