### ISSUE TITLE
get_feature_importance, fstr_type = "Doc"

### ISSUE THREAD

**Issue by alexandregerbeaux** [catboost/catboost#312]
### Problem: 
Really need y / label in Pool for get_feature_importance with fstr_type = "Doc"?
### Operating System: Linux

Hi all,
Thanks for this wonderful package and all the material and documentation that you guys are providing.
I was wondering why we would need to set the label for getting the feature importance at an individual level (fstr_type = "Doc" in the get_feature_importance -- CatboostError: Label in X has not initialized).
Does the underlying method is designed for exploratory analysis within the train / eval data sets or it can be used into pilot on unkown label?

Best!

**Comment by nikitxskv** [comment]
@alexandregerbeaux Hi!

This is a bug. When evaluating fstr, labels are not needed indeed.
We'll fix it soon.

Thank you for report!

**Comment by alexandregerbeaux** [comment]
Just wondering, would it work as expected if I put a dummy label column for now?

**Comment by nikitxskv** [comment]
Yes, it is.
You can try to put different label columns and make sure that the result will be the same.

**Comment by nikitxskv** [comment]
Fix it!
