### ISSUE TITLE
shap values for models with categorical feature combinations

### ISSUE THREAD

**Issue by alexandregerbeaux** [catboost/catboost#314]
Hi, I have just installed your last release (0.8) and wanted to try out the ShapValues type of feature importance.

I am getting the following error message:
CatboostError: catboost/libs/fstr/shap_values.cpp:238: Model uses complex Ctr features. This is not allowed for SHAP values calculation

I wanted to know guys if you could elaborate on this error message and maybe provide the parameter to use for the fitting so that this option works?

Thank you so much,

Alex

**Comment by annaveronika** [comment]
The code for that is on github, you can build from source. It'll be on pypi soon - in our next release
