### ISSUE TITLE
Big Data Plot error

### ISSUE THREAD

**Issue by DictMiner** [catboost/catboost#316]
Problem: Finally some experiments with no plot/error after some amount of data.
code from example:
```
import numpy as np
from catboost import Pool, CatBoostRegressor
# initialize data
train_data = np.random.randint(0, 100, size=(10000000, 10))
train_label = np.random.randint(0, 1000, size=(10000000))
size = 1500000
train_pool = Pool(train_data[:size], train_label[:size],)
model = CatBoostRegressor(iterations=2, depth=2, learning_rate=1, loss_function='RMSE')
model.fit(train_pool, plot=True,verbose=False)
```
After 1400000 data problem or no plot:

> Exception in thread Thread-14:
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/opt/anaconda3/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/catboost/widget/ipythonwidget.py", line 28, in start
>     self._update_data(subdirs=subdirs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/catboost/widget/ipythonwidget.py", line 54, in _update_data
>     content = self._update_data_from_dir(path)
>   File "/opt/anaconda3/lib/python3.6/site-packages/catboost/widget/ipythonwidget.py", line 88, in _update_data_from_dir
>     'passed_iterations': data['iterations'][-1]['iteration'],
> IndexError: list index out of range

catboost version: 0.7+ (0.7.2.3)
Operating System: Ubuntu 16.04 (same on Windows Server on it)
CPU: 24
GPU: -
ipywidgets-7.+ (7.2.1) widgetsnbextension-3.2.1

**Comment by DictMiner** [comment]
All problem in catboost/widget/ipythonwidget.py

Looks like there is no data for thread in catboost_training.json yet.
if it return None - no plot, if no data in json -  error,  this check lead to no plot everytime
```
if len(data['iterations'])<0:
            return None
```
this will greatly improve limit size  ^)
` time.sleep(1)`

Maybe we need normal null initialization

**Comment by Mechanix12** [comment]
I have sometimes same error

**Comment by nikitxskv** [comment]
@DictMiner @Mechanix12 Hi!
Could you upgrade CatBoost to 8.1 and try again?

**Comment by DictMiner** [comment]
@nikitxskv Nice, but u can't display None for first time (no plot this way).
This work for me:

1. add new flag for update

```
    def _update_data(self):
        ....
        is_updated = False

        for dir_info in dirs:
            ...
            data[path] = {
                'path': path,
                'name': dir_info.get('name'),
                'content': content
            }

            is_updated = True



        return is_updated
```

2. wait for update for first time:

```
    def start(self):
        # wait for start train (meta.tsv)
        self._init_static()
        
        while not self._update_data():
            time.sleep(1.0)

        display(self)

        while self._need_update:
            self._update_data()
            time.sleep(2.0)
```

**Comment by vadamoto** [comment]
ipywidgets==7.2.1
widgetsnbextension==3.2.1
catboost==0.8.1

I see only big white space where the plot is supposed to be.

To be sure, I loaded and trained titanic dataset in the very same notebook, and the plot works!

**Comment by annaveronika** [comment]
This should be fixed now, please try building from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/

Closing the issue. Feel free to reopen, if something doesn't work for you.
