### ISSUE TITLE
Reading pool from file causes python.exe to crash on 64-core server

### ISSUE THREAD

**Issue by elfwired** [catboost/catboost#320]
Problem: Reading pool from file causes python.exe to crash on 64-core server
catboost version: 0.8
Operating System: Windows Server 2012
CPU: 4x Intel Xeon v4 16 core (VMWare)
GPU: no GPU
--
`pool3 = Pool(data='train.tsv', has_header=False, column_description='train.cd')`

*This application has requested the Runtime to terminate it in an unusual way.*
*Please contact the application's support team for more information.*

It seems that when you don't specify thread_count, the default value (-1) means that thread_count is set to number of available cores. So on 64-core server thread_count is more than CB_THREAD_LIMIT (56 for now) 

I propose to set thread count to `MIN(available_cores,  CB_THREAD_LIMIT)` when `thread_count` is not set or set to `-1`
AND
alo please increase `CB_THREAD_LIMIT` value

**Comment by dbakshee** [comment]
Hi @elfwired ,
We've fixed this in commit 00cedecd42240d7a3c0c1541144e997b76f0fa31
