### ISSUE TITLE
Improve 'generate border' error message

### ISSUE THREAD

**Issue by LeData** [catboost/catboost#322]
Problem: It is not clear whether the model stops or continues after the following message appears:
`CatBoost needs **** Mb of memory to generate borders`
when using a used_ram_limit too low.

It would be good to be informed of what is actually happening next.

**Comment by annaveronika** [comment]
@LeData Sorry for a long response. This is a warning msg, the used_ram_limit parameter doesn't guarantee that the program will not use more memory than this value. This is only used for caching during calculating of categorical features statistics. We have this information in documentation:

``
Attempt to limit the amount of used CPU RAM.

Restriction.
This option affects only the CTR calculation memory usage.
In some cases it is impossible to limit the amount of used CPU RAM in accordance with the specified value.
``
