### ISSUE TITLE
[VIZ] Make summary table resizable

### ISSUE THREAD

**Issue by rs2** [catboost/catboost#324]
![image](https://user-images.githubusercontent.com/4407787/39407610-9dfc0592-4bc0-11e8-85e1-6b395933693e.png)

**Comment by annaveronika** [comment]
@rs2 Would you consider contributing?

**Comment by rs2** [comment]
Yes

**Comment by annaveronika** [comment]
@rs2 Any news on that? It would be nice to include this in our next release.

**Comment by rs2** [comment]
Happy to do a sprint at EuroPython. Will try to carve out some time before that, but can't promise...

**Comment by annaveronika** [comment]
Ok, thanks! removing the comment as unrelated to the topic.

**Comment by annaveronika** [comment]
Time flies and I don't belive there is a plan to implement this. So I'm closing the issue as won't fix.
@rs2 if you'll have a plan to do something, let us know, we have a lot of options including visualisation!
