### ISSUE TITLE
Make SHAP values not require y in Pool object

### ISSUE THREAD

**Issue by stasSajin** [catboost/catboost#328]
Currently, the following format for extracting shap values is accepted:

`model.get_feature_importance(Pool(X, y), fstr_type='ShapValues')`

`y` in this context is redundant and might not be available when explanations are required for new predictions for which an outcome is unknown. 

Currently the hack for getting feature explanations when the outcome is unknown is:
`model.get_feature_importance(Pool(X, np.repeat(1, len(X))), fstr_type='ShapValues')`

I recommend dropping `y` from the requirement or separating the pool objects into two (X and y, with y being optional), otherwise, users are going to be confused about how to use the catboost feature explainer for making new predictions.

**Comment by annaveronika** [comment]
You don't have to specify y when creating Pool object. You can just create Pool(data=X)

**Comment by stasSajin** [comment]
thanks for the quick response (I don't know why I didn't think about trying that) :)
