### ISSUE TITLE
[Tutorials][Important Objects] Need to convert indices into 1d array

### ISSUE THREAD

**Issue by lampts** [catboost/catboost#329]
Tutorial link: https://github.com/catboost/catboost/blob/master/catboost/tutorials/advanced_tutorials/catboost_object_importance_tutorial.ipynb

Line: indices, scores = cb.get_object_importance(..)
Error: CatboostError: catboost/libs/train_lib/preprocess.cpp:49: All train targets are equal

Root cause: indices is list of list
Solution: convert indices into 1D array: indices = np.array(indices[0])

Screenshot:
<img width="888" alt="screen shot 2018-05-01 at 2 47 08 pm" src="https://user-images.githubusercontent.com/656949/39465637-91bc1bf2-4d4e-11e8-86f3-f5bb243ca5b5.png">

Solution added:
<img width="935" alt="screen shot 2018-05-01 at 2 46 22 pm" src="https://user-images.githubusercontent.com/656949/39465638-91fb8116-4d4e-11e8-8989-c7a2d66aab7b.png">

**Comment by nikitxskv** [comment]
@lampts Hi!
This bug should be fixed in 8.1
Try to upgrade CatBoost and run the tutorial again.

**Comment by lampts** [comment]
Yes, it's fixed in 0.8.1. So I closed this.
