### ISSUE TITLE
Backpropagation back to parent network

### ISSUE THREAD

**Issue by ghost** [catboost/catboost#330]
Problem: No Problem
catboost version: v0.6.3
Operating System: CentOS
CPU: Intel Xeon E5
# GPU: GTX 1080Ti

I was wondering if there are any plans for future directions of CatBoost where it could be more tightly integrated with other deep learning frameworks allowing for gradient propagation back to parent networks generating the features. 
I believe it might be possible by creating appropriate support packages for different frameworks. What do developers/other users think about this ?

This could be a uniquely great feature.

**Comment by annaveronika** [comment]
Sorry, we missed the issue, there is no plan for this particular way of integrating with deep learning frameworks. So closing this one as won't fix.
