### ISSUE TITLE
Sample C code for C API throws segmentation fault

### ISSUE THREAD

**Issue by dlihhats** [catboost/catboost#331]
Problem: Sample C code for C API throws segmentation fault
catboost version: 0.81
Operating System: Ubuntu 18.04 LTS

I took a sample C code from https://tech.yandex.com/catboost/doc/dg/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper-docpage/ and compiled it with gcc. The program throws segmentation fault when `CalcModelPrediction` function iterates over 2D array.

It seems to me that the problem is the following. `CalcModelPrediction` function expects `char ***catFeatures` and `float **floatFeatures`. However, we pass `&catFeature` to it where `catFeatures` is defined as `char* catFeatures[2] = {"1", "2"};` (same for `floatFeatures`).

I managed to make it work by declaring a pointer like `float (*p)[1]"` then `p = floatFeatures`, and then pass `&p` to `CalcModelPrediction`. But I don't think it's the right way. In particular, since I need to call the .so library from JNA, I'm not sure how to pass such a pointer to a pointer from there when calling `CalcModelPrediction`.

I'm not a C expert at all, but I spent last couple of days studying arrays and pointers in C :) Can't handle it anymore :)

**Comment by dlihhats** [comment]
I've managed to make the C example work and make predictions for more than one documents by explicitly allocating memory for the 2D array using malloc. Here's the full code:

`#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <model_calcer_wrapper.h>
double main()
{
    const float floatFeatures[] = {0.4f, 0.8f, 0.3f, 0.3f, 0.1f, 0.5f, 0.4f, 0.8f, 0.3f, 0.3f}; // some dummy data
    const char *catFeatures[] = {"1", "2", "3", "4"};

    int fr = 2, fc = 10, fi, fj, fcount;
    int cr = 2, cc = 4, ci, cj, ccount;

    float **ppFloat = (float **)malloc(fr * sizeof(float *));
    for (fi = 0; fi < fr; fi++)
    {
        ppFloat[fi] = (float *)malloc(fc * sizeof(float));
    }
    for (fi = 0; fi < fr; fi++)
    {
        for (fj = 0; fj < fc; fj++)
        {
            ppFloat[fi][fj] = floatFeatures[fj] + 100.0f * (float)fi;
        }
    }

    char ***ppCat = (char ***)malloc(cr * sizeof(char **));
    for (ci = 0; ci < cr; ci++)
    {
        ppCat[ci] = (char **)malloc(cc * sizeof(char *));
    }
    for (ci = 0; ci < cr; ci++)
    {
        for (cj = 0; cj < cc; cj++)
        {
            ppCat[ci][cj] = catFeatures[cj];
        }
    }

    double *result = (double *)malloc(2*sizeof(double));

    ModelCalcerHandle * modelHandle;
    modelHandle = ModelCalcerCreate();

    if (!LoadFullModelFromFile(modelHandle, "catboost_test.model")) {
        printf("LoadFullModelFromFile error message: %s\n", GetErrorString());
    }
   
    if (!CalcModelPrediction(
                             modelHandle,
                             2,
                             ppFloat, 10,
                             ppCat, 4,
                             result, 2
                            )) {
        printf("CalcModelPrediction error message: %s\n", GetErrorString());
    }
    ModelCalcerDelete(modelHandle);
    printf("Done 1! %f\n", result[0]);
    printf("Done 2! %f\n", result[1]);

    return 0.0;
}`

Might be worth updating the C example on the website because still, it doesn't work.

**Comment by kizill** [comment]
Sorry for inactivity! We should definitely provide interface for single object prediction to make your life easier, i'll do it this week.

**Comment by dlihhats** [comment]
@kizill That would be very helpful, thank you! Also, could you please confirm that for the binary classification with Logloss as the optimisation function, to get the probability of the positive class, I simply need to take the sigmoid - `1 / (1 + exp(-x))` - of the raw value that the C library outputs?

**Comment by kizill** [comment]
@dlihhats, yes. I think we will should provide proper helper functions in C api to make raw values postprocessing friendly.
