### ISSUE TITLE
Shap Values in R - Feature Importance

### ISSUE THREAD

**Issue by geof88** [catboost/catboost#332]
Problem: {Shap Values in R}
catboost version: {0.8.1}
Operating System: {Windows}
CPU: {CPU}

Hello,
I am trying to produce the SHAP values in R for a model like in the "shap_values_tutorial" in Python but I get the following error: Key 'ShapValues' not found in enum. Valid options are: 'FeatureImportance', 'InternalFeatureImportance', 'Interaction', 'InternalInteraction', 'Doc'. 

I guess this option is available only in Python, right? Or there is a different command in R? In the first case, when will it be available in R?

**Comment by annaveronika** [comment]
This is done now, the code is on github, you can build from source.
We will provide the binaries in the next release.
