### ISSUE TITLE
What is "Random strength" used for?

### ISSUE THREAD

**Issue by jrzaurin** [catboost/catboost#333]
Hi there

More than a problem this is a question about the parameter `Random Strength`. In the documentation I read: `Score standard deviation multiplier.`  So, is a standard deviation multiplier, but what is it used for? Is it to define some boundary? to isolate potential outliers? to calculate some confidence metric? I know the answer will be in the source code, but I thought it would be easier if you guys could tell me? (also apologies in advance if this is trivial!)
catboost version: `0.8.1`
Operating System: `CentOS7`
CPU: `CPU` mode

thanks in advance!

**Comment by annaveronika** [comment]
We use randomness when scoring the splits. Every split gets a score and then we add some randomness to it, this helps to reduce overfitting.

**Comment by jrzaurin** [comment]
Ok, thanks 👍 :)

Then I assume in theory can take any value, right?

**Comment by annaveronika** [comment]
Yes, it can take any value, and 0 means there will be no randomness
