### ISSUE TITLE
Can't save progress to file

### ISSUE THREAD

**Issue by aCombray** [catboost/catboost#336]
Problem: {I am working on a classification problem using CatBoostClassifier. It can train but can't save the training data. As a result, I can't really get the best parameters. Can anyone help me? The error message is like 
``` 
0:      learn: 0.9623499        test: 0.9645383 best: 0.9645383 (0)     total: 1.67s    remaining: 41m 40s
Can't save progress to file, got exception: (TFileError) (No such file or directory) util/system/file.cpp:619: can't open "catboost_info/data/talkingdata-adtracking-fraud-detection/d93c81a5-42a0bd20-c83d0a6-1.tmp" with mode CreateAlways|WrOnly|Seq (0x00000034)
1:      learn: 0.9651663        test: 0.9662213 best: 0.9662213 (1)     total: 3.08s    remaining: 38m 23s
Can't save progress to file, got exception: (TFileError) (No such file or directory) util/system/file.cpp:619: can't open "catboost_info/data/talkingdata-adtracking-fraud-detection/e7f12b34-338b2e4c-a17b7b5a-2.tmp" with mode CreateAlways|WrOnly|Seq (0x00000034)
```
Here is the parameter I am using
```
USED_RAM_LIMIT = 5*(2 ** 30)
CLASSES_RATIO = 1.0
eval_metric = 'AUC'
cb_params = {
    # technical
    'verbose' : True,
    'random_seed' : 42,
    'save_snapshot' : True,
    'snapshot_file' : output_path + 'snapshot',
    'used_ram_limit' : USED_RAM_LIMIT,
    
    # learning
    'l2_leaf_reg' : 150,
    'scale_pos_weight' : CLASSES_RATIO,
    'one_hot_max_size' : 100,
    'max_ctr_complexity' : 3,
    'leaf_estimation_iterations' : 8,
    'learning_rate' : 0.1,
    'eval_metric' : eval_metric
}
```
}
catboost version: {version=0.8.1}
Operating System: {OS=Ubuntu}
CPU: {CPU}
GPU: {GPU=None}

**Comment by Arian96669** [comment]
Hi AnnaVeronika.  

Did you ever incorporate the fix in the live version?  I'm running catboost 0.16.1 and getting error:
File "_catboost.pyx", line 2696, in _catboost._CatBoost._train
_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/libs/train_lib/train_model.cpp:59: Can't create working dir: ./catboost_info/Aug_08_10_12

But, when I first manually create folder ./catboost_info it runs fine and creates /Aug_08_10_12 as a sub-directory of ./catboost_info

My code:
training_dir = './catboost_info/' + datetime.strftime(datetime.now(), '%b_%d_%H_%M')

model = CatBoostClassifier(
    iterations=300,
    random_seed=42,
    #learning_rate=0.2,
    custom_loss=['Accuracy'],
    eval_metric='Logloss',
    train_dir=training_dir
)

model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_val, y_val),
    logging_level='Silent',
    plot=True
    )

**Comment by Sphinxs** [comment]
Update?
