### ISSUE TITLE
Problem about installing on Windows 10 with GPU.

### ISSUE THREAD

**Issue by Johnkuo** [catboost/catboost#337]
Problem: {GPU version cannot be installed on Windows}
catboost version: {0.81}
Operating System: {Windows 10}
GPU: {GPU}
Sorry that I am a newcomer and I just want to install catboost on my Windows PC with GPU support.
I am using anaconda 5.1 (python3.6) and also have already install CUDA9.1 and VSC2017 (VC++ 2015.3 v140 toolset for desktop (x86,x64) and VC++ 2017 v141 toolset (x86,x64)).
CPU installation works very well using pip. But I cannot install the GPU building from source or binary.

When I try "ya.make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1" with the command line, a system window opened and ask me to select an app to open the ".make" file?!
I know it's my mistake, but could anyone teach me how to install the GPU version on Windows 10 correctly?
Thanks very much.

**Comment by kizill** [comment]
@johnkuo, call `ya make` not `ya.make`

**Comment by Johnkuo** [comment]
@kizill Thank you for your kind reply.
I tried "ya make......", but windows says 'ya' is not recognized as an internal or external command.
Did I miss something?

**Comment by kizill** [comment]
You can fix this by running ya make from git repo root, which contains `ya.bat` file. Another solution is using relative or absolute path to ya.bat like this: ```
cd catboost\
..\ya.bat make app
```
Anyway, if you need python wheel with your cuda runtime you can use `catboost/python-package/mk_wheel.py` , see notes about running it on windows in documentation https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/

**Comment by Johnkuo** [comment]
@kizill Thanks again.
Yes, I just found that the "ya.bat" is in the root directory...This is my oversight.
I do need a python-GPU version running catboost on windows, and I tried the documentation about making python wheel you just sent to me. I failed with information as below:
(I am sorry that there are some garbled codes duo to Chinese version Windows)


F:\catboost\catboost\python-package>python.exe mk_wheel.py -DPYTHON_INCLUDE="/I C:\Anaconda3\include" -DPYTHON_LIBRARIES="C:\Anaconda3\libs\python36.lib" -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1"
Trying to build GPU version
C:\Anaconda3\python.exe F:\catboost/ya make F:\catboost\catboost\python-package\catboost --no-src-links -r --output C:\Users\GuoJian\AppData\Local\Temp\tmpq8vgovc0 -DPYTHON_CONFIG=python3-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE=/I C:\Anaconda3\include -DPYTHON_LIBRARIES=C:\Anaconda3\libs\python36.lib -DPYTHON_INCLUDE=/I C:\Anaconda3\include -DPYTHON_LIBRARIES=C:\Anaconda3\libs\python36.lib -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1 -DHAVE_CUDA=yes
Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
------- [CC] {FAILED} $(S)\catboost\cuda\cuda_lib\tasks_impl\enable_peers.cpp
command C:\Users\GuoJian\.ya\tools\v3\173608136/python F:\catboost\build\scripts\fix_msvc_output.py cl C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /FoC:\Users\GuoJian\.ya\build\build_root\hwaj\000008\catboost\cuda\cuda_lib\tasks_impl\enable_peers.cpp.obj F:\catboost\catboost\cuda\cuda_lib\tasks_impl\enable_peers.cpp /I C:\Users\GuoJian\.ya\build\build_root\hwaj\000008 /I F:\catboost /I F:\catboost\contrib\libs\cxxsupp\libcxx\include /I F:\catboost\contrib\libs\libf2c /nologo /Zm500 /GR /bigobj /FC /EHsc /errorReport:prompt /Zc:inline /DFAKEID=cython0_28_1_try5 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\winrt /IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /Ox /Ob2 /Oi /DNDEBUG /MT /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /DSSE_ENABLED=1 /DSSE2_ENABLED=1 /DSSE3_ENABLED=1 /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS -DCATBOOST_OPENSOURCE=yes -IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1/include -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_WINDOWS_KITS_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0 /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /DSTRICT /DNOMINMAX /DWIN32_LEAN_AND_MEAN failed with exit code 2
c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime.h(194): error C2371: size_t: 囟澹煌?
c:\users\guojian\.ya\build\build_root\hwaj\000008\predefined c++ types (compiler internal)(16): note: 渭size_t

f:\catboost\catboost\cuda\cuda_lib\cuda_base.h(73): warning C4297: NCudaLib::TCudaStreamsProvider::~TCudaStreamsProvider: 俣斐Ｈ肥?
f:\catboost\catboost\cuda\cuda_lib\cuda_base.h(73): note: 头一()斐ｆ范
Failed
GPU version build failed
Trying to build CPU version
C:\Anaconda3\python.exe F:\catboost/ya make F:\catboost\catboost\python-package\catboost --no-src-links -r --output C:\Users\GuoJian\AppData\Local\Temp\tmpq8vgovc0 -DPYTHON_CONFIG=python3-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE=/I C:\Anaconda3\include -DPYTHON_LIBRARIES=C:\Anaconda3\libs\python36.lib -DPYTHON_INCLUDE=/I C:\Anaconda3\include -DPYTHON_LIBRARIES=C:\Anaconda3\libs\python36.lib -DCUDA_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1 -DHAVE_CUDA=no
Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
------- [CC] {FAILED} $(S)\contrib\libs\cxxsupp\libcxx\src\utility.cpp
command C:\Users\GuoJian\.ya\tools\v3\173608136/python F:\catboost\build\scripts\fix_msvc_output.py cl C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /FoC:\Users\GuoJian\.ya\build\build_root\d2yg\000005\contrib\libs\cxxsupp\libcxx\src\utility.cpp.obj F:\catboost\contrib\libs\cxxsupp\libcxx\src\utility.cpp /I C:\Users\GuoJian\.ya\build\build_root\d2yg\000005 /I F:\catboost /I F:\catboost\contrib\libs\cxxsupp\libcxx\include /nologo /Zm500 /GR /bigobj /FC /EHsc /errorReport:prompt /Zc:inline /DFAKEID=cython0_28_1_try5 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\winrt /IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /Ox /Ob2 /Oi /DNDEBUG /MT /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /DSSE_ENABLED=1 /DSSE2_ENABLED=1 /DSSE3_ENABLED=1 /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_WINDOWS_KITS_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0 /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /DSTRICT /DNOMINMAX /DWIN32_LEAN_AND_MEAN /w /wd4456 /wd4457 -D_LIBCPP_BUILDING_LIBRARY failed with exit code 2
c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime.h(194): error C2371: size_t: 囟澹煌?
c:\users\guojian\.ya\build\build_root\d2yg\000005\predefined c++ types (compiler internal)(16): note: 渭size_t
Failed
CPU version build failed
Traceback (most recent call last):
  File "mk_wheel.py", line 232, in <module>
    wheel_name = build(arc_root, out_root, sys.argv[1:])
  File "mk_wheel.py", line 221, in build
    make_wheel(wheel_name, arc_root, so_paths['CPU'], so_paths.get('GPU', None))
KeyError: 'CPU'

**Comment by dbakshee** [comment]
Hi @Johnkuo 
It looks like you are using 32-bit compiler within 64-bit environment, so it complaints of size_t.

**Comment by annaveronika** [comment]
I'm closing the issue, feel free to reopen if you will still have problems.
