### ISSUE TITLE
best_score

### ISSUE THREAD

**Issue by m-rahimi** [catboost/catboost#338]
Does Catboost has a function to return best_score similar to LightGBM or Xgboost. I know that it prints the best score at the end of the iteration but I want to return it as an output.

**Comment by annaveronika** [comment]
It doesn't, and it's a good idea for contribution

**Comment by annaveronika** [comment]
We've added this field, you can build from source to use it. Or wait for our next release, which will happen some time around next week.
Thank you very much for great suggestion!
