### ISSUE TITLE
implement CV on GPU

### ISSUE THREAD

**Issue by Zveroloff** [catboost/catboost#339]
Problem: cv doesn't work with task_type='GPU'
catboost version: 0.8.1.1
Operating System: Windows

**Comment by annaveronika** [comment]
We are working on that right now, it will be on github in about two weeks.

**Comment by jmhsi** [comment]
Any update on this? Still getting the same error with catboost version: 0.11.1

**Comment by annaveronika** [comment]
Still working on that, very sorry for the delay. We plan to add the feature in the next release.

**Comment by andrey-khropov** [comment]
> Any update on this? Still getting the same error with catboost version: 0.11.1

The code is almost ready and we're planning to integrate it into the master branch and release next week.

**Comment by cuniculus-0** [comment]
@andrey-khropov @annaveronika thanks for all the work on this great package!

**Comment by andreynikk** [comment]
Could you please provide an update on this issue?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Internal code review is in progress.

**Comment by andrey-khropov** [comment]
The change is now in trunk - https://github.com/catboost/catboost/commit/66921d520ca13c8697dcd0d4869b0f1602cd9895. It is expected to be in the release within a couple of days.

**Comment by shivakumarj-debug** [comment]
Does this support GPU yet? Its not mentioned in the documentation and I dont see it in the APIs as well, Much appreciated!

**Comment by Petzy68** [comment]
Hi, any update on this?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
just add 'task_type': 'GPU' to the params parameter of cv

**Comment by svetloffs** [comment]
> just add 'task_type': 'GPU' to the params parameter of cv

work! thanks, @Evgueni-Petrov-aka-espetrov
