### ISSUE TITLE
what is the "ya.make"? please, use build-files for normal build system. thanks!

### ISSUE THREAD

**Issue by antonov-impulsm** [catboost/catboost#34]
good day!

what is the "ya.make"?

**how to build this project without downloading unclear binary files from doubtful origin?**

there are some normal build systems: gmake, cmake, meson, etc..

please use these tools (or some other **regular** build systems) for open source projects. (and please continue to use "ya.make" for Yandex-closed-inside projects)

thank you in advance!

**Comment by user55844** [comment]
I'm a Windows user and I don't think that CMake or gmake is a better choice in this case.

I think you should take a look on Google notes about why they choose a GYP instead of CMake:
https://gyp.gsrc.io/docs/GypVsCMake.md

But also, I think that It's a good idea for Yandex to implement a translator which will translate ya.make to the old build system formats like CMake or gmake.

**Comment by ferrr** [comment]
Hi!

We appreciate your concerns about doubtful binaries. Soon (in a matter of weeks, I hope) we'll upload sources of _ya make_ into github. On a bright side, we download binaries from a trusted domain and perform signature check of the content.

CatBoost is still a part of our monorepo, which heavily relies on _ya make_, so we don't have any plans to migrate to any other build system.

We'll consider implementing a translator to other build systems. For now, we only have such translator to MSVS.

**Comment by polymorphm** [comment]
> We'll consider implementing a translator to other build systems.

thank you! it is would be useful!

> Soon (in a matter of weeks, I hope) we'll upload sources of ya make into github

thanks a lot! I think, it may be useful too.

> ...perform signature check of the content.

no! "md5" is not "signature check" :-D :-D :-D :-D :-D

> CatBoost is still a part of our monorepo, which heavily relies on ya make, so we don't have any plans....

yes -- it is some problem for others users. in open source we have "pkg-config" and other accepted standards for making links between software collections.

but unloading your project (catboost) to guthub is big deal! anybody may create a fork for straightening the situation! in this sense you are great, I think.

**Comment by aldanor** [comment]
> Soon (in a matter of weeks, I hope)

@ferrr A gentle reminder, 4.5 months later ^

**Comment by aldanor** [comment]
@ferrr @annaveronika Another gentle reminder, 2 years later...

**Comment by andrey-khropov** [comment]
CatBoost has switched to CMake-based build since https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb. See https://catboost.ai/en/docs/concepts/build-from-source
