### ISSUE TITLE
Group_ids can't be supplied without Pools 

### ISSUE THREAD

**Issue by wingrime** [catboost/catboost#344]
Problem:  Some ranking objectives (exp. YetiRank ) requres group_ids to be supplied to train and validation sets, but `eval_set` paramter of `Catboost.fit` accepts only (X, y) tuples or Pool object. 

That's somehow inconsistent, `Catboost.fit` have `group_id` param, that makes possible to supply train group_ids but for validation group_ids you have to use Pool object

**Comment by annaveronika** [comment]
If you have many things for initialization of the validation dataset, then we want you to name them. Like (data=X, label=y, group_id=groups). To pass these parameters with the names you can use Pool class.
So I don't see what is the way to make it better - if we allow passing triplets, then we need to also allow to pass weights there, which makes it list of 4 parameters, then there are pairs and so on.

We don't want to do that - we want to have an interface which makes it harder for you to make mistakes.

**Comment by annaveronika** [comment]
I'm closing the issue as wont fix, because currently I don't see how passing triplets is better than passing Pool object. If you have ideas of what would be a better interface, please share it with us!
