### ISSUE TITLE
How to show loss function in stdout

### ISSUE THREAD

**Issue by andrey290494** [catboost/catboost#345]
Problem: when I train my CatBoostRegressor model with a loss_function = 'MAE', eval_metric = 'MAPE' , stdout shows only Learn MAPE and Test MAPE. So how can i take in consideration loss function?
Code:
![default](https://user-images.githubusercontent.com/22135338/39927105-eb4235c4-5539-11e8-9dcd-988c862afded.png)
Last iterations and a calculated MAPE
![1](https://user-images.githubusercontent.com/22135338/39927635-99c5b7aa-553b-11e8-88fd-15f4390c7360.png)

catboost version: 0.6.3
Operating System: Win 10
CPU: Intel-Core i7 - 3612QM 2.1 GHZ 
# GPU:  Nvidia GT650M

Thank you

**Comment by annaveronika** [comment]
You can look on all metric values in catboost_info/*_error.tsv files.
If you are using eval_metric='MAPE', then this metric will be used for early stop or for selecting best iteration, so we decided to show this one in stdout.
Does this solve your problem?

**Comment by andrey290494** [comment]
Is this the only way? There is no verbose setup to show both, loss func and eval metric?

**Comment by annaveronika** [comment]
Yes, that's the only way we provide, because we want the log to be as clear as possible. If we allow both losses to be output, then it will be more than one line in log, and we want it to be on one line, because then it's more clear how loss is changing - next number is under previous one. Why don't you like the idea of looking on the file with loss values during training?

**Comment by annaveronika** [comment]
Actually what we can do - we can add a flat to show training + eval metrics, but only for eval dataset, this will be still one line.
@andrey290494 Do you want to take part and to add this new logging_level?

**Comment by annaveronika** [comment]
So we decided to let stdout be as it is. And to look on other metrics than eval metric we introduces another way - it not only is written to files, but also to python list. I hope these to things will cover all usecases.

**Comment by civilinformer** [comment]
Hi, where is the python list? I do not see any discussion of the convergence history in the documents. What I am trying to do is find where eval metrics reach very specific values.

**Comment by civilinformer** [comment]
Oh, its in model.get_evals_result(). Just what I needed.
