### ISSUE TITLE
ctr_border_count has disappeared in v0.8.1?

### ISSUE THREAD

**Issue by timchurches** [catboost/catboost#349]
Problem: trying to increase the number of splits for categorical features (50 may not be enough with our data), but the ctr_border_count parameter seems to no longer be supported. How can the number of splits be increased?
catboost version: 0.8.1
Operating System: macOS 10.13.4
CPU: Intel Core i7
# GPU: NA

**Comment by Noxoomo** [comment]
Hi!

You should use simple_ctr and combination_ctr options to edit  CTR options
