### ISSUE TITLE
libunwind: getEncodedP when training MultiClass on GPU

### ISSUE THREAD

**Issue by idavydov** [catboost/catboost#352]
Hi, I'm playing with catboost and the mnist dataset. I have problems when running the following code on GPU:

```
from catboost import CatBoostClassifier
import numpy as np
import mnist
## you need to do this once in order to download the dataset
# mnist.init()

x_train, t_train, x_test, t_test = mnist.load()

model = CatBoostClassifier(logging_level='Verbose', iterations=1000, classes_count=10, loss_function='MultiClass', task_type='GPU')

model.fit(x_train, t_train, use_best_model=True, eval_set=(x_test, t_test))
```

I get the following output:
```
libunwind: getEncodedP /home/travis/build/catboost/catboost/contrib/libs/libunwind_master/src/AddressSpace.hpp:269 - unknown pointer encoding
/cm/local/apps/slurm/var/spool/job12345678/slurm_script: line 13: 138131 Aborted                 /<path removed>/Anaconda3/4.3.1/bin/python train_mnist.py
```

1. The same example works well on CPU.
2. [This example](https://tech.yandex.com/catboost/doc/dg/installation/python-installation-test-catboost-docpage/#python-installation-test-catboost) works well on GPU.

catboost version: 8.1.1, python3.6, cuda 8.0.44
Operating System: GNU/Linux x86_64
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
GPU: Tesla K80

**Comment by idavydov** [comment]
Thanks for the quick response!

**Comment by annaveronika** [comment]
same problem as #384
