### ISSUE TITLE
Catboost precompiled python library does not work under CUDA 9.0

### ISSUE THREAD

**Issue by mirekphd** [catboost/catboost#353]
### Problem
Catboost precompiled python library made available via PyPi does not work under CUDA 9.0 (NVIDIA container nvidia/cuda:9.0-cudnn7-devel), while it works correctly under CUDA 8.0 (nvidia/cuda:8.0-cudnn6-devel).

### Platform
OS platform, distribution and version (e.g. Linux Ubuntu 16.04):
Linux-4.4.0-96-generic-x86_64-with-debian-stretch-sid

Installed from: binary (catboost-0.8.1.1-cp36-none-manylinux1_x86_64.whl)

Catboost version:
```
catboost                  0.8.1.1                   <pip>
```

Python version: 3.6.5 | packaged by conda-forge | (default, Apr 6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

Conda version:
conda 4.5.3

Pip version:
pip 10.0.1 

CUDA/cuDNN version:
9.0.176 / 7.1.2
(FROM nvidia/cuda:9.0-cudnn7-devel)

GPU model:
NVIDIA GeForce 1080 Ti

CPU model:
Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz

### How to reproduce
```
pip install catboost==0.8.1.1
[..]

params = {'loss_function': 'Logloss',  [..]
          'task_type' : 'GPU'}
model = CatBoostClassifier(**params)
model.fit([...])

[..]
CatboostError: catboost/libs/train_lib/train_model.cpp:677: Can't load GPU learning library. Module was not compiled or CUDA version/driver  is incompatible with package
```

### Proposed solution(s)
1) Add CUDA 9.0 support to the pre-compiled python binary, for instance by compiling this commit or a later one: ["Add CUDA Toolkit 9.0"](https://github.com/catboost/catboost/commit/e0ea6833cac887c3f94ab7826ec17df4d5f81ec9).
2) Add Dockerfile that will compile from GitHub source a carefully selected (tested as working) commit or tag an install the compiled python library with CUDA 9.0 support (current generic compilation instructions are not satisfactory in the age of Docker).

**Comment by mirekphd** [comment]
How about then the other solution: adding to your repo a Dockerfile or a simple bash script used for compilation under CUDA 8 and 9.x?

[Rant warning] Stopping CUDA 8.0 support altogether is not recommended, as you have extremely good GPU acceleration there, cutting down model training time from hours to minutes and from minutes to seconds. Why not continue providing support for "legacy" CUDA frameworks? I know that CUDA 9.x works under older hardware (Pascal architecture), but CUDA 9.1 is not supported in some packages, e.g. H2O4GPU does not support it. On the other hand it is possible to collect all GPU-enabled libraries in a single CUDA 8.0 container that non-technical users can access and enjoy, without worrying about catboost being in the CUDA 9.1 container, and most neural nets in CUDA 8.0.

**Comment by Noxoomo** [comment]
custom compilation is very simple:  ya make -r -DCUDA_ROOT=/usr/local/cuda-9.0 for cmd-line binary, and similar command for python package

About cuda 8.0: 
Legacy CUDA version doesn't not support Volta GPUs. For correct working on Volta we need to use cuda 9-only features, so source code can't be compiled with cuda 8.0.  And we don't want to split source code to different cuda versions, because this much harder to maintain. 

Plus one container is still achievable: catboost requirements will be a version of NVIDIA driver only. CUDA 8.0 could be used with newer version of drivers, so users will just need to install a proper driver version for container.

**Comment by mirekphd** [comment]
So it looks like compilation is the only solution for CUDA 9.x. This is what I'm already doing for XGBoost and LightGBM. Note that compilation times add up if your have the 20 or so GPU-enabled ML libraries...

Maybe I should instead rant to NVIDIA for their subversioning of CUDA 9.x? There is already new and improved CUDA version 9.2 released for LTS 16.04, so some projects will surely drop your current favorite 9.1... and I will soon have 3 CUDA 9.x containers to maintain, none of which will be sufficiently universal in coverage to be useful for machine learning...

**Comment by Noxoomo** [comment]
Several CUDA version could be installed at the time. It should be sufficient to maintain one container with latest NVIDIA driver, and packages linked to a exact version of CUDA they need (without symlinking /usr/local/cuda-9.x to /usr/local/cuda)

The problem arise only when it's hard to update driver to latest version (like corporative clusters).

**Comment by mirekphd** [comment]
Ok, thank you, i will try to install CUDA 9.1 in the CUDA 9.0 NVIDIA container and then during compilation try to pin the appropriate CUDA version supported by each package, like this example from LightGBM:
```
ENV CUDA_VER 9.1
RUN [..] cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda-${CUDA_VER}/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda-${CUDA_VER}/include/ .. && \ 
    make -j $(nproc) OPENCL_HEADERS=/usr/local/cuda-${CUDA_VER}/targets/x86_64-linux/include LIBOPENCL=/usr/local/cuda-${CUDA_VER}/targets/x86_64-linux/lib
```

**Comment by annaveronika** [comment]
It should work with cuda 9.1. I'm closing the issue, please feel free to reopen if something doesn't work for you.
