### ISSUE TITLE
Classes quantity mismatches actual classes for multiple classification task

### ISSUE THREAD

**Issue by JacobLea** [catboost/catboost#354]
Problem: For multiple classification task, unique labels like [0, 1, 3] (there is no label called 2) in Pool object leads to that the final model predict 4 unique classes, which doesn't match the actual quantity of classes 3. The return of function CatBoostClassifier.predict_proba gets 4 columns, which should be 3.
catboost version: 0.8.1.1
Operating System: Windows
CPU: CPU

**Comment by annaveronika** [comment]
This is expected behavoir - this happens sometimes that classes are not represented in train, this means, you shold answer with probability 0 when you are asked about probability of this class.
If you want 3 classes you need to provide labels 0,1,2
