### ISSUE TITLE
Plot model decision tree in CatBoost Python API

### ISSUE THREAD

**Issue by saj1919** [catboost/catboost#355]
**Problem:** Not able to figure out how to plot decision tree once the model is created. I was thinking something terms similar to here --> [xgboost decision tree](https://machinelearningmastery.com/visualize-gradient-boosting-decision-trees-xgboost-python/)
Let me know if there exist any way to do the same Or let us know if this can be added as a feature.

**catboost version:** 0.8.1

**Operating System:** Ubuntu 16.04

**Machine:** aws t2.xlarge

**Comment by franz101** [comment]
Also looking for help

**Comment by isudos** [comment]
Is there any news on this issue? The functional would be very useful for model analysis.

**Comment by annaveronika** [comment]
This functionality is added in catboost 0.15
