### ISSUE TITLE
Save metric values to lists in Python after training, not only to file.

### ISSUE THREAD

**Issue by fantauzzi** [catboost/catboost#365]
Problem: CatBoostClassifier.fit() allows to plot various metrics, but I don't know how to assign them to variables
catboost version: 0.8.1
Operating System: Ubuntu 160.04 LTS 64-bit
CPU: Intel® Core™ i7-2700K CPU @ 3.50GHz × 8 
GPU: GeForce GTX 1080/PCIe/SSE2

I have trained a model calling `CatBoostClassifier.fit()`, also providing an `eval_set`. How can I fetch the best value of the optimization and evaluation metrics, for learning and evaluation datasets, and the iteration number when they were  achieved during training?

I can display all that information in a notebook by setting `plot=True`, but how can I assign it to Python variables?

For instance, `cv()` returns the wanted information, but `CatBoostClassifier.fit()` seems to return just itself.

**Comment by annaveronika** [comment]
We are writing metric values during training to files - learn_error.tsv and test_error.tsv, you can read these numbers from there.

**Comment by snovik75** [comment]
Even I files I cannot fine the eval_metric for the train set. I only see Logloss in the learn_error.tsv, but not the 'AUC'

Am I doing smth wrong?

**Comment by annaveronika** [comment]
Saving metrics in python is implemented now. It'll be on pypi in the next release. For now you can build from source using this instruction: https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/#python-installation-method-build-from-source-linux-macos.
