### ISSUE TITLE
Get error building a GPU wheel package Windows 10

### ISSUE THREAD

**Issue by Mechanix12** [catboost/catboost#370]
Problem: Get error building a GPU wheel package Windows 10
Operating System: Windows 10
CPU: AMD Ryzen 7 1700X
GPU: GTI 1080Ti
Get this error:
------- [CC] {FAILED} $(S)\catboost\cuda\cuda_lib\kernel\reduce.cu
command C:\Users\mecha\.ya\tools\v3\173608136/python C:\catboost\build\scripts\compile_cuda.py C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe -std=c++14 -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=compute_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=compute_60 -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -c C:\catboost\catboost\cuda\cuda_lib\kernel\reduce.cu -o C:\Users\mecha\.ya\build\build_root\msl7\000cb3\catboost\cuda\cuda_lib\kernel\reduce.cu.o -IC:\Users\mecha\.ya\build\build_root\msl7\000cb3 -IC:\catboost -IC:\catboost\contrib\libs\cxxsupp\libcxx\include -IC:\catboost\contrib\libs\libf2c --cflags /nologo /Zm500 /GR /bigobj /FC /EHsc /errorReport:prompt /Zc:inline /DFAKEID=3638217 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um /IC:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\winrt /IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /Ox /Ob2 /Oi /DNDEBUG /MT /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /DSSE_ENABLED=1 /DSSE2_ENABLED=1 /DSSE3_ENABLED=1 /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS -DCATBOOST_OPENSOURCE=yes -IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0/include -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt /DY_MSVC_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include /DSTRICT /DNOMINMAX /DWIN32_LEAN_AND_MEAN failed with exit code 2
Files
c1xx: fatal error C1083: Cannot open source file: 'Files': No such file or directory
Windows
c1xx: fatal error C1083: Cannot open source file: '(x86)\Windows': No such file or directory
ucrt
c1xx: fatal error C1083: Cannot open source file: 'Kits\10\Include\10.0.17134.0\ucrt': No such file or directory
Files
c1xx: fatal error C1083: Cannot open source file: 'Files': No such file or directory
Microsoft
c1xx: fatal error C1083: Cannot open source file: '(x86)\Microsoft': No such file or directory
Visual
c1xx: fatal error C1083: Cannot open source file: 'Visual': No such file or directory
Studio
c1xx: fatal error C1083: Cannot open source file: 'Studio': No such file or directory
include
c1xx: fatal error C1083: Cannot open source file: '14.0\VC\include': No such file or directory
reduce.cu
c:\catboost\contrib\libs\cxxsupp\libcxx\include\limits.h(49): fatal error C1083: Cannot open include file: 'C:\Program/limits.h': No such file or directory
Failed
GPU version build failed

**Comment by dbakshee** [comment]
Hi, we are going to fix this issue in a near release. 
The reason is nvcc mishandles the /D flags if there are spaces in their values.

**Comment by annaveronika** [comment]
This should be fixed now. Please pull the latest version from github and try building again.
I'm closing the issue, please feel free to reopen if something doesn't work for you.
