### ISSUE TITLE
No 'train' visualization in jupyter notebook

### ISSUE THREAD

**Issue by stefan-jansen** [catboost/catboost#371]
Problem: (Re-)installed `ipywidgets==7.2.1` and enabled extensions, recreated & renamed notebook several times and ran in different browsers, but no visualization for `model.train(..., plot=True)`, instead white space where the visuazliation should probably appear and text output of train/validation error.
catboost version: 0.8.1 (installed via wheel for CUDA 9.0)
Operating System: Ubuntu 16.04
CPU: 4
GPU: GeForce 1080Ti

**Comment by annaveronika** [comment]
Could you try reinstalling the library from source? We updated GPU logging recently, now it should work the same way as CPU.
Here is the instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/

**Comment by annaveronika** [comment]
GPU visualization should work fine now. I'm closing the issue, feel free to reopen if anything doesn't work for you
