### ISSUE TITLE
Error on build in linux with GPU

### ISSUE THREAD

**Issue by tranquochuy** [catboost/catboost#372]
Problem: I got error when install catboost by command.
catboost version: 0.8.1
Operating System: Ubuntu 16.04
CPU: Intel i5
GPU:  GeForce GTX 1060

Command:

> ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda

Error:

`failed with exit code 1
nvcc fatal   : Value 'c++14' is not defined for option 'std'
Failed`

**Comment by Noxoomo** [comment]
Hi!

What CUDA version do you use? And did you build from 0.8.1 release tag or from latest master?

**Comment by tranquochuy** [comment]
@Noxoomo I follow the instruction here: https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/#python-installation-method-build-from-source-linux-macos

My CUDA version is: CUDA Version 8.0.44

**Comment by Noxoomo** [comment]
CUDA 8.0 is now supported only for 0.8.1 release, for latest master version you should use CUSA 9.0

**Comment by tranquochuy** [comment]
Still can't install it. I got this error message now.

> command home/huytran/.ya/tools/v3/244387436/usr/bin -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -DCATBOOST_OPENSOURCE=yes -I/usr/local/cuda/include -nostdinc++ -DFAKEID=3638217 -DARCADIA_ROOT=/home/huytran/workspace/projects/ml/catboost -DARCADIA_BUILD_ROOT=/home/huytran/.ya/build/build_root/cyz2/000463 failed with exit code 1
nvcc fatal   : Unsupported gpu architecture 'compute_20'
Failed

**Comment by Paperone80** [comment]
Hi, 

Had similar problems but compilation with GPU worked for me as I described here in Issue [386](https://github.com/catboost/catboost/issues/386). Hope that helps.

**Comment by annaveronika** [comment]
Everything should work now, so I'm closing the issue. Please feel free to reopen if something doesn't work for you.
