### ISSUE TITLE
Can multiclass model be used in C++ API?

### ISSUE THREAD

**Issue by leezonpen** [catboost/catboost#374]
Hello,

I trained a 5 classes model in python package successfully. Now i need to use it in C++ API but it throw such error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  (TCatboostException) catboost/libs/model/formula_evaluator.h:278: Condition violated: `(int)results.size() == model.ObliviousTrees.ApproxDimension'
```

And i found some information mentioned in wrapped_calcer.h that it doesn't work on multiclass models. So i have a question about it. Can multiclass model be used in C++ API? 
It also can be some mistakes in my using multiclass model prediction, can you provide some examples about it?

**Comment by kizill** [comment]
@leezonpen definetly yes. Model evaluation code outputs probability of each class, so as verify message tells you should provide result vector that has `ApproxDimension` elements. `ApproxDimension` is number of classes in train dataset.
