### ISSUE TITLE
GPU type_task for catboost.cv()

### ISSUE THREAD

**Issue by txtds** [catboost/catboost#375]
Problem:  I would like to use GPU on cv to accelerate my hyperopt.fmin. 
But i's not possible, every time I start a cross validation (catboost.cv) I get the error.
It's a really cool lib, thank you!

catboost version: {0.8.1}
Operating System: Windows 10 x64
CPU: AMD FX 8350
GPU: GTX 1060

`---------------------------------------------------------------------------
CatboostError                             Traceback (most recent call last)
<ipython-input-24-ca331643c5f7> in <module>()
      2     Pool(X, y, cat_features=categorical_features_indices),
      3     model.get_params(),
----> 4     plot=True
      5 )

~\Anaconda3\lib\site-packages\catboost\core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, verbose, verbose_eval, plot)
   2309 
   2310     with log_fixup():
-> 2311         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified, as_pandas)
   2312 
   2313 

_catboost.pyx in _catboost._cv()

_catboost.pyx in _catboost._cv()

CatboostError: st/catboost/libs/algo/learn_context.h:123: Error: except learn on CPU task type, got GPU`

**Comment by annaveronika** [comment]
cv is not implemented on gpu jet, there is an issue for that - #339
