### ISSUE TITLE
CatBoostClassifier getting feature names

### ISSUE THREAD

**Issue by shs5fh** [catboost/catboost#377]
I've looked at the Python API documentation and couldn't find a function that returns a list of the used features by a CatBoostClassifier. Is there any way you could implement this in the future or is there a way? It's very impractical to not store feature names in my case as the train and test sets can differ in format while still holding the same features used in the classifier.

**Comment by annaveronika** [comment]
The code for that is on github now, you can build from source and use it.
It will be on pypi in the next release.
