### ISSUE TITLE
Can not use 'pinned_memory_size'

### ISSUE THREAD

**Issue by mansoori8064** [catboost/catboost#380]
**Problem**: I am trying to use 'pinned_memory_size' option in GPU mode of Catboost in Python 3.6, as it's been mentioned in the following link:
https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_parameters-list-docpage/#python-reference_parameters-list
 
but I receive 'Invalid parameter' error. Have you changed the name of this argument?

**Catboost version:** {0.8}
**Operating System:** {Ubuntu 16}
**CPU**: {Sandy Bridge}
**GPU**: {one GPU P100}

**Comment by Noxoomo** [comment]
Hi!
Currently this option works only in cmd-line, we forgot to add it to python wrapper.
Will be fixed in the next release

**Comment by annaveronika** [comment]
You can use it now by passing to CatBoost class in parameters map instead of CatBoostClassifier or CatBoostRegressor

**Comment by Noxoomo** [comment]
btw, this options value  is estimated automatically based on dataset, so you usually don't need to set in manually (if there is an error with not enough pinned memory, than this is probably a bug)

**Comment by annaveronika** [comment]
The code with the fix is on github now, you can try building from source or use the ways described above. The fix will be on pypi in the next release.

**Comment by mansoori8064** [comment]
Thanks for solving this issue!
