### ISSUE TITLE
one_hot_max_size > 129 raises exception on GPU

### ISSUE THREAD

**Issue by yt87** [catboost/catboost#382]
Problem: 
The following code::

    import pandas as pd
    import numpy as np
    import catboost as cb
    n = 130
    df = pd.DataFrame({'a': ['x'+str(i) for i in range(n)], 'b': np.random.random((n,))})
    y = np.random.random((n,)) 
    cr = cb.CatBoostRegressor(one_hot_max_size=130, task_type='GPU', logging_level='Silent')
    cr.fit(df, y, cat_features=[0])

results in error message::

     CatboostError                             Traceback (most recent call last)
     <ipython-input-48-da42b5ea4e61> in <module>()
           7 y = np.random.random((n,))
           8 cr = cb.CatBoostRegressor(one_hot_max_size=130, task_type='GPU', logging_level='Silent')
      ----> 9 cr.fit(df, y, cat_features=[0])

     ~/local/Python-3.6.3/lib/python3.6/site-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval)
       2003         model : CatBoost
       2004         """
    -> 2005         return self._fit(X, y, cat_features, None, sample_weight, None, None, None, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval)
       2006 
       2007     def predict(self, data, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

    ~/local/Python-3.6.3/lib/python3.6/site-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, group_id, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval)
        784 
        785         with log_fixup():
    --> 786             self._train(train_pool, eval_set, params, allow_clear_pool)
        787         if calc_feature_importance:
        788             if allow_clear_pool:

    _catboost.pyx in _catboost._CatBoostBase._train()

    _catboost.pyx in _catboost._CatBoost._train()

    _catboost.pyx in _catboost._CatBoost._train()

    CatboostError: catboost/cuda/gpu_data/feature_layout_common.h:50: Condition violated: `featureValuesHolder.GetType() == EFeatureValuesType::BinarizedFloat'

It appears that this happens when 130 <= n <= one_hot_max_size <= 255. The code runs fine on CPU.

catboost version: 0.8.1.1
Operating System: RedHat 7
CPU: Intel(R) Xeon(R) CPU E5-2687W v3 
GPU: Quadro K 4200

**Comment by Noxoomo** [comment]
Hi!

This is a bug, will be fixed in the next release

**Comment by annaveronika** [comment]
the code for the fix is on github now. Will be on pypi in the next release
