### ISSUE TITLE
Ipython notebook fit(plot=True) not plotting anything

### ISSUE THREAD

**Issue by mxposed** [catboost/catboost#387]
Problem: no plot when I call classifier.fit(…, plot=True)
catboost version: 0.8.1.1
Operating System: MacOS 10.13.4

Please, see attached pictures of the `fit` call (the notebook allocated space for the plot, but it's blank) and the browser developer console output.

My libraries are:
jupyter            1.0.0
jupyter-client     5.1.0
jupyter-console    5.2.0
jupyter-core       4.4.0
ipywidgets         7.0.5

![2018-06-16_18-08-59](https://user-images.githubusercontent.com/57878/41500808-73e1bfb8-7190-11e8-9b37-9e385c0af3c3.png)
![2018-06-16_18-09-22](https://user-images.githubusercontent.com/57878/41500809-73ff625c-7190-11e8-9a70-ac03a44e1cdb.png)

**Comment by annaveronika** [comment]
Looks like it's the same problem as #316
We'll are looking into this problem, please follow that issue.
