### ISSUE TITLE
Inconsistent entries in meta.tsv

### ISSUE THREAD

**Issue by yt87** [catboost/catboost#388]
Problem: 
When `task_type='CPU'` the file is

    name    experiment
    iterCount       1000
    learnErrorLog   learn_error.tsv
    testErrorLog    test_error.tsv
    timeLeft        time_left.tsv
    loss    RMSE    min

When `task_type='GPU'`, `catboost_info` is prepended:

    name    experiment
    iterCount       1000
    learnErrorLog   catboost_info/learn_error.tsv
    testErrorLog    catboost_info/test_error.tsv
    timeLeft        catboost_info/time_left.tsv
    loss    RMSE    min

*CatBoostViewer* does not like this. A workaround is to run a *sed* script on *meta.tsv*

catboost version: 0.8.1.1
Operating System: NA
CPU: NA
GPU: NA

**Comment by annaveronika** [comment]
The fix for that is already on github, it will be on pypi in the next release.

**Comment by annaveronika** [comment]
You can build from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/
