### ISSUE TITLE
Issues with model.eval_metrics

### ISSUE THREAD

**Issue by bangeneticalgorithms** [catboost/catboost#390]
Problem: This is related to #303. I'm still not sure how eval_metrics should be called. In the response to #303, the feedback was,

`test_pool = catboost.Pool(testY, preds)`

`model.eval_metrics(test_pool, metrics=["R2"])`

Both preds and tesY are (L,) numpy arrays. I tried reshaping them to (L,1) and converting them to Pool objects which did not work either on the first line (TypeError: unhashable type: 'numpy.ndarray'
)

Then I tried to concat the preds and testY (true labels) to create a (L,2) numpy array and then create a Pool object. Now line one works. But line 2 fails due to 

_catboost.CatboostError: catboost/libs/algo/apply.h:52: Insufficient float features count 2<11327

catboost version: {0.8.1}
Operating System: {RHEL 7}

**Comment by annaveronika** [comment]
Can you try writing parameter names when creating Pool object?
pool1 = Pool(data=X, label=y) - like that
I think you are passing the arguments in the wrong order. The first argument is data - which is the matrix of the features. The second is label, which is the list of label values, or true values.

**Comment by annaveronika** [comment]
After you create your Pool object, make shure that the fields are set correctly, to do that you can call methods num_row, num_col, get_label.

**Comment by annaveronika** [comment]
@bangeneticalgorithms Have you managed to run eval_metrics?
