### ISSUE TITLE
Segmentation fault in import catboost on SLES

### ISSUE THREAD

**Issue by aleksandrkislitsyn** [catboost/catboost#391]
catboost version: 0.8.1.1
Operating System: 
    NAME="SLES"
    VERSION="12-SP2"
    VERSION_ID="12.2"
    PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"

I have installed catboost 0.8.1.1 on my VM with pip3 install catboost
But i get segmentation fault when trying import catboost:
```
Python 3.4.6 (default, Mar 01 2017, 16:52:22) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
Segmentation fault (core dumped)
```

**Comment by nikolaeff** [comment]
Had the same problem with debian installation. Fixed it by installing libc6-dev package - https://packages.debian.org/stretch/amd64/libc6-dev/filelist

**Comment by aleksandrkislitsyn** [comment]
Thank you, fixed it with `zypper install glibc-devel`
