### ISSUE TITLE
CatBoostClassifier.set_params seems to have a problem

### ISSUE THREAD

**Issue by echo66** [catboost/catboost#394]
Problem: 

Greetings! 

I'm having a really strange issue with `CatBoostClassifier`. I have this small pipeline

```python
model = Pipeline([
    ('column_dropper', ColumnDropper(['SK_ID_CURR'])), 
    ('classifier', CatBoostClassifier())
])
```

When I try to use `CatBoostClassifier.set_params` inside the following snippet 

```python
def objective(params_values, params_names, X, y, cat_features, model): 
    params = dict(zip(params_names, params_values))
    
    pprint(params)
    
    model.set_params(**params)
    
    #model = CatBoostClassifier(**params)
    
    cv = KFold(n_splits=3, random_state=params['classifier__random_state'], shuffle=True)
    scores = cross_val_score(model, X, y, 
                             scoring='roc_auc', 
                             cv=cv, n_jobs=-1, 
                             fit_params={
                                 'cat_features': cat_features, 
                                 'logging_level': 'Silent'
                             })
    
    return -np.min(scores)
```

There is an error similar to this:
```
KeyError: 'random_state'
```

After changing my pipeline to 
```python
model = Pipeline([
    ('column_dropper', ColumnDropper(['SK_ID_CURR'])), 
    ('classifier', CatBoostClassifier(random_state=10))
])
```

I get this error
```
CatboostError: only one of parameters random_seed, random_state should be initialised.
```

I think this problem is related to `CatBoostClassifier.set_params` because, when I create a `CatBoostClassifier` instance with a specific set of parameters, I don't get that kind of error. 

EDIT 1: It seems related to issue #369 

EDIT 2: #369 seems to be closed and solved but there is no new release. Any plans on any new release with this fix?

catboost version: {0.8.1.1}
Operating System: {Fedora 27}
CPU: {Intel i7 7700 HQ}
GPU: {gtx1060}

**Comment by annaveronika** [comment]
Yes, the new release will come out soon, we are currently working on that. For now you can build from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/

**Comment by annaveronika** [comment]
the fix is on pypi now!
