### ISSUE TITLE
Unable to use Brier Score metric with Python?

### ISSUE THREAD

**Issue by zachwill** [catboost/catboost#397]
Hey,

Even though there's a [Brier Score metric](https://github.com/catboost/catboost/blob/00bc357f861fa54a261e4e7f3fc2da1a702ed3d2/catboost/libs/metrics/brier_score.cpp) in the C++ [metric file](https://github.com/catboost/catboost/blob/00bc357f861fa54a261e4e7f3fc2da1a702ed3d2/catboost/libs/metrics/metric.cpp#L1395), it is unavailable when using [the Python package](https://github.com/catboost/catboost/blob/00bc357f861fa54a261e4e7f3fc2da1a702ed3d2/catboost/python-package/catboost/core.py#L1939-L1941) to create a classifier.

I was hoping it could be defined and used as a string similar to `F1`, `AUC`, etc?

Thanks for making an awesome library!

* * *

catboost version: 0.8.1
Operating System: macOS High Sierra

**Comment by annaveronika** [comment]
It's already available if you build from source. It'll be available on pypi in the next release, which we are already working on.

**Comment by zachwill** [comment]
Thanks for the quick reply!
