### ISSUE TITLE
Speed up custom metrics in python

### ISSUE THREAD

**Issue by kazeevn** [catboost/catboost#398]
The current implementation of custom metrics forces the user to call the `__getitem__` for each example. This is slow (for the task at hand adding a custom metric slowed down the training ~3 times)

I think that can be alleviated by adding something like this: 
```
 def as_numpy(self):
        return numpy.asarry(<numpy.float32_t[:self._count]> self._arr)`
```
to the [`_FloatArrayWrapper`](https://github.com/catboost/catboost/blob/df9ff2c69eddb918e80a359b12aa212c8be2d288/catboost/python-package/catboost/_catboost.pyx#L470).

P. S.
I tried to test it, but couldn't manage to get the necessary includes via the `ya` build system.

**Comment by kazeevn** [comment]
Thanks for a quick reply! In principle, that would work. Do I understand correctly that in order to go this way I'll need to patch and recompile catboost and then ask my collaborators to do the same?

**Comment by annaveronika** [comment]
I would strongly recommend that - it will be much faster. And it's a small code change - just adding of one C++ class as in the example in tutorial.
And if you want to see the values of some standard metric, the good way is to add it to the library and then it'll be published on pypi in the next release. Btw we've added a bunch of new metrics recently, maybe yours is already covered.

**Comment by kazeevn** [comment]
A small update (in case someone stumbles on this issue while searching the web). Using `np.fromiter` instead of `np.array` to convert from  `_FloatArrayWrapper` to `numpy.ndarray` speeds things up a lot.

I totally agree that a compiled C++ metric will be the fastest. The allure of plug-and-play Python metrics, at least for me, is that it allows to seamlessly try new things, so thanks for including them!

P. S.
What I want to measure is the true negative rate given a single true positive rate - basically a point on the ROC curve. From the documentation it looks like it's not covered. This is a quite common metric in high-energy physics - as we use the classifier output to filter a stream of data online.

**Comment by JoshuaC3** [comment]
@kazeevn @annaveronika Could we not get a C++ speed-up, with quick, python style code by writing the metric in Cython. I have not tried this but would be worth considering.

The other option could be to use numba.

**Comment by annaveronika** [comment]
The problem is that you need to call the python (or in this case cython) code from very optimized c++ code to calculate something (for example, derivative) for each object. This call itself is not free.
So I don't think it will help. But I am very welcoming you to try optimising it, I'm sure it could be much faster than it is now.

**Comment by micyril** [comment]
I will work on this one

**Comment by micyril** [comment]
Patch https://github.com/catboost/catboost/commit/394e9231b59b7fc52ae9e5a1b395e7d6d63152c9 was submitted.
