### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by nikitaivanovvrn** [catboost/catboost#40]
From the documentation I suspected that pandas data frame is a valid input format for `CatBoostClassifier()`. However, when I run the code 

    m4 = catboost.CatBoostClassifier()
    m4.fit(X_train, y_train.factorize()[0])

it gives an error message `TypeError: expected bytes, str found`. Note that `type(X_train)` gives `pandas.core.frame.DataFrame`.

 If I change the  code to 

    m4 = catboost.CatBoostClassifier()
    m4.fit(X_train.as_matrix(), y_train.factorize()[0])

then everything is fine.

**Comment by Donskov7** [comment]
@nikitaivanovvrn, can u tell which catboost and python versions do u use?

**Comment by nikitaivanovvrn** [comment]
@Donskov7 catboost 0.1.1.3, Python 3.6.1

**Comment by Donskov7** [comment]
@nikitaivanovvrn please update CatBoost version to 0.1.1.5, it could be help, we already fixed this bug.

**Comment by wsteitz** [comment]
I can confirm that this is fixed in a recent version.
