### ISSUE TITLE
Passing categorical features into C API functions

### ISSUE THREAD

**Issue by hanky** [catboost/catboost#402]
Hello.

In Python API I can declare features as categorical using the `cat_features` parameter when creating a `Pool` object. So, If I have a feature vector like `f0,f1,f2,cat3,cat4,f5`, where `fN` are numerical features and `catN` are categorical ones, I just set `Pool(data, cat_features=[3,4])`.

How can I do the same using C API functions? 
My first guess is to use the `CalcModelPredictionFlat` function, as my categorical features are actually numbers and I can put them into the `const float** floatFeatures` argument.

Is it correct that the `CalcModelPrediction` function, which accepts `floatFeatures` and `catFeatures` arguments for categorical and numerical features, does not support end-to-end feature numbering?

**Comment by kizill** [comment]
We internally convert integers to strings and than calculate cityhash of string value. So no, it is incorrect to do that way.

**Comment by hanky** [comment]
Then how do I pass the following feature vector `f0,f1,f2,cat3,cat4,f5` to the C API predict function?

**Comment by dlihhats** [comment]
@hanky The following issue I raised some time ago might help with passing features to C API. I put sample code there as well. 
https://github.com/catboost/catboost/issues/331

**Comment by kizill** [comment]
@dlihhats btw, now we have single object function :)

**Comment by hanky** [comment]
In my case I needed to have a single float array of both numerical and categorical features with end-to-end numbering, so I've ended up with this code:
```
float num_feat_0 = 0.5;
float num_feat_1 = 0.77;
float cat_feat_2 = 3;

float features[3];
features[0] = num_feat_0;
features[1] = num_feat_1

char cat_buf[10];
snprintf(cat_buf, 10, "%d", cat_feat);
int cat_feat = GetStringCatFeatureHash(cat_buf, strlen(cat_buf));
features[2] = *(float*)(&cat_feat);

const float *catboost_features = features;

double result[1] = { 0 };
CalcModelPredictionFlat(model, 1, &catboost_features, 81, result, 1))
```
I don't know if this approach is completely correct, but at least it gives the same results as in the Python predict API.

**Comment by kizill** [comment]
It's correct to do like this, also you can do this way:
```cpp
float num_feat_0 = 0.5;
float num_feat_1 = 0.77;
float cat_feat_2 = 3;

float floatFeaturesArr[2];
floatFeaturesArr[0] = num_feat_0;
floatFeaturesArr[1] = num_feat_1

char catFeatureBuf[10];
snprintf(cat_buf, 10, "%d", cat_feat);
double result[1] = { 0 };

if (!CalcModelPredictionSingle(model, floatFeaturesArr, 2, &catFeatureBuf, 1, result, 1))) {
    printf("%s", GetErrorString());
}
```
