### ISSUE TITLE
Visualization is not showing up in Notebook

### ISSUE THREAD

**Issue by zulkuf** [catboost/catboost#406]
Problem: I was happily using model visualization in version 0.8.1.1 but after upgrading to 0.9.1.1, it disappeared and I only get the following: 

![image](https://user-images.githubusercontent.com/1563066/42448816-c041422a-837e-11e8-8b33-f221236398f3.png)

I have ipywidgets installed and enabled. 

catboost version: {0.9.1.1}
Operating System: {Windows 10}
CPU: {Intel i7}

**Comment by annaveronika** [comment]
Could you please try updating jupyter notebook and ipywigets to the last version and rerun the notebook?

**Comment by zulkuf** [comment]
I did but update did not help. I notice something interesting that if I put less than ~165 features in the model the plot doesn't show up otherwise it does. In any case, fitting goes well.

**Comment by annaveronika** [comment]
This should be fixed now, please try building from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/

Closing the issue. Feel free to reopen, if something doesn't work for you.
