### ISSUE TITLE
C++ evaluator for ARM architecture

### ISSUE THREAD

**Issue by flux-wrk** [catboost/catboost#408]
Problem: As of now, according to [this tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/advanced_tutorials/catboost_model_export_as_cpp_code_tutorial.md), catboost doesn't support cpp evaluator compilation for ARM architectures.
Is it any plans for one of following solutions:
- Adding make/CMake/bazel/other build system, in which we can use arm toolchain
- Adding cross-compilation feature to ya.make or opensourcing it as someone promised in #34 back in 2017 
- Adding option to export model into json format as was asked in #202, so we can implement evaluator ourselves 

In my case, exporting model as code doesn't solve my problem.

catboost version: **9.1.1**
Operating System: **Linux**
CPU: **ARM v7 hf**

**Comment by annaveronika** [comment]
We have added make files here: https://github.com/catboost/catboost/tree/master/make
But they are for python package and for cmdline app.
Opensourcing our build system is a very big task, larger than we were thinking initially, so we decided to provide makefiles instead.
We are now working on the json model, so yes, we will provide it in one of the next releases.

And for now I can also suggest you to try using the header only applier: 
https://tech.yandex.com/catboost/doc/dg/concepts/c-plus-plus-api_header-only-evaluator-docpage/
But it only supports numerical features.

**Comment by flux-wrk** [comment]
I actually do use header only evaluator now, and it forces me to not have categorical features and use one classifier per class instead of single multiclass classifier.
In my use case I need to execute model that
- makes use of categorical features
- multiclass
- runs on ARM

And, unfortunately, all kinds of evaluators for now misses at least one of this features.

**Comment by ahrex** [comment]
Hello!

I have a similar problem with `catboost`, where I cannot build it on ARMv8. The `ya` build system is currently x86-only, and the current Makefiles don't support this architecture.

Would this ticket suffice for general ARM support, or should I file a new bug for catboost on ARMv8, specifically?

Thanks,
Alex

**Comment by nikalras** [comment]
@annaveronika we have the same problem regarding ARM support, any chance to bump this up the roadmap?

**Comment by annaveronika** [comment]
We have supported ONNX format now. Arm nn library has onnx support. Could you try it now?

**Comment by nylocx** [comment]
Does ONNX have support for multiclass classification?

And another show stopper is:
> Only models trained on datasets without categorical features are currently supported.

I really love catboost for the way it handles categorical features and how it does multiclass classification. If there is any way I can run this on ARM on my jetson nano cluster this would be plain amazing.

**Comment by kizill** [comment]
Now everything works just as planned, sorry for that crazy delay 🙀
To compile without CUDA support with cross-compilation toolkit:
```
./ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app
```
To compile with SBSA CUDA with cross-compile toolkit:
```
./ya make -r -DHAVE_CUDA=yes --target-platform default-linux-aarch64 catboost/libs/model_interface/ -DCUDA_ROOT=/usr/local/cuda-11.3/
```
So now i'm closing as DONE 🥳
