### ISSUE TITLE
ya-bin for ppc64le arch

### ISSUE THREAD

**Issue by sw1sh** [catboost/catboost#411]
Problem: ya-bin fails on ppc64le architecture 
catboost version: latest
Operating System: Ubuntu

`ERROR: [Errno 8] Exec format error: '/root/.ya/tools/a80fc73866_d/ya-bin'`

What is this ymake tool? Where can I find it and compile it?

**Comment by tusaty** [comment]
@sw1sh +1, thanks for your efforts. I've switched to xgboost for now, getting very close results.

**Comment by annaveronika** [comment]
Opensourcing our build system appeared to be a very big project, more than we were thinking initially. For that reason we decided to provide make files for those who doesn't want to use ya make. So please use makefiles: https://github.com/catboost/catboost/tree/master/make

**Comment by annaveronika** [comment]
@sw1sh Did the make file work for you?

**Comment by annaveronika** [comment]
I hope it worked, feel free to reopen if it didn't work

**Comment by cdalvaro** [comment]
I miss a makefile for macOS.

Could it be possible to add it?

Have you planned adding support for cmake?
