### ISSUE TITLE
R Build fails Windows 10, VS2017, x64

### ISSUE THREAD

**Issue by ciberger** [catboost/catboost#412]
Problem: {Unable to compile current Github version on Windows 10}
catboost version: {main branch}
Operating System: {Windows 10 Enterprise. Version 10.0.16229 Build 16299}
CPU: {Intel i7-7600U}
GPU: {Intel HD Graphics 620}

After going through issues #378 (Build fails Windows 10, VS2015 x64), #393 (build failed windows10 ,vs2017,cuda9.1,x64) and #278 (Error in building Python GPU package in Windows), I was not capable to compile current Catboost version. 

**Error log**
```
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/test/AppData/Local/Temp/RtmpekMfHa/devtools10f0293362be/catboost-catboost-48d8acd/catboost/R-package"  \
  --library="C:/Users/test/Documents/R/win-library/3.5" --install-tests 
*installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/Users/test/AppData/Local/Temp/RtmpekMfHa/devtools10f0293362be/catboost-catboost-48d8acd/catboost/R-package/src/../../../ya.bat make -r -o ../../..
Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
Config was not generated due to errors in C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py", line 2498, in <module>
    main()
  File "C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py", line 2491, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py", line 518, in __init__
    self.tc = self._get_toolchain_options()
  File "C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py", line 627, in _get_toolchain_options
    detector.detect(self.params['params'].get('c_compiler'), self.params['params'].get('cxx_compiler'))
  File "C:\Users\test\AppData\Local\Temp\RtmpekMfHa\devtools10f0293362be\catboost-catboost-48d8acd\build\ymake_conf.py", line 885, in detect
    raise ConfigureError('Could not determine custom compiler version: {}'.format(c_compiler))
ConfigureError: Could not determine custom compiler version: cl.exe
make: *** [Makefile.win:6: all] Error 1
ERROR: compilation failed for package 'catboost'
*removing 'C:/Users/test/Documents/R/win-library/3.5/catboost'
In R CMD INSTALL
Installation failed: Command failed (1)
```

**Software installed**
- Installed Visual Studio Build tools 2015
- Visual Studio Community 2015 (v 15.7.5): VC++ 2017 version 15.6 v14.13 and CMake

**R session information**
- R version 3.5.0 (2018-04-23)
- Platform: x86_64-w64-mingw32/x64 (64-bit)
- Running under: Windows >= 8 x64 (build 9200)

**Visual Studio Build Tools now include the VS2017 and VS2015 MSVC Toolsets**
https://blogs.msdn.microsoft.com/vcblog/2017/11/02/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/

Here an extract of the new VS 2017 Build Tools, seems they modify previous directory structure which might cause the error

> The Visual Studio 2017 command prompts work as expected. You can easily modify them to create command prompts for the VS 2015 v140 MSVC tools. If you go into the folder C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build you’ll find four developer command prompts (named vcvars*.bat). Pick any one and create a copy to edit.

Thanks in advance!

**Comment by annaveronika** [comment]
Because we had many problems with people trying to install R package on Windows, we now provide R binaries together with the release. This time we will add it also, it will be this week, sorry for the wait!

**Comment by ciberger** [comment]
Hi Anna, I'm really happy to hear that! Last week I spent more than half a day installing and reinstalling all the requirements listed on the installation guide and following the recommendation from Github. None of them worked at all. But! gladly there's a great team behind this project! Keep it up!
