### ISSUE TITLE
R Catboost install v0.9

### ISSUE THREAD

**Issue by StatMixedML** [catboost/catboost#413]
Problem:{R Catboost install v0.9}
catboost version: {0.9}
Operating System: {Linux}

Having problems with the R installation of catboost v0.9 using devtools::install_url("URL"). To install previous versions, I used

**devtools::install_url("https://github.com/catboost/catboost/releases/download/v0.8.1/catboost-R-Linux-0.8.1.tar")**

I checked the release page but there is no link as "catboost-R-Linux-0.9.tar". Any suggestion how to do it for the new version?

**Comment by annaveronika** [comment]
We have not jet added the binary, we'll add it this week, sorry for the wait!

**Comment by annaveronika** [comment]
The package is published now
