### ISSUE TITLE
Full list of available hyperparameters

### ISSUE THREAD

**Issue by Oktai15** [catboost/catboost#414]
CatBoost has excellent docs, but in terms of hyperparameters list, there is some problem.

The next link gave me one list of hyperparameters (see the list of parameters):
https://tech.yandex.com/catboost/doc/dg/concepts/r-reference_catboost-train-docpage/

But this link gave me not fully list:
https://tech.yandex.com/catboost/doc/dg/concepts/parameter-tuning-docpage/

Where truth list is located and why different languages have different list of parameters (I couldn't find the same list for Python)?

**Comment by annaveronika** [comment]
The parameter tunning page mentions only the most important in terms of quality parameters. They are the same for R and Python. There are more parameters, you can see the whole list in R and Python documentation.
