### ISSUE TITLE
Please update catboost conda package on conda-forge

### ISSUE THREAD

**Issue by Ingvar-Y** [catboost/catboost#416]
Problem: conda-forge package is still at version 0.8.1. There is 0 contributors at catboost-feedstock repository so I guess the best place to ask for it is here.

**Comment by scopatz** [comment]
You can also open an issue on the feedstock

**Comment by annaveronika** [comment]
we are working on the update

**Comment by sab** [comment]
Hi @Ingvar-Y! Conda-forge version updated, https://github.com/conda-forge/catboost-feedstock
