### ISSUE TITLE
st/catboost/libs/train_lib/train_model.cpp:800: Can't load GPU learning library. Module was not compiled or CUDA version/driver  is incompatible with package

### ISSUE THREAD

**Issue by aassdd654** [catboost/catboost#417]
Problem: task_type = 'GPU' add to the demo but met error 
catboost version: catboost-0.9.1.1 via conda
Operating System: Win 10 x64
CPU: {CPU}
GPU: {GPU}  Nvidia  Quadro M2200 

Sample Coding: 

import numpy as np
from catboost import CatBoostClassifier
train_data = np.random.randint(0, 100, size=(100, 10))
train_label = np.random.randint(0, 2, size=(100))
test_data = np.random.randint(0, 100, size=(50, 10))
model = CatBoostClassifier(iterations=2, depth=2, learning_rate=1, 
                           loss_function='Logloss', logging_level='Verbose', 
                           task_type = 'GPU')
model.fit(train_data, train_label, cat_features=[0,2,5])
preds_class = model.predict(test_data)
preds_proba = model.predict_proba(test_data)
print("class = ", preds_class)
print("proba = ", preds_proba)

Error: 
st/catboost/libs/train_lib/train_model.cpp:800: Can't load GPU learning library. 
Module was not compiled or CUDA version/driver  is incompatible with package

**Comment by aassdd654** [comment]
I'm using cuda_9.0.176_win10.exe, do it matter?

**Comment by aassdd654** [comment]
Tried with CUDA 8.0 same error

**Comment by aassdd654** [comment]
I ran import catboost.gpu._catboost, but got error 
DLL load failed: The specified module could not be found.

**Comment by Noxoomo** [comment]
Current version requires CUDA 9.1
 
We will soon make packages, that will not depend on cuda version on machine, just on proper Nvidia driver

**Comment by Paperone80** [comment]
Hi, 

I realize you are under Win10 maybe this points you into the right direction. I got the same error message under Red Hat Enterprise Linux 7.5. Also, I am using Jupyterhub. I had to set the folder permissions of the st/catboost/* -folder and subfolders that every user can Read/Write/Execute. After that pip uninstall catboost and pip install catboost*.whl again. And restart the python kernel. 

Also, try the following. Change the device number to the GPU one in your system:
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import catboost.gpu._catboost
```

Hope this helps.

**Comment by annaveronika** [comment]
This should be solved, please try pulling the latest version from github and building again.
I'm closing the issue, feel free to reopen, if something doesn't work for you.

**Comment by CoderCoderCoder** [comment]
Hi,

I just ran into the similar problem. If I execute a .py file directly from command line with catboost GPU support - everything works like a charm. Same done from Jupyter or Spyder results in:

> CatboostError: st/catboost/libs/train_lib/train_model.cpp:800: Can't load GPU learning library. Module was not compiled or CUDA version/driver  is incompatible with package

I have CUDA 9.1 and installed catboost with "pip install catboost". My OS is Windows 10 Pro.

**Comment by Paperone80** [comment]
@CoderCoderCoder, have you found the steps in: [393](https://github.com/catboost/catboost/issues/393)?   

Given your CUDA v9.1 and Win10 environment, the [binary releases of CatBoost](https://github.com/catboost/catboost/releases) don't support it.

Check the note [here](https://github.com/catboost/catboost/releases)

> Only CUDA 8.0 is supported. Windows users must build the binary from a local copy if GPU support is required and the installed version of CUDA differs from 8.0.

**Comment by CoderCoderCoder** [comment]
@Paperone80 Thanks for your comment, but how it it possible then that everything works just fine with GPU training if I execute scripts directly from the command line, but same script executed in Spyder/Jupyter produces such an error? I really don't get it..... Also as far as I can judge on the official Catboost website, now CUDA 9.1 is supported across any OS.

**Comment by Noxoomo** [comment]
How do you run Jupyter? This could be if you have different environment variables in Jupyter and cmd-line launch.

Btw, we'll ship a new release soon with static linking of CUDA and dependence on installed CUDA will be removed (you'll just to have proper NVIDIA driver)

**Comment by CoderCoderCoder** [comment]
I figured out what was the issue, indeed it was about dynamic linking of CUDA and PATH variables. I have 3 CUDA libs in my system - 9.0, 9.1 and 9.2, if I change the path to 9.2 instead of 9.1 such error occurs. Anaconda launcher picked up the wrong lib, contrary to PowerShell, which already had the proper 9.1 lib path. So indeed a static linking would be probably better here, to avoid such situations :-). Unfortunately one has to have lots of CUDA libraries present as different frameworks use different versions of CUDA (quite annoying btw, I hope this can be somehow solved in the future).
