### ISSUE TITLE
ImportError: cannot import name 'CatBoostRegressor'

### ISSUE THREAD

**Issue by gkourogiorgas** [catboost/catboost#422]
Problem: {After installing for first time the code ran. Then I closed and re-opened spyder and I got this error:
```from catboost import CatBoostRegressor
Traceback (most recent call last):

  File "<ipython-input-9-d222a454d36a>", line 1, in <module>
    from catboost import CatBoostRegressor

  File "C:\Users\gkourogiorgas\Documents\MEGAsync\Demand Forecasting\catboost.py", line 33, in <module>
    from catboost import CatBoostRegressor

ImportError: cannot import name 'CatBoostRegressor'```}
catboost version: {0.9.1.1}
Operating System: {Win10 64bit}
CPU: {i7}
# GPU: {integrated}

**Comment by gkourogiorgas** [comment]
Never mind. The error was that I named the code file catboost.py and it was conflicting with the import statement

**Comment by hannody** [comment]
> Never mind. The error was that I named the code file catboost.py and it was conflicting with the import statement
Got the same issue, catboost.py caused the problem.
