### ISSUE TITLE
Update shap values tutorial

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#423]
Looks like [SHAP](https://github.com/slundberg/shap) was updated, and now neither of the examples from [tutorial](https://github.com/catboost/tutorials/blob/master/advanced_tutorials/shap_values_tutorial.ipynb) is working. Could you please update the tutorial?

**Comment by annaveronika** [comment]
Thanks for poining this out! We'll update the tutorials soon.

**Comment by annaveronika** [comment]
Tutorials are now updated.
