### ISSUE TITLE
is there a spark wrapper/interface of catboost

### ISSUE THREAD

**Issue by StanWang798** [catboost/catboost#424]
I'm currently using spark as my main data science platform and have xgboost and lightgbm worked out. Does catboost has any spark interface?

**Comment by annaveronika** [comment]
Is duplicate of #153

**Comment by ashishanand7** [comment]
Do let us know the status on Spark support.
Thanks for all the hardwork to your team. Catboost is awesome.

**Comment by ryukinix** [comment]
Any news on that?

**Comment by annaveronika** [comment]
We will write the updates when we have them in issue #153
