### ISSUE TITLE
Weird exception as default parameter

### ISSUE THREAD

**Issue by vanillechai** [catboost/catboost#430]
Problem: Getting empty error message, see below
catboost version: 0.9.1.1
Operating System: Debian 3.16.43-2+deb8u5
CPU: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz

I reduced the problem to the following code fragment:
```
from catboost import CatBoostRegressor

class Foo:
    def foo(self, bar=CatBoostRegressor()):
        pass
```
executing or importing this gives:
```
Error in sys.excepthook:

Original exception was:
```

I could reproduce this on Linux and MacOS.
The error does not seem to be a real exception or error, but a confusing message.

**Comment by annaveronika** [comment]
This should be fixed now - please try building the latest version from source using this instruction https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/
and check if everything works.
