### ISSUE TITLE
impossible to find cudart64_91dll。。my cuda version 9.2

### ISSUE THREAD

**Issue by zslcodestorehouse** [catboost/catboost#434]
Problem: {problem description}The installation of exe prompts that it is impossible to find cudart64_91dll. My cuda is version 9.2 .Is there a solution without changing the cuda version?
catboost version: {version}catboost-cuda-0.9.1.1.exe
Operating System: {OS}win10
CPU: {CPU}8750h
GPU: {GPU}gtx1060

**Comment by annaveronika** [comment]
For current version of catboost you need to have cuda 9.1 installed. You don't have do uninstall your cuda 9.2, you can have both of them.

**Comment by annaveronika** [comment]
Closing the issue, feel free to reopen if you will still have problems.
