### ISSUE TITLE
Tutorial for categorical features parameters

### ISSUE THREAD

**Issue by mmortazavi** [catboost/catboost#436]
Problem: **How should I pass the CTR setting to access different way of handle categorical features under CTR settings?** 
catboost version: catboost-0.9.1.1
Operating System: macOS 10.13.4

I asked this question in _datascience.stackexchange_ a few months back but I have got no responses. Please see the detailed question [here](https://datascience.stackexchange.com/questions/27003/catboost-categorical-features-handling-options-ctr-settings). 

The [documentation](https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_parameters-list-docpage/) about passing this parameter is not quite clear to me. For example, how should I pass _simple_ctr_ (string)? The documentation says: 

> ['CtrType[:TargetBorderCount=BorderCount][:TargetBorderType=BorderType][:CtrBorderCount=Count][:CtrBorderType=Type][:Prior=num_1/denum_1]..[:Prior=num_N/denum_N]',
>  'CtrType[:TargetBorderCount=BorderCount][:TargetBorderType=BorderType][:CtrBorderCount=Count][:CtrBorderType=Type][:Prior=num_1/denum_1]..[:Prior=num_N/denum_N]',
>   ...]

A minimal example is highly appreciated.

**Comment by annaveronika** [comment]
Sure, thanks for pointing this out! We'll provide a tutorial for that.

**Comment by mmortazavi** [comment]
Still no documentation? I just checked, I did not find anything. Thanks

**Comment by annaveronika** [comment]
Some simple examples are now present in docs: https://catboost.ai/docs/concepts/python-reference_parameters-list.html

**Comment by annaveronika** [comment]
Btw we would greatly appreciate any help!

**Comment by mmortazavi** [comment]
Excellent, I will give it a go and let you know. About help, if I know how I am more than happy to contribute.

**Comment by mmortazavi** [comment]
Sorry for such a long delay, it works with the examples. Thanks!
