### ISSUE TITLE
GetIntegerCatFeatureHash in Python

### ISSUE THREAD

**Issue by hanky** [catboost/catboost#438]
Hello.

How do I emulate the `GetIntegerCatFeatureHash` function behaviour in Python? I know that internally it uses CityHash64, but I can't get the same results in Python and C.

C:
```
int val = 777;
printf("GetIntegerCatFeatureHash(%d) = %d\n", val, GetIntegerCatFeatureHash(val));
```
output:
```
GetIntegerCatFeatureHash(777) = -571044564
```

Python3:
```
from cityhash import CityHash64
print(CityHash64('777') & 0xffffffff)
```
output:
```
1509514830
```

**Comment by annaveronika** [comment]
Do you need this to use model as python code?

**Comment by annaveronika** [comment]
This probably was the case. We changed our python model representation so that it doesn't need the CityHash, see our latest release 0.10.
Closing the issue. If you have more questions, please comment, we'll reopen it.
