### ISSUE TITLE
Wrong estimation of total/remaining time

### ISSUE THREAD

**Issue by evilmucedin** [catboost/catboost#44]
You can see that total/remaining time for the last 20 iterations are wrong: https://pastebin.com/Z2tXt7kk

**Comment by adamant-pwn** [comment]
Could you please provide some elaborations on how did you get such results?

**Comment by evilmucedin** [comment]
I ran catboost on my MacBook Pro using the following command:
> 11:54 denplusplus@denplusplus-mbp:~/Temp/catboost/search$ ../../catboost.out/catboost/app/catboost fit --learn-set catboost_features_learn --column-description catboost.cd  --test-set catboost_features_test  --verbose --loss-function=Logloss

**Comment by adamant-pwn** [comment]
Is it consistently reproduced if you run it again?

**Comment by annaveronika** [comment]
MATRIXNET-760

**Comment by evilmucedin** [comment]
Thank you, Anna-Veronika :)

**Comment by annaveronika** [comment]
This is fixed in the last version.
