### ISSUE TITLE
Multiclass classification class labels

### ISSUE THREAD

**Issue by kdeore2** [catboost/catboost#441]
Problem: {I am doing a multiclass classification that consists of integers 1,2,3,4 but the catboost classifier reorders it to 0,1,2,3. How can I stop that?}

**Comment by sergmiller** [comment]
Hi @kdeore2 

Thank you for reporting about this problem it will be fixed soon.

You could build catboost from github few days later or wait for next release.
For now you should convert all labels explicitly to 0,1  ... {number of unique classes} - 1
Alternatively you may try to use[ catboost command-line package](https://tech.yandex.com/catboost/doc/dg/concepts/cli-reference_train-model-docpage/) where multiclass labels are recognized properly.

Moreover automatic class names will be added to python-package in next catboost release.

**Comment by annaveronika** [comment]
The fix is on github now. Please try building from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/
