### ISSUE TITLE
Catboost 0.9 fails to load .cbm model

### ISSUE THREAD

**Issue by ms-lilibeth** [catboost/catboost#442]
Half a year ago I opened the issue #235, the solution proposed by @kizill helped me. Today I've found out that I have got some more outdated but essential models, and I failed to convert catboost model from coreml to cbm format **with the catboost 0.9.1.1**: 
`m = CatBoost().load_model('model.coreml', format='coreml')  # OK`
`m.save_model('model.cbm')  # OK`
`m = CatBoost().load_model('model.cbm')  # fails with AttributeError`

```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5c7a3719c115> in <module>()
----> 1 m = CatBoost().load_model('model.cbm')

/usr/local/lib/python3.5/dist-packages/catboost/core.py in load_model(self, fname, format)
   1584         if not isinstance(fname, STRING_TYPES):
   1585             raise CatboostError("Invalid fname type={}: must be str().".format(type(fname)))
-> 1586         self._load_model(fname, format)
   1587         return self
   1588 

/usr/local/lib/python3.5/dist-packages/catboost/core.py in _load_model(self, model_file, format)
    887         setattr(self, '_random_seed', self._object._get_random_seed())
    888         setattr(self, '_learning_rate', self._object._get_learning_rate())
--> 889         for key, value in iteritems(self._get_params()):
    890             self._set_param(key, value)
    891 

/usr/local/lib/python3.5/dist-packages/catboost/core.py in _get_params(self)
    905 
    906     def _get_params(self):
--> 907         params = self._object._get_params()
    908         init_params = self._get_init_params()
    909         for key, value in iteritems(init_params):

_catboost.pyx in _catboost._CatBoost._get_params()

_catboost.pyx in _catboost._CatBoost._get_params()

AttributeError: 'NoneType' object has no attribute 'iteritems'
```

That problem does not appear with catboost 0.8 or older.

catboost version: 0.9.0, 0.9.1.1
Operating System: Ubuntu 16.04

**Comment by kizill** [comment]
Sorry for this bug! We will fix this ASAP.

**Comment by annaveronika** [comment]
The fix is on github now. Please try building from source using this instruction: https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/
It will be on pypi some time in September, when we make a new release.
