### ISSUE TITLE
get_object_importance() has no any debug messages

### ISSUE THREAD

**Issue by lukyanenkomax** [catboost/catboost#444]
Problem:  There is no any runtime progress bar or debug messages in `get_object_importance()` method of `CatBoostClassifier`. This method has no any `verbose` parameter. It makes  current state of data processing  completely unclear.
Catboost version 0.9.1.1
Operating System: Ubuntu 16.04
CPU: ?
GPU: Tesla K80

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/pull/575 - this pr will fix it

**Comment by annaveronika** [comment]
The code is on github now, will be out in the next release 0.12 which will be in the end on this week or in the begginning of next week. Thanks a lot to our contributor @neer201!
