### ISSUE TITLE
Categorical variables dominating feature importance

### ISSUE THREAD

**Issue by Rajat700** [catboost/catboost#446]
Problem: {I am solving a regression problem using Catboost regressor. Everytime categorical features are dominating the feature importance. Numerical variables are getting shadowed. If I discretize a numerical variable into some categories then that feature also starts coming at the top of feature importance. Can anyone explain why this might be happening. Is there any parameter that I can tune so that other numerical features don't get shadowed? }
catboost version: {0.9.1.1}
Operating System: {Windows 10}
CPU: {CPU}

**Comment by dlihhats** [comment]
Try setting the L2 parameter in the range of 30-50 and see if helps to decrease your categorical features importance and improve the score on your validation set.

**Comment by Sandy4321** [comment]
dlihhats , can you answer on this ?
