### ISSUE TITLE
random_strength parameter does not seem to work

### ISSUE THREAD

**Issue by vprokopev** [catboost/catboost#448]
Problem: I tried to set random_strength from 10^-6 to 10^6 and nothing seems to change after is terms of variance of the model. My parameters are: {'iterations':300, 'verbose':10, 'learning_rate':0.75, "depth":3, 'rsm':0.45, 'random_strength':100}
catboost version: Just intalled it with Conda, so, latest, I guess.
Operating System: Ubuntu

**Comment by annaveronika** [comment]
@vprokopev @ideological We have here explanation of the most important parameters in training: https://tech.yandex.com/catboost/doc/dg/concepts/parameter-tuning-docpage/. You also can find explanation of random_strength there. This parameter doesn't always have effect on the training, but sometimes it helps to prevent overfitting.

**Comment by annaveronika** [comment]
Actually we checked it for Ordered boosting only, it seems like it's not working for Plain boosting, which you probably have encountered. We are now checking why it doesn't work for Plain boosting. Thanks a lot for pointing it out and sorry that we didn't understand that it is broken from the first time.

**Comment by yazevnul** [comment]
@vprokopev @ideological, hey, it's been fixed in https://github.com/catboost/catboost/commit/218908091d3f4fc004b32e1f4b5a8436dc39081e#diff-d22877936aae879bfbee3b529fb2633a
