### ISSUE TITLE
CatBoostClassifier with gpu support not working.

### ISSUE THREAD

**Issue by bhavikapanara** [catboost/catboost#449]
Problem: {
when I run catboostclassifier It gives me the error:
`clf_cat = CatBoostClassifier(task_type = 'GPU')`

CatboostError: catboost/libs/train_lib/train_model.cpp:800: Can't load GPU learning library. Module was not compiled or CUDA version/driver  is incompatible with package

However, my system has cuda 9.2 version installed.

I have installed catboost using wheel. [I have follow this link for installation](https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/)

In step 2, for gpu support have to set '-DCUDA_ROOT' parameter value to the path of cuda.
so, I run this command : 
`python catboost/catboost/python-package/mk_wheel.py -DCUDA_ROOT="/usr/local/cuda/"`
After processing this command terminal show me this output.
`GPU version build failed`
}
catboost version: {version}
Operating System: {Ubuntu}
CPU: {CPU}
GPU: {GPU}

Please help me to solve it out.

**Comment by annaveronika** [comment]
You need CUDA 9.1 for the latest version of the library. You can read about this in documentation: https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-pip-install-docpage/
Please try installing it. It is possible to have several versions on your machine, so you don't need to uninstall 9.2
