### ISSUE TITLE
CatBoost Viewer Documentation Typo

### ISSUE THREAD

**Issue by abaspinar** [catboost/catboost#45]
There is a minor typo at the documentation for CatBoost Viewer. 

`nmp install catboost-viewer` should be `npm install catboost-viewer`

**Comment by veged** [comment]
which one documentation you mean? https://github.com/catboost/catboost-viewer here looks fine

**Comment by abaspinar** [comment]
Sorry for the misunderstanding.
I meant https://tech.yandex.com/catboost/doc/dg/concepts/visualization_catboost-viewer-docpage/#visualization_catboost-viewer page.

**Comment by veged** [comment]
no problems ;-) thank you for feedback!
