### ISSUE TITLE
Wrong predictions from saved model in python format

### ISSUE THREAD

**Issue by bedapisl** [catboost/catboost#452]
Problem: Predictions of `CatBooost.predict()` method differ from predictions of `apply_catboost_model()` method from exported model in Python format.
catboost version: 0.9.1.1
Operating System: Debian
CPU: x86_64

Example script:
```
from catboost import CatBoost

train_features = [[1,2,3,4,5],[6,7,8,9,0],[1,3,5,7,9],[9,7,5,4,3]]  #random numbers
train_targets = [1,0,1,0]
test_features = [[2,4,5,7,5],[2,4,1,2,3],[5,4,6,3,2],[5,6,3,2,4]]

params = {'depth' : 2, 'iterations' : 1, 'random_seed' : 0}
     
model = CatBoost(params)
model.fit(train_features, train_targets)

predictions = model.predict(test_features)

model.save_model("minimal_error_model.py", format="python")

from minimal_error_model import apply_catboost_model

exported_predictions = []
for test_row in test_features:
    exported_predictions.append(apply_catboost_model(test_row))

print(predictions)
print(exported_predictions)
```
output:
```
0:	learn: 0.7023404	total: 47.3ms	remaining: 0us
[0.006 0.    0.    0.   ]
[0.007499999832361937, 0.007499999832361937, 0.0, 0.00599999986588955]
```

**Comment by annaveronika** [comment]
This is a bug in saving the model as python code. It works incorrectly if the model has not used some feature. We are working on the fix now. Very sorry for inconvenience.

**Comment by annaveronika** [comment]
We fixed this issue with this commit: https://github.com/catboost/catboost/commit/16df1ef236e7eac655237e54aa79c8645898dcc6

Please build from source using this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/#python-installation-method-build-from-source-linux-macos

We will also publish the new version on pypi during this week.
