### ISSUE TITLE
Unsupervised Learning with CatBoost

### ISSUE THREAD

**Issue by StatMixedML** [catboost/catboost#453]
Problem: {Unsupervised Learning with CatBoost}
catboost version: {all}
Operating System: {all}

Dear CatBoost developer team,

besides the high accuracy of CatBoost of supervised learning tasks, I was wondering if you have thought about implementing a kind of Unsupervised Learning task so that we can use your model for clustering etc. A good reference is [this](https://amstat.tandfonline.com/doi/abs/10.1198/106186006X94072#.W30mhcIyWUk). The idea is to arrive at a dissimilarity measure between the X variables, similar to __R's randomForest proximity matrix__. The approach can be best described by [Brieman’s original description:](https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm)

_In unsupervised learning the data consist of a set of x -vectors of the same dimension with no class labels or response variables. There is no figure of merit to optimize, leaving the field open to ambiguous conclusions. The usual goal is to cluster the data - to see if it falls into different piles, each of which can be assigned some meaning._

_The approach in random forests is to consider the original data as class 1 and to create a synthetic second class of the same size that will be labeled as class 2. The synthetic second class is created by sampling at random from the univariate distributions of the original data. Here is how a single member of class two is created - the first coordinate is sampled from the N values {x(1,n)}. The second coordinate is sampled independently from the N values {x(2,n)}, and so forth._

_Thus, class two has the distribution of independent random variables, each one having the same univariate distribution as the corresponding variable in the original data. Class 2 thus destroys the dependency structure in the original data. But now, there are two classes and this artificial two-class problem can be run through random forests. This allows all of the random forests options to be applied to the original unlabeled data set._

_If the oob misclassification rate in the two-class problem is, say, 40% or more, it implies that the x -variables look too much like independent variables to random forests. The dependencies do not have a large role and not much discrimination is taking place. If the misclassification rate is lower, then the dependencies are playing an important role._

_Formulating it as a two class problem has a number of payoffs. Missing values can be replaced effectively. Outliers can be found. Variable importance can be measured. Scaling can be performed (in this case, if the original data had labels, the unsupervised scaling often retains the structure of the original scaling). But the most important payoff is the possibility of clustering._

**Comment by StatMixedML** [comment]
Any update on this?

**Comment by annaveronika** [comment]
@StatMixedML Sorry for a long response. Thanks a lot for your interest in the library! We don't have a plan for adding unsupervised learning. But it would be a nice research project if you are interested in the topic.

**Comment by StatMixedML** [comment]
Thanks Anna Veronika for your comment. Research project in the sense of a collaboration?

**Comment by annaveronika** [comment]
@StatMixedML We will not be able to put much effort into this now, so I'm talking about reseaching on your own or with your supervisor.

**Comment by annaveronika** [comment]
Closing the issue as won't fix.
