### ISSUE TITLE
Interpreting feature importances of one hot encoded variables

### ISSUE THREAD

**Issue by Rajat700** [catboost/catboost#457]
My question is when I train a model on a dataset which contains a categorical variable say month which has categories from January to December using target based statistics and if I get a feature importance score of say 10 for column month then it is interpretable.

But if I use the parameter one_hot_max_size=15 and then train the model then how to interpret feature importance score of month column given the fact that  one hot encoding will create dummy columns (in this case 11 or 12) then we should get feature importance of all the dummy columns individually like we get in random forest. But even after using one_hot_max_size parameter I am getting feature importance of month column instead of dummy columns.

Can you please comment on this ? 

catboost version: {0.9.9.1}
Operating System: {OS}
CPU: {CPU}

**Comment by annaveronika** [comment]
This is not jet supported in CatBoost. For now if you want to see these importances, you can do one-hot encoding during preprocessing. This will work much slower, but in the end you will get the desired importances.
You need to set random_strength=0 if you do this, this should be better for quality.

**Comment by Rajat700** [comment]
Okay many thanks for the clarification.

One question which I have is after using one_hot_max_size how should I interpret feature importance score which I am currently getting after training my model.

**Comment by annaveronika** [comment]
The default feature importances show how much model value changes if the split value changes from 0 to one or from 1 to 0 (https://tech.yandex.com/catboost/doc/dg/concepts/fstr-docpage/#fstr). In case of one-hot encoding you have as many possible splits as you have categories in this feature.

The next way to calculate feature importances is shap values. You can read about it here:
https://github.com/slundberg/shap

**Comment by Rajat700** [comment]
So if my understanding is correct if we use one_hot_max_size then the categories will get converted into some numbers say in this case January will get converted to 1, Feb to 2, etc. In this way we will get a column whose value ranges from 1 to 12 and the datatype of this column will be numeric and in this way our model will get trained.

Is my understanding correct ?

**Comment by annaveronika** [comment]
No, we do regular one-hot encoding, which produces binary features - is a feature equal to this category or  not. When calculating our feature importances we calculate feature importance using the splits that this feature produces. This feature produces binary splits - is feature equal to category.

**Comment by annaveronika** [comment]
@Rajat700 Should we close the issue?

**Comment by Rajat700** [comment]
Oh yes I got my answers. Thanks I will close the issue.
