### ISSUE TITLE
catboost_python_tutorial.ipynb is broken

### ISSUE THREAD

**Issue by b0noI** [catboost/catboost#462]
Problem: broken tutorial
catboost version: 0.9.1.1
Operating System: Debian 9

~/catboost_python_tutorial.py in <module>()
    315     'logging_level': 'Verbose'
    316 })
--> 317 model = CatBoostClassifier(**params_with_snapshot).fit(train_pool, eval_set=validate_pool, save_snapshot=True)
    318 params_with_snapshot.update({
    319     'iterations': 10,

**Comment by nikitxskv** [comment]
@b0noI Hi!
Could you send the error message, please?

**Comment by annaveronika** [comment]
It might be that we added to the tutorial some functionality that is not jet available on pypi, but is on github. It will be on pypi in a couple of days in our next release.

**Comment by annaveronika** [comment]
@b0noI We cannot reproduce the problem. Could you please send the error message?

**Comment by annaveronika** [comment]
Tutorials should work with the latest pypi version.
