### ISSUE TITLE
Error at end of training in Python 3.4

### ISSUE THREAD

**Issue by Akababa** [catboost/catboost#466]
Problem: Error at end of training in Python 3
catboost version: 0.9.1.1
Operating System: Ubuntu 14.04 LTS
CPU: Intel® Core™ i5-4460 CPU @ 3.20GHz × 4
GPU: None

I tried the test at the end of "Getting Started": https://tech.yandex.com/catboost/doc/dg/installation/python-installation-test-catboost-docpage/#python-installation-test-catboost

```
import numpy 
from catboost import CatBoostRegressor

dataset = numpy.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]])
train_labels = [1.2,3.4,9.5,24.5]
model = CatBoostRegressor(learning_rate=1, depth=6, loss_function='RMSE')
fit_model = model.fit(dataset, train_labels)

print (fit_model.get_params())
```

and got the following error after the 999th iteration of training:

```
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
TypeError: 'NoneType' object is not callable

Original exception was:
TypeError: 'NoneType' object is not callable
Exception ignored in: '_catboost._CatBoost.__dealloc__'
TypeError: 'NoneType' object is not callable
```

**Comment by annaveronika** [comment]
I'm not sure what was the reason for the error, but could you upgrade to python 3.5 and to catboost 0.10 and see if the error reproduces?

**Comment by annaveronika** [comment]
We probably should change this behavoir and return the classifier object.

**Comment by annaveronika** [comment]
Actually I just checked catboost 0.10 and it works as expected, could you please check python 3.5 + catboost 0.10?

**Comment by annaveronika** [comment]
This should work in 0.10 and later in python 3.5 or later. We don't support python 3.4 starting from 0.10
