### ISSUE TITLE
CatboostError: Cannot calc metric which requires logits for absolute values.

### ISSUE THREAD

**Issue by saran46** [catboost/catboost#467]
Problem: Cannot calc metric which requires logits for absolute values.
catboost version: 0.10.0
Operating System: macos 10.13.6
CPU: 2015 i7 2.2Ghz
GPU: None

I am learning catboost by following along the the tutorials from Github
https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_python_tutorial.ipynb
When i try Parameters Tuning section using hyperopt i run into following error 

> CatboostError: catboost/libs/metrics/metric.cpp:2660: Cannot calc metric which requires logits for absolute values.

I am running 
```
catboost.__version__
'0.10.0'
hyperopt.__version__
'0.2
```
Even when i download the **catboost_python_tutorial.ipynb** from Github and run it instead of working on different dataset and different parameters I still run into exact same error message when i get to Parameters Tuning using Hyperopt.

```
import hyperopt
def hyperopt_objective(params):
    model1 = CatBoostClassifier(
        l2_leaf_reg=(params['l2_leaf_reg']),
        learning_rate=params['learning_rate'],
        iterations=500,
        eval_metric='Accuracy',
        random_seed=42,
        logging_level='Silent'
    )
    
    cv_data = cv(
        Pool(X, y, cat_features=cat_types_indices),
        model1.get_params()
    )
    best_accuracy = np.max(cv_data['test-Accuracy-mean'])
    
    return 1 - best_accuracy # as hyperopt minimises

from numpy.random import RandomState

params_space = {
    'l2_leaf_reg': hyperopt.hp.qloguniform('l2_leaf_reg', 0, 2, 1),
    'learning_rate': hyperopt.hp.uniform('learning_rate', 1e-3, 5e-1),
}

trials = hyperopt.Trials()

best = hyperopt.fmin(
    hyperopt_objective,
    space=params_space,
    algo=hyperopt.tpe.suggest,
    max_evals=50,
    trials=trials
)

print(best)

```

Kindly let me know, how to fix this issue

**Comment by annaveronika** [comment]
model1.get_params() now returns only the parameters that were explicitly set in CatBoostClassifier. This is requirement of sklearn.

And we set loss_function to None by default, so it was not included in parameters.
And the default loss_function in cv is RMSE.

To fix that you need to add loss_function='Logloss' to the parameters.
Which means instead of 
`params=model1.get_params()
params['loss_function']='Logloss'`

From our site we'll include loss_function='Logloss' instead of loss_function=None to default parameter values, and this issue will be fixed.

**Comment by saran46** [comment]
Thank You very much @annaveronika  for explaining the reason for the error. As you suggested i was able to fix this by passing `loss_function='Logloss'` parameter to CatBoostClassifier

**Comment by annaveronika** [comment]
the code for setting default loss value is on github now, will be on pypi in the next release.

**Comment by PavloFesenko** [comment]
@annaveronika The same issue in the catboost 0.16. 🙁 Before it was working fine but now `cv` again calculates RMSE when passing parameters from `CatBoostClassifier()` and not specifying `loss_function='Logloss'` explicitly.

**Comment by annaveronika** [comment]
If you call get_params from CatBoostClassifier, you only get back the parameters that you have explicitly set. If you don't set the loss function, then it is not in the params. So you need to add it to params before calling cv function.

We were setting Logloss before, but this is the loss for binary classification. Currently CatBoostClassifier sets loss function only in fit method, when it is possible to choose between Logloss and MultiClass.
