### ISSUE TITLE
Install binary package for R doesn't work in latest release (v0.10.0)

### ISSUE THREAD

**Issue by psygoh** [catboost/catboost#468]
Problem: {problem description}
catboost version: 0.10.0
Operating System: Windows 10 64 bit
CPU: Intel i5 6500
# GPU: GTX 1070

Can't install the latest R package via the following commands. It works for previous versions (i.e. v0.9.1.1 and below). Any help is appreciated.

`devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz', args = c("--no-multiarch"))`

`Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz
Installing catboost
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/.../AppData/Local/Temp/RtmpuagaR7/devtools1c7c3ac26d03/catboost" --library="C:/Users/.../Documents/R/win-library/3.5" --install-tests --no-multiarch 

* installing *source* package 'catboost' ...
** inst
** help
No man pages found in package  'catboost' 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: S3 methods 'dim.catboost.Pool', 'dimnames.catboost.Pool', 'head.catboost.Pool', 'print.catboost.Pool', 'tail.catboost.Pool' were declared in NAMESPACE but not found
Error: package or namespace load failed for 'catboost' in namespaceExport(ns, exports):
 undefined exports: catboost.caret, catboost.get_feature_importance, catboost.get_model_params, catboost.get_object_importance, catboost.load_model, catboost.load_pool, catboost.predict, catboost.save_model, catboost.save_pool, catboost.shrink, catboost.staged_predict, catboost.train
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/.../Documents/R/win-library/3.5/catboost'
* restoring previous 'C:/Users/.../Documents/R/win-library/3.5/catboost'
In R CMD INSTALL
Installation failed: Command failed (1)`

**Comment by kizill** [comment]
Sorry for that! We had a problem with directory structure in R-package tgz for windows. I updated file in 0.10 realease and double checked installation on different windows machines :).
