### ISSUE TITLE
Catboost v0.10.0 - R installation fail in Windows7 64bit

### ISSUE THREAD

**Issue by thomas9000** [catboost/catboost#469]
Problem: I have tried installing Catboost v0.10.0 via Anaconda R studio 64 bit by downloading the file into my Windows desktop and running the following separate command for tar.gz and .zip . Both failed.

catboost version: 0.10.0
Operating System: Windows7 64bit
CPU: Intel

==============================================================
> **install.packages("C:/Users/thomas/Desktop/catboost-0.10.0.tar.gz", repos = NULL, type = "source", lib="C:/anaconda3/envs/rstudio/lib/R/library")**

Warning in file(name, "wb") :
  cannot open file 'catboost-0.10.0/catboost/pytest/canondata/test.test_ctr_type_calc_block=5000000-Ordered-Borders_BinarizedTargetMeanValue_TargetBorderCount=10_/': Invalid argument
Error in file(name, "wb") : cannot open the connection
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/ANACON~1/envs/rstudio/lib/R/bin/x64/R" CMD INSTALL -l "C:\anaconda3\envs\rstudio\lib\R\library" "C:/Users/thomas/Desktop/catboost-0.10.0.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/thomas/Desktop/catboost-0.10.0.tar.gz’ had non-zero exit status

==================================================================

> **install.packages("C:/Users/thomas/Desktop/catboost-0.10.0.zip", repos = NULL, type = "win.binary", lib="C:/anaconda3/envs/rstudio/lib/R/library")**
Warning in install.packages :
  cannot open compressed file 'catboost-0.10.0/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by thomas9000** [comment]
Installation still fail in R Windows7 64bit.
===================================================

> **install.packages("devtools")**

Installing package into ‘C:/Users/thomas/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2017-09-01/bin/windows/contrib/3.4/devtools_1.13.3.zip'
Content type 'application/zip' length 443758 bytes (433 KB)
downloaded 433 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\thomas\AppData\Local\Temp\RtmpiICy3Y\downloaded_packages




> **devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz', args = c("--no-multiarch"))**

Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz
/usr/bin/tar: Cannot connect to C: resolve failed
Installation failed: Does not appear to be an R package (no DESCRIPTION)
Warning messages:
1: running command 'tar.exe -xf "C:\Users\thomas\AppData\Local\Temp\RtmpiICy3Y\file676458664043.tgz" -C "C:/Users/thomas/AppData/Local/Temp/RtmpiICy3Y/devtools676434e89bc"' had status 128 
2: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘tar.exe -xf "C:\Users\thomas\AppData\Local\Temp\RtmpiICy3Y\file676458664043.tgz" -C "C:/Users/thomas/AppData/Local/Temp/RtmpiICy3Y/devtools676434e89bc"’ returned error code 128
3: running command 'tar.exe -tf "C:\Users\thomas\AppData\Local\Temp\RtmpiICy3Y\file676458664043.tgz"' had status 128

**Comment by kizill** [comment]
I think that in that case there is some error with your system settings, like git tar seen in your PATH or like that. To to demistify tar problem try calling it directly like that:
```
utils::untar('C:\\Users\\kizill\\Downloads\\catboost-R-Windows-0.10.0.tgz', exdir = 'C:\\Users\\kizill\\Downloads\\catboost', compressed = "gzip")
```

**Comment by thomas9000** [comment]
> utils::untar('C:\\Users\\kizill\\Downloads\\catboost-R-Windows-0.10.0.tgz', exdir = 'C:\\Users\\kizill\\Downloads\\catboost', compressed = "gzip")
/usr/bin/tar: Cannot connect to C: resolve failed
Warning messages:
1: running command 'tar.exe -xf "C:\Users\kizill\Downloads\catboost-R-Windows-0.10.0.tgz" -C "C:/Users/kizill/Downloads/catboost"' had status 128 
2: In utils::untar("C:\\Users\\kizill\\Downloads\\catboost-R-Windows-0.10.0.tgz",  :
  ‘tar.exe -xf "C:\Users\kizill\Downloads\catboost-R-Windows-0.10.0.tgz" -C "C:/Users/kizill/Downloads/catboost"’ returned error code 128

**Comment by thomas9000** [comment]
When I run the tar command in my Windows7 64bit cmd window, it returned the following which means my path is correct?

**C:\Users\thomas>tar**
tar: You must specify one of the '-Acdtrux', '--delete' or
s
Try 'tar --help' or 'tar --usage' for more information.

**Comment by kizill** [comment]
After all this, i still think that you have tar from cygwin or git something like it, that can't handle paths starting with drive letter 'c:'
I found another GH issue with the same problem on windows 
https://github.com/andrie/miniCRAN/issues/110#issuecomment-399368349
Could you please run `where tar` in command shell?

**Comment by thomas9000** [comment]
Thanks very much kizill, you have solve the problem. Hope this thread will help the others too.
