### ISSUE TITLE
Class Pool has critical bug with DataFrame for data

### ISSUE THREAD

**Issue by Oktai15** [catboost/catboost#470]
I have the next simple code:
```
data = pd.DataFrame(data)
target = pd.DataFrame(target)

pool = Pool(data, target)
```

And I got following error: 
```
CatboostError: Invalid data type=<class 'pandas.core.frame.DataFrame'>: data must be list(), np.ndarray(), DataFrame(), Series(), FeaturesData or filename str().
```

Catboost version: 0.10.0

**Comment by annaveronika** [comment]
It's not a bug, it's a not supported behavoir: it is not allowed to pass DataFrame as label values. You are right, it would be great to support it.! This is a nice idea for contrubution, so I'm adding "help wanted" to the issue.

**Comment by Oktai15** [comment]
@annaveronika Hm, but in error message is written: `data must be list(), np.ndarray(), DataFrame()`...

**Comment by annaveronika** [comment]
Sorry, didn't read that the exception is about data. We'll look into this and get back to you!

**Comment by Oktai15** [comment]
@annaveronika I returned old name of issue

**Comment by Oktai15** [comment]
Oh, I don't know what it was, but now everything is okay. I am really sorry, @annaveronika, @nikitxskv.
