### ISSUE TITLE
early_stopping_rounds not recognized [R]

### ISSUE THREAD

**Issue by patarol** [catboost/catboost#471]
Hi, I'm using `catboost` (version 0.10.0) in `R 3.5.0` for Linux and I'm trying to set some parameters before training my model using `catboost.train` function. 

Specifically I want to set `early_stopping_rounds` to `TRUE` (based on the [documentation page](https://tech.yandex.com/catboost/doc/dg/concepts/r-reference_catboost-train-docpage/)).

Even if the example from the [notebook](https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_r_tutorial.ipynb) I'm not able to set this parameters... 
I've tried setting this to `TRUE` or an integer value (e.g. 200) and it throws and error:

> ```
> Error in catboost.train(train_pool, test_pool, fit_params) : 
>   catboost/libs/options/plain_options_helper.cpp:237: Error: unknown option early_stopping_rounds with value 200
> ```

and if I set it to `TRUE`:

> ```
> Error in catboost.train(train_pool, test_pool, fit_params) : 
>   catboost/libs/options/plain_options_helper.cpp:237: Error: unknown option early_stopping_rounds with value true
> ```

Here's the code I'm using:

```
train_path = system.file("extdata", "adult_train.1000", package="catboost")
test_path = system.file("extdata", "adult_test.1000", package="catboost")

column_description_vector = rep('numeric', 15)
cat_features <- c(3, 5, 7, 8, 9, 10, 11, 15)
for (i in cat_features)
  column_description_vector[i] <- 'factor'

train <- read.table(train_path, head = F, sep = "\t", colClasses = column_description_vector, na.strings='NAN')
test <- read.table(test_path, head = F, sep = "\t", colClasses = column_description_vector, na.strings='NAN')
target <- c(1)
train_pool <- catboost.load_pool(data=train[,-target], label = train[,target])
test_pool <- catboost.load_pool(data=test[,-target], label = test[,target])

fit_params <- list(iterations = 100,
                   thread_count = 10,
                   loss_function = 'Logloss',
                   ignored_features = c(4,9),
                   border_count = 32,
                   depth = 5,
                   learning_rate = 0.03,
                   l2_leaf_reg = 3.5,
                   train_dir = 'train_dir',
                   early_stopping_rounds = TRUE)
model <- catboost.train(train_pool, test_pool, 
                        fit_params)
```

Thank you!

**Comment by annaveronika** [comment]
We are looking into that. Please use od_type = 'Iter' + od_wait=200 for now. Or something different from 200 according to your decision.

**Comment by annaveronika** [comment]
early_stopping_rounds should not be TRUE, it should be an integer value, for example 200. Maybe this solves your problem?

**Comment by patarol** [comment]
@annaveronika thank you for your help.
I've just tried and it works.

Thank you!
Closing...
