### ISSUE TITLE
Catboost in Rust lang

### ISSUE THREAD

**Issue by johnkarasev** [catboost/catboost#473]
I am creating a electric power consumption forecasts model in Rust language. Will catboost work with rust?

**Comment by annaveronika** [comment]
We have C++, python and Java appliers. Rust is a great idea for contribution.

**Comment by johnkarasev** [comment]
Before I make any contributions, is catboost good with time series?

**Comment by Shuternay** [comment]
I would like to implement this

**Comment by johnkarasev** [comment]
@Shuternay I can contribute also, what is your progress on it

**Comment by annaveronika** [comment]
@Shuternay @johnkarasev We are happy if we get help with this!

**Comment by kizill** [comment]
> @Shuternay I can contribute also, what is your progress on it?
@Shuternay privately stated that he already have some rust wrapper around model C API. I hope he will send PR in near future :)

**Comment by Shuternay** [comment]
@johnkarasev 
I have wrapped model C API, but there are only methods which apply model and get some model info: https://github.com/Shuternay/catboost/tree/master/catboost/rust-package
Now I want to add support for model training.

**Comment by annaveronika** [comment]
@Shuternay What's the progress? We are waiting for your pr!

**Comment by annaveronika** [comment]
You don't have to do training, the first step - applying the model - would be already great.

**Comment by annaveronika** [comment]
This is implemented in catboost 0.15

**Comment by goldenMetteyya** [comment]
> @johnkarasev
> I have wrapped model C API, but there are only methods which apply model and get some model info: https://github.com/Shuternay/catboost/tree/master/catboost/rust-package
> Now I want to add support for model training.

Has any work been done on training with rust?

**Comment by annaveronika** [comment]
No, and there is not plan to support training on Rust

**Comment by goldenMetteyya** [comment]
> No, and there is not plan to support training on Rust

hello, is there a c api for training? I am interested in working on it.

**Comment by manavsah** [comment]
if no one has started i can start with training ?

**Comment by Longcuirong** [comment]
> 



> @annaveronika
> 
> > No, and there is not plan to support training on Rust
> 
> hello, is there a c api for training? I am interested in working on it.

me too, i want to use a c api for training
