### ISSUE TITLE
Documentation page unavailable

### ISSUE THREAD

**Issue by syadalam** [catboost/catboost#476]
Problem: URL in the repo for documentation is not accessible
Operating System: MAC OS X Chrome/Firefox browser

URL: https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

<img width="903" alt="image" src="https://user-images.githubusercontent.com/43450697/45836888-947ad780-bcd3-11e8-9170-2a963063691f.png">

**Comment by annaveronika** [comment]
@syadalam Could you please try again? I'm not sure what was the issue, but the site should be working on on OS

**Comment by annaveronika** [comment]
Documentation should work, we cannot reproduce the problem on any OS, this probably was a network problem.
