### ISSUE TITLE
not the same dependency between pip install and conda install: is this expected ?

### ISSUE THREAD

**Issue by tarrade** [catboost/catboost#478]
Problem: not the same dependency between pip install and conda install, is this expected
catboost version: 0.10.2
Operating System: Linux centos:6.9

Hi there,

I am using python 3.5.6 from Anaconda. If I install catboost using conda:

>> conda install catboost=0.10.2

and If I run:

>> conda info catboost:
     ....
     catboost 0.10.2 py35_0
     ----------------------
     file name   : catboost-0.10.2-py35_0.tar.bz2
     name        : catboost
     version     : 0.10.2
     build string: py35_0
     build number: 0
     channel     : https://conda.anaconda.org/conda-forge/linux-64
     size        : 48.2 MB
     arch        : x86_64
     constrains  : ()
     license     : Apache 2.0
     license_family: MIT
     md5         : 10250ebb380a3df23c2f88139d8f72b2
     platform    : linux
     subdir      : linux-64
     timestamp   : 1537601702073
     url         : https://conda.anaconda.org/conda-forge/linux-64/catboost-0.10.2-py35_0.tar.bz2
     dependencies:
         numpy
         python >=3.5,<3.6.0a0
         six

you can see that the dependency are numpy, python  and six

if on the same installation if I run pip install for other packages, I will see some warning like the one here:

>> pip check
     catboost 0.10.2 requires enum34, which is not installed.

>> pip show catboost
     Name: catboost
     Version: 0.10.2
     Summary: Python package for catboost
     Home-page: https://catboost.ai
     Author: CatBoost Developers
     Author-email: None
     License: Apache License, Version 2.0
     Location: /opt/conda/envs/env_py35/lib/python3.5/site-packages
     Requires: enum34, pandas, numpy, six
     Required-by: 

you can see that the dependency are numpy, six, enum34, pandas

Which one is correct ? pip or conda ?

I did run the test with catboost install with conda and the test run without any issues:
https://tech.yandex.com/catboost/doc/dg/installation/python-installation-test-catboost-docpage/

Thanks
Cheers
Fabien

**Comment by DS-AI** [comment]
Sorry, when its going to be fixed? Doing pip install breaks python since other packages do not expect enum34 to be in 3.5+.

**Comment by tarrade** [comment]
@DS-AI unfortunately I am not an expert in pip and conda dependency in catboost. I am a conda user so at the end it os working for me. I suggest you to open a specific bug report about the enum34 dependency. This is a real bug. Sorry, I cannot really do more and nothing happen since almost a year.

**Comment by dbakshee** [comment]
See #1056 
We are going to use environment marker for enum34.
