### ISSUE TITLE
Pool class using cat_features could not convert string to float error

### ISSUE THREAD

**Issue by abaspinar** [catboost/catboost#48]
Hi, 
I am using Python Pool class for my string categorical features.
`cat_index=[22, 32, 34, 49, 55]`
`train_pool = Pool(x_train, y_train, cat_features=cat_index)`

I am getting the following error for the string `LARS`.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-5e1830151743> in <module>()
----> 1 train_pool = Pool(x_train, y_train, cat_features=cat_index)
      2 #test_pool = Pool(test_data, cat_features=cat_index)

/home/dorukhan/.local/lib/python2.7/site-packages/catboost/core.pyc in __init__(self, data, label, cat_features, column_description, delimiter, has_header, weight, baseline, feature_names, thread_count)
     92                 self._read(data, column_description, delimiter, has_header, thread_count)
     93             else:
---> 94                 self._init(data, label, cat_features, weight, baseline, feature_names)
     95         super(Pool, self).__init__()
     96 

/home/dorukhan/.local/lib/python2.7/site-packages/catboost/core.pyc in _init(self, data_matrix, label, cat_features, weight, baseline, feature_names)
    303         if feature_names is not None:
    304             self._check_feature_names(feature_names, data_shape[1])
--> 305         self._init_pool(data_matrix, label, weight, baseline, feature_names)
    306 
    307 

_catboost.pyx in _catboost._PoolBase._init_pool (/home/donskov/.ya/build/build_root/7970737a6565726b34656c346638377a/catboost/python-package/catboost/_catboost.pyx.cpp:5141)()

_catboost.pyx in _catboost._PoolBase._init_pool (/home/donskov/.ya/build/build_root/7970737a6565726b34656c346638377a/catboost/python-package/catboost/_catboost.pyx.cpp:4860)()

_catboost.pyx in _catboost._PoolBase._set_data (/home/donskov/.ya/build/build_root/7970737a6565726b34656c346638377a/catboost/python-package/catboost/_catboost.pyx.cpp:5586)()

ValueError: could not convert string to float: LARS
```

Python: Python 2.7.13 :: Anaconda custom (64-bit)
Installed with: pip install catboost

Thanks.

**Comment by Donskov7** [comment]
@abaspinar, could you provide your data? 
*And check that all features have right indices that you give into cat_features (all indices start from 0 (zero))

**Comment by abaspinar** [comment]
Thanks! @Donskov7 
It was because of wrong indices.

**Comment by parthparashar1647** [comment]
I did'nt understand @abaspinar how did you correct the wrong indicies

**Comment by annaveronika** [comment]
Categorical feature indices should be correct. If the 0 and 2 features are categorical and others numeric, then the value should be cat_index=[0,2]
In case of this error some categorical feature was not included to this list, so alrogithm was trying to parse it as numeric.

**Comment by amresh1495** [comment]
Does it convert date into numerical value ?

**Comment by annaveronika** [comment]
No, if you provide the date and say that it's a categorical feature, then it will be treated like a string with this value.

**Comment by shivamsaboo17** [comment]
I am getting same error but it's with the target labels which are in string format. Should I convert the labels to categories as string labels are not supported?

**Comment by sergmiller** [comment]
@shivamsaboo17,  for now if you use python package you should convert the labels to categories or try [catboost command line version](https://tech.yandex.com/catboost/doc/dg/concepts/cli-reference_train-model-docpage/) with option --class-names. Possibility to use class-names in python version will be added soon.

Also automatic setting class_names will be added into both versions.

**Comment by goshulina** [comment]
Same issue
What should i fix if:
I trained catboost and defined cat features as this:
`clf.fit(train, labels, cat_dims)`
And when i look at indexes of cat and float features in the trained model they are the same as in cat_dims var before. 
I got this error when i load test set and try to make class prediction:
`_catboost.CatboostError: Bad value for num_feature[0,3]="1.281.501.0": Cannot convert 'b'1.281.501.0'' to float`

My cat indexes in trained model:
[0, 1, 2, 9, 10, 11, 12, 13, 15, 16, 19, 21, 24, 28, 29, 31, 32, 34, 35, 36, 38, 39]
So, [0,3] error - means, that my third feature was float (and it is truly does not presented in the cat indexes list above), and it was OK while training, and now, when i try to predict on test sample it suddenly became unable to convert it to float, because third feature in test sample is now categorical (according to the value "1.281.501.0")? And how to know the name of this feature? The "third" feature does not make any sense to me. What should i do to load test samples and make a prediction successfully?

**Comment by rousso1** [comment]
for the sake of future visitors - this error is most likely thrown when you have a categorical feature which is not casted to string, prior to fitting

**Comment by jendefig** [comment]
I'm having the same problem on a new dataset.  In the coursera example all the column dtypes are int64 and it works fine. Nothing was converted.   My new dataset is throwing the error with a float64 that I converted to string (object) and am having the same problem... @annaveronika what am I missing?

**Comment by bharath7896** [comment]
do we need to label encode the string containing categorical features which contain dtypes as object to numeric ? for data to be pooled ? because I am also getting same error

TypeError: Cannot convert 'b'W'' to float

**Comment by annaveronika** [comment]
> I'm having the same problem on a new dataset. In the coursera example all the column dtypes are int64 and it works fine. Nothing was converted. My new dataset is throwing the error with a float64 that I converted to string (object) and am having the same problem... @annaveronika what am I missing?

It is not allowed to use floating point columns for categorical features. The best thing is to use Categorical type, you can also use integer or object types.
Here is the explanation why you cannot use float numbers for categorical features:
https://catboost.ai/docs/concepts/faq.html#specify-weights-or-baseline-for-eval-set

**Comment by annaveronika** [comment]
> do we need to label encode the string containing categorical features which contain dtypes as object to numeric ? for data to be pooled ? because I am also getting same error
> 
> TypeError: Cannot convert 'b'W'' to float

This error means that you have not listed your categorical feature in cat_features parameter. By default all features are considered numeric. You must explicitly say that the feature is categorical.
