### ISSUE TITLE
CatBoost giving bad performance when giving categories indices

### ISSUE THREAD

**Issue by Kshitijagrawal27** [catboost/catboost#483]
I am using CatBoost on genetic data , actually the issue is when I am using one hot encoding and directly converting categories in integers , CatBoost is giving good results ( Similar or quite better than gbm) , but when I am mentioning the categories indices, it's performance decreased a lot. For e.g. with one hot encoding recall = .76 , when mentioning categories indices then recall =.46   , Please suggest where I am going wrong ,reason behind this decrease in performance  and how to improve performane.

**Comment by annaveronika** [comment]
My best guess is that there is some bug in generating categorical feature indices. Please check that they are 0-based. You can share your dataset and code, we can look into it if you want.

**Comment by annaveronika** [comment]
Could you please provide all the code, including reading of the data and training of the model?

**Comment by Kshitijagrawal27** [comment]
Hi @annaveronika  ... Thanks for the suggestion, I rechecked the whole code again, and there was a mistake in categorical columns indices. Thanks a lot.
