### ISSUE TITLE
custom profit function to get optimized

### ISSUE THREAD

**Issue by raulcarlomagno** [catboost/catboost#485]
Problem: is it possible to use my custom profit function to get optimized (maximized) without using another model based optimization like bayesian optimization?

catboost version: v0.10.0
Operating System: Windows 10
CPU: Intel I7-7500U
GPU: NVIDIA GeForce 940MX

**Comment by annaveronika** [comment]
It is possible to optimize a custom objective, you can specify it in python or c++. I strongly suggest using c++ because it will work much faster. We have a tutorial explaining how to do that:
https://github.com/catboost/tutorials/blob/master/advanced_tutorials/catboost_custom_metric_tutorial.md

**Comment by raulcarlomagno** [comment]
ok, right now, im developing in R, is there an example in python to see it?

**Comment by annaveronika** [comment]
We don't support custom loss functions that are written in R. So if you want to use R and custom loss, you need to write it in C++.

Other option would be python. You can write your loss in python, here is an example
https://tech.yandex.com/catboost/doc/dg/concepts/python-usages-examples-docpage/#custom-objective-function

**Comment by raulcarlomagno** [comment]
very clear, thank you!
