### ISSUE TITLE
Good error msg for invalid classification objective

### ISSUE THREAD

**Issue by nd7141** [catboost/catboost#487]
Problem: 
When I set loss function for classifier to 'RMSE' `model = CatBoostClassifier(loss_function='RMSE')`, it logically says: 
`_catboost.CatboostError: Invalid loss_function='RMSE': for classifier use Logloss, CrossEntropy, MultiClass, MultiClassOneVsAll, AUC, Accuracy, Precision, Recall, F1, TotalF1, MCC or custom objective object`
But then when I set 'AUC' `model = CatBoostClassifier(loss_function='AUC')`, I get: 
`_catboost.CatboostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/options/catboost_options.cpp:125: Unknown loss function AUC`

So is it possible to use AUC as loss function? 

catboost version: 0.10.2
Operating System: Windows
CPU: CPU

**Comment by annaveronika** [comment]
loss_function parameter is the name of the optimized objective. You can use the ones from the Classification and Multiclassification parts that are mentioned as Used for optimization == '+' here:
https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/

We'll provide a better error msg here, thanks for pointing it out! For now these are the losses you can look on, not optimize.

**Comment by nd7141** [comment]
Okay, thank you. One follow-up. 

> The calculation of some metrics is disabled by default for the train dataset to speed up the training. Use the hints=skip_train~false parameter to enable the calculation.

I'm not sure, where should I specify in my code (function) this command `hints=skip_train~false`? 

And which objectives/metrics are calculated in addition to the one specified in loss_function?

**Comment by annaveronika** [comment]
Take a look on usage examples on page https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/. There is an example
`AUC:hints=skip_train~false` - this is the way to name the metric if you want it to not skip calculation on train dataset.

No metrics are calculated in addition to the loss function by default. If you want to calculate some other metrics, you need to use custom_metric or eval_metric parameters.

**Comment by nd7141** [comment]
I guess I should write something like: 

`model = CatBoostClassifier(
                                   loss_function='Logloss',
                                   custom_metric='AUC:hints=skip_train~false',
                                   metric_period=20
                                   )`

**Comment by annaveronika** [comment]
Exactly! The metric_period is a good thing to use if you are calculating AUC on your train, because otherwise it will be the bottleneck of the training.

One more thing - you can write eval_metric instead of custom_metric, if you want it to be used for autostop or selecting best iteration.

**Comment by annaveronika** [comment]
Yes, you can optimize a custom loss, here is a tutorial for that:
https://github.com/catboost/tutorials/blob/master/advanced_tutorials/catboost_custom_metric_tutorial.md

**Comment by annaveronika** [comment]
The error msg is now fixed, you can build from source to have it right. It'll be on pypi with the next release, which we plan to do this or next week.

**Comment by extrospective** [comment]
> Yes, you can optimize a custom loss, here is a tutorial for that:
> https://github.com/catboost/tutorials/blob/master/advanced_tutorials/catboost_custom_metric_tutorial.md

This link did not work.  

Perhaps this one is intended:
https://github.com/catboost/tutorials/blob/master/custom_loss/custom_metric_tutorial.md
