### ISSUE TITLE
Pool from gzipped file

### ISSUE THREAD

**Issue by TarasDerevianko** [catboost/catboost#489]
Is it possible to create a Pool object from the gzipped csv\tsv file in python\R without load to memory?

**Comment by Noxoomo** [comment]
Hi!

Currently you can't load in Pool directly from gzip on disk.
But if you have enough RAM then you could load it to pandas and create Pool from pandas dataframe

**Comment by annaveronika** [comment]
We don't have a plan to implement loading Pool from gzipped file. So closing this one as won't fix.
