### ISSUE TITLE
ya-bin.exe flagged as malware

### ISSUE THREAD

**Issue by Weekend-Warrior** [catboost/catboost#49]
Is there anything in ya-bin.exe that would set off AVG? It's quarantined this file twice for me.

**Comment by ferrr** [comment]
You can use https://www.virustotal.com/ to scan with different anti malware software — https://www.virustotal.com/en/file/e22f32356ce87e44152915585c14e447e5bf6757449ee48b3a0c8fc812b60be0/analysis/

I think AVG overreacts to the fact of running downloaded binary.

Not much we can do :(
