### ISSUE TITLE
How to add custom eval metric in my catboost training?

### ISSUE THREAD

**Issue by HelloSilicat** [catboost/catboost#490]
Just like lightgbm,`LGB=lgb.train(params,train_data,num_boost_round=2000,valid_sets=[train_data,validation_data], early_stopping_rounds=300,feval=f1_score,verbose_eval=1)`,which **f1_score** is custom eval metric.

I want to know how to do this in catboost? Or is **macro-f1** metric is built-in?
Thanks!

**Comment by annaveronika** [comment]
F1 score is supported, take a look on all supported metrics here:
https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/

**Comment by HelloSilicat** [comment]
@annaveronika Thank you for your helpful response.

**Comment by annaveronika** [comment]
No problem! Closing the issue then.

**Comment by bestpredicts** [comment]
it seems catboost. cann't run  MultiClass ,when set  metric = F1?

**Comment by annaveronika** [comment]
MultiClass F1 is calculated as described in the docs here:
https://catboost.ai/docs/concepts/loss-functions-multiclassification.html
The metric is calculated separately for each class k numbered from 0 to M – 1.
So you can calculate this metrics during training and plot them, to do this you need to use custom_metric parameter.
