### ISSUE TITLE
Implement shap_interaction_values() of the Shap package

### ISSUE THREAD

**Issue by pccampbell** [catboost/catboost#493]
I've been building out a workflow using catbosot and so far things have been going very smoothly and I appreciate all the work that has been done on it. I started to use the shap package to output plots of feature importance and all of them have worked so far besides shap_interaction_values(). When I run this I get an error `'CatBoostClassifier' object does not support indexing`  I decided to post this here because I found your post on the original implementation of shap_values() for catbosot where it was stated that only shap_values had been implemented. 

https://github.com/slundberg/shap/issues/58#issuecomment-382101972

Am I understanding it correctly that is not currently supported with catboost models or did I make an error? Is it something that could be supported in the future or is it too complicated to bother with. I'm rather curious what the output of the interaction values would be, so it would be fantastic if it was a relatively easy fix.

catboost version: 0.10.2
Operating System: Win 
CPU: Win Intel i7
GPU: Win (1050ti)

**Comment by annaveronika** [comment]
Yes, you are right, we haven't implemented the interaction values jet. But we plan to do it at some point. Or maybe somebody will contribute. Let this issue be the point to start this.

**Comment by sebconort** [comment]
I think shap interaction values are of great interest for business users to get more insights about what the model does when predicting. It would help get confidence to push Catboost models in production pipelines. I trieds to have a look but I know Python only. In addition, parsing Catboost trees seems quite complex whithout getting a deep tutorial.
As stated in Shap paper (https://arxiv.org/pdf/1802.03888.pdf), computing interaction values does not seem quite complex once you already implemented shap values optimised algorithm.
I hope someone will take time to work on this open issue soon.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Implemented in CatBoost 0.23
