### ISSUE TITLE
catboostmodel library build problem

### ISSUE THREAD

**Issue by quickdevel** [catboost/catboost#497]
**Problem:**
I build libcatboostmodel:
`./ya make -r -o build_output -r catboost/libs/model_interface`
and get two identical files with different names:
libcatboostmodel.so with libcatboostmodel.so.1 on Linux
or
libcatboostmodel.dylib with libcatboostmodel.dylib.1 on macOS

otool -L for libcatboostmodel.dylib output:
```
libcatboostmodel.dylib:
        libcatboostmodel.dylib.1 (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

What a postfix ".1" after file extension?
I link library libcatboostmodel with my app in binding.gyp (node-gyp):
```
...
        ['OS=="win"', {
          'libraries': [
            '../libs/catboostmodel.lib'
          ],
          'copies': [{
            'destination': '<(PRODUCT_DIR)',
            'files': [
              'libs/catboostmodel.dll'
            ]
          }]
        }],
        ['OS=="linux"', {
          'libraries': [
            '../libs/libcatboostmodel.so',
            '-Wl,--disable-new-dtags -Wl,-rpath=\'$${ORIGIN}/../../libs\''
          ]
        }],
        ['OS=="mac"', {
          'libraries': [
            '../libs/libcatboostmodel.dylib',
            '-rpath \'@loader_path/../../libs\''
          ],
          'xcode_settings': {
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES'
          }
        }]
...
```
On macOS at startup I got error:
`Library not loaded: libcatboostmodel.dylib.1`

On Windows all ok.
On Linux all ok, but need have two files: libcatboostmodel.so and libcatboostmodel.so.1

**catboost version:** 0.10.3, 0.9.11
**Operating System:** macOS and Linux

**Comment by quickdevel** [comment]
I resolve problem with library loading by install_name_tool in postinstall script. But why after building catboostlibrary I get two identical files and one file have postfix ".1" after file ext?

**Comment by dbakshee** [comment]
Hi @quickdevel 

Traditionally shared objects are provided with a version suffix. 
For example, libfoo.so.1 contains functions of the first version, and libfoo.so.2 would contain the functions with improved (but different) API, or incompatibly bugfixed functions or such.
To conveniently link with the latest version (typically) of a versioned library, linux and darwin employ symbolic links, such as `libfoo.so -> libfoo.so.1`. Presence of symbolic link allow use of linker flag `-l`, e.g. `-lfoo`. 

If you don't care about versioning (e.g. always build catboost from source), you may use the file without the suffix. On the other hand, if you expect that several versions of the library would coexist in your system, then you are advised to take the versioned file and setup a symbolic link to it. 

Look here for example:
```
$ ls -ld /usr/lib/libc*
lrwxrwxrwx 1 root root    15 Jan  6  2017 /usr/lib/libcdt.so -> libcdt.so.5.0.0
lrwxrwxrwx 1 root root    15 Jan  6  2017 /usr/lib/libcdt.so.5 -> libcdt.so.5.0.0
-rw-r--r-- 1 root root 26824 Jan  6  2017 /usr/lib/libcdt.so.5.0.0
lrwxrwxrwx 1 root root    18 Jan  6  2017 /usr/lib/libcgraph.so -> libcgraph.so.6.0.0
lrwxrwxrwx 1 root root    18 Jan  6  2017 /usr/lib/libcgraph.so.6 -> libcgraph.so.6.0.0
-rw-r--r-- 1 root root 85504 Jan  6  2017 /usr/lib/libcgraph.so.6.0.0
```

**Comment by quickdevel** [comment]
But on macOS suffix is before extension:
```
-rwxr-xr-x  1 root  wheel  1476080 21 сен 09:17 /usr/lib/libc++.1.dylib
lrwxr-xr-x  1 root  wheel       14  6 окт 16:11 /usr/lib/libc++.dylib -> libc++.1.dylib
```

**Comment by dbakshee** [comment]
The idea is the same, anyway

**Comment by quickdevel** [comment]
Yes, but libcatboostmodel has version suffix after .dylib. It's ok?

**Comment by dbakshee** [comment]
It is ok because the versioned library is supposed to be linked via a symlink with normal name

**Comment by quickdevel** [comment]
Ok. Thanks :)
