### ISSUE TITLE
CatBoostRegressor `best_score_` atribute contains byte-encoded keys

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#509]
Problem: CatBoostRegressor.`best_score_` is a dict with mixed-encoded keys: some are unicode, some are byte-encoded
{'learn': {b'RMSE': 10.640102055539602}, 'validation_0': {b'RMSE': 10.502003539191}}

catboost version: catboost 0.10.3 
Operating System: Ubuntu 16.04.5 LTS
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
GPU: integrated, not used

**Comment by AndreyGurevich** [comment]
For example, this code will not work as expected:
```
params = model.get_params()
score = model.best_score_['learn'][params['metric']]
```

**Comment by annaveronika** [comment]
Thanks for pointing it out! We'll look into this.

**Comment by dbakshee** [comment]
Hi, @AndreyGurevich 
The issue should be fixed by commit 145ad6b22ee390d6d255448703383aa8c120cc0d

**Comment by annaveronika** [comment]
Ok, closing the issue, please try building from source (https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/)
or wait for our next pypi release which will happen this week.

**Comment by AndreyGurevich** [comment]
Thank you!

пн, 22 окт. 2018 г. в 14:08, annaveronika <notifications@github.com>:
