### ISSUE TITLE
CatBoost load pool (java)

### ISSUE THREAD

**Issue by daryapryadchenko** [catboost/catboost#512]
Support catboost.load_pool() not yet implemented for Java? Is there any way around this problem?

**Comment by yazevnul** [comment]
Hi, I don't think Java application library will ever have this functionality, until we decide that we want to implement Java interface for training.

If you are using `catboost.load_pool()` to load object features into memory and then apply model to them. Then you should write object features loading in Java by yourself, and then use Java interface to apply model.

**Comment by annaveronika** [comment]
Closing the issue as won't fix.
