### ISSUE TITLE
Problem with CB_ENSURE check in depth parameter = 9 for GPU pairwise learning

### ISSUE THREAD

**Issue by kslazarev** [catboost/catboost#515]
Problem: Problem with CB_ENSURE check in --depth 9 for GPU pairwise learning. Expect error on --depth 11 .
Catboost version: master

`catboost fit -f train_queries.tsv --train-dir train_dir --task-type GPU --depth 9 --loss-function YetiRankPairwise -w 0.03 -r 0 -i 300 --cd cd_file`

> (TCatboostException) catboost/cuda/methods/pairwise_oblivious_trees/pairwise_score_calcer_for_policy.cpp:22: Error: GPU pairwise learning works with tree depth <= 10 only

https://github.com/catboost/catboost/blob/eb83d24ef9c76be8f40c7c3f594781d79d829621/catboost/cuda/methods/pairwise_oblivious_trees/pairwise_score_calcer_for_policy.cpp#L22

**Comment by annaveronika** [comment]
GPU pairwise modes don't support depth more than 8, we plan to add it to documentation soon.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
The message in CB_ENSURE is [fixed](https://github.com/catboost/catboost/commit/30a56d38b1e76d57b578e47c94ae374f503a54aa)

The documentation will be updated soon.
