### ISSUE TITLE
catboost4j-prediction library

### ISSUE THREAD

**Issue by NesterovVladislav** [catboost/catboost#516]
Is it possible to use the catboost4j-prediction library to predict the calculation function with prediction_type = "Probability"? If you use the pred (float [], int []) method, then you get a calculation for the RowFormulaVal type. Development is conducted on Java.

**Comment by vasiliykovalev** [comment]
@NesterovVladislav if I understand correctly what you want:
```
public class CatboostPredictorTest {
    public static void softmax(final double[] x) {
        double sum = 0;
        for (int i = 0; i < x.length; i++) {
            x[i] = Math.exp(x[i]);
            sum += x[i];
        }
        for (int i = 0; i < x.length; i++) {
            x[i] /= sum;
        }
    }

    public static void main(String[] args) throws CatBoostError {
        CatBoostModel model = CatBoostModel.loadModel("path_to_catboost_model");
        float[] test_data = new float[]{1,2,3,4};
        CatBoostPredictions predictions = model.predict(test_data, (String[]) null);
        double[] ans = predictions.copyRowMajorPredictions();
        softmax(ans);
        System.out.println(Arrays.toString(ans));
    }
}
```

**Comment by NesterovVladislav** [comment]
Unfortunately, this option is not suitable for me. In my case, when calculating data by model, I get an array of one element. So when I apply the softmax() function to this array, I will always get 1. Maybe there is some other option?

**Comment by NesterovVladislav** [comment]
How are the results of answers for the type Probability and for the type RovformulaVal related to each other?
