### ISSUE TITLE
Compiling for Linux CPU failed, all Event::fn() missing

### ISSUE THREAD

**Issue by francky06l** [catboost/catboost#519]
Hello,

As of October 29th, after a pull, catboost does not compile (actually does not link), many errors as follow in libraries:
library/par/par_util.h:102: undefined reference to `Event::~Event()'

It seems the file util/system/event.cpp is missing in the make files.

Another question concerning the loss function QueryCrossEntropy, it's seems available for GPU only, not having GPU capability how could I make it available for CPU (if ever possible) ?

Thanks
F.

**Comment by francky06l** [comment]
No solution for this compiling (CPU) issue ?
Sample of error:
In function `NNetliba_v12::TUdpHost::ProcessDataPacket(NNetlibaSocket::NNetliba_v12::EUdpCmd, char const*, char const*, TAutoPtr<NNetlibaSocket::TUdpRecvPacket, TDelete>, NNetliba_v12::TTransfer const&, NNetliba_v12::TOptionsVector const&)':
/home/xxxxx/catboost/util/system/event.h:93: undefined reference to `Event::Event(Event const&)

Thanks

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
I will try to reproduce this issue today, and will post here.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
https://github.com/catboost/catboost/archive/master.zip and https://github.com/catboost/catboost/commit/2075983de479bd3363e8b6a7d12cad4be5f729e4 (last revision of 2018-oct-29) compile with out errors, if I do `./ya make catboost`

Could you please explain in detail how you build CatBoost?

**Comment by francky06l** [comment]
Hi
I was following the documentation for compiling on Linux CPU and I just usually do:
make -f make/app.CLANG50-LINUX-X86_64.makefile
I will try with ./ya make and see how it goes
Thanks

**Comment by dbakshee** [comment]
Hi @francky06l 
The issue `undefined reference to Event::Event` has been fixed in 0.11.1. 
The following command succeeds: 
`CC=clang-5.0 CXX=clang++-5.0 make -f make/app.CLANG50-LINUX-X86_64.makefile`
Could you check if it works for you?

**Comment by francky06l** [comment]
Hello,
Yes it does work now, thanks. There is another issue compiling CLI with CUDA, but I guess it's better to open a new issue.
Thanks very much
