### ISSUE TITLE
catboost widget issues

### ISSUE THREAD

**Issue by msampathkumar** [catboost/catboost#52]
I was getting following error while trying `kaggle_titanic_catboost_demo.ipynb` tutorial(cell id - 11)(CatBoostClassifier - Model Plot using Widget).

`_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`

I am using Mac, Python 3.5.3 :: Continuum Analytics, Inc
Working Fix:

```
changed - line 81, catboost/widget/ipythonwidget.py
-            with open(meta_tsv, 'rb') as meta_in:
+            with open(meta_tsv, 'r') as meta_in:

changed - line 101, catboost/widget/ipythonwidget.py
-                with open(file_path, 'rb') as f:
+                with open(file_path, 'r') as f:

```

Please check and close this issue.

**Comment by annaveronika** [comment]
It is fixed now, try updating to the last version.
