### ISSUE TITLE
Problem with GPU on Ubuntu 16.04

### ISSUE THREAD

**Issue by petrpavlov** [catboost/catboost#520]
Problem: Raised `CatboostError` exception when set `task_type='GUI'`:
>CatboostError: catboost/cuda/cuda_lib/cuda_base.h:272: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version

CUDA installation was tested by compiling and running `deviceQuery` example:
>deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS

catboost version: 0.10.4.1
Operating System: Ununtu 16.04
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU: GeForce GTX 1050Ti
CUDA version: 9.0
NVIDIA driver: 384.130

**Comment by kizill** [comment]
Hello! Our prebuilt python/R packages and binaries require nvidia dirver compatible with CUDA 9.1 or higher and we don't depend on CUDA runtime version at all. So you can upgrade your driver.

**Comment by Noxoomo** [comment]
You need  390.xx or higher version of NVIDIA Driver

**Comment by petrpavlov** [comment]
Thanks for help. Now it works.
