### ISSUE TITLE
Add categorical features and nan values to json tutorial

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#522]

**Comment by annaveronika** [comment]
Here is the tutorial:
https://github.com/catboost/tutorials/blob/master/apply_model/json_model_tutorial.ipynb
It will be much more complicated with categorical features, so we decided to do it only for numeric ones.

**Comment by ser0t0nin** [comment]
Thanks a lot! I am currently using only numeric features, so it's exactly what i needed in #23. 
Is it worth waiting for categorical tutorial to appear once?

**Comment by annaveronika** [comment]
We don't plan to do it now, but we definitely should do it at some point, so I suggest this issue to be open. I'll rename it to make the clarification.

**Comment by saurzcode** [comment]
> Here is the tutorial:
> https://github.com/catboost/tutorials/blob/master/apply_model/json_model_tutorial.ipynb
> It will be much more complicated with categorical features, so we decided to do it only for numeric ones.

The link seems not available, here is the correct link - 
https://github.com/catboost/tutorials/blob/master/apply_model/model_export_as_json_tutorial.ipynb
