### ISSUE TITLE
No CUDA host compiler for the selected platform and CUDA Toolkit version 10.0

### ISSUE THREAD

**Issue by taurandat** [catboost/catboost#524]
Problem: I got the error `No CUDA host compiler for the selected platform and CUDA Toolkit version 10.0` when trying to build `catboost` for GPU

Build command:

```
../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda
```

catboost version: Commit 56c0928

Operating System: Ubuntu 18.04

CPU: Ryzen Threadripper 1920x

GPU: RTX 2080 Ti

```
~ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

```
~ nvidia-smi
Thu Nov  1 16:50:03 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
```

Edit: Add build command and `nvcc --version` output

**Comment by ei-grad** [comment]
@taurandat How did you solve this issue?

**Comment by dbakshee** [comment]
Hi @taurandat, @ei-grad, @diaper151,
The build problem is solved by adding `-DCUDA_HOST_COMPILER=''` flag on `ya make ...` build line.

**Comment by diaper151** [comment]
> Hi @taurandat, @ei-grad, @diaper151,
> The build problem is solved by adding `-DCUDA_HOST_COMPILER=''` flag on `ya make ...` build line.

That works for me, thanks @dbakshee
