### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by weisskatze** [catboost/catboost#526]
Problem: I tried to install catboost in R, but when I executed "install.packages('devtools')", error occured belbow:

**ERROR: compilation failed for package 'catboost' 
removing 'C:/Users/XXX/Documents/R/win-library/3.5/catboost'**

I installed Python and added it to Path, and also installed  Visual Studio Community 2017 with  Windows Platform development and Desktop Development with C++ options.

How can I deal with this issue?

catboost version: {version} new one
Operating System: {OS} Windoes10
CPU: {CPU} AMD Ryzen 3 2200G
GPU: {GPU} AMD Radeon[TM] Vega 8 Graphics

**Comment by annaveronika** [comment]
Could you please try this way? https://tech.yandex.com/catboost/doc/dg/installation/r-installation-conda-install-docpage/

**Comment by annaveronika** [comment]
Actually I think you didn't use the recommended way to install the package.
Please try following this instruction:
https://tech.yandex.com/catboost/doc/dg/installation/r-installation-binary-installation-docpage/

**Comment by annaveronika** [comment]
The latest comment should help, closing the issue.

**Comment by weisskatze** [comment]
I already did it, but it didn't work.
------ Original Message ------
Date: Thursday, Nov 8, 2018 05:12:07 AM

**Comment by kizill** [comment]
>  I already did it, but it didn't work.

Could you please execute this two commands one-by-one and paste here full output to help us understand your problem?
First, run `install.packages('devtools')` then run `devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.11.0/catboost-R-Windows-0.11.0.tgz', args = c("--no-multiarch"))`

**Comment by weisskatze** [comment]
By chance, I solved this issue.I installed catboost through anaconda, and then, I executed code you said again. And then, it works!Thanks a lot.
------ Original Message ------
Date: Friday, Nov 9, 2018 05:05:10 PM
