### ISSUE TITLE
Nominal categorical features with multiple string  formatting

### ISSUE THREAD

**Issue by jy03189211** [catboost/catboost#529]
Hello,

I have a column of the non-ordinal categorical features, **material**
I am a bit confused how to corretly  formatting it as input
Formally I was treating them as one hot encoding. since catboost declare a better choice, I'd like to try it out
the column are in pandas column with multi string value delimited with space
list of unique string value['wood','iron','cement','brick']
```
material
'wood iron'
'cement'
'wood element'
'brick wood'
'wood iron cement'
```

I have only float columns in addition to the material columns

would
```
categorical_features_indices = np.where(X.dtypes != np.float)[0]
cat.fit(X_train, y_train,eval_set=validate_pool ,cat_features=categorical_features_indices,plot=True)
```

be enough?

**Comment by annaveronika** [comment]
Hi! Sorry for a long response. I have not fully understood. Can one object have multiple values of material? Currently we support only a single value of category for one object. We are working on supporting multiple values though.
If an object has a single value of material then your code will be enough.

**Comment by jy03189211** [comment]
> If one object has a value ['wood','iron','cement','brick'] - then we don't support it jet.

Thank you! That's what I'd like to confirm.
