### ISSUE TITLE
Cat feature values of Pool objects

### ISSUE THREAD

**Issue by bangeneticalgorithms** [catboost/catboost#532]
Problem: {Lets say I train a model with a categorical feature (or multiple categorical features)
                           Cat Feature Columns
Row 0                'A'
Row 1                'B'
Row 2                'C'
Row 3                 'D'

When I create a Pool object with this dataframe, since there's multiple rows with cat feature value 'A' it knows both values are the same. When I call a pool object on the dataframe and call get_features() the list looks like this

[[10081510400.0], [-5.223943760798657e+29], [-0.2222742885351181], [10081510400.0]]

The I train a model using this dataset. During inference I have a row which has cat feature 'A' for that column. When I create a Pool object and call get_features, the value of 'A' should be 10081510400.0 for inference to work. Is this guaranteed? Is this guaranteed for more any categorical feature

}
catboost version: {0.7.2}}
Operating System: {Ubuntu 16.04}
CPU: {Intel Xeon}
# GPU: {GPU}

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Categorical feature values are replaced with hashes, and the hash function is same at learning and inference stages.
So the answer is yes.

**Comment by annaveronika** [comment]
@bangeneticalgorithms Does this solve your problem?

**Comment by annaveronika** [comment]
I hope, it's fine now. Closing the issue.
