### ISSUE TITLE
Fail to convert model from catboost format into a json format

### ISSUE THREAD

**Issue by towelenee** [catboost/catboost#533]
Problem: I have a model in cb format. I need to transform it into a json format. When I load it and then dump it into json format it crashes the core on c++ function  ConvertModelToJson. It works just fine for other formats. What could be the problem?
Here is a code:
```
from_file = CatBoostClassifier()
from_file.load_model("./MuID-Run2-MC-570-v1.cb")

print(json.dumps(from_file.get_params()))
from_file.save_model("./MuID-Run2-MC-570-v1", format = "json")
```
And you can find model attached 
[tranformation.zip](https://github.com/catboost/catboost/files/2554652/tranformation.zip)

catboost version: 0.10.4.1
Operating System: fedora/ubuntu tested on both operational systems

CPU: intel i7

Thank you in advance for your help.

**Comment by annaveronika** [comment]
Could you please provide the file with the model? We will then debug the problem.

**Comment by annaveronika** [comment]
We'll debug the problem
