### ISSUE TITLE
Python wheel package doesn't contain file verfication hashes

### ISSUE THREAD

**Issue by leenr** [catboost/catboost#534]
`catboost`'s python wheel package doesn't contain file verification hashes in `.dist-info/RECORD` file, as required per [PEP 427 - The Wheel Binary Package Format 1.0](https://www.python.org/dev/peps/pep-0427/#id14).
This makes it impossible to install `catboost` without wheel file modifications via [wheel's reference implemenation](https://github.com/pypa/wheel) and therefore, to build [PEX](https://github.com/pantsbuild/pex) file with `catboost` distribution included.

catboost version: 0.10.4.

**Comment by maxgrenderjones** [comment]
As of `catboost==0.15.2` (and possibly earlier) this is no longer a problem.
