### ISSUE TITLE
YetiRankPairwise needs 40+ times more GPU RAM than YetiRank

### ISSUE THREAD

**Issue by kslazarev** [catboost/catboost#535]
Problem: YetiRankPairwise needs 40+ times more GPU RAM than YetiRank. 337 MiB vs 15754 MiB. 

### Environment

Catboost version: git master / fd3a6c69c088965aded761d3bb6919f3a2aeb926
Operating System: Ubuntu 16.04
GPU: 2 x 1080 TI (2 x 11177 MiB)

### Test Case

Dataset: https://yadi.sk/d/lyZm2CLsCO15LQ
Dataset Specs:
* train_queries.tsv
  - 1919 queries
  - 1023 documents per query
  - 7 features (Num)
  - file size: 154M
* valid_queries.tsv
  - 399 queries
  - 1023 documents per query
  - 7 features (Num)
  - file size: 32M

### YetiRank

CMD: 

`catboost fit -f train_queries.tsv -t valid_queries.tsv --train-dir train_dir --task-type GPU --boosting-type Plain --loss-function YetiRank --eval-metric NDCG:top=100 -w 0.03 --gpu-ram-part 0.015 -r 0 -i 300 --cd cd_file --devices 0 --metric-period 10
`

**GPU RAM Usage: 337 MiB**

`nvidia-smi --query-gpu=timestamp,index,pstate,temperature.gpu,utilization.gpu,utilization.memory,memory.used --format=csv -l 5 -i 0`

> timestamp, index, pstate, temperature.gpu, utilization.gpu [%], utilization.memory [%], memory.used [MiB]
> 2018/11/08 02:52:27.073, 0, P5, 35, 0 %, 0 %, 0 MiB
> 2018/11/08 02:52:32.074, 0, P2, 48, 71 %, 12 %, 337 MiB
> 2018/11/08 02:52:37.075, 0, P2, 49, 61 %, 12 %, 337 MiB
> 2018/11/08 02:52:42.076, 0, P0, 46, 0 %, 0 %, 0 MiB

### YetiRankPairwise

CMD: 

`catboost fit -f train_queries.tsv -t valid_queries.tsv --train-dir train_dir --task-type GPU --boosting-type Plain --loss-function YetiRankPairwise --eval-metric NDCG:top=100 -w 0.03 --gpu-ram-part 0.7 -r 0 -i 300 --cd cd_file --metric-period 10
`

**GPU RAM Usage: 15754 MiB (used 2 GPU), less memory raise Out Of Memory Error**

`nvidia-smi --query-gpu=timestamp,index,pstate,temperature.gpu,utilization.gpu,utilization.memory,memory.used --format=csv -l 5`

> timestamp, index, pstate, temperature.gpu, utilization.gpu [%], utilization.memory [%], memory.used [MiB]
> 2018/11/08 02:57:27.510, 0, P0, 45, 0 %, 0 %, 0 MiB
> 2018/11/08 02:57:27.511, 1, P0, 50, 3 %, 0 %, 0 MiB
> 2018/11/08 02:57:32.512, 0, P2, 45, 99 %, 24 %, 7877 MiB
> 2018/11/08 02:57:32.513, 1, P2, 51, 14 %, 11 %, 7877 MiB
> 2018/11/08 02:57:37.513, 0, P2, 54, 92 %, 86 %, 7877 MiB
> 2018/11/08 02:57:37.514, 1, P2, 56, 97 %, 83 %, 7877 MiB
> 2018/11/08 02:57:42.514, 0, P2, 55, 90 %, 83 %, 7877 MiB
> 2018/11/08 02:57:42.515, 1, P2, 57, 98 %, 85 %, 7877 MiB
> 2018/11/08 02:57:47.515, 0, P2, 57, 92 %, 83 %, 7877 MiB
> 2018/11/08 02:57:47.516, 1, P2, 59, 98 %, 85 %, 7877 MiB
> 2018/11/08 02:57:52.516, 0, P2, 58, 90 %, 83 %, 7877 MiB
> 2018/11/08 02:57:52.517, 1, P2, 60, 97 %, 83 %, 7877 MiB
> 2018/11/08 02:57:57.517, 0, P2, 58, 42 %, 38 %, 7877 MiB
> 2018/11/08 02:57:57.518, 1, P2, 61, 54 %, 45 %, 7877 MiB
> 2018/11/08 02:58:02.518, 0, P0, 54, 0 %, 0 %, 0 MiB
> 2018/11/08 02:58:02.519, 1, P0, 59, 0 %, 0 %, 0 MiB

Out of Memory Traceback

```
Application terminated with error: NCudaLib::TStackLikeMemoryPool<(NCudaLib::EPtrType)0>::TMemoryBlock<char>* NCudaLib::TStackLikeMemoryPool<(NCudaLib::EPtrType)0>::Create<char>(unsigned long)+366 (0x734714E)
NCudaLib::TGpuOneDeviceWorker::AllocateMemory(NCudaLib::IAllocateMemoryTask const&)+171 (0x73455CB)
NCudaLib::TGpuOneDeviceWorker::AllocateTempMemory(unsigned long, NCudaLib::EPtrType, unsigned long)+887 (0x7343F57)
NCudaLib::TGpuOneDeviceWorker::TTempMemoryManager::AllocateImpl(NCudaLib::EPtrType, unsigned long)+87 (0x679EF77)
NKernelHost::TRadixSortKernel<unsigned int, unsigned int>::PrepareContext(NKernelHost::IMemoryManager&) const+875 (0x65D0DDB)
NCudaLib::TGpuKernelTask<NKernelHost::TRadixSortKernel<unsigned int, unsigned int> >::PrepareExec(NKernelHost::IMemoryManager&) const+83 (0x65D0913)
NCudaLib::TGpuOneDeviceWorker::RunIteration()+2223 (0x734493F)
NCudaLib::TGpuOneDeviceWorker::Run()+104 (0x7344D38)
NCudaLib::TGpuOneDeviceWorker::TGpuOneDeviceWorker(int, TIntrusivePtr<NCudaLib::IExceptionCallback, TDefaultIntrusivePtrOps<NCudaLib::IExceptionCallback> >)::'lambda'()::operator()() const+178 (0x679F8C2)
void* std::__y1::__thread_proxy<std::__y1::tuple<std::__y1::unique_ptr<std::__y1::__thread_struct, std::__y1::default_delete<std::__y1::__thread_struct> >, NCudaLib::TGpuOneDeviceWorker::TGpuOneDeviceWorker(int, TIntrusivePtr<NCudaLib::IExceptionCallback, TDefaultIntrusivePtrOps<NCudaLib::IExceptionCallback> >)::'lambda'()> >(void*)+39 (0x679F787)
??+0 (0x7F62DB3BF6BA)
clone+109 (0x7F62DB0F541D)

(NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 1870.507568 MB; Free 1024.22871 MB
uncaught exception:
    address -> 0x106f8b808
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 1870.507568 MB; Free 1024.22871 MB"
    type -> NCudaLib::TOutOfMemoryError
Aborted (core dumped)
```

**Comment by Noxoomo** [comment]
This is correct behavior
For YetiRankPairwise mode we need O(qCount * qSize ^ 2) memory. You have qSize = 1023, so our memory consumption will be  big (Memory usage by gradient computation in YetiRankPairwise is optimized for relatively small queries, like 20-50)

**Comment by kslazarev** [comment]
@Noxoomo so if I need to rank 1000+ docs by query the best catboost options will be  --loss-function YetiRank --boosting-type Ordered. Or there are another variants, could you suggest?

**Comment by annaveronika** [comment]
We'll add this information when writing docs in https://github.com/catboost/catboost/issues/428

About the modes: YetiRankPairwise might give better results especially for large datasets. But if you are bound by memory, you should use YetiRank. About Ordered boosting - it helps to prevent overfitting and usually helps for small datasets, while Plain boosing works better when you have a large dataset. So you can try both Plain and Ordered modes when using YetiRank.

**Comment by annaveronika** [comment]
I pointed out in that issue that we need to write about YetiRank vs YetiRankPairwise. So closing this one as duplicate.
