### ISSUE TITLE
Unexpected GPU RAM allocation when forced 'devices' parameter

### ISSUE THREAD

**Issue by kslazarev** [catboost/catboost#536]
Problem: Unexpected GPU RAM allocation when forced 'devices' parameter

### Environment

Catboost version: git master / fd3a6c69c088965aded761d3bb6919f3a2aeb926
Operating System: Ubuntu 16.04
GPU: 2 x 1080 TI 

### Test Case

Dataset: https://yadi.sk/d/lyZm2CLsCO15LQ

CMD: 

`catboost fit -f train_queries.tsv -t valid_queries.tsv --train-dir train_dir --task-type GPU --boosting-type Plain --loss-function YetiRank --eval-metric NDCG:top=100 -w 0.03 --gpu-ram-part 0.015 -r 0 -i 300 --cd cd_file --devices 0 --metric-period 10
`

GPU RAM Usage

`nvidia-smi --query-gpu=timestamp,index,pstate,temperature.gpu,utilization.gpu,utilization.memory,memory.used --format=csv -l 5`

> timestamp, index, pstate, temperature.gpu, utilization.gpu [%], utilization.memory [%], memory.used [MiB]
> 2018/11/08 03:16:41.799, 0, P5, 36, 0 %, 0 %, 0 MiB
> 2018/11/08 03:16:41.800, 1, P0, 41, 0 %, 0 %, 0 MiB
> 2018/11/08 03:16:46.802, 0, P2, 37, 100 %, 4 %, 337 MiB
> 2018/11/08 03:16:46.802, 1, P2, 43, 0 %, 0 %, 171 MiB
> 2018/11/08 03:16:51.803, 0, P2, 49, 98 %, 16 %, 337 MiB
> 2018/11/08 03:16:51.803, 1, P2, 43, 0 %, 0 %, 171 MiB
> 2018/11/08 03:16:56.804, 0, P2, 51, 98 %, 18 %, 337 MiB
> 2018/11/08 03:16:56.804, 1, P2, 44, 0 %, 0 %, 171 MiB
> 2018/11/08 03:17:01.805, 0, P0, 46, 0 %, 0 %, 0 MiB
> 2018/11/08 03:17:01.806, 1, P0, 45, 0 %, 0 %, 0 MiB

GPU 1 memory.used: 337 MiB
GPU 2 memory.used: 171 MiB (unexpected)

**Comment by Noxoomo** [comment]
Hi!

This memory allocation is done by NVIDIA runtime, catboost doesn't use this memory explicitly and can't free it. 

Btw, i'll look, if we avoid all calls for NVIDIA runtime for unused devices that cause this memory allocation

**Comment by kslazarev** [comment]
Hi! Ok, this isn't cause a problem, just unexpected events in logs / need check.
