### ISSUE TITLE
R installation using binary, source and devtools

### ISSUE THREAD

**Issue by VKON** [catboost/catboost#538]
Problem: {cannot install in R}
catboost version: {catboost_0.11.0}
Operating System: {windows 7 x64}
CPU: {CPU}
# GPU: {GPU}

Dear developers,

I have not been able to install catboost using the binary or the source file. I also tried devtools, but unfortunately unsuccessfully. Please have a look at the errors below and let me know your thoughts. I noticed one thing which I found strange: the slash direction was different when devtools tried to install the file (see below). I added my comment on stackoverflow, if that helps:

https://stackoverflow.com/questions/49689345/catboost-building-and-installing-error-in-r/53247952?noredirect=1#comment93380817_53247952

Here the comment, thanks again for your time:

I am so glad you were asking.

A few months later, I couldn't install it on my laptop with R 3.5.1. Perhaps you were more successful today? Please let me know even if not.

Ive tried both in R 64bit, and RStudio, see my system specs at the bottom of this post. I updated my Rtools and devtools prior to installation and Ive got VS 2017 on my system. To make sure, I updated and reinstalled the R packages one more time.

I followed the Yandex installation guide but it doesnt work, otherwise I wouldnt be writing here now: https://tech.yandex.com/catboost/doc/dg/installation/r-installation-local-copy-installation-windows-docpage/#r-installation-local-copy-installation-windows.

I am quite surprised I could not reproduce it as the guide was very well written.

1) Error when installing from binary:

setwd("C:/Users/../Desktop") install.packages("catboost-0.11.0.zip", repos = NULL, type = 'binary') Installing package into ‘C:/Users/../Documents/R/win-library/3.5’ (as ‘lib’ is unspecified) Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : cannot open the connection In addition: Warning messages: 1: In unzip(zipname, exdir = dest) : error -1 in extracting from zip file 2: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : cannot open compressed file 'catboost-0.11.0/DESCRIPTION', probable reason 'No such file or directory'

2) Error when installing from source:

setwd("C:/Users/../catboost/catboost/") install.packages("catboost_0.11.0.tar.gz", repos = NULL, type = 'source') Installing package into ‘C:/Users/../Documents/R/win-library/3.5’ (as ‘lib’ is unspecified) * installing source package 'catboost' ... ** libs running 'src/Makefile.win' ... Warning in system(paste("make --no-print-directory", paste("-f", shQuote(makefiles), : 'make' not found ERROR: compilation failed for package 'catboost' * removing 'C:/Users/../Documents/R/win-library/3.5/catboost' In R CMD INSTALL Warning message: In install.packages("catboost_0.11.0.tar.gz", repos = NULL, type = "source") : installation of package ‘catboost_0.11.0.tar.gz’ had non-zero exit status

3) Error when following the readme and trying to install via devtools via URL

devtools::install_github('catboost/catboost', subdir = 'catboost/R-package') Downloading GitHub repo catboost/catboost@master Error in file(name, "wb") : cannot open the connection In addition: Warning message: In file(name, "wb") : cannot open file 'catboost-catboost-3a4e370/catboost/pytest/canondata/test.test_ctr_type_calc_block=5000000-Ordered-Borders_BinarizedTargetMeanValue_TargetBorderCount=10_/': Invalid argument

4) Error when installing from local files with build devtools

setwd("C:/Users/../catboost/catboost/R-package") devtools::build() checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION' ... checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION' ... √ checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION'

preparing 'catboost': checking DESCRIPTION meta-information ... checking DESCRIPTION meta-information ... √ checking DESCRIPTION meta-information
cleaning src
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'catboost_0.11.0.tar.gz' [1] "C:/Users/../catboost/catboost/catboost_0.11.0.tar.gz"
devtools::install()
checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION' ... checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION' ... √ checking for file 'C:\Users..\catboost\catboost\R-package/DESCRIPTION

preparing 'catboost': checking DESCRIPTION meta-information ... checking DESCRIPTION meta-information ... √ checking DESCRIPTION meta-information
cleaning src
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'catboost_0.11.0.tar.gz'
Running "C:/PROGRA~1/R/R-35~1.1/bin/i386/Rcmd.exe" INSTALL "C:\Users..\AppData\Local\Temp\RtmpasdQyh/catboost_0.11.0.tar.gz" --install-tests

* installing to library 'C:/Users/../Documents/R/win-library/3.5'
installing source package 'catboost' ... ** libs running 'src/Makefile.win' ... Warning in system(paste("make --no-print-directory", paste("-f", shQuote(makefiles), : 'make' not found ERROR: compilation failed for package 'catboost'
removing 'C:/Users/../Documents/R/win-library/3.5/catboost' | In R CMD INSTALL
I have a feeling the DESCRIPTION folder might be provided with the wrong kind of slash: \ instead of /, have a look at Error 4. May this be the reason the DESCRIPTION cannot be found'? I dont know...Apart form that, I dont see a reason why none installations is successful.

Happy to hear from you if you succeeded or if you did not.

sys info:

platform x86_64-w64-mingw32
arch x86_64
os mingw32
system x86_64, mingw32
status
major 3
minor 5.1
year 2018
month 07
day 02
svn rev 74947
language R
version.string R version 3.5.1 (2018-07-02) nickname Feather Spray

**Comment by kizill** [comment]
Could you try to install pre-built binary package https://tech.yandex.com/catboost/doc/dg/installation/r-installation-binary-installation-docpage/ with 
`devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.11.0/catboost-R-Windows-0.11.0.tgz', args = c("--no-multiarch"))` ?

**Comment by VKON** [comment]
Thanks kizill,

I am sorry, this was not successful. I understand it must be working for you? Does nobody have this problem, what could it be, what do you think? 

Just a silly question perhaps, but do you think the destination might be given with the wrong kind of slash in the directory? I mean a \ and / kind of mistake in the destination such as checking for file 'C:\Users\..\AppData\Local\Temp\RtmpiCNKHK\remotes279c4171611b\catboost/DESCRIPTION'




Here the full log:

devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.11.0/catboost-R-Windows-0.11.0.tgz', args = c("--no-multiarch"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.11.0/catboost-R-Windows-0.11.0.tgz
  
  
  
   checking for file 'C:\Users\..\AppData\Local\Temp\RtmpiCNKHK\remotes279c4171611b\catboost/DESCRIPTION' ...
  
   checking for file 'C:\Users\..\AppData\Local\Temp\RtmpiCNKHK\remotes279c4171611b\catboost/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\..\AppData\Local\Temp\RtmpiCNKHK\remotes279c4171611b\catboost/DESCRIPTION'

  
  
  
-  preparing 'catboost': (540ms)
   checking DESCRIPTION meta-information ...
  
√  checking DESCRIPTION meta-information

  
  
  
-  checking for LF line-endings in source and make files and shell scripts

  
  
  
-  checking for empty or unneeded directories

  
  
  
-  building 'catboost_0.11.0.tar.gz'

  
   

Installing package into ‘C:/Users/../Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'catboost' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'catboost'
    finding HTML links ... done
    catboost.caret                          html  
    catboost.drop_unused_features           html  
    catboost.get_feature_importance         html  
    catboost.get_model_params               html  
    catboost.get_object_importance          html  
    catboost.load_model                     html  
    catboost.load_pool                      html  
    catboost.predict                        html  
    catboost.save_model                     html  
    catboost.save_pool                      html  
    catboost.shrink                         html  
    catboost.staged_predict                 html  
    catboost.train                          html  
    dim.catboost.Pool                       html  
    dimnames.catboost.Pool                  html  
    head.catboost.Pool                      html  
    print.catboost.Pool                     html  
    tail.catboost.Pool                      html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error : package 'catboost' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/../Documents/R/win-library/3.5/catboost'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/../AppData/Local/Temp/RtmpiCNKHK/file279c150e4f3/catboost_0.11.0.tar.gz’ had non-zero exit status

**Comment by dbakshee** [comment]
Hi @VKON ,
Could you try command `R CMD INSTALL . --build` in directory `catboost/R-package` ? This is nearly equivalent to R commands
```
setwd('...../catboost/R-package')
devtools::install('.', '--build')
```

It looks like 32-bit and 64-bit environments interfere with each other (look for `/bin/i386/Rcmd.exe` in your logs).

**Comment by VKON** [comment]
Dear @dbakshee , 

The answer is still no but I am glad you may have identified a potential root cause. 

$ R CMD INSTALL . --build
In R CMD INSTALL
* installing to library 'C:/Users/../Documents/R/win-library/3.5'
* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
Warning in system(paste("make --no-print-directory", paste("-f", shQuote(makefiles)
,  :
  'make' not found
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/../Documents/R/win-library/3.5/catboost'


It is basically the same error as the one I get with devtools::install(): 


running 'src/Makefile.win' ...
|arning in system(paste("make --no-print-directory", paste("-f", shQuote(makefiles),  :
  'make' not found

So what about this make file, why is it not found, or whats wrong with it? At least it seemed to have found the description file. I assume you all have managed to get it up and running in R, may I ask which version and operating system you are using? Could it be a version issue? 

Thanks again!

**Comment by dbakshee** [comment]
Dear @VKON, 

To build packages for R on Windows you definitely need to install an [Rtools](https://cran.r-project.org/bin/windows/Rtools) package, in addition to MS Visual Studio. The Rtools package  contains the `make` utility that R failed to locate on your system. `make` is necessary to build packages. The Rtools also contains uncompressors `tar` and `unzip` that would help to install the package from a `catboost*.tar.gz` file. 

Thanks
Dima

**Comment by VKON** [comment]
I have Rtools Version 3.5 on my system, and I just checked if I can start Visual Studio, and I can. I have MS VS Community 2017 Version 15.3.2 installed. 

Any other leads?

**Comment by dbakshee** [comment]
The message `'make' not found` indicates that Rtools is not involved, possibly because it is not in the PATH.
You can check this in R console by typing `system('where make')` or `system('make --version')` - both commands should give a meaningful output.

**Comment by VKON** [comment]
Interesting, you might not be aware that my catboost package sits in a different folder than my Rbuildtools. 

this is where catboost is:
setwd("C:/Users/../catboost/catboost/R-package")

this is where RbuildTools is:
setwd("C:/RBuildTools/3.5/bin")

if I stay in that folder, and run
system('where make')

I find it there. 
C:\RBuildTools\3.5\bin\make.exe

When I want to run 
devtools::build()
devtools::install()

I have to go to the catboost directory. I suppose I just need to let R know both paths, so how do you suggest to add the path?
Thanks for your efforts, much appreciated!

**Comment by VKON** [comment]
PS I think this might be helpful, I havent read through it all just yet:
http://r.789695.n4.nabble.com/Setting-the-path-to-Rtools-for-package-compilation-on-Windows-td4748266.html

There was another potential solution cited but a little short in its description, but perhaps allows you to give a recommendation:
https://stackoverflow.com/questions/47539125/how-to-add-rtools-bin-to-the-system-path-in-r

**Comment by dbakshee** [comment]
Thank you for the references. They seem to suffer of similar if not the same issue: Rtools not in PATH.

Possible solutions:
Option 1. When installing Rtools, do not miss Installer's checkbox `[x] Add rtools to system PATH`. After installation you should probably reboot the system. After reboot, rtools should be accessible.

Option 2. Set your environment yourself. Open 'Control panel', search for Environment variables, edit Path (either user or system) to have Rtools/bin listed, save. After that, restart your Rstudio or command line - rtools should be accessible. The same way you may want to set `BINPREF` environment variable, though I am not sure it is neccessary.

**Comment by VKON** [comment]
Thanks, I tried Option 2 first:

So now when I go to my catboost directory and run build and install devtools, it has an issue with ya.bat while running 'src/Makefile.win'. It also gives you a traceable error 127 that might further help to troubleshoot this. I feel we are getting closer. Ideas?


Running "C:/PROGRA~1/R/R-35~1.1/bin/x64/Rcmd.exe" INSTALL \
  "C:\Users\..\AppData\Local\Temp\RtmpI3AzHJ/catboost_0.11.0.tar.gz" \
  --install-tests 
* installing to library 'C:/Users/../Documents/R/win-library/3.5'
* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/../AppData/Local/Temp/RtmpAv5NZR/R.INSTALL2aec10145867/catboost/src/../../../ya.bat make -r -o ../../.. -DHAVE_CUDA=no "-DCUDA_ROOT=" -DCUDA_HOST_COMPILER=
sh: /cygdrive/c/Users/../AppData/Local/Temp/RtmpAv5NZR/R.INSTALL2aec10145867/catboost/src/../../../ya.bat: No such file or directory
make: *** [Makefile.win:9: all] Error 127
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/../Documents/R/win-library/3.5/catboost'
In R CMD INSTALL

**Comment by VKON** [comment]
Thanks @dbakshee for trying. 


meanwhile I tried Option 1, and added Rtools to path during installation, it also did not work. the .. are my username, here illustrated with VKON.

 setwd("C:/Users/VKON/catboost/catboost/R-package")
getwd()
devtools::build()
devtools::install()

Running "C:/PROGRA~1/R/R-35~1.1/bin/x64/Rcmd.exe" INSTALL \
  "C:\Users\VKON\AppData\Local\Temp\RtmpwtSv0a/catboost_0.11.0.tar.gz" \
  --install-tests 
* installing to library 'C:/Users/VKON/Documents/R/win-library/3.5'
* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/Users/VKON/AppData/Local/Temp/Rtmpai7ZRg/R.INSTALL2b347e47426d/catboost/src/../../../ya.bat make -r -o ../../.. -DHAVE_CUDA=no "-DCUDA_ROOT=" -DCUDA_HOST_COMPILER=
sh: /Users/VKON/AppData/Local/Temp/Rtmpai7ZRg/R.INSTALL2b347e47426d/catboost/src/../../../ya.bat: No such file or directory
make: *** [Makefile.win:9: all] Error 127
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/VKON/Documents/R/win-library/3.5/catboost'
In R CMD INSTALL


Do you think it  the visual studio version might not be high enough, causing the problem in the first place? I have this one:

Microsoft Visual Studio Community 2017 
Version 15.3.2
VisualStudio.15.Release/15.3.2+26730.10
Microsoft .NET Framework
Version 4.7.02558

I read the note in your installation guide:

Visual Studio forcibly installs the latest version of the compiler upon each update. The latest MSVC compiler may not be suitable for compiling CatBoost, especially with CUDA. It is advised to install VC++ 2017 version 15.6 v14.13 for CUDA Toolkit 9.2 and 15.6 v14.11 for CUDA Toolkit 9.0 and 9.1.

I opened VS and checked in help-info what is installed. I cant find CUDA in there, yet you talk about the MSVC compiler for CUDA in a specific version, so maybe the problem lies in there. 

How and from where do I get the right MSVC compiler and the CUDA toolkit you are talking about? And how do I update to that specific version 15.6 v14.11, I think the current version is 15.9 so seems like I first have to upgrade, then downgrade VS? 

Sorry if the questions may sound basic for you. I feel there are a lot of dependencies and knowledge required to get going and I would really like to try catboost. 


Thanks for your patience!

**Comment by StefHai** [comment]
The following code worked for me:

install.packages('devtools',dependencies = T)
library(devtools)
options(devtools.install.args = c("--no-multiarch", "--no-test-load"))
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.11.1/catboost-R-Windows-0.11.1.tgz', INSTALL_opts  = c("--no-multiarch", "--no-test-load"))

**Comment by VKON** [comment]
Confirmed!


Thanks StefHai, well done. I consider this issue closed after someone from your side could please update the R installation guide to prevent any others to run into the same issues as I did. 

Thanks to all involved!

**Comment by StefHai** [comment]
Just a few lines to the post above:
I think that when you have R-32bit and R-64bit installed, devtools::install_url tries to do a test load for 32bit and 64bit at the end of the installation process - and fails for 32bit and does a rollback.
"--no-test-load" prevents the test load.

**Comment by VKON** [comment]
congratulations @timchurches - your participation in the thread will hopefully help others to achieve what you did today. And thanks again @StefHai & catboost devs.

**Comment by annaveronika** [comment]
Need to add --no-test-load hint to our documentation. We'll close when it's done.
