### ISSUE TITLE
Titanic cross-validation error

### ISSUE THREAD

**Issue by RinatSafianov** [catboost/catboost#54]
I try to run kaggle_titanic_catboost_demo.ipynb.
And CV procedure returns empty array for 'Accuracy_test_avg'.
![image](https://user-images.githubusercontent.com/23735708/28502858-23b8f2ba-7004-11e7-9e84-77ee300212cf.png)

**Comment by asaitgalin** [comment]
Issue: MATRIXNET-770

**Comment by nikitxskv** [comment]
@RinatSafianov Hello!
In last version it should be fixed.
