### ISSUE TITLE
catboost.caret$predict crash R-Session

### ISSUE THREAD

**Issue by StefHai** [catboost/catboost#540]
Problem: R-Session in R-Studio crashs when calling catboost.caret$predict directly
catboost version: 0.10.3
Operating System: windows 2012
CPU: x64

I have trained a regression with caret and saved the final model with saveRDS.
After loading the model with readRDS and calling catboost.caret$predict, the R-session crashs.
When I use the code from https://github.com/catboost/catboost/blob/8bcfbad2c8ce9085194c28c8c9553626bd9f7f2c/catboost/R-package/R/catboost.caret.R and remove line 85: "param <- catboost.get_model_params(modelFit)" the call works. 
I'm not sure if you need this line, because as far as I can see the variable param is not used in the function.

Btw: Thank's for providing catboost :)

**Comment by dbakshee** [comment]
Hi @StefHai , 
Thank you for reporting the issue. 
It should have been fixed in catboost 0.10.4.
