### ISSUE TITLE
Add multiple outputs request

### ISSUE THREAD

**Issue by karacor** [catboost/catboost#547]
It would be an awesome feature to have multiple output/target option in both regression and classification.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi karacor,
Since you can tell CatBoost to ignore any columns of your choice, you can have multiple target columns using one of them for training, and ignoring the other ones.
Could you please explain your request in detail?

**Comment by karacor** [comment]
Hi Evgueni,

Let's say I have an input feature set related with past and present weather activity, and I would like to predict the future air temperature, and not only that but water temperature, humidity, rain amount, etc. using the same input features; however, instead of training a separate model for each target value to be predicted I would like to train one model with all the targets together, and use this one model to predict the  whole future weather activity.
Or let's assume I have an integer target variable ranging from 0 to 7. Instead of modelling it as a multiple classification problem, I would like to encode the value to get a 4 output (binary digits) model:

```
8 -> 1 0 0 0
7 -> 0 1 1 1
.
0 -> 0 0 0 0
```
Hence I'd like to train one model to predict all 4 binary target values simultaneously.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks! Will discuss and reply soon.

**Comment by snowzjy** [comment]
This is a very good idea!

**Comment by yichuj** [comment]
I would very much love this feature as well. Just wondering if we have any updates on this.

**Comment by annaveronika** [comment]
We are not working on it yet. Contributions are very welcome! Adding help wanted flag.

**Comment by Jerry2001Qu** [comment]
Any updates on this? Currently, I'm just going to iteratively create 15 different Regressors on each of my targets.

**Comment by annaveronika** [comment]
Multi regression is now supported: https://catboost.ai/docs/concepts/loss-functions-multiregression.html

**Comment by kmedved** [comment]
How does this functionality work exactly? Is this fitting independent models for each target, or is there some relationship between the targets being captured as well?

Thanks!

**Comment by liberbey** [comment]
Hi @kmedved, did you find the answer of your question?

**Comment by kmedved** [comment]
Unfortunately not @liberbey

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@liberbey @kmedved 
Multi-regression is a loss function involving multiple target columns.
Catboost builds a single model to minimize this loss.
This loss is computed according to https://catboost.ai/docs/concepts/loss-functions-multiregression.html

**Comment by gabrielgcbs** [comment]
Hi, as seen in this issue, MultiOutputRegression is now supported, but is MultiOutputClassification going to be supported too? Thanks.

**Comment by ogencoglu** [comment]
Any plans to support multi-task learning where one task is classification and targets are categorical (classes) and the other task is regression?

**Comment by Sandy4321** [comment]
can you share what algorithm is used for multi target regression . But there is no explanation what algorithm  used for catbost and how better it is than just one model for each target ?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
> algorithm is used for multi target regression

generic gradient boosted decision trees

> how better it is than just one model for each target

multi target regression models are more accurate, if targets are correlated
