### ISSUE TITLE
Inference in Python without data copy overhead

### ISSUE THREAD

**Issue by Goorman** [catboost/catboost#549]
Hello, i wanted to ask if it is possible to apply catboost model to a numpy array of features in Python without massive overhead to basically copy all input data.

https://github.com/catboost/catboost/blob/e442c570bd1916092de1b317f4dec87830c16dc1/catboost/python-package/catboost/_catboost.pyx#L1092-L1101

This overhead is negligible when working with tens of thousands of trees, but when working with small ensembles the time to construct Pool can take most of the inference time.

Thank you.

**Comment by andrey-khropov** [comment]
Some optimizations eliminating the need to copy source data if it is stored as numpy array are planned in the near future. 

Just to be sure - do you pass your data as numpy array with dtype = numpy.float32 or as a [FeaturesData](https://tech.yandex.com/catboost/doc/dg/concepts/python-features-data__desc-docpage/) structure?

In these cases CatBoost uses native code implementation [_set_data_np](https://github.com/catboost/catboost/blob/e442c570bd1916092de1b317f4dec87830c16dc1/catboost/python-package/catboost/_catboost.pyx#L1064) which is mush faster than python code that deals with generic type and/or layout matrices - [_set_data_from_generic_matrix](https://github.com/catboost/catboost/blob/e442c570bd1916092de1b317f4dec87830c16dc1/catboost/python-package/catboost/_catboost.pyx#L1114).

**Comment by Goorman** [comment]
Yes, I am using numpy.float32 -> FeaturesData -> predict (-> to Pool inside) so the main bottleneck is data copy. 
Glad to hear that you are working on it, thank you!

**Comment by andrey-khropov** [comment]
Commit https://github.com/catboost/catboost/commit/10f79b2d551ffbf3880e0d5fca2e089d22832b26

avoids copying if data is compatible with internal CatBoost raw (not quantized/binned) numerical features data representation (dtype is numpy.float32 and data is continuous and stored column-wise (order='F')). This works for numerical features data represented as as numpy.ndarray, FeaturesData and pandas.DataFrame.

It will be included in the next main release supposed to be shipped very soon.

We are also planning to have similar native support for other common numerical data types in numpy (int32,uint32,int64,uint64,float64).

**Comment by Goorman** [comment]
Great, thank you!
As a QoL improvement for the future, would you consider adding a flag <no_copy> into Pool constructor, which if set True would raise an error if data is incompatible with CatBoost raw format and has to be copied?

**Comment by andrey-khropov** [comment]
Released in 0.12.0.

> As a QoL improvement for the future, would you consider adding a flag <no_copy> into Pool constructor, which if set True will raise an error if data is incompatible with CatBoost raw format and has to be copied?

We'll think about how to properly implement this (or you could help!), I've made a separate issue for this: https://github.com/catboost/catboost/issues/601

**Comment by Goorman** [comment]
I would be glad to contribute, only i am not sure adding ~3 lines of code can be considered "contributing" ;) You could add tests of course, but who counts those...

**Comment by annaveronika** [comment]
Of course this is considered contributing! That's a good way to start. We'll help if there will be any questions.

**Comment by anuragreddygv323** [comment]
is this feature added ?

**Comment by anuragreddygv323** [comment]
@annaveronika  is this feature added ?

**Comment by annaveronika** [comment]
Yes, it should work now.

**Comment by anuragreddygv323** [comment]
how to use this feature ? any example ?

**Comment by annaveronika** [comment]
The latest version has this feature. You need to use numpy matrix and it will work out of the box, you don't need to do anything extra.

**Comment by anuragreddygv323** [comment]
@annaveronika Is it possible to train the model without creating the pool object ?
