### ISSUE TITLE
Wrong slash in .vcproj files 

### ISSUE THREAD

**Issue by Alhel** [catboost/catboost#55]
for example output:
1>$B/contrib/libs/coreml/ArrayFeatureExtractor.pb.cc
1>'" \catboost\catboost\msvs\Debug/contrib/tools/protoc/protoc.exe"' is not recognized as an internal or external command,
1>operable program or batch file.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009.
1>Done building project "contrib-libs-coreml.vcxproj" -- FAILED.

contrib-libs-coreml.vcproj 
...
"$(SolutionDir)$(Configuration)/contrib/tools/protoc/protoc.exe" "-I=./" "-I=$(SolutionDir)../" "-I=$(SolutionDir)$(Configuration)" "-I=$(SolutionDir)../contrib/libs/protobuf" "--cpp_out=$(SolutionDir)$(Configuration)/" "--cpp_styleguide_out=$(SolutionDir)$(Configuration)/" "--plugin=protoc-gen-cpp_styleguide=$(SolutionDir)$(Configuration)/contrib/tools/protoc/plugins/cpp_styleguide/cpp_styleguide.exe" "contrib/libs/coreml/ArrayFeatureExtractor.proto"
...

**Comment by exprmntr** [comment]
Hello

It works for me (Windows 10, Visual Studio 2017). Please provide some details, how can I reproduce this problem?

**Comment by Alhel** [comment]
Hello,
I use windows 7 and Visual Studio 2017 Comunity(15.2) , visual studio 2015(v14) build tools

**Comment by exprmntr** [comment]
DEVTOOLS-3600 (internal ticket, to not forget)

**Comment by annaveronika** [comment]
Does the problem still exist?

**Comment by Alhel** [comment]
yes:
catboost\catboost\msvs\Debug**/t**ools**/**enum_parser**/**enum_parser**/**enum_parser.exe"' is not recognized as an internal or external command,
2>operable program or batch file.
in .vcxproj you use unix style path: 
"$(SolutionDir)$(Configuration)/tools/enum_parser/enum_parser/enum_parser.exe" "$(SolutionDir)../library/logger/priority.h" "--include-path" "library/logger/priority.h" "--output" "$(SolutionDir)$(Configuration)/library/logger/priority.h_serialized.cpp"

**Comment by annaveronika** [comment]
This is not about the slashes. It was a bug in visual studio:
https://developercommunity.visualstudio.com/content/problem/24975/vs-2017-rtm-ignores-project-dependencies-build-fai.html
