### ISSUE TITLE
CUDA CLI make broken

### ISSUE THREAD

**Issue by francky06l** [catboost/catboost#552]
Hello,
Using the app.CUDA.CLANG50-LINUX-X86_64.makefile failed on nvcc invocation.

Catboost pulled from master:
`catboost --version
Git info:
    Commit: 7e7ffefacbe10b67eceac7c79d78517f21cf7938`

OS: Opensuse Leap 15
CUDA: 10.0

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
`

The issue comes from these 2 flags that are actually identical (-ccbin is the short flag for --compiler-bindir)

`
-ccbin ${CC} -std=c++14 '--compiler-bindir=$(CUDA_HOST_TOOLCHAIN-sbr:243907179)/bin/clang'
`
The --compiler-bindir becomes /bin/clang that does not exists, /usr/bin/clang (version 5.0.2) different from  $CC=/usr/bin/clang-5.0.
Not sure if it's because of nvcc version or because the 2 flags are solved with different values, anyway removing --compiler-bindir flag solve the problem and it builds.

**Comment by kizill** [comment]
Closing as we now have new issues in building catboost with CUDA support via makefiles. We are working with our devtools to solve them.
