### ISSUE TITLE
catboost multiclassification shap_values

### ISSUE THREAD

**Issue by canglangshushu** [catboost/catboost#553]
Problem: {1 and 2 below}
catboost version: {'0.10.4.1'}
Operating System: {windows 10}
CPU: {CPU}
1.shap_values1= model.get_feature_importance(pool, fstr_type=catboost.EFstrType.ShapValues)
shap_values.shape #return  (num,class,feature+1),I want to know why it returns feature+1?shap.summary_plot# not work well 
2.explainer = shap.TreeExplainer(model)
shap_values2 = explainer.shap_values(catboost.Pool(X, y))
shap_values.shape  #return  type is list
shap.summary_plot# work well 
I want to know what's the difference between shap_values1  and shap_values2 ?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi canglangshushu,

The extra column in shap_values1 stores the expected prediction (the same value in each row).
In shap_values2 this column is removed, and the expected prediction is stored as scalar.
Please have a look at shap module for more detail ([link](https://github.com/slundberg/shap/blob/5d5f1c4136175fd7240b9cd05d4d31c6a212c5fa/shap/explainers/tree.py#L178))

**Comment by canglangshushu** [comment]
@Evgueni-Petrov-aka-espetrov 
Thank you for your quick reply. I will check the document carefully

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Please feel free to re-open, if you have questions :)
