### ISSUE TITLE
How to apply "apply_catboost_model" from a "standalone Python code" export on new data

### ISSUE THREAD

**Issue by robroe-tsi** [catboost/catboost#558]
Problem: How can we apply a "standalone Python code" export (https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_apply_catboost_model-docpage/)  to new data using **apply_catboost_model**?

The provided tutorial (https://github.com/catboost/tutorials/blob/master/apply_model/model_export_as_python_code_tutorial.md) states:

> The exported model code contains complete data for the current trained model and apply_catboost_model() function which applies the model to a given dataset.

But the method "apply_catboost_model" just have two parameters for specifiying the indices to the float and categorial features. The tutorial shows example code how to export a learned model but shows no concret example how to apply the "apply_catboost_model" function.

This is how far I got:
```Python
from catboost.datasets import titanic
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder  
from sklearn import tree
import numpy as np
import pandas as pd

# data loading
train_df, test_df = titanic()
train_df.head()

# prepare data
train_df.fillna(-999, inplace=True)
test_df.fillna(-999, inplace=True)

train_df['Name'] = train_df['Name'].str.replace('"','\'')
test_df['Name'] = test_df['Name'].str.replace('"','\'')

# define categorial feature list - needed for prediction
float_features_indices = np.where(train_df.dtypes == np.float)[0]
categorical_features_indices = np.where(train_df.dtypes != np.float)[0]

# load the model
from models.model_simple_example import apply_catboost_model

# apply the model - how?
# apply_catboost_model(...)

# apply_catboost_model(float_features=float_features_indices, cat_features=categorical_features_indices)
# resulting in 0.5529792437937432, but for me makes no sense
```

Here is the corresponding model file:
[https://github.com/catboost/catboost/files/2626250/model_simple_example.zip](url)

catboost version: 0.11.1
Operating System: Win7
CPU: i7-6820HQ
GPU: NVIDIA Quadro M1000M

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi robroe-tsi,
Overall, apply_catboost_model expects a single row from the test dataset split into float and cathegirical values.
The following test ([link](https://github.com/catboost/catboost/blob/2c0e317fd4861d1d6b454016272dca9a14cfe72a/catboost/libs/model/model_export/ut/test.py#L134)) shows how to use apply_catboost_model.

**Comment by robroe-tsi** [comment]
Hi @Evgueni-Petrov-aka-espetrov ,

thanks for the link. That helped me a lot. Why not adding this test as an example to the documentation? would help a lot .

Taken you example from the test I experienced also a strange behavior regarding the predicted scores. Taking a records features from a Pool object and modifying it with your custom "split_features" function results in a different score than it should be. Here is an example that compares taking a record from the Pool object with taking a record from the pandas DF:
```Python
# Model Exported as Python code - using transformed record from data pool
split_features
def split_features(features, cat_features_indices, hash_to_string):
    float_features = []
    cat_features = []
    for i in range(len(features)):
        if i in cat_features_indices:
            cat_features.append(hash_to_string[features[i]])
        else:
            float_features.append(features[i])
    return float_features, cat_features
​
first_test_instance = test_pool.get_features()[0]
float_features, cat_features = split_features(first_test_instance, 
                                              categorical_features_indices, 
                                              test_pool.get_cat_feature_hash_to_string())
print(float_features)
print(cat_features)
apply_catboost_model(float_features=float_features, cat_features=cat_features)
# [34.5, 7.82919979095459]
# [b'892', b'3', b'Kelly, Mr. James', b'male', b'0', b'0', b'330911', b'-999', b'Q']
# -0.7677998507156258
```
vs

```Python
# Model Exported as Python code - using pandas df
float_feat_values = X_test.iloc[0,float_features_indices].values.tolist()
cat_feat_values = [str(i) for i in X_test.iloc[0,categorical_features_indices].values.tolist()]

print(float_feat_values)
print(cat_feat_values)
apply_catboost_model(float_features=float_feat_values, cat_features=cat_feat_values)
# [34.5, 7.8292]
# ['892', '3', 'Kelly, Mr. James', 'male', '0', '0', '330911', '-999', 'Q']
# -2.006561232213108
```
The second part is the correct one (with -2.0065) as it matches the results from the python model API
```Python
# Standard python model API - using pandas df
print(X_test.iloc[0:1,:])
print(model.predict(X_test.iloc[0:1,:], prediction_type='RawFormulaVal'))
#    PassengerId  Pclass              Name   Sex   Age  SibSp  Parch  Ticket  \
# 0          892       3  Kelly, Mr. James  male  34.5      0      0  330911   
#
#    Fare Cabin Embarked  
# 0  7.8292  -999        Q  
# [-2.00656123]
```
or 
```Python
# Standard python model API - using Pool record
print(model.predict(test_pool, prediction_type='RawFormulaVal')[0])
#  -2.006561232213108
```
This might be something you should investigate.

Best, Roberto

Jupyter Workbook attached 
[Catboost Model Application Approaches.zip](https://github.com/catboost/catboost/files/2637040/Catboost.Model.Application.Approaches.zip)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Looks like a bug.
