### ISSUE TITLE
cat_features in __init__ rather than in fit

### ISSUE THREAD

**Issue by chanansh** [catboost/catboost#564]
I find it more suitable to have cat_features as part of the __init__ rather than as part of the fit argument.
This will make using sklearn over catboost easier (e.g. pipeline etc.).
sklearn has problem to pass parameters at fit time,

**Comment by annaveronika** [comment]
it is possible tu pass cat_features both to the init function and to the fit function.

**Comment by chanansh** [comment]
thanks
