### ISSUE TITLE
Catboost ranking objective 

### ISSUE THREAD

**Issue by MiaoBao** [catboost/catboost#570]
Problem: I was comparing the models using different objectives for ranking. It seems that catboost implements several novel objectives that other algorithms haven't used before. I would love to learn more about them but the documentation on how those objective are computed are not detailed enough (https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/#loss-functions__ranking) . Could anyone point me to other resources regarding the objectives? 

More specifically, I want to know the difference between PairLogit/yetiRank and PairLogitPairwise/YetiRankPairwise. Also some more documentations on QuerySoftMax, QueryRMSE and QueryCrossEntropy would be great. 

catboost version: {version}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi MiaoBao,

You might want to have a look at our [Ranking Tutorial](https://github.com/catboost/tutorials/blob/master/ranking/ranking_tutorial.ipynb) .

**Comment by annaveronika** [comment]
Here is a set of papers about catboost: https://tech.yandex.com/catboost/doc/dg/concepts/educational-materials-papers-docpage/ 
"Winning The Transfer Learning Track of Yahoo!’s Learning To Rank Challenge with YetiRank" paper explains the pairwise modes.

**Comment by kizill** [comment]
https://catboost.ai/docs/concepts/loss-functions-ranking.html - we have a documentation about loss functions for ranking.
