### ISSUE TITLE
thread_count = -1 does not work (python)

### ISSUE THREAD

**Issue by chanansh** [catboost/catboost#572]
Problem:
According to documentation value of -1 means use all cpus. However, I get the following error message:
```
_catboost.CatboostError: catboost/libs/options/json_helper.h:152: Can't parse parameter "thread_count" with value: -1
```
catboost version: 0.11.1
Operating System: Ubuntu
CPU: Intel

**Comment by annaveronika** [comment]
This is bug in documentation. Please set thread_count to nan or don't set it, then all cpus will be used.

**Comment by chanansh** [comment]
thanks

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
I reopen the issue as we plan to fix this to improve compatibility with XGBoost.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
https://github.com/catboost/catboost/commit/8d715e9f9f0999d867b6884780ebb0ff0a33b727
