### ISSUE TITLE
how to get all the sub-estimators

### ISSUE THREAD

**Issue by zhenyiy** [catboost/catboost#573]
Problem: {How to get all the sub-estimators}
catboost version: {0.11.1}
Operating System: {Amazon Linux}
CPU: {Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz}
GPU: {K80}

Hi,
I am wondering whether there is a way that I can get the list of all sub-estimators. In sklearn.ensemble.AdaBoostClassifier(https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html#sklearn.ensemble.AdaBoostClassifier), I can get all the sub-estimators.

> estimators_ : list of classifiers
> The collection of fitted sub-estimators.
>  
Can I get the sub-estimators in catboost?

Thanks

**Comment by annaveronika** [comment]
No, it's not possible. What is your scenario, maybe we can solve it without sub-estimators?

**Comment by zhenyiy** [comment]
I want to get all the estimators and then use the predictions from them as the input layer of the neural network. With this approach, I can get the benefit of both a state of art boosting models and a neural network.

**Comment by annaveronika** [comment]
I am not sure that this approach will be beneficial. But you can do it in the current version using predict with parameters ntree_start, ntree_end.

**Comment by annaveronika** [comment]
@zhenyiy Did predict function work for you? How about quality - did you get any profit from this approach?

**Comment by zhenyiy** [comment]
Hi @annaveronika , thank u very much. I can get the prediction from each estimator when I set ntree_start and ntree_end adjacent to each other now. However, I did not get any meaningful benefit from this approach. Since I only tested it on a few examples, it is still possible that it might have an effect on other problems.

**Comment by annaveronika** [comment]
Ok, that's great news, write to us if you have profit! Closing the issue then.
