### ISSUE TITLE
Problem in catboost.train: write failed

### ISSUE THREAD

**Issue by vikto9494** [catboost/catboost#58]
Sometimes during catboost.train I got following error:

_Error in catboost.train(pool, NULL, param, calc_importance = TRUE) : 
  (Cannot create a file when that file already exists.) sman/appdata/local/temp/rtmpcleqvg/devtools2120232836e1/catboost-catboost-03459cd/util/stream/output.cpp:271: write failed_

For instance, it happends for your example "Select hyperparameters" on [https://tech.yandex.com/catboost/doc/dg/concepts/r-usages-examples-docpage/](https://tech.yandex.com/catboost/doc/dg/concepts/r-usages-examples-docpage/) in code

_report <- train(x, as.factor(make.names(y)),
                method = catboost.caret,
                verbose = TRUE, preProc = NULL,
                tuneGrid = grid, trControl = fit_control)_

**Comment by nikitxskv** [comment]
@vikto9494 Hello!
Try to prevent creating output files. To do it you must assign `allow_writing_files` parameter the `FALSE` value. We added this parameter recently.
