### ISSUE TITLE
Google Colaboratory example

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#581]

**Comment by col14m** [comment]
Hi, Do I understand correctly that this task has already been completed (https://github.com/catboost/tutorials/blob/master/tools/google_colaboratory_cpu_vs_gpu_tutorial.ipynb), and help is no longer needed?

**Comment by annaveronika** [comment]
@col14m Do you have an intention to make a tutorial? If so we will be very happy - there can not be too few examples.

**Comment by col14m** [comment]
@annaveronika Yes, I would like to try making additional tutorials.

**Comment by annaveronika** [comment]
We have now tutorials for regression and classification here:
https://github.com/catboost/tutorials/tree/master/tools

Maybe we'll move it to some other folder at some point, but they will be in tutorials repo.
