### ISSUE TITLE
CatBoost blocks main thread of program when predict calls

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#586]
CatBoost blocks main thread, it is not good because GUI works in main thread. Using FeaturesData instead of Pandas df does not solve the issue. You can see the code to reproduce the issue in my repository https://github.com/khrisanfov/pyqt_catboost.

**Comment by kizill** [comment]
Fix already in master and in nightly build PyPi repository `catboost-dev`, so you can install and test today. Also we are planning to publish release with this fix in a short time.
