### ISSUE TITLE
CatboostError: Invalid loss_function='MSLE': for regressor use RMSE, MAE, Quantile, LogLinQuantile, Poisson, MAPE, Lq or custom objective object

### ISSUE THREAD

**Issue by chrishna1** [catboost/catboost#587]
Problem: Can't use Mean squared logarithmic error
catboost version: '0.11.2'
Operating System: Ubuntu 18.04.1 LTS
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz

Hi, MSLE is described in documentation but it throws error on using it. Do I need to update my version or something else?

**Comment by andrey-khropov** [comment]
> Hi, MSLE is described in documentation but it throws error on using it.

It is descibed in documentation (https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/#loss-functions__regression) that in can be used as a metric, but it can't be used as an optimization objective (that's what 'loss_function' parameter specifies).

**Comment by chrishna1** [comment]
Sorry didn't read carefully.
