### ISSUE TITLE
CatboostError: Incorrect CD file

### ISSUE THREAD

**Issue by Netherdrake** [catboost/catboost#591]
Running this code yields an error https://github.com/catboost/tutorials/blob/master/feature_selection/eval_tutorial.ipynb

```
CatboostError: Incorrect CD file. Invalid line number #10: catboost/libs/column_description/cd_parser.cpp:60: Invalid column index: index = 10, columnsCount = 10
```

catboost version: 0.11.2
Operating System: Ubuntu

**Comment by annaveronika** [comment]
Thank you very much for reporting it, we'll look into this!

**Comment by annaveronika** [comment]
The fix is on github now.

**Comment by glukhove** [comment]
@annaveronika, what was the issue? I also have simmilar error:
`CatboostError: Incorrect CD file. Invalid line number #1: catboost/libs/column_description/cd_parser.cpp:60: Invalid column index: index = 1, columnsCount =1`

There is a problem with cd file or data?

**Comment by annaveronika** [comment]
It looks like your dataset has only one column. Maybe your dataset has a separator other than '\t', please check it.
You can use cd file for any dataset, including a dataset without  categorical features. This might be useful if you have a column with GroupId, a column with DocId or for examle few columns with auxiliary data. Or if you have target or label in some of your columns.

**Comment by joy199** [comment]
Hi @annaveronika,
i have the same problem like @Netherdrake . I get the code from 
https://github.com/catboost/tutorials/blob/master/python_tutorial_with_tasks.ipynb. I don't know where can be my mistake, because I already copy and paste it after a while.

**Comment by annaveronika** [comment]
Sorry, the correct code for creating cd file is the following:
`from catboost.utils import create_cd
feature_names = dict(list(enumerate(train_df.keys()[1:])))
    
create_cd(
    label=0,
    cat_features=list(range(1, train_df.shape[1])),
    feature_names=feature_names,
    output_path=os.path.join(dataset_dir, 'train.cd')
)
`
We'll fix it in the tutorial soon.

**Comment by annaveronika** [comment]
done
