### ISSUE TITLE
Weird thread_count performance for inference in Python

### ISSUE THREAD

**Issue by Goorman** [catboost/catboost#592]
Problem: Inference in Python has weird performance issues when using with threading, reproduction is in this notebook:
https://github.com/Goorman/catboost_threading_perfomance

Catboost Version: 0.11.1
OS: Linux Ubuntu
CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz

**Comment by Goorman** [comment]
Update:
https://github.com/catboost/catboost/blob/b990c2279b18b9a9cf623273fcadcf013a44d4e4/catboost/libs/algo/apply.cpp#L42-L44

There is a heuristic that chooses minimum amount of objects it devotes to a single thread, formula ^^
But if you don't specify ntree_end and ntree_start parameters they default to 0, and min block size formula outputs 1 for datasets with object count < than 10000. This problem is easily fixed, both on c++ side (by fixing the formula) and as a hack-fix on python side (by specifying ntree_end to the real size).

**Comment by annaveronika** [comment]
Thanks a lot for pointing it out! We'll fix it soon.

**Comment by annaveronika** [comment]
This was fixed in 0.12
