### ISSUE TITLE
setting metric_period throws exception after first metric output

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#594]
The following fails 

```
from catboost import Pool, cv

params = {'iterations': 1000, 
          'depth': 3, 
          'loss_function': 'RMSE'}
scores = cv(train, params, early_stopping_rounds=100, metric_period=100)
```

with the message below. Not setting metric_period allows cv to run correctly

> 0:	learn: 56.2893495	test: 56.2903134	best: 56.2903134 (0)	total: 39.4ms	remaining: 39.4s
>
> CatboostError                             Traceback (most recent call last)
> <ipython-input-111-b448498879ce> in <module>
>       4           'depth': 3,
>       5           'loss_function': 'RMSE'}
> ----> 6 scores = cv(train, params, early_stopping_rounds=100, metric_period=100)
> 
> ~/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/catboost/core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
>    2898 
>    2899     with log_fixup(), plot_wrapper(plot, params):
> -> 2900         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified, as_pandas)
>    2901 
>    2902 
> 
> _catboost.pyx in _catboost._cv()
> 
> _catboost.pyx in _catboost._cv()
> 
> CatboostError: util/generic/hash.h:1652: Key not found in hashtable: RMSE
> 

catboost version: 0.11.2
Operating System: Ubuntu 18.04

**Comment by annaveronika** [comment]
Thanks a lot for reporting this issue! We'll fix it soon. For now if you just want to have less logging, you can use verbose=100.

**Comment by andrey-khropov** [comment]
This problem has been fixed in https://github.com/catboost/catboost/commit/a9b16d3b595b82c3ca1d03b226e1478aaa89c0ee and the fix will be in the next release.
