### ISSUE TITLE
hyperparameters grid at once

### ISSUE THREAD

**Issue by DBusAI** [catboost/catboost#598]
Problem: {It will be a good feature to have not only one parameter at once, but a grid of params, for better(faster) hyperparameter tuning or inplace blending}
catboost version: {any}
Operating System: {Ubuntu}
CPU: {+CPU}
GPU: {+GPU}

**Comment by annaveronika** [comment]
We've implemented grid_seach() method, which solves this problem:
https://catboost.ai/docs/concepts/python-reference_catboost_grid_search.html
