### ISSUE TITLE
Suggestion: Error message when ipywidgets is too old

### ISSUE THREAD

**Issue by FedorZaytsev** [catboost/catboost#599]
Problem: No error message is shown when ipywidgets is too old
catboost version: 0.12.0
Operating System: OSX

When ipywidgets version is too old and you are trying to display plot using plot=True flag nothing is showing. No error message or something like that. It would be nice if you will check ipywidgets version available using the following code and show some error message:
```
>>> import ipywidgets
>>> ipywidgets.__version__
'7.4.2'
```

Thanks

**Comment by annaveronika** [comment]
Thanks a lot for the suggestion! I'm not sure if ipywidgets can be too old though... we should work with all new versions. Vanya @newbfg, could you please take a look?

**Comment by FedorZaytsev** [comment]
My version was something around 6.x.x, while documentation states that you are working with 7.0+: https://tech.yandex.com/catboost/doc/dg/installation/python-installation-additional-data-visualization-packages-docpage/#python-installation-additional-data-visualization-packages

**Comment by annaveronika** [comment]
Sorry, I misread this, I was thinking widgets are too new :) Yes, they can be too old. We'll look to see how hard it is to add this warning.

**Comment by annaveronika** [comment]
We have not decided what to do with this. And we don't get issues about ipywigets. So I'm closing this as won't fix. Please, if you will have a problem with visualization, let us know, we'll try to help!
