### ISSUE TITLE
[python-package] Flag to ensure raw features data is not copied unnecessarily

### ISSUE THREAD

**Issue by andrey-khropov** [catboost/catboost#601]

**Comment by anuragreddygv323** [comment]
is this feature added ?

**Comment by annaveronika** [comment]
@anuragreddygv323 This feature is not added, and actually I think we are fine without this flag. We have improved our work with numpy and now there is much less copying of data, and you should not have struggles with it.

I'm closing the issue as won't fix, let us know if you will have problems with data loading speed!
