### ISSUE TITLE
Need to pass again cat_features in eval_metrics whereas it was already passed in CatBoostClassifier

### ISSUE THREAD

**Issue by ismael-elatifi** [catboost/catboost#603]
catboost version: 0.12.0
Operating System: Windows

The issue is described and demonstrated by the code below.

```Python
from catboost import CatBoostClassifier, Pool
    
col_cat = ['A','B']
target =  [ 1,  0]
model = CatBoostClassifier(num_trees=1, depth=1, cat_features=[0])
model.fit(col_cat, target)
model.eval_metrics(Pool(col_cat, label=target, cat_features=[0]), metrics=["Accuracy"])
```
If we don't pass cat_features to eval_metrics, we get error :

> Bad value for num_feature[0,0]="A": Cannot convert 'b'A'' to float

cat_features is already passed to the model constructor CatBoostClassifier so it should not be necessary to pass it again in eval_metrics call

**Comment by annaveronika** [comment]
You are right, this information should not be required. We'll change this behavoir. Thanks for this suggestion!

**Comment by annaveronika** [comment]
Actually it is a good idea for contribution. So I'm adding a help wanted and good first issue labels.

**Comment by eskayML** [comment]
I might be wrong, 

but I think in  current stable version of catboost (1.1.1), categorical features are automatically detected by the model,
there's even an `eval_metric` parameter now.

Would really love to contribute , I don't know if this issue is still valid

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @eskayML !
thank you for looking at this issue!

actually, this behavior is ok because it is unsafe to silently type-cast dataset columns to match the types expected by the model

it is better to change this example as follows

```python
from catboost import CatBoostClassifier, Pool
    
col_cat = ['A','B']
target =  [ 1,  0]
pool = Pool(col_cat, label=target, cat_features=[0])
model = CatBoostClassifier(num_trees=1, depth=1)
model.fit(pool)
model.eval_metrics(pool, metrics=["Accuracy"])
```
