### ISSUE TITLE
Catboost type error

### ISSUE THREAD

**Issue by shriavi** [catboost/catboost#605]
Problem: Getting type error in catboost training data
catboost version: Kaggle kernel
Operating System: Kaggle Kernel
CPU: {CPU}
# GPU: Not Enabled
Code:
x_train = x_train.astype(np.float32)
    x_test = x_test.astype(np.float32)
    y_train = y_train.astype(np.float32)
    y_test = y_test.astype(np.float32)

    train_pool = Pool(x_train, y_train, cat_features=[]) # cat_features=[0,2,5])
    test_pool = Pool(x_test)

    cb = CatBoostRegressor(iterations=400,
                             learning_rate=0.02,
                             depth=12,
                             eval_metric='RMSE')
    cb.fit(train_pool)
Error:
/opt/conda/lib/python3.6/site-packages/catboost/core.py in _init(self, data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    635         if feature_names is not None:
    636             self._check_feature_names(feature_names, features_count)
--> 637         self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    638 
    639 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

TypeError: unhashable type: 'numpy.ndarray'

I've converted everything to float32 and dimensions are also equal. All the columns are numerical as well. Please suggest.

Thanks.

**Comment by dbakshee** [comment]
Hi @shriavi 
You probably give labels (y_train, y_test) as 2d arrays, whereas they are expected to be 1d (a label per object)

**Comment by shriavi** [comment]
Hi,
Thanks for the reply. I'll recheck the shape of train and test data to confirm this and get back soon.

**Comment by shriavi** [comment]
Thanks. It was (n,1) array and converting to (n,) flat array helped.
