### ISSUE TITLE
Error : Cannot convert Categorical to numpy.ndarray

### ISSUE THREAD

**Issue by ismael-elatifi** [catboost/catboost#606]
catboost version: 0.12.0
Operating System: Windows

This issue was not present in version 0.11.2.

The code below using categorical type with a pandas.Series works fine :
```Python
from catboost import CatBoostClassifier
import pandas as pd
    
data = pd.Series(['A','B'], dtype='category')
target =  [ 1,  0]
model = CatBoostClassifier(num_trees=1, depth=1, cat_features=[0])
model.fit(data, target)
```
But if I just replace the Series by a DataFrame, i.e. by :
```Python
data = pd.DataFrame({'col':['A','B']}, dtype='category')
```
I get error :

> **TypeError: Cannot convert Categorical to numpy.ndarray** 

Using DataFrame inside Pool, it is working fine :
```Python
from catboost import CatBoostClassifier
    
data = pd.DataFrame({'col':['A','B']}, dtype='category')
target =  [ 1,  0]
pool = Pool(data.values, label=target, cat_features=[0])
model = CatBoostClassifier(num_trees=1, depth=1)
model.fit(pool)
```

**Comment by andrey-khropov** [comment]
Yes. It is a bug. Fixed in https://github.com/catboost/catboost/commit/50b3b7555e0d78bc703015120ad18e9a13b63e8e. Will be included in the next minor release.
Meanwhile you could also pass dataFrame.values instead of dataFrame directly as in your last example. It is less efficient because dataframe columns are copied into a new numpy ndarray with a common dtype, but it will work.

**Comment by annaveronika** [comment]
@ismael-elatifi And thanks a lot for this report!

**Comment by andrey-khropov** [comment]
fixed in https://github.com/catboost/catboost/releases/tag/v0.12.1

**Comment by ismael-elatifi** [comment]
Thanks for the fix. I tested with 0.12.1 and it is now working fine !

**Comment by andrey-khropov** [comment]
> Categorical data will still be copied right ?

Yes and no. Right now CatBoost treats categorical features this way - it converts input values of either strings or integers to utf-8 internal strings and then computes 32-bit hashes from these strings and stores hash_values together with back mapping of hash_value to utf-8 string.

Internal utf-8 strings data is discarded after hash computation.

So for each categorical feature in the dataset with N objects there will be additional memory used of the size 4*N bytes  + size of (hash map from uniq categorical values as utf-8 strings to 32 bit hashes).

Some additional memory will also be used during training to store quantized numerical feature values and sequentially recoded categorical feature values (1 byte per numerical value and 4 bytes per categorical value).

> Is there a way to pass numerical / categorical data without any copy ?

In three cases numerical features data won't be copied:

- You have only numerical features and they are passed to Pool constructor or fit methods of CatBoost* classes as a numpy.ndarray with an 'C' (columnar) data layout order and dtype=numpy.float32
- If you pass features as a [FeaturesData structure](https://tech.yandex.com/catboost/doc/dg/concepts/python-features-data__desc-docpage/) with num_feature_data as a numpy.ndarray with an 'C' (columnar) data layout order and dtype=numpy.float32
- If you pass features as pandas.DataFrame with numerical features columns having dtype=numpy.float32.
