### ISSUE TITLE
no errors for unknown arguments to catboostclassifier

### ISSUE THREAD

**Issue by jameslyons** [catboost/catboost#61]
If I call CatBoostClassifier(dfdscdsc=10) in python I get no indication that the argument is invalid. This is annoying e.g. if i misspell an argument it won't tell me, it just ignores it. It would be nice to get an error or some other indication that an unknown argument is present.

**Comment by Donskov7** [comment]
@jameslyons you're right. We'll add checking for arguments in one of the next versions.

**Comment by Donskov7** [comment]
MATRIXNET-845

**Comment by Donskov7** [comment]
It was fixed in last version, try to update CatBoost.
