### ISSUE TITLE
Catboost installation in R does not work

### ISSUE THREAD

**Issue by Quaterion** [catboost/catboost#612]
Problem: {Installation of Catboost in R is not successful even after considering the past solutions}
catboost version: {catboost 11.1, 12.1 ... does not matter}
Operating System: {windows 7 x64}
CPU: {CPU}

I considered all comments in issue [#538](https://github.com/catboost/catboost/issues/538). I use R version 3.4.3 and 3.5.2 in Windows 7. Rtools is installed. I can install other packages from github but not catboost. Any suggestions? 

Using the suggested solution ... 

    install.packages('devtools',dependencies = T)
    library(devtools)
    options(devtools.install.args = c("--no-multiarch", "--no-test-load"))
    devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.11.1/catboost-R-Windows-0.11.1.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))

... gives this not very informative output:  

    Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.11.1/catboost-R-Linux-0.11.1.tgz
    v  checking for file 'C:\Users\Quaterion\AppData\Local\Temp\RtmpOIGKis\remotes9843afc1c7d\catboost/DESCRIPTION' 
    -  preparing 'catboost': (1.3s)
    v  checking DESCRIPTION meta-information  
    -  checking for LF line-endings in source and make files and shell scripts
    -  checking for empty or unneeded directories
    -  building 'catboost_0.11.1.tar.gz'

    Installing package into ‘C:/Users/Quaterion/Documents/R/win-library/3.5’
    (as ‘lib’ is unspecified)
    * installing *source* package 'catboost' ...
    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
      converting help for package 'catboost'
        finding HTML links ... done
        catboost.caret                          html  
        catboost.drop_unused_features           html  
        catboost.get_feature_importance         html  
        catboost.get_model_params               html  
        catboost.get_object_importance          html  
        catboost.load_model                     html  
        catboost.load_pool                      html  
        catboost.predict                        html  
        catboost.save_model                     html  
        catboost.save_pool                      html  
        catboost.shrink                         html  
        catboost.staged_predict                 html  
        catboost.train                          html  
        dim.catboost.Pool                       html  
        dimnames.catboost.Pool                  html  
        head.catboost.Pool                      html  
        print.catboost.Pool                     html  
        tail.catboost.Pool                      html  
    ** building package indices
    ** testing if installed package can be loaded
    Error : package 'catboost' is not installed for 'arch = x64'
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing 'C:/Users/Quaterion/Documents/R/win-library/3.5/catboost'
    In R CMD INSTALL
    Error in i.p(...) : 
      (converted from warning) installation of package ‘C:/Users/Quaterion/AppData/Local/Temp/RtmpOIGKis/file9845b88501e/catboost_0.11.1.tar.gz’ had non-zero exit status

**Comment by david-waterworth** [comment]
Have you tried the latest version (12.1)

`devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.12.1/catboost-R-Windows-0.12.1.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
`

It worked for me

**Comment by david-waterworth** [comment]
12.1 worked for me, I did have to run the install command above from the 64 bit R console. When I tried to run it in Rstudio, I got the bomb icon.

**Comment by Quaterion** [comment]
Thank you. The installation worked after downloading the file and installing it from a local folder. It had nothing to do with version 12 or 11, however and I did not need to rename the file either: 


    options(devtools.install.args = c("--no-multiarch", "--no-test-load"))
    install.packages("C:/catboost-R-Windows-0.12.1.tgz", repos = NULL, type = "source", INSTALL_opts = c("--no-multiarch", "--no-test-load"))

**Comment by annaveronika** [comment]
@Quaterion I'm happy that you managed to install catboost! I'm sorry that you had problems with it. We'll discuss what we should update in the docs before closing this one. You are very welcome, if you have recommendations!

**Comment by SomyKamble** [comment]
even I am facing the same problem 
Installing package into ‘C:/Users/somy/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'catboost' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'catboost'
    finding HTML links ... done
    catboost.caret                          html  
    catboost.cv                             html  
    catboost.drop_unused_features           html  
    catboost.get_feature_importance         html  
    catboost.get_model_params               html  
    catboost.get_object_importance          html  
    catboost.load_model                     html  
    catboost.load_pool                      html  
    catboost.predict                        html  
    catboost.save_model                     html  
    catboost.save_pool                      html  
    catboost.shrink                         html  
    catboost.staged_predict                 html  
    catboost.train                          html  
    dim.catboost.Pool                       html  
    dimnames.catboost.Pool                  html  
    head.catboost.Pool                      html  
    print.catboost.Pool                     html  
    tail.catboost.Pool                      html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error : package 'catboost' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/somy/Documents/R/win-library/3.6/catboost'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘C:/Users/somy/AppData/Local/Temp/RtmpKSzxRl/file2148401b454c/catboost_0.16.5.tar.gz’ had non-zero exit status

**Comment by kizill** [comment]
Closing as inactive and possibly irreproducible. Please, open new issue for R installation problem to start new investigations, if any problem occur.

**Comment by jui9734** [comment]
@Quaterion after so many attempts, this code is really a lifesaver
