### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by elch10** [catboost/catboost#616]
After trying to import catboost
```python
import catboost
```
I get error: 
```
[1]    11525 illegal hardware instruction (core dumped)  python3
```
python version: `Python 3.6.7`
catboost version: `0.12.1.1`
Operating System: `Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
CPU:  
```
Dual core AMD Athlon II P360 (-MCP-) cache: 1024 KB
clock speeds: max: 2300 MHz 1: 2300 MHz 2: 2300 MHz
```
GPU not used
UPD: catboost installed via pip - `pip3 install catboost`

**Comment by kizill** [comment]
Hello!
Could you provide a crashdump to help us find what's happened?

**Comment by elch10** [comment]
@kizill Of course. You can download it from [here](https://drive.google.com/open?id=1v9qebVC0LndH2eZmk0Ek8ZlJABuY2gk5)

**Comment by kizill** [comment]
Your CPU don't support SSSE3 instructions, so try building `_catboost.so` from master  https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-from-source-linux-macos-docpage/ with `-mno-ssse3` flag:
```
ya make ........  -DCFLAGS="-mno-ssse3"
```
or if you want to build wheel package as in https://tech.yandex.com/catboost/doc/dg/installation/python-installation-method-build-a-wheel-package-docpage/, just add ` -DCFLAGS="-mno-ssse3"` option to command line.

**Comment by kizill** [comment]
Hi and sorry for delay! I think for now the simpliest way to build catboost for your processor is to use makefiles with completely droped -mssse3 flags:
```
sed -i -e 's/\-mssse3//' make/*.makefile
make -f make/python3.CLANG50-LINUX-X86_64.makefile -j
```

**Comment by elch10** [comment]
@kizill Now something wrong with makefile...
```bash
$ sed -i -e 's/\-mssse3//' make/*.makefile
$ make -f make/python3.CLANG50-LINUX-X86_64.makefile -j
_CC_VERSION = '__clang_major__ __clang_minor__'
make/python3.CLANG50-LINUX-X86_64.makefile:16: *** clang 5.0 is required.  Stop.
```
But I have installed clang:
```
$ dpkg -l | grep clang                  
ii  clang-5.0                                     1:5.0.1-4                           amd64        C, C++ and Objective-C compiler
ii  libclang-common-5.0-dev                       1:5.0.1-4                           amd64        clang library - Common development package
ii  libclang1-5.0:amd64                           1:5.0.1-4                           amd64        C interface to the clang library
ii  python-clang-5.0                              1:5.0.1-4                           amd64        Clang Python Bindings
```
May be I need to `export` some varriables?

**Comment by kizill** [comment]
Yes, you should do
```bash
export CC=clang-5.0
export CXX=clang++-5.0```

**Comment by elch10** [comment]
@kizill Thank you, I built it from source and now it works fine!
