### ISSUE TITLE
Free all GPU memory after fit

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#619]
After fitting a model with task_type='GPU', the python process continues to hold about 200MiB of GPU memory as reported by nvidia-smi, i.e the first process in the list below. I'm using juypter so this means each time I start a kernel and train a model my total available GPU memory is reduced until I manually clean up by shutting down kernels (or I guess I could delete the CatBoostRegressor objects) or eventualyl a fit will fail. It would be preferable if after fitting, all GPU memory is free'd

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
> | 42%   38C    P8    17W / 260W |   2023MiB / 10986MiB |      3%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0       635      C   ...ons/3.7.1/envs/jupyter-3.7.1/bin/python   215MiB |
> |    0      1261      G   /usr/lib/xorg/Xorg                            40MiB |
> |    0      1310      G   /usr/bin/gnome-shell                         122MiB |
> |    0      2959      G   /usr/lib/xorg/Xorg                           545MiB |
> |    0      3158      G   /usr/bin/gnome-shell                         385MiB |
> |    0      3618      G   ...quest-channel-token=6154509017737376030   515MiB |
> |    0      4270      G   ...-token=C928B9A942AED155F718E54497D30E3D   193MiB |
> +-----------------------------------------------------------------------------+
>

**Comment by Noxoomo** [comment]
Hi!

This memory is reserved not by CatBoost, but by NVIDIA CUDA runtime (for each unique process that uses GPU NVIDIA allocates some memory). 
 
It's not good idea to free this memory automatically (context creation is not cheap task) after training.
But we'll give explicit function to deallocate all GPU memory manually

**Comment by david-waterworth** [comment]
Also not sure if it's related but after many GPU fits, eventually calling fit() results in a hang (I have 'verbose' logging set, nothing is logged). Restarting the juptyer lab kernel doesn't help, I have to reboot my PC. I appreciate this isn't much info but not sure what more I can provide?

**Comment by Noxoomo** [comment]
> Also not sure if it's related but after many GPU fits, eventually calling fit() results in a hang (I have 'verbose' logging set, nothing is logged). Restarting the juptyer lab kernel doesn't help, I have to reboot my PC. I appreciate this isn't much info but not sure what more I can provide?

Hi!
sorry for delay

This problem is not related
Could you please specify you OS/NVIDIA driver/PC specs?
And if it's linux, could you attach nvidia-smi output and dmesg output right after hang?

**Comment by andrey-khropov** [comment]
Fixed in aef5013e863bab2add06873decbfce9c4b3dab21. Has been released in v1.0.5
