### ISSUE TITLE
CV enhancements (python)

### ISSUE THREAD

**Issue by BrianMiner** [catboost/catboost#62]
Is there any documentation on what enable_early_stopping and eval_period does? The resulting behavior is what what I expected.

Also, a great enhancement for cv would be to return the predictions (out of fold) for the best number of iterations

**Comment by annaveronika** [comment]
We have added description of these parameters to documentation:
https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_cv-docpage/

Best iteration is written to log if you use verbose mode (verbose=True).

You can also calculate best iteration from metric values from the return value.

**Comment by BrianMiner** [comment]
Thank you. So I assume from this that:
1) The algorithm runs for the full number of iterations - there is no early stopping to training, simply a capture of the best # of iterations

2) eval_period means how often is the metric of eval examined to see if a better result is found

Am I correct?

**Comment by annaveronika** [comment]
We changed cross-validation overfitting detection parameters to be same as those in training. Now it should be more clear.

**Comment by unnir** [comment]
Any updates regarding how to use "early stopping" feature with CV?

**Comment by annaveronika** [comment]
The cv early stopping parameters are the same as ones in train. In documentation they are in block "training parameters"

**Comment by unnir** [comment]
@annaveronika sorry, but I could not find any parameter related to "early stopping". Could you please share a code how to do CV with early stopping using CatBoost. Something like this:


```python
cv_data = cv(cat_params, cat_train, nfold=3, num_boost_round=4000, partition_random_seed=23, verbose_eval=10, )
```

**Comment by annaveronika** [comment]
We have not added it to the online documentation, we'll add it soon. Thanks for pointing this out! You can look up the list of parameters of cv in docstring of cv for now. You need parameter num_boost_round or early_stopping_rounds, they are synonyms.

**Comment by annaveronika** [comment]
One other option, which we already have in online docs is setting it in parameters map that you pass to the cv function.

**Comment by annaveronika** [comment]
@unnir Yes, I think it's not on pypi jet, sorry for desinformation.
You should pass overfitting detector in params map the same way as it is passed to fit function.
Name of parameters can be found here: https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_parameters-list-docpage/

**Comment by ralanburnett** [comment]
I'm getting an error when running CatboostOptimizer in the Catboost Playground code at https://gist.github.com/talperetz/6030f4e9997c249b09409dcf00e78f91
class CatboostOptimizer(ModelOptimizer):
    def evaluate_model(self):
        validation_scores = catboost.cv(
        catboost.Pool(self.X_train, 
                      self.y_train, 
                      cat_features=self.categorical_columns_indices),
        self.model.get_params(), 
        nfold=self.n_fold,
        stratified=self.is_stratified,
        seed=self.seed,
        early_stopping_rounds=self.early_stopping_rounds,
        shuffle=self.is_shuffle,
        metrics='auc',
        plot=False)
        self.scores = validation_scores
        test_scores = validation_scores.iloc[:, 2]
        best_metric = test_scores.max()
        return 1 - best_metric
The error is from metrics='auc'.  If I remove this the code runs, but the results are awful.  Since metrics is not in the cv parameter list, how do you pass a value for metrics in.  In particular, the error occurs when evaluate_model is run:
default_cb = catboost.CatBoostClassifier(loss_function='Logloss', eval_metric='AUC', silent=True)
default_cb_optimizer = CatboostOptimizer(default_cb, X_train, y_train)
default_cb_optimizer.evaluate_model()
