### ISSUE TITLE
Predicting Probabilities with MultiClass Classifier

### ISSUE THREAD

**Issue by escuccim** [catboost/catboost#625]
catboost version: latest

I am using CatBoostClassifier with objective 'MultiClass' and classes_count = 5. When I predict the class the output works as expected, but when I do predict_proba it outputs only two probabilities per item instead of the expected 5.

`foo = model.predict_proba(test)
print(foo.shape)
[3289, 2]
`

I am not sure if this is an issue or if I am doing something wrong.

**Comment by annaveronika** [comment]
This sounds weird, we'll check this. Thanks for the issue!

**Comment by escuccim** [comment]
This seems strange but when I use loss_function="MultiClass" it works properly.

When I use objective="MultiClass" it only outputs two probabilities.

**Comment by annaveronika** [comment]
This is a bug in handling synonyms, thank you very much for reporting this! Will be fixed soon.

**Comment by annaveronika** [comment]
This but is fixed already.

**Comment by annaveronika** [comment]
This should be fixed starting from 0.13.
We just published 0.14.0, please try upgrading and let us know if the problem still exists.

**Comment by PhilipMachineLearning** [comment]
What about the order of the class labels for predict_proba

Spurious example: Consider we are doing an economic prediction with a column labelled 'Country' with the following unique values: ['Germany', 'France', 'Spain', 'Sweden']

predict_proba returns the following but does not tell you what the columns of the returned array return: 

array([[0.51163663, 0.12707082, 0.33764476, 0.0236478 ],
       [0.5060725 , 0.13009993, 0.2945307 , 0.06929688],
       [0.52897682, 0.11629713, 0.33798389, 0.01674217],
       ...,
       [0.53548177, 0.08361807, 0.36218414, 0.01871603],
       [0.47610545, 0.11881453, 0.35728305, 0.04779698],
       [0.47913336, 0.1276168 , 0.33808458, 0.05516526]])

The columns do not seem to be consistent with a different model trained.

**Comment by PhilipMachineLearning** [comment]
> This should be fixed starting from 0.13.
> We just published 0.14.0, please try upgrading and let us know if the problem still exists.

What about the order of the class labels for predict_proba

Spurious example: Consider we are doing an economic prediction with a column labelled 'Country' with the following unique values: ['Germany', 'France', 'Spain', 'Sweden']

predict_proba returns the following but does not tell you what the columns of the returned array return:

array([[0.51163663, 0.12707082, 0.33764476, 0.0236478 ],
[0.5060725 , 0.13009993, 0.2945307 , 0.06929688],
[0.52897682, 0.11629713, 0.33798389, 0.01674217],
...,
[0.53548177, 0.08361807, 0.36218414, 0.01871603],
[0.47610545, 0.11881453, 0.35728305, 0.04779698],
[0.47913336, 0.1276168 , 0.33808458, 0.05516526]])

The columns do not seem to be consistent with a different model trained.

**Comment by annaveronika** [comment]
You can look into classes_ field to understand the order.
