### ISSUE TITLE
Catboost Error

### ISSUE THREAD

**Issue by hsmith876** [catboost/catboost#626]
Problem: CatboostError: Invalid cat_features[6] = 100 value: must be < 100.

Not sure why I am getting this error and how to fix. Any insights?

**Comment by annaveronika** [comment]
this error means that your dataset contains 100 features with indices from 0 to 99. You are trying to declare a categorical feature with index 100 which is greater than max index.

**Comment by hsmith876** [comment]
Hi Anna, Thanks for your reply. I already fix the problem and you are correct about the issue. Great work!

**Comment by annaveronika** [comment]
Great! Closing the issue then.

**Comment by ogidaniel** [comment]
how was it fixed? please
