### ISSUE TITLE
Cardinality of categorical feature greater than 255

### ISSUE THREAD

**Issue by rushabhy** [catboost/catboost#628]
Problem: How to deal with a categorical feature with cardinality higher than 255.
catboost version: 0.11.1
Operating System: Ubuntu 18.04
CPU: 8
#GPU: 0

**Comment by annaveronika** [comment]
Everything should work out of the box - we calculate frequencies and traget based statistics for these features.
One thing though - you cannot use one-hot encoding for this categorical features now. But we are currently working on that, so this also will be possible.

**Comment by annaveronika** [comment]
@rushabhy Does this help? Do you need any further info?

**Comment by rushabhy** [comment]
@annaveronika Yes, thank you 👍

**Comment by hadaev8** [comment]
Any progress?

**Comment by annaveronika** [comment]
If you are asking about one-hot encoding, then yes, you can use larger values for it on CPU. I'm not sure you want it though, since default categorical feature handling works usually better for high cardinality categorical features.

**Comment by rushabhy** [comment]
When will be able to use it on GPU?

**Comment by annaveronika** [comment]
It's not implemented yet. No time estimate for it now, https://github.com/catboost/catboost/issues/875 - here's an issue for that.

**Comment by annaveronika** [comment]
@rushabhy But why do you want to use one-hot encoding? Why does the default categorical features handling not fit for you?
