### ISSUE TITLE
GPU training hang

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#629]
As reported in the comments of https://github.com/catboost/catboost/issues/619#issuecomment-456803537 I'm seeing a hang when GPU training after running a large number of fits.

I'm using Ubuntu 18.04 x64, 1x Nvidia 2080Ti, Intel i7-8700K CPU and 32GB RAM.

Pattern so far is I train each model overnight by launching from the console (they're ipynb notebooks run from a script using the jupyter api, launched from the vscode console). Then in the morning I find often when I try and do a fit interactively in jupyter lab the fit() method hangs. In verbose mode nothing at all is logged so it seems to be hung setting up the GPU. 

Next time it occurs I'll provide more details.

**Comment by Noxoomo** [comment]
could you please specify driver version (hangs could be caused by old driver versions, especially on new GPUs like 2080), and you data size

**Comment by Noxoomo** [comment]
and what loss did you use?

**Comment by david-waterworth** [comment]
I'm using 410.79 and RMSE loss

**Comment by david-waterworth** [comment]
The issue occurs when there's a fit job running in the background (via a python script) and I accidentally call fit from a jupyter notebook. Presumably PID 29272 is blocking PID 24164

Wed Jan 30 12:50:13 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 40%   46C    P2   114W / 260W |  10554MiB / 10986MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1396      G   /usr/lib/xorg/Xorg                            40MiB |
|    0      1441      G   /usr/bin/gnome-shell                          58MiB |
|    0      2049      G   /usr/lib/xorg/Xorg                           516MiB |
|    0      2370      G   /usr/bin/gnome-shell                         242MiB |
|    0      5166      G   ...-token=XXX   216MiB |
|    0     24164      G   ...uest-channel-token=XXX  1043MiB |
|    0     29272      C   ...pyenv/versions/jupyter-3.7.1/bin/python  8431MiB |
+-----------------------------------------------------------------------------+

**Comment by david-waterworth** [comment]
And when the blocking process stops, the blocked process remains blocked

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 40%   39C    P8    10W / 260W |   1750MiB / 10986MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1396      G   /usr/lib/xorg/Xorg                            40MiB |
|    0      1441      G   /usr/bin/gnome-shell                          58MiB |
|    0      2049      G   /usr/lib/xorg/Xorg                           402MiB |
|    0      2370      G   /usr/bin/gnome-shell                         199MiB |
|    0     24164      G   ...uest-channel-token=XXX  1047MiB |
+-----------------------------------------------------------------------------+

**Comment by kizill** [comment]
Hi @david-waterworth , do you still encounter deadlocks?

**Comment by david-waterworth** [comment]
I've not encountered it for some time

**Comment by kizill** [comment]
I guess that was some cuda driver issue, please reopen if you'll find a way to make it reproduceable :)
