### ISSUE TITLE
Publish compiled R packages

### ISSUE THREAD

**Issue by yn2191** [catboost/catboost#63]
Could you please help me to figure out what I should do in order to download catboost? 
I have Windows at work (so I don't have the right of administrator of this computer), R is 3.3.2. version. 
I downloaded Visual C++ 2015, but still I got an error: 
install.packages('devtools')
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Installation failed: Timeout was reached

and I tried 
packageurl <- "https://github.com/catboost/catboost.git"
install.packages(packageurl, repos=NULL, type="source")
installation of package had non-zero exit status

**Comment by Sinxxx** [comment]
Так и не получилось скомпилировать для R. Парни с яндекса!
За разработку респект, но надо как то решить с компилом.
LightGBM худо бедно компильнул, а тут не получается. Решите
пожалуйста проблему. VS 2015 заменмте на что нибудь попроще.
Ребят, у кого получилось компильнуть - выложите пожалуйста
папку с пакетом из R! Под 3.4.0 или 3.4.1 версии. Спасибо.

**Comment by exprmntr** [comment]
Hello, @yn2191,

"Installation failed: Timeout was reached" looks like network problem, probably firewall or proxy settings don't allow you make connection to github.

**Comment by exprmntr** [comment]
Hello @Sinxxx, 

Thank your for feedback. We will consider the possibility to publish compiled R packages.

**Comment by annaveronika** [comment]
@yn2191 @Sinxxx Have you managed to install the package?

**Comment by yn2191** [comment]
@annaveronika No, I still can't download.

**Comment by annaveronika** [comment]
MATRIXNET-936

**Comment by Sinxxx** [comment]
@annaveronika No. To compile and failed. Put and 15, and vs 17, for new instructions. I understand you laid out here compiled ? But I unfortunately did not download. Anna, if not difficult to compile for versions R3.4.0 and(or) R3.4.1, post here.
Нет. Скомпилировать так и не удалось. Ставил и 15 и 17 vs, по новой инструкции. Как я понял вы здесь выкладывали скомпилированный ? Но я к сожалению не успел скачать. Аннушка, если не сложно скомпилируйте для версий R3.4.0 и(или) R3.4.1, и выложите здесь.

**Comment by Rlfdinky** [comment]
I have alos a problem to install the Catboost package in R : I have this message : 
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installation failed: Does not appear to be an R package (no DESCRIPTION)

**Comment by annaveronika** [comment]
As some people have problems with R package installation, we decided to publish compiled versions of the package. The progress will be reported in this issue. For now I could only suggest to try again or to use python or command line utility... Sorry for inconvenience.

**Comment by ved93** [comment]
Could you pls tell me about any update on compiled catboost R package?

**Comment by annaveronika** [comment]
@ved93 We are working on that.

**Comment by MrOoijer** [comment]
Anna, can we get some progress on this issue? I succesfully installed (windows 10) a similar R package (lightGBM) that could find the C++ compiler from Visual Studio 2017 and all the other tools needed but here it fails to find them. As Visual Studio 2015 is no longer avalibale and I do want CUDA support, help would be appreciated.

**Comment by sab** [comment]
Hi everyone!

R-package pre-build binaries are available now with every [release](https://github.com/catboost/catboost/releases) (from 0.6)

Install R-package with the following command

>  devtools::install_url("BINARY_URL")

where 'BINARY_URL' is a path to the pre-build binary file. For instance, https://github.com/catboost/catboost/releases/download/v0.6.1/catboost-R-windows-0.6.1.tgz
Please take notice that path contains exact build number (0.6.1) and platform (windows).
You could find required for your needs binary on the CatBoost [release page](https://github.com/catboost/catboost/releases/).

Let us know if any problem with this process.

**Comment by sab** [comment]
On windows you might also need INSTALL_opts = c("--no-multiarch")) or args = c("--no-multiarch")) if you have both 32 and 64 bit R installation.

**Comment by exterminatorgg** [comment]
I have this problem, how can i solve?

> devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz'
+                       ,INSTALL_opts = c("--no-multiarch"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.10.0/catboost-R-Windows-0.10.0.tgz
Installing catboost
"C:/PROGRA~1/R/R-3.5.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "C:/Users/Diego  \
  Risco/AppData/Local/Temp/RtmpCqC1hT/devtools55423d71060/catboost"  \
  --library="C:/Users/Diego Risco/Documents/R/win-library/3.5"  \
  --install-tests 

* installing *source* package 'catboost' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'catboost'
    finding HTML links ... done
    catboost.caret                          html  
    catboost.get_feature_importance         html  
    catboost.get_model_params               html  
    catboost.get_object_importance          html  
    catboost.load_model                     html  
    catboost.load_pool                      html  
    catboost.predict                        html  
    catboost.save_model                     html  
    catboost.save_pool                      html  
    catboost.shrink                         html  
    catboost.staged_predict                 html  
    catboost.train                          html  
    dim.catboost.Pool                       html  
    dimnames.catboost.Pool                  html  
    head.catboost.Pool                      html  
    print.catboost.Pool                     html  
    tail.catboost.Pool                      html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error fatal: no fue posible abrir el archivo 'C:\Users\Diego': No such file or directory

*** arch - x64
Error fatal: no fue posible abrir el archivo 'C:\Users\Diego': No such file or directory

ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Diego Risco/Documents/R/win-library/3.5/catboost'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by kizill** [comment]
Hello, @exterminatorgg ! I think that problem is that R language has poor support of spaces in paths on Windows ( for example see: https://github.com/r-lib/devtools/issues/1787 ) As a hotfix for you R installation i can only recommend you to create special user account without spaces in it's username.
