### ISSUE TITLE
CatBoost feature importance values

### ISSUE THREAD

**Issue by ushmalramesh** [catboost/catboost#632]
Problem: Catboost feature importance values vary between runs of the Catboost classifier on the same machine and also between different machines for the same data and code. I wanted to know what parameter causes the randomness in the returned feature importance values. The relative ordering of features also changes between runs but not for the top features. Setting of the random seed does not seem to make these values constant. I also tried setting random_strength to 0.

catboost version: {0.12.2}
Operating System: {Linux Mint based on Ubuntu 18.04}
CPU: {Intel Core i7 7th Gen}

**Comment by annaveronika** [comment]
Different runs of CatBoostClassifier on the same data with a fixed random_seed give exactly the same model and must give exactly the same feature importances. Please provide the code that you are running and the stdout that shows that results are different.

**Comment by ushmalramesh** [comment]
Hello,

Thank you for the swift response! I looked through my code and it turns out there were some inconsistencies in my test code causing the discrepancy. My apologies for the confusion. Please close this issue.
