### ISSUE TITLE
Not clear error msg

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#633]
Same issue
What should i fix if:
I trained catboost and defined cat features as this:
clf.fit(train, labels, cat_dims)
And when i look at indexes of cat and float features in the trained model they are the same as in cat_dims variable before.
I got this error when i load test set and try to make class prediction:
_catboost.CatboostError: Bad value for num_feature[0,3]="1.281.501.0": Cannot convert 'b'1.281.501.0'' to float

My cat indexes in trained model:
[0, 1, 2, 9, 10, 11, 12, 13, 15, 16, 19, 21, 24, 28, 29, 31, 32, 34, 35, 36, 38, 39]
So, Bad value for num_feature[0,3] error - means, that my third feature was float (and it is true; it is not presented in the cat indexes list above), and it was OK while training, and now, when i try to predict on test sample it suddenly became unable to convert it to float, because third feature in test sample is now categorical (according to the value "1.281.501.0")? And how to know the name of this feature? The "third" feature does not make any sense to me. What should i do to load test samples and make a prediction successfully?

PS.: i open test sample in pandas with the same data types as train. And the number of features is the same

The error Bad value for num_feature[0,3]="1.281.501.0" looks weird, there should be a single index.

**Comment by goshulina** [comment]
I found this value in the dataframe. It have type of <class 'pandas.core.dtypes.dtypes.CategoricalDtype'>
And it is really third in Series of train.dtypes.
So why it tries to convert it to float.
And here comes the deal though!
Doing this stuff:
`dataset = Pool(
        data=FeaturesData(
            num_feature_data=np.array(X[X.columns[float_indexes]].values,
                                      dtype=np.float32),
            cat_feature_data=np.array(X[X.columns[cat_indexes]].values,
                                      dtype=object)
        ),
        label=y
    )`
X.columns[float_indexes] - is the evil. Because X.columns contains index column. And float_indexes and cat_indexes does not. The first value of cat_indexes or float_indexes does not imply that the very first value is index column.

So, i should do it like this:
`dataset = Pool(
        data=FeaturesData(
            num_feature_data=np.array(X[X.columns[1:][float_indexes]].values,
                                      dtype=np.float32),
            cat_feature_data=np.array(X[X.columns[1:][cat_indexes]].values,
                                      dtype=object)
        ),
        label=y
    )`

Now i feel myself stupid for creating this issue :|
It can be closed

**Comment by annaveronika** [comment]
No, you don't have to use Features data, sorry for bad doc example, we'll add better ones soon.

You can write
from catboost import CatBoostClassifier, Pool

train_data = Pool(
    data=[[1, 4, 5, 6], 
          [4, 5, 6, 7], 
          [30, 40, 50, 60]],
    label=[1, 1, -1],
    weight=[0.1, 0.2, 0.3]
)

model = CatBoostClassifier(iterations = 10)

model.fit(train_data)
preds_class = model.predict(train_data)

if you don't have categorical features.
And if you have categorical features, then you can just use DataFrame as input data
