### ISSUE TITLE
Error issued while running custom loss with custom metric functions

### ISSUE THREAD

**Issue by omer-shaked** [catboost/catboost#634]
Problem: error occurs during training when using both custom loss and custom metric
catboost version: 0.12.2
Operating System: Ubuntu
CPU

When trying to initiate training using both custom loss function and custom metric functions (which were both tested and are working well when run independently), the following error is issued:
**catboost.CatboostError: catboost/libs/data_new/target.cpp:1232: Internal CatBoost Error (contact developers for assistance): no Target data in targetDataProviders**

Full error trace within the package:
File "/home/omers/.local/lib/python3.6/site-packages/catboost/core.py", line 2183, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
  File "/home/omers/.local/lib/python3.6/site-packages/catboost/core.py", line 1126, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool)
  File "/home/omers/.local/lib/python3.6/site-packages/catboost/core.py", line 828, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool)
  File "_catboost.pyx", line 2296, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2316, in _catboost._CatBoost._train
_catboost.CatboostError: catboost/libs/data_new/target.cpp:1232: Internal CatBoost Error (contact developers for assistance): no Target data in targetDataProviders

**Comment by annaveronika** [comment]
We had a major refactoring after this version, looks like we missed this case, we'll fix it. Thanks a lot for the report!

**Comment by zachanton** [comment]
Any news about this bug?

**Comment by annaveronika** [comment]
Very sorry for the delay! We'll update the status tomorrow.

**Comment by andrey-khropov** [comment]
This bug is fixed in https://github.com/catboost/catboost/commit/e77abb5b23f1126dac7e7d1883c7d9b4ffa73c47. It will be included in the next release.
