### ISSUE TITLE
Why can't CatBoost use floating-point numbers or nan values for categorical features?

### ISSUE THREAD

**Issue by devforfu** [catboost/catboost#635]
I am using a `catboost` classifier as follows:
```python
catboost = cb.CatBoostClassifier(iterations=10, cat_features=cat_features)
catboost.fit(X_train, y_train, eval_set=(X_valid, y_valid))
```
In each case, the data is stored as a numpy array of `np.float32` type. The model is trained absolutely fine, without any issues. Next, I am trying to run the prediction on the test set, like this:
```python
probs = catboost.predict_proba(X_test)
```
However, I am getting the following error that says I can't feed `np.float32` array that represents categorical data:
```text
CatboostError: 'data' is numpy array of np.float32, it means no categorical features, but 'cat_features' parameter specifies nonzero number of categorical features
```
I wonder, why it is the case? Because I provide the explicit indices of categorical columns in `cat_features` list, and the training process doesn't complain about having data in floating points format.

Could you please explain, why do we have such a limitation? I am not sure why the booster can't figure out which columns are categorical ones because it already has the list I've provided during the training phase. Should I convert the test set into a data frame of appropriate types before running predictions?

For example, the `lightgbm` booster workes without any issues when I am using the following snippet (using the very same arrays of data):
```python
gbm = lgb.LGBMClassifier(n_estimators=1000, verbose=0)
gbm.fit(X_train, y_train, eval_set=(X_valid, y_valid))
preds = gbm.predict_proba(X_test)
```
Probably I just don't understand something?

**Comment by david-waterworth** [comment]
I believe you should be passing `cat_features` to the fit method, not to the constructor. i.e. 

```
catboost = cb.CatBoostClassifier(iterations=10)
catboost.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_valid, y_valid))
```

**Comment by devforfu** [comment]
@david-waterworth Unfortunately, I am still getting the same error even when `cat_features` parameter is set in the `fit` method. 

[This fragment](https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/core.py#L281-L285) makes me suspicious:
```python
elif isinstance(data, np.ndarray):
    if (data.dtype == np.float32) and (cat_features is not None) and (len(cat_features) > 0):
        raise CatboostError(
            "'data' is numpy array of np.float32, it means no categorical features,"
            " but 'cat_features' parameter specifies nonzero number of categorical features"
        )
```
In case if your data is a NumPy array of `np.float32` type, _and_ you have provided non-empty `cat_features`, this fragment should raise an exception, right? I guess this thing happens when the library converts Numpy arrays into `Pool` object to represent the data.

I believe it could also check the type of elements in `cat_features`, and in case if they are integers, everything is fine and it can figure out which columns to use as categorical ones, and raise that exception in case if values are strings, i.e., names of `pandas.DataFrame` columns.

**Comment by devforfu** [comment]
Ok, here is a simple solution to get rid of this exception:
```python
probs = catboost.predict_proba(pd.DataFrame(X_test))
```
If you wrap your matrix into `pd.DataFrame`, it works fine.

**Comment by david-waterworth** [comment]
Yes it appears there's an assumption that X is an float array your data is categorical. A warning rather than an error seems more appropriate though.

I've never seen this error, and have always used panda's data frames so your workaround makes sense.

**Comment by devforfu** [comment]
Ok, makes sense. Though I would say that my case was more about the user API than the details of implementation. Like, from my point of view, it looks a bit weird that the algorithm is OK with having NumPy arrays during training and raising the error when getting an `X_test` array in the same format.

**Comment by annaveronika** [comment]
If your train data has float categorical features, an exception will be raised also. It's not about train or test, it will be the same for any of them.

**Comment by devforfu** [comment]
I guess that we talking about a bit different things. Essentially, the question boils down to the following difference:
```python
# everything is a NumPy array
catboost = cb.CatBoostClassifier(iterations=10, cat_features=cat_features)
catboost.fit(X_train, y_train, eval_set=(X_valid, y_valid))
preds = catboost.predict_proba(X_test)  # CatBoostError: 'data' is numpy array of np.float32 [...]

# wrapping with Data Frame, and everything works fine
catboost = cb.CatBoostClassifier(iterations=10, cat_features=cat_features)
catboost.fit(X_train, y_train, eval_set=(X_valid, y_valid))
preds = catboost.predict_proba(pd.DataFrame(X_test))  # No errors here
```
So I just was surprised a bit that one data type (numpy array) raises an exception, and the very same array wrapped into another container (pandas dataframe) gives different results. That's it :)

**Comment by annaveronika** [comment]
We've added the info to FAQ https://catboost.ai/docs/concepts/faq.html#specify-weights-or-baseline-for-eval-set

**Comment by Nitinsiwach** [comment]
This is a big problem if you are trying to be economical with your memory usage. Since you have to convert the data to pandas that consumes a lot of memory. Maybe adding support for polars is in order
