### ISSUE TITLE
Documentation typo in Dataset description

### ISSUE THREAD

**Issue by xhu4** [catboost/catboost#636]
Problem: typo in [page about dataset description](https://tech.yandex.com/catboost/doc/dg/concepts/input-data_values-file-docpage/#input-data_values-file).

Original text:

> The feature indexed 3 is categorical, so the value in the __second__ column is set to “Categ”. The name of this feature is set to “wind direction” in the third column of the description file.

I think maybe you meant 4th instead of 2nd.

**Comment by annaveronika** [comment]
Thanks a lot for the report, we'll check this!

**Comment by Nikulinnn** [comment]
> Problem: typo in [page about dataset description](https://tech.yandex.com/catboost/doc/dg/concepts/input-data_values-file-docpage/#input-data_values-file).
> 
> Original text:
> 
> > The feature indexed 3 is categorical, so the value in the **second** column is set to “Categ”. The name of this feature is set to “wind direction” in the third column of the description file.
> 
> I think maybe you meant 4th instead of 2nd.

Thank you for the feedback.
This block of text refers to the structure of the corresponding column descriptions file, which contains three columns at the most. The data type is always specified in the second column of this file.
We have clarified this in our recent update. Please, check out whether the description is more clear now or not.

**Comment by annaveronika** [comment]
Ok, I think it's fixed now, closing the issue. If you see any other problems - let us know!
