### ISSUE TITLE
Feature volatility_dcl is present in model but not in pool.

### ISSUE THREAD

**Issue by gkourogiorgas** [catboost/catboost#637]
Problem: I get this error:
CatboostError: catboost/libs/data_new/model_dataset_compatibility.cpp:146: Feature volatility_dcl is present in model but not in pool.

I run cat boost in a loop
I use the exact same DataFrame but with different rows obviously.
I have used cat boost in loops previously with success

catboost version: 0.12.2
Operating System: Mac OS X 10.14.2
CPU: i7 2.6 GHz

**Comment by annaveronika** [comment]
Are you sure you are passing dataframes with the same column names? Are you sure that you don't remove column names somewhere?

**Comment by annaveronika** [comment]
Also please try the same code with version 0.10.3 and check if it works there.

**Comment by gkourogiorgas** [comment]
I used the exact same dataset. Anyway, I changed the logic of my code and I got what I wanted
