### ISSUE TITLE
R Catboost: Got Unsafe Target Value

### ISSUE THREAD

**Issue by prescient** [catboost/catboost#639]
**Problem:** Receive the error "Got unsafe target value = 1.10959e+06 at object #0 of dataset learn" when running the code below. Am unsure of what this error means or if i should be receiving it. I've tried running catboost on data with a similar size and did not have any issues.

**catboost version:** 0.12.1.1
**Operating System:** OSX 10.13.6
**CPU:** Core i7

```
label <- c(1103786.01, 303244.875, 1109587.0875, 1342230.65, 954332.775, 1030986.775, 1097247.1625, 1003217.1, 426214.8, 1131959.8, 745345.1125, 1005575.2875)
data <- structure(list(X1 = c(14036.77, 18986.51, 1029.36, 950.8, 16795.53, 47158.25, 44.64, 22035.24, 37.4, 32.94, 2667.95, 42890.6099999999),
                       X2 = c(5711.51999999999, 1659.81, 12478.6, 8904.95999999998, 447.55, 4504.23, 1358.07, 5266.85, 1517.7, 4403.46999999999, 500.08, 2027.41), 
                       X3 = c(1580.15, 2873.17, 111.9, 95.17, 2715.02, 26321.02, 109.02, 27896.63, 124.58, 33.1, 2547.31, 2993.46), 
                       X4 = c(3324.72999999999, 1218.51, 233.34, 116.88, 537.05, 10635.84, 509.31, 6818.77, 1243.75, 43.85, 1359.35, 5884.12), 
                       X5 = c(330.35, 290.59, 1004.88, 936.22, 48.47, 315.92, 310.77, 1037.22, 158.38, 986.359999999999, 116.53, 159.64)), 
                  row.names = c(3L, 14L, 9L, 6L, 12L, 15L, 10L, 8L, 11L, 7L, 5L, 13L), class = "data.frame")

train_pool <- catboost.load_pool(data = data, label = label)
mdl <- catboost.train(train_pool,
                      NULL,
                      params = list(loss_function = "RMSE",
                                    eval_metric = "RMSE",
                                    random_seed = 1234,
                                    logging_level = "Silent"))
```

**Comment by prescient** [comment]
Poking around a bit it looks as if absolute values greater than 1e6 are flagged as not safe:

```
  inline bool IsSafeTarget(float value) {
    return Abs(value) < 1e6f;
  }
```
  https://github.com/catboost/catboost/blob/a79166e60eb72f2338cf3680217301ef93d67c88/catboost/libs/target/data_providers.cpp

Which generates this warning:

```
for (auto objectIdx : xrange(convertedTarget.size())) {
  const float value = convertedTarget[objectIdx];
  if (!IsSafeTarget(value)) {
    CATBOOST_WARNING_LOG
    << "Got unsafe target "
    << LabeledOutput(value)
    << " at object #" << objectIdx << " of dataset " << datasetName << Endl;
    break;
  }
```
But I'm not sure if this is an actual issue in terms of building the model and if so do I need to scale all my data/labels.

**Comment by annaveronika** [comment]
This is just a safety warning. Usually when people have very large target values, this means they have some trash in data. This happends often, and having large values happens not so often. So maybe in your case the data is fine, then you can just ignore the warning.

This warning doesn't change the behavoir of the algorithm, it trains the same way as it should.

**Comment by prescient** [comment]
I appreciate the info. We are using catboost with financial data so large values are expected.

**Comment by annaveronika** [comment]
We will remove this warning for regression then.

**Comment by nikitxskv** [comment]
We fixed it!

**Comment by Sarustam** [comment]
Добрый день, Анна-Вероника! У меня тоже появляются подобные сообщения "Got unsafe target value = 1.2667e+09 at object #0 of dataset learn" я уверен, что с моими данными все отлично. Есть ли способ отключить такие сообщения?
