### ISSUE TITLE
Add iteration to cv output

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#640]
If metric_period != 1 the `scores` is hard to interpret as it doesn't contain an iterations column. 

```
from catboost import Pool, cv
params = {'iterations': 2500, 'loss_function':'RMSE', 'has_time':True,  'leaf_estimation_iterations':1 }  # https://github.com/catboost/catboost/issues/339
scores = cv(Pool(X, y, cat_features), params, fold_count=12, metric_period=100, shuffle=False)
```
```

0:	learn: 56.2508041	test: 55.9916902	best: 55.9916902 (0)	total: 151ms	remaining: 6m 17s
100:	learn: 5.4106440	test: 5.2920596	best: 5.2920596 (100)	total: 12.5s	remaining: 4m 57s
200:	learn: 4.0520781	test: 4.4677955	best: 4.4677955 (200)	total: 24.9s	remaining: 4m 44s
300:	learn: 3.7810889	test: 4.3575763	best: 4.3575763 (300)	total: 37.8s	remaining: 4m 35s
400:	learn: 3.6016282	test: 4.2939335	best: 4.2939335 (400)	total: 50.8s	remaining: 4m 25s
```

```
scores
```

```
test-RMSE-mean | test-RMSE-std | train-RMSE-mean | train-RMSE-std
-- | -- | -- | --
55.991690 | 5.668848 | 56.250804 | 0.526749
5.292060 | 1.432104 | 5.410644 | 0.088603
4.467795 | 0.900840 | 4.052078 | 0.065281
4.357576 | 0.860407 | 3.781089 | 0.059641
4.293933 | 0.840615 | 3.601628 | 0.05334
```

scores is missing the first column above. Also running best - how do you extract this? I've observed that the best model from `cv()` with `shuffle=False` for a time series model with high auto-correlation is significantly different to what I get when I use an eval_set with early stopping as a blocked cv gives a less biased estimate in these cases. So I'd prefer to use cv() but I don't see how to automatically extract the best estimator from the result?

**Comment by annaveronika** [comment]
We will add the iterations column, thanks a lot for this idea!
About extracting the best estimator from cv - we can only select the best iteration during cv. The best iteration in cv is the iteration with best mean test error value.
If you want to select best parameters using cv, you need to run it on each set of parameters and select best estimator after that.

**Comment by annaveronika** [comment]
This is implemented now.
