### ISSUE TITLE
Bring name of base CatBoost exception type to naming convention

### ISSUE THREAD

**Issue by daskol** [catboost/catboost#648]
At the moment, `CatboostError` is a base exception. It differs from other identifiers which have capitalized `B` like `CatBoostRegressor` or `_CatBoostBase`. I suppose that it would be better no rename `CatboostError` to `CatBoostError` for consistency

**Comment by annaveronika** [comment]
That's a nice idea and a simple task for contribution! Adding "good first issue" label.

**Comment by annaveronika** [comment]
This is fixed now thanks to @infected-mushroom, thanks a lot for your contribution!
