### ISSUE TITLE
Upgrade to 12.2 hangs in cv()

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#664]
I upgraded from catboost python 11.2 to 12.2 as I wanted to make use of the GPU enhancements in release 12.0

I immediately ran into issues. 

First it continually warns 

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric. 

Disabling 'metric_period' suppresses the message, but it displays the log below after a few seconds then hangs. GPU usage is 0%. I've pasted the KeyboardInterrupt I get when I force halt execution.

There doesn't appear to be anything in the release notes after 11.2 mentioning over fit detection or how to disable? If it's a new feature then the documentation needs to be updated. How do I get back to 11.2 behaviour with GPU cv?

Update: rolled back to 12.0 and it doesn't hang. 
```
estimator = CatBoostRegressor(loss_function='RMSE', has_time=True, logging_level='Silent', task_type='GPU', train_dir=os.path.join(folder, 'catboost_info'), leaf_estimation_iterations=1)
params = {'iterations': 5000, 'max_depth':max_depth, 'loss_function':'RMSE', 'has_time':True,'leaf_estimation_iterations':1 }
cv(Pool(X, y, cat_features), params, fold_count=5, shuffle=False)
```

> 
> 0:	learn: 56.2590112	test: 56.0987956	best: 56.0987956 (0)
> 1:	learn: 54.6424166	test: 54.4864229	best: 54.4864229 (1)
> 2:	learn: 53.0711652	test: 52.9180095	best: 52.9180095 (2)
> 3:	learn: 51.5448314	test: 51.4005489	best: 51.4005489 (3)
> 4:	learn: 50.0692420	test: 49.9293819	best: 49.9293819 (4)
> 5:	learn: 48.6432487	test: 48.5113637	best: 48.5113637 (5)
> 6:	learn: 47.2602977	test: 47.1332312	best: 47.1332312 (6)
> 7:	learn: 45.9144117	test: 45.8027206	best: 45.8027206 (7)
> 8:	learn: 44.6074339	test: 44.5036863	best: 44.5036863 (8)
> 9:	learn: 43.3416403	test: 43.2430982	best: 43.2430982 (9)
> 10:	learn: 42.1189394	test: 42.0486796	best: 42.0486796 (10)
> 11:	learn: 40.9381990	test: 40.8827915	best: 40.8827915 (11)
> 12:	learn: 39.7910436	test: 39.7331648	best: 39.7331648 (12)
> 13:	learn: 38.6745958	test: 38.6212012	best: 38.6212012 (13)
> 14:	learn: 37.6035676	test: 37.5588591	best: 37.5588591 (14)
> 15:	learn: 36.5596698	test: 36.5224911	best: 36.5224911 (15)
> 16:	learn: 35.5482654	test: 35.5162237	best: 35.5162237 (16)
> 17:	learn: 34.5705109	test: 34.5439229	best: 34.5439229 (17)
> 18:	learn: 33.6254317	test: 33.5982958	best: 33.5982958 (18)
> 19:	learn: 32.7105456	test: 32.6920351	best: 32.6920351 (19)
> 20:	learn: 31.8238989	test: 31.8093966	best: 31.8093966 (20)
> 21:	learn: 30.9675317	test: 30.9533636	best: 30.9533636 (21)
> 22:	learn: 30.1372897	test: 30.1447135	best: 30.1447135 (22)
> 23:	learn: 29.3386934	test: 29.3502392	best: 29.3502392 (23)
> 24:	learn: 28.5669423	test: 28.5829809	best: 28.5829809 (24)
> 25:	learn: 27.8123282	test: 27.8273074	best: 27.8273074 (25)
> 26:	learn: 27.0794141	test: 27.1010562	best: 27.1010562 (26)
> 27:	learn: 26.3702774	test: 26.3990484	best: 26.3990484 (27)
> 28:	learn: 25.6826836	test: 25.7304341	best: 25.7304341 (28)
> 29:	learn: 25.0238769	test: 25.0686829	best: 25.0686829 (29)
> 30:	learn: 24.3876170	test: 24.4372886	best: 24.4372886 (30)
> 31:	learn: 23.7760735	test: 23.8210060	best: 23.8210060 (31)
> 32:	learn: 23.1836116	test: 23.2549592	best: 23.2549592 (32)
> 33:	learn: 22.6107336	test: 22.6866914	best: 22.6866914 (33)
> 34:	learn: 22.0497685	test: 22.1279707	best: 22.1279707 (34)
> 35:	learn: 21.5097790	test: 21.5891840	best: 21.5891840 (35)
> 36:	learn: 20.9904129	test: 21.0737074	best: 21.0737074 (36)
> 37:	learn: 20.4852112	test: 20.5805300	best: 20.5805300 (37)
> 38:	learn: 20.0026523	test: 20.1015344	best: 20.1015344 (38)
> 39:	learn: 19.5344998	test: 19.6339143	best: 19.6339143 (39)
> 40:	learn: 19.0812010	test: 19.1905257	best: 19.1905257 (40)
> 41:	learn: 18.6401975	test: 18.7443711	best: 18.7443711 (41)
> 42:	learn: 18.2186061	test: 18.3274512	best: 18.3274512 (42)
> 43:	learn: 17.8165080	test: 17.9309602	best: 17.9309602 (43)
> 44:	learn: 17.4285026	test: 17.5602934	best: 17.5602934 (44)
> 45:	learn: 17.0496262	test: 17.1824466	best: 17.1824466 (45)
> 46:	learn: 16.6828383	test: 16.8260860	best: 16.8260860 (46)
> 47:	learn: 16.3353598	test: 16.4749555	best: 16.4749555 (47)
> 48:	learn: 15.9841178	test: 16.1238615	best: 16.1238615 (48)
> 49:	learn: 15.6098464	test: 15.7564653	best: 15.7564653 (49)
> 50:	learn: 15.2442314	test: 15.3965930	best: 15.3965930 (50)
> 51:	learn: 14.8899489	test: 15.0385087	best: 15.0385087 (51)
> 52:	learn: 14.5351727	test: 14.7101088	best: 14.7101088 (52)
> 53:	learn: 14.1918246	test: 14.3658954	best: 14.3658954 (53)
> 54:	learn: 13.8590463	test: 14.0473009	best: 14.0473009 (54)
> 55:	learn: 13.5241644	test: 13.7333374	best: 13.7333374 (55)
> 56:	learn: 13.1964893	test: 13.4057868	best: 13.4057868 (56)
> 57:	learn: 12.8824552	test: 13.0866115	best: 13.0866115 (57)
> 58:	learn: 12.5791929	test: 12.7648393	best: 12.7648393 (58)
> 59:	learn: 12.2870069	test: 12.4699482	best: 12.4699482 (59)
> 60:	learn: 12.0039641	test: 12.1750785	best: 12.1750785 (60)
> 61:	learn: 11.7291978	test: 11.9071826	best: 11.9071826 (61)
> 62:	learn: 11.4624945	test: 11.6481079	best: 11.6481079 (62)
> 63:	learn: 11.2056838	test: 11.3866532	best: 11.3866532 (63)
> 64:	learn: 10.9587219	test: 11.1398740	best: 11.1398740 (64)
> 65:	learn: 10.7187715	test: 10.9058686	best: 10.9058686 (65)
> 66:	learn: 10.4874326	test: 10.6743262	best: 10.6743262 (66)
> 67:	learn: 10.2651262	test: 10.4571397	best: 10.4571397 (67)
> 68:	learn: 10.0516722	test: 10.2281573	best: 10.2281573 (68)
> 69:	learn: 9.8458537	test: 10.0090697	best: 10.0090697 (69)
> 70:	learn: 9.6454418	test: 9.7978681	best: 9.7978681 (70)
> 71:	learn: 9.4556162	test: 9.5971608	best: 9.5971608 (71)
> 72:	learn: 9.2708558	test: 9.4079435	best: 9.4079435 (72)
> 73:	learn: 9.0924685	test: 9.2199029	best: 9.2199029 (73)
> 74:	learn: 8.9222454	test: 9.0577690	best: 9.0577690 (74)
> 75:	learn: 8.7576366	test: 8.8928460	best: 8.8928460 (75)
> 76:	learn: 8.5979880	test: 8.7337254	best: 8.7337254 (76)
> 77:	learn: 8.4443301	test: 8.5665879	best: 8.5665879 (77)
> 78:	learn: 8.2961593	test: 8.4265929	best: 8.4265929 (78)
> 79:	learn: 8.1548944	test: 8.2737867	best: 8.2737867 (79)
> 80:	learn: 8.0190034	test: 8.1394297	best: 8.1394297 (80)
> 81:	learn: 7.8897455	test: 8.0120379	best: 8.0120379 (81)
> 82:	learn: 7.7649116	test: 7.8769370	best: 7.8769370 (82)
> 83:	learn: 7.6451866	test: 7.7623187	best: 7.7623187 (83)
> 84:	learn: 7.5284868	test: 7.6426469	best: 7.6426469 (84)
> 85:	learn: 7.4178659	test: 7.5265349	best: 7.5265349 (85)
> 86:	learn: 7.3118763	test: 7.4244316	best: 7.4244316 (86)
> 87:	learn: 7.2082271	test: 7.3063385	best: 7.3063385 (87)
> 88:	learn: 7.1112329	test: 7.1971437	best: 7.1971437 (88)
> 89:	learn: 7.0186053	test: 7.1072523	best: 7.1072523 (89)
> 90:	learn: 6.9279349	test: 7.0167661	best: 7.0167661 (90)
> 91:	learn: 6.8421892	test: 6.9314039	best: 6.9314039 (91)
> 92:	learn: 6.7597306	test: 6.8379030	best: 6.8379030 (92)
> 93:	learn: 6.6785245	test: 6.7639390	best: 6.7639390 (93)	total: 3.27s	remaining: 2m 50s
> 

> ---------------------------------------------------------------------------
> KeyboardInterrupt                         Traceback (most recent call last)
> <ipython-input-19-58aeb9768ba4> in <module>
>       8 
>       9 params = {'iterations': 5000, 'max_depth':max_depth, 'loss_function':'RMSE', 'has_time':True,'leaf_estimation_iterations':1 }
> ---> 10 cv(Pool(X, y, cat_features), params, fold_count=5, shuffle=False)
>      11 
>      12 #results = []
> 
> ~/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/catboost/core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, max_time_spent_on_fixed_cost_ratio, dev_max_iterations_batch_size)
>    2949     with log_fixup(), plot_wrapper(plot, params):
>    2950         return _cv(params, pool, fold_count, inverted, partition_random_seed, shuffle, stratified,
> -> 2951                    as_pandas, max_time_spent_on_fixed_cost_ratio, dev_max_iterations_batch_size)
>    2952 
>    2953 
> 
> _catboost.pyx in _catboost._cv()
> 
> _catboost.pyx in _catboost._cv()
> 
> KeyboardInterrupt:

**Comment by annaveronika** [comment]
We have removed the warning, it will come out in the next release soon.
About the hanging of the training: actually the current version trains several iterations on first fold, then the same ones on next fold and so on. And after each fold is processed the log is out. This feels like the training hangs.
What we will do with that: we will output time left on each iteration, so that you see that there is progress. And we will stop outputting loss values in batches, we will only output one loss value after a block of iterations is processed.

Sorry for inconvenience!

**Comment by annaveronika** [comment]
We'll start again with this task when we have resources for that. For now - just information: there is no hanging, it's just that cv now processes iterations in batches. So you need to wait for the next batch to finish.
We'll make proper logging later.

**Comment by annaveronika** [comment]
This is fixed now in code, will be on pypi in the next release, which will happen in a couple of days
