### ISSUE TITLE
How to build libcatboostmodel as a static lib and not shared library?

### ISSUE THREAD

**Issue by laurentvm** [catboost/catboost#666]
How can I change the makefile to build a static library instead of a dynamic one?

**Comment by hanyk** [comment]
The same question. We really need that!

**Comment by exprmntr** [comment]
Added make/model_interface_static.CLANG50-LINUX-X86_64.makefile, it builds catboost/libs/model_interface/static/libcatboostmodel.a:

```
export CC=<...>
export CXX=<...>

make -j33 -f ./make/model_interface_static.CLANG50-LINUX-X86_64.makefile

$CXX catboost/libs/model_interface/cmake_example/main.cpp -L catboost/libs/model_interface/static/ -lcatboostmodel -lpthread -ldl -o example
```

**Comment by hanyk** [comment]
I think ${CC}++  should be replaced with ${CXX}.
It seems not work under mac os.

**Comment by annaveronika** [comment]
@hanyk @laurentvm Does the solution work for you?

**Comment by hanyk** [comment]
@annaveronika 
./ya make -r catboost/libs/model_interface/static

**Comment by laurentvm** [comment]
Yes, thanks a lot it works.

**Comment by annaveronika** [comment]
Awesome!
