### ISSUE TITLE
shap.TreeExplainer(model, train_data, feature_dependence="independent", model_output="probability")

### ISSUE THREAD

**Issue by le01phuo** [catboost/catboost#668]
https://github.com/catboost/catboost/blob/820f1bff5e2e5d6fc64fcb4d572c9a7f3fcaf5a1/catboost/tutorials/classification/classification_tutorial.ipynb#L1100

When we want to explain the probability of prediction. 
explainer = shap.TreeExplainer(model, train_data, feature_dependence="independent", model_output="probability")

How can we modify the train_data from the earlier code below?

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(Pool(X, y, cat_features=cat_features))

**Comment by dvpolyakov** [comment]
@le01phuo, sorry for a long waiting of an answer. 

Could you, please, provide a full code for us to reproduce the error?

**Comment by annaveronika** [comment]
The pr by @dvpolyakov is merged now, the functionality will be available starting from next release. Thanks for the issue! And thanks a lot @dvpolyakov for the contribution!
