### ISSUE TITLE
Border caching

### ISSUE THREAD

**Issue by Metamorphus** [catboost/catboost#673]
After training is it possible to save/cache acquired borders in order to reuse them in future trains? Binarization stage for me is the most time-consuming, so it would be nice to do it once and then reuse the results (provided that the dataset doesn't change).

**Comment by annaveronika** [comment]
If you do it using cmdline then it's already possible (save it to file, load from file), if you want it in python here is the pr https://github.com/catboost/catboost/pull/656
It will be there after the pr is merged.

**Comment by Metamorphus** [comment]
Thanks!
