### ISSUE TITLE
Out of the box LabelEncoder on cat_features

### ISSUE THREAD

**Issue by AlexRig** [catboost/catboost#675]
Problem: I recently applied CatBoost to data where a feature specified in `cat_features` was `dtype` `str` i.e. A1, A2, B1, B2. I got the usual `must be int()` error so I went back and passed `LabelEncoder` over it and it worked fine. `feature_importances_` was also able to report back. I thought it might be a nice addition to have the in-built with CatBoost and wanted to raise it to highlight any potential conflicts.

catboost version: 12.2
Operating System: Windows 10
CPU: i7

**Comment by kizill** [comment]
If you are doing something like this:
```python
cb = CatBoost()
...
cb.fit(X,y, cat_features=['A', 'B'])
```
you are experiencing issue #608 
Currently `cat_features` should contain categorical feature column indexes.

**Comment by AlexRig** [comment]
@kizill you are absolutely correct, I had forgotten that I had addressed this elsewhere in my Notebook. I have seen issue #608 and will correct my response there.

This is a different 'issue', this is where the contents of the feature are `str`. It is quite common for business features to have countries etc. and I believe `LabelEncoder` would address this. Thoughts?

**Comment by david-waterworth** [comment]
When you say LabelEncoder are you talking about the sklearn LabelEncoder? I believe that's intended for encoding y? I think you should be using OrdinalEncoder for this as you're encoding X?

But as long as you pass the correct column ordinals to fit() it should work fine for str features? Although I've found that doing so causes the train residuals to have a non-zero mean which doesn't seem to occur when you OrdinalEncoder string features (as then catboost's categorical encoding isn't invoked)

**Comment by AlexRig** [comment]
`LabelEncoder` and `OrdinalEncoder` have been used interchangeably, I used `LabelEncoder` as it was a single feature I needed converted.

When I passed the feature column indices to `cat_features` in CatBoostClassifier, it wouldn't accept it as this particular feature's content `dtype` was `str`. Interested to see how you managed it?

**Comment by david-waterworth** [comment]
Ah I see, if you pass a single column as the y argument to LableEncoder it will work fine. I was accidentally using it in a pipeline using ColumnTransformer to pass multiple columns and getting a stack trace.

When using ColumnTransformer I didn't pass cat_features at all, i.e.

```
pipeline = Pipeline([
        ('encoder', ColumnTransformer([('categorical',OrdinalEncoder(categories='auto'),['timeofday','dayofweek','isdst','isholiday'])], remainder = 'passthrough')),
        ('estimator', CatBoostRegressor(loss_function='RMSE', has_time=True, logging_level='Silent', task_type='GPU', devices='0'))])
```

This doesn't use CatBoosts target encoding at all. The other thing I've experimented with is created my own sklearn estimator which wraps CatBoostRegressor and generates the cat_features array from the data. This is slightly annoying as sklearn hyper-parameter discovery requires each parameter be explicitly defined as a constructor argument.

i.e. something like this - it's requires X to be a pandas.DataFrame and cat_features_type controls the mapping by type to category, i.e. you may use cat_feature_types=['object','int'] for strings and integers

```
class CatBoostRegressorEx(BaseEstimator, RegressorMixin):
    '''
    sklearn like wrapper for CatBoostRegressor, allows use of sklearn style cross-validation etc by internalising cat_features
    '''
    def __init__(self, n_estimators=1000, max_depth=6, cat_feature_types=['object']):
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.cat_feature_types = cat_feature_types

    def fit(self, X: pd.DataFrame, y: pd.Series, **fit_params):
        self.estimator_ =  CatBoostRegressor(n_estimators=self.n_estimators, max_depth=self.max_depth, loss_function='RMSE', has_time=True, metric_period=100)
        cat_features=self._cat_features(X, cat_feature_types=self.cat_feature_types)
        self.estimator_.fit(Pool(X, y, cat_features=cat_features)   )
        return self

    def predict(self, X: pd.DataFrame, **predict_params) -> pd.Series:
        return self.estimator_.predict(X, **predict_params)

    def _cat_features(self, X: pd.DataFrame, cat_feature_types:List[str]=['object']):
        """
        get column ordinals of categorical columns based on dtype
        """
        cat_columns = X.select_dtypes(include=cat_feature_types).columns
        return [X.columns.get_loc(c) for c in X.columns if c in cat_columns]

```

**Comment by annaveronika** [comment]
> This is a different 'issue', this is where the contents of the feature are `str`. It is quite common for business features to have countries etc. and I believe `LabelEncoder` would address this. Thoughts?

@AlexRig Strings are already supported for categorical feature values.

**Comment by annaveronika** [comment]
@AlexRig So the answer to your request is - it's already there. If there are other issues - let us know, we'll try to help. Should I close this issue?

**Comment by AlexRig** [comment]
@annaveronika I can't seem to replicate the error I was facing so assume user error. Please close.
