### ISSUE TITLE
Unable to compile R-package with GPU support on Ubuntu 18.04

### ISSUE THREAD

**Issue by psandev** [catboost/catboost#676]
Problem: {problem description}
Compilation error. 
cuda_base.h:129:27: error: 'memoryType' is deprecated [-Werror,-Wdeprecated-declarations]
See attached files.
catboost version: {version}
0.12.2
Operating System: {OS}
Ubuntu 18,04
CPU: {CPU}
i9 9900K
# GPU: {GPU}
Geforce RTX 2080 Ti

# gcc
6
[00check.log](https://github.com/catboost/catboost/files/2866402/00check.log)

[00install.txt](https://github.com/catboost/catboost/files/2866404/00install.txt)

**Comment by annaveronika** [comment]
I suggest to install prebuilt binaries from github or from conda.
We had a bunch of compilation problems with R, and these problems were different for different environment settings that people have, and it was very time consuming to look into each of them and to debug every different case.
For that reason we published the binaries. Does this solution not work for you?

**Comment by annaveronika** [comment]
https://tech.yandex.com/catboost/doc/dg/installation/r-installation-binary-installation-docpage/ - here is the instruction.

**Comment by annaveronika** [comment]
@psandev Does this work for you?

**Comment by psandev** [comment]
Yes, it did eventually. I installed the binaries and was able to train with
GPU. Thanks a lot for the help. The reason I was trying fanatically to
compile catboost was that it was unclear from the manual(at least to me) if
the binaries will support GPU. All the rest of the GPU capable algorithms
need compilation and I kind of extrapolated that it is so with catboost as
well. And I am not the only one with that assumption. Quite many went
straight to compilation instead of using the binaries. It would be helpful
if you state it cleared that the binaries support GPU, it would save many
countless hours. And we will be using more catboost, which is a great
algorithm. Thanks again.

**Comment by annaveronika** [comment]
Thanks for the feedback, we will clarify it in docs!

**Comment by annaveronika** [comment]
TODO: clafiry in the docs that gpu is supported by default in python, R and cmdline.

**Comment by kizill** [comment]
Already in released docs.
