### ISSUE TITLE
Feature B present in model but not in pool.

### ISSUE THREAD

**Issue by timpal0l** [catboost/catboost#682]
**Problem:** 

Cannot use pretrained model for prediction on new data. I have trained a CatBoost classifier on a pandas dataframe. The dataframe contains a header. And there is 262 attributes (A,B,C, D, ...) , and 100 000 samples. The model training is fine. However when loading the model with joblib and passing in one sample with 262 attributes as a list or a numpy array, it complains about the second feature "B" not being presented in the Pool. I verfied it is present by taking a raw sample from the training set and passing it in for prediction. 
 
**catboost version:** Latest (2019/03/20)

**Operating System:** {Ubuntu 18.04}

**GPU:** 2x Nvidia 1080Ti

**Comment by annaveronika** [comment]
We'll check and get back to you! Looking into this now.

**Comment by annaveronika** [comment]
I think the problem was that we didn't support prediction on a single object. Starting from v0.14.0 we do support it. So the problem should be fixed. Please try upgrading. And let us know if you still have any problems!

**Comment by veonua** [comment]
it is just an ambiguous error message, it happens when you do prediction on one item instead of an array of items

`model.predict( samples[1] ) ` would trigger this error
propper form is  `model.predict( [ samples[1] ] ) `

**Comment by annaveronika** [comment]
Prediction on one item is supported starting from 0.14.0

**Comment by veonua** [comment]
> catboost.__version__

 '0.14.0'
> type(X_train.iloc[25])

pandas.core.series.Series
>model.predict(X_train.iloc[25])

...
catboost/libs/data_new/model_dataset_compatibility.cpp:143: Feature txt_tfidf_1 is present in model but not in pool.

works fine with 
>model.predict( [ X_train.iloc[25] ] )

**Comment by annaveronika** [comment]
This means, we didn't support this case for all ways of passing a single object. Thanks for pointing this out! Here is an issue for that: https://github.com/catboost/catboost/issues/785
Btw we do welcome contrubitions! You can take a look on how it was supported for list and implement this case.

**Comment by randomstate13** [comment]
It's not common practice to use iloc/loc like [ X_train.iloc[25] ] to get a nested row. Try this X_train.iloc[ [25] ]
