### ISSUE TITLE
model.predict() allocates too much memory

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#684]
Seems to need returns numpy array instead of python array - https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L2404

**Comment by khrisanfov** [comment]
Looks like ShapValues has the same issue https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L2474

**Comment by annaveronika** [comment]
The fix is on github now, you can now build from source, or wait for our next release on pypi, which will come soon!

**Comment by 410124810** [comment]
> Seems to need returns numpy array instead of python array - https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/_catboost.pyx#L2404

Hi, khrisanfov,  have  you got a improvement on prediction with newer version?
I use the version 0.15.2.  In my condition,  I used 90% data for training,  it just cost 8G memory,  but when  predicting on the other 10% data, it cost extra  26G  memory.  I'm not sure if the bug had been fixed.
ps: predict_proba()
