### ISSUE TITLE
Question about one_hot_max_size

### ISSUE THREAD

**Issue by gitmario** [catboost/catboost#686]
I have a question about the one_hot_max_size parameter.

In practical applications of supervised learning, it happens quite often that a categorical feature has too many levels to be one-hot encoded, but a very small subset of levels covers the majority of the population.

A classical example is the country. Imagine that we're building a model to predict a customer's propensity to purchase based on demographic information. If we have customers from all over the world, the "country" column will have about 100 levels, but most likely 10% of countries will cover 90% of the customer base (example of Pareto principle).

What is the best approach in this case?

Proposed solutions:
1) Set one_hot_max_size=0 and use CatBoost's integrated target statistics
2) Set one_hot_max_size=300 and use CatBoost's integrated one-hot encoding
3) Set one_hot_max_size=0 and use CatBoost's integrated target statistics, but also create dummy binary features for the top 10 big coutries (in this case, we're using one-hot encoding for big countries, and target statics for all countries)

Thanks in advance!

catboost version: {0.11.2}

**Comment by annaveronika** [comment]
The out-of-the box solution for that usually works better than external one-hot encoding, but it's a great idea to experiment further. For example, we currently do either one-hot or stats - only one of them. But in some cases it is beneficial to do both, so you are right, it might give a quality boost to use out-of-the-box catboost + one-hot for few top categories. We plan to add this to out-of-the box solution at some point!

As for the format of the question: this is more a discussion question than an issue. For that the best would be a stackoverflow question with tag catboost (https://stackoverflow.com/questions/tagged/catboost), you will get different view points there (and issues are usually only answered by the team). We are reading stackoverflow too, not only issues, so it's better in all acepts. Another option is to use our telegram chat (http://t.me/catboost_en) where you will also find different people from and outside the team that will love to discuss things.

Anyway thanks a lot for asking!

**Comment by annaveronika** [comment]
Let us know if you need any further information!

**Comment by gitmario** [comment]
Thank you Anna Veronika. I will set up an experiment with different combinations of target statistics and OHE as soon as I have time. I'll keep you posted on the results

**Comment by annaveronika** [comment]
@gitmario Here is an issue for us to support one-hot together with target-based statistics: https://github.com/catboost/catboost/issues/698
I'm closing the current issue then, and if you're interested, you can follow this one for progress.
Thanks for a great suggestion!

**Comment by gitmario** [comment]
Cool thanks! I'm following #698
