### ISSUE TITLE
where is pip package for python3 on Windows?

### ISSUE THREAD

**Issue by goodtogood** [catboost/catboost#689]
os: windows 8.1  python 3.5
tried some time , failed in building GPU catboost on Windows.
Is there some pip package with GPU enabled for windows?
thanks!

**Comment by annaveronika** [comment]
"pip install catboost" will install catboost with gpu support.

**Comment by annaveronika** [comment]
Please let us know if this works for you!

**Comment by goodtogood** [comment]
@annaveronika 
sorry for that.
there's no gpu within package name, I thought It's without gpu support
now It works.
thanks!
