### ISSUE TITLE
CatboostError: catboost/libs/model/model_build_helper.cpp:48: Condition violated: `ApproxDimension == treeLeafValues.ysize()'

### ISSUE THREAD

**Issue by xg-servian** [catboost/catboost#690]
### Problem: 

When fit model, get the following error

```
---------------------------------------------------------------------------
CatboostError                             Traceback (most recent call last)
<ipython-input-30-27786e17dd8c> in <module>()
     18     model.fit(data.iloc[train_index][input_col], 
     19               data.iloc[train_index]['isTEST'],
---> 20              eval_set= test_data
     21              )
     22     y_pred = model.predict_proba(data.iloc[test_index][input_col])[:,np.where(model.classes_)[0][0]]

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
   2181         self._fit(X, y, cat_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   2182                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 2183                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
   2184         return self
   2185 

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
   1124 
   1125         with log_fixup(), plot_wrapper(plot, self.get_params()):
-> 1126             self._train(train_pool, eval_sets, params, allow_clear_pool)
   1127 
   1128         if (not self._object._has_leaf_weights_in_model()) and allow_clear_pool:

~/anaconda3/lib/python3.7/site-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool)
    826 
    827     def _train(self, train_pool, test_pool, params, allow_clear_pool):
--> 828         self._object._train(train_pool, test_pool, params, allow_clear_pool)
    829         self._set_trained_model_attributes()
    830 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatboostError: catboost/libs/model/model_build_helper.cpp:48: Condition violated: `ApproxDimension == treeLeafValues.ysize()'
```

### catboost version: 

`catboost==0.12.2`

### Operating System: 

MacBook Pro (15-inch, 2018) // MacOS Mojave ver10.14.2 (18C54)

16G RAM

### CPU: 

2.2 GHz Intel Core i7

### Observations:

Seems related to RAM.

RAM usually got 100% before the error.
And if decrease the size of training data, error will disappear.

**Comment by kizill** [comment]
Hello! Do you use CPU or GPU training? And do you use multiclass target?

**Comment by xg1990** [comment]
Hi, it is using CPU for binary classification

**Comment by kizill** [comment]
Please, set `logging_level='Debug'` and send us your log. My current assumption - there was an empty tree during training, and that triggered a bug with model export.

**Comment by ideological** [comment]
...
Needed more memory then allowed, will drop some ctrs after score calculation
current rss: 36.7968 full needed memory: 0.0743753
P70_AMOUNT_BASE_IPTV_AMNTCURRENT, bin=213 score 32.98202693
Needed more memory then allowed, will drop some ctrs after score calculation
current rss: 36.7968 full needed memory: 0.148751
SERIALS_AOPTLIKECURRENT, bin=3 score 38.9058468
45:     test: 0.7424199 best: 0.7476032 (26)    total: 1m 14s   remaining: 2h 13m 57s

Needed more memory then allowed, will drop some ctrs after score calculation
current rss: 36.7968 full needed memory: 0.0743753
ELK_ON_CLIENTCURRENT, bin=0 score 31.41920388
Needed more memory then allowed, will drop some ctrs after score calculation
current rss: 36.7968 full needed memory: 0.148751
ELK_ON_CLIENTHISTORY, bin=0 score 83.89428397
46:     test: 0.7541862 best: 0.7541862 (46)    total: 1m 16s   remaining: 2h 14m 6s
Training has stopped (degenerate solution on iteration 46, probably too small l2-regularization, try to increase it)

bestTest = 0.7541862497
bestIteration = 46

Shrink model to first 47 iterations.
Traceback (most recent call last):
  File "trainer.py", line 1298, in <module>
  File "/opt/python3/lib/python3.6/site-packages/catboost/core.py", line 2183, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
  File "/opt/python3/lib/python3.6/site-packages/catboost/core.py", line 1126, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool)
  File "/opt/python3/lib/python3.6/site-packages/catboost/core.py", line 828, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool)
  File "_catboost.pyx", line 2296, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2316, in _catboost._CatBoost._train
_catboost.CatboostError: catboost/libs/model/model_build_helper.cpp:48: Condition violated: `ApproxDimension == treeLeafValues.ysize()'
