### ISSUE TITLE
Not showing Custom Loss AUC

### ISSUE THREAD

**Issue by payala-pi** [catboost/catboost#691]
Problem: Not showing Custom Loss AUC 
catboost version: version 0.11.1
Operating System: Windows

Hi!
Doing:

```
fit_paramsdef1<- list(iterations = 500,loss_function = 'Logloss',custom_loss='AUC')
model<- catboost.train(train_pool,params = fit_paramsdef1)
```

I get:

> 0:	learn: 0.3835461	total: 187ms	remaining: 9.18s
> 1:	learn: 0.3213105	total: 397ms	remaining: 9.52s
> 2:	learn: 0.3036115	total: 623ms	remaining: 9.76s
> 3:	learn: 0.2951326	total: 829ms	remaining: 9.54s
> 4:	learn: 0.2893794	total: 1.03s	remaining: 9.27s
> 5:	learn: 0.2843688	total: 1.22s	remaining: 8.94s
> 6:	learn: 0.2801148	total: 1.43s	remaining: 8.81s
> 7:	learn: 0.2767989	total: 1.63s	remaining: 8.55s
> 8:	learn: 0.2732825	total: 1.81s	remaining: 8.25s
> 9:	learn: 0.2695338	total: 2.03s	remaining: 8.13s
> 10:	learn: 0.2664555	total: 2.22s	remaining: 7.88s

> ...

It does not output AUC, only Logloss. 
Aren't AUC values supposed to output during training?

**Comment by annaveronika** [comment]
Custom loss values are not written to stdout. But you can look into files with metric values (https://tech.yandex.com/catboost/doc/dg/concepts/output-data_loss-function-docpage/) that are generated during training.
You can also look on CatBoost Viewer or use tensorboard to see metric values plotted on graphs (https://tech.yandex.com/catboost/doc/dg/features/visualization-docpage/).
