### ISSUE TITLE
Support text features

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#697]

**Comment by timchurches** [comment]
Looking forwards to that! We're beginning to get good results using CatBoost with word2vec embeddings, but built-in support would be even better. One of the advantages of CatBoost is that it works so well out-of-the-box, without lots of hyper parameter tuning. We've made that one of the conclusions of a forthcoming applied research paper which uses CatBoost (we're **still** working on it, will post details soon, I promise!).

**Comment by bratao** [comment]
Hello @annaveronika ,

This is incredible. Could you share how you planning to implement this?
Will be similar to categories ( hashing trick or one hot), embeddings, or it is a novel technique?
Do you have an ETA for this feature?

**Comment by bratao** [comment]
Apparently this is already starting to arrive 🔥 🔥 🔥 

Just I found this commit by @KruchDmitriy 
https://github.com/catboost/catboost/commit/ff1d0cc18fab944ab42e0a6af706f6d9f4bdf2ed

**Comment by annaveronika** [comment]
No ETA yet, but we are working on that. Thank you very much for your interest! We will write about the details when it's all ready.

**Comment by bratao** [comment]
@annaveronika @KruchDmitriy this made into 0.15.1? It is possible to test this now?

**Comment by annaveronika** [comment]
It is not in 0.15.1 and it will not be there in next few releases. We'll let you know in this issue. Thanks for your interest!

**Comment by bratao** [comment]
Sorry to bother you @annaveronika ,but do the Catboost team plan to release this feature anytime soon? Or is something not for the short-term release?

**Comment by annaveronika** [comment]
The very first version should be out very soon. The code is on github, we'll publish texts together with a tutorial in the next release on in the release after next one.

**Comment by bratao** [comment]
@annaveronika Can you update us about the status of this feature? It made to the release? I cant find any example in the docs.

Thank you, and sorry for being annoying

**Comment by annaveronika** [comment]
Actually the first version can be already used from cmdline. The first version with python support is already on github and will come out in the next release this week.

**Comment by annaveronika** [comment]
Ok, so the first version is out in 0.19! We'll give updates on the next features in future release notices!

**Comment by franz101** [comment]
@annaveronika I really enjoyed your y-data talk. any updates on the word2vec feature?

cheers!

**Comment by annaveronika** [comment]
> @annaveronika I really enjoyed your y-data talk. any updates on the word2vec feature?
> 
> cheers!

All updates will be in future release notices. As for the news of the next release - text features are now supported on CPU, the release will be out in a couple of days.
