### ISSUE TITLE
thread_count documentation typo

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#699]
There's a minor typo for `thread_count` on [python-reference_parameters-list](https://catboost.ai/docs/concepts/python-reference_parameters-list.html)

There's two headers, CPU and GPU, under the CPU header there's two bullet points, CPU and GPU, then the GPU desription is repeated

**Comment by annaveronika** [comment]
Thanks, we'll fix it!

**Comment by Nikulinnn** [comment]
Thank you for the report, we have fixed it and published the corrected version.
