### ISSUE TITLE
'Invalid Description File : R installation. Did anyone succeed in installing R package?

### ISSUE THREAD

**Issue by akogay** [catboost/catboost#7]
install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/***/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/***/Temp/Rtmp8g9Ngq/devtools81cc1e1c2710/catboost-catboost-8fde831/catboost/R-package"  \
  --library="C:/***R-3.4.0/library" --install-tests 

* installing *source* package 'catboost' ...
Error : Неправильный файл 'DESCRIPTION'

<cd><e5><ef><f0><e0><e2><e8><eb><fc><ed><ee> <f1><ee><e7><e4><e0><ed><ed><e0>
ERROR: installing package DESCRIPTION failed for package 'catboost'
* removing 'C:/***/R-3.4.0/library/catboost'
Error: Command failed (1)

**Comment by akogay** [comment]
If I try to install from zip file:

> install.packages("C:/***/catboost-master.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'catboost-master/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by Mrugankakarte** [comment]
Hi,
I got error as Invalid Description File.

```
>devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
* installing *source* package 'catboost' ...
Error : Invalid DESCRIPTION file

Malformed package version.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package 'catboost'
```

**Comment by akogay** [comment]
Mrugankakarte I have same ERROR message
They updated README, I hope they'll update DESCRIPTION file too.
https://github.com/catboost/catboost/pull/6

**Comment by Mrugankakarte** [comment]
Yeah ....I just now read the news about catboost... directy came here to try it out...
I tried installing locally...same issue with Description File... Hope they will fix it soon.

```
>devtools::build()
* checking for file 'C:\Users\Mrugank\catboost\catboost\R-package/DESCRIPTION' ... OK
* preparing 'catboost':
* checking DESCRIPTION meta-information ... ERROR
Malformed package version.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

**Comment by alex-danilin** [comment]
Having the same issue. Maybe the problem is in 
Version: {version}
line in DESCRIPTION?

**Comment by Mrugankakarte** [comment]
Rename this issue to 'Invalid Description File : R installation'

This will help the developers to pinpoint the issue.

**Comment by av1611** [comment]
The same trouble.
> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
"C:/Users/avgr/AppData/Local/Temp/RtmpmyzyZ9/devtools2f502bfb74b3/catboost-catboost-8fde831/catboost/R-package"  \
  --library="C:/Users/avgr/Documents/R/win-library/3.4" --install-tests 
* installing *source* package 'catboost' ...
Error : Invalid DESCRIPTION file
Malformed package version.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
ERROR: installing package DESCRIPTION failed for package 'catboost'
* removing 'C:/Users/avgr/Documents/R/win-library/3.4/catboost'
Installation failed: Command failed (1)

> setwd ("C://Dropbox/tmp/catboost-master/catboost/R-package/")
> devtools::build()
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build "C:\Dropbox\tmp\catboost-master\catboost\R-package"  \
  --no-resave-data --no-manual 
* checking for file 'C:\Dropbox\tmp\catboost-master\catboost\R-package/DESCRIPTION' ... OK
* preparing 'catboost':
* checking DESCRIPTION meta-information ... ERROR
Malformed package version.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
Error: Command failed (1)

> devtools::install()
Installing catboost
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
"C:/Dropbox/tmp/catboost-master/catboost/R-package"  \
  --library="C:/Users/avgr/Documents/R/win-library/3.4" --install-tests 
* installing *source* package 'catboost' ...
Error : Invalid DESCRIPTION file
Malformed package version.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
ERROR: installing package DESCRIPTION failed for package 'catboost'
* removing 'C:/Users/avgr/Documents/R/win-library/3.4/catboost'
Error: Command failed (1)

**Comment by annaveronika** [comment]
Fixed!
