### ISSUE TITLE
how to save in csv file data what actually catboost uses for prediction

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#702]
Problem: { how to save in csv file data what actually catboost uses for predictoin, meaning I gave data then catboost aoutomatically converets data to it own format, so how to get this transorme data} 
catboost version: {latest}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by annaveronika** [comment]
CatBoost does feature quantization before training, which compresses numeric features.
We will provide an option to save quantized dataset into separate file and then allow the training to work with already quantized dataset.
This will speed up data preprocessing, which might be a bottleneck for GPU training.

As for preprocessing of categorical features - statistics that are calculated instead of categorical features, are calculated during training. Feature combinations are selected in a greedy way during training, so it cannot be done during preprocessing phase.

**Comment by Sandy4321** [comment]
great
1
"
We will provide an option to save quantized dataset into separate file and then allow the training to work with already quantized dataset"
So can now to save preprocessed data to csv file or it will be implemented in the future, so it is not available now?
2
 "statistics that are calculated instead of categorical features"
I need csv file not with "statistics that are calculated instead " but with categorical feature features
for example, if we have feature A with values " 0,1,2,3,4,5 then you create one hot encoding
for such are features
Do how to save to file data in this new format you create before calculating "statistics that are calculated instead of categorical features" 
Thanks for help

**Comment by annaveronika** [comment]
1 - this will be implemented in the future. There is also an issue about that, but I couldn't find it strait away.
2 - We don't create one-hot encoding, we use categorical features as is.

**Comment by Sandy4321** [comment]
thanks
1 - this will be implemented in the future. There is also an issue about that, but I couldn't find it strait away.
please let me know when it will be implemented?

**Comment by Sandy4321** [comment]
by the way, can catboost , at least ,  automatically  recognize if a feature is categorical or numerical
for example 
feature 1 has variables in   0,1,0,5,0,2, 0,2,1,2,5,1,1,1,2,2,2 will it be considers automatically as numerical integer with range from 0 to 5 or categorical?

**Comment by annaveronika** [comment]
No, we require the user to set categorical features, we don't select them automatically. The main reason for that is that it that some feature might be categorical, but look like numerical, for example some hashes. To be on the safe side, we decided to require this to be passed by user.

**Comment by annaveronika** [comment]
> thanks
> 1 - this will be implemented in the future. There is also an issue about that, but I couldn't find it strait away.
> please let me know when it will be implemented?

We don't have a plan jet for implementing this in close future. But we'll do it at some point, we'll update the issue https://github.com/catboost/catboost/issues/273 when it's done. I think you should follow that one if you're interested!

**Comment by Sandy4321** [comment]
No, we require the user to set categorical features, we don't select them automatically. The main reason for that is that it that some feature might be categorical, but look like numerical, for example some hashes. To be on the safe side, we decided to require this to be passed by user.
-------------------------------------------------------------------------------
So user should manually mark each feature is it is numerical of categorical?

**Comment by annaveronika** [comment]
Exactly, see examples in the docs: https://tech.yandex.com/catboost/doc/dg/concepts/python-quickstart-docpage/
There is parameter called cat_features, that you can use.

**Comment by Sandy4321** [comment]
I try to use your file for test from pytest folder
import yatest.common
from yatest.common import network, ExecutionTimeoutError, ExecutionError
import pytest
import os
import filecmp
import csv
import numpy as np
import time
import timeit
import json

bu thave error

le "e:\boosting like catbost xgboost\catboost\my_code_learn_catboost\pytest\test.py", line 1, in <module>
  import yatest.common

builtins.ModuleNotFoundError: No module named 'yatest'

**Comment by Sandy4321** [comment]
pi does not have yatest?
Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\boosting like catbost xgboost\catboost>pip install yatest
Collecting yatest
  Could not find a version that satisfies the requirement yatest (from versions: )
No matching distribution found for yatest
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

E:\boosting like catbost xgboost\catboost>

**Comment by annaveronika** [comment]
There is one issue https://github.com/catboost/catboost/issues/273 - please follow that one for further updates. Closing this one. I answered about yatest in other issue - it's not on pypi, and it's expected behavoir, that you run this file and it doesn't work. It will not work for any given python file.
If I understand correctly, what you want is examples of python code. You can find them in docs (https://tech.yandex.com/catboost/doc/dg/concepts/python-quickstart-docpage/, https://tech.yandex.com/catboost/doc/dg/concepts/python-usages-examples-docpage/) and in tutorials (for example, https://github.com/catboost/tutorials/blob/master/python_tutorial.ipynb)
