### ISSUE TITLE
what catboos doing with rows with NANs , can catboost not to delete rows  with NANs ?

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#703]
Problem: {what catboos doing with rows with NANs , can catboost not to delete rows  with NANs but some how to do classification just using nan as valid value. For example if there many nans in data?}
catboost version: {last}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by annaveronika** [comment]
CatBoost does not delete rows with nans. You can read about nan data handling here:
https://tech.yandex.com/catboost/doc/dg/concepts/python-data-mv-processing-docpage/

**Comment by Sandy4321** [comment]
thanks, so if we have 2 values for column "yes" and "no"
but there are many  NANs, then NAN will be used as third value?
for example

feature 1     feature 2    label
yes               yes                1
yes                no                1
no                 no                0
no                yes                1
what would be the prediction
for 
feature 1     feature 2    label
yes               NAN                ?

Thanks

**Comment by annaveronika** [comment]
Yes, you are right, it will be treated as a third value.

**Comment by Sandy4321** [comment]
great thanks for soon answer

**Comment by annaveronika** [comment]
no problem!
