### ISSUE TITLE
wrong CatBoost Viewer installation instractions

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#705]
Problem: {your page https://catboost.ai/docs/concepts/catboostviewer-installation.html#catboostviewer-installation sugests to click on  npm but this references to   broken link https://www.npmjs.com/package/nmp/tutorial.   So how to install needed soft for CatBoost Viewer for use for Python , if possble at all}
catboost version: {latest}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by annaveronika** [comment]
to use visualization from jupyter notebook you need to:
pip install ipywidgets
jupyter nbextension enable --py widgetsnbextension

After these two commands everything should work.
Or you want the stand alone visualiser?

**Comment by Sandy4321** [comment]
I want to try what is explained in this page, so it is mistaken page?
by the way, my previous question : how to save in csv file data what actually catboost uses for prediction
is ignored: does it means it is very difficult question or it is impossible to get inner data representation?
But it is the main catboost advantage advertised, that cat boos automatically preprocess data to get the best representation to categorical form?

**Comment by annaveronika** [comment]
Yes, the link in the docs doesn't work, we'll look into this. But we might stop supporting CatBoost Viewer as a separate tool soon, since jupyter notebook and tensorboard already cover everything.
Your other question I'll answer in the other issue. We didn't get to it jet.

**Comment by Sandy4321** [comment]
super thanks, I glad I helped to catboost team to find a bug, it is a great tool  and we can together make it even better

**Comment by annaveronika** [comment]
Yes, thanks a lot for the feedback!

**Comment by annaveronika** [comment]
We've removed this viewer from the docs, since it's not supported anymore.
