### ISSUE TITLE
how catboost deals with time-date features

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#706]
Problem: {if ther is columne with records  dates format like this :  2018/ jan/1 , 2018/ jan4, 2018/jan/20, 2018/jan3. When transorming data, is catboost convert this dates to days counting integer numbers like : 0, 4, 20, 3. And then using backets to creat new categorical fetures like 0,0,1, 3 for threshould equal to 10 days? }
catboost version: {latest}
Operating System: {W}indows
CPU: {i7}
# GPU: {GPU}

**Comment by Sandy4321** [comment]
last sentence should be like this
And then using buckets to create new categorical values like 0,0,1, 0 for threshold equal to 10 days?

**Comment by annaveronika** [comment]
We don't do any specific treatment for dates. We support only categorical features and numerical features, you should do the proprocessing that is suitable for your task for dates before passing them as numeric features or categories to the algorithm.

**Comment by Sandy4321** [comment]
I see, so by default date data like this 2018/Jan/6 will be considered as a string or categorical value?

**Comment by annaveronika** [comment]
Categorical values are actually strings. And the ones that are integers are treated in the following way: we convert them to strings first.

**Comment by annaveronika** [comment]
As I explained before we only support categorical and numerical features. No plan for other features, except for text features not. Closing the issue, because there is nothing to do from our side.
