### ISSUE TITLE
cannot use GridSearchCV or RandomSearchCV

### ISSUE THREAD

**Issue by akbaramed** [catboost/catboost#707]
Problem: {cannot use GridSearchCV or RandomSearchCV}
catboost version: {0.12.2}
Operating System: {Windows 10}
CPU: {intel i7-8550U, 16 GB RAM}

Hello,
I am using CatBoostRegressor in python 3.6 on Spyder

Normal use is working fine
print(categorical_feature_indicies )
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int64)
model = cb.CatBoostRegressor( iterations=5000,    learning_rate=0.01)
model.fit(X_train, y_train, cat_features=categorical_features_indices)
###################
but when using with Grid and Random Search and same dataset
#################
model = cb.CatBoostRegressor()
parameters = {'depth'         : [6,8,10],
                  'learning_rate' : [0.01, 0.05, 0.1],
                  'iterations'    : [30, 50, 100]
                 }
grid = GridSearchCV(estimator=model, param_grid = parameters, cv = 2, n_jobs=-1)
grid.fit(X_train, y_train,cat_features=categorical_features_indices)
##################
Keeps giving error - 
"<built-in method _train of _catboost._CatBoost object at 0x000002B4EB8C4AB0> returned a result with an error set"

Tried using 
RandomSearchCV 
Removed different parameters from the param_grid
Also cat codes the category variables and just used grid.fit(X_train, y_train), same error.

Can you please tell me what I am doing wrong.

Thanks

**Comment by annaveronika** [comment]
GridSearchCV doesn't have parameter cat_features. You should pass cat_features when init estimator.

**Comment by annaveronika** [comment]
model = cb.CatBoostRegressor(cat_features=[0,1,2])

**Comment by annaveronika** [comment]
@akbaramed  Does this solve your problem?

**Comment by david-waterworth** [comment]
I think you can also pass as `fit_params` to the fit method, i.e.

grid.fit(X_train, y_train,fit_params={'cat_features':categorical_features_indices})

**Comment by akbaramed** [comment]
Hello,

Many thanks for the reply.

@annaveronika got the same error using your suggestion. model = cb.CatBoostRegressor(cat_features = categorical_features_indices)
parameters = {'depth'         : [6,8,10],
                  'learning_rate' : [0.01, 0.05, 0.1],
                  'iterations'    : [30, 50, 100]
                 }
grid = GridSearchCV(estimator=model, param_grid = parameters, cv = 2, n_jobs=-1)
grid.fit(X_train, y_train)


even l tired using list(categorical_features_indices) as categorical_features_indices is a array

-----------------------------------------------------------------

@david-waterworth :  fit() got an unexpected keyword argument 'model__cat_features'

model = cb.CatBoostRegressor()
parameters = {'depth'         : [6,8,10],
                  'learning_rate' : [0.01, 0.05, 0.1],
                  'iterations'    : [30, 50, 100]
                 }
grid = GridSearchCV(estimator=model, param_grid = parameters, cv = 2, n_jobs=-1)
grid.fit(X_train, y_train, model__cat_features = categorical_features_indices)
---------------------------------------------------------------------------------------------------
Please suggest.

**Comment by david-waterworth** [comment]
@akbaramed  maybe try the syntax I crossed out?

grid.fit(X_train, y_train,fit_params={'cat_features':categorical_features_indices})

See: https://stackoverflow.com/questions/13051706/scikit-learn-using-sample-weight-in-grid-search

**Comment by akbaramed** [comment]
Hello,
@david-waterworth .
####### Approach 1 
model = cb.CatBoostRegressor(random_seed=42)
parameters = {'depth'         : [6,8,10],
                  'learning_rate' : [0.01, 0.05, 0.1],
                  'iterations'    : [30, 50, 100]
                 }
grid = GridSearchCV(estimator=model, param_grid = parameters, cv = 2)
grid.fit(X_train, y_train, **{'cat_features': list(categorical_features_indices)})

###### Approach 2
model = cb.CatBoostRegressor(random_seed=42, cat_features = categorical_features_indices)
parameters = {'depth'         : [6,8,10],
                  'learning_rate' : [0.01, 0.05, 0.1],
                  'iterations'    : [30, 50, 100]
                 }
grid = GridSearchCV(estimator=model, param_grid = parameters, cv = 2)
grid.fit(X_train, y_train)
#########################################
Both Approach 1 and 2 works
Only difference is I have removed n_jobs from the GridSearchCV function. So in short njobs=-1 was the problem.

**Comment by david-waterworth** [comment]
That seems correct to me, I always set njobs=1 when using sklearn as catboost creates it's own CPU and GPU threads, sorry I didn't notice that. Approach 2 is probably the clearer option although both should be equivalent.

**Comment by akbaramed** [comment]
@david-waterworth 
Thank you very much for the comments, really appreciate the support. Just last question. can you please advice on the parameters to use when using catboostregressor. There are so many of them. May be the top 5 or so parameters to get the most out of the algorithm or cover some important aspects of the catboost logic.

many thanks

**Comment by annaveronika** [comment]
We have tutorial on how to tune parameters: https://tech.yandex.com/catboost/doc/dg/concepts/parameter-tuning-docpage/
Please, take a look!

**Comment by akbaramed** [comment]
Many Thanks for the help @annaveronika  and @david-waterworth.
