### ISSUE TITLE
there is no explanations for greedy cauboost mode 

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#709]
Problem: {   this link showes table with greedy cauboost mode prediction 
 https://towardsdatascience.com/https-medium-com-talperetz24-mastering-the-new-generation-of-gradient-boosting-db04062a7ea2    but google search does not show explanatoins holw to use it, can you share link to tutorial and examples and description how to use it?  do you have one place list of all possible options?}
catboost version: {latest}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by annaveronika** [comment]
I think we have all the information in our documentation and tutorials - take a carefull look and you will find everything.

**Comment by annaveronika** [comment]
https://tech.yandex.com/catboost/doc/dg/concepts/educational-materials-papers-docpage/ - here is the list of papers that explain catboost functionality.
