### ISSUE TITLE
OS X build C API interface

### ISSUE THREAD

**Issue by NonaryR** [catboost/catboost#710]
- Hello! How can I build catboost evaluator for OS X? I'm following this [doc](https://catboost.ai/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper.html), but after executing this command
```
./ya make -r catboost/libs/model_interface/
```
I find in `catboost/libs/model_interface/` folder
```
catboostmodel.dSYM
libcatboostmodel.dylib
libcatboostmodel.dylib.1
```
files which is symlinks. 
I want to use `catboost_model/c_api.h` in include statement, how can I symlink those files?
- Catboost version: master
- Operating System: OS X

**Comment by NonaryR** [comment]
this is my workaround
```
git clone https://github.com/catboost/catboost.git
cd catboost
./ya make -r catboost/libs/model_interface/

cd catboost/libs/model_interface/
cp  libcatboostmodel.dylib.1 /usr/local/lib
ln -s /usr/local/lib/libcatboostmodel.dylib.1 /usr/local/lib/libcatboostmodel.dylib

mkdir /usr/local/include/catboost_model
cp c_api.h /usr/local/include/catboost_model/
```

**Comment by rbdm-qnt** [comment]
> this is my workaround
> 
> ```
> git clone https://github.com/catboost/catboost.git
> cd catboost
> ./ya make -r catboost/libs/model_interface/
> 
> cd catboost/libs/model_interface/
> cp  libcatboostmodel.dylib.1 /usr/local/lib
> ln -s /usr/local/lib/libcatboostmodel.dylib.1 /usr/local/lib/libcatboostmodel.dylib
> 
> mkdir /usr/local/include/catboost_model
> cp c_api.h /usr/local/include/catboost_model/
> ```

I'm having problems installing catboost aswell, I followed this, but still cannot get it to compile. What did you add to your makefile?
