### ISSUE TITLE
error for test files  from pytest folder

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#711]
Problem: {I try to use your file for test from pytest folder
import yatest.common
from yatest.common import network, ExecutionTimeoutError, ExecutionError
import pytest
import os
import filecmp
import csv
import numpy as np
import time
import timeit
import json

but have error

le "e:\boosting like catbost xgboost\catboost\my_code_learn_catboost\pytest\test.py", line 1, in 
import yatest.common

builtins.ModuleNotFoundError: No module named 'yatest'

pypy does not have yatest?
Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\boosting like catbost xgboost\catboost>pip install yatest
Collecting yatest
Could not find a version that satisfies the requirement yatest (from versions: )
No matching distribution found for yatest
You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

E:\boosting like catbost xgboost\catboost>}
catboost version: {latest}
Operating System: {Windows}
CPU: {i7}
# GPU: {GPU}

**Comment by annaveronika** [comment]
This is actually expected behavoir. These are libraries that are used in our test system, they are not on pypi.

**Comment by annaveronika** [comment]
So this is expected behavoir - these are libraries for testing, which are not on pypi. Thus I'm closing the issue.
