### ISSUE TITLE
logger interception

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#713]
I've implemented a catboost model in a docker container with the intention to deploy via sagemaker. I'd like to be able to log the catboost training and cross-validation in a format which can be parsed by sagemaker or a custom tensorboard. I'm using sklearn `cross_validate` rather than catboost, and I do a final fit. I'd like to be able to control the formatting on the catboost iteration logger so that a) it's the same format as the rest of my apps logging format, and b) I'd like to add additional info which allows sagemakers log parser to properly parse the iterations i.e. different chart for each cv fold and the final fit etc.

Ideally would be able to inject a logger into the CatBoostRegressor to allow formatting of messages rather than you write directly to stdout? That way could inject a tensorboard logger i.e. https://github.com/TeamHG-Memex/tensorboard_logger for inspiration? Or maybe simpler, pass in a format string?

**Comment by annaveronika** [comment]
Sorry for a long response! We don't plan for it jet. But we are welcoming contributions here.

As for tensorboard, catboost is also writing logs in tensorboard format, you can try using it.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
You may now specify custom logger via cout_log and cerr_log parameter in fit and other methods in classes CatBoost and Pool.
These parameters should be either streams, or functions taking log entry as parameter.
