### ISSUE TITLE
Unable to load R version

### ISSUE THREAD

**Issue by LandFarmer** [catboost/catboost#72]
I am unable to load Catboost in R - I have a win 64 version of R using the following command:
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package').
I receive the following message:

[ya.bat] Error: Python not found  make: *** [all] Error 1 Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2 ERROR: compilation failed for package 'catboost' * removing 'C:/Users/George/Documents/R/win-library/3.3/catboost' Installation failed: Command failed (1)

**Comment by exprmntr** [comment]
Hello,

It seems "Python not found" is a source of a problem, our build system requires python (and Visual Studio 2015 build tools for Windows, see #30)

**Comment by LandFarmer** [comment]
I do not use Python so which part of Python exactly do I need to load? This is the first time I have seen that Python is required to load an R package. Thanks.

**Comment by exprmntr** [comment]
Just interpreter, something like https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi (from https://www.python.org/downloads/release/python-2713/)

**Comment by LandFarmer** [comment]
Thanks for that, but still no luck. Pyphon downloaded into it's own
sub-directory.

I then ran:

devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')

The message I received was:

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/George/AppData/Local/Temp/Rtmp8WtNpz/devtools4b4058e21457/catboost-catboost-a18db8f/catboost/R-package/src/../../../ya.bat
make -r -o ../../..
2017-08-04T11:49:16.129000 [MainThread] Info: Attention! Using system
user-defined compiler: cl.exe (check CC and CXX env vars).
2017-08-04T11:49:16.131000 [MainThread] Info: will fetch 'YMake' from sandbox

Config was not generated due to errors in
C:\Users\George\AppData\Local\Temp\Rtmp8WtNpz\devtools4b4058e21457\catboost-catboost-a18db8f\build\ymake_conf.py
ERROR:root:Could not detect cxx compiler, error is [Error 2] The
system cannot find the file specified

Downloading http://storage.mds.yandex.net/get-devtools-opensource/373962/f919b31c76892a16618a97f0ebeac217
[..] OK
Downloading http://storage.mds.yandex.net/get-devtools-opensource/250854/312900269
[.............] OK
make: *** [all] Error 1
Warning: running command 'make --no-print-directory -f "Makefile.win"'
had status 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Users/George/Documents/R/win-library/3.3/catboost'Installation
failed: Command failed (1)


Still no luck. Thanks.










*Contact number +48 781 415 432**"In God we trust, all others bring data."*

**Comment by exprmntr** [comment]
Is Visual Studio installed? See #30

**Comment by LandFarmer** [comment]
I have installed Visual C++ 2015 Build Tools
<http://landinghub.visualstudio.com/visual-cpp-build-tools>. I get same
error message.

**Comment by BenjaminLott** [comment]
Any updates on this? I'm having the same problem and I'm slammed my head into the wall trying to figure this out.

**Comment by LandFarmer** [comment]
No not yet - I'm on the other side of the wall, also slamming my head.

**Comment by lidskidder** [comment]
same issue here, with two users of R studio:

Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'

Any ideas?

**Comment by BenjaminLott** [comment]
I have Cmake and possibly every version of visual studio and visual studio tools (all x64).  I currently feel like this is impossible to load this package.

**Comment by lidskidder** [comment]
One of our developers managed to get this installed and working yesterday. I'll post his step by step solution tomorrow.

**Comment by lidskidder** [comment]
As promised, please see below the steps to for manual installation of the catboost package which solved the problem for us:

1.	Install Git locally https://git-scm.com/download/
2.	Open Git Bash, and create directory to contain the Cat-Boost repository:
         mkdir Cat-Boost-Repo
3.	CD to new Cat-Boost repository and run the following commands to initialise git, get around proxy, and download Cat-Boost repository:
         git init
         git config --global http.proxy http://KID:PASSWORD@HOST:PORT  --replace KID and PASSWORD with your network logon credentials, replace HOST with the IP Address and PORT with the port number
        git clone https://github.com/catboost/catboost.git
4.	Install python 3.5 https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe (tick check box (install 3.5 to PATH))
5.	Install Visual Studio Community 2017 https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017
   I choose the Universal Windows Platform development and Desktop Development with C++ options under the ‘workloads’ tab, and also made sure the following were ticked under ‘individual components’
VC++ 2015.3 v140 toolset for desktop (x86,x64)
VC++ 2017 v141 toolset (x86,x64)
6.	From RStudio:
    a.	Tools->Check for Package Updates.
    b.	Run the following:-
         > setwd("H:/Cat-Boost-Repo/catboost/catboost/R-package")
         > install.packages('devtools')
         > devtools::build()
         > devtools::install()

**Comment by annaveronika** [comment]
Hope it works for you right now. Closing as resolved.
