### ISSUE TITLE
CatboostError: max ctr , spell error

### ISSUE THREAD

**Issue by shuiyuejihua** [catboost/catboost#720]
Problem: {small spell error, can be ignored}
catboost version: {0.12.2}
Operating System: {ubuntu}
CPU: {CPU}

>CatboostError: catboost/libs/options/cat_feature_options.cpp:265: Error: max ctr complexity should be less then 16

less then or less than?

**Comment by annaveronika** [comment]
Fixed in code, will be on pypi in next release. Thanks for pointing it out!
