### ISSUE TITLE
Backtracking type Armijo is supported only on GPU

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#722]
FYI, [documentation](https://catboost.ai/docs/concepts/python-reference_parameters-list.html) for `leaf_estimation_backtracking` states 

> Armijo — Reduce the descent step until the Armijo condition is met. Supported only on **CPU**.

But the validation in `catboost_options.cpp` says Supported only on **GPU**

    if (GetTaskType() == ETaskType::CPU) {
        CB_ENSURE(!(IsPairwiseScoring(lossFunction) && leavesEstimation == ELeavesEstimation::Newton),
                  "This leaf estimation method is not supported for querywise error for CPU learning");
        CB_ENSURE(
            ObliviousTreeOptions->LeavesEstimationBacktrackingType != ELeavesEstimationStepBacktracking::Armijo,
            "Backtracking type Armijo is supported only on GPU");
        CB_ENSURE(
            LossFunctionDescription->GetLossFunction() != ELossFunction::PythonUserDefinedPerObject
            || ObliviousTreeOptions->LeavesEstimationBacktrackingType == ELeavesEstimationStepBacktracking::No,
            "Backtracking is not supported for custom loss functions on CPU");
    }

**Comment by annaveronika** [comment]
Thanks a lot for pointing it out, we'll fix it soon!

**Comment by aprive** [comment]
Is this:
1. An error in documentation, or 
2. An error in the `catboost_options.cpp` file?

(I'd like to use the option on CPU)

**Comment by Noxoomo** [comment]
Hi!
it's an error in documentation,  Armijo is supported on GPU-only

**Comment by annaveronika** [comment]
This is fixed in docs now.
