### ISSUE TITLE
TQuantileError::CalcDer incorrect when target==approx

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#730]
TQuantileError::CalcDer is implemented as follows:

    double CalcDer(double approx, float target) const override {
        return (target - approx > 0) ? Alpha : -(1 - Alpha);
    }

What this means is when target == approx, instead of returning 0, alpha-1 is returned. The result is at the x which minimises L(x) the calculated derivative is not always zero.

I think this is probably more correct

    double CalcDer(double approx, float target) const override {
        double error = target - approx;
        if (error > -1e-6 && error < 1.0 + 1e-6) return 0.0;
        return (error > 0) ? Alpha : -(1 - Alpha);
    }

**Comment by annaveronika** [comment]
This change is implemented in the latest version, thank you very much!
