### ISSUE TITLE
Custom metrics in GPU training

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#736]

**Comment by StatMixedML** [comment]
Any update on this? Would be great to have GPU support for custom evaluation metric

**Comment by annaveronika** [comment]
No progress on that. But I suggest to use eval_metrics method or staged_predict method to calculate the custom loss after the training has finished.

**Comment by andrey-khropov** [comment]
Duplicate of #1792 (closing this issue because that issue has more activity).

**Comment by andrey-khropov** [comment]
#1792 is about callbacks. User-defined objectives and losses have been implemented in https://github.com/catboost/catboost/commit/14ef09c08cddbf72c1d3e121239140c36eaffe4d.
