### ISSUE TITLE
fold_permutation_block_size bug

### ISSUE THREAD

**Issue by antipisa** [catboost/catboost#739]
catboost version: 0.11
Operating System:Unix
CPU
The parameter fold_permutation_block_size does not work. It gives the error

```
from catboost import CatBoostRegressor, Pool
params = {"boosting_type":"Ordered", "num_boost_round":100, "fold_permutation_block_size":50}
model = CatBoostRegressor(**params)
model.fit(Pool(X,label=y))
```
**`CatboostError: catboost/libs/options/plain_options_helper.cpp:272: Error:unknown option fold_permutation_block_size with value 50`**

**Comment by annaveronika** [comment]
Thanks a lot for reporting this issue! This is a bug, we'll fix it.

**Comment by nikitxskv** [comment]
@antipisa Hi!
It is the bug in the python-package and documentation. Now we fixed it.
Try to be update, rebuild CatBoost and try again with a parameter name `fold_permutation_block`.
