### ISSUE TITLE
Не работает ya make

### ISSUE THREAD

**Issue by GoldenMan123** [catboost/catboost#74]
Скачал репозиторий, запустил "../../ya make -r" в "catboost/catboost/app". Висит бесконечно долго при попытке выкачать рекурс из сэндбокса.

Выхлопы:
Downloading http://storage.mds.yandex.net/get-devtools-opensource/373962/f919b31c76892a16618a97f0ebeac217 [..] OK
Downloading http://storage.mds.yandex.net/get-devtools-opensource/233854/312900358 [........................] OK
Info: will fetch 'YMake' from sandbox

Правильно, откуда у внешних юзеров доступ к сэндбочным ресурсам?))

**Comment by exprmntr** [comment]
Этот ya не должен ходить в сандбокс, ресурсы он скачивает из http://storage.mds.yandex.net/get-devtools-opensource/

Просьба показать выхлоб `ya -v make -v -r`

**Comment by GoldenMan123** [comment]
[build.log.txt](https://github.com/catboost/catboost/files/1195115/build.log.txt)

**Comment by GoldenMan123** [comment]
Я смотрю, что уже собирается. Вчера и на CI была сборка сломана.
