### ISSUE TITLE
IndexError in Pool.get_baseline

### ISSUE THREAD

**Issue by polezhaev-ds** [catboost/catboost#740]
catboost version: 0.13.1
Operating System: Windows 10
CPU
Python 3.6.4
numpy 1.15.2

I got exception **"IndexError: too many indices for array"**

 for call of get_baseline() of Pool object
It can be easily reproduced by your 
[example](https://catboost.ai/docs/concepts/python-reference_pool_set_baseline.html)

```
IndexError                                Traceback (most recent call last)
<ipython-input-65-644a2f0f70de> in <module>()
----> 1 input_pool.get_baseline()

_catboost.pyx in _catboost._PoolBase.get_baseline()

_catboost.pyx in _catboost._PoolBase.get_baseline()

IndexError: too many indices for array

```

**Comment by annaveronika** [comment]
Thanks a lot for reporting this. We'll fix this and update pypi version.

**Comment by nikitxskv** [comment]
@polezhaev-ds Hi!
Now we fixed it.
Try to update, rebuild CatBoost and try again.
