### ISSUE TITLE
PAIRWISE RANKING

### ISSUE THREAD

**Issue by anuragreddygv323** [catboost/catboost#741]
In pairwise ranking, If i create a pool using

pool1 = Pool(data=features, label= relavance, group_id=group_id, pairs=pairs)

I want to create the pairs because I have features which are interaction features between two documents which I am trying to rank. For example, text similarity between Doc1 and Doc2.
I cant use the default option of letting catboost create the pairs.

Is creating a pool using the above code is correct ?
Features will be { document 1 features, Document 2 features, interaction features between docmument 1 and document2 }

If done like this will the model learn the probabilty of Doc 1 > Doc 2 ? or Doc1 and Doc2 relavance scores seperately ?

If I get doc1 > doc2, then I have to use some sorting algorithm to re rank the results right ? Hence, I want to know if it gives probabilty of (Doc 1 > Doc 2) or Doc1 and Doc2 relavance scores seperately ?

**Comment by anuragreddygv323** [comment]
@annaveronika  could you answer this ?

**Comment by annaveronika** [comment]
If you want interaction features, then you should have labels 0 and 1 and run binary classification to predict probability of first doc being more relevant then second.
For the pairwise mode each line contains only features for a single document.

Sorry for a delayed answer!
