### ISSUE TITLE
get_feature_importance is broken

### ISSUE THREAD

**Issue by Masterming** [catboost/catboost#745]
Problem: 
When calling get_feature_importance on the model I get an error " AttributeError: 'dict' object has no attribute 'type' ". from line 1650 of catboost\core.py.

Example code:
import numpy as np
from catboost import CatBoostClassifier
model = CatBoostClassifier(iterations=5, depth=5, learning_rate=1, loss_function="Logloss")
x = np.random.randint(2, size=(10,10))
y = np.random.randint(2, size=(10))
model.fit(x, y)
arr = model.get_feature_importance()

catboost version: 0.13.1
Operating System: Win 10

**Comment by Sandy4321** [comment]
I do not have error for this on windows 10
catboost version  0.9.1.1
catboost installed by conda
https://catboost.ai/docs/installation/python-installation-method-conda-install.html
but I do have many other errors for valid catboost methods 
please see issue 
https://github.com/catboost/catboost/issues/746

![image](https://user-images.githubusercontent.com/11426119/55039107-500d2300-4ff9-11e9-91e7-86bc354561ae.png)

**Comment by david-waterworth** [comment]
@Sandy4321 the latest catboost version is 0.13.1 so you're way out of date, as the documentation isn't (as far as I know) versioned it's no surprise you're seeing differences in behaviour from 0.9.1.1 and the 0.13.1 documentation?

@Masterming I see the same thing with 0.13.1 (which was the release which was supposed to fix get_feature_importance)

**Comment by Masterming** [comment]
Yes, I can confirm that the problem showed up only after a recent upgrade.

David Waterworth <notifications@github.com> schrieb am Mi., 27. März 2019,
00:19:

**Comment by Sandy4321** [comment]
by the way how you installed 
I do have only 0.9.1.1 what I got recently  from 
https://catboost.ai/docs/installation/python-installation-method-conda-install.html
conda install catboost
did you used pip?
do yo have many errors what I have for 
https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb
as written in 
https://github.com/catboost/catboost/issues/746

**Comment by Sandy4321** [comment]
@david-waterworth 
thanks but I have catboost both conda and pip installed 
before I use
pip install --upgrade catboost
should I uninstall conda installed catboost 
catboost                  0.9.1.1                  py36_1    conda-forge
and how?

**Comment by Sandy4321** [comment]
by the way as written above maybe
catboost 0.9.1.1 
is better than
catboost version: 0.13.1
though I do have many other errors in tutorials

**Comment by david-waterworth** [comment]
@Sandy4321 I'll reply to your original issue to avoid hijacking this one

**Comment by Sandy4321** [comment]
I updated catboost and now have this bug as well
![image](https://user-images.githubusercontent.com/11426119/55041357-10e3cf80-5003-11e9-9423-93af3676a920.png)

**Comment by Sandy4321** [comment]
what can be done?

**Comment by Masterming** [comment]
It is a bug. You as a user cant do anything except reporting the bug and going to an earlier version if you need that method.

**Comment by annaveronika** [comment]
This is a bug, we are working on it right now, we'll publish a version with a fix soon.

**Comment by Sandy4321** [comment]
will you know us , when new version is ready?

**Comment by Sandy4321** [comment]
how long it usually takes to fix this kind of bugs?

**Comment by Sandy4321** [comment]
what exactly should I to do to uninstall this latest version and install version without bug?

**Comment by Masterming** [comment]
As long as you have catboost installed by pip you only need to use the following command to return to a earlier version: pip install -U catboost==0.12.2

**Comment by Sandy4321** [comment]
great thanks, by the way why 0.12.2 and not 0.13.0
is 0.12.2 most stable version?

**Comment by kizill** [comment]
> how long it usually takes to fix this kind of bugs?
We are prepearing for next big realease 0.14, stay tuned. I hope it'll be ready in days.

**Comment by annaveronika** [comment]
This is fixed now. You can build from source or wait for our next release, which will happen tomorrow.
