### ISSUE TITLE
catboost installed by both pip and conda, is it problem

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#748]
Problem: {
I did not mention that you run line
!pip install -q numpy pandas catboost hyperopt scikit-learn frozendict matplotlib
in tutorial
https://github.com/catboost/tutorials/blob/master/classification/classification_with_parameter_tuning_tutorial.ipynb
previously I installed catboost by conda 
So now I have 2 catboost instalaltions
pip list
catboost                           0.9.1.1
conda list
catboost                  0.9.1.1                  py36_1    conda-forge

do I have now contradiction between 2 installations?
which one to uninstall and how?
and may it be problem of very strange error
![image](https://user-images.githubusercontent.com/11426119/55039591-26ed9200-4ffb-11e9-8100-1c878b3def8e.png)
for this tutorial code 
https://github.com/catboost/tutorials/blob/master/classification/classification_with_parameter_tuning_tutorial.ipynb

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a92456d7def9> in <module>()
      1 # We are going to use UCI Adult Data Set because it has both numerical and categorical
      2 # features and also has missing features.
----> 3 print(cbd.adult.__doc__)

AttributeError: module 'catboost.datasets' has no attribute 'adult'

![image](https://user-images.githubusercontent.com/11426119/55039412-6798db80-4ffa-11e9-8978-6bbbed9fbb8c.png)

}
catboost version: {0.9.1.1}
Operating System: {Windows}
CPU: {CPU}
# GPU: {GPU}

**Comment by david-waterworth** [comment]
They both seem to be the same version from different packages (since conda appears to repackage the PyPI package). I'd remove both and reinstall the specific version you need.

**Comment by annaveronika** [comment]
I don't think there is anything we can help on catboost side except for an advice above. So closing the issue.

**Comment by omshri29** [comment]
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

I am having above error, i tired reinstalling catboost, downgrade upgrade numpy, rebooting jupyter notebook. kind not solving it .

**Comment by omshri29** [comment]
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
> 
> I am having above error, i tired reinstalling catboost, downgrade upgrade numpy, rebooting jupyter notebook. but no resolutions .

It got solved by upgrading numpy and than rebooting the notebook from conda command line
