### ISSUE TITLE
tutorial error: roc_auc = sklearn.metrics.auc(fpr, tpr)

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#750]
Problem: {
tutorial 
https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb

gives error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-acef3ffd36e3> in <module>()
      6 curve = get_roc_curve(model, eval_pool)
      7 (fpr, tpr, thresholds) = curve
----> 8 roc_auc = sklearn.metrics.auc(fpr, tpr)

~\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py in auc(x, y, reorder)
     97             else:
     98                 raise ValueError("Reordering is not turned on, and "
---> 99                                  "the x array is not increasing: %s" % x)
    100 
    101     area = direction * np.trapz(y, x)

ValueError: Reordering is not turned on, and the x array is not increasing: [0.     0.     0.     ... 0.9948 0.9974 1.    ]

![image](https://user-images.githubusercontent.com/11426119/55042533-463eec00-5008-11e9-82df-933d03e3d698.png)

}
catboost version: {0.13.1}
Operating System: {windows}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
Thanks a lot for reporting this! We've fixed this in code, you can build from source now to get correct behavoir, or wait for our next release, which will happen tomorrow.
