### ISSUE TITLE
absents of detailed technical description (not paper what is more theoretical )  of the algorithm

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#751]
Problem: {absents of detailed technical description (not paper what is more theoretical )  of the algorithm
do you have more detailed description of an algorithm , better with code examples 
infirst view in this direction
https://www.youtube.com/watch?v=db-iLhQvcH8&feature=youtu.be
Liudmila Prokhorenkova: «CatBoost: unbiased boosting with categorical features»
especially how main ideas expressed in practical results 
very interesting (mentioned in video many times including questions) variables combining 
It is pitty, catboost is great, but the shortage of description prevents from proper use
 }
catboost version: {latest}
Operating System: {windows}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
There are several descriptions with different level of detalisation and amount of theory. https://catboost.ai/docs/concepts/educational-materials-papers.html - here is the list of papers. The first one is more theoretical, the second one is more technical, this is probably what you need.

**Comment by annaveronika** [comment]
The second paper is what you need. I hope it solves the problem. Closing the issue.
