### ISSUE TITLE
Getting error while predicting value of Y contain categorical features 

### ISSUE THREAD

**Issue by shubhammishra93** [catboost/catboost#752]
Problem: unable to predict the Y contain categorical features using catboost algorithm
catboost version: 0.13.1
Operating System: Windows 10
CPU: {CPU}
# GPU: {GPU}

**Comment by shubhammishra93** [comment]
The error while predicting Y is these

CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/target/target_converter.cpp:53: Target value "critical" cannot be parsed as float

**Comment by annaveronika** [comment]
Could you please provide a minimal repruducing example? Toy data + code that you are running.

**Comment by annaveronika** [comment]
My best guess is that you are using string labels in CatBoostRegressor, where you need to have floating point target values.

**Comment by annaveronika** [comment]
Closing the issue because of inactivity. Let us know if our answer doesn't solve your problem.
