### ISSUE TITLE
save_model to cpp generates faulty code

### ISSUE THREAD

**Issue by jlongva** [catboost/catboost#753]
Problem: 

When saving av model to cpp, the Borders array is generated as follows:

float Borders[408] = {3295.5f, 3315.5f, ..., 7.5f, 21f};
(I've exluded some values)

The last value "21f" is not legal in C++. It generates this error:

error: unable to find numeric literal operator 'operator"" f'

It should be "21.f" or "21.0f".

Solution: always make sure the generated code includes the required decimal separator, even if the number is a whole number.

catboost version: 0.13.1
Operating System: Windows 10
CPU: Intel I9

**Comment by annaveronika** [comment]
Thanks a lot for reporting this! We'll fix it soon.

**Comment by annaveronika** [comment]
The fix is on github now, you can try building from source. It will be on pypi in todays release.
