### ISSUE TITLE
where to read about each new relese details

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#754]
Problem: {

where to read about each new relese details : what is new
on https://pypi.org/project/catboost/0.13.1/
no details
for exampel 0.13.1 haw bug for features , so it needs to know how it is different from 13.0
}
catboost version: {13.1}
Operating System: {Windows}
CPU: {CPU}
# GPU: {GPU}

**Comment by david-waterworth** [comment]
https://github.com/catboost/catboost/releases

**Comment by Sandy4321** [comment]
thanks
