### ISSUE TITLE
Need tutorial/documentation/samples about custom metrics for CatBoostRegressor

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#756]

**Comment by LyzhinIvan** [comment]
Hi, @AndreyGurevich ! The tutorial is available now: https://github.com/catboost/catboost/blob/master/catboost/tutorials/custom_loss/custom_loss_and_metric_tutorial.ipynb

**Comment by AndreyGurevich** [comment]
Great, thank you!
