### ISSUE TITLE
Plot saving into file

### ISSUE THREAD

**Issue by vchulski** [catboost/catboost#758]
Code below generate cool interactive graph: 

`CatBoostClassifier().fit(X_train, y_train,eval_set=(X_valid, y_valid),plot=True);`

But after notebook is rendered it disappear. 
I am asking to add option this graph could be saved into a file.

**Comment by fingoldo** [comment]
it's a plotly object, it seems. could we have some access to it, or maybe there is a way to access it from a callback?

**Comment by DanRamage** [comment]
I develop in PyCharm, not Jupyter Notebooks. I'd really like to be able to save the plots/trees/visualizations to file.
