### ISSUE TITLE
PEERDIR to missing directory: $S/contrib/libs/nvidia/cudalib

### ISSUE THREAD

**Issue by novikovmikhail** [catboost/catboost#76]
I added .cu file in catboost/catboost/libs/algo folder and in ya.make file in it. Then i tried to create .whl file:

~/catboost/catboost/python-package$ python mk_wheel.py 
/usr/bin/python /home/dilim/catboost/ya make /home/dilim/catboost/catboost/python-package/catboost --no-src-links -r --output /tmp/tmp0SaHqU -DUSE_ARCADIA_PYTHON=no -DPYTHON_CONFIG=python-config -DNO_DEBUGINFO
Error[-WBadDir]: in $S/catboost/libs/algo/ya.make: PEERDIR to missing directory: $S/contrib/libs/nvidia/cudalib
Configure error (use -k to proceed)
Traceback (most recent call last):
  File "mk_wheel.py", line 112, in <module>
    wheel_name = build(arc_root, out_root, sys.argv[1:])
  File "mk_wheel.py", line 76, in build
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/dilim/catboost/ya', 'make', '/home/dilim/catboost/catboost/python-package/catboost', '--no-src-links', '-r', '--output', '/tmp/tmp0SaHqU', '-DUSE_ARCADIA_PYTHON=no', '-DPYTHON_CONFIG=python-config', '-DNO_DEBUGINFO']' returned non-zero exit status 1

Can you, please, add the necessary files for cuda support?

**Comment by exprmntr** [comment]
Hi @novikovmikhail, 

Sure, we are working on it right now

**Comment by annaveronika** [comment]
MATRIXNET-904

**Comment by annaveronika** [comment]
We added cuda support
