### ISSUE TITLE
Crash on predict_proba() predict()

### ISSUE THREAD

**Issue by Enggarin** [catboost/catboost#760]
Problem: {CB goes to crash (without any logg for jupyter) if u send not valid data (like None).} 
catboost version: {0.13.1} 
Operating System: {Win10}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
@Enggarin Could you please provide a minimal reproducing example?

**Comment by Enggarin** [comment]
X_test = None (as example)
Y_test = model.predict_proba(X_test, thread_count=-1, verbose=True)
Jupiter said - "The kernel appears to have died. It will restart automatically.", and no any Logs.
Ye, thats stupid mistake, but it can be happened some times for lazy and insensitive users.

**Comment by annaveronika** [comment]
Thanks for reporting! We'll fix this.

**Comment by annaveronika** [comment]
The code for the fix is on github now, you can build from source or wait for our next release. We plan to do it today or tomorrow.
