### ISSUE TITLE
QueryCrossEntropy CPU unclear error log

### ISSUE THREAD

**Issue by BraginIvan** [catboost/catboost#762]
Problem: unclear error log
catboost version: 0.13.1
Operating System: Ubuntu
CPU: intel i5 8th
Currently QueryCrossEntropy is not supported on CPU, but the log error looks like I have to change the leaf estimation method 

> This leaf estimation method is not supported for querywise error for CPU learning
https://github.com/catboost/catboost/blob/master/catboost/libs/options/catboost_options.cpp#L432

If I set  'leaf_estimation_method':'Gradient' the error is:

> Gradient leaf estimation is not supported for QueryCrossEntropy

So the only problem is the log error that should have stopped me on the first attempt, something like "QueryCrossEntropy is not supported on CPU"

**Comment by annaveronika** [comment]
This is fixed now in code. You can build from source or wait for our next release, which will happen tomorrow.
