### ISSUE TITLE
ImportError: cannot import name 'CV' from 'catboost'

### ISSUE THREAD

**Issue by Sasirekha123** [catboost/catboost#764]
ImportError                               Traceback (most recent call last)
<ipython-input-1-4698fe1d1c9f> in <module>
     35 from sklearn.linear_model import LinearRegression, LogisticRegression, SGDClassifier
     36 from sklearn.tree import DecisionTreeClassifier
---> 37 from catboost import CatBoostClassifier, Pool, CV
     38 
     39 #lets be rebels and ignore warnings for now

ImportError: cannot import name 'CV' from 'catboost' (C:\Users\ssss\Anaconda3\lib\site-packages\catboost\__init__.py)

**Comment by annaveronika** [comment]
it's lower case

**Comment by annaveronika** [comment]
This should definitely fix the problem. Closing the issue, let us know if you have any further questions!

**Comment by Sasirekha123** [comment]
Thank you so much Annaveronika.
