### ISSUE TITLE
Provide custom folds splitting for catboost.cv()

### ISSUE THREAD

**Issue by takiholadi** [catboost/catboost#765]
Please support custom splitting indices. For example, it needs for time series splitting strategies.

**Comment by Sandy4321** [comment]
by the how folders are generated: is it possible to set minumum size of fold, then folders overlapping will be possible to provide   many folders?

**Comment by david-waterworth** [comment]
+1 I would like to see this as well, our models are based on time series data and kfold doesn't very well with autocorrelation.

**Comment by annaveronika** [comment]
We plan to add both - time series split and possibility to use custom folders. But we have not started on that yet. We'll let you know.

**Comment by annaveronika** [comment]
We've added custom splits and time series splits in catboost 0.16.2 and 0.16.3

**Comment by annaveronika** [comment]
Documentation is here:
https://catboost.ai/docs/concepts/python-reference_cv.html

Example notebook is here:
https://github.com/catboost/tutorials/blob/master/cross_validation/cv_tutorial.ipynb
