### ISSUE TITLE
CatBoostRanker class in Python

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#766]
XGBoost and LightGBM have sklearn interfaces for ranking, we should also introduce one.

xgboost.XGBRanker
lightgbm.LGBMRanker

**Comment by annaveronika** [comment]
@imatiach-msft 
> how would one know that it is a ranker specifically
You need to look on the loss_function parameter value and check if it's a ranking objective.

**Comment by andrey-khropov** [comment]
Released in 0.26.
