### ISSUE TITLE
Interpretation of feature importance

### ISSUE THREAD

**Issue by Rajat700** [catboost/catboost#767]
Problem: {I trained a regression model using catboost and by looking at the feature importance when I am changing the input of the 4th important feature then their is no change on the target variable. How should I interpret this behaviour of the model}
catboost version: {0.12.1.1}
Operating System: {Linux}
CPU: {CPU}

**Comment by annaveronika** [comment]
This probably means that you have changed the feature by a small value.
In GBDT there is a set of borders that are used in splits of the trees. If you change the feature in a way that no split has changed its value, then nothing will change.

**Comment by Rajat700** [comment]
Okay I understood your point. Thanks for the explanation.

Is it possible to extract those set of borders of different features that are used in splits of the trees.

**Comment by annaveronika** [comment]
Yes, you can use output_borders parameter in training. Starting from next release (which will be in a few days) there will be also a new method save_borders(). You can use it now if you build from source.

**Comment by Rajat700** [comment]
Okay thanks for the explanation. I think that I have got my answers so I am closing this issue for now.

**Comment by Rajat700** [comment]
I am reopening this issue because I am unable to pass output_borders parameter in Catboost Regressor. When I am passing this parameter I am getting an error
![catboost](https://user-images.githubusercontent.com/23118255/55644306-291dd080-57f3-11e9-961d-13acae688d58.png)

I also upgraded to  catboost version '0.13.1'

**Comment by annaveronika** [comment]
Thanks for the report! This is fixed now, you can try building from source or wait for our next release 0.14 which will be out today or tomorrow.
