### ISSUE TITLE
Suggestion for using staged prediction to improve MAPE in regression

### ISSUE THREAD

**Issue by Rajat700** [catboost/catboost#769]
Problem: Can anyone suggest me what is the  use of staged prediction functionality of catboost?
Is it possible to use staged prediction to improve MAPE in case of regression ?

Thanks in advance

catboost version: {0.12.1.1}
Operating System: {Linux}
CPU: {CPU}

**Comment by annaveronika** [comment]
MAPE is implemented as a metric, so you don't have to use staged prediction, you can use eval_metrics instead.

**Comment by Rajat700** [comment]
Okay thanks for the explanation. I got my answers.

I am closing this issue now.
