### ISSUE TITLE
Plot problem, python package

### ISSUE THREAD

**Issue by Ciroel** [catboost/catboost#77]
If I use `plot = True` in `.fit` method it always plot the previous `.fit` results (with previous n_iterations, metric, etc.). Is it ok?
In order to fix it i have to remove catboost files in folder before each `.fit` call.

**Comment by annaveronika** [comment]
MATRIXNET-916

**Comment by annaveronika** [comment]
Actually this should not happen. Are you using snapshots? Could you provide screenshot of how this behavoir looks like?

**Comment by nikitxskv** [comment]
@Ciroel Hello!
Thank you for report!
This bug should be fixed in the last version.
