### ISSUE TITLE
how to find class 0 for class_weights

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#771]
Problem: { if I have lables yes and no in labale then how to set class_weights, which class is 0 : yes or no}
catboost version: {latest}
Operating System: {windows }
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
There is classes_ property which contains class names in the order in which classes appear in predictions and in class_weights.

**Comment by annaveronika** [comment]
It is not yet in documentation, but it will be there soon - it is currently in testing version of docs.

**Comment by annaveronika** [comment]
This should help, closing the issue. Let us know if this doesn't work. Note that the feature is there starting from 0.13.
