### ISSUE TITLE
is it mistake in tutorial pydata_moscow_oct_13_2018: parameter Class_weights is not used, when data is unbalansed?

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#775]
Problem: {still  it is not clear how to  use catboost for inbalanced data : https://stackoverflow.com/questions/54437646/catboost-precision-imbalanced-classes  (CatBoost precision imbalanced classes) how to find    a clear code example,
for example from this  video 
![image](https://user-images.githubusercontent.com/11426119/55752993-492dd980-5a17-11e9-8f18-93ab719419b8.png)

data is inbalanced but model  trained as for  balanced data https://www.youtube.com/watch?v=xl1fwCza9C8&t=44s  code https://github.com/catboost/tutorials/blob/master/events/pydata_moscow_oct_13_2018.ipynb
![image](https://user-images.githubusercontent.com/11426119/55752774-c73db080-5a16-11e9-8c59-61e50459827d.png)

}
catboost version: {version}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
There is no correct answer for this question. For unbalanced data you can try reweighting your samples or making oversampling. To use reweighting you can use weights, where you set weight for every sample, or you can use class weights. See documentation and tutorials for examples of how to set these parameters.

**Comment by annaveronika** [comment]
The answer to the question in the name of the issue "is it mistake in tutorial pydata_moscow_oct_13_2018: parameter Class_weights is not used, when data is unbalansed?" is no, it is not a mistake. It is not obligatory to use class weights if your dataset is not balanced. For the dataset that we were using in the tutorial setting class weights doesn't improve quality. It might improve quality in other cases.
