### ISSUE TITLE
 CatBoost does not work with servers on Hyper-V

### ISSUE THREAD

**Issue by VladislavLecter** [catboost/catboost#78]
Здравствуйте! Вкратце опишу ситуацию, с которой столкнулся и уже довольно долго не могу решить.
Что имеем:
- Anaconda3 x64
- catboost v 0.1.1.6
- VDS Server 2012R (перепробовал разные, в т.ч. 2008, 2016)
- Обученную модель средствами Catboost

Модель обучалась на Windows 7, Windows 10 (домашняя версия, не серверная), после чего возникла необходимость запустить predict этой обученной модели на 2012R, и тут самое интересное - происходит краш кернела (оболочки) и никакие альтернативные способы запустить predict не помогают. 

Пример: 
загружаю модель:
model = CatBoost(model_file='SomeModel')

создаю список:
X = np.array([ 22. , -98. , 99.38, 98.89], ndmin=2)

И после этого хочу проверить результаты предсказания:
pred = model.predict(X)

И после запуска model.predict происходит краш. 
Причем при проверке на Linux, MacOS, Windows (home) все работает прекрасно.
Помогите разобраться, пожалуйста.

**Comment by Donskov7** [comment]
@VladislavLecter а модель обучалась на той же версии catboost (v 0.1.1.6)?

**Comment by VladislavLecter** [comment]
@Donskov7 да, конечно, все было написано и обучено на одной версии catboost

**Comment by annaveronika** [comment]
@VladislavLecter Can you still reproduce your error with the last version of the library?

**Comment by VladislavLecter** [comment]
@annaveronika now after upgrate lib when i try call 'model = CatBoostRegressor()' 
crash happens before to make a prediction :(

**Comment by annaveronika** [comment]
What exactly is the scenario? You pip install catboost on VDS Server 2012R and it crashes after "model = CatBoostRegressor()" ?

**Comment by VladislavLecter** [comment]
@annaveronika yes, kernel crashes after "model = CatBoostRegressor()"

**Comment by annaveronika** [comment]
Can you try building from source?

**Comment by VladislavLecter** [comment]
@annaveronika Yes, I tried, but nothing happened. I can provide you access to the server that you check on their own and helped to set up. 
Your library is very important to me

**Comment by VladislavLecter** [comment]
@annaveronika  can close the issue. It turned out that the library does not work with servers on Hyper-V

**Comment by kizill** [comment]
@VladislavLecter we've fixed this bug in commit e50df64, can you try to build from master and test it?
