### ISSUE TITLE
Is it possible to give weightage to a feature ?

### ISSUE THREAD

**Issue by Rajat700** [catboost/catboost#784]
Problem: {I am training a regression model using Catboost in which I am getting good MAPE but there is a categorical feature in my data which is coming at the top of feature importance data. My question is whether it is possible to reduce the weightage of that categorical feature so that its importance decreases but the MAPE more or less remains the same }
catboost version: {0.12.1.1}
Operating System: {Linux}
CPU: {CPU}

**Comment by david-waterworth** [comment]
This is something I've considered as well. I have correlated features temperature and time-of-day/day-of-week, month-of-year etc, with target being electricity demand. I want to preference temperature over time features as much as possible as that makes the model more general (i.e. the time features are really proxies for features I don't have data for)

I've considered a nest model, fit one model first using just temperature, then fit a 2nd model to the residuals for the first using all features.

Catboost has the ability to start training from a non-zero starting point - https://tech.yandex.com/catboost/doc/dg/features/proceed-training-docpage/#proceed-training

Not sure that helps?

**Comment by Rajat700** [comment]
Okay David  thanks for the advice. I will try this and see if this works. For now I am closing this issue.

Thanks a lot David and AnnaVeronika for your suggestions.

I am closing this issue for now.
