### ISSUE TITLE
Predict on a single object with iloc

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#785]
> `catboost.__version__`

 '0.14.0'

> type(X_train.iloc[25])

pandas.core.series.Series
>model.predict(X_train.iloc[25])

...
catboost/libs/data_new/model_dataset_compatibility.cpp:143: Feature txt_tfidf_1 is present in model but not in pool.

works fine with 
>model.predict( [ X_train.iloc[25] ] )

**Comment by feeeper** [comment]
I'm going to work on that issue

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!
