### ISSUE TITLE
CMD fit run CTR error

### ISSUE THREAD

**Issue by ElSurycat** [catboost/catboost#786]
Hi!

Problem: 
I try to use cmd built version, during first time running the fit function I get error, so full result:

<..>Catboost\bin>catboost-0.14.0 fit --learn-set train.tsv --test-set test.tsv --column-description train.cd
AN EXCEPTION OCCURRED. ??+0 (0x1404A98EC)
??+0 (0x1400C4A9E)
??+0 (0x14077DCAD)
??+0 (0x1407AD125)
??+0 (0x1407AD4DB)
??+0 (0x1401122E7)
??+0 (0x1400E7E57)
??+0 (0x14046E778)
??+0 (0x140567E5B)
??+0 (0x140565B6A)
??+0 (0x140565502)
??+0 (0x140466842)
??+0 (0x1413B7750)
BaseThreadInitThunk+20 (0x7FF922DA1FE4)
RtlUserThreadStart+33 (0x7FF923E6CB31)

(class TCatBoostException) c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/target/data_providers.cpp:446: CTR features require Target data

I've taken test data from the Catboost Jupyter tutorial. So, the questions are:
- is this set of data valid to run in cmd version of the Catboost?
- are these parameters enough for running fit function?

catboost version: 0.14.0
Operating System: Win10
CPU: i7-4770

**Comment by annaveronika** [comment]
Please write here what is in your train.cd file, and please write number of columns in train.tsv and test.tsv

**Comment by ElSurycat** [comment]
I have 10 columns in train.tsv and test.tsv with comma delimeter and header.
Attached train.cd as train.cd.txt
[train.cd.txt](https://github.com/catboost/catboost/files/3080389/train.cd.txt)

**Comment by annaveronika** [comment]
There is no Label column in train dataset and test dataset. Optimized objective requires Label (Target) column to be present in your dataset. Otherwise training cannot be done.

**Comment by annaveronika** [comment]
Label column should be written in your cd file.

**Comment by ElSurycat** [comment]
Thanks a lot! Now it works.
