### ISSUE TITLE
Are SKLEARN API estimators can distinguish PANDAS nominal type feature and PANDAS ordinal type feature?

### ISSUE THREAD

**Issue by muketer** [catboost/catboost#789]
Are SKLEARN API estimators can recognize difference between
'ordinal feature (applying pandas.api.types.CategoricalDtype(data, ordered=True))'
and
'nominal feature (applying pandas.api.types.CategoricalDtype(data, ordered=False))' ?

thank you for your help.

**Comment by annaveronika** [comment]
As far as I know sklearn doesn't support categorical types yet, but you need to check with sklearn.

**Comment by annaveronika** [comment]
We'll post all the updates in the duplicate issue.
