### ISSUE TITLE
cat_features, using only certain values from categorial columns

### ISSUE THREAD

**Issue by munitech4u** [catboost/catboost#79]
Hello,

I believe how cat_features work is by transforming each of categorical feature into dummy coding. I have a column say country(a,b,c,d,e). I am feeding it as cat_features in catboost. But I want model to train only on certain column values like: a,b,c. How can I do that?

**Comment by VladislavLecter** [comment]
You can convert your data (if using pandas or another lib), create a variable without unnecessary data.
just example:
c = data([data.country != d] & [data.country != e]) 
then train your 'c'  data

**Comment by munitech4u** [comment]
Only problem with this is, if there are other column values corresponding to d and e, which I want to keep in model, so I don't want to remove complete row. Just don't want to create features for the values d and e.

This is to bring data more close to test dataset.

**Comment by annaveronika** [comment]
We don't support ignoring particular values of categorical features, because this doesn't fit to our training schema. So you need to do some data preprocessing to be able to use CatBoost in the way you want to.
