### ISSUE TITLE
Targeting different python versions when building using pyenv

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#793]
I'm having issues creating a build environment to build the python package using pyenv+virtualenv.

The issue is the build system appears to require `python3-config` which I think it installed by `sudo apt-get install python3-dev` if you install python using apt. If however I use pyenv+virtaulenv to install and build a python 3.7.1 package on Ubuntu 18.04 (where the system python is 3.6) I get PYTHON-NOT-FOUND.

I've passed `-DPYTHON_CONFIG=/home/david/.pyenv/shims/python/python3-config` but this file is much smaller than `/usr/bin/python3-config` and doesn't appear to contain the location of the required headers etc.

Any ideas how to build catboost for a different target to the system python?

**Comment by david-waterworth** [comment]
I figured out the answer, to build _catboost.so you need to tell ya where the python binary is, and the python*-config script, which in turn returns the location of the libs, includes and compiler flags required to build a python extension against that version of python. When using pyenv these are located in the following path (if you follow the recommended install guide) (assuming you've installed python 3.7.1)

`~/.pyenv/versions/3.7.1/bin/python3.7`
`~/.pyenv/versions/3.7.1/bin/python3.7-config`

Since pyenv builds each version of python from source the included and libs are also located in `~/.pyenv/versions/3.7.1`

Then in order to build, I use full paths although that's not required. What I have found necessary is pass the following flags: -DPYTHON_BIN, -DPYTHON_CONFIG, -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_ARCADIA_CUDA_HOST_COMPILER=no

i.e.

`/home/david/.pyenv/versions/3.7.1/bin/python3.7 /home/david/dev/catboost/ya make /home/david/dev/catboost/catboost/python-package/catboost --no-src-links -r --output /home/david/dev/catboost/ -DPYTHON_BIN=/home/david/.pyenv/versions/3.7.1/bin/python3.7 -DPYTHON_CONFIG=/home/david/.pyenv/versions/3.7.1/bin/python3.7-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DUSE_ARCADIA_CUDA_HOST_COMPILER=no -DHAVE_CUDA=yes -DCUDA_ROOT=/usr/local/cuda
`

Note this is basically what mk_wheel.py does except it hard codes -DPYTHON_CONFIG=python3-config and doesn't detect the correct python bin.

**Comment by kizill** [comment]
We are using PYENV for release wheels building, you can look how it works in `ci/build_all_nix.sh` script: https://github.com/catboost/catboost/blob/master/ci/build_all_nix.sh#L89-L121

**Comment by andrey-khropov** [comment]
JFYI it is also possible in CMake-based build but requires specifying `CMAKE_FIND_ROOT_PATH` and `-DPython3_LIBRARY` and `-DPython3_INCLUDE_DIR`. An example can be seen in [our new CI script](https://github.com/catboost/catboost/blob/7c5080343b072f21fef5ddd5bce9de6c7a5c928a/ci/build_all.py#L402-L403).
