### ISSUE TITLE
_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#797]
Problem: 
"_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:281: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version"

```
Traceback (most recent call last):
  File "catboosttest.py", line 161, in <module>
    trainmodel()
  File "catboosttest.py", line 109, in trainmodel
    verbose=True)
  File "C:\Anaconda3\lib\site-packages\catboost\core.py", line 2701, in fit
    save_snapshot, snapshot_file, snapshot_interval)
  File "C:\Anaconda3\lib\site-packages\catboost\core.py", line 1173, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool)
  File "C:\Anaconda3\lib\site-packages\catboost\core.py", line 866, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool)
  File "_catboost.pyx", line 2308, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2344, in _catboost._CatBoost._train
_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/cuda/cuda_lib/cuda_base.h:280: CUDA error 35: CUDA driver version is insufficient for CUDA runtime version
```
```
  model = CatBoostRegressor(depth=6, learning_rate=1, loss_function='MAE', task_type = "GPU")    
```

CUDA version:  
              CUDA Toolkit 10.1 
              cuda_10.1.105_win10_network.exe

catboost version: 0.14.2 
+ 0.13.0 — same error.

Operating System: Windows 10
CPU: Intel Core i7 950
GPU:  NVIDIA Quadro K2200

**Comment by david-waterworth** [comment]
What driver are you using, i.e. what does the command `nvidia-smi` return?

**Comment by belonesox** [comment]
NVIDIA-SMI 391.35                 Driver Version: 391.35                    |

**Comment by david-waterworth** [comment]
@belonesox https://github.com/catboost/catboost/issues/353#issuecomment-390395517 indicates catboost is now built with CUDA 9.1, and [CUDA Driverr](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/) indicates that >=390.46 is required for CUDA 9.1 so it should really work as I thought they statically linked cuda to the catboost library.

It may be trying to dynamically load the system version of CUDA though, which you say is 10.1 and this definitely requires >= 418.39 so your CUDA install is broken, I'd update the driver and see if that works.

In general to check CUDA you need to build and run the samples - but if updating the driver means catboost works that's probably sufficient.

**Comment by gigikalo** [comment]
Same error but I have Intel Corporation HD Graphics 5500

**Comment by John-Brown** [comment]
Similar issue

Cuda version
```bash
NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0
```

What fixed it for me was the following:

```bash
conda create -n env37 python=3.7
conda install -c conda-forge catboost=0.21
```
It didn't seem to like the python 3.8 environment that comes default with the latest conda, nor did it like any version newer than 0.21.

**Comment by kizill** [comment]
Yes, since 0.22 we are using CUDA toolkit v10.1, so you need at least 418.39 driver on linux and at least 418.96 on windows platform. 
We'll update documentation soon.
