### ISSUE TITLE
Create #catboost tag on Stackoverflow

### ISSUE THREAD

**Issue by ZarubinArtem** [catboost/catboost#8]
To create a new tag on Stackoverflow you must to have at least 1500 reputation.
Maybe you need to create first post on SOF and create the #catboost tag? With instructions how to start to contribute to the package for instance.

**Comment by synapticarbors** [comment]
https://stackoverflow.com/tags/catboost/info

**Comment by crazyelf1971** [comment]
Thanx! I approved this tag to my question where https://stackoverflow.com/questions/45165532/how-to-install-yandex-catboost-on-anaconda-x64

**Comment by annaveronika** [comment]
Instructions for contributors can be found in our documentation here:
https://tech.yandex.com/catboost/doc/dg/concepts/development-and-contributions-docpage/

Thanks a lot for helping with the tag! Tag is created, so I'm closing the issue.
