### ISSUE TITLE
Negative Feature Importance Value Interpretation

### ISSUE THREAD

**Issue by hrbzkm98** [catboost/catboost#801]
Problem: {Some features have negative feature importance value (QueryRMSE Loss)}
catboost version: {0.14.2}
Operating System: {Ubuntu 18.04}
CPU: {CPU}
# GPU: {GPU}

I am using CatBoost for ranking task. I am using QueryRMSE as my loss function. I notice for some features, the feature importance values are negative and I don't know how to interpret them.
It says in the documentation, the i-th feature importance is calculated as the difference between loss(model with i-th feature excluded) - loss(model).
So a negative feature importance value means that feature makes my loss go up?
What does that suggest then?

**Comment by annaveronika** [comment]
Yes, negative feature importance value means that feature makes the loss go up. This means that your model is not getting good use of this feature. This might mean that your model is underfit (not enough iteration and it has not used the feature enough) or that the feature is not good and you can try removing it to improve final quality.

**Comment by annaveronika** [comment]
@hrbzkm98 Does this answer your question?

**Comment by hrbzkm98** [comment]
@annaveronika yes thank you for your follow up and excellent explanation!
