### ISSUE TITLE
Crash python on exit: VERIFY failed:   c:\goagent\pipelines\buildmaster\catboost.git\catboost\cuda\cuda_lib\gpu_single_worker.h:343

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#803]
Problem: {problem description}
Crash python on exit:

on catboost 0.13
``
VERIFY failed:
  c:\goagent\pipelines\buildmaster\catboost.git\catboost\cuda\cuda_lib\gpu_single_worker.h:343
  NCudaLib::TGpuOneDeviceWorker::~TGpuOneDeviceWorker(): requirement AtomicGet(Stopped) failed
PyInit__catboost+498899 (0x7FFB48E72DF3)
PyInit__catboost+582100 (0x7FFB48E872F4)
??+0 (0x7FFB48CB1431)
??+0 (0x7FFB48CA6FB4)
??+0 (0x7FFB48CB06E6)
??+0 (0x7FFB48CB34D9)
??+0 (0x7FFB48CAA6D6)
PyInit__catboost+551813 (0x7FFB48E7FCA5)
PyInit__catboost+496426 (0x7FFB48E7244A)
PyInit__catboost+16159312 (0x7FFB49D62370)
PyInit__catboost+16158381 (0x7FFB49D61FCD)
PyInit__catboost+16159601 (0x7FFB49D62491)
PyInit__catboost+16015472 (0x7FFB49D3F190)
PyInit__catboost+16015133 (0x7FFB49D3F03D)
PyInit__catboost+16015803 (0x7FFB49D3F2DB)
PyInit__catboost+15774295 (0x7FFB49D04377)
PyInit__catboost+15773246 (0x7FFB49D03F5E)
PyInit__catboost+15773540 (0x7FFB49D04084)
RtlDeactivateActivationContextUnsafeFast+435 (0x7FFBB48812C3)
LdrShutdownProcess+293 (0x7FFBB48C6325)
RtlExitUserProcess+180 (0x7FFBB48C61E4)
ExitProcess+10 (0x7FFBB2C6D26A)
exit+244 (0x7FFBB1AA5954)
exit+123 (0x7FFBB1AA58DB)
??+0 (0x1C8E12BF)
BaseThreadInitThunk+20 (0x7FFBB2C637E4)
RtlUserThreadStart+33 (0x7FFBB48BCB81)
``

on catboost 14.2
''
VERIFY failed (2019-04-22T13:41:04.682298+0300):
  c:\goagent\pipelines\buildmaster\catboost.git\catboost\cuda\cuda_lib\gpu_single_worker.h:343
  NCudaLib::TGpuOneDeviceWorker::~TGpuOneDeviceWorker(): requirement AtomicGet(Stopped) failed
PyInit__catboost+536803 (0x7FFB3A1DFCB3)
PyInit__catboost+619653 (0x7FFB3A1F4055)
??+0 (0x7FFB3A00A9F1)
??+0 (0x7FFB39FFCFA4)
??+0 (0x7FFB3A009AF6)
??+0 (0x7FFB3A00CE49)
??+0 (0x7FFB3A0025E6)
PyInit__catboost+589717 (0x7FFB3A1ECB65)
PyInit__catboost+534330 (0x7FFB3A1DF30A)
PyInit__catboost+17703656 (0x7FFB3B23EEB8)
PyInit__catboost+17702725 (0x7FFB3B23EB15)
PyInit__catboost+17703945 (0x7FFB3B23EFD9)
PyInit__catboost+17559456 (0x7FFB3B21BB70)
PyInit__catboost+17559117 (0x7FFB3B21BA1D)
PyInit__catboost+17559787 (0x7FFB3B21BCBB)
PyInit__catboost+17313355 (0x7FFB3B1DFA1B)
PyInit__catboost+17312306 (0x7FFB3B1DF602)
PyInit__catboost+17312600 (0x7FFB3B1DF728)
RtlDeactivateActivationContextUnsafeFast+435 (0x7FFBB48812C3)
LdrShutdownProcess+293 (0x7FFBB48C6325)
RtlExitUserProcess+180 (0x7FFBB48C61E4)
ExitProcess+10 (0x7FFBB2C6D26A)
exit+244 (0x7FFBB1AA5954)
exit+123 (0x7FFBB1AA58DB)
??+0 (0x1C8E12BF)
BaseThreadInitThunk+20 (0x7FFBB2C637E4)
RtlUserThreadStart+33 (0x7FFBB48BCB81)
''
catboost version: 0.14.2 and 0.13
Operating System: Windows 10
CPU: Intel Core i7 950
GPU: NVIDIA Quadro K2200
``
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 416.78       Driver Version: 416.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200       WDDM  | 00000000:03:00.0  On |                  N/A |
| 47%   56C    P8     2W /  39W |    693MiB /  4096MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+
``

**Comment by Bixi81** [comment]
I have a similar problem: Any fix for that?

VERIFY failed:
  c:\goagent\pipelines\buildmaster\catboost.git\catboost\cuda\cuda_lib\gpu_single_worker.h:343
  NCudaLib::TGpuOneDeviceWorker::~TGpuOneDeviceWorker(): requirement AtomicGet(Stopped) failed
PyInit__catboost+501715 (0x7FFF3ADBAB93)
PyInit__catboost+584452 (0x7FFF3ADCEEC4)
??+0 (0x7FFF3ABEEA51)
??+0 (0x7FFF3ABE1004)
??+0 (0x7FFF3ABEDB56)
??+0 (0x7FFF3ABF0EA9)
??+0 (0x7FFF3ABE6646)
PyInit__catboost+554629 (0x7FFF3ADC7A45)
PyInit__catboost+499242 (0x7FFF3ADBA1EA)
PyInit__catboost+16458032 (0x7FFF3BCF24F0)
PyInit__catboost+16457101 (0x7FFF3BCF214D)
PyInit__catboost+16458321 (0x7FFF3BCF2611)
PyInit__catboost+16314192 (0x7FFF3BCCF310)
PyInit__catboost+16313853 (0x7FFF3BCCF1BD)
PyInit__catboost+16314523 (0x7FFF3BCCF45B)
PyInit__catboost+16068075 (0x7FFF3BC931AB)
PyInit__catboost+16067026 (0x7FFF3BC92D92)
PyInit__catboost+16067320 (0x7FFF3BC92EB8)
RtlActivateActivationContextUnsafeFast+291 (0x7FFF9914B583)
LdrShutdownProcess+293 (0x7FFF99157F85)
RtlExitUserProcess+216 (0x7FFF99157E48)
FatalExit+10 (0x7FFF9802CA7A)
exit+200 (0x7FFF964BCC08)
exit+123 (0x7FFF964BCBBB)
??+0 (0x1C69127F)
BaseThreadInitThunk+20 (0x7FFF98024034)
RtlUserThreadStart+33 (0x7FFF99183691)
The terminal process terminated with exit code: 1

**Comment by kizill** [comment]
I'll try to reproduce this issue next week. Stas had shared his data with us, could you also give us small code snippet that fails?

**Comment by Bixi81** [comment]
Hi kizill, thanks for looking at this. I think it is caused by GPU support. Here is the relevant part of the code:

```
from catboost import CatBoostClassifier
from catboost import Pool

train_dataset = Pool(data=xtrain,
                     label=ytrain,
                     cat_features=cat_features)

eval_dataset = Pool(data=xtest,
                    label=ytest,
                    cat_features=cat_features)

# Initialize CatBoostClassifier
model = CatBoostClassifier(iterations=999999999,
                            learning_rate=1, #0.9
                            depth=3,   #2
                            scale_pos_weight=3.4,
                            l2_leaf_reg=0.0000001,
                            task_type='GPU',
                            od_type = "Iter", 
                            od_wait = 100,
                            random_seed=7)
# Fit model
model.fit(train_dataset, use_best_model=True, eval_set=eval_dataset)
```

**Comment by belonesox** [comment]
https://cloud.mail.ru/public/3d2b/34EaJGbQF 

!demo-bug.bat  — run it on windows with anaconda 3
conda.list — list of my conda packages 
categories_and_week_to_amount_with_lags.pickle — dataset
catboostbuggpu.py — ugly script to reproduce the issue.

**Comment by redpoint13** [comment]
I was able to get past this issue by commenting out 'depth'.

**Comment by bluetyson** [comment]
I saw this today... Windows 10, 
Python 3.69 Anaconda, 
Catboost 0.17.4

**Comment by atifemreyuksel** [comment]
I encounter the same problem on exit.
I used Windows 10, Python 3.6.5, and CatBoost 0.17.4.

@kizill, is there any update about this issue? Thanks.

**Comment by Girrajjangid** [comment]
VERIFY failed (2020-03-20T17:45:10.079299+0530):
  c:\goagent\pipelines\buildmaster\catboost.gittt\catboost\cuda\cuda_lib\gpu_single_worker.h:343
  NCudaLib::TGpuOneDeviceWorker::~TGpuOneDeviceWorker(): requirement AtomicGet(Stopped) failed
PyInit__catboost+1288259 (0x7FF96907E093)
PyInit__catboost+1363269 (0x7FF969090595)
??+0 (0x7FF968DAFE32)
??+0 (0x7FF968DC3956)
??+0 (0x7FF968DC65C9)
??+0 (0x7FF968DB9756)
PyInit__catboost+1338309 (0x7FF96908A415)
PyInit__catboost+1285786 (0x7FF96907D6EA)
PyInit__catboost+20264792 (0x7FF96A296FA8)
PyInit__catboost+20263861 (0x7FF96A296C05)
PyInit__catboost+20265081 (0x7FF96A2970C9)
PyInit__catboost+20120576 (0x7FF96A273C50)
PyInit__catboost+20120237 (0x7FF96A273AFD)
PyInit__catboost+20120907 (0x7FF96A273D9B)
PyInit__catboost+19874995 (0x7FF96A237D03)
PyInit__catboost+19873946 (0x7FF96A2378EA)
PyInit__catboost+19874240 (0x7FF96A237A10)
RtlActivateActivationContextUnsafeFast+289 (0x7FF9F4A650A1)
LdrShutdownProcess+306 (0x7FF9F4AAAB02)
RtlExitUserProcess+173 (0x7FF9F4AAA9AD)
ExitProcess+10 (0x7FF9F305CD8A)
o_free+376 (0x7FF9F220AE38)
exit+127 (0x7FF9F22086EF)
??+0 (0x1CEC128D)
BaseThreadInitThunk+20 (0x7FF9F3057BD4)
RtlUserThreadStart+33 (0x7FF9F4AACED1)


Still facing this issue

**Comment by kizill** [comment]
I reproduced this case and found bug, currenty testing fixup code. Sorry for such a long delay :(

**Comment by CallShaul** [comment]
@kizill Could it be related to issue #1530 ?
