### ISSUE TITLE
Python: Segmentation fault when `y` or `eval_set` parameters are None

### ISSUE THREAD

**Issue by mfcabrera** [catboost/catboost#804]
Problem: Segmentation fault when 
catboost version: 0.14.2
Operating System: Mac OSX Sierra 10.12.6 and Linux 3.10.0-693.17.1.el7.
CPU: x86_64

Example code that makes the failure:
```python

import catboost as cb
import pandas as pd
import numpy as np


data = pd.DataFrame({
              'color': np.random.randint(1, 10, 100),
              'article_id': np.random.randint(100, 125, 100),
              'weight': np.random.rand(100),
              'y': np.arange(100) ** 2
})
y = data['y']
data = data.drop('y', axis=1)

cr = cb.CatBoostRegressor(loss_function='RMSE', eval_metric="RMSE")
fit_params={'use_best_model': True, 'cat_features': [0, 1], 'verbose': False}

# Segmentation fault here
cr.fit(data, y, eval_set=(None, None), **fit_params)

# Segmentation fault here as well
cr.fit(None, y, **fit_params)
```
Looking at the code, it seems that some guards are missing. When `y` is None there's an error but the message is cryptic.  Having not `None` paramters might be obvious when using for experiments but when is used inside a software this might happen and having a clear error is better than a seg fault (or a weird message). 

I will submit a small PR for solving this.

**Comment by annaveronika** [comment]
Thank you very much for pointing it out! Would you like to contribute to fix this? I think this will be a simple change, and we will help you if you will have any questions.

**Comment by mfcabrera** [comment]
Hi @annaveronika Thanks, I've already created #805 for that purpose :).
