### ISSUE TITLE
Default parameter loss_function=Logloss might confuse users in MultiClass classification task

### ISSUE THREAD

**Issue by dvpolyakov** [catboost/catboost#806]
Problem: default parameter value of loss_function = Logloss might confuse the new users in multi class classification task. 

CatBoostClassifier by default is set to binary classification task, which might be confusing for new users if they want to solve multi classification task, especially if they have previously used, e.g. XGBClassifier, where the binary/multiclass mode is set automatically depending on the number of unique values in the target vector. 

The detailed explanation with code is here:
https://github.com/dvpolyakov/CatBoost_issues/blob/master/Catboost%20usability%20example%20issue%201.ipynb

catboost version: 0.14.1
Operating System: Ubuntu

**Comment by annaveronika** [comment]
Thanks a lot for pointing it out! Yes, we have to fix this. Currently there is a border parameter of Logloss function, which makes binarization on the label values (0 class - less than border, 1 class - >= border).
We have to change this behavoir to using border only if it is specified. It will be a breaking change, but I agree that it is necessary.

**Comment by annaveronika** [comment]
this is fixed in 0.15
