### ISSUE TITLE
Catboost Error

### ISSUE THREAD

**Issue by AkshaysNimbalkar** [catboost/catboost#808]
Problem: { My target variable is categorical having three categories 'functional', 'Not functional', 'functional needs repair'} So while fitting catboost classifier facing this error:

CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/target/target_converter.cpp:53: Target value "functional needs repair" cannot be parsed as float

What does it mean ?
 
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
Please set loss_function='MultiClass', we run binary classification by default. We'll fix this soon.

**Comment by annaveronika** [comment]
It is fixed in 0.15
