### ISSUE TITLE
Working with categorical features

### ISSUE THREAD

**Issue by SergeyPy** [catboost/catboost#811]
Problem: practical application of CTR settings
catboost version: 0.14.2
Operating System: MAC OS Mojave 10.14.3 (18D109)
CPU: 2,3 GHz Intel Core i5
# GPU: {GPU}
Hello, not quite understanding but practical application of CTR settings, is there a detailed manual for applying these settings?

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/issues/436 - here is an issue for that
