### ISSUE TITLE
What are the default values for simple_ctr,combinations_ctr & per_feature_ctr. IF no default then how do we set them.

### ISSUE THREAD

**Issue by rt3722** [catboost/catboost#813]
Problem: {problem description}
catboost version: {version}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
Sorry it's not documented well enough. Here is an issue for that: https://github.com/catboost/catboost/issues/436

**Comment by annaveronika** [comment]
Closing this one as a duplicate.

**Comment by rt3722** [comment]
Thank you.
