### ISSUE TITLE
The result is different with Pandas 'category' and 'object' types

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#814]
When I create the Pool by passing Pandas DataFrame and the list of categorical features indexes into it, the result of learning is different when categorical features in DataFrame have types 'category' and 'object'. In the 2nd case, the result is much better, and the importance of categorical features is higher than in the 1st case.

catboost version: 0.14.2
Operating System: Ubuntu 18.04
CPU: Intel Xeon E3

**Comment by annaveronika** [comment]
Category is not supported yet, please use object for now.

**Comment by annaveronika** [comment]
From the duplicate issue:

Are SKLEARN API estimators can recognize difference between
'ordinal feature (applying pandas.api.types.CategoricalDtype(data, ordered=True))'
and
'nominal feature (applying pandas.api.types.CategoricalDtype(data, ordered=False))'

**Comment by annaveronika** [comment]
Closing the issue then, let us know if there will be problems with this type.
