### ISSUE TITLE
What is the use of cv when it does not return the best model?How to build cv model in catboost.

### ISSUE THREAD

**Issue by rt3722** [catboost/catboost#820]
Problem: {problem description}
catboost version: {version}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
cv in catboost is regular cross-validation, see https://en.wikipedia.org/wiki/Cross-validation_(statistics)
It is useful if you need cross-validation for some reason. For example, if you want to compare two different models, you can run cross-validation on both of them, look on the resulting error for every model, and select one of them as a better one.

We plan to add something like GridSearchCV from sklearn, which is not cross-validation, but parameter tuning which uses cross-validation internally.

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/issues/821 - here is an issue for that.
Does this answer your question?

**Comment by rt3722** [comment]
Yup.Thank you for your time and patience
