### ISSUE TITLE
Improve cmdline tutorial: provide example files with dataset and columns description.

### ISSUE THREAD

**Issue by cramen** [catboost/catboost#825]
https://github.com/catboost/catboost/blob/master/catboost/tutorials/cmdline_tutorial.md

In this tutorual test.tsv and other tsv files specified.
But files not exists.

You need to create this files.
This will make it easier to run the tutorial.

**Comment by annaveronika** [comment]
@cramen Thanks for the issue! Could you maybe help us with that? We have several datasets, which can be saved into files (catboost.datasets). You could change this md file to a folder with train.tsv, test.tsv, train.cd, tutorial.md

**Comment by annaveronika** [comment]
The tutorial has example files now.
