### ISSUE TITLE
Source releases on PyPi

### ISSUE THREAD

**Issue by jayantsahewal** [catboost/catboost#830]
Is it possible to publish source release on PyPi along with wheels? It would help in package's adoption tremendously.
Thank you!

**Comment by annaveronika** [comment]
Why is it useful?

**Comment by jayantsahewal** [comment]
A number of organizations, including mine, thrive on open-source packages such as this. However, because of the security and licensing reasons, they don't allow to build it from wheels. We and other organizations have built a bunch of automated tools to build using source files from pypi repository and make sure that the packages adhere to security and legal protocols. Hence, the request to publish source files on PyPi.

I can give example a number of libraries which we have been able to leverage. One such library is Shap which catboost also supports integration with.
https://pypi.org/project/shap/#files

I hope this justifies the request.

**Comment by jayantsahewal** [comment]
Is there any update on this?

**Comment by annaveronika** [comment]
No updates yet, sorry :(

**Comment by jayantsahewal** [comment]
Well, that's a bummer. Either ways, I appreciate the update. Thank you!

**Comment by jayantsahewal** [comment]
I am guessing still no update considering a new version was released yesterday. Is there a reason why you are not able to release the source files?

**Comment by marcelotrevisani** [comment]
A lot of packaging systems use the sdist package available on pypi
For example debian, centos, conda, etc

**Comment by FedericoCeratto** [comment]
I second what is being written: many organization, including FAANGs, review, vet and package everything from sources (from tarballs) for multiple reasons: legal, security, regulatory compliance but also reproducibility.

**Comment by kizill** [comment]
Hello!
We've recently finished our great journey of migrating external CatBoost builds to CMake. So from now on we finally can make this possible. I'd like to say this can be done by the end of January or in the beginning of February.

**Comment by andrey-khropov** [comment]
Release 1.2 with sdist archive is now available on PyPI.
