### ISSUE TITLE
error in description of classifier Transforming categorical features to numerical features

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#836]
![count class calulation](https://user-images.githubusercontent.com/11426119/57984931-8af66a80-7a2e-11e9-99b8-cb3bef0ffe00.jpg)
![my example calulations](https://user-images.githubusercontent.com/11426119/57984932-8af66a80-7a2e-11e9-8313-46a2da87d7cc.jpg)
![website explanatoin copy](https://user-images.githubusercontent.com/11426119/57984933-8af66a80-7a2e-11e9-881b-2a8b2e34dd6a.jpg)

Problem: {error in description of classifier Transforming categorical features to numerical features     https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html#algorithm-main-stages_cat-to-numberic.  Seems to be phrase "(up to the current one) " is lost in sentence  "  CountInClass  is how many times the label value was equal to “1” for objects with the current categorical feature value. "   . Also it is not clear what "(up to the current one) " means - is it from top to bottom or from bottom to top. Assuming it is from top to bottom and    assuming that "(up to the current one) " relates to "  CountInClass  is how many times the label value was equal to “1” for objects with the current categorical feature value. " We get the same numbers as in example , for example for line #1 (0+0.05)/ (0+1) = 0.05 and for line #7 (2+0.05) / (0+1) = 0.5125. All calculations are shown in attached 3 files  }
catboost version: {14.2}
Operating System: {win}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
There is a separate issue where we plan to improve categorical features descriptions. Please follow that issue and post your ideas of how we can improve the description there.

**Comment by Sandy4321** [comment]
I can help you ,  just give me correct without mistakes explanation/description possibly in Russian and I will help you.

**Comment by Sandy4321** [comment]
There is a separate issue where we plan to improve categorical features descriptions. Please follow that issue and post your ideas of how we can improve the description there
