### ISSUE TITLE
seems to be editing needed for regression description  in    Transforming categorical features to numerical features page

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#837]
[catboost website decription Transforming categorical features to numerical features copied May 19 2019.pdf](https://github.com/catboost/catboost/files/3195307/catboost.website.decription.Transforming.categorical.features.to.numerical.features.copied.May.19.2019.pdf)
Problem: {seems to be editing needed for regression description  in    Transforming categorical features to numerical features page https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html#algorithm-main-stages_cat-to-numberic. Title 3 Transforming categorical features to numerical features. Should be changed to  Transforming categorical features to numerical features got regression. Also this title should be done in the same style as title for classification : Transforming categorical features to numerical features in classification }
catboost version: {14.2}
Operating System: {win}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
There is a separate issue where we plan to improve categorical features descriptions. Please follow that issue and post your ideas of how we can improve the description there.
