### ISSUE TITLE
test and train data sets categorical transforming to numerical  : Is algorithm from title "Transforming categorical features to numerical features in classification" the same and fully independent for train and test data sets?? 

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#838]
Problem: {clarification needed in page Transforming categorical features to numerical features  https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html#algorithm-main-stages_cat-to-numberic. How Transforming categorical features to numerical features calculated  for classification test data? Is algorithm from title "Transforming categorical features to numerical features in classification" the same and fully independent for train and test data sets??  }
catboost version: {14.2}
Operating System: {win}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
No, when you are transforming categorical features on training dataset, for every object you are using the objects before this one in the permutation. When doing it on test dataset you use the whole train dataset to calculate statistics. And you don't use label values from test dataset, only from train dataset.

If you are interested in this topic and you have more ideas of how categorical feature documentation can be improved, there's an issue about that, please follow that one.
