### ISSUE TITLE
Wrong spelling in error message

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [catboost/catboost#84]
Just a small heads up. I am using latest catboost in python. I have installed it using `pip`. The error message when a wrong `loss_function` is used has a typo:
![screen shot 2017-08-17 at 08 54 50](https://user-images.githubusercontent.com/8193234/29394620-36ffc1a4-8329-11e7-918b-9d607e96bab4.png)
**'loss_fanction' should be changed to 'loss_function'**

I'd love to upload a patch if I get a little bit of guidance on how to contribute.

**Comment by sab** [comment]
Hello!

To contribute to CatBoost you need to read the Yandex CLA and indicate that you agree to its terms. Details of how to do that and the text of the CLA can be found in [CONTRIBUTING.md](https://github.com/catboost/catboost/blob/master/CONTRIBUTING.md)

**Comment by annaveronika** [comment]
This is fixed in the last version.
