### ISSUE TITLE
error in python_tutorial_with_tasks.ipynb

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#840]
Problem: { code from https://github.com/catboost/catboost/blob/master/catboost/tutorials/python_tutorial_with_tasks.ipynb  is not running on Windows 10 , error is 

---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-11-8d10bd29e142> in <module>()
      4     delimiter=',',
      5     column_description=os.path.join(dataset_dir, 'train.cd'),
----> 6     has_header=True
      7 )
      8 pool3 = Pool(data=X, cat_features=cat_features)

~\Anaconda3\lib\site-packages\catboost\core.py in __init__(self, data, label, cat_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    303                     raise CatBoostError("cat_features, weight, group_id, group_weight, subgroup_id, pairs_weight, \
    304                                         baseline, feature_names should have the None type when the pool is read from the file.")
--> 305                 self._read(data, column_description, pairs, delimiter, has_header, thread_count)
    306             else:
    307                 if isinstance(data, FeaturesData):

~\Anaconda3\lib\site-packages\catboost\core.py in _read(self, pool_file, column_description, pairs, delimiter, has_header, thread_count)
    609                 pairs = ''
    610             self._check_thread_count(thread_count)
--> 611             self._read_pool(pool_file, column_description, pairs, delimiter[0], has_header, thread_count)
    612 
    613     def _init(self, data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names):

_catboost.pyx in _catboost._PoolBase._read_pool()

_catboost.pyx in _catboost._PoolBase._read_pool()

CatBoostError: Incorrect CD file. Invalid line number #10: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/column_description/cd_parser.cpp:60: Invalid column index: index = 10, columnsCount = 10
![image](https://user-images.githubusercontent.com/11426119/57987671-b723e280-7a52-11e9-9589-cdfe3ca76a3a.png)

}
catboost version: {14.2}
Operating System: {win10}
CPU: {CPU}
# GPU: {GPU}

**Comment by annaveronika** [comment]
Sorry, it was an error, we've fixed it now.

**Comment by Sandy4321** [comment]
thanks, but this file still has bug
error message is
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-44d8ccb6e8ca> in <module>()
     11     logging_level='Silent'
     12 )
---> 13 print('Model is fitted: ' + str(model.is_fitted_))
     14 print('Model params:')
     15 print(model.get_params())

AttributeError: 'CatBoostClassifier' object has no attribute 'is_fitted_'

![image](https://user-images.githubusercontent.com/11426119/59040493-c671a100-8844-11e9-8bd9-93f19df3abb8.png)

![image](https://user-images.githubusercontent.com/11426119/59040656-223c2a00-8845-11e9-8d81-abe4031cf8d3.png)

**Comment by annaveronika** [comment]
Thanks! We've made the fix in our internal repo, it'll be on github soon.

**Comment by annaveronika** [comment]
Btw you are very welcome to make contributions! This one would a good first one. It is fixed though, but for the next time - it would be really nice.

**Comment by Sandy4321** [comment]
as I wrote you, I may help with help page with explanation how categorical values encoding happen , but you did not answer...
