### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Sasirekha123** [catboost/catboost#845]
im in a beginner level in datascience.pls somebody sort out this issue for me

->numeric_features = train.select_dtype(include=[np.number])

-> Error msg:
AttributeError: 'DataFrame' object has no attribute 'select_dtype'

AttributeError                            Traceback (most recent call last)
<ipython-input-24-45a19b23a041> in <module>
----> 1 numeric_features = train.select_dtype(include=[np.number])

~\Anaconda3\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5066                 return self[name]
-> 5067             return object.__getattribute__(self, name)
   5068 
   5069     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'select_dtype'

Thanks in advance

**Comment by annaveronika** [comment]
'DataFrame' object has no attribute 'select_dtype' - this error msg shows the problem.

I'm closing the issue, since it is not a problem or a request for catboost. This is more a question for stackoverflow.
