### ISSUE TITLE
catboost.from_data_frame in R

### ISSUE THREAD

**Issue by TarasDerevianko** [catboost/catboost#85]
Very inefficient realization of catboost.from_data_frame function.

-- uncorrect result for tbl_df(data.frame(...)) format (dplyr is very popular package in R!)
-- memory-inefficient (duplicated input dataframe in memory)

fastest and memory-efficient realization (without dplyr)

`catboost.from_data_frame2 <- function(data, 
                                      target = NULL, 
                                      weight = NULL, 
                                      baseline = NULL)
{
  if (!is.data.frame(data)) 
    stop("Unsupported data type, expecting data.frame, got: ", 
         class(data))
  if (sum(is.na(data)) > 0) {
    stop("NA and NULL values are not supported!")
  }
  
  if(length(setdiff(sapply(data, class), c("character", "integer", "numeric"))) > 0)
  {
    stop("Unsupported column type: ", paste0(setdiff(sapply(data, class), c("character", "integer", "numeric")),
                                             collapse = ', '))
  }
  
  cat_features <- which(sapply(data, class) == "character")
  
  if(length(cat_features) > 0)
  {
    for(column_index in cat_features) 
    {
      data[[column_index]] = .Call("CatBoostHashStrings_R", data[[column_index]])
    }
  }
  
  pool <- catboost.from_matrix(as.matrix(data), 
                               target, 
                               weight, 
                               baseline, 
                               cat_features-1)
  return(pool)
}`

**Comment by nikitxskv** [comment]
@TarasDerevianko Hello!
Thank you for report! We fixed it.
