### ISSUE TITLE
Catboost4j-prediction can't load the native library on java 12

### ISSUE THREAD

**Issue by ixtora** [catboost/catboost#852]
### Problem:
Catboost is loaded with a warning on Java 9-11.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ai.catboost.NativeLib (file:/local/repository/ai/catboost/catboost-prediction/0.2.5/catboost-prediction-0.2.5.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of ai.catboost.NativeLib
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```  
<br/>

In Java 12 the ability to change fields on the ClassLoader has been disabled. And so you get:
```
2019-06-01 20:27:29.725 ERROR 17401 --- [main] ai.catboost.NativeLib                    : usr_paths
2019-06-01 20:27:29.729 ERROR 17401 --- [main] ai.catboost.NativeLib                    : Failed to load native library

java.io.IOException: Failed to get field handle for `usr_path`
	at ai.catboost.NativeLib.addDirectoryToNativeLibSearchList(NativeLib.java:165) ~[catboost-prediction-0.2.5.jar:na]
	at ai.catboost.NativeLib.smartLoad(NativeLib.java:48) ~[catboost-prediction-0.2.5.jar:na]
	at ai.catboost.NativeLib.<clinit>(NativeLib.java:22) ~[catboost-prediction-0.2.5.jar:na]
```
<br/>

I have proposed a simple fix for this as a pull request.

### Catboost version: 
0.2.5
### Operating System:
MacOS Mojave 10.14.5
Ubuntu 16.04

**Comment by oldirtybasti** [comment]
is there a packaged jar that I can download that is compatible with java 12? Version 0.2.5 on mavencentral does not have this fix applied

**Comment by annaveronika** [comment]
> is there a packaged jar that I can download that is compatible with java 12? Version 0.2.5 on mavencentral does not have this fix applied

If you have additional problems, please create new issues, otherwise they might be lost: we don't always check closed issues.
Here is an issue for your problem:
https://github.com/catboost/catboost/issues/1000

**Comment by victorbartel** [comment]
Hi,
Finally, the fix for this issue wasn't released so far. Am I missing a point? Many thanks.

**Comment by andrey-khropov** [comment]
> Hi,
> Finally, the fix for this issue wasn't released so far. Am I missing a point? Many thanks.

The new release with the fix will be on maven today or tomorrow. Tested with Java 13. 12 is no longer supported (https://en.wikipedia.org/wiki/Java_version_history)

**Comment by victorbartel** [comment]
Thank you Andrey,

Do you have any plan, or considerations to stick to LTS versions rather than short term versions? The industry adores LTSs and when you are making Kotlin or Scala you don't wanna mess around with JDKs updates in production every 6 months. Thanks a lot.

**Comment by andrey-khropov** [comment]
> Do you have any plan, or considerations to stick to LTS versions rather than short term versions? 

CatBoost Java applier should be compatible will all currently supported Java versions greater than 8 (that is 8, 11, 13). This issue affected Java 12+, the only currently supported version greater than or equal than 12 is 13, that is why I mentioned it.

**Comment by andrey-khropov** [comment]
Maven version 0.2.6 released today contains this fix.
