### ISSUE TITLE
RuntimeError, dictionary changed size during iteration

### ISSUE THREAD

**Issue by chalesguo** [catboost/catboost#86]
when  initializing CatBoostClassifier, I get the runtime error: dictionary changed size during iteration

both comments get the same error.

model = CatBoostClassifier(iterations=100, depth=2, learning_rate=1, loss_function='Logloss', verbose=True)
model = CatBoostClassifier(iterations=100, learning_rate=1, depth=6, loss_function='MultiClass', class_count=3)

**Comment by annaveronika** [comment]
This should be fixed in the last version
