### ISSUE TITLE
Python 3.7 deprecation warning

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#862]
FYI only, at least until python 3.8

> site-packages/catboost/core.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by kizill** [comment]
Do you use proper version? This warning was fixed in https://github.com/catboost/catboost/commit/1356ac70716956c17f41b5c377f22517e3479d9b

**Comment by david-waterworth** [comment]
Yes, but looks like I've not installed it into a pyenv I'm using, thanks!
