### ISSUE TITLE
Increment learning with different sampling rate for the unbalanced dataset

### ISSUE THREAD

**Issue by Jxu-Thu** [catboost/catboost#867]
Problem:
catboost version: 0.15.2
Operating System: Ubuntu 16.04
CPU

In catboost, each tree builds on a sampling dataset(called bagging). But for some unbalanced classification problems, I want to change the negative sampling rate of bagging dataset(for the unbalanced dataset) when training. How can I do this thing?

Thanks for your kind reply

**Comment by annaveronika** [comment]
Here is the information about sampling in catboost:
https://catboost.ai/docs/concepts/algorithm-main-stages_bootstrap-options.html
