### ISSUE TITLE
R: Get ShapValues fails for MultiClass models

### ISSUE THREAD

**Issue by kaboroevich** [catboost/catboost#868]
Problem: In the R package, get_feature_importance(type='ShapeValues') fails for models trained with loss_function='MultiClass'
catboost version: v0.14.2
Operating System: Linux (CentOS 6.6) x86_64
CPU: Intel Xeon CPU E5-1620 v2 @ 3.70GHz

The command `get_feature_importance(model = model, pool = pool, type='ShapeValues')` fails with:

> Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
> Traceback:
>
> 1\. catboost.get_feature_importance(model, pool, "ShapeValues")
> 2\. \`colnames<-\`(\`\*tmp\*\`, value = c(colnames(pool), "<base>"))

This is because the line `importances <- .Call("CatBoostCalcRegularFeatureEffect_R", model$handle, pool, type, thread_count)` returns a three-dimensional **array** (the extra dimension being the classes) for a 'MultiClass' model rather than a two-dimensional **matrix** (objects x features). 

One workaround would be to replace the line 1723:
`colnames(importances) <- c(colnames(pool), "<base>")`
with:
`dimnames(importances)[[length(dims(importances))]] <- c(colnames(pool), "<base>")`

This would add the feature names for both 2D matricies and 3D arrays

**Comment by annaveronika** [comment]
Which version are you using? Could you try with the latest one?

**Comment by kaboroevich** [comment]
As stated, I was using v0.14.2.

I upgraded to v0.15.1, and get the same error.

.Call("CatBoostCalcRegularFeatureEffect_R", model$handle, pool, type="ShapValues", thread_count) returns a 3 dimensional array (objects x class x features) for MultiClass models. The command colnames does not work for arrays greater than two-dimensions.

**Comment by annaveronika** [comment]
This is fixed now in code, will be out in the next minor release 0.16.5
