### ISSUE TITLE
[Request] Support LambdaRank

### ISSUE THREAD

**Issue by henry0312** [catboost/catboost#87]
I think CatBoost is so nice and it would become much better to support LambdaRank.
LightGBM supports it (http://lightgbm.readthedocs.io/en/latest/python/lightgbm.html#lightgbm.LGBMRanker), but XGBoost (Python API at least) doesn't.

**Comment by annaveronika** [comment]
We plan to add our ranking and pairwise objectives, so wait for the updates.

**Comment by annaveronika** [comment]
We've added YetiRank in last release, which works better than LambdaRank. We also plan to add a modification of this mode, which works better for very large datasets. Please try this!
