### ISSUE TITLE
How can I extract the values of different levels of categorical features?

### ISSUE THREAD

**Issue by CHI-MING-LEE** [catboost/catboost#870]
Problem: Can I get values used for prediction like parameters in regression analysis?
catboost version: 0.14.2
Operating System: win7
CPU: i7
# GPU: none

I've been dealing with the problem of interpretability when using CatBoostRegressor. I would like to get the values that model used for prediction in terms of each level of each categorical feature from CatBoost model after training. For example, I have a categorical feature with levels A, B, C, etc. After model training, I will get prediction result using this feature and I want to know what value each level of this feature is, which means when a row uses level A, the model will get a base value says 10, and 5 for B, 20 for C, etc. In the end, the prediction result is sort of summation of this values like regression. If I have these values, I can use them to interpret how much effect it will be for each level of each feature. It will be a great help for practical use, making the CatBoost less black-boxy. Thank you in advance for any help and suggestion.

**Comment by david-waterworth** [comment]
have you looked at get_feature_importance()? In particular take a look at Shap (https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Catboost%20tutorial.ipynb)

**Comment by CHI-MING-LEE** [comment]
I see. I will take a look at it. Thank you so much.
