### ISSUE TITLE
Multiclass model saving

### ISSUE THREAD

**Issue by MotoRZR** [catboost/catboost#874]
I’m working on a project that requires hundreds of millions of predictions at any one time so latency is big concern.  This is a multiclass problem.  We’ve explored lightgbm and estimated it would take a couple of days to run with baseline hardware. Also, should mention the project will most likely be written in .NET/C++.  With LightGBM we could output the model to C++ so could call the predictive model easily.

We are starting to explore catboost because of inference speed to cut that prediction time significantly.

My understanding is that a multiclass model cannot be saved to a python or C++ version.  What other options might we have to use the catboost model in this type of system?

**Comment by kizill** [comment]
Hello! I strongly recommend our binary model format as it is stable and really fast. We have C API library both [dynamic libcatboostmodel.(so|dll)](https://github.com/catboost/catboost/tree/master/catboost/libs/model_interface)  and [static](https://github.com/catboost/catboost/tree/master/catboost/libs/model_interface/static) version. More infromation about model integration you could read [here](https://github.com/catboost/catboost/blob/master/catboost/CatboostModelAPI.md)
Also, we now have C#/.Net wrapper for our C API library, see examples [here](https://github.com/catboost/catboost/tree/master/catboost/dotnet)

**Comment by MotoRZR** [comment]
Thanks for the quick response.  I will revert once we make progress.

**Comment by annaveronika** [comment]
I don't think there's an issue on our side though. If you have questions (just want to talk, no action items) then a better place would be our group in telegram or our channel in slack. Thus I'm closing the issue.
