### ISSUE TITLE
How does CatBoost generate Pairs if the pairs are not specifically provided ?

### ISSUE THREAD

**Issue by imeckr** [catboost/catboost#876]
I realised in the following code that CatBoost generates pairs randomly without looking at the actual label. For e.g.
Id, Group Id, Label
0, 1, 0
1, 1, 0
2, 1, 1
3, 1, 2
4, 1, 0
5, 1, 1

The pairs should be ids (0,2), (0,3), (0,5), (1,2), (1,3), (1,5), (4,2), (4,3), (4,5), (2,3), (5,3)
But according to the pair generation code, it can be any pair like (0,1) or (0,4) which doesn't make sense as they have the same relevance label.
https://github.com/catboost/catboost/blob/c14b18af4d23f8ce5eb7caaa01444fce7ca1e3c3/catboost/libs/pairs/util.cpp

Am I missing something or it is intentional?

**Comment by ek-ak** [comment]
Hi!
Pairs with the same relevance label are skipped during generation:
https://github.com/catboost/catboost/blob/c14b18af4d23f8ce5eb7caaa01444fce7ca1e3c3/catboost/libs/pairs/util.cpp#L26
https://github.com/catboost/catboost/blob/c14b18af4d23f8ce5eb7caaa01444fce7ca1e3c3/catboost/libs/pairs/util.cpp#L55
