### ISSUE TITLE
Incremental learning with "init_model=xxx"  not worked if new dataset has different number of rows

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#879]
Problem:  
I wish to use incremental learning.

> It is a new parameter of the fit function init_model. It is described in docs in fit function description. And you can find an example here: https://catboost.ai/docs/concepts/python-usages-examples.html#training-continuation

I tried to use «init_model=model1» for continue training with dataset with same columns/features but different number of rows, and got 
```
 File "/usr/lib64/python3.5/site-packages/catboost/core.py", line 1895, in get_feature_importance
   Pass training dataset to this function.")
_catboost.CatBoostError: Model has no meta information needed to calculate feature importances.                         Pass training dataset to this function.
```
demo script and data  https://cloud.mail.ru/public/4wmB/5JBRocyhB
(just run "python3 wtf.py")

catboost version: 0.15.1
Operating System: Linux 64

**Comment by annaveronika** [comment]
Working on that, fix will be on pypi soon. Sorry for inconvenience!
