### ISSUE TITLE
different results during different runs

### ISSUE THREAD

**Issue by varghesealex90** [catboost/catboost#88]
Hi;

I am try to use catboost for a regression problem, however I get different results while rerunning the model. I do set the random_state=2017 for all runs, however it fails to produce the same result.

Could someone shed some light on this?

**Comment by varghesealex90** [comment]
CatBoostRegressor(calc_feature_importance=True,random_state=2017,use_best_model=True,iterations=2000)

**Comment by annaveronika** [comment]
You are using wrong parameter name. Try using random_seed=2017, it should work. Argument check will be added in next update.
