### ISSUE TITLE
documentation: json tutorial is unavailable 

### ISSUE THREAD

**Issue by unnir** [catboost/catboost#880]
Problem:

A broken link to the save_model json tutorial here:
https://catboost.ai/docs/concepts/python-reference_catboost_save_model.html#python-reference_catboost_save_model

the correct link is>
https://github.com/catboost/tutorials/blob/master/apply_model/json/model_export_as_json_tutorial.ipynb

**Comment by annaveronika** [comment]
Thanks for pointing that out, we'll fix it soon!
