### ISSUE TITLE
Error 0xC0000005

### ISSUE THREAD

**Issue by Aleks-FX** [catboost/catboost#881]
Problem: Console application catboost-0.15.1.exe does not work on Windows 7, causes error 0xC0000005.
catboost version: Please note that applications up to version 0.14.2 all work on this OS.
Operating System: Windows 7 64-bit
CPU: AMD FX-8350
# GPU: not use

**Comment by Aleks-FX** [comment]
And???

**Comment by annaveronika** [comment]
As discussed in catboost telegram chat, additional information is needed to understand, what exactly is not working.

**Comment by kizill** [comment]
Fixed in 0.17.3 release, sorry for delay!
