### ISSUE TITLE
can't continue train with model in file

### ISSUE THREAD

**Issue by baicao** [catboost/catboost#884]
Problem:i save the model to file , and want to continue train model through reload model from file, but I get this error
_catboost.CatBoostError: Model has no meta information needed to calculate feature importances. 
catboost version:0.15.1
Operating System:mac
CPU:

`from catboost import CatBoostClassifier
train_data = [[1, 4, 5, 6],
              [4, 5, 6, 7],
              [30, 40, 50, 60]]

eval_data = [[2, 4, 6, 8],
             [1, 4, 50, 60]]

train_labels = [1, 2, 1]

model1 = CatBoostClassifier(iterations=2,
                           learning_rate=0.2,
                           depth=2)

model1.fit(train_data, train_labels)
model_file = "catboost_test.model"
model1.save_model(model_file)
print("save model to file :"+ model_file)
model11 = CatBoostClassifier()
model11.load_model(model_file)
model1.fit(train_data, train_labels, init_model=model11)`

**Comment by annaveronika** [comment]
This is already fixed in code, it will be on pypi today in the next release.

**Comment by annaveronika** [comment]
fixed in 0.15.2
