### ISSUE TITLE
Save Pool in python

### ISSUE THREAD

**Issue by GeraudK** [catboost/catboost#898]
I'm sorry if this question has already been answered before but I couldn't find it. Is there a way to save a Pool in python? I see this functionality exists in R but not in python.

**Comment by andrey-khropov** [comment]
> Is there a way to save a Pool in python?

It is not supported at the moment. 

What is your usecase?

If all the features are numerical and stored as numpy.ndarrays in columnar order (either in 2d numpy.ndarray with order='F' or as a 'num_feature_data' part of [catboost.FeaturesData](https://catboost.ai/docs/concepts/python-features-data__desc.html) with order='F' or as pandas.DataFrame columns) and have dtype=numpy.float32  it is possible to create Pool very cheaply using such data (most of the time and CPU RAM during Pool creation might be spent on data format conversion if it is different from the internal representation) - Pool will just store references to numpy arrays data internally.

And numpy.ndarray can be saved and loaded.

**Comment by GeraudK** [comment]
Hi @andrey-khropov, I'm using Airflow along with Sagemaker parameter hypertuning. The goal was to save a Pool on S3 so that each instance would be able to collect it in order to train a model. This had the advantage to have weights, labels and categorical columns being saved in the correct way.

Do you know if a valid option would be to create a Pool and from that Pool create a numpy array along with a column description file and save this to S3? I'm worried that some data transformations will be performed again on the categorical features?

**Comment by kizill** [comment]
We've finally release quantized pool serialization/deserialization support https://catboost.ai/docs/concepts/python-reference_pool_quantized.html?lang=en . Now you can once preprocess, quantize and save your dataset to file and then reuse it, for example, for faster parameter tuning. If it's not what you wanted - feel free to reopen that issue 👍
Thank you for waiting!

**Comment by mastryukov1990** [comment]
can not eval_metrics on quantized pool. Can you add function to save raw Pool, without quantized? or add eval_metrics for quantized pool?
