### ISSUE TITLE
catboost/libs/data_new/model_dataset_compatibility.cpp:121: Feature A from pool must be B.

### ISSUE THREAD

**Issue by Sriharika1395** [catboost/catboost#899]
Problem: I have succesfully trained my data and saved my model . While predicting the data i am getting the below error:
catboost/libs/data_new/model_dataset_compatibility.cpp:121: Feature A from pool must be B.

A and B features are present in my dataframe(during training as well as predicting) and in the categorical columns as well.

catboost version:0.14.2
I have also updated my version to 0.15.2 but didn't help.

**Comment by annaveronika** [comment]
features in prediction must have the same order as features in training

**Comment by Sriharika1395** [comment]
Can we pass categorical column names instead of positions while training and predicting the data?

**Comment by annaveronika** [comment]
Yes, you can pass the names, but the order of columns in matrix must be the same.

**Comment by Sriharika1395** [comment]
Working now. Thank you so much.
Closing the issue.
