### ISSUE TITLE
Passing categorical features with nulls to FeaturesData

### ISSUE THREAD

**Issue by Ingvar-Y** [catboost/catboost#901]
Follow-up to the comment in #792 

Problem:
If you extract numeric and categorical values as np.array from pd.DataFrame and pass them into `FeaturesData` without filling missing values in the categorical part then calling `CatBoost.fit()` will throw a lot of errors like
```
TypeError                                 Traceback (most recent call last)
TypeError: object of type 'float' has no len()
Exception ignored in: '_catboost.to_arcadia_string'
TypeError: object of type 'float' has no len()
```
It looked like endless loop but I guess it just throwed an error for every np.nan value in the object array.

I suggest two things:
* adding more safeguards so that a user doesn't end in a situation with a stream of inscrutable errors
* adding more reminders across documentation that categorical features can't contain null values - catboost is supposed to handle null values so this difference between numeric and categorical features is unintuitive

@xthomas8888 was that your problem?

catboost version: 0.15.2

**Comment by annaveronika** [comment]
Actually the reason is that FeaturesData makes no checks at all to input data. You should use FeaturesData only if you are sure that you are already doing everything correctly and you don't want to spend additional time on checks.

Otherwise you should use Pool class or pass X and y to fit.

**Comment by annaveronika** [comment]
We are adding this warning to documentation.

**Comment by annaveronika** [comment]
https://catboost.ai/docs/concepts/python-features-data__desc.html

We've added a warning with explanation here.
