### ISSUE TITLE
Documentation: CatBoost Model Applier version

### ISSUE THREAD

**Issue by BraginIvan** [catboost/catboost#902]
Problem: I didn't work with  Java several years, so it mostly my fault, but it took ~30 minutes to understand how to add the "applier lib" to maven.

https://catboost.ai/docs/concepts/java-package.html
> change the source_version line to the latest available version 

tried source_version=0.15.2 and searched issue in other places. Would be better to add link https://mvnrepository.com/artifact/ai.catboost/catboost-prediction on word "version".

**Comment by BraginIvan** [comment]
And the last section
CatBoostPredictions prediction = model.predict(new float[3]{0.1f, 0.3f, 0.2f}, new String[3]{"foo", "bar", "baz"});
should be 
CatBoostPredictions prediction = model.predict(new float[]{0.1f, 0.3f, 0.2f}, new String[]{"foo", "bar", "baz"});

**Comment by andrey-khropov** [comment]
fixed
