### ISSUE TITLE
one_hot_max_size

### ISSUE THREAD

**Issue by andresfelipellm** [catboost/catboost#905]
Question: I have some categorical variables with lots of levels, so I am using one_hot_max_size. 

Basically 80% of the data have 20% of the levels. Does one_hot_max_size use random levels or it takes the most frequent ones?

How can I know which levels were used? and what happen to the levels that were not used? 

Does it create like another level (ex: "Others") to categorize the not used ones? or simply delete them?

I am just wondering how will be this encoding for new data, after applying the trained model.

**Comment by annaveronika** [comment]
one_hot_max_size does the following:
Use one-hot encoding for all categorical features with a number of different values less than or equal to the given parameter value. Ctrs are not calculated for such features.

It's all in the docs, please read carefully 
https://catboost.ai/docs/concepts/python-reference_parameters-list.html

**Comment by annaveronika** [comment]
For questions like that a good place is the telegram chat (https://t.me/catboost_en), our slack channel (#tool_catboost in https://ods.ai) or stackoverflow.

**Comment by andresfelipellm** [comment]
Thank you
