### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#906]
Unfortunately, I don't have much more to report but I'm now very frequently seeing "Segmentation Fault (core dumped)" during training. It happens when I'm hyper-parameter tuning in a loop, it's random and occurs fairly infrequently but frequently enough (daily) to be annoying. Please advise if there's anything I can provide which can help.

**Comment by annaveronika** [comment]
Very sorry for that! Is it CPU or GPU? Is it possible to share the code and data that provide seg fault?

**Comment by annaveronika** [comment]
Or at least the code

**Comment by david-waterworth** [comment]
My preference would be to share the core dump, but I cannot find it. It's not where it's supposed to be so I have to do some digging to ensure it's working, then try and recreated.

**Comment by annaveronika** [comment]
Is is CPU or GPU?

**Comment by david-waterworth** [comment]
GPU

**Comment by annaveronika** [comment]
What are optimizing RMSE, Logloss or something else?

**Comment by david-waterworth** [comment]
RMSE

If I restart the same model it runs fine so it’s not data / model related, it seems like some sort of resource leak, or potentially something interrupting the process

**Comment by david-waterworth** [comment]
Also I think this has only happened on my dual 1080ti machine, not my single 2080ti one. 

Both are Ubuntu 18.04

**Comment by david-waterworth** [comment]
I'm going to close this, I think it's an issue with my system. I restarted, and it cude and the nvidia driver were missing. I think it was a result of a previous upgrade which updated the kernel to the latest version, and removed a whole bunch of packages of which I think included the display driver and cuda.
