### ISSUE TITLE
Can I avoid saving files generated during training?

### ISSUE THREAD

**Issue by gitmario** [catboost/catboost#913]
Problem: CatBoostRegressor automatically saves some files generated during training in a folder called  `catboost_info`. Can I avoid creating this folder? I tried to set the parameter `train_dir=None`, but nothing changed. Thanks in advance!

**Comment by annaveronika** [comment]
Try setting allow_writing_files=False

**Comment by HiiHarshita** [comment]
Hi annaveronika,

 model = CatBoostRegressor(allow_writing_files=False,silent=True,verbose=False)
 parameters = {'depth' : [6,8,10],'learning_rate' : [0.01, 0.1],'iterations': [30, 50, 100]}
 grid = GridSearchCV(estimator=model, param_grid = parameters, cv = tscv, n_jobs=-1)
 grid.fit(data_collector['X_train'],data_collector['y_train'])

In the above code I have specified allow_writing_files as you have suggested but then also it is creating_info
please suggest
