### ISSUE TITLE
CatBoost for a dataset that is the list of tuples of two tuples of variable length inside them

### ISSUE THREAD

**Issue by sp2811** [catboost/catboost#915]
Problem: I have a very specific dataset consisting only of categorical variables. X_train is the list of tuples of two tuples of variable length inside them.

My X_train and y_train are something like

X_train = [(('a', 'b', 'c'), ('b', 'd')), (('d', 'c'), ('b', 'a')), (('a', 'c', 'd'), ('a', 'b')), (('a', 'c', 'd'), ('b', 'a', 'c')), (('a', 'b'), ('c', 'a', 'd'))],

y_train = ['p', 'q', 'r', 'q', 'p'].

I cannot apply CatBoost to my data, I do not understand how to use cat_features with my dataset. Is it possible to use CatBoost for such data?

**Comment by annaveronika** [comment]
CatBoost does not yet support features that have multiple values. Categorical features which are supported, require the feature to have a single value.

**Comment by sp2811** [comment]
Thank you very much for your answer!

Let me describe my problem in more detail.

For each sentence from a CoNLL-U file, we take the corresponding tree, we write a list of morphological features of words in the nodes of this tree, and we mark the edges of the tree with labels which are universal dependency relations.

X_train data are pairs of lists of morphological features (i.e., pairs of nodes of the tree, or, what is the same thing, edges of the tree), and the corresponding y_train are edge labels (universal dependency relations).

So it is a multiclassification problem, all data are categorical.

We want to use the CatBoost classifier for this problem of labeling edges of trees.

[https://universaldependencies.org/format.html](url)

[https://universaldependencies.org/tools.html](url)

[https://arborator.ilpga.fr/q.cgi](url)

![1](https://user-images.githubusercontent.com/50981786/61653253-8fefc880-acc2-11e9-8a76-9a306b79c8f4.png)

![2](https://user-images.githubusercontent.com/50981786/61653255-90885f00-acc2-11e9-9b06-464562eb5bc6.png)

**Comment by annaveronika** [comment]
I don't have an answer out of my head. But it looks like you need some feature engineering to built a dataset where each feature has a single value.
A good place for such discussions is our slack channel, where we have a lot of active users. You can go to ods.ai, register to the slack community ods, and then go to #tool_catboost channel there.
The community is mostly russian, but there is a lot of staff in english also, and you can always ask in english.

**Comment by sp2811** [comment]
Thank you very much! We are in fact the Russian researchers team. We want to build a syntax analyzer for the Russian language using text corpora.
I wrote to you in your English section because there is less activity in the Russian section, as it seemed to me.

**Comment by annaveronika** [comment]
If you speak Russian, then it makes sence to join our telegram chat https://t.me/catboost_ru, it's the most active place with catboost discussions.

**Comment by annaveronika** [comment]
Closing the issue, please join our discussions!
