### ISSUE TITLE
Minimizing QuerySoftMax with 200 or more iterations is an order of magnitude slower than with 199 or less

### ISSUE THREAD

**Issue by artli** [catboost/catboost#917]
When using the QuerySoftMax loss function for training, the running time curiously increases 20-fold if the number of iterations is greater than 200. The problem persists with non-random data as well.

```shell
$ cat test.py
import sys
import numpy as np
from catboost import CatBoost, Pool

pool = Pool(
    data=np.random.rand(10000),
    label=np.random.randint(0, 2, size=10000),
    group_id=np.repeat(np.arange(100), 100))
clf = CatBoost(params=dict(
    loss_function='QuerySoftMax',
    iterations=int(sys.argv[1])))
clf.fit(pool, verbose=False)

$ time python test.py 100
real	0m0.754s
user	0m1.736s
sys	0m0.491s

$ time python test.py 199
real	0m0.921s
user	0m2.895s
sys	0m0.471s

$ time python test.py 200
real	0m11.848s
user	1m6.918s
sys	0m2.784s
```

catboost version: 0.16
Operating System: Ubuntu 18.04
CPU: Intel Core i7-8550U

**Comment by khrisanfov** [comment]
@artli Hello. I had the same issue. I think since 200 iterations CatBoost uses more complex parameters like feature combinations. Try to check get_all_params() output.

**Comment by annaveronika** [comment]
@artli @khrisanfov Yes, that's right, there is a set of parameters that depend on number of iterations. They include boosting type and categorical features combinations, which have influence on the speed.

**Comment by artli** [comment]
Thanks. In this case the parameter that slowed the training was leaf_estimation_iterationsleaf_estimation_iterations

**Comment by artli** [comment]
Thanks. In this case the parameter that slowed down the training was `leaf_estimation_iterations`. Upon increasing the number of iterations to 200, its default value automatically changes from 1 to 100, and restoring it back to 1 fixes the problem.

**Comment by bakwc** [comment]
Same here. Strange behavior.
