### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_object' using select_threshold()

### ISSUE THREAD

**Issue by ezavarygin** [catboost/catboost#919]
Problem: `catboost.utils.select_threshold()` produces 

> AttributeError: 'NoneType' object has no attribute '_object' using select_threshold

when only the `curve` is provided.
catboost version: 0.16
Operating System: Mac OS 10.13.6
CPU: 2,2 GHz Intel Core i7

The following example reproduces the problem:

```
from catboost.datasets import amazon
from catboost import CatBoostClassifier, utils, Pool
from sklearn.model_selection import train_test_split

amazon_train, amazon_test = amazon()

X_train, X_valid, y_train, y_valid = train_test_split(
    amazon_train.drop('ACTION', axis=1), 
    amazon_train.ACTION, 
    test_size=0.3, 
    random_state=4
)
cat_features = list(range(X_train.shape[1]))

model = CatBoostClassifier(iterations=20)
model.fit(X_train, y_train, cat_features=cat_features, verbose=False)

roc_curve = utils.get_roc_curve(model, Pool(X_valid, y_valid, cat_features))
print(utils.select_threshold(curve=roc_curve, FPR=0.01))
```

The [documentation](https://catboost.ai/docs/concepts/python-reference_utils_select_threshold.html) suggests that the `curve` should be enough to get the threshold. However, I get:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-56d8d38ed0a8> in <module>
>      18 
>      19 roc_curve = utils.get_roc_curve(model, Pool(X_valid, y_valid, cat_features))
> ---> 20 print(utils.select_threshold(curve=roc_curve, FPR=0.01))
>      21 #print(utils.select_threshold(model=model, data=Pool(X_valid, y_valid, cat_features), FPR=0.01))
> 
> ~/anaconda3/envs/pandas/lib/python3.7/site-packages/catboost/utils.py in select_threshold(model, data, curve, FPR, FNR, thread_count)
>     328         raise CatBoostError('One of the parameters data and curve should be set.')
>     329 
> --> 330     return _select_threshold(model._object, data, curve, FPR, FNR, thread_count)
> 
> AttributeError: 'NoneType' object has no attribute '_object'

The code works fine if I replace the last line with 
```
print(utils.select_threshold(model=model, data=Pool(X_valid, y_valid, cat_features), FPR=0.01))
```

**Comment by annaveronika** [comment]
Thanks for pointing this out, we will look into this!

**Comment by annaveronika** [comment]
The fix is on github and will be out on pypi in catboost 0.18
