### ISSUE TITLE
Feature request: Adding AUC as a loss function to optimize.

### ISSUE THREAD

**Issue by divakarhebbar** [catboost/catboost#920]
Problem: Currently, loss_function parameter doesn't support AUC.  I'm wondering if it could be implemented in the future releases. Is there any technical reason why this feature is not included so far? (Is it the case that AUC function is not differentiable which makes the optimization problem difficult to solve?)

catboost version: v0.16

**Comment by annaveronika** [comment]
Yes, AUC is not differentiable, so you can not optimize it with gradient-based methods. AUC is implemented as eval_metric, so you can optimize Logloss and select best iteration using AUC.

**Comment by divakarhebbar** [comment]
Thank you!
