### ISSUE TITLE
Issue with LogLoss calculation

### ISSUE THREAD

**Issue by khrisanfov** [catboost/catboost#925]
catboost version: 16.0
Operating System: Ubuntu 18.04
CPU: 1080Ti

During the training and after it LogLoss are different. I have created examples https://github.com/khrisanfov/catboost_eval_metric_issue. In amazon.ipynb you can see that LogLoss is 0.14829 during the training, but if I calculate LogLoss after the training it is much lower:  0.05402. In flight_delays.ipynb you can see that problem is with validation LogLoss. Why is it so?

**Comment by annaveronika** [comment]
On amazon you have categorical features, so statistics on categorical features are calculated differently on train dataset during training and during prediction. Here is the detailed explanation:
https://catboost.ai/docs/concepts/faq.html#applying-the-model-to-train-dataset

We'll look into flights.

**Comment by khrisanfov** [comment]
it was fixed in 0.16.4
