### ISSUE TITLE
Cannot access catboost.ai

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#927]
An FYI https://catboost.ai is blocked by privacy badger (the EFF's privacy extension). The issue isn't the main site, it blocks yastatic.net which seems to contain the assets required to render the page properly. I've reported to EFF

**Comment by annaveronika** [comment]
A similar problem on stackoverflow: https://github.com/catboost/catboost/issues/832

**Comment by david-waterworth** [comment]
I’ve noticed Privacy Badger blocks quite a few content delivery sites.

**Comment by annaveronika** [comment]
We are looking into this.

**Comment by annaveronika** [comment]
It should be fixed now.
