### ISSUE TITLE
CatBoostError: (Access is denied.) 

### ISSUE THREAD

**Issue by m1sta** [catboost/catboost#929]
Problem:

    CatBoostError: (Access is denied.) 
    c:/goagent/pipelines/buildmaster/catboost.git/util/system/file.cpp:625: can't open 
    "cat_feature_index.cb910109-ac4c38ea-2398bb65-5adfb5c0.tmp" with mode 
    CreateAlways|WrOnly|Seq (0x00000034)

catboost version: 0.16
Operating System: Windows 10 x64
CPU: Intel i7

Error generated when calling model.fit, including using examples in https://catboost.ai/docs/concepts/python-usages-examples.html

Problem does not occur when logged in as administrator.

**Comment by m1sta** [comment]
`
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-3-354ce5ed1057> in <module>
     14                            depth=2)
     15 # Fit model
---> 16 model.fit(train_data, train_labels, cat_features)
     17 # Get predicted classes
     18 preds_class = model.predict(eval_data)

C:\Program Files\Python37\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3230         self._fit(X, y, cat_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   3231                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 3232                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3233         return self
   3234 

C:\Program Files\Python37\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1353                 params,
   1354                 allow_clear_pool,
-> 1355                 train_params["init_model"]
   1356             )
   1357 

C:\Program Files\Python37\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
    930 
    931     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
--> 932         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
    933         self._set_trained_model_attributes()
    934 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: (Access is denied.) c:/goagent/pipelines/buildmaster/catboost.git/util/system/file.cpp:625: can't open "cat_feature_index.cb910109-ac4c38ea-2398bb65-5adfb5c0.tmp" with mode CreateAlways|WrOnly|Seq (0x00000034)
`

**Comment by david-waterworth** [comment]
My guess is the process doesn't have write access to the working directory you're running from? it's trying to create a temporary file and getting `Access is denied`

**Comment by annaveronika** [comment]
@m1sta Is this the case?

**Comment by m1sta** [comment]
That's my assumption too. I don't know why this would be the case. It may be a peculiarity with how ipython was setup on my machine.

**Comment by kostapanfilov** [comment]
can i specipy a path for this files?

**Comment by annaveronika** [comment]
> can i specipy a path for this files?
Yes, you can specify train_dir parameter.
You can also deprecate writing files using allow_writing_files=False

**Comment by VishnuPy** [comment]
Thanks @Annaveronika. I too faced this and able to resolve it with allow_writing_files parameter. Then faced a new one for which i have set the train_dir as I used Colab.google.com for trying out CatBoost Alg.

**Comment by Kingsley-opoku** [comment]
Thank you @annaveronika.
