### ISSUE TITLE
Segmentation fault from plot_tree

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#930]
When I pass a Pool() to plot_tree I get a Segmentation fault

using GDB to analyse the core dump I get the following stack trace, not sure if it helps.

> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x00007f3d884011ba in NCB::TFeaturesLayout::GetExternalFeatureDescription(unsigned int, EFeatureType) const
>     () from /home/david/.local/lib/python3.6/site-packages/catboost/./_catboost.so

It's from `estimator._get_tree_splits(tree_idx, pool)` i.e.

> pool = Pool(X,y,cat_features=None, feature_names=list(X.columns))
> 
> pool, _ = estimator._process_predict_input_data(pool, "plot_tree")
> splits = estimator._get_tree_splits(tree_idx, pool)

I'm not 100% sure how this is supposed to work - if X is a matrix does it take a slice (i.e. row 1)? I tried to slice it before creating the pool but taking a single row of a pandas dataframe results in a vector and Pool() doesn't seem to like that.

**Comment by david-waterworth** [comment]
Looks like I'm not using the same X I trained the model with. I forgot to put X through my transformation pipeline (which adds derived features)

Although Ideally this wouldn't cause a core dump...

**Comment by andrey-khropov** [comment]
Right now (with catboost 1.1.1) passing `pool` param to `plot_tree` that does not contain all features used in the model causes an error:

```
_catboost.CatBoostError: catboost/libs/data/model_dataset_compatibility.cpp:72: Feature 2 is present in model but not in pool.
```
