### ISSUE TITLE
Wrong number of calculated metrics (1), expected 2

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#931]
I'm using GPU training with RMSE loss_function and eval_metric

Doing the following results in an exception (catboost 16.1)

        pool = Pool(X_train,y_train,cat_features=cat_features, feature_names=list(X_train.columns))
        self.regressor.fit(pool,eval_set=(X_train,y_train))

this was working (I've changed to using a pool for the training data. I've deliberately passed (X_train,y_train) as the eval_set. 

> uncaught exception:
>     address -> 0x106f07808
>     what() -> "catboost/libs/loggers/catboost_logger_helpers.cpp:189: Wrong number of calculated metrics (1), expected 2"
>     type -> TCatBoostException
> Aborted (core dumped)

**Comment by annaveronika** [comment]
This is fixed in code with this pr: https://github.com/catboost/catboost/commit/2228b4ddded7f16a5633b9e159eef9139a6bed14

Will be out on pypi in the next release.
