### ISSUE TITLE
name 'features' is not defined

### ISSUE THREAD

**Issue by mahmoodn** [catboost/catboost#937]
For page rank [example](https://github.com/catboost/tutorials/blob/master/ranking/ranking_tutorial.ipynb), I hit this error
```
Traceback (most recent call last):
  File "rank.py", line 243, in <module>
    pool1 = Pool(data=features, label=relevances, group_id=group_id, pairs=pairs)
NameError: name 'features' is not defined
 ```
The code is
```
pool1 = Pool(data=features, label=relevances, group_id=group_id, pairs=pairs)
```

I tried with python3.6.
How can I fix that?

**Comment by mahmoodn** [comment]
No idea? Has anyone run this example successfully?

**Comment by david-waterworth** [comment]
It looks to me like it's been fixed by @KruchDmitriy.
