### ISSUE TITLE
IPython.core.display.HTML object message

### ISSUE THREAD

**Issue by mahmoodn** [catboost/catboost#938]
I see the following lines
```
<IPython.core.display.HTML object>
MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))
```
while running page rank. Are they important? I think I get that due to `model.fit(train_pool, eval_set=test_pool, plot=True)`

**Comment by annaveronika** [comment]
Do you run your code in jupyter notebook?

**Comment by mahmoodn** [comment]
No, I pasted the codes in a plain python file and ran it.

**Comment by annaveronika** [comment]
This is what you see if you use plot=True outside of jupyter notebook. plot=True works only in Jupyter. If you want visualization then you can use it instead of plain python. If you don't care about visualization then just write plot=False, and you will not have this lines in output.

**Comment by annaveronika** [comment]
closing the issue, let us know if you have more questions!
