### ISSUE TITLE
Obtain the number of iterations after overfitting detector triggers (python)

### ISSUE THREAD

**Issue by benediktbrandt** [catboost/catboost#94]
Is there a way to access the optimal number of iterations once the overfitting detector stops the fitting (using the python interface)? Catboost prints out the optimal number of Iterations

> Stopped by overfitting detector with threshold 0.1000000015
> 
> bestTest = 0.03253740638
> bestIteration = 191

How can I access this value in my python code? Thanks

**Comment by annaveronika** [comment]
If you want your model to save only the amount of iterations until the best iteration you can use use_best_model=True parameter.
There is also another possibility of accessing this - applying a fixed amount of trees in predict function:
predict(ntree_limit=191)

**Comment by benediktbrandt** [comment]
I am using the use_best_model=True parameter. Unfortunately there seems to be no indication on whether catboost stopped because it reached the maximum number of iterations or because the overfitting detector triggered (if verbose=False). If I could access the final number of iterations I could i.e. compare whether it is equal to the maximum number of iterations specified in the parameters. 

I am trying to tune the hyper-parameters over a lot of values and I need to know whether there is a parameter combination for which the maximum number of iterations is hit. 

I tried get_params() after I ran catboost with  use_best_model=True and the output for 'iterations' is 1000 which is the maximum number of iterations I specified (the overfitting detector determines 191 iterations as optimal)

**Comment by annaveronika** [comment]
There is an attribute called tree_count_ which is the number of trees in model. get_params() returns training params. We'll clarify this in documentation, thanks for the feedback.

**Comment by benediktbrandt** [comment]
Ha! got it to work! Thanks a lot for your help. I had to update to the latest version and then specify the od_type and od_pval parameters. 

I really appreciate your efforts and catboost and I know it is a lot of work, but if you see an opportunity it would be great if you could use a documentation that is updated automatically after each commit to master. (I.e like lightgbm does it https://github.com/Microsoft/LightGBM/tree/master/docs) )
