### ISSUE TITLE
sampling_frequency is unimplemented for task type GPU

### ISSUE THREAD

**Issue by wboleksii** [catboost/catboost#941]
According to the docs `sampling_frequency` is supported on GPU. I'm getting this error:
`catboost/libs/options/json_helper.h:223: Error: change of option sampling_frequency is unimplemented for task type GPU and was not default in previous run`

catboost version: v0.16.2
Operating System: Windows
GPU: nvidia quadro

**Comment by annaveronika** [comment]
It's not implemented for GPU, we'll fix the docs, thanks for pointing it out!

**Comment by annaveronika** [comment]
fixed in docs now
