### ISSUE TITLE
How to use the model predict trained on cv of catboost?

### ISSUE THREAD

**Issue by gaosq0604** [catboost/catboost#943]
Problem: I used the cv function in catboost for cv training. After training, it just returns a dataframe about some statistics. But I want to save the model and make predictions. What can I do in order to make cv in catboost?
The thing is like this:
df_pool = Pool(data = df, label = y, cat_features = cat_features )
params = {'iterations': 20000,
          'one_hot_max_size': 31,
          'learning_rate': 0.005,
          'loss_function': 'Logloss',
          'custom_metric': ['Logloss', 'AUC', 'Precision', 'Recall'],
          'eval_metric': 'AUC',
          'scale_pos_weight': 50}
clf = cv(df_pool, params, fold_count = 5, early_stopping_rounds = 200, plot = True)

resp = clf.predict_proba(val_df)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-77c22be1234f> in <module>
----> 1 res = clf.predict(val_df)
      2 resp = clf.predict_proba(val_df)
      3 resp1 = resp[:, 1]
      4 resp1s = sorted(resp1, reverse = True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5066                 return self[name]
-> 5067             return object.__getattribute__(self, name)
   5068 
   5069     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'predict'

B.T.W., catboost also seems to have some problems with gridsearchcv. Before, I tried once, but finally it leads to an error of 'bad location'.

Best regards

**Comment by annaveronika** [comment]
cv does not return a model, it returns a dataframe with loss values:
https://catboost.ai/docs/concepts/python-reference_cv.html

You probably want to use model.grid_search or model.randomized_search methods:
https://catboost.ai/docs/concepts/python-reference_catboost_grid_search.html
https://catboost.ai/docs/concepts/python-reference_catboost_randomized_search.html

There is a tutorial on github in our tutorials repository with examples of using these two methods.

**Comment by annaveronika** [comment]
And your question is also answered in our FAQ:
https://catboost.ai/docs/concepts/faq.html#how-to-get-best-parameters-from-the-cv-function

**Comment by annaveronika** [comment]
Hope it helps! Let us know, if you have other questions!
