### ISSUE TITLE
Too many features in model, ask catboost team for support

### ISSUE THREAD

**Issue by husseinmur** [catboost/catboost#944]
Problem:
I have a pandas dataframe of 1670825 rows and 40 columns (numerical and categorical features).
While running catboost.fit(), AUC keeps increasing with every iteration reaching 250,000 iterations. I limited the max iterations to 220,000. 

```
params = {'loss_function':'Logloss', 
          'eval_metric':'AUC', 
          'cat_features':cat_features,
          'verbose': 50, 
          'task_type': 'GPU',
          'early_stopping_rounds': 500,
          'border_count': 32,
          'random_seed': 1,
          "iterations": 220000
         }
```
As soon as it finishes the training, it shows this error message:
```
silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 1399, in _fit
    train_params["init_model"]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 961, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 2629, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2685, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/model/model.cpp:265: To many features in model, ask catboost team for support
```
I checked catboost/catboost/libs/model/model.cpp and found that there is a limit of 0xffff on the features.

Can this value be configurable? Or there is a specific reason for it to be 0xffff?

catboost version: 0.16.2
Operating System: Ubuntu 16.04.4
CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
GPU: Nvidia Tesla V100

**Comment by annaveronika** [comment]
It looks like there have been created too many different feature combinations with categorical features. You can control it by reducing max_ctr_complexity (it's 4 by default, set it to 2 or 3).
