### ISSUE TITLE
Catboost.cv in R does not work

### ISSUE THREAD

**Issue by acmilannesta** [catboost/catboost#946]
Problem: Fail to call catboost.cv
catboost version: catboost R package (0.16)
Operating System: Win10
CPU: 6 cores
# GPU: 0

When I try to run catboost.cv and use AUC metrics like following:
```
library(catboost)
library(dplyr)

cat_tr = catboost.load_pool(data = train %>% select(-c(ID_code, target)),
                            label = train$target)
catboost.cv(cat_tr,
                    params = list(loss_function='Logloss',
                                  eval_metric='AUC',
                                  iterations=5,
                                  l2_leaf_reg=100,
                                  depth=5,
                                  use_best_model=T),
                    fold_count = 3,
                    stratified = T,
                    )
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 5

However, if I remove the "eval_metric", the error disappears.

**Comment by annaveronika** [comment]
The error doesn't seem to be related to catboost. The error appears in R when you are creating the dataframe. Could you please check that your data matrix is rectangular and that creating data works fine?
If you will still have the error, please build a small reproducing example with data, so that we can reproduce and fix it.

**Comment by acmilannesta** [comment]
Thanks for the response. Here is the reproducible example:

dataset = matrix(c(sample(1:100, 20, T), 
                   sample(1:100, 20, T), 
                   sample(1:100, 20, T)),
                 nrow=20, 
                 ncol=3, 
                 byrow = TRUE)

label_values = sample(0:1, 20, T)
pool = catboost.load_pool(apply(dataset, 2, as.numeric), label = label_values)
catboost.cv(pool, params = list(iterations = 10,
                                loss_function = 'Logloss',
                                eval_metric='AUC'))

which output as the following:
0:	test: 0.5458333	best: 0.5458333 (0)	total: 739ms	remaining: 6.65s
1:	test: 0.3555556	best: 0.5458333 (0)	total: 1.55s	remaining: 6.2s
2:	test: 0.3888889	best: 0.5458333 (0)	total: 2.2s	remaining: 5.14s
3:	test: 0.3250000	best: 0.5458333 (0)	total: 3.08s	remaining: 4.62s
4:	test: 0.3250000	best: 0.5458333 (0)	total: 3.87s	remaining: 3.87s
5:	test: 0.3250000	best: 0.5458333 (0)	total: 4.67s	remaining: 3.11s
6:	test: 0.3250000	best: 0.5458333 (0)	total: 5.53s	remaining: 2.37s
7:	test: 0.3250000	best: 0.5458333 (0)	total: 6.37s	remaining: 1.59s
8:	test: 0.3250000	best: 0.5458333 (0)	total: 7.5s	remaining: 833ms
9:	test: 0.2472222	best: 0.5458333 (0)	total: 8.36s	remaining: 0us
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 10

**Comment by annaveronika** [comment]
Thanks, we'll look into this!

**Comment by annaveronika** [comment]
This is fixed.

**Comment by acmilannesta** [comment]
Great. Thx so much!
