### ISSUE TITLE
Catboost crashing on v0.16.3

### ISSUE THREAD

**Issue by AdrianAntico** [catboost/catboost#947]
Problem: Models are fitting terribly
catboost version: 16.3
Operating System: Windows
CPU: Intel 7700
# GPU: geForce 1080ti

On top of the error message below, the models results are terrible. I don't know if this is a catboost issue or something wrong with my GPU / cuda / ?

The below error message comes from running a catboost regression with eval_metric = "MAE" and task_type = "GPU"

0:	learn: 0.9850852	test: 1.0046840	best: 1.0046840 (0)	total: 30ms	remaining: 1.47s
10:	learn: 0.9699316	test: 0.9906618	best: 0.9906618 (10)	total: 214ms	remaining: 757ms
20:	learn: 0.9566828	test: 0.9792318	best: 0.9792318 (20)	total: 410ms	remaining: 567ms
30:	learn: 0.9431929	test: 0.9672433	best: 0.9672433 (30)	total: 593ms	remaining: 364ms
40:	learn: 0.9291698	test: 0.9545774	best: 0.9545774 (40)	total: 782ms	remaining: 172ms
49:	learn: 0.9168736	test: 0.9434884	best: 0.9434884 (49)	total: 951ms	remaining: 0us
bestTest = 0.9434883881
bestIteration = 49
Shrink model to first 50 iterations.
[1] 3
Application terminated with error: CatBoostIsNullHandle_R+240076 (0x7FF9F830911C)
??+0 (0x7FF9F7FA5D2E)
??+0 (0x7FF9F80256FA)
??+0 (0x7FF9F8033493)
CatBoostIsNullHandle_R+6867851 (0x7FF9F895B2DB)
CatBoostIsNullHandle_R+6837344 (0x7FF9F8953BB0)
CatBoostIsNullHandle_R+6838424 (0x7FF9F8953FE8)
??+0 (0x7FF9F81D5D9A)
??+0 (0x7FF9F81CEFBB)
CatBoostIsNullHandle_R+18247676 (0x7FF9F943574C)
BaseThreadInitThunk+20 (0x7FFA72EE4034)
RtlUserThreadStart+33 (0x7FFA74873691)

(class TCatBoostException) c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/cuda/cuda_lib/cuda_base.h:243: CUDA error 4: unspecified launch failure

**Comment by annaveronika** [comment]
Could you provide the full code that you are running?
Does the error reproduce if running several times?
What is your GPU?
Does it happen only in R or if you run the same in python it reproduces also?
