### ISSUE TITLE
mistaken description for categorical values creation

### ISSUE THREAD

**Issue by Sandy4321** [catboost/catboost#948]
Problem: mistaken description for categorical values creation
Several months ago I showed you that user manual description for categorical values calculation algorithm is mistaken, you agreed with me and asked help, I suggested you help but you ignored this   (Unfortunately I can not find this issue link, did you removed it?) . In any case you can help yourself by using this link
 http://contrib.scikit-learn.org/categorical-encoding/catboost.html
  CatBoost Encoder. Just use code from this  link to understand how your categorical values creation algorithm works. Seems to be you have bad communication between algorithm author and programmers. Also you underestimate how  knowledge of your algorithms important for your cod use. Sorry for criticism, but seems to be it is only way to draw you attention to this problem... 
catboost version: 15
Operating System:Windows
CPU: i7
# GPU:

**Comment by annaveronika** [comment]
http://contrib.scikit-learn.org/categorical-encoding/catboost.html
This implementation is wrong, our documentation is correct, but not very detailed, which we plan to improve when we have time.
If you have resources to go through catboost code and understand details of categorical feature encodings, you are welcome to improve existing documentation. If you want developers to improve it, then you just need to wait until we have time for it.

**Comment by Sandy4321** [comment]
sounds great, what is the link to code for catboost algorithm for for categorical values calculation algorithm and its  description?

**Comment by annaveronika** [comment]
You can look into libs/algo/online_ctr.* to make yourself familiar with the ctr code.

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/issues/436 - here is the actual part of categorical features documentation, that is missing in the docs.
The algorithm itself is explained in the docs and in the papers that can be found in Educational materials section.

**Comment by Sandy4321** [comment]
provided link 
https://github.com/catboost/catboost/issues/436
is not for algorithm description
original issue located at link
https://github.com/catboost/catboost/issues/836
referenced code
https://github.com/catboost/catboost/blob/master/catboost/libs/algo/online_ctr.cpp
written in secret style : not comments
so code is not readable
key idea for whole project to introduce new categorical encoding and you keep the description is secret - not nice
can in any case make efforts to describe your algorithm without mistakes 
 
and it is not as you wrote 
"There is a separate issue where we plan to improve categorical features descriptions."
it is to fix mistakes
