### ISSUE TITLE
Issues applying model built with catboost.caret

### ISSUE THREAD

**Issue by lvbradley** [catboost/catboost#95]
Using your 'Select hyperparameters' code in your R package documentation I have been able to build a model using cart's train function and the catboost.caret method. However, when I come to apply out the model on my holdout data using caret's predict function (pred <- predict(catboost_model, holdout_dataset)) my R session crashes and aborts. Am I missing something here? Could you add an example of how to apply a catboost model that was built using catboost.caret?

**Comment by nikitxskv** [comment]
@lvbradley Hello!
Well, we will do it.
In the meantime, could you send the sample code, data and error message?

**Comment by khrisanfov** [comment]
I confirm that it happens when columns order doesn't match the order in the training set. For example: in case I trained model using data.frame(A = c(1, 2, 3 ...), B = c("a", "b", "c" ...), predict will crush R if I will be using data.frame(B = c("a"), A = c(1))

```
*** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("CatBoostPredictMulti_R", model$handle, pool, verbose,     type, tree_count_limit, thread_count)
 2: catboost.predict(modelFit, pool, type = "Probability")
 3: method$prob(modelFit = modelFit, newdata = newdata, submodels = param)
 4: probFunction(method = object$modelInfo, modelFit = object$finalModel,     newdata = newdata, preProc = object$preProcess)
 5: predict.train(catboost.fit, data.frame(...), type = "prob")
 6: predict(catboost.fit, data.frame(...), type = "prob")
```

**Comment by nikitxskv** [comment]
@lvbradley 
We added the example of applying caret catboost model at the end of our [tutorial](https://github.com/catboost/catboost/blob/master/catboost/tutorials/catboost_r_tutorial.ipynb).

@khrisanfov 
It is not allowd to apply formula when the order of the columns in testing set differs from the order of the columns in training set.
We will add this information to our documentation.
