### ISSUE TITLE
binaryFeatures range exception on CPP model format and bad results with json model format (repro files attached)

### ISSUE THREAD

**Issue by rcohendw** [catboost/catboost#951]
Problem: With some test data (attached), I'm getting a crash when calling ApplyCatboostModel() on the CPP model format, and getting broken results from the JSON model format. The BIN model format, however, works correctly with this data.
catboost version: 0.16.3
Operating System: Windows 10 Pro
CPU: Intel Core i7-6920HQ
GPU: AMD Radeon Pro 460 (not used)

Repro steps (with attached data):
1) Train and export to bin and cpp model files.

catboost fit --learn-set train_mean_690324890.tsv --column-description train_690324890.cd --iterations 200 --model-format CPP --model-file model_mean_690324890.bin

2) Train using same data and export to json model file.

catboost fit --learn-set train_mean_690324890.tsv --column-description train_690324890.cd --iterations 200 --model-format json --model-file model_mean_690324890.json

3) Evaluate first two training samples using bin model file.  Results are correct.

catboost calc --model-path model_mean_690324890.bin --input-path test.tsv --column-description predict_690324890.cd --output-path test_out_bin.tsv

4) Evaluate first two training samples using json model file.  Results are broken!

catboost calc --model-path model_mean_690324890.json --input-path test.tsv --column-description predict_690324890.cd --output-path test_out_json.tsv

5) CPP file (model_mean_690324890.bin.cpp) crashes in ApplyCatboostModel() with array range exception on binaryFeatures
Line 466: binaryFeatures[binFeatureIndex] |= (unsigned char)(hash == model.OneHotHashValues[i][borderIdx]) * (borderIdx + 1);
binFeatureIndex = 4, but binaryFeatures.size() == model.BinaryFeatureCount == 4

unsigned int FloatFeatureCount = 2;
unsigned int CatFeatureCount = 3;
nsigned int BinaryFeatureCount = 4;

(2 + 3) > 4 !
Also, it may be relevant that FloatFeatureBorders[0].size() == 0.

Thank you for catboost and for your help!
Test files and repro batch files are attached.

Best,
Rob

[cpp_and_json_bug.zip](https://github.com/catboost/catboost/files/3498394/cpp_and_json_bug.zip)

**Comment by rcohendw** [comment]
FYI, for the C++ case, this modification of the generated C++ code appears to avoid the crash and generate the right values:

Old:
```
    /* Binarize features */
    std::vector<unsigned char> binaryFeatures(model.BinaryFeatureCount, 0);
    unsigned int binFeatureIndex = 0;
    {
        /* Binarize float features */
        for (size_t i = 0; i < model.FloatFeatureBorders.size(); ++i) {
            for (const float border : model.FloatFeatureBorders[i]) {
                binaryFeatures[binFeatureIndex] += (unsigned char)(floatFeatures[i] > border);
            }
            ++binFeatureIndex;
        }
    }
```

Modified:
```
    /* Binarize features */
    std::vector<unsigned char> binaryFeatures(model.BinaryFeatureCount, 0);
    unsigned int binFeatureIndex = 0;
    {
        /* Binarize float features */
        for (size_t i = 0; i < model.FloatFeatureBorders.size(); ++i) {
            if (model.FloatFeatureBorders[i].size() > 0) {
                for (const float border : model.FloatFeatureBorders[i]) {
                    binaryFeatures[binFeatureIndex] += (unsigned char)(floatFeatures[i] > border);
                }
                ++binFeatureIndex;
            }
        }
    }
```

Please keep in mind these things:
1) I don't know the code well enough to know if this fix is actually correct.
2) I don't know if other uses of binaryFeatures require similar fixes.
3) This doesn't address the (presumably related) problem with the JSON models generating incorrect results.

**Comment by annaveronika** [comment]
Thanks a lot for the report and for the reproducible example! We'll look into this!

**Comment by ek-ak** [comment]
Thank for the issue! The fix is on github now.

**Comment by annaveronika** [comment]
It will be out on pypi in the next minor release 0.18.1
