### ISSUE TITLE
"--fstr-file" combined with "--model-format cpp" crashes catboost.exe

### ISSUE THREAD

**Issue by rcohendw** [catboost/catboost#952]
Problem: Combining the --fster-file and --model-format cpp command line options causes a crash.
catboost version: 0.16.3
Operating System: Windows 10 Pro
CPU: Intel Core i7-6920HQ
GPU: AMD Radeon Pro 460 (not used)

This crashes catboost.exe:

catboost fit --learn-set catboost\train_mean_33474290.tsv --column-description catboost\train_33474290.cd --iterations 100 --fstr-file catboost\fstr.tsv --model-format cpp --model-file catboost\model_mean_33474290.bin

But this works fine ("CatboostBinary,cpp" insdead of "cpp"):

catboost fit --learn-set catboost\train_mean_33474290.tsv --column-description catboost\train_33474290.cd --iterations 100 --fstr-file catboost\fstr.tsv --model-format CatboostBinary,cpp --model-file catboost\model_mean_33474290.bin

Thanks!
Rob

**Comment by annaveronika** [comment]
Files are in this issue https://github.com/catboost/catboost/issues/951

**Comment by annaveronika** [comment]
Thanks for the report, we'll look into this!

**Comment by rcohendw** [comment]
More specifically, it looks like --fstr-file crashes whenever the _first_ model format listed is cpp.  If the first model format listed is either CatboostBinary or json, it prevents the crash.

So:
Crash: --fstr-file fstr.tsv --model-format cpp
No crash: --fstr-file fstr.tsv --model-format CatboostBinary,cpp
Crash: --fstr-file fstr.tsv --model-format cpp,CatboostBinary
No crash: --fstr-file fstr.tsv --model-format json,cpp
No crash: --fstr-file fstr.tsv --model-format json,CatboostBinary,cpp
Crash: --fstr-file fstr.tsv --model-format cpp,json,CatboostBinary
No crash: --fstr-file fstr.tsv --model-format json,cpp,CatboostBinary

**Comment by ek-ak** [comment]
Hello!
If you want fstr, you should specify  deserializable model format in list of saving model formats, i. e. CatboostBinary.  `cpp` model format is not deserializable, all other listed  combination are ok now.

**Comment by rcohendw** [comment]
> Hello!
> If you want fstr, you should specify deserializable model format in list of saving model formats, i. e. CatboostBinary. `cpp` model format is not deserializable, all other listed combination are ok now.

Thanks!
For clarity, is it safe to work around the crash with "--model-format CatboostBinary,cpp"?
It seems to work fine.
