### ISSUE TITLE
No module named '__builtin__'

### ISSUE THREAD

**Issue by ibuda** [catboost/catboost#953]
I am calling:
```
model.get_feature_importance(X_test, type='ShapValues')
```
and getting the following error with the updated Catboost:
```
-----------------------------------------------------------
ModuleNotFoundError       Traceback (most recent call last)
<ipython-input-53-7163a82dee4a> in <module>
----> 1 shap_values = model_with_early_stop1.get_feature_importance(X_test, type='ShapValues')
      2 print(shap_values.shape)
      3 expected_value = shap_values[0,-1]
      4 shap_values = shap_values[:,:-1]
      5 print(shap_values.shape)

~/prb/anaconda3/lib/python3.7/site-packages/catboost/core.py in get_feature_importance(self, data, type, prettified, thread_count, verbose, fstr_type, shap_mode)
   2016         else:
   2017             if data is not None and not isinstance(data, Pool):
-> 2018                 from __builtin__ import type as typeof
   2019                 raise CatBoostError("Invalid data type={}, must be catboost.Pool.".format(typeof(data)))
   2020 

ModuleNotFoundError: No module named '__builtin__'
```

Problem: ModuleNotFoundError: No module named '__builtin__'
catboost version: '0.16.4'
Operating System: Ubuntu 19.04
CPU: Intel® Core™ i5-7400 CPU @ 3.00GHz × 4
GPU: GeForce GT 710/PCIe/SSE2

**Comment by ibuda** [comment]
Apparently, the __builtin__ module was renamed to builtins in Python3.
Changing the code line:
`from __builtin__ import type as typeof`
to:
`from builtins import type as typeof`
solved my issue.

**Comment by AbhinavanT** [comment]
Shouldn't this remain open? You could submit PR with the change since it should be reflected in the master

**Comment by ibuda** [comment]
@AbhinavanT yup, was planning to, but there already is one PR covering this. :)
