### ISSUE TITLE
catFeaturesHashToString hash collisions with only 9k unique categorical feature values

### ISSUE THREAD

**Issue by rcohendw** [catboost/catboost#959]
Problem: catFeaturesHashToString uses a 32-bit hash value, and doesn't appear to detect and handle collisions (unless I missed something), leading to high probability of collisions under some usage conditions.
catboost version: 1.6.3

Hash collision probability exceeds 1% for a 32-bit hash after only sqrt(2*(2^32)*0.01) = 9,268 unique values.
Source: https://www.ilikebigbits.com/2018_10_20_estimating_hash_collisions.html

It appears that catFeaturesHashToString using a 32-bit value without special handling for collisions, which means that collisions get into risky territory under some usage conditions.  1% collision probability at 9,268 unique categorical feature values.

I'm not sure from the code if that means 9k unique values per categorical feature, or if there would be a problem with 9k unique values across all categorical features.  9k unique values across all cat features is, of course, more problematic.

A 64-bit hash value would move this to comfortable territory of sqrt(2*(2^64)*0.01) = 607 million unique categorical feature values.

Alternately, using IDs rather than hashes would allow up to 4 billion (2^32) unique categorical feature values to be safely represented with 32-bit integers.  That would be preferable for compact model files, although it requires storing the strings in a look-up table.

Thanks!

**Comment by annaveronika** [comment]
There should not be a problem if there will be a collision. But it we increase number of bits in hashes, then the model size will grow x2, we really don't want that, because you might get a very big model.
As we don't plan to increase number of bits, I'll have to close this issue as won't fix. Sorry.
