### ISSUE TITLE
CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/libs/data_new/quantization.cpp:1453: All features are either constant or ignored

### ISSUE THREAD

**Issue by YasmineHamdar** [catboost/catboost#961]
Hello, 

I am trying to fit my CatBoost Model and I keep getting this error. Can anyone help?

Thanks

**Comment by annaveronika** [comment]
This means that your train features are constant.

**Comment by rcohendw** [comment]
Use --allow-const-label

**Comment by annaveronika** [comment]
Hope this has helped! Let us know if you have more questions.

**Comment by Rikywenok** [comment]
> Use --allow-const-label

Where it should be used?

**Comment by spike8888** [comment]
You can use it like this:
`regressor = CatBoostRegressor(allow_const_label=True)`
It doen't eliminate error on my side tho.

**Comment by stiv-yakovenko** [comment]
This doesn't help me either

**Comment by BabuRao69420** [comment]
> You can use it like this: `regressor = CatBoostRegressor(allow_const_label=True)` It doen't eliminate error on my side tho.

Same here, doesn't help

**Comment by ek-ak** [comment]
> Same here, doesn't help
Hello! Are you 100% sure, that there are not constant not ignored features in you dataset? If there are good feature -- it is bug and we need a reproducer, and if there are only constant features -- why do you need such dataset?
