### ISSUE TITLE
Normalized gini not shown in plot (and also model.best_score_)

### ISSUE THREAD

**Issue by LSinev** [catboost/catboost#962]
Problem: Normalized gini not shown in plot (and also model.best_score_)
catboost version: 0.16.4
Operating System: Win10
Python 3.6.9
params set to
```
    'loss_function': 'Logloss',
    'custom_metric': ['MCC', 'BrierScore', 'AUC:hints=skip_train~false', 'AUC:hints=skip_train~false;use_weights=false',
                      'NormalizedGini:hints=skip_train~false;use_weights=false',
                     'NormalizedGini:hints=skip_train~false'],
    'eval_metric': 'MCC:use_weights=false',
```
but `model.best_score_` outputs is like:
```
{'AUC:use_weights=false': 0.5010702032687193, 'Logloss': 0.6931443860809862, 'BrierScore': 0.24999860267006002, 'MCC:use_weights=false': 0.004238939522563364, 'AUC': 0.5010702032687193, 'MCC': 0.0027681553711513163}
```
Sample *.ipynb attached
[NormalizedGinibug.zip](https://github.com/catboost/catboost/files/3513547/NormalizedGinibug.zip)

**Comment by annaveronika** [comment]
Thanks for the report, we'll look into this!

**Comment by annaveronika** [comment]
This is fixed now in code and will be out on pypi in the next minor release.
