### ISSUE TITLE
Got lot of times «Floating point exception (core dumped)» on model.predict

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#971]
Problem: Got lot of times «Floating point exception (core dumped)» on model.predict. 
catboost version:  0.16.5
Operating System: Linux 64

Demo for the bug  — Full Python3 VirtualEnv with pickled data and demo script 
(run wtf.sh)  →  https://cloud.mail.ru/public/5jZr/zZWMU2Qgh

**Comment by david-waterworth** [comment]
I'm seeing this a lot as well - I'm not sure if it's fit or predict though. It's only on 1 of my 2 machines (dual 20180Ti GPU), the single 2080Ti doesn't have a problem.

**Comment by sswetank-CS** [comment]
Any resolution on this ? or do we know what's the root cause issue here?

**Comment by vectosaurus** [comment]
I too am facing this same issue on calling `predict`.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Could you please provide a reproducer, and let us know the CPU model name where you get FPE?
CatBoost 0.23.2 works just fine on Intel(R) Xeon(R) CPU E5-2650 v2.

**Comment by kizill** [comment]
I've just found that this bug was fixed exactly in 0.17.5 release. Closing as fixed.
