### ISSUE TITLE
Expose GPU evaluation functionality in Python bindings

### ISSUE THREAD

**Issue by DanielLumb** [catboost/catboost#972]
Problem: Cannot find any documentation about running prediction / evaluation of catboost models on GPU.
catboost version: 0.16+

In release notes for 0.16 it was stated that:
- "It is now possible to apply model on GPU"

which is a great feature but I could not find any information or API which allowed that (using catboost mainly from Python).

I commented about that in issue #560 , which is however quite old and might not catch enough attention.

Can anyone give a hint about how to use that very promising new feature? Thank you in advance!

**Comment by kizill** [comment]
Hello! I currently implemented GPU evaluation in C API for prediction (and in C++ wrapper) https://github.com/catboost/catboost/blob/master/catboost/CatboostModelAPI.md#c-api
Just load model and call `EnableGPUEvaluation` on model handle or from C++ wrapper class. I'm planning to add python GPU evaluation possibility in next major release, so stay tuned.

**Comment by DanielLumb** [comment]
Thanks a lot for your fast & accurate reply! 
Then I wait utill you expose that in python API and already curious about what kind of evaluation speedup is to be expected by running that on GPU.
Thanks a lot for the great job you're guys doing with this library!

**Comment by DanielLumb** [comment]
Could not find the `EnableGPUEvaluation` function exposed in Python bindings for catboost 0.17. 
I will rename this issue to a more appropriate name so it can stay open until resolution.
Thank you in advance!

**Comment by DanielLumb** [comment]
Apparently this issue is not gaining too much community interest so far - so I just wanted to ask whether it would be feasible for you to implement a somewhat cheaper, low-tech solution?

For example, even a global flag or environment variable would be enough (and great!) to enable GPU prediction. And things like device selection could be managed in other ways, outside of catboost - turning it hopefully maybe into a 1-(or 2) liner, thus not taking too much of your valuable time.

Greetings and thanks!

**Comment by annaveronika** [comment]
There is no low-tech solution. We will implement this feature, when we'll have someone available for this task, currently there are some other things in top priority. We will implement it though, sorry for the wait!

**Comment by LukeArrigoni** [comment]
Any new movement on this feature?

**Comment by andrey-khropov** [comment]
Released in 0.26.

**Comment by DanielLumb** [comment]
Thank you a lot (and especially big thanks for @rakalexandra!) for implementing this!!

While this seems currently being blocked by some GPU/kernel issues in 0.26 (as reported in #1735) - I'm really excited to be able to finally test this functionality.
Big thanks for everyone!

**Comment by 814850963** [comment]
> Thank you a lot (and especially big thanks for @rakalexandra!) for implementing this!!
> 
> While this seems currently being blocked by some GPU/kernel issues in 0.26 (as reported in #1735) - I'm really excited to be able to finally test this functionality. Big thanks for everyone!

Can you give me some code or hint to use GPU prediction?
