### ISSUE TITLE
Compile error on  Nvidia Jetson Nano

### ISSUE THREAD

**Issue by lk1983823** [catboost/catboost#975]
Problem: follow the instruction of "Build from source" on step 6, I use ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda-10.0 and an error shows:
`ERROR: [Errno 8] Exec format error: '/home/lly2014/.ya/tools/b6b1bb5ef0_d/ya-bin'`
catboost version: 0.16.4
Operating System:  Ubuntu 16.04
CPU:  aarch64-linux-gnu
GPU: Maxwell arch with cuda-10.0
Does catboost support  aarch64? Thanks!

**Comment by annaveronika** [comment]
We don't support ya make on this platform. Would cross-compilation work for you?

**Comment by lk1983823** [comment]
So can you share how to do it? Thx.


发自我的 iPhone

**Comment by kizill** [comment]
We found our cross-compilation toolkit failing while compiling with clang7 for aarch64 platform, later it will work like ```./ya make --target-platform=clang7-linux-aarch64 catboost/app/``` from x86_64 linux. We will notice you after fixing compilation issues.

**Comment by nylocx** [comment]
Are there any news on this? I have a Jetson Nano Cluster with Kubernetes running and would love to run some catboost models on it.

**Comment by bobrik** [comment]
@nylocx you can use cross-compilation like @kizill described.

**Comment by nylocx** [comment]
Nice to hear that the cross compilation issue is solved. I guess I will come back to this some time in the future.

**Comment by kizill** [comment]
Now everything works just as planned, sorry for that crazy delay 🙀
To compile without CUDA support with cross-compilation toolkit:
```
./ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 catboost/app
```
To compile with SBSA CUDA with cross-compile toolkit:
```
./ya make -r -DHAVE_CUDA=yes --target-platform default-linux-aarch64 catboost/libs/model_interface/ -DCUDA_ROOT=/usr/local/cuda-11.3/
```
So now i'm closing as DONE 🥳
