### ISSUE TITLE
Unclear on how catboost treats categorical variables

### ISSUE THREAD

**Issue by aamster** [catboost/catboost#976]
In the documentation https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html#algorithm-main-stages_cat-to-numberic at step 3 it gives several ways catboost treats categorical variables. Does it choose one of these methods? Does it try all of them? How to see which method was selected and what the resulting values are? 

I'm assuming the same preprocessing for categorical variables is done to the test set? Related is this issue https://github.com/catboost/catboost/issues/578 which is still open and regards how catboost handles test set categorical preprocessing. 

The documentation also says "The method is determined by the starting parameters." Which starting parameters? Which method?

Furthermore, how are categorical combinations created? Is this random? 

Thanks,
Adam

**Comment by kizill** [comment]
We have a great [blog post](https://towardsdatascience.com/categorical-features-parameters-in-catboost-4ebd1326bee5)  and [tutorial about categorical features parameters](https://github.com/catboost/tutorials/blob/master/categorical_features/categorical_features_parameters.ipynb) you can check read to understand categorical features processing in CatBoost.
