### ISSUE TITLE
Incorrect output when converting LightGBM onnx model to CatBoost model

### ISSUE THREAD

**Issue by NProkoptsev** [catboost/catboost#977]
Problem: Incorrect output when converting LightGBM onnx model to CatBoost model
catboost version: 0.16.5
Operating System: MacOS 10.14.6
CPU: Intel Core i7-8559U CPU @ 2.70GHz

Train LightGBM
```
import lightgbm as lgb
import numpy as np
parameters = {
        'objective': 'regression'
}
X = np.random.rand(100,2)
y = 2*X[:,0] + 3 * X[:,1]
dataset = lgb.Dataset(X,y)
model = lgb.train(parameters,train_set  = dataset)
model.predict(X[:5])
```

> array([3.27468099, 4.3142817 , 1.3207617 , 2.81700226, 2.23956626])

Convert Model to onnx
```
import onnxmltools
from onnxmltools.convert.common.data_types import FloatTensorType
model_onnx = onnxmltools.convert_lightgbm(model, name='LightGBM',initial_types=[('input', FloatTensorType([0,2]))])
onnxmltools.utils.save_model(model_onnx, 'LightGBM.onnx')
```

Check predictions
```
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("LightGBM.onnx")
pred_onx = sess.run(None, {"input": X[:5].astype(np.float32)})
print("predict", pred_onx[0])
```

> predict [[3.2746809]
>  [4.314282 ]
>  [1.3207617]
>  [2.8170023]
>  [2.2395663]]

Convert to catboost and check predictions
```
from catboost import CatBoost
model_cb = CatBoost()
model_cb = model_cb.load_model('LightGBM.onnx', format='onnx')
model_cb.predict(X[:5].astype(np.float32))
```
> array([2.20379168, 0.77787595, 3.70520718, 2.17169584, 2.82726264])

As you can see the pedictions of lightGBM and onnx matches, however CatBoost gives different predictions

**Comment by annaveronika** [comment]
This is fixed in code and will be in the next release in a few days. You can build from source now. Sorry for inconvenience and thanks a lot for pointing this out!
