### ISSUE TITLE
Is it possible to implement learning rate decay in catboost

### ISSUE THREAD

**Issue by BovenPeng** [catboost/catboost#979]
Problem: Is it possible to implement learning rate decay in catboost
catboost version: 0.15.2
Operating System: Ubuntu 16
CPU: Intel® Core™ i7-8086K 
GPU: 1080Ti

I want to ask if there is possible to implement to learning rate decay in catboost to train fast and in the same accuracy situation.

**Comment by annaveronika** [comment]
Hi! We did experiments with learning rate decay and have encountered that it decreases quality - it is always better to use lower learning rate from the start. So we don't plan to add this functionality. But you can use init_model parameter or baseline to do this: you train first model with first learning rate, then pass it as init_model to the next one and so on.

**Comment by annaveronika** [comment]
With that I'm closing the issue as won't fix. Hope the suggested solution works for you!

**Comment by BovenPeng** [comment]
Thanks for your reply. 
> But you can use init_model parameter or baseline to do this: you train first model with first learning rate, then pass it as init_model to the next one and so on.

I will try this later to accelerate the training speed without decreasing quality.
