### ISSUE TITLE
Issue in installing (using pip or conda) catboost package

### ISSUE THREAD

**Issue by devarshi11github** [catboost/catboost#980]
Problem: Trying to install 'catboost' using the Anaconda command prompt using pip install. It installs over there but when I try to import CatBoostRegressor, it shows the following error

> 
AttributeError: type object '_catboost._FloatArrayWrapper' has no attribute '__reduce_cython__'
> 

Any reason as to why this is happening

catboost version:
Operating System: Windows 10 Pro, 64-bit operating system
CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz 2.11GHz
# GPU:

**Comment by kizill** [comment]
Please, upgarde numpy. We are planning to add more meaningfull error for that case, but now import errors on catboost lib initialization looks like that...

**Comment by annaveronika** [comment]
I hope this has helped! Let us know if you have more questions.

**Comment by devarshi11github** [comment]
Yes it was helpful, thanks for the support. Sorry could not reply earlier
