### ISSUE TITLE
MSE on catboost

### ISSUE THREAD

**Issue by RonBig** [catboost/catboost#982]
Problem:MSE on catboost
Hi
I saw the following post
https://github.com/catboost/catboost/issues/140
And I do not quite understand what does it mean that catboost uses MSE...
It is not in the supported list of loss functions at the moment.

I wanted to experiment with using different loss functions and I wonder if I need to implement MSE as a custom function or is there a way to do it using different parameters

Thanks

**Comment by annaveronika** [comment]
Sorry for a long response! You need to use loss_function='RMSE'

**Comment by annaveronika** [comment]
I hope this answers your question. Closing the issue, let us know if you have other questions.

**Comment by RonBig** [comment]
Hi
Tghank you for your message, I missed the reply :(

Now that I checked, I got the following error
CatBoostError: Invalid loss_function='RMSE': for classifier use Logloss, CrossEntropy, MultiClass, MultiClassOneVsAll or custom objective object

**Comment by annaveronika** [comment]
You need to use CatBoostRegressor instead of CatBoostClassifier
