### ISSUE TITLE
Error: rsm on GPU is supported for pairwise modes only

### ISSUE THREAD

**Issue by rcohendw** [catboost/catboost#983]
Problem: RSM on GPU would be very useful!
catboost version: 0.16.5
Operating System: Windows
CPU: any
# GPU: any

RSM is such a useful feature for reducing training time with higher numbers of features, while maintaining quality.  It would be very useful if it were possible to use it on the GPU.

**Comment by annaveronika** [comment]
> RSM is such a useful feature for reducing training time with higher numbers of features, while maintaining quality. It would be very useful if it were possible to use it on the GPU.

This is exactly right, this parameter helps improving the training speed. For not pairwise modes GPU speed should not be an issue, so we decided to not implement this parameter for this mode.

**Comment by annaveronika** [comment]
We don't plan to add this functionality, thus closing as Won't fix.

**Comment by Garfield2013** [comment]
I get the same error - but I don't understand what you mean by "pairwise GPU"?

**Comment by annaveronika** [comment]
pairwise modes are PairLogitPairwise and YetiRankPairwise

**Comment by GabrielFo** [comment]
> > RSM is such a useful feature for reducing training time with higher numbers of features, while maintaining quality. It would be very useful if it were possible to use it on the GPU.
> 
> This is exactly right, this parameter helps improving the training speed. For not pairwise modes GPU speed should not be an issue, so we decided to not implement this parameter for this modes.

Hello @annaveronika ,
The rsm parameter is a great parameter to limit overfitting, especially when you are trying to select the relevant features in your model based on their importances. 
Do you plan to add that feature for GPU?
Many thanks

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@GabrielFo Thanks for reminding! This may (or may not...) get planned for this summer.

**Comment by EvanZ** [comment]
I'm getting this error. I don't understand why. I'm not setting any rsm paramter:

`model = CatBoostClassifier(**params, cat_features=features, task_type="GPU", silent=True)`

**Comment by NisuSan** [comment]
> @GabrielFo Thanks for reminding! This may (or may not...) get planned for this summer.

Is this still in planning?

**Comment by andrey-khropov** [comment]
> I'm getting this error. I don't understand why. I'm not setting any rsm paramter:
> 
> `model = CatBoostClassifier(**params, cat_features=features, task_type="GPU", silent=True)`

Most likely you are setting `colsample_by_level` parameter which is a synonym of `rsm`: https://catboost.ai/en/docs/references/training-parameters/common#rsm

**Comment by lizhuoq** [comment]
@andrey-khropov Will this feature be added in 2025?

**Comment by andrey-khropov** [comment]
> [@andrey-khropov](https://github.com/andrey-khropov) Will this feature be added in 2025?

That's unlikely unless somebody volunteers to implement it.
