### ISSUE TITLE
model.classes_ is an empty list for classification problem

### ISSUE THREAD

**Issue by muggle14** [catboost/catboost#984]
Problem: model.classes_ is an empty list for classification problem
catboost version: 0.16.5
Operating System: 
CPU: Linux
# GPU:
[catboost_classes_issue.pdf](https://github.com/catboost/catboost/files/3578598/catboost_classes_issue.pdf)

Please help

**Comment by annaveronika** [comment]
This looks like a bug, thanks for reporting it. We are looking into this now.

**Comment by muggle14** [comment]
👍👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by annaveronika** [comment]
Current status:
We have fixed most of the problems here. One remaining problem is that if you have binary classification, you will have classes_ equal to 0, 1 independant from what were the correct classes.
But classes_ is not empty, is correct always for multiclass and has always correct dimension.
This fixes will be out in our next release catboost 0.18

**Comment by andrey-khropov** [comment]
Fixed by commit https://github.com/catboost/catboost/commit/480753c946c19e7bad2f8e9f54ec4dd20a35acc7. Will be on pypi in the next release.

**Comment by andrey-khropov** [comment]
Released in r0.20.2.
