### ISSUE TITLE
Is CatboostEvaluation deprecated?

### ISSUE THREAD

**Issue by aamster** [catboost/catboost#987]
Is CatboostEvaluation deprecated? There is a tutorial for feature selection using it at https://github.com/catboost/tutorials/blob/master/feature_selection/eval_tutorial.ipynb however I can't find it documented on the catboost site. Has it been replaced in favor of `get_feature_importance`?

**Comment by annaveronika** [comment]
It's not deprecated, we plan to improve interfaces and to write documentation.

**Comment by annaveronika** [comment]
Closing as a duplicate of https://github.com/catboost/catboost/issues/429
