### ISSUE TITLE
Speed of work with Sparse matrix has great potential for optimization

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#990]
Problem:
I tried to make cv (3 folds) with regression and sparse dataset:
<3256x26075 sparse matrix of type '<class 'numpy.float64'>'  with 234060 stored elements in Compressed Sparse Row format>. It is bag of word after TF-IDF.
Estimated work tome was about 20 hours. 

catboost version: 0.17
Operating System: Windows
CPU:

**Comment by andrey-khropov** [comment]
Did you run CV on CPU or on GPU?

**Comment by AndreyGurevich** [comment]
CPU

**Comment by kizill** [comment]
We've rolled out this speedup in 0.24.1, so closing this issue.
