### ISSUE TITLE
Grid search for multi-classification 

### ISSUE THREAD

**Issue by jennykathambi90** [catboost/catboost#993]
Problem: Applying grid search on multi-classification throws the following error:

CatBoostError: c:/goagent/pipelines/buildmaster/catboost.gittt/catboost/libs/labels/label_converter.cpp:97: Can't use uninitialized object of TLabelConverter

catboost version: 0.17

Operating System: Windows 10 64  bit

# CPU:
GPU:

**Comment by zoj613** [comment]
Got the same error too. I hope this gets a fix soon as I plan to use this for multiclass classification.

**Comment by annaveronika** [comment]
This is fixed in code now and will be out on pypi in the next minor release.

**Comment by jennykathambi90** [comment]
Thank Anna, you saved me a lot of agony. I hope that passing of class weights for grid-search is flawless since sklearn is a bit not user friendly when passing class weights during grid search.
