### ISSUE TITLE
Incorrect prediction from model with monotonic constraint.

### ISSUE THREAD

**Issue by afg101** [catboost/catboost#994]
Function `predict` return incorrect prediction:
Metrics are different: 0.3277 vs 0.4488
I think it has some bias...

![Screenshot_20190913_190321](https://user-images.githubusercontent.com/49680674/64877051-3f10a680-d659-11e9-9822-297d8e07f6cb.png)

catboost version: 0.17

**Comment by annaveronika** [comment]
Could you please copy text of the example above and attach it as text also, so that we don't have to retype it to reproduce the error?...

**Comment by afg101** [comment]
yes of course

```
from catboost.datasets import monotonic2
from catboost import Pool, CatBoostRegressor
from sklearn.metrics import mean_squared_error

train, test = monotonic2()
train_pool = Pool(data=train.drop(columns=['Target']), label=train['Target'])
test_pool = Pool(data=test.drop(columns=['Target']), label=test['Target'])
monotone_constraints_list = [-1, 1, -1, 1]

model = CatBoostRegressor(iterations=500, monotone_constraints=monotone_constraints_list)
model.fit(train_pool, verbose_eval=100)

print('\nMetrict after predic')
pred_train = model.predict(train_pool)

print('RMSE:         ', mean_squared_error(train['Target'], pred_train)**0.5)
print('target mean:  ', train['Target'].mean())
print('predict mean: ', pred_train.mean())
```

**Comment by afg101** [comment]
looks like prediction has bias, because after simple correction i have almost right prediction:
```
correcter_pred = pred_train-pred_train.min()
print(mean_squared_error(train['Target'], correcter_pred)**0.5)
 > 0.3321
```

**Comment by annaveronika** [comment]
In the latest release we've added start from average. Our algorithm for monotonic constraints uses shrinking model on every step (model_shrink_rate parameter is by default not zero). We shrink the starting bias during training, but not when saving the model. We'll fix it soon, for now please use model_shrink_rate=0. Or "boost_from_average" : False if you are using CatBoost class.

**Comment by annaveronika** [comment]
the fix is on pypi now
