### ISSUE TITLE
Catboost 0.16.0 onwards crashing on Google colab Python 3, GPU

### ISSUE THREAD

**Issue by agracian** [catboost/catboost#995]
Problem:
catboost version: 0.17.1
Operating System: Google colab Python 3, GPU

Most recent version which doesn't generate an error is 0.15.2

Error message:
![Screenshot 2019-09-16 08 54 22](https://user-images.githubusercontent.com/49029849/64942051-04c52600-d860-11e9-9f34-6e154a9e8352.png)

what() -> "catboost/libs/model/cpu/formula_evaluator.cpp:360: Unexpected block stride: 579712"

**Comment by kizill** [comment]
Hello! Can you help us with some code reproducing that problem?

**Comment by agracian** [comment]
Hi Guys,
Thanks for the quick response.. This chat window doesn't seem to support attaching .ipynb & .py files? What is the best way to send you the code?
Alex

**Comment by kizill** [comment]
I think you can share your Google colab notebook with a code?

**Comment by agracian** [comment]
**Shared colab .ipynb code**
https://colab.research.google.com/drive/12MgPiXwXOng74SS-Z6cUuHLOaRzTakWE

**Runs part of the way in 0.16.0 or greater (but runs ok in 0.15.2)**

Train Meta raw Catboost classifcation model for Rank.Total.Perf.Wgtd
Train Meta numeric Catboost Regression model for Rank.Total.Perf.Wgtd
Test Meta raw Catboost classifcation model for Rank.Total.Perf.Wgtd
Test Meta numeric Catboost Regression model for Rank.Total.Perf.Wgtd
Train Meta numeric Catboost classifcation model for Total.Perf.Wgtd.
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-3-68433dc089cd> in <module>()
      6   print('Train Meta ' + DATA_CLASS[i] + ' Catboost classifcation model for ' + TARGETS[i])
      7   X_data1 = pd.read_csv(PATH + 'data/csv files/train.factors.' + DATA_CLASS[i]+'.csv').iloc[:,1:]
----> 8   mOTr =predictCatboostClass(TARGETS[i], X_data1, DATA_CLASS[i], mOTr)
      9 
     10   print('Train Meta ' + DATA_REGRESS[i] + ' Catboost Regression model for ' + TARGETS[i])

<string> in predictCatboostClass(target, X_data, fStub, mO)

2 frames
/usr/local/lib/python3.6/dist-packages/catboost/core.py in _base_predict(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   1142 
   1143     def _base_predict(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose):
-> 1144         return self._object._base_predict(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   1145 
   1146     def _base_predict_multi(self, pool, prediction_type, ntree_start, ntree_end, thread_count, verbose):

_catboost.pyx in _catboost._CatBoost._base_predict()

_catboost.pyx in _catboost._CatBoost._base_predict()

CatBoostError: catboost/libs/model/cpu/formula_evaluator.cpp:363: Unexpected block stride: 53632

**catboost wrapper functions catboost_functions.py:**

# Python Catboost functions "Sat May 25 13:15:58 2019"
print("Loading Catboost functions from catboost_functions.py")

modelC = CatBoostClassifier()
modelR = CatBoostRegressor()

def buildCatboostClass(mTrF, mTrTc, mTeF, mTeTc, fOpath, fStub):
  
  mTrO =pd.DataFrame()
  mTeO =pd.DataFrame()
  cat_var= None
  if fStub=='raw': cat_var =CATEGORICAL
    
  for target in TARGETS:
    print('\nBuilding Catboost ' + fStub + 
          ' classifcation model for target ' + target)
    modelC.fit(
          mTrF, mTrTc[[target]],
          cat_features = cat_var,
          eval_set=(mTeF, mTeTc[[target]]),
          verbose=PRINT_EVERY
      )
    # Save model
    modelC.save_model(fOpath + 'models/' + target + '.' + fStub + '.catboost_class')

    # Run Train & test for Catboost Meta models later (Combining with R models)
    predictions_probs = modelC.predict_proba(mTrF)
    mTrO =pd.concat([mTrO, pd.DataFrame(predictions_probs).iloc[:,1:]], axis=1)

    predictions_probs = modelC.predict_proba(mTeF)
    mTeO =pd.concat([mTeO, pd.DataFrame(predictions_probs).iloc[:,1:]], axis=1)

  mTrO.columns =TARGETS
  mTrO =mTrO.add_suffix('_cat1_' + fStub)
  mTeO.columns =TARGETS
  mTeO =mTeO.add_suffix('_cat1_' + fStub)
  #np.savetxt(PATH + 'output/' + target + '.test.probs.csv', predictions_probs, delimiter=",")
  mTrO =mTrO.applymap("{0:.3f}".format)
  mTeO =mTeO.applymap("{0:.3f}".format)
  mTrO.to_csv(fOpath + 'csv files/train.' + fStub + '.probs.cat.csv', sep=',')
  mTeO.to_csv(fOpath + 'csv files/test.' + fStub + '.probs.cat.csv', sep=',')

  
  
def buildCatboostRegress(mTrF, mTrTr, mTeF, mTeTr, fOpath, fStub):
  
  mTrO =pd.DataFrame()
  mTeO =pd.DataFrame()
  cat_var= None
  if fStub=='raw': cat_var =CATEGORICAL
    
  for target in TARGETS:
    print('\nBuilding Catboost ' + fStub + 
          ' regression model for target ' + target)
    modelR.fit(
          mTrF, mTrTr[[target]],
          cat_features = cat_var,
          eval_set=(mTeF, mTeTr[[target]]),
          verbose=PRINT_EVERY
      )
    # Save model
    modelR.save_model(fOpath + 'models/' + target + '.' + fStub + '.catboost_regress')

    # Run Train & test for Catboost Meta models later (Combining with R models)
    predictions_rets = modelR.predict(mTrF)
    mTrO =pd.concat([mTrO, pd.DataFrame(predictions_rets)], axis=1)

    predictions_rets = modelR.predict(mTeF)
    mTeO =pd.concat([mTeO, pd.DataFrame(predictions_rets)], axis=1)

  mTrO.columns =TARGETS
  mTrO =mTrO.add_suffix('_catret_' + fStub)
  mTeO.columns =TARGETS
  mTeO =mTeO.add_suffix('_catret_' + fStub)
  mTrO =mTrO.applymap("{0:.4f}".format)
  mTeO =mTeO.applymap("{0:.4f}".format)
  mTrO.to_csv(fOpath + 'csv files/train.' + fStub + '.regress.cat.csv', sep=',')
  mTeO.to_csv(fOpath + 'csv files/test.' + fStub + '.regress.cat.csv', sep=',')
  return
  
def predictCatboostClass(target, X_data, fStub, mO):
  # load model
  modelC.load_model(PATH + 'runtime/models/'+target+'.'+fStub+'.catboost_class')

  if fStub=='raw':
      predictions_probs = modelC.predict_proba(Pool(X_data, cat_features=CATEGORICAL))
  else:
      predictions_probs = modelC.predict_proba(X_data)
      
  return pd.concat([mO, pd.DataFrame(predictions_probs).iloc[:,1:]], axis=1)

def predictCatboostRegress(target, X_data, fStub, mO):
  # load model
  modelR.load_model(PATH + 'runtime/models/'+target+'.'+fStub+'.catboost_regress')
   
  if fStub=='raw':
      predictions_rets = modelR.predict(Pool(X_data, cat_features=CATEGORICAL))
  else:
      predictions_rets = modelR.predict(X_data)
  return pd.concat([mO, pd.DataFrame(predictions_rets)], axis=1)

**Comment by agracian** [comment]
Shared the colab code, error output (under 0.17.1) & catboost_functions.py functions called by Meta Catboost.ipynb

Let me me know if you need further details. 
Alex

**Comment by agracian** [comment]
![Screenshot 2019-09-16 11 20 18](https://user-images.githubusercontent.com/49029849/64950736-039df400-d874-11e9-8ead-573a3d1da428.png)

**Comment by kizill** [comment]
The code in notebook is not full - at least i don't find `predictCatboostClass` and `predictCatboostRegress`

**Comment by agracian** [comment]
these functions are loaded from catboost_functions.py in line 24 of Meta Catboost.ipynb: 
exec(open(HOME+ "catboost_functions.py").read())

Here a shared link to the file on my gdrive:
https://drive.google.com/open?id=1lX10nWPj1qhCM29UnQEDJhvrBtzK9j_6

**Comment by agracian** [comment]
Hi Stanislav,
Any insight yet into what the problem is?
Best
Alex

**Comment by kizill** [comment]
Could you please try make one relatively independent code-snippet and pack it with model/data needed for reproducing the problem? Notebook and additional catboost_functions.py file that you shared are not enough :(

**Comment by agracian** [comment]
ok. will try in the next few days.

**Comment by agracian** [comment]
Hi Stanislav,

I seem to have found the problem & got my code working, but this maybe useful insight for you:

**Before I initialised CatBoostClassifier() external to the def predictCatboostClass() globally & predicted DIFFERNT models , using  load_model() for different trained models**

**modelC = CatBoostClassifier()**

def predictCatboostClass(target, X_data, fStub, mO):
  # load model
  modelC.load_model(PATH + 'runtime/models/'+target+'.'+fStub+'.catboost_class')
  predictions_probs = modelC.predict_proba(Pool(X_data, cat_features=CATEGORICAL))

This worked up till v 0.15.2, but crashed for later versions. Initialising CatBoostClassifier() locally each time within def predictCatboostClass() seems to have avoided it crashing

def predictCatboostClass(target, X_data, fStub, mO):
  # load model
  **modelC1 = CatBoostClassifier()**
  modelC1.load_model(PATH + 'runtime/models/'+target+'.'+fStub+'.catboost_class')
  predictions_probs = modelC1.predict_proba(Pool(X_data, cat_features=CATEGORICAL))

Is it possible that load_model() post 0.15.2 is not fully re-initialising the CatBoostClassifier(). FYI I think the same is the case for CatBoostRegressor()

Best
Alex

**Comment by agracian** [comment]
Basically, it appears that load_model() does not fully reset and current model from version 0.16.0 onwards?

**Comment by kizill** [comment]
Fixed, thank you for your help! Will be in minor release in the beginning of next week 😃
