### ISSUE TITLE
Can't parse params file when saving a model

### ISSUE THREAD

**Issue by ibuda** [catboost/catboost#998]
Problem: can't parse params file
catboost version: 0.17.1
Operating System: Ubuntu 19.04
CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

Steps to reproduce the error:
1. Train a couple of catboost classifiers (`models` list), and based on those, create another one using `sum_models` function, i.e. `model = sum_models(models, weights=[1.0/len(models)] * len(models))`
2. Save it to a file using the default cbm format, i.e. `model.save_model('tmp_model')`
3. Load the model, i.e. `model = CatBoostClassifier().load_model('tmp_model')`
4. Try saving model, i.e. `model.save_model('tmp_model', format='json')`, you get the following error:
```
CatBoostError                             Traceback (most recent call last)
<ipython-input-12-2759bdc89692> in <module>
----> 1 model.save_model('tmp_model', format='json')

~/prb/anaconda3/lib/python3.7/site-packages/catboost/core.py in save_model(self, fname, format, export_parameters, pool)
   2346                 cat_features=self._get_cat_feature_indices() if not isinstance(pool, FeaturesData) else None
   2347             )
-> 2348         self._save_model(fname, format, export_parameters, pool)
   2349 
   2350     def load_model(self, fname, format='catboost'):

~/prb/anaconda3/lib/python3.7/site-packages/catboost/core.py in _save_model(self, output_file, format, export_parameters, pool)
   1180                 params_string = json.dumps(export_parameters, cls=_NumpyAwareEncoder)
   1181 
-> 1182             self._object._save_model(output_file, format, params_string, pool)
   1183 
   1184     def _load_model(self, model_file, format):

_catboost.pyx in _catboost._CatBoost._save_model()

_catboost.pyx in _catboost._CatBoost._save_model()

CatBoostError: catboost/libs/model/model_export/json_model_helpers.cpp:468: can't parse params file
```

**Comment by annaveronika** [comment]
Sorry for a long answer. And thanks for reporting this problem. We'll look into it!

**Comment by annaveronika** [comment]
The code of the fix is on github now and will be out on pypi in the next minor release 0.18.1
